### ISSUE TITLE
Use own package name

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#1]
Bromite is currently using Chromium's package name, it should use its own so that users can install it side by side with regular Chromium.

**Comment by andrin55** [comment]
Are you sure about that? I prefer it to be chromium, so I can apply my substratum theme to it.

**Comment by csagan5** [comment]
It is currently still Chromium's package name (mostly because the patch to apply is troublesome to maintain), but technically it's against common practice since one should not "abuse" the package name of another android app.

People also can't install the two side by side currently; would it be too difficult to have substratum support Bromite? If it's a bit more widespread in use, I think there wouldn't be an issue from the authors?

**Comment by andrin55** [comment]
> would it be too difficult to have substratum support Bromite?

Nope it wouldn't, but not many theme authors would support it since Bromite is relatively unknown yet.

**Comment by Atavic** [comment]
Package name should definitely be unique!

**Comment by csagan5** [comment]
Fixed in 63.0.3239.15

**Comment by westsibe** [comment]
Bromite Browser without Google Sync (with new package name) became useless

**Comment by Primokorn** [comment]
@westsibe It's actually a good thing to reduce the dependency to Google.
Bromite is a really nice project for users that care about their privacy. Just use Chrome if you just want to sync your Google bookmarks.

**Comment by westsibe** [comment]
This is a truncation of the capabilities of Bromite Browser.

**Comment by Atavic** [comment]
1. Open another issue

2. Bromite - Take back your browser - is Chromium plus some patches for... enhanced privacy.

**Comment by csagan5** [comment]
@westsibe you are ignorant, in the sense that you ignore how things work. Go read here and make yourself informed: https://www.chromium.org/developers/how-tos/api-keys

In short: **regardless of the package name, it is not possible to use Google Sync API (and others) if you do not work inside Google and have their API keys**

You can call it my little pony, or Chrome, or whatever. This is not the reason why Google proprietary APIs  do not work. The reason is that Google revoked them.

**Comment by westsibe** [comment]
I changed the name of the package to org.chromium.chrome and then Google Sync is worked (mail.google.com, Bookmarks, etc), but then the upload of files to sites was *broken*. –It's my tests. I used APK Editor for Android for editing of package name.

**Comment by csagan5** [comment]
@westsibe I will try again changing the package name; all other developers also told me it would not work and it did not work by my tests. If it really helps, I apologize in advance and will change this. I will test it with the device simulator and on a real phone.

By the way, such a simple hack might soon be found and fixed; I think it works only in certain conditions (pre-existing keys stored for the Chrome app, that get used by Bromite).

**Comment by westsibe** [comment]
For more info: APK Edidor for Android ver.1.6.5 (signature: test-key), Android 4.4.2 Stock, MTK6582.

**Comment by csagan5** [comment]
It does not work. I will close it; if anybody else cares to test, feel free. I do not think the Google devs are so stupid to check the package name. They use API keys and some other method to check which browser (Chrome) is allowed to use their proprietary APIs.
