### ISSUE TITLE
Adblock toggle bug

### ISSUE THREAD

**Issue by drxgxn** [bromite/bromite#100]
Webpages keeps on showing error "Requests to the server have been blocked by an extention."
After some trial and error, I found out it is the adblock toggle which is causing the problem. I have to toggle it off every time to load a webpage.
![screenshot_20180731-211952__01](https://user-images.githubusercontent.com/26479749/43483132-58bef88e-9528-11e8-968f-ecb8c432da9c.jpg)

**Comment by drxgxn** [comment]
I'm on One Plus 3 OxygenOS 5.0.4 Oreo 8.0.0

**Comment by csagan5** [comment]
I assume you installed a version which had botched filters; I re-uploaded the correct version shortly after so if you re-download it and install it the problem is gone.

**Comment by drxgxn** [comment]
:+1:
