### ISSUE TITLE
Videos not playing

### ISSUE THREAD

**Issue by XxNoobMaster69xX** [bromite/bromite#1001]
### Bromite version

Version: `89.0.4389.78`
Arch: arm64`
Android version: 11
Device model: SM-G985F

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Allow ads for the site; is the bug caused by the adblocker?

No

### Is the bug a crash?

No

### Describe the bug

Videos on websites loads and sound plays as normal. But the screen stays blank white.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Any videos in website

### Screenshots

![Screenshot_20210314-012835_Bromite.jpg](https://user-images.githubusercontent.com/78025271/111038564-b00a6780-8464-11eb-81fa-c5077413e6da.jpg)![Screenshot_20210314-012844_Bromite.jpg](https://user-images.githubusercontent.com/78025271/111038573-b6004880-8464-11eb-818c-bcaef458082f.jpg)

**Comment by csagan5** [comment]
> 1. Any videos in website

Which URLs?

**Comment by XxNoobMaster69xX** [comment]
> > 1. Any videos in website
> 
> Which URLs?

https://www.disney.my/

Rest are adult site URLs which I'm pretty obvious u don't need.

I have tried with adblock off, re install. Didn't work.

**Comment by csagan5** [comment]
Cannot reproduce this issue; try seeing if there is anything relevant in the console via [remote debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging).

**Comment by csagan5** [comment]
Duplicate of #1005

**Comment by Nemris** [comment]
@csagan5 Not even Giphy GIFs appear to load - check the bottom of https://www.deviantart.com/dmsalesman and see if they work for you.
