### ISSUE TITLE
Bug in Add-a-flag-to-allow-screenshots-in-Incognito-mode.patch

### ISSUE THREAD

**Issue by uazo** [bromite/bromite#1006]
This line is incorrect:

https://github.com/bromite/bromite/blob/fb90e00324d415d1af35d2b0651ad76a25cb6354/build/patches/Add-a-flag-to-allow-screenshots-in-Incognito-mode.patch#L23-L28

line 24 must be moved one line above

**Comment by csagan5** [comment]
Fixed in `89.0.4389.100`.
