### ISSUE TITLE
DeviantArt chat not loading

### ISSUE THREAD

**Issue by Nemris** [bromite/bromite#1011]
### Bromite version

Version: `89.0.4389.100`
Arch: `arm64`
Android version: `10.0`
Device model: `SM-A405FN`

### Flags

These are the flags changed under `chrome://flags`:
```
    enable-vulkan
    tabbed-app-overflow-menu-icons
    tabbed-app-overflow-menu-regroup
    cct-incognito
    darken-websites-checkbox-in-themes-setting
    incognito-screenshot
```

### Is this bug about the SystemWebView?
No.

### Is the bug reproducible with latest version?
Yes.

### Can the bug be reproduced with corresponding Chromium version?
No.

### Allow ads for the site; is the bug caused by the adblocker?
No.

### Describe the bug
When logged in to https://www.deviantart.com, touching the chat icon causes the chat to never load, instead hanging on either a partially black screen or a permanent loading animation with placeholders in place of the chat interface.

The bug occurs both on normal tabs, as well as incognito ones.

### Steps to reproduce the bug
First, make sure to be logged in to https://www.deviantart.com. Double-check that JavaScript is allowed for the site.

Steps to reproduce the bug:
1. Go to https://www.deviantart.com;
2. Click on the icon resembling a chat bubble, near the top right corner of the screen;
3. Wait for the loading animation to begin;
4. Notice the chat never completes loading.

### Expected behavior
The chat window should load.

**Comment by csagan5** [comment]
Please use [remote debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging) to see if there are errors in the Javascript console.

After that you can try disabling one or more of `#fingerprinting-canvas-image-data-noise`, `#fingerprinting-client-rects-noise` and `#fingerprinting-canvas-measuretext-noise` to see if the chat loads.

**Comment by Nemris** [comment]
There are around 6 errors revolving around the 500 status code returned by frog.wix.com, but it happens under Chromium as well.
Moreover, disabling the three flags doesn't solve the issue.

Possibly worth mentioning is that logging under Chromium mentions a "policy violation" as a warning. I can check for more details, if you think it's important.

**Comment by csagan5** [comment]
It could be due to #836 or #985. You need to look into differences between the two; what is the policy violation reported in Chromium? Is there an error in Bromite for the same request?

**Comment by Nemris** [comment]
The policy violation reported in the Chromium log reads

```
howler.js:2500 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
```

Curiously enough, the Bromite log also contains a 404'd request to google-analytics.com immediately at the beginning, which is missing from the Chromium log.

In case you think it's useful, I can likely attach the logs here.

**Comment by csagan5** [comment]
Have you tested this with the adblocker disabled or enabled?

**Comment by Nemris** [comment]
I did - and toggling the adblocker didn't solve the issue. To be sure, I also toggled the systemwide adblocker and checked again, but the issue persisted.

Disabling the three flags you suggested, restarting Bromite thrice and retrying changed nothing, either.

**Comment by csagan5** [comment]
What are the requests happening on Chromium that do not happen on Bromite, and viceversa?

**Comment by Nemris** [comment]
I'll research the DevTools some more and follow up as soon as I have more data.

**Comment by csagan5** [comment]
@uazo do you know of a way to disable some of the partitioning features to make a test? There is no flag for them; see #836 or #985.

**Comment by Nemris** [comment]
By the way - I tried to disable `#site-isolation-trial-opt-out` and check if it'd make a difference, but it didn't seem to help.

**Comment by uazo** [comment]
> do you know of a way to disable some of the partitioning features to make a test? 

I seem to remember that all features can be disabled and enabled from the command line, which however is active only in debug.

unfortunately I have the vm occupied by running tests, then I check.
For the command line, here an example

`echo "--enable-logging --v=0" > /data/local/tmp/chrome-command-line`

**Comment by csagan5** [comment]
> I seem to remember that all features can be disabled and enabled from the command line, which however is active only in debug.

So not working for our builds?

**Comment by uazo** [comment]
no, see https://www.chromium.org/developers/how-tos/run-chromium-with-flags

`For production build on a non-rooted device, you need to enable "Enable command line on non-rooted devices" in chrome://flags, then set command line in /data/local/tmp/chrome-command-line. When doing that, mind that the first command line item should be a "_" (underscore) followed by the ones you actually need. Finally, manually restart Chrome ("Relaunch" from chrome://flags page might no be enough to trigger reading this file). See https://crbug.com/784947.`

i'm looking in the code how it works

**Comment by csagan5** [comment]
Ok, thanks; I suspected that too. We could add flags for these partition isolation features but they are eventually going to be enabled by upstream and they are important as a security feature.

**Comment by Nemris** [comment]
From the logged requests, it would appear that the credential validation process triggered by some JavaScript file proceeded on Chromium while getting stuck on Bromite. The same requests reported status 200 on both browsers, with both adblocking and third-party cookies either enabled or disabled.

**Comment by Nemris** [comment]
Further research revealed that the validation process uses Google's Identity Toolkit, handled by a minified DeviantArt JS file.

Execution of this file appears to halt after the credential verification procedure succeeds - no clue why.

**Comment by Nemris** [comment]
It would seem that there's a failing WebSocket handshake under Bromite. While on Chromium it succeeds with status 101, on Bromite it hangs first, only to fail with status 504 after a bit.

**Comment by csagan5** [comment]
`504` is a gateway timeout; is there no other security problem reported when using Bromite?

**Comment by Nemris** [comment]
I didn't see anything - even the failing handshake isn't guaranteed to pop up. Most of the times, progress halts immediately after Identity Toolkit replies with the data.

**Comment by csagan5** [comment]
It needs further investigation; however I cannot commit to this. If someone finds which Bromite feature is responsible for the problem, and there is no ill behaviour from the site, we can think of a solution.
