### ISSUE TITLE
Bookmark Menu Need Some Tweaks 

### ISSUE THREAD

**Issue by oldphones68** [bromite/bromite#1015]
Hello! 
I was a user of Opera browser for 10+ years. After that I swithed to Bromite.

Bromite's privacy statements attract me warmly.
I love this browser.

But, just a thing is somehow detering me to use it in a more user friendly way.

When we use bookmarks, imagine a situation:

1. User have ~400++ bookmarks
2. They are arranged using some folders
3. Imagine, the 26th folder has 100 bookmarks
4. The user is in that folder AND opened a bookmark in a new tab (let, that was the 75th bookmark in that folder)
5. Then after closing the tab s/he returned to the browser's homepage and go to the bookmark menu again

NOW S/HE HAVE TO SCROLL THE BOOKMARKS MENU UNTIL HE REACHES THE 26TH FOLDER AND THEN 75TH BOOKMARK.

I mentioned I have falllen love with Bromite and rest features are joss actually.

BUT, this ONE think is making the experience difficult and making me sad.

Can you tweaks this issue, please?

By the way, I lost 2300+ bookmarks saved in Opera and came to Bromite with a broken heart. Do NOT want to switch again.

Thanks and regards!
With love!

**Comment by csagan5** [comment]
@oldphones68 please use the issue template; this feature request does not seem related to privacy.
