### ISSUE TITLE
Do not resolve suffix domain of onion and i2p when use secure DNS

### ISSUE THREAD

**Issue by srxr** [bromite/bromite#1024]
### Is your feature request related to privacy?
No.

### Is there a patch available for this feature somewhere?
No.

### Describe the solution you would like
Exclude specific domains for DNS resolve if enabled `Use secure DNS`, e.g. `onion` and `i2p`.

**Comment by csagan5** [comment]
This is probably related to privacy but we cannot make the domains that are resolved via secure DNS or a regular DNS customizable; if we did this then someone would ask to resolve some domains with a certain DNS etc

Bromite (or Chromium) do not have any concept of special TLDs.

The best way to solve this is to run a DNS proxy locally on the phone and do this distinction there in its customization.
