### ISSUE TITLE
Let the User Agent Client Hints show the same values as the Customized User Agent String.

### ISSUE THREAD

**Issue by bat999** [bromite/bromite#1033]
### Is your feature request related to privacy?
Yes (It concerns the Customized User Agent String which helps privacy)

### Is there a patch available for this feature somewhere?
Not that I know of.

### Describe the solution you would like
We can use "Customize User Agent" with Bromite.
If we have a Customized User Agent String for a browser that supports User Agent Client Hints then let them show the same values.

If we have a Customized User Agent String like this...
Mozilla/5.0 (Linux; Android 19; Generic) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.1234.56/Mobile Safari/537.36

Expect to see Client Hints like this...
Sec-CH-UA: "Chromium";v="99", ";Not A Brand";v="99"
Sec-CH-UA-Mobile: ?1
Sec-CH-UA-Full-Version: "99.0.1234.56"
Sec-CH-UA-Platform: "Android"
Sec-CH-UA-Platform-Version: "19"
Sec-CH-UA-Arch:
Sec-CH-UA-Model: "Generic"

As it is now the Client Hints show like this...
Sec-CH-UA:
Sec-CH-UA-Mobile: ?0

There is a demo here --> https://user-agent-client-hints.glitch.me/
So far I think only Chromium-based browsers support User Agent Client Hints.
They are still behind the flag #enable-experimental-web-platform-features

### Describe alternatives you have considered
At present with version 89 we can disable the User Agent Client HInts with the flag.
But probably they will be enabled by default in later versions.

**Comment by csagan5** [comment]
I doubt that this can be done. We are not going to ship a database of user agents in Bromite.

**Comment by bat999** [comment]
> ...We are not going to ship a database of user agents in Bromite.

Yes, I see what you mean.
I thought it might be "simple" to parse the Customized String and grep it for words such as Linux and Android and Chrome and Mobile.
But it might say Brave or Edge or Opera or even Bromite instead of Chrome.
And it would be difficult to pick out a device model from among the cruft.

So it's not such a good idea after all.

One thing though...
If we send out "**Sec-CH-UA-Mobile: ?0**" it says that we don't want a small-screen web page.
Even though we might have used Mobile in the Customized String.

Maybe we should try to kill all the User Agent Client Hints when using a Customized String.
Same effect as with #enable-experimental-web-platform-features -> **Disabled**.

I will close the thread.

**Comment by csagan5** [comment]
> If we send out "**Sec-CH-UA-Mobile: ?0**" it says that we don't want a small-screen web page.
> Even though we might have used **Mobile** in the Customized String.
> 
> Maybe we should try to kill all the User Agent Client Hints when using a Customized String.
> Same effect as with #enable-experimental-web-platform-features -> **Disabled**.

As soon as most browsers freeze the UA string it will become more clear what is the future of the custom UA feature in Bromite.
