### ISSUE TITLE
Align filters.dat to uBlock Origin's default lists (AKA: Easy mode) to ensure site compatibility/security/privacy

### ISSUE THREAD

**Issue by Pentaphon** [bromite/bromite#1042]
### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

We should only use the default filters that uBlock Origin does since that project has a very large community that is very security and privacy conscious. In other words, we should fully align filters.dat with: 

https://github.com/gorhill/uBlock/wiki/Blocking-mode:-easy-mode

> 3rd-party filters pane:

    All of uBlock Origin's custom filter lists: checked
    EasyList: checked
    Peter Lowe’s Ad server list: checked
    EasyPrivacy: checked
    Online Malicious URL Blocklist‎: checked
    All other filter lists: unchecked

--------------

We do this by:

1) Remove old Brave filters from filters.dat that haven't been updated since 2018 from

https://github.com/bromite/filters/blob/master/lists.txt

Which are: 

https://raw.githubusercontent.com/brave/adblock-lists/master/brave-unbreak.txt
https://raw.githubusercontent.com/brave/adblock-lists/master/coin-miners.txt

As you can see from reading them, those 2 lists are old. We should use what uBlock Origin uses by default as that is an actively maintained community project with a great emphasis on privacy and security, while Brave is more concerned with their own BAT coin and their own filterlist. 

2) Add the 3 default uBlock Origin lists that we don't have, which are: 

https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt
https://raw.githubusercontent.com/curbengh/urlhaus-filter/master/urlhaus-filter.txt

3) Reconsider this list (or just remove?) since uBlock Origin does not include it by default. 

https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt

### Describe alternatives you have considered

None. I just think mirroring uBlock Origin's default filters would be best for security and privacy, as well as site compatibility.

**Comment by csagan5** [comment]
> 1. Remove old Brave filters from filters.dat that haven't been updated since 2018 [...]
> 
> https://raw.githubusercontent.com/brave/adblock-lists/master/brave-unbreak.txt
> https://raw.githubusercontent.com/brave/adblock-lists/master/coin-miners.txt

They have been updated 10 months ago.

> I just think mirroring uBlock Origin's default filters would be best for security and privacy, as well as site compatibility.

The current lists have been tailored after many issues reported and fixed.

**Comment by csagan5** [comment]
I think in (2) and (3) you report the wrong URLs for the privacy list.

**Comment by Pentaphon** [comment]
> 
> 
> > 1. Remove old Brave filters from filters.dat that haven't been updated since 2018 [...]
> > 
> > https://raw.githubusercontent.com/brave/adblock-lists/master/brave-unbreak.txt
> > https://raw.githubusercontent.com/brave/adblock-lists/master/coin-miners.txt
> 
> They have been updated 10 months ago.

coin-miners.txt says: 

! Title: NoCoin Filter List
! Expires: 2 days (update frequency)
! Version: 44
! Last modified: 19 Mar 2018

And we already have the uBlock resource filter. 

> > I just think mirroring uBlock Origin's default filters would be best for security and privacy, as well as site compatibility.
> 
> The current lists have been tailored after many issues reported and fixed.

Perhaps, but uBlock Origin's community is MUCH bigger than ours so their defaults are even more widely reported and received more fixes over time. For the sake of ensuring privacy/security/site compatibility, I think it would be wise to defer to their default config. 

> I think in (2) and (3) you report the wrong URLs for the privacy list.

You're right. I should have linked the raw link instead. Regardless, we should include those lists, and adopt uBlock Origin's easy mode. 

We are also missing the Online Malicious URL Blocklist, which is a default list on uBlock Origin's easy mode. 

https://gitlab.com/curben/urlhaus-filter#urlhaus-malicious-url-blocklist

Just to be as safe as uBlock Origin users, filters.dat should mirror Easy Mode. 

https://github.com/gorhill/uBlock/wiki/Blocking-mode:-easy-mode

**Comment by csagan5** [comment]
> coin-miners.txt says:

The git history shows that other changes have happened, perhaps they forgot to update the `Last Modified`.

> We are also missing the Online Malicious URL Blocklist, which is a default list on uBlock Origin's easy mode.
> 
> https://gitlab.com/curben/urlhaus-filter#urlhaus-malicious-url-blocklist

I will check this.

In the currently released version the badware list has been added and the 2 brave lists have been removed.

**Comment by Pentaphon** [comment]
> In the currently released version the badware list has been added and the 2 brave lists have been removed.

Thanks. I'm already noticing an improvement in a couple of very ad-heavy sites that took ages to load with Bromite before but loaded fine with Firefox + uBlock Origin Easy Mode so this is definitely helping so far. Not sure if it was the removal of the Brave lists or the addition of the badware list. Once Bromite follows the exact same Easy Mode default that uBlock Origin has, I suspect site compatibility will improve even further in the long run and it will also block more malicious sites.

**Comment by csagan5** [comment]
Hardly so, because the Chromium subresource filter engine does not support CSS adblocking, so the comparison can never be 1:1.

Also other features are missing, like script replacement.

**Comment by Pentaphon** [comment]
> Hardly so, because the Chromium subresource filter engine does not support CSS adblocking, so the comparison can never be 1:1.
> 
> Also other features are missing, like script replacement.

That may be, but I'm seeing ad-heavy sites like torrentgalaxy.to load in a few seconds on Bromite with the new filterlist whereas before with the old filters they would lock up and take forever to fill the Bromite site loading progress bar. There's definitely an improvement so far. Thanks for working on my request. I really think Easy Mode is the right direction to take.

**Comment by Pentaphon** [comment]
> In the currently released version the badware list has been added and the 2 brave lists have been removed.

Here's another reason to add the uBlock Origin Privacy list: It will be updated to block FLOC until uBlock Origin can find a better solution. 

https://github.com/uBlockOrigin/uBlock-issues/issues/1553#issuecomment-817146265

**Comment by csagan5** [comment]
> Here's another reason to add the uBlock Origin Privacy list: It will be updated to block Google's FLOC until uBlock Origin can find a better solution.
> 
> [uBlockOrigin/uBlock-issues#1553 (comment)](https://github.com/uBlockOrigin/uBlock-issues/issues/1553#issuecomment-817146265)

That is not a valid reason. There is no FLOC in Bromite and that type of filter does not work here anyways.



> That may be, but I'm seeing ad-heavy sites like torrentgalaxy.to load in a few seconds on Bromite with the new filterlist whereas before with the old filters they would lock up and take forever to fill the Bromite site loading progress bar. There's definitely an improvement so far. Thanks for working on my request. I really think Easy Mode is the right direction to take.

Like everything in life, it needs proof or it cannot and will be used to decide on this.

**Comment by Pentaphon** [comment]
> That is not a valid reason. There is no FLOC in Bromite and that type of filter does not work here anyways

Fair enough. I will leave this to your judgment. I wasn't aware of those facts. Looking forward to seeing how filterlist.dat looks when this is closed.

**Comment by csagan5** [comment]
The urlhaus list is unrelated to blocking ads, and only a minority are relevant for mobile. It will not be included.

**Comment by Pentaphon** [comment]
> The urlhaus list is unrelated to blocking ads, and only a minority are relevant for mobile. It will not be included.

What about the uBlock Origin Privacy.txt list? That wasn't added to our .dat file. I understand how malware is not relevant to Bromite but uBlock Origin's included privacy list surely would benefit Bromite, since you do ask in the issue template whether the issue is related to privacy.

**Comment by csagan5** [comment]
Yes, that one will be added.
