### ISSUE TITLE
HTTP/3 broken - h3-29

### ISSUE THREAD

**Issue by FireMasterK** [bromite/bromite#1046]
### Bromite version

Version: 89.0.4389.117
Arch: `arm64`
Android version: 10
Device model: Mi Pad 4 Plus / clover

### Flags

These are the flags changed under `chrome://flags`:

Experimental Quic is not enabled, it is expected to work only when default is selected 

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?
No, it works fine there

### Allow ads for the site; is the bug caused by the adblocker?
No

### Describe the bug

The IETF draft versions of quic do not work. 

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to https://www.cloudflare.com/
2. Go to https://www.cloudflare.com/cdn-cgi/trace
3. It will show http/2

### Expected behavior

HTTP/3 to work, like in Brave and Chromium

**Comment by csagan5** [comment]
I cannot reproduce your test; it uses HTTP/2 for all browsers, even with the Quic flag explicitly enabled.

**Comment by FireMasterK** [comment]
Did you have the Quic flag set to default? Keeping it set on enabled forces only the GQUIC versions only iirc.

**Comment by FireMasterK** [comment]
You will also need to open both URLs in the same tab too.

**Comment by csagan5** [comment]
By going to www.cloudflare.com and then to https://www.cloudflare.com/cdn-cgi/trace I can see HTTP/3 on both Bromite and Chrome, without any QUIC flag change; on Chromium it shows HTTP/2.

Perhaps it is decided also by server side.

**Comment by FireMasterK** [comment]
Turns out the update from 2 days ago fixes this, thank you!
