### ISSUE TITLE
Having two different search engine for incognito mode and normal mode

### ISSUE THREAD

**Issue by Thewisem** [bromite/bromite#1048]
### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

I would like to request for an option to have different search engine while incognito and different search engine while normal

### Describe alternatives you have considered

An icon at the tip of search bar which when pressed gives the option to change search engine

**Comment by anppraveen** [comment]
This is part of brave browser. 
For reference u could visit https://github.com/brave/brave-browser/issues/61

**Comment by Thewisem** [comment]
Oh dame. Sorry didn't know that. I don't use that browser. I just thought of this issue while using bromite

**Comment by csagan5** [comment]
This would require too many changes for the added benefit.
