### ISSUE TITLE
Bookmarks import at Bromite

### ISSUE THREAD

**Issue by galaktiker** [bromite/bromite#105]
Version: 68
Arch: arm64

Hi! Could you please add bookmarks import (from html file) to Bromite. I know about https://forum.xda-developers.com/showpost.php?p=73048109&postcount=746 method. But it's complicated, incovenient and annoying. 

Ok, sync is impossible because of Google. But importing bookmarks is the basic function of any browser!

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear here on Github via mobile; I had always been assuming that the issue template was being ignored for opened issues like this, sorry for that.

(Issues not following the template are considered invalid)

This functionality has already been implemented.
