### ISSUE TITLE
Close all tabs on exit

### ISSUE THREAD

**Issue by casta** [bromite/bromite#106]
---
name: close all tabs on exit
about: allow to dismiss all tabs on exit to start fresh and not resend requests on old sites.

---

**Is your feature request related to privacy?**
I think it is.

**Is there a patch available for this feature somewhere?**
Brave has an option to do that, but I could not find the relevant part on their repository

**Describe the solution you'd like**
Just like Brave is perfect: having an option in privacy panel that allow to enable to close all tabs on exit. With this enabled, when you exit Bromite (slide app in android tasks or click exit in menu), all tabs are effectively closed, when you restart Bromite, it start fresh on the NTP without tabs opened.

**Describe alternatives you've considered**
I did not find an alternative with current Bromite: closing all tabs one by one is painful when you have many tabs opened, accessing the menu "close all tabs" takes too many clicks IMHO.

**Comment by Primokorn** [comment]
FYI
https://forum.xda-developers.com/showpost.php?p=77228314&postcount=1125

https://forum.xda-developers.com/showpost.php?p=77307321&postcount=1168

**Comment by csagan5** [comment]
> Is your feature request related to privacy?
> I think it is.

@casta  I assume you mean that sending requests to the tabs when you re-open the browser is a privacy concern; is this happening? As far as I know only when you activate the tab a request is made to refresh it. 

I have recently added an option to hide all icons in the new tab page which is similar in scope to this one.

The feature request you ask is instead equivalent to the "Restore browser session" that regular desktop Chromium already has.

"Close all tabs" takes two clicks to activate.

> FYI
> https://forum.xda-developers.com/showpost.php?p=77228314&postcount=1125
> 
> https://forum.xda-developers.com/showpost.php?p=77307321&postcount=1168

`<offtopic>`
@Primokorn I think using the Github issue templates is best for a project like this (and for my involvement), the submitter here has used the template correctly so I try to engage in a positive discussion. I am sorry about my recent replies on XDA and about XDA itself, but it does not work for me.`</offtopic>`

**Comment by casta** [comment]
Yes indeed. At least the current tab is reloaded. So the current tab can track your moves by IP, switching to WiFi, crossing a border (roaming)...

Yes it's adding an option to disable "restore session".  Since Brave added it, it should not be a very big work (?), but since I'm not familiar with their source tree, I could not locate the correct part. But I think it definitively worth it.

The option you added is fine too, by two aspects : stopping non-user triggered external requests, and not exposing topmost visited websites.

By the way closing all tabs in chromium has UX shortcomings IMHO. Especially on phones with big screen (controls at the top of screen). This does not help to use it. Using the standard android way (task menu + swype) is far more ergonomic and fast. That's why Google is experiencing bar at the bottom of the screen.

Thanks !!

**Comment by condor0765** [comment]
> https://forum.xda-developers.com/showpost.php?p=77228314&postcount=1125
Any reasoning for this. (i.e.)
Will there be a feature to automatically erase history and open tabs while we exit the browser?

I would very much like this.

**Comment by csagan5** [comment]
> Since Brave added it, it should not be a very big work 

Added it on the Android version of their browser? Can you tell or show how to do that? It is not "a big work" only if it is a maintained patch against latest versions.

**Comment by casta** [comment]
Yes on the last Brave Android version, they added an entry in the privacy menu for that (4th entry). Currently I have limited time, but starting on 2018-08-27 I will have more time to dig into their sources to find the corresponding patch.

Le 16 août 2018 19:45:53 GMT+02:00, Carl <notifications@github.com> a écrit :
>> Since Brave added it, it should not be a very big work 
>
>Added it on the Android version of their browser? Can you tell or show
>how to do that? It is not "a big work" only if it is a maintained patch
>against latest versions.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/bromite/bromite/issues/106#issuecomment-413628571

-- 
    Guillaume Castagnino
        casta@xwing.info / guillaume@castagnino.org

**Comment by casta** [comment]
Here is their corresponding translation string on tree: https://github.com/brave/browser-android-tabs/search?p=1&q=7459000603787995422&type=&utf8=✓
But I'm new to this, I do not know how to go to the corresponding code.

**Comment by csagan5** [comment]
@casta the feature is here: https://github.com/brave/browser-android-tabs/pull/605

and indeed it uses the pre-existing `ChromeSwitches.NO_RESTORE_STATE`, so this is proof that the corresponding desktop feature of Chromium works also on the Android version.

We do not have in Bromite a privacy preferences settings section so I might add a flag for the time being.

Regarding this feature being about privacy: I think it's more about convenience than privacy, but as I said before since I added an option to not show NTP tiles this is more or less in the same vein.

**Comment by csagan5** [comment]
The privacy preferences section used there is just the regular Chromium one, it is the translation strings that have been moved. I might be able to solve that easily.

**Comment by csagan5** [comment]
Fixed in 68.0.3440.121

**Comment by casta** [comment]
This is great news thank’s
