### ISSUE TITLE
Flag To Disable HTTP Requests

### ISSUE THREAD

**Issue by AzureB1te** [bromite/bromite#1068]
It's a feature request

 It's neither of tham. 

### Is your feature request related to privacy?

 It is a privacy/security enchancement. 

### Is there a patch available for this feature somewhere?

 Nowhere that I'm aware of

### Describe the solution you would like

 I would like a flag (or setting) that completely disables unencrypted HTTP requests. I'm not asking for HTTPS Everywhere, I have read the FAQ. I'm simply asking to block unencryped sites. 

### Describe alternatives you have considered

 
Extension support would solve it, altough, that's not possible, as far as my understanding goes. Brave (Android)
has a similar feature, built into it's "Shields", so implementing that might be an option, as of you've already used some of brave's patches, since they're being open source, altough, I don't quite undertand the licensing system, so It probabily isn't as easy as it seems.

**Comment by uazo** [comment]
if acting on this

https://source.chromium.org/chromium/chromium/src/+/master:net/android/java/src/org/chromium/net/AndroidNetworkLibrary.java;l=372?q=androidnetwork

you completely deactivated the https connection, the patch would be simple.
you just need to figure out how to pass a chrome flag to the net layer, when I look at this https://github.com/bromite/bromite/issues/921 I throw an eye

**Comment by uazo** [comment]
![image](https://user-images.githubusercontent.com/29201891/115542604-b8926100-a2a0-11eb-87a9-fdc985c3fd91.png)

the problem with that flag correctly disable http connection, but that there is no automatic transition from http to https
so writing www.google.com, the browser reads it as **http**://www.google.com and does not ask any redirect from server, and an CLEARTEXT_NOT_PERMITTED error is shown to user.

![image](https://user-images.githubusercontent.com/29201891/115545908-ac100780-a2a4-11eb-9f4f-2af22532733f.png)
with this change, upgrade to https is always done (even when wrong :)
so **http**://www.columbia.edu/~fdc/sample.html exists, but bromite will land to **https**://www.columbia.edu/~fdc/sample.html (that not exists), and the user see:
![image](https://user-images.githubusercontent.com/29201891/115546416-4c662c00-a2a5-11eb-89bf-e62eb6383bd5.png)


@csagan5 what do you think about it?

**Comment by csagan5** [comment]
> with this change, upgrade to https is always done (even when wrong :)

This is not what the user asked. We will not implement HTTPS Everywhere in Bromite.

We can have a flag to always disable HTTP connections, but that's it.

**Comment by csagan5** [comment]
Fixed in `90.0.4430.92`.
