### ISSUE TITLE
Add anti-anti-adblock like Nano Defender

### ISSUE THREAD

**Issue by DragoCubed** [bromite/bromite#107]
**Is your feature request related to privacy?**
Only privacy-related feature requests are considered.
Very much so
**Is there a patch available for this feature somewhere?**
...
https://jspenguin2017.github.io/uBlockProtector/

**Describe the solution you'd like**
I'm not really sure about this
**Describe alternatives you've considered**
I'm not a developer so I don't know about implementing this.

**Comment by antonin-lebrard** [comment]
It's actually related to these issues: #2 and #33 
The patch you are refering to, is a web extensions that uses javascript to remove DOM elements and non-trivial code to block transparently anti-adblocker features (without the website knowing).

You can see the adblock rules of Bromite in this file: https://raw.githubusercontent.com/bromite/bromite/master/filters/adblock_entries.h

And all privacy patches done in the chromium C++ code https://github.com/bromite/bromite/tree/master/patches

And you will see that the patch and rules are targetting the browser code, and consists of "only" domain-based rules that Bromite will block, and blocking browser features that websites can access through a javascript API but no changes in website content is made (and so no javascript changes).

The progress of such features will be tracked on #2 I suppose

**Comment by csagan5** [comment]
@DragoCubed the adblock engine of Bromite does not support DOM blocking rules and I am not planning to swap its engine for a more advanced one, sorry. The wiki contains a description of other adblock engines.
