### ISSUE TITLE
Restoring old tab view

### ISSUE THREAD

**Issue by Telestrin** [bromite/bromite#1079]
Have you read the README? 
https://github.com/bromite/bromite/blob/master/README.md
*YES*

Have you searched the issue tracker? https://github.com/bromite/bromite/issues
*YES*

Are you sure this is not a Chromium bug? You have to test with Chromium before submitting a bug.
*YES*

Are you using the latest version of Bromite?
*YES*

### Bromite version

Version: 90.0.4430.74
Arch: arm
Android version: 10.0
Device model: SM-G960U

### Flags
*NONE*

### Is this bug about the SystemWebView?
*No*

### Is the bug reproducible with latest version?
*YES*

### Can the bug be reproduced with corresponding Chromium version?
*NO*

### Is this bug happening in an incognito tab?
*YES*

### Allow ads for the site; is the bug caused by the adblocker?
 *NO*

### Is the bug a crash?

*NO*

### Describe the bug

[I don't know if this is the right place to report this since I do not know if it is an error or mistake, or an intended feature, and I do not want to put it in the future bequest since it is not strictly speaking privacy-related]*

Hello. I would ask that you kindly restore the previous tab view, where you could scroll through multiple different pages, instead of the grid that is in effect now. If there is some reason why this other change was made and people like it (I find it to be extremely unpleasant), could you please at least give the option to choose which tab you use. Thank you.

### Steps to reproduce the bug

*Use browser*

### Expected behavior

*ibid*

### Screenshots

*ibid*

**Comment by n-buna404** [comment]
This is intended feature by chromium that is enabled by default in 90.XXX
How to change it please refer to https://github.com/bromite/bromite/discussions/1056

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> _NO_

Are you sure?

**Comment by oldphones68** [comment]
> > ### Can the bug be reproduced with corresponding Chromium version?
> > _NO_
> 
> Are you sure?

It is also disabled on the upstream, AFAIK.

@csagan5

**Comment by csagan5** [comment]
It is not.
