### ISSUE TITLE
Videos should not pause when tab looses focus

### ISSUE THREAD

**Issue by DragoCubed** [bromite/bromite#108]
**Is your feature request related to privacy?**
This is not a (request for a) privacy tweak but just a minor tweak for an existing Bromite, non-privacy/adblock feature. I think this is fair

**Is there a patch available for this feature somewhere?**
...
No.

**Describe the solution you'd like**
When you leave the app while a video is playing the video should not pause. Similar to the YouTube app.

**Describe alternatives you've considered**
I'm not a developer. I'm sorry.

**Comment by csagan5** [comment]
Similar issue: https://github.com/brave/browser-android-tabs/issues/160

However in Bromite we already cover that aspect and what needs to be addressed is the very specific `ShouldPauseVideoWhenHidden()` which causes this issue on Android.

I think on next release we can have this fixed.

**Comment by csagan5** [comment]
Fixed in `70.0.3538.80`.
