### ISSUE TITLE
Add Bookmark Import Option From Other Browser

### ISSUE THREAD

**Issue by Ahsan40** [bromite/bromite#109]
there are no doubt that this is one of the best browser for mobile. But it has no bookmark sync option. That's why after reset mobile all bookmark will be gone. So please add bookmark import option. So that after reset mobile we can get all bookmark which is stored another borwser like chrome.

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear here on Github via mobile; I had always been assuming that the issue template was being ignored for opened issues like this, sorry for that.

(Issues not following the template are considered invalid)

As for this specific issue: bookmark import/export has been implemented already for a while.

**Comment by Ahsan40** [comment]
its ok. But the problem is Bookmark imorting system doesn't works. please
check it and fix it please.
