### ISSUE TITLE
MonochromePublic no longer supported?

### ISSUE THREAD

**Issue by Zoraver** [bromite/bromite#110]
I have been using the MonochromePublic variant of Bromite as the webview provider on one of my Android devices. I have noticed that the recent releases of Bromite (since v68.0.3440.87) do not include a MonochomePublic variant and the documentation relating to the MonochromePublic variant has been removed from the project wiki. If the MonochromePublic variant is no longer supported, is the recommended migration strategy to switch to independent SystemWebview and ChromeModernPublic installs?

**Comment by csagan5** [comment]
@Zoraver sorry, the issue submissions templates cannot be ignored; I am not answering to questions via the Github issue tracker..

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear here on Github via mobile; I had always been assuming that the issue template was being ignored for opened issues like this, sorry for that.

(Issues not following the template are considered invalid)

As for your specific question: yes, Monochrome builds have been dropped.
