### ISSUE TITLE
Dark theme causes problem with some websites

### ISSUE THREAD

**Issue by KatoriYuu** [bromite/bromite#1100]
### Bromite version

Version: `90.0.4430.74`
Arch: `arm64`
Android version: 11
Device model: TA-1119

### Flags

These are the flags changed under `chrome://flags`:

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is this bug happening in an incognito tab?
Yes

### Allow ads for the site; is the bug caused by the adblocker?
No

### Is the bug a crash?

No

### Describe the bug
When enabling dark theme with darken websites option selected, some websites aren't displayed correctly.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to 'Genk.vn'
2. Click on 'any news'
3. Scroll down to 'bottom of the page'

Do not write "any website", specify which URLs can be used to reproduce the issue.

### Expected behavior
These boxes should be black.

### Screenshots
![Screenshot_20210423-204939](https://user-images.githubusercontent.com/42930110/115881122-9f8ed900-a475-11eb-86ef-95e545aaa133.png)

Problem with google.com:
![Screenshot_20210423-205016~2](https://user-images.githubusercontent.com/42930110/115881176-b1707c00-a475-11eb-9da7-56aca5f6cf86.png)

Thanks for your help.

**Comment by csagan5** [comment]
How does it look like in Chromium?

**Comment by KatoriYuu** [comment]
@csagan5 Chromium doesn't have the option to darken websites.

**Comment by csagan5** [comment]
How did you enable this option?

**Comment by KatoriYuu** [comment]
I went to Bromite setting -> theme -> chose "dark" option and ticked the "darken websites" box.

**Comment by KatoriYuu** [comment]
They should look like this:
![Screenshot_20210424-005452](https://user-images.githubusercontent.com/42930110/115911061-d0800580-a497-11eb-9fbd-11781ac92c21.png)
I took this screenshot from Firefox with Dark Reader extension installed.

**Comment by csagan5** [comment]
The feature is provided as is, it is not perfect for all websites, sorry.
