### ISSUE TITLE
High Ram Usage

### ISSUE THREAD

**Issue by iamrohanbro** [bromite/bromite#111]
Version 68.0.3440.110
Arm 64 chrome modern public.

Issue :-
High ram usage leading to excessive lags in tab transitions & during animations of page loading.

Steps to reproduce :-
Install bromite browser.
Launch, force stop & restart to get new ui.
Use normally.

Other info.:-
I used to face this issue months ago on some other version of bromite, so I switched out, after few updates I restarted using bromite & it was fixed, recently I'm facing it again.
The app is lagging so much in milultiple tab transitions that sometimes I'm being asked by android system to force stop or wait for the app to respond. Its also happening sometimes when I click on a link, say the "view first unread" option on any XDA thread.
The whole device isn't lagging. Like say, I can pull down the quick settings panel smoothly, press home button & use other apps laglessly, double tap recent button to switch to previous app, all these works smoothly as expected.

When I open running services in developer options and then go to cached processes, bromite is occupying minimum 500MB RAM in a single process excluding several other bromite processes that are occupying 30-50 MB & this is when I'm using 1 tab, with multiple tabs the 1st process takes up 700-850 MB.
I've tried fennec fdroid, brave & they are not taking up so much ram.
I've not tweaked any chrome flags too.

Device info:
ZUK Z2
ROM - Cardinal AOSP 5.8.0 official  - android 8.1.0_r43
RAM - 4GB LPDDR4 1866MHz. bandwidth - 29.8 GB/s. 32 bit dual channel.
CPU - SD 820.
![screenshot_settings_20180822-171528](https://user-images.githubusercontent.com/37928125/44464555-9d13bb80-a60a-11e8-9b91-f1d82d1e3d32.png)
.
![screenshot_bromite_20180822-171513](https://user-images.githubusercontent.com/37928125/44464586-b74d9980-a60a-11e8-987e-3ae684408a99.png)

Thank you.

**Comment by ouzowtf** [comment]
Did you test with Chromium?

**Comment by iamrohanbro** [comment]
Yes facing on chromium too. With bromite & chromium together, free ram is like 250MB but device ain't lagging a bit, only the 2 browsers are.
![screenshot_settings_20180822-204624](https://user-images.githubusercontent.com/37928125/44472862-97c06c00-a61e-11e8-8fc5-8f2cbc905542.png)
![screenshot_settings_20180822-204634](https://user-images.githubusercontent.com/37928125/44472995-eb32ba00-a61e-11e8-8e53-92a77e1c3f94.png)

**Comment by csagan5** [comment]
> Yes facing on chromium too. 

In this case the problem should be addressed upstream ([Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list)).

Search there for existing/similar issues to the one you are observing.

I am also afraid that the cached memory use is not a problem, but let's not discuss that here because it is off-topic.
