### ISSUE TITLE
Javascript toggle

### ISSUE THREAD

**Issue by yant0** [bromite/bromite#1185]
### Is your feature request related to privacy?

Sort of

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

When user set javasript off for all website, they'll need to backtrack to enable every new website that needs it. The page info seems good for a toggle.

### Describe alternatives you have considered

Maybe in three dots menu, but it woulf disrupt the ui.

**Comment by csagan5** [comment]
There is already both a global and a site-specific toggle for this.
