### ISSUE TITLE
WebSocket is blocked

### ISSUE THREAD

**Issue by danielehrhardt** [bromite/bromite#1189]
### Bromite version

Version: `91.0.4472.50`
Arch: `arm` or `arm64` or `x86`
Android version: (example: `8.1.0`)
Device model: SM-T510

### Flags

These are the flags changed under `chrome://flags`:

Default

### Is this bug about the SystemWebView?

Yes

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is this bug happening in an incognito tab?
No

### Allow ads for the site; is the bug caused by the adblocker?
No

### Is the bug a crash?

No

### Describe the bug
If i try to connect to a SSL WebSocket i get the following Error Message:
`Uncaught DOMException: Failed to construct 'WebSocket': Access to this address is not allowed.`
https://github.com/bromite/bromite/issues/1129
https://github.com/bromite/bromite/issues/1011
https://github.com/bromite/bromite/issues/590

### Steps to reproduce the bug

Connect to a WebSocket. wss://
or go to the Website` https://www.websocket.org/echo.html`

Do not write "any website", specify which URLs can be used to reproduce the issue.

### Expected behavior

The WebView should connect to normal SSL WebSocket in the Internet. 
`Bromite v84.0.4147.95` does work flawless

### Screenshots

-

**Comment by csagan5** [comment]
In #980, aside from abusive comments, the problem is that problem was not reproduced with **a public IP which is not the same public IP as your router**.

Can you confirm that the problem happens with a public IP which is not your router or a local device, and the steps to reproduce this?

Note: you should specify one architecture in the issue, not 3.

**Comment by danielehrhardt** [comment]
> In #980, aside from abusive comments, the problem is that problem was not reproduced with **a public IP which is not the same public IP as your router**.
> 
> Can you confirm that the problem happens with a public IP which is not your router or a local device, and the steps to reproduce this?
> 
> Note: you should specify one architecture in the issue, not 3.

I can confirm that the problem happens with a public IP. 
You can open the Page https://www.websocket.org/echo.html and try to connect to the WebSocket. 

About the architecture. I extra checked it on every architecture.

**Comment by uazo** [comment]
it works for me (A10, internet over 4g)
here a screenshot of the emulator version (x86 over wifi), I don't use the official version of bromite in the emulator, but it should be the same .. 

![image](https://user-images.githubusercontent.com/29201891/120367734-86e5ce80-c311-11eb-8ac0-adf578a176cf.png)

maybe something related to your network? can you check with the developer tools?

**Comment by csagan5** [comment]
> About the architecture. I extra checked it on every architecture.

It is about reproducibility; we must stick to one architecture as there are problems that happen only on certain architectures. Please pick one.

Is your android version 8.1.0? The issue still has the example from the template.

> You can open the Page https://www.websocket.org/echo.html and try to connect to the WebSocket.

It works.

**Comment by danielehrhardt** [comment]
> > About the architecture. I extra checked it on every architecture.
> 
> It is about reproducibility; we must stick to one architecture as there are problems that happen only on certain architectures. Please pick one.
> 
> Is your android version 8.1.0? The issue still has the example from the template.
> 
> > You can open the Page https://www.websocket.org/echo.html and try to connect to the WebSocket.
> 
> It works.

I am out of Office this Week. I will check again next week with the developer tools. I tested the System Web View in a App, not the Browser.

**Comment by csagan5** [comment]
> I tested the System Web View in a App

Please try reproducing the problem with the browser and fix the other problems I mentioned; we can re-open it at that time.
