### ISSUE TITLE
Differences between arm builds

### ISSUE THREAD

**Issue by Primokorn** [bromite/bromite#12]
Hi,
When downloading **arm** build for **Nougat and above**, **arm_MonochromePublic.apk** is automatically selected.
What are the differences with **arm_ChromeModernPublic.apk** and **arm_ChromePublic.apk**?

Thank you.

**Comment by csagan5** [comment]
I was one of the first things asked on XDA forums: https://forum.xda-developers.com/showpost.php?p=74123065&postcount=3

The official description is here: https://chromium.googlesource.com/chromium/src/+/lkcr/docs/android_build_instructions.md#Multiple-Chrome-APK-Targets

**Comment by Primokorn** [comment]
Didn't know you had a thread on XDA.
Thanks.

**Comment by csagan5** [comment]
You're welcome. I was used to build Chromium pre-50, now it has changed quite a lot. So I was also surprised by the new build targets but it makes sense.

**Comment by AngryPhantom** [comment]
Sorry for bumping, but still not sure what to install since the page is dead: https://chromium.googlesource.com/chromium/src/+/lkcr/docs/android_build_instructions.md#Multiple-Chrome-APK-Targets

**Comment by csagan5** [comment]
@AngryPhantom you can search for "Chromium multiple APK targets" on the web to find it. I have updated the [link](https://chromium.googlesource.com/chromium/src/+/master/docs/android_build_instructions.md#Multiple-Chrome-Targets) on the wiki page with the new one.

**Comment by AngryPhantom** [comment]
Thank you very much!
