### ISSUE TITLE
New logo for Bromite

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#120]
Bromite needs a new logo. The current logo is a derivation of [Chromium logo](https://commons.wikimedia.org/wiki/File:Chromium_11_Logo.svg) and it makes sense since Bromite is 99% Chromium, but for the sake of the project it is better to have an original one.

I am thinking to create a submission window and reference it from the official website to give it visibility, and/or create a Reddit post for this. Suggestions welcome.

**Edit:** I added the official news post here: https://www.bromite.org/news/2018-09-05-submissions-for-new-logo
it will be edited and act as the reference for the submissions for the time being

**Comment by Primokorn** [comment]
What about [https://forum.xda-developers.com/showthread.php?p=75328902&postcount=223](these icons)?
All suggestions should be posted here.

**Comment by ouzowtf** [comment]
It could be me but I don't understand what the icons are trying to express.
I checked Wikipedia for the chemical formula of Bromite (I thought this is the background for the name), but it's too complex for an icon :sweat_smile:

**Comment by csagan5** [comment]
> What about these icons?
> All suggestions should be posted here.

I remember those, nothing worth using IMO, they are a quick job. There was even an user that setup a steemit page claiming he did some work for this open source project; we are not using any of those.

**Comment by csagan5** [comment]
I added the official news post here: https://www.bromite.org/news/2018-09-05-submissions-for-new-logo
it will be edited and act as the reference for the submissions for the time being

**Comment by Primokorn** [comment]
> they are a quick job
Material Design is quick job lol
[This](https://opensourcedesign.net/jobs) may interest you.

**Comment by csagan5** [comment]
> Material Design is quick job lol

First of all, who said material design? I know Chromium is getting a new material design UI with release 69, but it does not mean that everything must be done in material design for Bromite as well. I personally would prefer a minimalist design.

Second, those **are** quick jobs. They were posted a day from the moment I said Play Store does not like Bromite's logo (note: I never asked for a logo submission back then). None of them cater the idea of a browser in my opinion. Also I would stay away from trying to visualize the idea of privacy, it is difficult and ambiguous.

The only one which was probably done decently is this: https://steemit.com/utopian-io/@iamfo/sngt-version-and-my-version-new-proposed-logo-design-for-bromite

I have great respect for the work of designers, but the donations are not enough to pay one properly. Any work done for the logo of Bromite will be obviously a donation itself, since 100$ are probably an indecent amount for most professionals (depends from the part of the world, I know).

> This may interest you.
I will give a look. There is also 99talents, but I am not sure I want to register to some platform that will send me endless spam for life if I want to use the service once.

**Comment by subh98** [comment]
I have drawn a logo myself😅solely for this project😍. If you like it, you can use and modify it at your own free will.
![img_20180906_214611](https://user-images.githubusercontent.com/43043047/45171882-348b2800-b221-11e8-93ca-21ba51870122.jpg)

The rotated logo represents the bromite ion.
![img_20180906_214808](https://user-images.githubusercontent.com/43043047/45172609-71f0b500-b223-11e8-8754-1a9c5565a84d.jpg)

1. Outer chromium logo represents that it is a fork of the chromium project
2. The spectacle stands for **the letter 'B'**
3. Lips with protruding tongue stands for **the letter 'r'**
4. Facial outline represents **the letter 'O'** and also the **round part of a search icon**. The handle of the search icon stands for the **symbol of a negative ion**
5. The crack stands for **the number '2'**
As a whole, it portrays BrO2– (bromite ion)

P. S. It is a rough sketch, so you have to modify it.

**Comment by csagan5** [comment]
@subh98 thanks, it would be too similar to the Chromium logo though. That is an exclusion criteria as [described here](https://www.bromite.org/news/2018-09-05-submissions-for-new-logo).

**Comment by subh98** [comment]
In that case, you can freely modify it, only if you liked the idea of symbolism of the central part of this icon. You can remove the outer part and add a new background. You can do whatever you want. And it is totally a free suggestion, I claim no money or whatsoever. I love this project and somehow wanted to contribute to it. Thanks.

**Comment by subh98** [comment]
Is it okay now?
![img_20180907_002817](https://user-images.githubusercontent.com/43043047/45179097-1f1ff900-b235-11e8-933a-4c810dc20989.jpg)
Colorful, yet powerful😁

**Comment by subh98** [comment]
3 more interpretations:
Eye glasses: Privacy
Thunder like crack: speed
Eyes made by **> <** symbol: relates to coding/software geekiness
😁😁

**Comment by subh98** [comment]
![img_20180907_002817](https://user-images.githubusercontent.com/43043047/45186747-2b638080-b24c-11e8-8d96-b7e37fae49f6.jpg)

**Comment by rohitjuyal5** [comment]
why you named it bromite?

**Comment by csagan5** [comment]
> why you named it bromite?

See https://www.bromite.org/news/2018-09-05-submissions-for-new-logo#inspiration-material-for-this-logo

**Comment by Vicky19971** [comment]
Have a new icon suggestion for bromite!
png format:
![mybromiteicon](https://user-images.githubusercontent.com/43119346/45268464-7c68b400-b49a-11e8-995c-155fcc590560.png)
svg format:
[MyBromiteIcon.zip](https://github.com/bromite/bromite/files/2364612/MyBromiteIcon.zip)

**Comment by ggabogarcia** [comment]
Hello, I will make my proposal :smiley:

**Comment by ggabogarcia** [comment]
Hello here are my proposals, I made 3.
#
The first proposal is a test tube inside a circle which represents the world.
# 
In the second proposal I made an extraction of the image of the chemical [component](https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Bromous_acid_molecule_spacefill.png/160px-Bromous_acid_molecule_spacefill.png), in which I superimposed circles according to the pattern.
# 
The third one I focus on when you say:  
>For example the logo - in its most basic design - could be a greenish world with a test tube overlayed.

![bromite](https://user-images.githubusercontent.com/35750428/45328665-81714600-b522-11e8-8b90-a6cbb6188eb4.jpg)

**Comment by csagan5** [comment]
@ggabogarcia thanks! They look really nice. Some feedback, which is entirely up to you to consider or not:
* on (1), have you considered having a contour?
* same for (2), and perhaps one of the atoms could be the world, and/or the rightmost sport a "B"?
* for (3) I think most people would want to see the outline of continents there? my preference being Antarctica to be neutral :laughing: 

@Primokorn you meant that Android icons must necessarily be done in material design? are there special requirements that I should mention in the logo submission news post?

**Comment by devpete9** [comment]
May I propose something?
![cc_20180911_203258](https://user-images.githubusercontent.com/43180354/45372328-4fd3aa00-b60a-11e8-9372-339be1f00d72.png)

**Comment by ggabogarcia** [comment]
I followed your advice, but only modify the first and third proposals
# 
![2](https://user-images.githubusercontent.com/35750428/45382425-cef6bd00-b5cd-11e8-88fc-e95324a2bf46.jpg)

**Comment by Primokorn** [comment]
> @Primokorn you meant that Android icons must necessarily be done in material design? are there special requirements that I should mention in the logo submission news post?

Dimensions: 192 x 192 since you didn't need a specific file for Google Play (512px)
The icon should be adaptive: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive
Here are the MD guidelines: https://material.io/design/iconography/#icons-product-icons

**Comment by 0x264f** [comment]
> The current logo is a derivation of Chromium logo and it makes sense since Bromite is 99% Chromium, but for the sake of the project it is better to have an original one.

Since it's based on Chromium, logo can be based on the original Chromium shapes. This is an adaptive icon.
![ic_launcher](https://user-images.githubusercontent.com/34649010/45448984-9e517900-b6dc-11e8-8b93-9ac078e11bf2.png)![ic_launcher2](https://user-images.githubusercontent.com/34649010/45448986-9e517900-b6dc-11e8-8653-5969b45178ea.png)

**Comment by csagan5** [comment]
@ggabogarcia that is a bit too heavy contour, if I may say :blush: 

@Primokorn thanks, I will update the logo submission post

@0x264f I am afraid that is still too similar to Chromium logo

**Comment by vdmp** [comment]
Hi, guys!

My name is Vadim, I’m a designer, and while exploring android guidelines, I decided to make an icon for your project.

Here is my suggestion. It's a test flask, so I keep allusion to chemistry, but it's also represents the window to the world, which I think is also nice for the browser.

![2018-09-15 23-09-48-bromite_icon](https://user-images.githubusercontent.com/31536570/45590259-8f1d3600-b93d-11e8-9bed-ce731e72a43a.png)

Icon matches nicely with other adaptive android icons:
![phone](https://user-images.githubusercontent.com/31536570/45590698-00adb200-b947-11e8-849e-5f7963e02744.png)


...and takes advantage of its layered structure with nice periscope effect:
![animation](https://user-images.githubusercontent.com/31536570/45590334-d7892380-b93e-11e8-95c1-c0b2b95caa74.gif)

Flask itself can be used as a logo on site or social media:
![logo_](https://user-images.githubusercontent.com/31536570/45590448-84fd3680-b941-11e8-802d-0d4950fbb45f.png)

Let me know if you decided to use my version, and I'll provide you files.
Thanks!

**Comment by Abacate123** [comment]
Wow, @vdmp, this looks amazing already.

**Comment by csagan5** [comment]
@vdmp thanks for your work and your submission! Really nice :blush: I will have to pick one on the deadline of 5 October 23:59 UTC, as published here: https://www.bromite.org/news/2018-09-05-submissions-for-new-logo

**Comment by csagan5** [comment]
Thanks to all participants, I have closed the submission window a bit earlier; the selected logo is the submission of @vdmp [here](https://github.com/bromite/bromite/issues/120#issuecomment-421637631)

I really appreciate the works you guys submitted!

The logo will be changed as soon as I receive the material and there is a new release.

**Comment by illucent** [comment]
Hi! A bit late.
![bromite-scetchg-v0 0000012](https://user-images.githubusercontent.com/3680424/46249356-6a35c200-c417-11e8-94bf-6563b5c23c16.png)

**Comment by Madis0** [comment]
You forgot the favicons.

**Comment by nicd23** [comment]
> 
> 
> Hi, guys!
> 
> My name is Vadim, I’m a designer, and while exploring android guidelines, I decided to make an icon for your project.
> 
> Here is my suggestion. It's a test flask, so I keep allusion to chemistry, but it's also represents the window to the world, which I think is also nice for the browser.
> 
> ![2018-09-15 23-09-48-bromite_icon](https://user-images.githubusercontent.com/31536570/45590259-8f1d3600-b93d-11e8-9bed-ce731e72a43a.png)
> 
> Icon matches nicely with other adaptive android icons:
> ![phone](https://user-images.githubusercontent.com/31536570/45590698-00adb200-b947-11e8-849e-5f7963e02744.png)
> 
> ...and takes advantage of its layered structure with nice periscope effect:
> ![animation](https://user-images.githubusercontent.com/31536570/45590334-d7892380-b93e-11e8-95c1-c0b2b95caa74.gif)
> 
> Flask itself can be used as a logo on site or social media:
> ![logo_](https://user-images.githubusercontent.com/31536570/45590448-84fd3680-b941-11e8-802d-0d4950fbb45f.png)
> 
> Let me know if you decided to use my version, and I'll provide you files.
> Thanks!

I'm not getting adaptive icon on Oreo.

**Comment by csagan5** [comment]
> You forgot to update the favicons.

Yes, I am not finished with updating the logo everywhere.

> I'm not getting adaptive icon on Oreo.

@nicd23 unfortunately I am not capable of adding adaptive icons. Does the regular Chromium have them?

**Comment by nicd23** [comment]
@csagan5 I'm not sing regular Chromium, just Bromite. Designer of the new icon @vdmp  provided all shapes, nicely done shadow but official icon doesn't look nearly as good.. Why is that the case?

**Comment by Madis0** [comment]
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive
Pretty much just one more XML file.

**Comment by csagan5** [comment]
@Madis0 well then please submit a patch! :smile:

**Comment by Madis0** [comment]
Hmm, maybe I could but I'm not sure how much processing power does it require to compile this app 😁

**Comment by csagan5** [comment]
@Madis0 let's continue this on #181
