### ISSUE TITLE
Unable to enable DeviceOrientation API

### ISSUE THREAD

**Issue by easrng** [bromite/bromite#1204]
### Bromite version

Version: `91.0.4472.97 (Official Build) (32-bit)`
Arch: `arm`
Android version: `8.1`
Device model: `Moto G (5) Plus`

### Flags

These are the flags changed under `chrome://flags`:

  - #enable-device-motion: Enabled
  - #enable-device-orientation: Enabled
  - #enable-generic-sensor-extra-classes: Enabled

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is this bug happening in an incognito tab?

No

### Allow ads for the site; is the bug caused by the adblocker?
No

### Is the bug a crash?

No

### Describe the bug

I enabled DeviceOrientation and DeviceMotion but they aren't working.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Enable DeviceOrientation
2. Go to https://www.audero.it/demo/device-orientation-api-demo.html
3. Move device
4. Cube is still

### Expected behavior

Cube moves with device.

**Comment by uazo** [comment]
>  perhaps we could retire the flags

one less patch to manage...

> And we could also make it become an "ask" site setting (unrelated).

why not! but I don't know how to do it ...
I would like to see how to do this, because the request at user is done via communication between blink and the browser via mojo (that I still don't know well), and I would like to understand how this is done.

but before I'd like to add self-cleaning of the storage (cookies and similar) when a tab is closed... we'll talk about it?

**Comment by csagan5** [comment]
> but before I'd like to add self-cleaning of the storage (cookies and similar) when a tab is closed... we'll talk about it?

on a separate issue.

I will close this one when flags are removed; any idea if the current site settings cover both flags we have? There is no diversification.

**Comment by uazo** [comment]
> any idea if the current site settings cover both flags we have?

no, I haven't looked at it yet

**Comment by csagan5** [comment]
Fixed in `91.0.4472.146`.
