### ISSUE TITLE
Crash when trying to change media options

### ISSUE THREAD

**Issue by razorsoup** [bromite/bromite#122]
Version: v69.0.3497.73.
Arch: arm64_ChromeModernPublic.apk

Is the bug a crash? Yes

Describe the bug
In the settings menu, going to Site Settings>Media causes Bromite to FC.

**Comment by lowtrucks** [comment]
i can also confirm that.

model: Samsung Galaxy S III (i9300)
CPU: 1.4 GHz quad-core Cortex-A9
OS: Android 7.1.2
Bromite: 69.0.3497.73, arm_ChromeModernPublic.apk
