### ISSUE TITLE
Adding custom search engine

### ISSUE THREAD

**Issue by ygz213** [bromite/bromite#1231]
### Is your feature request related to privacy?

Maybe (Someone may want to add a privacy-oriented search engine to Bromite.)

### Is there a patch available for this feature somewhere?

As far as I know in Firefox for Android (I saw in app)

### Describe the solution you would like

For example, type a URL like https://html.duckduckgo.com/html/?q=%s and use this as a search engine.

### Describe alternatives you have considered

Adding 15-20 search engines to Bromite.

**Comment by csagan5** [comment]
See https://github.com/bromite/bromite/wiki/SearchEngines.
