### ISSUE TITLE
Add custom search URL

### ISSUE THREAD

**Issue by eggplanting** [bromite/bromite#1238]
### Is your feature request related to privacy?

Yes, this solution would allow every search engine to be compatible with Bromite. For example Startpage.com could be used, which is a huge privacy increase compared to Google.

### Is there a patch available for this feature somewhere?

I don't know

### Describe the solution you would like

Add an option to set a custom search engine via URL string, like the desktop version of Chromium has.

Example for a valid search string: https://startpage.com/sp/search?query=%s
Where %s is the keyword which is searched for

### Describe alternatives you have considered

This is similar but no alternative: https://github.com/bromite/bromite/wiki/SearchEngines
Not all search engines are supported this way, Startpage.com for example won't show up.

Adding the custom URL allows more freedom of choice for our favorite browser.

**Comment by BL4CKH47H4CK3R** [comment]
I was about to open this issue just now. But got yours :+1: 
Customized search engine is a very much needed feature. Like I am using selfhosted `searx` and `whoogle-search` engine. But the problem is I need to manually type always my instances for searching. As a privacy respecting browser it should not use google but use [whoogle](https://whooglesearch.net) as an example. also I think people don't do search using ecosia and others. BTW it will be great to customize search engine so that people can use their own or have other choices

Greetings, BL4CKH47H4CK3R

**Comment by csagan5** [comment]
No, I have no intention to develop or maintain such patch for search engines that do not follow the standard.

**Comment by eggplanting** [comment]
Thanks for the reply, even if I don't understand your reasons.

Setting a custom search via URL allows not only to use more search engines, it allows exactly to set which search parameters you want to include via URL. In many cases, cookies are not needed when you use the equivalent URL parameters.

When I heard from Bromite, I thought it would already support this feature. A privacy respecting browser should allow me, the user, to choose which search engine I want to use. Even desktop versions of Chromium and other mobile browsers like Firefox allow this.

Would be glad if you rethink your choice, since Bromite is a great project and this feature would only benefit the userbase.

**Comment by csagan5** [comment]
> Would be glad if you rethink your choice, since Bromite is a great project and this feature would only benefit the userbase.

I will not rethink my choice and you have no rights to ask that. This is an open source project: if you want to help, do something for the project. Asking does not correspond to helping.

**Comment by sorryusernameisalreadytaken** [comment]
You can add startpage.com, see [here](https://github.com/bromite/bromite/issues/435#issuecomment-1007228859).
