### ISSUE TITLE
Crash when a Cast target advertises on network

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#125]
**Bromite version**

Version: `69.0.3497.91`
Arch: `arm64`
Android version: `nougat`

**Is the bug reproducible with latest version?**
Yes.

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No.

**Is the bug a crash?**
Yes, but could not find the crash log

**Describe the bug**
Bromite crashes a few times right after phone wakes up from deep sleep.

**To Reproduce**
1. Have phone enter deep sleep
2. Wake it up and use some app (does not have to be Bromite)

This was initially incorrectly filed as #123

**Comment by vashin1** [comment]
I cannot repeat this on my Pixel 2 running 69.0.3497.91 on Android 9.0. Have yet to see it on my Galaxy s4 running Nougat either.

**Comment by csagan5** [comment]
I am using stock ROM on this phone; I could not capture the log when it happened but I remember it started some time ago with similar symptoms (so not specific to 69).

**Comment by csagan5** [comment]
I finally could catch the log dump in time:

```
09-25 22:44:22.693  3691  3691 I crash_dump64: obtaining output fd from tombstoned
09-25 22:44:22.694  3691  3691 I crash_dump64: performing dump of process 3612 (target tid = 3612)
09-25 22:44:22.694  3691  3691 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-25 22:44:22.694  3691  3691 F DEBUG   : Build fingerprint: 'xiaomi/mido/mido:7.0/NRD90M/V8.5.4.0.NCFMIED:user/release-keys'
09-25 22:44:22.694  3691  3691 F DEBUG   : Revision: '0'
09-25 22:44:22.694  3691  3691 F DEBUG   : ABI: 'arm64'
09-25 22:44:22.694  3691  3691 F DEBUG   : pid: 3612, tid: 3612, name: bromite.bromite  >>> org.bromite.bromite <<<
09-25 22:44:22.694  3691  3691 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
09-25 22:44:22.694  3691  3691 F DEBUG   : Cause: null pointer dereference
09-25 22:44:22.695  3691  3691 F DEBUG   :     x0   0000000000000000  x1   0000007fd5f09a88  x2   0000000012dc3a70  x3   0000007fd5f09a78
09-25 22:44:22.695  3691  3691 F DEBUG   :     x4   0000007fd5f09a70  x5   0000007c280e70c8  x6   0000007c3c857000  x7   0000000000d503da
09-25 22:44:22.695  3691  3691 F DEBUG   :     x8   ec50abe01eea506a  x9   ec50abe01eea506a  x10  0000000000430000  x11  ec50abe01eea506a
09-25 22:44:22.695  3691  3691 F DEBUG   :     x12  ec50abe01eea506a  x13  0000007c37cb18c0  x14  0000007c37cb1920  x15  0000000000000000
09-25 22:44:22.695  3691  3691 F DEBUG   :     x16  0000007c3a10fcc8  x17  0000007c3a0adf60  x18  0000000000000020  x19  0000007c280e70c0
09-25 22:44:22.695  3691  3691 F DEBUG   :     x20  0000007c1a39fcb4  x21  0000007c380c3a00  x22  0000007fd5f09d3c  x23  0000007c1e5d7bf5
09-25 22:44:22.695  3691  3691 F DEBUG   :     x24  000000000000000c  x25  0000007c380c3a98  x26  0000000000000000  x27  0000000000000004
09-25 22:44:22.695  3691  3691 F DEBUG   :     x28  0000000000000003  x29  0000007fd5f09a90  x30  0000007c1a39fcf4
09-25 22:44:22.695  3691  3691 F DEBUG   :     sp   0000007fd5f09a70  pc   0000007c1a39fcfc  pstate 0000000060000000
09-25 22:44:22.696  3691  3691 F DEBUG   : 
09-25 22:44:22.696  3691  3691 F DEBUG   : backtrace:
09-25 22:44:22.696  3691  3691 F DEBUG   :     #00 pc 00000000011d4cfc  /data/app/org.bromite.bromite-XEEIl2TQekzrQF12CYc9sA==/base.apk (offset 0x24f7000)
09-25 22:44:22.696  3691  3691 F DEBUG   :     #01 pc 00000000011d4cf0  /data/app/org.bromite.bromite-XEEIl2TQekzrQF12CYc9sA==/base.apk (offset 0x24f7000)
```

I am not sure but I think that this is caused by a smart TV on same network that exposes MediaRouter functionality (e.g. a Cast target).

Can somebody please confirm/deny if you have a Cast target in same local network?

**Comment by MrGlasspoole** [comment]
I also have the problem that i get a "Bromite has stopped" after boot or sleep even if Bromite is not running.

Can you please explain what a "Cast target" or "exposed MediaRouter functionality" is respectively how i can find out? I'm relatively sure that i don't have something like that.

Android 7.0.0
Bromite 69.0.3497.113

**Comment by k4r7u** [comment]
I have a Chromecast in my network. Nevertheless I can notice the crashes even when the cast device is completely unplugged.

**Comment by MrGlasspoole** [comment]
I switched from the original Android 7.0.0 to a custom 7.1.2 and first i thought the error is gone.
But now i get "Bromite keeps stopping" from time to time (Bromite is not running when this happens).

**Comment by csagan5** [comment]
@MrGlasspoole yes that is also the behaviour I see; did you test with a version equal or after `70.0.3538.67`? I believe that dropping the GCM-removal patch might have fixed this problem.

In next release `70.0.3538.80` another unrelated crash due to the update check has been fixed.

**Comment by csagan5** [comment]
I think this is the same as #169; latest `70.0.3538.83` should still be affected.
