### ISSUE TITLE
Allow multiple host files for Adblocker

### ISSUE THREAD

**Issue by AzureB1te** [bromite/bromite#1254]
It is a clear feature request. 

 It is neither of the above.

### Is your feature request related to privacy?

 
Well, yes. Technically could be worse, for fingerprinting, but generally, blocking more trackers is prefered, I think. 

### Is there a patch available for this feature somewhere?

 Not that I know of

### Describe the solution you would like

So basically, as of now, Bromite can only handle one host files. Maybe the default one, maybe a custom one. But what if, we could have multiple files in parallel? I'm not quite sure how hosts work, but if this is possible, it would greatly increase the Adblocker's power. Maybe, more filters could be used, for more purposes, regional filters would make sense, and so on. Obviously, I'm not asking for the filters themselves, I'm just suggesting adding support for multiple, if possible

### Describe alternatives you have considered

Upgrade the Adblocker to something more complex/modular

**Comment by csagan5** [comment]
> I'm not quite sure how hosts work, but if this is possible, it would greatly increase the Adblocker's power.

If you are not sure how hosts work, how can you conclude that this would increase the Adblocker power? Please come back after you know how they work, you will figure out that this feature request would do nothing.

**Comment by tp0** [comment]
It seems like OP was/is actually suggesting "allow multiple filter URLs".
