### ISSUE TITLE
Separate screenshot toggle

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [bromite/bromite#1258]
### Is your feature request related to privacy?

Yes.

### Is there a patch available for this feature somewhere?

--

### Describe the solution you would like

Currently we can only block screenshots when in Incognito mode, however there might be situations where we might need to take one and switching Always Incognito mode on and off isn't the most practical thing. So I propose let's have a separate switch that controls this. 

### Describe alternatives you have considered

--

**Comment by CJ-47** [comment]
![bromite incognito screenshot ](https://user-images.githubusercontent.com/73770668/124759309-23bd0c80-df4d-11eb-812b-d85acd463cb8.jpg)

Have you tried using  'incognito screenshot' flag at chrome://flags for using screenshot while on incognito mode ?

**Comment by IHateTheProgrammingClass** [comment]
@CJ-47 No I haven't tinkered with flags. I would imagine Incognito mode and the screenshot block being two separate toggles. Although a better alternative could be to have a direct switch in the settings that modifies this flag. "Allow screenshots in Incognito mode".

**Comment by IHateTheProgrammingClass** [comment]
@csagan5 Why is it invalid?

**Comment by IHateTheProgrammingClass** [comment]
@csagan5 Why is it invalid?

**Comment by IHateTheProgrammingClass** [comment]
@csagan5 Why is it invalid?

**Comment by csagan5** [comment]
What is the feature you would like to see? The capability to block screenshots during regular browsing?

**Comment by IHateTheProgrammingClass** [comment]
@csagan5 The capability to have an option so that not the tab type (i.e. regular or incognito) manage when screenshots are enabled. Ultimately I would like a separate screenshot allow or disable switch. It could have a "one time" enable option. If you find it worth the effort or like the idea it could be set separately for the two tab type.

For example currently:

**Regular: Enabled**

**Incognito: Disabled**

Both of them could be set enabled or disabled or switched up per the separate switch. If one or both of them are disabled, there could be a one time exception option too.

**Comment by IHateTheProgrammingClass** [comment]
@csagan5 It's still closed. Do you still consider this invalid?
