### ISSUE TITLE
double version numbers in fdroid repo

### ISSUE THREAD

**Issue by Tonbia** [bromite/bromite#126]
Bromite version

Version: all
Arch: arm64
Android version: nougat

Is the bug reproducible with latest version?
Yes.

Can the bug be reproduced with corresponding Chromium version?
Yes

Is the bug a crash?
No

Describe the bug
When i try to update bromite via fdroid, i get " apk failed to verify".

**Comment by csagan5** [comment]
@Tonbia "apk failed to verify": re-download it. There are no duplicates, there is one for each architecture and Android ABI. F-Droid will suggest you the right one, no need to download a specific version (in particular if you cannot see the difference).
