### ISSUE TITLE
Webrtc call not working

### ISSUE THREAD

**Issue by gothmog123** [bromite/bromite#127]
Video works but I think there's a problem with capturing the microphone. Firefox works on the same service.

Keep up the great work, this is the best browser on android.

**Comment by vashin1** [comment]
I had zero problems granting permissions to my camera and microphone on WebRTC, I also confirmed that sound and video capture works just fine on the latest release of Bromite - https://webrtc.github.io/samples/src/content/devices/input-output/

Zero issued on Android 9.0 on my Pixel 2, perhaps it's a system issue on your end but the app is fine. I don't think there is any bugs here.

**Comment by gothmog123** [comment]
Thanks, I have 0 clue what could be wrong with my device:(

It's Lineage OS 15 by the way.

**Comment by csagan5** [comment]
I cannot reproduce as well, closing.
