### ISSUE TITLE
F-Droid installs multiple versions at once.

### ISSUE THREAD

**Issue by Muscarv2** [bromite/bromite#129]
The most recent update is listed multiple times under "versions", witch no difference in the description of each one, but they are all different sizes. I have no idea which is the right one. Why has this happened? Here's an image that shows the versions: http://u.cubeupload.com/Muscar/Screenshot2018091709.jpg

**Comment by csagan5** [comment]
As in #126, this must be a change in F-Droid client because I can see on F-Droid client v1.2.2 the binary version on the bottom-right corner of each box.

The right one is the one that F-Droid suggests you to install.

**Comment by ouzowtf** [comment]
Yes, just update the F-Droid client to the current version 1.4.
It should look for Bromite like this:

![Bromite on F-Droid 1.4](https://i.imgur.com/oirfQx1.jpg)

**Comment by Muscarv2** [comment]
Updated to 1.4, I think it's fixed, will have to wait till a new Bromite update to see if it only installs one of them, thanks!

**Comment by csagan5** [comment]
In 1.2.2 it would show the platform; regardless of the version, it always installs the right one, you never need to pick any manually unless you are installing a Beta (and there are no Bromite Betas right now, and you would know if you are testing a Beta...)
