### ISSUE TITLE
Adblocker is not working

### ISSUE THREAD

**Issue by ygz213** [bromite/bromite#1299]
### Bromite version

Version: `92.0.4515.103`
Arch: `arm`
Android version: : `5.0.1`
Device model: `TCL-8079`

### Flags

These are the flags changed under `chrome://flags`:

`#disable-webgl` / WebGL : Disabled
`#smooth-scrolling` / Smooth Scrolling : Enabled
`#enable-quic` / Experimental QUIC protocol : Enabled
`#enable-gpu-rasterization` / GPU rasterization : Enabled
`#omnibox-clipboard-suggestions-content-hidden` / Clipboard suggestion content hidden : Disabled
`#read-later` / Reading List : Enabled
`#bookmark-bottom-sheet` / Enables bookmark bottom sheet : Enabled
### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is this bug happening in an incognito tab?

In an incognito and normal tab

### Allow ads for the site; is the bug caused by the adblocker?

No

### Is the bug a crash?

No

### Describe the bug

Adblocker is not working. I have tried restart adblocker and browser but it didn't work.

### Steps to reproduce the bug

1. Go to ad-ful site.
2. See bug

### Expected behavior

Adblocker must work like previous versions

**Comment by SV84** [comment]
Can confirm this.

**Comment by impreza233** [comment]
I can confirm this on my tablet:

![Screenshot_20210723-191238_Bromite](https://user-images.githubusercontent.com/25793051/126817729-f918203a-95df-407d-b984-26d5b88fafa7.jpg)

Chromium | 92.0.4515.103 (Official build) (64 bits)
-- | --
Revision | b296ca7d9a18418b8cdf2e7d9a8e9701f493161f-
Operating System | Android 11; SM-T220 Build/RP1A.200720.012

**Comment by c64bob** [comment]
Can confirm this as well.

**Comment by frankjrp** [comment]
I can confirm that the adblocker is not working in the version `92.0.4515.103`.

![3](https://user-images.githubusercontent.com/33721770/126854775-cc8dda9b-f2d9-4b9d-aa20-67aa7c5bdef7.jpg)
<br><br>

![2](https://user-images.githubusercontent.com/33721770/126854776-294b6def-21b7-49d2-b562-350c476b6a20.jpg)
<br><br>

![1](https://user-images.githubusercontent.com/33721770/126854777-e6658560-d6fd-4fc1-a4ae-9ac55decd6ef.jpg)

**Comment by chromer030** [comment]
I confirm this, i clean installed bromite and adblocker stoped working in 92 release.

**Comment by ichibauer** [comment]
Can confirm this.

**Comment by RicoHeat** [comment]
Wish there were an easier way to convert our own lists to the .dat version that Bromite uses.. I even asked @badmojr from the 1Hosts list to try to provide an already converted one to his lists but after some tests it just didn't work properly to his standards.. OISD wouldn't even touch it at all.

**Comment by badmojr** [comment]
Could it be that issue was related to this @RicoHeat ?

**Comment by lowtrucks** [comment]
i confirm this bug.

**Comment by nityy** [comment]
@RicoHeat Try this https://github.com/xarantolus/filtrite

**Comment by u0a266** [comment]
Downgrading bromite to 91.x made adblock work!

**Comment by uazo** [comment]
@csagan5 I think I understand why. look there, it seems wrong!

https://github.com/bromite/bromite/blob/master/build/patches/Disable-safe-browsing.patch#L2201

you can look my version of that patch, in my version i did not detect this bug. now I try and I give you confirmation.

**Comment by rt1omas** [comment]
Can confirm this as well.

**Comment by wavedashdoc** [comment]
Also experiencing this issue as well. Android 11 Pixel 4a.

**Comment by denzhaummer** [comment]
I am also suffering from the same problem

**Comment by ygz213** [comment]
I guess this is occurring on everyone's phone

**Comment by petep0p** [comment]
also seeing ads on mine:
- Application version 
- Bromite 92.0.4515.103

- Operating system
- Android 8.0.0; SM-G892A Build/R16NW

**Comment by kimbob13** [comment]
Can confirm this as well

- Galaxy S20+ (SM-G986N)
- Android 11

**Comment by NineOutOfTen** [comment]
Me too and i use a Google Pixel 3XL.

**Comment by NSTAdventure** [comment]
@csgan5

I use latest updates and have same problem on realme 5i devices with android Q

**Comment by NSTAdventure** [comment]
I have some ideas regarding to bromite also for overcome this issues:
https://github.com/bromite/bromite/discussions/1304

**Comment by anwad** [comment]
Same issue on Mi a3 Android 11 Bromite version 92.0.4515.103

**Comment by rojenzaman** [comment]
Same issue on Galaxy Grand Prime - Android 10 - Bromite version 92.0.4515.103

**Comment by matternjei** [comment]
I can confirm this bug on my oneplus 6T on Android 10

**Comment by csagan5** [comment]
Fixed in `92.0.4515.125`.

**Comment by matternjei** [comment]
Thank you!
