### ISSUE TITLE
All Google Sync failed!

### ISSUE THREAD

**Issue by westsibe** [bromite/bromite#13]
All Google Sync failed now! :-( Please make package name as org.chromium.chrome
As now is org.bromite.bromite it's very bad idea for Google Sync.

**Comment by westsibe** [comment]
Then Google Sync be broken.

**Comment by westsibe** [comment]
(I checked it!)

**Comment by csagan5** [comment]
@westsibe it cannot use Chromium package name.

Google sync would be broken anyways

**Comment by csagan5** [comment]
I have added a short explanation as a F.A.Q. here: https://github.com/bromite/bromite/blob/master/README.md#does-google-sync-work

Since everyone expects Chromium projects to use Google APIs for free (as in Chrome), but that's not allowed by Google.

**Comment by westsibe** [comment]
In 1 from last versions of Bomite Browser has been works the Bookmarks, Gmail, Google Translate and now it all is broken. :-( Google Rules... Google Rules... :-(
