### ISSUE TITLE
Allow local websocket request when requestor_space is local too

### ISSUE THREAD

**Issue by thomazz-nl** [bromite/bromite#1320]
### Is your feature request related to privacy?
Yes.

### Is there a patch available for this feature somewhere?
No.

### Describe the solution you would like
[Block private networks scanning (gateway attacks)](https://github.com/bromite/bromite/issues/590) introduced desired protection from gateway scanning. But it might block a bit more than what's strictly needed to be safe (which I presume is the main goal). [The patch in Bromite has three checks](https://github.com/bromite/bromite/issues/590#issuecomment-832138948):
1. forbid a request to reserved IP addresses
2. forbid a request to local IP addresses
3. forbid requestor_space > target_space

Now how about requestor_space == target_space && the request is to a local IP-address?

If anyone were to host a local service and visits it with Bromite (e.g. requestor_space/window.location.origin is https://home.mydomain.tld of which the domain record resolves to 192.168.1.100) and the rendered client wants to communicate to its origin by using a websocket (e.g. target_space/uri is wss://home.mydomain.tld/api/websocket, wouldn't that be something to be considered safe/allowed?

**Reasons to NOT allow this (I can think of):**
* Protect the Bromite user from evil
     * user is not in control of his local network/devices - bigger issues at hand.
     * user is on public wifi - unsafe by nature, requires both malicious server and user action (visiting the server).
     * evil actor gained control of local network/devices - unlikely and bigger issues at hand.
* Protect the Bromite user from a misbehaving local service
    *  local service uploading network scans to remote server - the service can probably do this without any client and isn't the user responsible for what is knowingly installed (and thus trusted) on the local network?

### Describe alternatives you have considered
* Using another browser (Chromium perhaps).
* Make home.mydomain.tld resolve to a public ip and expose the service to the internet (and use hairpin routing or 4g instead of wifi).

**Comment by csagan5** [comment]
This feature was introduced with #590 and I raised a concern about local-to-local in [that comment you quoted](https://github.com/bromite/bromite/issues/590#issuecomment-832138948).

> 1. forbid a request to reserved IP addresses
> 2. forbid a request to local IP addresses
> 3. forbid requestor_space > target_space

However, I cannot find evidence of (1) or (2); additionally, this is not a feature request but a bug report and should provide steps to reproduce.

**Comment by thomazz-nl** [comment]
Thanks for responding Carl. I thought the current behaviour was intentional, hence the feature request instead of a bug report.

I'm willing to pursue this further and supply detailed steps to reproduce (test case with docker-compose file and such). Would you suggest I create a new issue (while there are already quite some related closed ones) or continue this in #590  or #1189?

And more importantly: any advice on how I can be more helpful (to not end with another closed ticket in the list)? My "discussions" post was deleted without any feedback while it could've been converted to a issue/bug report in a single click (it had the template in it), the disappeared effort was a bit demoralizing :(.

**Comment by csagan5** [comment]
> And more importantly: any advice on how I can be more helpful (to not end with another closed ticket in the list)? My "discussions" post was deleted without any feedback while it could've been converted to a issue/bug report in a single click (it had the template in it), the disappeared effort was a bit demoralizing :(.

From this end I have seen:
1. a bug report submitted as a discussion, I must suppose you know that those should not be filed under discussions
2. a bug report submitted as a feature request, this is again a bland attempt to avoid the submission template?

Can you please submit the bug report using the proper template on your next attempt? This project receives tens of issues per week and if submitters do not spend the effort to use the template I unfortunately cannot spend the effort either.
