### ISSUE TITLE
Ability to add exceptions to save Cookies, Javascript, Ads

### ISSUE THREAD

**Issue by vladimirkosolapov** [bromite/bromite#133]
**Is your feature request related to privacy?**
Yes

**Is there a patch available for this feature somewhere?**
Maybe

**Describe the solution you'd like**
It would be nice to be able to allow some sites to save Cookies when global setting forbids saving them for all sites.
<details>
  <summary>Click to expand</summary>
  <img alt="Power Browser NTP settings" src="https://user-images.githubusercontent.com/34649010/45822451-2692d800-bcf4-11e8-8916-fdaa31c3b5cf.png"/>
</details>

**Comment by csagan5** [comment]
I think this is another missing feature which is missing with intent to damage user freedom...the site settings is very scarce in functionality related to cookies, Javascript etc with no apparent reason.

I would have to check the amount of work needed for this to be patched; I am not aware of any other open source Chromium browser that has this functionality.

**Comment by Madis0** [comment]
>the site settings is very scarce in functionality related to cookies, Javascript etc with no apparent reason.

I can't remember how it used to be in mobile Chromium versions, but this is the reason for the desktop browser change:
https://chromium-review.googlesource.com/c/chromium/src/+/662997/

Though the obvious difference here is that in desktop, users can at change all permissions proactively when clicking on "Site settings" on the page info popup. 

Perhaps you can just make the internal URL `chrome://settings/content/` work on mobile? `chrome://settings/content/siteDetails?site=https%3A%2F%2Fexample.org` for a specific site.

**Comment by csagan5** [comment]
> I can't remember how it used to be in mobile Chromium versions, but this is the reason for the desktop browser change:
> https://chromium-review.googlesource.com/c/chromium/src/+/662997/

This affects the visualization of the settings, yes. They do not show defaults to save space on mobile, it is acceptable.



> Though the obvious difference here is that in desktop, users can at change all permissions proactively when clicking on "Site settings" on the page info popup.
> 
> Perhaps you can just make the internal URL `chrome://settings/content/` work on mobile? `chrome://settings/content/siteDetails?site=https%3A%2F%2Fexample.org` for a specific site.

The parent page (`chrome://settings`) would be too hard to enable; it is a good idea to check if the specific site details page can work, although I doubt it's a walk in the park. Also: there is to see if it works decently well for mobile devices.

If it were possible there would then be two UI locations to change site settings (the Android one and the desktop-like one).

**Comment by DI555** [comment]
Please add in this list and:

• third party Cookies
• third party JavaScripts

**Comment by DI555** [comment]
And imho this will be also usefull:

• HTTPS Everywhere

**Comment by Madis0** [comment]
I've personally forgotten that it is still possible to add exceptions from a different place, so writing instructions here for others: 

1. 3-dot menu > Settings > Site settings 
2. Pick a category 
3. Tap on Add site exception 
4. Add a domain with subdomain (e.g. www.theverge.com, not theverge.com)
5. Visit the site to confirm it works

**Comment by csagan5** [comment]
@Madis0 thanks for reporting back; at this point the issue here is open only to figure out how to show different permissions on the site tab as per [your comment here](https://github.com/bromite/bromite/issues/133#issuecomment-441968326)

**Comment by csagan5** [comment]
This feature will be released with `79.0.3945.105` and it will cover cookies, Javascript and ads as per the original issue.

**Comment by csagan5** [comment]
Fixed in `79.0.3945.107`.
