### ISSUE TITLE
Site setting for images

### ISSUE THREAD

**Issue by frogtile** [bromite/bromite#1339]
### Is your feature request related to privacy?
In some cases, maybe?

### Is there a patch available for this feature somewhere?
I haven't look for.

### Describe the solution you would like

I want to be able to disable loading of images, fonts etc.

Primary use case is browsing with limited bandwidth. (when using cellular internet package)

### Describe alternatives you have considered

chromium used have image blocking. But they removed it (in 2015)

https://bugs.chromium.org/p/chromium/issues/detail?id=505844

**Comment by frogtile** [comment]
@kokukyocho any update on this

**Comment by csagan5** [comment]
The use-case for this is very small but I guess it could be reinstated with some site setting for it; @uazo what do you think?

**Comment by uazo** [comment]
what is missing seems is only the ui, the content settings is still active for non android platforms

https://source.chromium.org/chromium/chromium/src/+/main:components/content_settings/core/browser/content_settings_utils.cc;l=136;drc=cb65284bde8d00949f8b51e6b6c58f2502d8af2d

**Comment by csagan5** [comment]
Ok; then I would say we can re-add it with a patch similar to those we have for timezone/UA. @uazo shall I assign it to you or myself?

**Comment by uazo** [comment]
> shall I assign it to you or myself?

I do it, it shouldn't take long.

**Comment by csagan5** [comment]
Fixed in `94.0.4606.94`.

**Comment by frogtile** [comment]
Remote fonts?
