### ISSUE TITLE
Crash when trying to open an intent as normal page with incognito mode

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#135]
**Bromite version**

Version: `69.0.3497.91`
Arch: `arm64`
Android version: `nougat`

**Is the bug reproducible with latest version?**
Yes.

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No.

**Is the bug a crash?**
Yes.

**To Reproduce**
1. Enable always-incognito mode
2. Allow custom tab intents (default)
3. Open an intent URL from an app
4. Click on the 3-dots menu -> Open in Bromite

Related to #18

**Comment by serovar** [comment]
Are there any news about this bug?

**Comment by csagan5** [comment]
@serovar can you reproduce it with latest version?

**Comment by serovar** [comment]
Yes, unfortunately

**Comment by csagan5** [comment]
The crash has the same stacktrace as #453.

**Comment by pflanzenandi** [comment]
For me Bromite also crashes without allowing custom tab intents.

**Comment by csagan5** [comment]
If someone wants to test we have a potential fix in https://github.com/bromite/bromite/pull/529#issuecomment-616800602

**Comment by bocekm** [comment]
> If someone wants to test we have a potential fix in [#529 (comment)](https://github.com/bromite/bromite/pull/529#issuecomment-616800602)

It fixes the issue, as well as the https://github.com/bromite/bromite/issues/453 issue. Thanks!

**Comment by csagan5** [comment]
Fixed in `81.0.4044.127`
