### ISSUE TITLE
Can't get camera (video stream) working with WebRTC API

### ISSUE THREAD

**Issue by kutsan** [bromite/bromite#1359]
### Bromite version

Version: `92.0.4515.134`
Arch: `arm`
Android version: `11`
Device model: `Xiaomi Mi Note 10 Lite (M2002F4LG)`

### Flags

These are the flags changed under `chrome://flags`:

It's all in defaults.

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is this bug happening in an incognito tab?

Yes

### Allow ads for the site; is the bug caused by the adblocker?

No

### Is the bug a crash?

No

### Describe the bug

[MediaDevices.getUserMedia()](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) API is not working on Bromite but it is on Chromium.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to [qrscan-pwa.kutsankaplan.com](https://qrscan-pwa.kutsankaplan.com/)
2. See the video stream is not working. It's working on Chromium and Google Chrome.
3. Check the source code related to that video stream API: https://github.com/kutsan/qrscan-pwa/blob/97b883553d8ba259c151b26cfbe6c17e72db1b87/src/hooks/use-usermedia.ts#L24-L39

### Expected behavior

[MediaDevices.getUserMedia()](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) API should work.

**Comment by csagan5** [comment]
What do you see in the Javascript console?

**Comment by kutsan** [comment]
@csagan5 Says `DOMException: play() can only be initiated by a user gesture.` since I'm trying to get video stream after getting camera permissions but I have no idea why only Bromite behaves like that.

**Comment by csagan5** [comment]
Bromite prevents autoplay, so it is working as intended.
