### ISSUE TITLE
Blocking Third-Party Scrips (Javascript Persite Settings)

### ISSUE THREAD

**Issue by AzureB1te** [bromite/bromite#1360]
It's a feature request

 It's neither.

### Is your feature request related to privacy?

 It massively improves privacy.

### Is there a patch available for this feature somewhere?

 Not that I know of. uBlock Origin might have one maybe, but nothing I'm sure of. 

### Describe the solution you would like

I'd like the site settings -> javascript page to provide a way to block Third-Party Scripts, the same way one could block Third-Party cookies. Some sites would break for sure, but that's something I'm willing to sacrifice. 

### Describe alternatives you have considered

N/A

**Comment by rawlife56** [comment]
This is mostly theater and not worth the effort. Most of the tracking is switching to first party nowadays. Blocking scripts is an inconvenient and ineffective solution. Chromium has few mitigations in roadmap to tackle first party tracking.

**Comment by csagan5** [comment]
There is currently no UI to finely tune script/ads blocking in Bromite and no plans to add one.

**Comment by Thewisem** [comment]
So The idea is rejected. Ok
