### ISSUE TITLE
"Add to Home Screen" button in Incognito Mode as well

### ISSUE THREAD

**Issue by pixincreate** [bromite/bromite#1362]
### Is your feature request related to privacy?
Yes.   

### Is there a patch available for this feature somewhere?
Yes. I saw this on Firefox browser as of now as I use it every day.

### Describe the solution you would like
**Add to Home screen** option is only available in Normal mode, which means you cannot add shortcuts to access some webpages in Incognito Mode from the homescreen itself.     
**Add to Home screen** button is required to add some webpages to the homescreen in Incognito Mode.

### Describe alternatives you have considered
So far, using firefox's incognito webpage Home screen option which is too slow.

**Comment by rawlife56** [comment]
+1 This would be helpful.

**Comment by tonya1545b** [comment]
+1 would be nice seeing this added

**Comment by jadedgnome** [comment]
> Fixed in `94.0.4606.102`.

i'm using version 101.0.4951.69 and I don't see the 'add to homescreen' option in a incognito tab. was it removed?

**Comment by csagan5** [comment]
The fix was introduced in e6c854cc9c7aed911b7a3dbee6244025ba67c4d7; @uazo the code looks fine, any idea? If it is a problem there should be a new issue though, this one is quite old.

**Comment by uazo** [comment]
I honestly can't reproduce it. can you do it?
I remember that always incognito must be activated, maybe it is not active in your tests?

**Comment by jadedgnome** [comment]
> The fix was introduced in [e6c854c](https://github.com/bromite/bromite/commit/e6c854cc9c7aed911b7a3dbee6244025ba67c4d7); @uazo the code looks fine, any idea? If it is a problem there should be a new issue though, this one is quite old.

i'm using android 10.

https://user-images.githubusercontent.com/2940805/192962012-1a4a1560-f42b-421e-945b-d02c199a17b0.mp4

**Comment by uazo** [comment]
did you activate the history in the settings?

**Comment by jadedgnome** [comment]
> did you activate the history in the settings?

no, was I suppose to?

**Comment by uazo** [comment]
yes, I don't think I've ever changed that need, but it makes sense, doesn't it?

**Comment by jadedgnome** [comment]
> yes, I don't think I've ever changed that need, but it makes sense, doesn't it?

I upgraded to the latest release,  enabled history and relaunched the browser, the feature isn't visible.


https://user-images.githubusercontent.com/2940805/192967162-19a5f2e4-09dd-40b6-982e-4c39f550dac4.mp4

**Comment by uazo** [comment]
sorry also "always incognito"... :(
maybe we should write it somewhere...

**Comment by jadedgnome** [comment]
> sorry also "always incognito"... :( maybe we should write it somewhere...

Thank you, it works now but due to the history needing to be enabled I used shelter to clone it and run two separate instances.
