### ISSUE TITLE
Design Suggestion

### ISSUE THREAD

**Issue by SNaushadS** [bromite/bromite#137]
Hi there,

Thanks for the work on this.

I am a designer here, and got to know about Bromite through a post on new logo request.

My feedback:
- The bromite site does not communicate that its a Mobile Version

I think it will be better to communicate on the bromite site that this is a mobile only browser (when it evolves into a desktop browser, the message can be updated.).

Thanks again for the effort.

**Comment by csagan5** [comment]
There are never been real plans to add a desktop version, mostly because of the extra support that would be needed. In the "Download Bromite" section it says "Android v4.1 and above are supported.", is that not enough?

How would you improve the page?

**Comment by SNaushadS** [comment]
This is one of the ways, just making it clear its mobile only. The download section is way below the fold. From the top the page communicates that its a privacy centric browser and user makes an assumption that its across (bringing in their knowledge that Chrome is cross platform).

So some minor text changes across will help it be precise.

![image](https://user-images.githubusercontent.com/1532907/46002810-a510c080-c0cc-11e8-88ab-9487b5bcf73d.png)

**Comment by csagan5** [comment]
I have made some improvements to mention earlier that it is for Android. I expect users to read the README if they have an interest.

**Comment by SNaushadS** [comment]
In Usability, you can't expect users to read each and every detail. Its your project you are obviously good to keep it as is. I gave a feedback as i came on Bromite excited with the expectation of a browser. The communication on the page does not set the expectation first that its mobile only. 
Your assumption is that the audience who wish to use a privacy focussed browser are all developers and would understand the lingo of "README.md" file. 
Right now its more confusing as the logo is similar to that of Chrome which is cross-platform.
Such minor changes help communicate well.

Thanks for listening.

**Comment by csagan5** [comment]
@SNaushadS can you point explicitly where there is "developers lingo" in the README? The README is for the users of Bromite, not developers. There are 0 instructions for developers in that file.

I do not design the page for any type of reader/user, I design it for people that want to commit reading and understanding English (plain English, not any "lingo").

Yes, I do expect people to read each and every detail. I do not encourage "skim reading" in any form, and if a reader does it, he/she takes the bets in what percentage of the total is being understood.

The home page and the README are split in sections to help reading and understanding; I am not designing a mobile website, and even if I were, I would never design one for the target users that behave like you said.

> Your assumption is that the audience who wish to use a privacy focussed browser are all developers

No, I do not have assumptions about the audience. Anybody can use it as they want. I have **requirements** that if you want to understand the message of any text, you have to read it. I am not making any shortcut version of the text for whoever does not want to read.
