### ISSUE TITLE
Add flag to allow same-origin TLS websocket LAN traffic to pass through network partitioning

### ISSUE THREAD

**Issue by thomazz-nl** [bromite/bromite#1373]
### Is your feature request related to privacy?
Yes.

### Is there a patch available for this feature somewhere?
No.

### Describe the solution you would like
As concluded in https://github.com/bromite/bromite/issues/1327#issuecomment-917600637 Bromite's network partitioning features block TLS secured websocket traffic from a Bromite client to a service on the LAN (whether referenced by IP or FQDN) while the traffic is same-domain (and thus not a private network scanning risk as described in https://github.com/bromite/bromite/issues/590).

The solution I request is to add a flag "Allow same-origin LAN traffic for websockets". It will give power users a choice: be a bit more secure or have access to your local servers/services.

### Describe alternatives you have considered
* Choose to run the service without TLS as that does work (but it will force local only usage, as external access is unsafe).
* Run Chromite instead of Bromite as that does work (but you will miss out on **all** the extra security features added to Bromite)

**Comment by csagan5** [comment]
This feature request is not related to privacy; this is a feature request to allow disabling a privacy-protection feature and it is also about a fringe use-case.

Most users benefit from the current default flag values which enable network partitioning, and when disabling it you would not be protected anymore.

Next step would be to provide you a custom build to test if disabling the network partitioning flags really solves the issue you are experiencing; however last time we attempted this the collaboration did not work at all.

I will accept patches to provide a flag to disable this functionality but there is no intent to develop this.
