### ISSUE TITLE
120hz bug 

### ISSUE THREAD

**Issue by sdgrs546547Q** [bromite/bromite#1376]
On my Xiaomi poco x3 pro, bromite does not work at 120hz. I saw on Reddit that someone had a similar problem. Thanks

**Comment by Anurag-redvelvetcake** [comment]
Chromium based browsers don't work on high refresh rate displays and instead default to 60Hz.
Only chrome runs at native refresh rate of the display.
It's a well known issue there's nothing that bromite developers can do about it.
Only Xiaomi can whitelist chromium based browsers to take advantage of hight refresh rate.

**Comment by sdgrs546547Q** [comment]
> Chromium based browsers don't work on high refresh rate displays and instead default to 60Hz.
> Only chrome runs at native refresh rate of the display.
> It's a well known issue there's nothing that bromite developers can do about it.
> Only Xiaomi can whitelist chromium based browsers to take advantage of hight refresh rate.

I found a solution on the web. Type chrome://flags/ in the chrome search bar and again search for Android SurfaceControl. Disable that and the 120hz scrolling lag is gone!
