### ISSUE TITLE
[Question] Bromite WebView 69.0.3497.109 reports as Chrome/67.0.3396.87

### ISSUE THREAD

**Issue by sanjayen** [bromite/bromite#138]
I have tried explaining the possible bug in as simple a manner I can. Apologies in advance if something is not clear.

Keep up the good work with Bromite. I keep checking the Bromite.org website on a regular basis to check if any new update has been made available.

**Bromite SystemWebView version**
69.0.3497.109

Version: `69.0.3497.109`
Arch: `arm64`
Android version: 8.0.0

**Is the bug reproducible with latest version?**
Yes, am using Bromite browser for a long time now. Found out about Bromite System WebView today and decided to give it a try.

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
Not sure, I have changed the System WebView available on my rooted Mi5 device using the steps mentioned in the wiki - https://github.com/bromite/bromite/wiki/Installing-SystemWebView#installation-with-root-or-twrp

**Is the bug a crash?**
Not sure if this is a bug or if the webview version as displayed by WebView Test app for the Bromite System WebView is correct or not.

**Describe the bug**
I followed the steps as described in the wiki of replacing the System WebView. As I have a Xiaomi Mi 5 device, I had a folder called WebViewGoogle in the /system/app folder. I did a backup of the system WebView and deleted the same from the /system/app/WebViewGoogle folder. I rebooted the device and then installed Bromite System WebView downloaded from https://www.bromite.org/system_web_view. Using WebView Test to check the useragent, I realized that the default WebView was still getting used. I then used Titanium to freeze both the System WebView as well as the MiUiWebView so that only Bromite WebView was the only WebView remaining. I even checked inside the Developer Options > WebView Implementation to verify that Bromite WebView was selected as the default WebView.

Checking the WebView Info inside the WebView Test app linked from https://github.com/bromite/bromite/wiki/Installing-SystemWebView#verifying-installation, the Version is displayed as;

Chrome/67.0.3396.87 AppleWebKit/537.36

Is this version information correct as corresponding to Bromite System WebView 69.0.3497.109?

**Expected behavior**
I expected the Bromite System WebView to display the version Chrome/69.0.3497.109 instead of Chrome/67.0.3396.36.

**Screenshots**
Please see the attached 4 screenshots. 

![01-default-system-webview](https://user-images.githubusercontent.com/4888991/46093411-c9d96680-c1a6-11e8-8e36-977c5119de69.png)
![02-titanium-frozen-other-webviews](https://user-images.githubusercontent.com/4888991/46093429-d362ce80-c1a6-11e8-8712-f09e90ac6f4d.png)
![03-bromite-webview-default](https://user-images.githubusercontent.com/4888991/46093439-d9f14600-c1a6-11e8-8910-5d5b4310e28e.png)
![04-webview-test-version-check](https://user-images.githubusercontent.com/4888991/46093442-dd84cd00-c1a6-11e8-9b90-5a3a1a0b8907.png)

**Comment by csagan5** [comment]
This is by design, as an anti-fingerprinting mitigation technique.
