### ISSUE TITLE
[Privacy Feauture] Blocking and Allowing javascript of specific domains on each site and protection against cross site scripting attacks

### ISSUE THREAD

**Issue by spiderman973** [bromite/bromite#1380]
### Is your feature request related to privacy?
Yes

### Is there a patch available for this feature somewhere?

I am not aware of

### Describe the solution you would like

an option for blocking or allowing javascript for each domain and protection against cross site scripting attacks

### Describe alternatives you have considered

Strong Sandboxing so that malicious javascript will not be able escape the site and protection against cross site scripting attacks

**Comment by csagan5** [comment]
You can already enable/disable Javascript for each site.
