### ISSUE TITLE
[Privacy Feautue] Option to Set a Static IP address

### ISSUE THREAD

**Issue by spiderman973** [bromite/bromite#1390]
### Is your feature request related to privacy?
Yes

### Is there a patch available for this feature somewhere?
I am not aware of

### Describe the solution you would like
Option to Set a Static IP address because if you use VPN It can Sell your data

### Describe alternatives you have considered
No Alternative Solution

**Comment by csagan5** [comment]
You cannot change IP addresses with your browser.
