### ISSUE TITLE
Add Quad9 to Dns over HTTPS

### ISSUE THREAD

**Issue by Techguyprivate** [bromite/bromite#140]
Is your feature request related to privacy?
Yes.

Is there a patch available for this feature somewhere?
Yes. On Dnscrypt ,simple dns, quad9 website blog.

Describe the solution you'd like
Add quad9 dns : 9.9.9.9 which has tremoundous security advantages to Dns over https flags. Try to create a option in setting rather than in about:flags.

**Comment by csagan5** [comment]
Quad9 does not offer any DNS-over-HTTPS service.

**Comment by Techguyprivate** [comment]
My dear privacy warriors , now quad9 support dns over https ( doh). Request to add an option in about:flags entry . Quad9 has an advantage of being secure, malwarefree.

https://www.quad9.net/doh-quad9-dns-servers/

**Comment by csagan5** [comment]
@Techguyprivate please avoid name calling like "privacy warriors" and "dude"; you don't need any of that to talk about Bromite and privacy here. No need to reply, just keep it in mind for future comments.

I will consider adding the option for Quad9 for next release.

**Comment by csagan5** [comment]
Released in `70.0.3538.77`.
