### ISSUE TITLE
Major Problem, Apps crash. Bromite doesn't work at all.

### ISSUE THREAD

**Issue by privacyosint** [bromite/bromite#1409]
### Bromite version

Version: `92.0.4515.176`
Arch: `arm64`
Android version: (example: `10.0`)
Device model: (example: `SM-G964F`)

### Flags

These are the flags changed under `chrome://flags`:
No flags changes..

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is this bug happening in an incognito tab?
No

### Allow ads for the site; is the bug caused by the adblocker?
No

### Is the bug a crash?

Yes

-- or --

Yes, this is the crash dump:
```
<I don't know where the crash report is..>
```

### Describe the bug

The app crash every time I use them. There is something really wrong here. Please help me.
### Steps to reproduce the bug

Steps to reproduce the bug:
1. Installed bromite.
2. Try to load school first banking app, crashes.
3. Try opening Clash of clans, Crashing.
4. These apps need google services I think, How can I fix this? Why is this Happening?

Do not write "any website", specify which URLs can be used to reproduce the issue.

### Expected behavior
Something is wrong and I don't know what it is.

### Screenshots

![2](https://user-images.githubusercontent.com/90421861/134422869-884a439c-1a5b-4f04-86c2-9d4347f1686d.png)

**Comment by csagan5** [comment]
Please visit `chrome://crashes` and download the latest crash, then upload it here as an attachment to a comment.

**Comment by privacyosint** [comment]
Where do I put in `chrome://crashes`

**Comment by csagan5** [comment]
In the address bar.

**Comment by privacyosint** [comment]
@csagan5 
I can't open anything chrome....
![11](https://user-images.githubusercontent.com/90421861/134788115-68f55f01-42f9-47d7-8a9c-f98f7d58ae73.png)

**Comment by privacyosint** [comment]
I fixed it, I needed to add this. You need to make that more clear..
https://www.bromite.org/fdroid
