### ISSUE TITLE
Disable #enable-query-in-omnibox

### ISSUE THREAD

**Issue by Madis0** [bromite/bromite#143]
**Is your feature request related to privacy?**  
Yes

**Is there a patch available for this feature somewhere?**  
No

**Describe the solution you'd like**  
Currently URLs are hidden completely when searching through the Omnibox on mobile Chromium. 
To fight that, Bromite should disable the flag 
`#enable-query-in-omnibox`
 by default and in the future consider removing specific code altogether. 

FWIW, this is also planned for the desktop Chromium... 

**Describe alternatives you've considered**  
Users can disable the flag manually.

**Comment by csagan5** [comment]
Good idea, thanks for reporting; I will change the default value for this flag.

**Comment by csagan5** [comment]
Strangely this flag is already disabled by default according to the code, but in v69 and v70 I see it effectively enabled by default instead.

**Comment by csagan5** [comment]
Fixed in `70.0.3538.67`
