### ISSUE TITLE
[Feature Request] FIDO/FIDO2/WebAuthn implementation using COTECH's SDK

### ISSUE THREAD

**Issue by theanonymousexyz** [bromite/bromite#1433]
### Is your feature request related to privacy?

Yes.

### Is there a patch available for this feature somewhere?

https://github.com/cotechde/hwsecurity/
License: GPLv3

### Describe the solution you would like

I would like to see FIDO/FIDO2/WebAuthn implementation in Bromite. This will enhance both privacy and security, as users (especially on phones without Google Services) will be able to use security keys (NitroKey, SoloKey, YubiKey, etc.) on their phones, instead of relying on weaker 2FA. Currently, phones without Google Services don't have any way of supporting security keys, so users need to have two forms of 2FA on every account they want to be able to access from their phone, which not every online service supports (e.g. AnonAddy). A simple solution would be the above SDK, which is licensed under GPLv3 (same as Bromite) and is [successfully implemented in the Nextcloud app for Android](https://github.com/nextcloud/android/pull/4286). It doesn't depend on Google Services either.

This would make Bromite the first FIDO/FIDO2/WebAuthn enabled browser for degoogled phones.

### Describe alternatives you have considered

The only currently available alternative would require Google Services, and would also require using Google Chrome, which is not desirable from a privacy-perspective.

**Comment by wchen342** [comment]
The chromium FIDO modules in java are packed into several really big files (they have optimized things a bit recently though). The APIs on the chromium side are still there but all the internal logic needs to be reimplemented unless you can find a way to seamlessly convert play service calls into this SDK calls. So yes, it will require substantial effort. I would say about 50~60 hours of works at least.

**Comment by uazo** [comment]
> unless you can find a way to seamlessly convert play service calls into this SDK calls

technically there is probably an alternative.
their sdk uses webview apis that basically inject javascript into all pages that communicate with java through a bridge, "it would be enough" to emulate that, after all the webview code is available.

**Comment by csagan5** [comment]
I am closing this as nobody volunteered so far to implement the changes.
