### ISSUE TITLE
AMP still shows up on some websites

### ISSUE THREAD

**Issue by thanuj10** [bromite/bromite#146]
**Bromite version**

Version: `69.0.3497.109`
Arch: `arm`
Android version: Nougat

**Is the bug reproducible with latest version?**
`Yes`

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
`No`

**Describe the bug**
Bromite skips/removes AMP pages but some pages still show in the AMP form.

**To Reproduce**
1. Go to google search
2. Search for anything(News, tech)
3. Scroll down to results and try clicking on pages with AMP

**Expected behavior**
The AMP site shoudn't load while some pages still load the AMP version.

**Comment by csagan5** [comment]
@thanuj10 please edit the submission with a real example of search terms and a result that is in AMP form so that it can be reproduced and verified, then I can re-open it.

Also: on step 4 you say "see error". What error?
