### ISSUE TITLE
Bromite restarts (?) after "unfocusing" or switching back from another app

### ISSUE THREAD

**Issue by ghost** [bromite/bromite#1468]
### Bromite version

Version: 93.0.4577.110
Arch: ARM32
Android version: 9
Device model: SM-J330FN

### Flags

These are the flags changed under `chrome://flags`:

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is this bug happening in an incognito tab?
Yes

### Allow ads for the site; is the bug caused by the adblocker?
No

### Is the bug a crash?

No

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Switch to another app in the app history
2. Switch back
3. The browser appears
to be "restarted" and the already existing pages are gone.

Alternatively, unlock the phone and the browser is wiped.

Do not write "any website", specify which URLs can be used to reproduce the issue.

### Expected behavior

Websites should not be wiped or the browser reset.

The animations or the behavior of the browser are the same when starting it up.

(Issue is not as frequent to be able to test it in the side built vanilla version AND without losing significant privacy at the same time)

**Comment by uazo** [comment]
> what am I doing wrong

I do not know.

> Is the bug a crash? No

to see if it's a crash, please attach the result of `chrome://crashes`

**Comment by csagan5** [comment]
Architecture is missing; please edit the submission to specify that.

**Comment by IHateTheProgrammingClass** [comment]
I think I'm just going to let this go.

**Comment by IHateTheProgrammingClass** [comment]
@uazo I have also noticed this only hapoens when battery saving is turned on.
