### ISSUE TITLE
Option to "save" site settings directly from the site info popup

### ISSUE THREAD

**Issue by AzureB1te** [bromite/bromite#1483]
Not a question, but an idea

### Is your feature request related to privacy?

 It's sort of privacy related. Not directly, but could impact it.

### Is there a patch available for this feature somewhere?

 Not that I know of. 

### Describe the solution you would like

So Bromite provides instant acces to JS, and newly image toggles in the site info menu. This is great, as I, a user with a stricter threat model can run it with both disabled. Now, with a browsing mode like this, it's unavoidable to sometimes whitelist sites. And for some, that I don't come back to, it's good, that setting set here don't presist. But for some websites, that I consistently visit, it would be nice, is such a whitelist was easier to make. My idea, is to add a "save settings" toggle, that makes the rules permanent. At the moment, you'd have to navigate to the menu, and whitelist the site manually, for every single setting individually, which is just that painfull. 

### Describe alternatives you have considered

 N/A

**Comment by csagan5** [comment]
See #1496
