### ISSUE TITLE
Site setting permissions reset on exit in always incognito 

### ISSUE THREAD

**Issue by AzureB1te** [bromite/bromite#1496]
it's a bug report @uazo told me to create a report of what i initially tought was a feature or so. 

### Bromite version

Version: 94.0.4606.94
Arch: arm64
Android version: 11
Device model: HD1903

### Flags

These are the flags changed under `chrome://flags`:

Webgl disabled - on
Adaptive button in top toolbar - always new tab page
Isolate additional orogins - on & empty
Strict-origin isolation - on
TLS Post-Quantum Confidentiality enabled
Tab Groups, TG UI, and TG Continuation all disabled. 
Incognito screenshots - enabled

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is this bug happening in an incognito tab?
Yes

### Allow ads for the site; is the bug caused by the adblocker?
No

### Is the bug a crash?

No

### Describe the bug

If you run Bromite with always incognito mode, and any site setting disbaled by default, going to a random website, and whitelisting the disabled setting does not presist after a restart of the browser.
### Steps to reproduce the bug

Steps to reproduce the bug:
Enable always incognito under privacy settings.
Disable JS, Cookies or Images by default in Site Settings
Go to github.com
Open the quick site settings, by tapping the incognito sign next to the url, and select permissions and whitelist the site. 
Close Bromite
Go back to github.com
The blacklisted parameter should be disabled, our whitelist entry is earased.

Do not write "any website", specify which URLs can be used to reproduce the issue.

### Expected behavior

I expect the changed setting to presist after restarting bromite. 

### Screenshots

N/A

**Comment by csagan5** [comment]
> solving it is simple

First: do we want to solve it? Why? Where would the settings be stored? (in the regular profile, I assume)

**Comment by AzureB1te** [comment]
> First: do we want to solve it? Why? Where would the settings be stored? (in the regular profile, I assume)
>
Well, solving it would make Always Incognito a lot more convinient to use. As I said, I run JS and Images off by default, and creating a whitelist that presists would be helpfull. I know that this is possible if you type all the urls into the site settings exceptions, but you'd have to do that per site, per setting. I undertsand that there's only a few people who use theese crazy settings, so I can absolutely understand if you decide agains me.

**Comment by csagan5** [comment]
Fixed in `99.0.4844.55`.
