### ISSUE TITLE
Add canvas randomisation feature

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#15]
Study how to add some canvas randomisation feature

**Comment by csagan5** [comment]
This addon could be used for inspiration/material: https://github.com/kkapsner/CanvasBlocker

**Comment by csagan5** [comment]
Randomising the canvas does not help against fingerprinting; the problem should be addressed upstream; only thing we could do is disable completely the canvas.

Funnily enough, [Chromium official document](https://www.chromium.org/Home/chromium-security/client-identification-mechanisms) on this topic does not even mention canvas, albeit being one of the biggest finds of [EFF's study](https://wiki.mozilla.org/Fingerprinting).

Closing for now.

**Comment by dimqua** [comment]
>Randomising the canvas does not help against fingerprinting

Why do you think so?

**Comment by csagan5** [comment]
Because the only mitigation strategy is a slight randomisation, that makes it unique every time it is being read.

This makes your fingerprint every time unique, which collides with the approach of "trying to not be unique" and melding with the mass. If whoever is fingerprinting decides to acknowledge this, then it becomes just 1 bit of information.

**Comment by csagan5** [comment]
Re-opening as I plan to experiment disabling the canvas methods that are used for fingerpriting.

**Comment by csagan5** [comment]
The methods used for fingerprinting have been disabled via IDL since version 65.0.3325.190
