### ISSUE TITLE
Excessive battery usage

### ISSUE THREAD

**Issue by koendv** [bromite/bromite#151]
I'm quite happy with the clean, ad-free browsing experience Bromite provides. But the battery usage is excessive, both on mobile phone and tablet. As measured by AccuBattery the Bromite browser is the main drain on my battery, and uninstalling the browser has improved my mobile phone experience.

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear here on Github via mobile; I had always been assuming that the issue template was being ignored for opened issues like this, sorry for that.

All issues not following the template are considered invalid.
