### ISSUE TITLE
Tab groups stoped working? 

### ISSUE THREAD

**Issue by TMS-Namespace** [bromite/bromite#1510]
Hi, 

I used to use tab groups,  that I enabled in flags page,  but in the last couple versions,  tab groups are not working at all,  even so I checked that they are enabled. 

Any reason for that?  They are very useful.. Thx.

**Comment by BurhanDanger** [comment]
Is it working on newer versions now ? I'm stuck on v92 cause it's the last one that have "Open in new tab in group", and I'm pretty much dependent on this feature.
