### ISSUE TITLE
Allow new tab page customization

### ISSUE THREAD

**Issue by KatoriYuu** [bromite/bromite#1519]
### Is your feature request related to privacy?
Somewhat related, if people want their browsing history to be hidden in the new tab page.

### Is there a patch available for this feature somewhere?
Yes, there's a patch in ungoogled chromium project.
https://github.com/Eloston/ungoogled-chromium/pull/1686

### Describe the solution you would like
Follow the merge request

### Describe alternatives you have considered
None

**Comment by csagan5** [comment]
This was possible until the removal of the patch due to #517; we can try re-introducing it.

**Comment by uazo** [comment]
> we can try re-introducing it.

possibly also for the always incognito? but without favicons.

**Comment by csagan5** [comment]
@uazo you can see my attempt here: https://github.com/bromite/bromite/pull/1579

Due to the introduction of the `HomepageManager` this is more difficult than expected. Feel free to continue it if you like, otherwise we will not implement this. Too complex for the added benefit.

**Comment by csagan5** [comment]
Fixed in `96.0.4664.54`.

**Comment by cecxl** [comment]
in my opinion it doesn't make sense for privacy-oriented browser to even have frequent visited messages on the front page, what if someone looks over your shoulder and sees something you don't want them to see. that along with recent tabs in the menu are excessive. it would make more sense if NTP had bookmarks or manually added pages only by default.

**Comment by csagan5** [comment]
> in my opinion it doesn't make sense for privacy-oriented browser

Everyone has opinions and it is impossible to have a browser that matches everybody's opinions.

> what if someone looks over your shoulder

You disable the NTP page.

> recent tabs in the menu

You disable history.

**Comment by mrspiderbrain** [comment]
Use homepage, use for new tabs and set as "about:blank" works well for me.
