### ISSUE TITLE
Duplicate patchs for disable-pull-to-refresh-effect

### ISSUE THREAD

**Issue by uazo** [bromite/bromite#1522]
I know, it will be closed automatically, but @csagan5 we have two identical patches that cause me to dcheck failed in the startup

Add-flag-to-disable-pull-to-refresh-effect.patch
Revert-flags-remove-disable-pull-to-refresh-effect.patch

**Comment by csagan5** [comment]
@uazo you can use discussions or the project repo

**Comment by uazo** [comment]
sure, as you prefer, but this time there is little to discuss!

I thought about opening an issue to track the change, also because I often lose the verification of the direct commits on the master you do (github does not notify me of these things), or maybe, you could also do the pull-requests when you modify code?

for example, [this](https://github.com/bromite/bromite/commit/413c2c76452d10b78da9b6c2f7c71e102f15a743#diff-aebd3fbbd8aa7b0916984b7321f8847e60983536c7d931c301360d1856a8adceL18) is not quite correct, because so it is not tied to any actual flag, but I didn't notice it before the user reported, maybe I could have told you earlier

**Comment by csagan5** [comment]
> you could also do the pull-requests when you modify code?

Both patches apply correctly, so I do not understand where the duplication is. One restores the switch, the other adds the flag.

> you could also do the pull-requests when you modify code?
> for example, [this](https://github.com/bromite/bromite/commit/413c2c76452d10b78da9b6c2f7c71e102f15a743#diff-aebd3fbbd8aa7b0916984b7321f8847e60983536c7d931c301360d1856a8adceL18) is not quite correct, because so it is not tied to any actual flag, but I didn't notice it before the user reported, maybe I could have told you earlier

What are the changes you are referring to in [this comment](https://github.com/bromite/bromite/issues/1154#issuecomment-856501051)? I assume you had reviewed the changes already because of [this other comment](https://github.com/bromite/bromite/issues/1154#issuecomment-859379344).

I cannot tell whether these changes I made are due to an automatically applied patch (with increased fuzz factor) or manual changes, but first let's figure out the above.

> there is little to discuss

Does not look like that; the issue is not valid and thus cannot stay open, and since the issue is closed it will not have any visibility.

**Comment by uazo** [comment]
> so I do not understand where the duplication is.

maybe it's easier if I fix it so we understand each other.

> I assume you had reviewed the changes already because of this other comment.

I will open a new issue for that.

**Comment by uazo** [comment]
> maybe it's easier if I fix it so we understand each other.

I checked, I can't fix it except by removing one of the two patches

> so I do not understand where the duplication is. One restores the switch, the other adds the flag

the duplication is in the `kFeatureEntries` list in `chrome/browser/about_flags.cc`

```
Add-flag-to-disable-pull-to-refresh-effect.patch

#if defined(OS_ANDROID)
    {switches::kDisablePullToRefreshEffect, flag_descriptions::kDisablePullToRefreshEffectName,
     flag_descriptions::kDisablePullToRefreshEffectDescription, kOsAndroid,
     SINGLE_VALUE_TYPE(switches::kDisablePullToRefreshEffect)},
#endif
```

```
Revert-flags-remove-disable-pull-to-refresh-effect.patch

    {"disable-pull-to-refresh-effect",
     flag_descriptions::kPullToRefreshEffectName,
     flag_descriptions::kPullToRefreshEffectDescription, kOsAndroid,
     SINGLE_DISABLE_VALUE_TYPE(switches::kDisablePullToRefreshEffect)},
```

since `switches::kDisablePullToRefreshEffect == "disable-pull-to-refresh-effect"`

> I will open a new issue for that.

I'm sorry, `disable-external-intent-requests` actually works but on the contrary!
if you want, just edit:

```
    {"disable-external-intent-requests", flag_descriptions::kDisableExternalIntentRequestsName,
     flag_descriptions::kDisableExternalIntentRequestsDescription, kOsAll,
     SINGLE_DISABLE_VALUE_TYPE("disable-external-intent-requests")},
```

to

```
    {"disable-external-intent-requests", flag_descriptions::kDisableExternalIntentRequestsName,
     flag_descriptions::kDisableExternalIntentRequestsDescription, kOsAll,
     SINGLE_VALUE_TYPE("disable-external-intent-requests")},  <--- SINGLE_VALUE_TYPE
```

**Comment by csagan5** [comment]
> What are the changes you are referring to in [this comment](https://github.com/bromite/bromite/issues/1154#issuecomment-856501051)?

I wanted to reconstruct this as well ^

> I'm sorry, `disable-external-intent-requests` actually works but on the contrary!
> if you want, just edit:

All flags that say "disable" should use the `SINGLE_DISABLE_VALUE_TYPE`?

I have applied the changes you suggested in #1532

> > maybe it's easier if I fix it so we understand each other.
> 
> I checked, I can't fix it except by removing one of the two patches

Fix what? An error?

**Comment by uazo** [comment]
> I wanted to reconstruct this as well ^

more this https://github.com/bromite/bromite/issues/1200 
anyway you're right, my fault, sorry

> All flags that say "disable" should use the SINGLE_DISABLE_VALUE_TYPE?

I think so, it depends if you want the switch/flag to be added with on or off

> Fix what? An error?

a [DCHECK](https://source.chromium.org/chromium/chromium/src/+/main:components/flags_ui/flags_state.cc;l=673;drc=b6777804f3e4f89dc97cf754a3578ff17b5a104c?q=FlagsState::AddSwitchMapping&ss=chromium%2Fchromium%2Fsrc)

**Comment by csagan5** [comment]
I have removed the duplicate; please check if the DCHECK passes now.
