### ISSUE TITLE
Clear Data On Exit

### ISSUE THREAD

**Issue by blogmangit** [bromite/bromite#1525]
### Is your feature request related to privacy?

Yes
### Is there a patch available for this feature somewhere?

Yes Patch is present in brave repo

### Describe the solution you would like

Plz implement clear data on exit. I know this has been discussed earlier & the solution is to use always incognito but there is a problem regarding that. If we use always incognito then links are not opened in external apps like say reddit links in reddit app, playstore links in playstore app etc. if always incognito is enabled then all links open in bromite which sometimes is not useful and that is why I am requesting to reconsider this feature. 

### Describe alternatives you have considered

No alternatives considered

**Comment by csagan5** [comment]
> If we use always incognito then links are not opened in external apps like say reddit links in reddit app, playstore links in playstore app etc. if always incognito is enabled then all links open in bromite

@uazo I think this is covered by #1514?

**Comment by uazo** [comment]
no, that's another thing.
the user asks to be able to open applications from url in always incognito. like this:
![1](https://user-images.githubusercontent.com/29201891/140067253-eb298bda-0eec-424b-9edf-1ce3fcc891a6.gif)

The relative code is [ExternalNavigationHandler.java](https://source.chromium.org/chromium/chromium/src/+/main:components/external_intents/android/java/src/org/chromium/components/external_intents/ExternalNavigationHandler.java) but we must be careful because the referral or other data may be passed.

**Comment by csagan5** [comment]
> The relative code is [ExternalNavigationHandler.java](https://source.chromium.org/chromium/chromium/src/+/main:components/external_intents/android/java/src/org/chromium/components/external_intents/ExternalNavigationHandler.java) but we must be careful because the referral or other data may be passed.

Doesn't the browser currently display a question "Do you want to leave incognito?" when this happens?

**Comment by uazo** [comment]
> "Do you want to leave incognito?" when this happens?

no, it doesn't happen to me

**Comment by csagan5** [comment]
> > "Do you want to leave incognito?" when this happens?
> 
> no, it doesn't happen to me

It's there on that class you linked:
```
        // The user is about to potentially leave the app, so we should ask whether they want to
        // leave incognito or not.
        if (!intentTargetedToApp) {
            return handleExternalIncognitoIntent(
                    targetIntent, params, fallbackUrl, shouldProxyForInstantApps);
        }
```

**Comment by uazo** [comment]
yes, I had seen it, but checking with the `LOG()` does not even go there.

**Comment by blogmangit** [comment]
guys I was just curious any progress on this?

**Comment by blogmangit** [comment]
guys any progress on this how this issue is a duplicate issue please anyone guide me its the only feature bromite is missing

**Comment by blogmangit** [comment]
I don't understand why there are two separate setting for incognito but no clear data on exit please guys implement this brave already did that a long ago. if clear data on exit is implemented we might not even need incognito. 

![20_03_2022_23_24_09.jpg](https://user-images.githubusercontent.com/92579403/159175951-edb50631-445e-4d79-a9fe-f1513eaaf74a.jpg)

**Comment by blogmangit** [comment]
guys please implement this feature or else bromite is taking huge cache say 2 or 3 gigs. Also enabling incognito mode doesn't open links in external apps ie always opens in bromite. This is an issue. Please implement clear data on exit like brave vivaldi edge samsung internet browser did.

**Comment by blogmangit** [comment]
Here is the patch from brave for this https://github.com/brave/brave-core/blob/master/patches/chrome-browser-browsing_data-chrome_browsing_data_remover_delegate.h.patch

**Comment by bat999** [comment]
Hi
The feature request...
"An option to automatically erase browsing history at end of session"
I would find this useful.

Consider the person who...
Does not use Incognito Mode.
Does need browsing history available during a session.

I don't think this feature request is strictly about privacy.
But many people think it is good practice to erase browsing history after use.
It would be a convenience to have it done automatically.

Maybe this feature request would need a new patch to be developed and maintained.
Or maybe it can be added to the current Privacy and Security --> Expiry history days threshold.

**Comment by bat999** [comment]
Duplicate of #426
