### ISSUE TITLE
Permanently deactivate support for origin-trials from meta-tag `http-equiv="origin-trial"`

### ISSUE THREAD

**Issue by uazo** [bromite/bromite#1530]
### Is your feature request related to privacy?

yes, in the sense that a function is made active without the user knowing it

### Is there a patch available for this feature somewhere?

no

### Describe the solution you would like

it seems that some functions (such as floc) can be activated from the outside through the management of the meta tag
ref: https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/explainer.md
to check a token: https://googlechrome.github.io/OriginTrials/check-token.html
things [that can be activated](https://source.chromium.org/chromium/chromium/src/+/main:out/Debug/gen/third_party/blink/renderer/core/origin_trials/origin_trials.cc
)

it currently seems active to me
```
    {
      name: "ThirdPartyOriginTrials",
      status: "stable",
    },

source: third_party/blink/renderer/platform/runtime_enabled_features.json5
```

note: from what I understand the third_party are the ones from the navigation because the first parts are those inserted through the dev tools by the user

### Describe alternatives you have considered

change [ProcessHttpEquivOriginTrial](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/loader/http_equiv.cc;l=147;drc=6e123f3a055b62946261e57c5742dc3820ffb6d1;bpv=1;bpt=1) and/or disable in `runtime_enabled_features.json5`

**Comment by csagan5** [comment]
> it currently seems active to me

Can you verify this? Perhaps with some logging to see if that code is triggered.

**Comment by uazo** [comment]
I confirm that the code passes from there.
going up the chain the point where it is activated is [OriginTrialPolicyImpl::IsOriginTrialsSupported()](https://source.chromium.org/chromium/chromium/src/+/main:components/embedder_support/origin_trials/origin_trial_policy_impl.cc;l=56;drc=b6777804f3e4f89dc97cf754a3578ff17b5a104c;bpv=1;bpt=1)

changing from

`
11-03 13:58:25.071 13341 13356 I chromium: [INFO:origin_trial_context.cc(546)] ---EnableTrialFromToken: token_result = kExpired, token = "Anb2GUnhMjfTIX0D2a4a6NPAqPI5GaxxRAiF81XTjHJ2qK4E3Hw3VFM4eaJBgRzz45CNPt624audv+wHOJwfAAEAAABieyJvcmlnaW4iOiJodHRwczovL2dvb2dsZS5jb206NDQzIiwiZmVhdHVyZSI6IlRydXN0VG9rZW5zIiwiZXhwaXJ5IjoxNjI2MjIwNzk5LCJpc1N1YmRvbWFpbiI6dHJ1ZX0="
`

it becomes

`
11-03 14:11:14.278 13611 13626 I chromium: [INFO:origin_trial_context.cc(546)] ---EnableTrialFromToken: token_result = kNotSupported, token = "Anb2GUnhMjfTIX0D2a4a6NPAqPI5GaxxRAiF81XTjHJ2qK4E3Hw3VFM4eaJBgRzz45CNPt624audv+wHOJwfAAEAAABieyJvcmlnaW4iOiJodHRwczovL2dvb2dsZS5jb206NDQzIiwiZmVhdHVyZSI6IlRydXN0VG9rZW5zIiwiZXhwaXJ5IjoxNjI2MjIwNzk5LCJpc1N1YmRvbWFpbiI6dHJ1ZX0="
`

**Comment by csagan5** [comment]
Thanks for checking; this is terrible.

I will add a patch that disables this from `third_party/blink/renderer/platform/runtime_enabled_features.json5`.

**Comment by uazo** [comment]
> Thanks for checking; this is terrible.

I agree.

> I will add a patch that disables this

maybe I'm afraid it's not enough because I've seen trials enabled by default, I keep checking

**Comment by csagan5** [comment]
> > I will add a patch that disables this
> 
> maybe I'm afraid it's not enough because I've seen trials enabled by default, I keep checking

In that case we should solve the problem for all trials, none should be enabled by default; only exceptions should be made for problems related to quirks for chipsets (like the Vulkan-related issues).

**Comment by uazo** [comment]
> only exceptions should be made for problems related to quirks for chipsets 

perfect, I'll take it into account

**Comment by csagan5** [comment]
> > only exceptions should be made for problems related to quirks for chipsets
> 
> perfect, I'll take it into account

I am referring to the situation where Vulkan or hardware acceleration was disabled in Chromium but enabled in Bromite; that time I concluded that it could be due to origin trials enabled/disabled by default in Chromium, and if that conclusion was correct then in Bromite all field trials would be as we want them e.g. not active.

I will wait for your findings.

**Comment by uazo** [comment]
I confirm that I have not found trials that refer to flags of the gpu.

However, I realized that the blink code must also be analyzed, which before now I thought was a "simple" graphic render of html.
for example, I noticed that regarding the default configuration, there is no single source of truth, especially if a feature is considered stable.
for example client hits: [this](https://github.com/bromite/bromite/blob/master/build/patches/Override-UA-client-hint-for-model.patch#L37) is not enough, because the functionality in blink is stable and the deactivation is not acknowledged (ie, in that case the switch is passed only if ON, but if OFF it is not removed).
the modification must also be made in `third_party\blink\renderer\platform\runtime_enabled_features.json5`, so for example:
```
    {
      name: "FeaturePolicyForClientHints",
      //status: "stable",
    },
```
regarding the deactivation of origin trials, in my opinion the patch needs to modify 
- [OriginTrialPolicyImpl::IsOriginTrialsSupported](https://source.chromium.org/chromium/chromium/src/+/main:components/embedder_support/origin_trials/origin_trial_policy_impl.cc;l=56;drc=b6777804f3e4f89dc97cf754a3578ff17b5a104c;bpv=1;bpt=1) because it is the source of truth of the function (blink side, strangely it is delegated by a function passed by reference by chromium and not by mojom like the other calls, perhaps for historical reasons)
- [kDefaultPublicKey](https://source.chromium.org/chromium/chromium/src/+/main:components/embedder_support/origin_trials/origin_trial_policy_impl.cc;l=24;drc=b6777804f3e4f89dc97cf754a3578ff17b5a104c) because it is the public key that is used to verify the first parties (and without the private key there is no way to enter a correct value through the developer tools, and therefore this possibility must also be eliminated)

the other points I would keep them as they are, but I would put in `OriginTrialPolicyImpl` all the "Set" functions private (they are currently public), so that the compiler will eventually tell us if some point of the code in the future is called externally.
I can make a proposal as soon as we release v95 so I work on the final patches.

**Comment by csagan5** [comment]
> (ie, in that case the switch is passed only if ON, but if OFF it is not removed).
> the modification must also be made in `third_party\blink\renderer\platform\runtime_enabled_features.json5`

I am aware of this, but sometimes I forget about the disable/enable behaviour and to look in the runtime enabled features; perhaps I should complete that project to follow Chromium features in the code across releases.

> in my opinion the patch needs to modify

Sure; I have applied alll the changes.

**Comment by csagan5** [comment]
> However, I realized that the blink code must also be analyzed, which before now I thought was a "simple" graphic render of html.

It is not; please continue with the scrutiny, I am sure there is plenty of currently active features (both in Blink and in Chromium) that we could get rid of.

**Comment by uazo** [comment]
> but sometimes I forget about the disable/enable behaviour and to look in the runtime enabled features; perhaps I should complete that project to follow Chromium features in the code across releases.

we should think about doing something that can automatically warn us of these situations.

> Sure; I have applied alll the changes.

wow, what a speed.

> please continue with the scrutiny

sure, because, by answering [this](https://github.com/bromite/bromite/issues/1516#issuecomment-956959143) maybe I came up with a way to do it "scientifically" (maybe, for now it's just an idea)

**Comment by uazo** [comment]
I found another point to touch [NavigationRequest::ForceEnableOriginTrials()](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/navigation_request.cc;l=6549;drc=e723720b51167bcdb24b8867b1462af059aa0072;bpv=1;bpt=1), currently only used by chromeos, but the api is available.
in my opinion the change must also be made in `third_party/blink/renderer/core/loader/document_loader.cc` and `content/renderer/render_frame_impl.cc`

**Comment by csagan5** [comment]
Fixed in `95.0.4638.78`.

@uazo sure, send a PR to update the existing patch?

**Comment by uazo** [comment]
> sure, send a PR to update the existing patch?

sure, you would leave the issue open for me, otherwise I risk forgetting it.

**Comment by uazo** [comment]
> and without the private key there is no way to enter a correct value through the developer tools, and therefore this possibility must also be eliminated

also on this I wrote an inaccuracy, the script for generating the tokens is in `tools/origin_trials/generate_token.py`
