### ISSUE TITLE
Canvas fingerprinting mitigations working only for JPEG

### ISSUE THREAD

**Issue by DecodeMehh** [bromite/bromite#154]
**Bromite version**

Version: 70.0.3538.67
Arch: arm64
Android version: Oreo (8.1)

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
It is a Bromite feature

**Is the bug a crash?**
no

**Describe the bug**
Canvas fingerprint does not protect anymore

**To Reproduce**
1. Go to 'https://browserleaks.com/canvas'
2. Scroll down to 'Signature'
4. Refresh the page
5. Look if it has changed

**Expected behavior**
Canvas fingerprint signature should change everytime you refresh the page

**Screenshots**
No need.

**Comment by DecodeMehh** [comment]
also tested with https://panopticlick.eff.org/ and got same result.

**Comment by csagan5** [comment]
It can be tested with https://www.bromite.org/detect as well.

**Comment by DecodeMehh** [comment]
> It can be tested with https://www.bromite.org/detect as well.

Yes even with this one my convas fingerprint is same.

**Comment by csagan5** [comment]
Fixed in `70.0.3538.71`
