### ISSUE TITLE
Update user agent to remove build number

### ISSUE THREAD

**Issue by Madis0** [bromite/bromite#156]
**Is your feature request related to privacy?**
Yes

**Is there a patch available for this feature somewhere?**
In upstream

**Describe the solution you'd like**
In Chromium 70, the user agent [no longer includes the OS build number.](https://www.chromestatus.com/feature/4558585463832576)
Bromite should match that because while the Bromite one is frozen to a specific version and model, the build number still may increase the fingerprint-ability because it usually varies by region. 

I don't suggest doing it right away though, it would be better to consider it as a milestone for version 71.

**Describe alternatives you've considered**
Use a different Chromium-based browser that doesn't include it

**Comment by csagan5** [comment]
Nice to see that this is being taken care of upstream!

However it will be a while until v70 becomes the most common version used, and the current user agent changes in Bromite do refer to the most common used versions per Android OS version.

There are currently no plans to change the current patch (Android OS 8 and above get v67), ping me here when v70 becomes the most used? I would re-open this and change the patch then, but I think it will take a (relatively) long while.

**Comment by csagan5** [comment]
> [According to](https://caniuse.com/usage-table) [three](https://www.w3counter.com/globalstats.php) [sources](https://clicky.com/marketshare/global/web-browsers/versions/), Chrome 70 is now the most used Chrome version.

The versions I am using are still very common in the wild; I will tend to an update.

> Makes me wonder why do you even use [different Chrome versions per OS](https://github.com/bromite/bromite/blob/master/patches/BRM053_User-Agent-anonymize.patch)?

The most common version and phone model distribution is different by Android (major) version.

> You should consider Play Store updates too, which even the version numbering out for everyone.

This would be possible if Google published all installs by phone model, which is not the case.

Original upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=494452 - ignored back then in 2015, even if scammers could use the information proficiently
New upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=860229 - this has caused the Build ID to be removed (so harder for attackers to know the specific vulnerabilities your Android OS has)

The phone model is still there; until phone model is removed from the UA, I cannot retract this patch.

**Comment by Madis0** [comment]
>The versions I am using are still very common in the wild; I will tend to an update.
>The most common version and phone model distribution is different by Android (major) version.

After thinking about it and it seems you are referring to the Webview more, rather than the browser itself. Although that also has been Play store-updatable since Android 5.0. 

So... what is the actual concern here worth waiting for? Majority of the world uses Play Store, with the big exception of China, but assuming that would give other concerns anyway (IP geolocation match, default languages etc.)

>this has caused the Build ID to be removed (so harder for attackers to know the specific vulnerabilities your Android OS has)

Yes, that's good, now maybe we could spoof the Android version too as I suggested to further limit the attack surface.

>The phone model is still there; until phone model is removed from the UA, I cannot retract this patch.

Sure, don't retract the patch, just change it to include less information (as feasible).

**Comment by csagan5** [comment]
@Madis0 no UA can be spoofed if you do not know the distribution by phone model. The sources you pointed at only show the major browser version, they are useless for the purpose of spoofing the UA in Bromite.

None of the sources you mentioned publishes the source data they use, as far as I could see.

I am not going to spoof the Android version as it can be detected in other ways.

**Comment by Madis0** [comment]
> no UA can be spoofed if you do not know the distribution by phone model. The sources you pointed at only show the major browser version, they are useless for the purpose of spoofing the UA in Bromite.

>None of the sources you mentioned publishes the source data they use, as far as I could see.

That makes me more curious about what sources do you use and how do you judge their data.

I can't seem to understand how using the earliest released version (the one that came with the device) helps get anonymous when in real life, people get automatic updates to the latest browser version anyway (gradual rollout, but still). 

Only thing that could stay the same are major _OS_ versions per device model, as people are more likely to ignore those updates (due to the necessity of big download, restarting and waiting).

**Comment by csagan5** [comment]
@Madis0 if you can find a sizable and trustable public source of data with full UAs and frequency, we can use that. You can consider my selection random until that.

I think you misunderstand why the UA is spoofed in Bromite: it is spoofed to not disclose the exact version of the Bromite build, which is updated usually more often than upstream, and not to be always the latest most common version. I am not going to change it to achieve such goal.

You could also check how Tor browser does this, but it is really not important; the only important bit is not disclosing the exact specific Chromium build, OS build and phone model.

**Comment by Madis0** [comment]
>I think you misunderstand why the UA is spoofed in Bromite: it is spoofed to not disclose the exact version of the Bromite build, which is updated usually more often than upstream, and not to be always the latest most common version. I am not going to change it to achieve such goal.

I understand and support that idea, the problem I found is that the Bromite UA seems to lag _too much_ behind, especially if you differ it between OS versions, which in turn could make Bromite even more fingerprintable.

For example, [Chromium](https://chromiumdash.appspot.com/schedule) and [Chrome](https://chromereleases.googleblog.com/2018/12/chrome-for-android-update.html) 71 were released 4 days ago. Therefore it is safe to assume that v70 and somewhat v69 are still commonly used. 

And yes, the analytics sources claim that:

- 71: 0.07% | ? | 12.71%
- 70: 25.39% | 38.30% | 47.41%
- 69: 1.33% | 4.30% | 1.93%

However, when Bromite uses versions 67, 63 and 62, of course it is going to be more fingerprintable due to that fact because others have updated long ago. 

>It should be noted that Chromium forks like Samsung Browser, Opera and Edge do use older versions, however they also like to append their name to the UA so it cannot be considered the same as Chrome/Chromium.

>You could also check how Tor browser does this

Totally different scope. Not only does Tor browser have low marketshare anyway, it also uses an [ESR version of Firefox](https://www.mozilla.org/en-US/firefox/organizations/) (and therefore old version number), something that mostly companies use and Chromium has never had.

>but it is really not important; the only important bit is not disclosing the exact specific Chromium build, OS build and phone model.

You don't reveal your build and phone, but you may reveal the use of Bromite. Why not try to hide that fact too?

**Comment by csagan5** [comment]
> You don't reveal your build and phone, but you may reveal the use of Bromite. Why not try to hide that fact too?

That is not possible. It can be detected in many other ways; the goal of this patch is to not disclose which specific version of Bromite is being used.

> Bromite UA seems to lag _too much_ behind, especially if you differ it between OS versions, which in turn could make Bromite even more fingerprintable.

Hiding that Bromite is being used is not the main goal; as I said the goal is to hide just which specific build is being used (and upstream should do that too in my opinion).

I have already said I will update the versions in the [reopening comment](https://github.com/bromite/bromite/issues/156#issuecomment-445449741), I think that's sufficient for the purpose of simply hiding the specific build tag of Bromite.

**Comment by csagan5** [comment]
There is also a "trail" effect on most bodies of analytics data available: they can provide a percentage over the whole dataset or a smaller window, but without knowing how small is the window (and distribution per device, since that information is included in the UA) we cannot use the percentage for more advanced purposes.

For example Android 4 has a bigger usage in the past and a small one currently, so if you measure over historical use the most recent UA have a very small impact and do not qualify as most common.

In next release Bromite will use `70.0.3538.80` and `69.0.3497.100`; the original plan was to align this declared version with the current stable version, so it might be done that way too after all (but has little importance, as I explained).

**Comment by csagan5** [comment]
Fixed in `71.0.3578.88` (not yet released).
