### ISSUE TITLE
[feature removal request] Privacy Sandbox in Bromite? 

### ISSUE THREAD

**Issue by pixincreate** [bromite/bromite#1560]
### Is your feature request related to privacy?
Yes

### Is there a patch available for this feature somewhere?
Privious versions

### Describe the solution you would like
Remove the controversial Privacy Sandbox option by Google. It's a nightmare for privacy AFAIK.

### Describe alternatives you have considered
Nothing.

**Comment by pixincreate** [comment]
![Screenshot_20211109-230531_Bromite](https://user-images.githubusercontent.com/69745008/140975440-43ef6cde-7232-422f-b4c7-0aad3cbab46e.png)
Screenshot of existence of privacy Sandbox feature in the latest version of Bromite.

**Comment by csagan5** [comment]
> Screenshot of existence of privacy Sandbox feature in the latest version of Bromite.

There is no such feature, only the UI is present.

**Comment by pixincreate** [comment]
So technically it doesn't work?

**Comment by uazo** [comment]
> So technically it doesn't work?

yes, it doesn't work, all internal flags are disabled.
obviously, don't turn it on.

**Comment by pixincreate** [comment]
What's the need for its existence in such case? It's worth removing right? 
> obviously, don't turn it on.

What's does it mean? I shouldn't turn the option on even if it doesn't work at the first place?

**Comment by BUAWF** [comment]
I've just checked, it is On by default.
I haven't touched it just saw it now.

**Comment by csagan5** [comment]
It does nothing whether it is on or off; it will be removed in next release.

**Comment by csagan5** [comment]
Fixed in `95.0.4638.79`.
