### ISSUE TITLE
#disallow-doc-written-script-loads flags does not work

### ISSUE THREAD

**Issue by uazo** [bromite/bromite#1587]
### Bromite version

Version: `95.0.4638.78`
Arch: `x86`
Android version: `9.0`
Device model: `emulator`

### Flags

`#disallow-doc-written-script-loads`

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is this bug happening in an incognito tab?

No

### Allow ads for the site; is the bug caused by the adblocker?

No

### Is the bug a crash?

No

### Describe the bug

the flag should block the ability for javascript to modify the dom inline, but it doesn't work.
it works fine in chromium, where it is _enabled by default_.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to 'https://uazo.github.io/bromite/test_document_write.html'
2. You see `you shouldn't see this` but it shouldn't appear

### Expected behavior

respect the flag

**Comment by rustforfuture** [comment]
I tested this and confirm it.

**Comment by csagan5** [comment]
@uazo any idea why it doesn't happen in Chromium? These blink options are not really something changed in Bromite.

**Comment by uazo** [comment]
> any idea why it doesn't happen in Chromium?

yes, i already looked, guess what? fieldtrials.. 
there is some part of the code that is not being executed, maybe due to some patch, but i still haven't found out where and what it is.
the bug is still old, it has existed from many versions ago, but I had not noticed it before and it is also related to the flag that disables quic.

**Comment by csagan5** [comment]
> it is also related to the flag that disables quic.

That doc-written script loading is related to QUIC is...surprising.

**Comment by uazo** [comment]
> That doc-written script loading is related to QUIC is...surprising.

no, I badly explained myself, quic flag is under fieldtrial.

**Comment by csagan5** [comment]
It looks like we are still not releasing Bromite with the same field trials that Chromium has; we should probably fetch the default field trials from their servers if it is really the case that the default one are different/bogus.

**Comment by csagan5** [comment]
The flag says "do not allow script loading from document.write", it does not say "disallow document.write".

Please post the code snippets in issue next time.

**Comment by uazo** [comment]
> The flag says "do not allow script loading from document.write", it does not say "disallow document.write".

you are right, but I do not explain anyway then why in chromium it is not seen.
i will check better, thanks.

> Please post the code snippets in issue next time.

of course you're right.

**Comment by csagan5** [comment]
> > The flag says "do not allow script loading from document.write", it does not say "disallow document.write".
> 
> you are right, but I do not explain anyway then why in chromium it is not seen. i will check better, thanks.

Perhaps there is a different flag there, but toggling this one should have no effect.
