### ISSUE TITLE
[Feature Request] Add an option to automatically clear history when leaving the browser (in normal browsing mode, not incognito mode).

### ISSUE THREAD

**Issue by Random-Person213** [bromite/bromite#1604]
### Is your feature request related to privacy?
Yes

### Is there a patch available for this feature somewhere?
Not sure.

### Describe the solution you would like
What I'm requesting is to add an option that clears your browsing history when you leave the browser (in normal browsing mode, not incognito mode) and I want the option to clear the history when I leave the browser in any way, it may include hitting the home or back button in the android device, or the app crashing.

### Describe alternatives you have considered
Add an exit button that if you press the browser closes and your history gets cleared.

**Comment by bat999** [comment]
Duplicate of #426
