### ISSUE TITLE
Unable to download&install Bromite&Chromium from F-droid (without previous installation)

### ISSUE THREAD

**Issue by Techguyprivate** [bromite/bromite#161]
**Bromite version**

Version: 70.0.3538.67
Arch: arm & arm64
Android version: lollipop & oreo

**Is the bug reproducible with latest version?**
yes.   

**Is the bug a crash?**
No.
 
**Describe the bug**

Unable to download &install bromite browser & vanilla chromium from F-droid .Showing error as failed to verify.
Important: As a new user , for the first time,the error occurs. If you have already added bromite repo as 3rd party repo in fdroid, then update get downloaded with no problem.

**To Reproduce**
1. Go to f-droid.
2. Click on  manage repositories.Add bromite as 3rd party repo by copying the link from QR code.
3. Now try to download & install bromite ot vanilla chromium.
4. Throwing error that unable to verify.

**Expected behavior** 
Bromite& vanilla chrimium should be downloaded without any problem.
<img src="https://user-images.githubusercontent.com/43615747/47303269-1ba7cc00-d641-11e8-8760-33d00febe920.png" width=400 />

**Screenshots**

<img src="https://user-images.githubusercontent.com/43615747/47304392-0bc6c280-d616-11e8-94e9-0167b4fd6ba0.gif" width=400 />

**Comment by csagan5** [comment]
@Techguyprivate I don't think there is anything to be done in Bromite about this. Ask on F-droid issue tracker or forums?

It might be this issue: https://gitlab.com/fdroid/fdroidclient/issues/728
also mentioned in https://forum.f-droid.org/t/install-aborted-with-errormessage-failed-to-verify/2964

If you find out what needs to be changed in Bromite's F-Droid repository, then we can change it, but it looks like a bug in F-Droid itself (in particular if it works after some attempts).

**Comment by Techguyprivate** [comment]
Ok dude , whatever you say. Attempted  for 30 consecutive times , but didn't able to download   . Anyway, let me report it at various f-droid forum  with step by step with gif &  video.

**Comment by csagan5** [comment]
You can stop at the 3rd time, no need to try 30 times. This is not something to fix in Bromite, I wrote it right there:

> If you find out what needs to be changed in Bromite's F-Droid repository, then we can change it

**Comment by luontokoodaus** [comment]
@Techguyprivate solved here: https://github.com/bromite/bromite/issues/308
