### ISSUE TITLE
Useragent does note match the phone information and browser version.

### ISSUE THREAD

**Issue by whour** [bromite/bromite#162]
**Bromite version**

Version: `70.0.3538.71`
Arch:  `arm64` 
Android version: `Oreo`

**Is the bug reproducible with latest version?**
`Bug must be reproducible with latest version`

**Describe the bug**
My mobile phone is Redmi note 5, I am going to [https://www.bromite.org/detect](https://www.bromite.org/detect ) but it shows SM-G950U Samsung Galaxy S8 and Chrome 67.0.3396.87

**Screenshots**

![screenshot_2018-10-23-10-33-42-407_org bromite bromite](https://user-images.githubusercontent.com/4928187/47332808-197e5580-d6b3-11e8-984e-4fbdb185ac0a.png)
![screenshot_2018-10-23-10-34-40-565_org bromite bromite](https://user-images.githubusercontent.com/4928187/47332813-2307bd80-d6b3-11e8-973a-762f892c3c7e.png)

**Comment by csagan5** [comment]
This is by design. in Bromite user-agents are fixed and do not report the real phone model or browser version/build as a fingerprinting mitigation.
