### ISSUE TITLE
Suspicious default homepage

### ISSUE THREAD

**Issue by frogtile** [bromite/bromite#1646]
I installed Bromite from GitHub release, after I ran it i I found that it's default home page is set to the following URL: 

![Screenshot_20211211-003325](https://user-images.githubusercontent.com/87414805/145624545-d1bd9dfe-2336-4fcd-bfac-a3cc2d6616c6.png)

**Comment by frogtile** [comment]
@csagan5 what happened?

**Comment by csagan5** [comment]
@frogtile you need to submit the issue following the issue template; try to use GitHub in desktop mode if you submitted this via mobile.
