### ISSUE TITLE
Motion sensor stil works

### ISSUE THREAD

**Issue by randomshell** [bromite/bromite#165]
**Bromite version**

Version: `70.0.3538.77`
Arch: `arm64`
Android version: `8.0.0`

**Is the bug reproducible with latest version?**
Yes. Introduced in latest.

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
Not relevant

**Is the bug a crash?**
No

**Describe the bug**
In chrome flags:
`#enable-generic-sensor`, `#enable-generic-sensor-extra-classes`, `#webxr-orientaion-sensor-device` set to disabled
`#disable-device-motion` set to enabled.

Visiting http://webkay.robinlinus.com/ still show the correct device orientaion, under 3d_rotation.

**To Reproduce**
1. Go to http://webkay.robinlinus.com/ 
2. Scroll down to 3d_rotation
3. See device orientation

**Expected behavior**
Motion sensor disabled with the flags set as above.

**Screenshots**
None

**Comment by csagan5** [comment]
> #disable-device-motion set to enabled.

You should set to disabled.

**Comment by randomshell** [comment]
If the option is `disable.x` I expect to set it to enabled to disable x.
Anyway, for me the site shows the correct orientation on disabled too.

**Comment by csagan5** [comment]
@randomshell device orientation API has never been targeted as a privacy violation vector and there are no plans to disable it.

In #160 we did not discuss that such API is a threat, and it is not as far as I know.

**Comment by csagan5** [comment]
> If the option is disable.x I expect to set it to enabled to disable x.

I tried to follow the behaviour of other flags that start with `#disable-`; if I am doing this incorrectly we can change it.

**Comment by csagan5** [comment]
The option has been changed and the default fixed (it was not working, I was mistaken, sorry for that).

**Comment by randomshell** [comment]
My bad I reported it incorrectly.
Thank you for your work.
