### ISSUE TITLE
Cannot Print to PDF on Bromite

### ISSUE THREAD

**Issue by pixincreate** [bromite/bromite#1655]
### Bromite version

Version: `96.0.4664.54`
Arch: `arm64`
Android version: LineageOS 18.1
Device model: Nokia 6.1 Plus (DRG), Xiaomi Resmi Note 7S (Lavender)

### Flags

These are the flags changed under `chrome://flags`:
I've some that are not related to print like long screenshots and tab groupings.

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is this bug happening in an incognito tab?
Yes

### Allow ads for the site; is the bug caused by the adblocker?
No

### Is the bug a crash?

No

-- or --

Yes, I have attached here on GitHub the crash report dump that I downloaded from `chrome://crashes`.

-- or --

Yes, this is a copy/paste of the crash dump:
```
<paste here logcat dump individuated with 'adb logcat | grep chromium'>
```

### Describe the bug
I cannot print to PDF from Bromite while I can do the same from Chromium. It's happening across the app, not only restricted to Incognito mode.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to website like bill payment ones or so that has Print option which redirects to Print spooler.
2. Click on it.
3. You see blank page as shown in the screenshots below.

Do not write "any website", specify which URLs can be used to reproduce the issue.

### Expected behavior
I should be able to download the PDF from any Website that has print option which redirects to print spooler.

### Screenshots

![Screenshot_20211216-093020_Print_Spooler](https://user-images.githubusercontent.com/69745008/146305988-c43da27b-528a-42ca-8778-20bf7d6a2c78.png)
Image from Chromium

![Screenshot_20211216-092905_Print_Spooler](https://user-images.githubusercontent.com/69745008/146306006-b64f276f-6c2f-4c2f-8833-7f74bf77dfbf.png)
Image from Bromite.

**Comment by csagan5** [comment]
What happens if you disable the ad blocker?

**Comment by pixincreate** [comment]
Have to try that, will update in a few mins

**Comment by csagan5** [comment]
This issue is specific to the unmentioned site you are using, it works in other cases; see if you can create a `.html` file that allows everyone to reproduce the issue otherwise it is very difficult that there will be a solution.

It might be due to the higher security requirements of Bromite; you can try connecting via [remote debugging](https://developer.chrome.com/docs/devtools/remote-debugging/) and checking for network or Javascript errors.

**Comment by pixincreate** [comment]
The website was actually a Government website and I'd applied for a bus pass. I couldn't print the details to a PDF and I did it from other browser.

**Comment by pixincreate** [comment]
> This issue is specific to the unmentioned site you are using, it works in other cases; see if you can create a `.html` file that allows everyone to reproduce the issue otherwise it is very difficult that there will be a solution.
> 
> It might be due to the higher security requirements of Bromite; you can try connecting via [remote debugging](https://developer.chrome.com/docs/devtools/remote-debugging/) and checking for network or Javascript errors.

Ok, I'd to print another application form for the college purpose today, same issue, but this time, everything appeared in the first sheet, but plenty white background on the second. However, the first sheet had dark background where the content existed.
So I believe that the content is being loaded properly but font colors are the one causing the issue here

**Comment by pixincreate** [comment]
@csagan5, I can confirm you that this is being caused by the theme in the app.  
Here are the screenshots of it as a proof of confirmation. 
![1. Screenshot_20220121-200654_Print_Spooler](https://user-images.githubusercontent.com/69745008/150546934-136b5af0-232f-4f10-ac85-0e4809f6f18e.png)  
This image have no issues as shown. Yes, when in light theme, no issues can be found. Everything looks and works smoothly.

![2. Screenshot_20220121-200740_Print_Spooler](https://user-images.githubusercontent.com/69745008/150547189-ad35e3b0-d013-4d25-8d5d-acaeba80ead3.png)  
This second image is when the Dark theme is turned on, either by system default or dark theme with dark theme for sites turned off on both below the dark theme button as well as in the bottom of site settings.

![3. Screenshot_20220121-200822_Print_Spooler](https://user-images.githubusercontent.com/69745008/150547424-aa8d2d7b-a8f4-4908-a2c1-79b476d6a032.png)  
3rd image has all the dark theme settings turned on.
