### ISSUE TITLE
Missing settings entry string in "Site Settings"

### ISSUE THREAD

**Issue by dvheyden** [bromite/bromite#166]
**Bromite version**

Version: Latest, Arm64 ChromeModern
Android: 8.1

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding [Chromium]**
No

**Is the bug a crash?**
No

**Describe the bug**
There is a missing settings entry in "Site Settings"

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Site Settings.'
3. Scroll down and you will notice a settings entry with no string (blank) you can still tap it and enter its respective menu but its obviously a UI bug.

**Expected behavior**
A header for these sub settings with an icon should be present.

**Comment by csagan5** [comment]
I have found a solution to this issue; additionally, the non-working option to keep cookies until session exit (currently broken, see #142) is appearing on all site settings sub-views. I will try to fix that as well.

**Comment by csagan5** [comment]
Fixed in `70.0.3538.83`
