### ISSUE TITLE
F-Droid release

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [bromite/bromite#1661]
### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

F-Droid is an Android app store born under free license and for user’s privacy, it would be nice to see you F-Droid.

### Describe alternatives you have considered

No, F-Droid itself is free alternative to Play Store.

**Comment by KrasnayaPloshchad** [comment]
Sorry, I haven’t see your documentation clearly, I just thought of following what they did as Fennec F-Droid.

**Comment by chrislogan-foss** [comment]
You can add the Bromite repo to F-Droid https://www.bromite.org/fdroid
