### ISSUE TITLE
feature: support Encrypted SNI 

### ISSUE THREAD

**Issue by Techguyprivate** [bromite/bromite#167]
**Is your feature request related to privacy?**
Yes.

**Is there a patch available for this feature somewhere?**
Don't know surely.But discussions at brave browser issues at github and firefox nightly.
...https://github.com/brave/brave-browser/issues/1851

**Describe the solution you'd like**
https://blog.mozilla.org/security/2018/10/18/encrypted-sni-comes-to-firefox-nightly/

**Comment by csagan5** [comment]
Useful links from [this comment](https://github.com/chromium/badssl.com/issues/356#issuecomment-405120381):

> https://datatracker.ietf.org/doc/draft-ietf-tls-sni-encryption/
> https://tools.ietf.org/html/draft-rescorla-tls-esni
> https://www.ietf.org/proceedings/94/slides/slides-94-tls-8.pdf
> https://news.ycombinator.com/item?id=16565368
> https://huitema.wordpress.com/2017/09/12/cracking-the-sni-encryption-nut/

From what I can see Chromium does not support ESNI; @Techguyprivate you have to request this feature upstream in Chromium, there are 0 chances such a big patch can be implemented and supported in Bromite (and the Chromium devs will have to implement it anyways when other major browsers do).

**Comment by istiak101** [comment]
Maybe now?

chrome://flags/#encrypted-client-hello

https://blog.cloudflare.com/announcing-encrypted-client-hello/
https://blog.cloudflare.com/encrypted-client-hello/
https://tls-ech.dev/
brave/brave-browser#1851
