### ISSUE TITLE
Do not open in dumb custom tab mode

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#17]
It appears that all links (at least with Android 8) are opened in a dumb custom tab mode.

For reference: https://android.stackexchange.com/questions/145745/prevent-apps-opening-links-in-chrome-custom-tabs-i-e-open-in-default-browser-d

Force Bromite to never use such mode.

**Comment by csagan5** [comment]
I made some tests on this, but I cannot identify what are the passed flags that trigger this behaviour. Also I need to find a way to trigger this on the device simulator.

**Comment by Madis0** [comment]
An option would be nice, there are users who prefer it because it is faster to open and looks cleaner (more app-like).

**Comment by csagan5** [comment]
I see it being app-like as a downside, since it does not make it evident which URL you are visiting. It is unlikely there will be an option for each of the customisations, but they will be picked sparingly.

**Comment by Madis0** [comment]
The URL is always visible, it is just shown below the title. ![](https://vgy.me/ck1nl9.png)

**Comment by Madis0** [comment]
[More info about how it works](https://android.stackexchange.com/questions/145745/prevent-apps-opening-links-in-chrome-custom-tabs-i-e-open-in-default-browser-d ). Alternatively, you could backport a [now-removed flag.](https://fwned.com/disable-chrome-custom-tabs/)

**Comment by csagan5** [comment]
Thanks for your pointers; I did some digging and apparently the flag was removed in [this commit](https://github.com/chromium/chromium/commit/64953ee1b0093f5c0f60773f4ca803224281f23a).

We could indeed restore the flag, as it is not too far in the past; however for next release I am going to experiment with a complete disable.

It is true what you said, that the URL is still visible, but somehow it feels like a limited user experience in this custom tab mode. It may indeed be a matter of taste, but my guiding principle is that a webpage is not an app and should be recognised as a webpage (with the full features of a browser). I know, debatable and not trendy...

**Comment by D0ve** [comment]
If possible, would be best if mostly all futures be always optional at least thrue about:flags page!
Many thanks in advance!

**Comment by csagan5** [comment]
Fixed in 66.0.3359.148

**Comment by csagan5** [comment]
@Madis0 @D0ve we might have later on flags, but not at this stage

**Comment by D0ve** [comment]
Oh, God bless you! Thanks!
