### ISSUE TITLE
Option for allowing screenshots in incognito mode.

### ISSUE THREAD

**Issue by hollowghost00** [bromite/bromite#1714]
### Is your feature request related to privacy?
Yes.

### Is there a patch available for this feature somewhere?
I don't know.

### Describe the solution you would like
I believe an option to allow screenshots in incognito mode should be added.

I use incognito mode as my default mode, and having to copy the link, paste it in a normal tab and *then* take the screenshot is very annoying. And while I know that incognito mode is far from being completely anonymous, I also fear that doing that process gives websites more of my info than I would like. But I'm not knowledgeable about the subject, so I suppose you can consider it just peace of mind.

### Describe alternatives you have considered
Removing that screenshot "block" altogether would also work, of course, but I have no idea of the privacy concerns that would bring.

**Comment by Disqu3-mirOir-qt** [comment]
chrome://flags/#enable-incognito-snapshots-in-android-recents

already available

**Comment by hollowghost00** [comment]
Wasn't aware of chrome://flags. Sorry.
