### ISSUE TITLE
Enable TLS 1.3 (final)  by default 

### ISSUE THREAD

**Issue by Techguyprivate** [bromite/bromite#174]
**Is your feature request related to privacy?**
Yes.Kind of . 

**Describe the solution you'd like**

Enable TLS 1.3 final by default. TLS 1.3 is little bit fast , more secure and  privacy friendly over TLS 1.2.

**Describe alternatives you've considered**
1. Go to about:flags.
2. Search for TLS.
3. Change Tls to final , manually.

**Comment by csagan5** [comment]
https://support.cloudflare.com/hc/en-us/articles/227172348-How-do-I-enable-TLS-1-3-

**Comment by csagan5** [comment]
This is fixed in next release `70.0.3538.95` (not yet released).
