### ISSUE TITLE
Enable trivial auto var init

### ISSUE THREAD

**Issue by BayLee4** [bromite/bromite#1749]
### Is your feature request related to privacy?

Not really, it's mostly related to security.

### Is there a patch available for this feature somewhere?

Yes : https://github.com/GrapheneOS/Vanadium/tree/12/patches

### Describe the solution you would like

Merge the patches using the Clang compile option `-ftrivial-auto-var-init=zero` as it prevents memory corruption vulnerabilities related to uninitialized memory.

[enable-ftrivial-auto-var-init-zero.patch](https://github.com/GrapheneOS/Vanadium/blob/12/patches/0005-enable-ftrivial-auto-var-init-zero.patch)
[disable-broken-warning-for-auto-var-init.patch](https://github.com/GrapheneOS/Vanadium/blob/12/patches/0006-disable-broken-warning-for-auto-var-init.patch)

Merge the patch enabling by default the `Strict Origin Isolation` flag, it should have no impact for devices with low memory as (afaik) Site Isolation is already disabled for them, and it increase the security of devices with sufficient memory. Enabling it would also help with #1720.

[Enable-strict-origin-isolation-by-default.patch](https://github.com/GrapheneOS/Vanadium/blob/12/patches/0080-Enable-strict-origin-isolation-by-default.patch)

### Describe alternatives you have considered

• `-ftrivial-auto-var-init=zero` related patches : No simple alternative, as it's a compile time flag.
• `Strict Origin Isolation` related patch : Keep the flag disabled, and let users manually enabling it in `chrome://flags` if they want to.

**Comment by ASTechnical** [comment]
You can open a Pull Request

**Comment by csagan5** [comment]
Fixed in `97.0.4692.106`.
