### ISSUE TITLE
This Feature already exist but has to be implemented from your side

### ISSUE THREAD

**Issue by pixincreate** [bromite/bromite#1756]
### Is your feature request related to privacy?
Yes

### Is there a patch available for this feature somewhere?
Not Sure

### Describe the solution you would like
Change the default search engine to duckduckgo.com instead of traditional google.com. This increases privacy of an individual significantly. And both are default search engines that comes with Bromite.

### Describe alternatives you have considered

I change it manually everytime I install which is quite inconvienient.

**Comment by csagan5** [comment]
This has been asked before; DuckDuckGo is one of many alternatives, Bromite does not make any choice for you.

**Comment by pixincreate** [comment]
> Bromite does not make any choice for you.

I'd like to know the reason behind keeping Google as the default search engine.

**Comment by csagan5** [comment]
I have added a F.A.Q., you can read it there now.
