### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by Esokrates** [bromite/bromite#176]
Logging into https://tickets.oebb.at/de/ticket does not work here, when logging in the site just reloads and you are not logged in
Tried to disable adblock, does not make a difference.
Works fine in chrome.

**Comment by csagan5** [comment]
There is an issue template, please use it.

**Comment by Esokrates** [comment]
This template does not show up when reporting from the mobile browser. 
Please include that in the README.

**Comment by csagan5** [comment]
@Esokrates I had never tried from mobile and this is totally unexpected...thanks for telling me, I have replied to tens of issues thinking that they were ignoring the issue template. I have contacted Github about this.

**Comment by Esokrates** [comment]
Yep, reporting from the phone is a pretty limited experience, this is what it looks like when clicking on report. I guess some of the others who asked where to find the template made the same experience.

![screenshot_20181107-231708](https://user-images.githubusercontent.com/17780185/48164631-549f9c00-e2e3-11e8-820d-3feaa2f0a6f2.png)

**Comment by Esokrates** [comment]
@csagan5 I would suggest migrating to gitlab to save you from trouble in that regard. Issue templates work there and the mobile bug reporting experience looks far superior, have a look:
![screenshot_20181108-155617](https://user-images.githubusercontent.com/17780185/48206720-52831f00-e36f-11e8-9fa0-4ddcf3d7e314.png)

**Comment by csagan5** [comment]
Indeed, I suspected that Gitlab already got this right, thanks for checking.

**Comment by csagan5** [comment]
Github support does not have an ETA for fixing this, so I will see what are the pros/cons of moving to Gitlab since there are around 4 issues without template every week and it is a bit tedious already.
