### ISSUE TITLE
Login on tickets.oebb.at broken

### ISSUE THREAD

**Issue by Esokrates** [bromite/bromite#177]
**Bromite version**

Version: `70.0.3538.95`
Arch: `arm64`
Android version: `Pie`
Phone: `Google Pixel 2016`, fully upgraded

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No

**Is the bug a crash?**
No

**Describe the bug**
When trying to log in or creating an account on the mentioned site it simply reloads.
In chromium on the other hand, there is a spinner spinning and everything works as expected.

**To Reproduce**
1. Go to https://tickets.oebb.at/en/ticket
2. Click on the Home Button on the top left oft the page
3. Click on the Hamburger Menu with "ÖBB" Label on the top left of the page
4. Try to create an account, by filling in the form and then pressing "Confirm".

You will now observe that the page simply reloads on nothing happened.

**Expected behavior**
The login / account creation should work in Bromite. Right now I have to use a second browser for this.

**Screenshots**

![screenshot_20181107-230620](https://user-images.githubusercontent.com/17780185/48164485-f1156e80-e2e2-11e8-941e-6f3dd35577b2.png)

**Comment by csagan5** [comment]
They seem to have finished the maintenance and I could reproduce your results, tested on the `/de` version.

I will investigate further.

**Comment by csagan5** [comment]
@Esokrates perhaps that website does something funny with the history. In #171 we changed the value of `#enable-history-entry-requires-user-gesture` to be not enabled by default. I have tried to disable that but still not working.

**Comment by csagan5** [comment]
Fixed in next release `70.0.3538.107`

**Comment by Esokrates** [comment]
Thanks very much for fixing this, login works now :-).
