### ISSUE TITLE
Remember default set of ua 'full version'

### ISSUE THREAD

**Issue by DI555** [bromite/bromite#178]
Great to be possible to remember default set of ua checkbox 'full version'  that in right upper corner of 'dots' menu.
Would be useful to see this option in 'settings' section, to select the default mode : 'mobile' or 'desktop'. (I use desktop mode(full version mode) , that needed always to switch it on :-(  )
Also, if possible, great to see editable strokes for 'mobile' and 'desktop' ua !

**Comment by csagan5** [comment]
@DI555 please edit or re-submit this issue by using the issue template; due to a limitation of Github you can only see the issue template when switching to "Desktop mode".
