### ISSUE TITLE
Option to toggle incognito mode

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#18]
In the CAF patchset there was a feature to have an option to toggle always-on incognito mode.

See if it's possible to port it over.

**Comment by Primokorn** [comment]
Yes that would be cool. Actually I'd like to be logged in to a Gmail account in Normal while defining Bromite in Incognito mode by default.

**Comment by csagan5** [comment]
I have found a way to enable incognito mode for all new URLs opened via Bromite. We might be able to use this in next release, although it does not persist the setting.

**Comment by Primokorn** [comment]
Thanks a lot for your efforts! Hope it will work fine.

**Comment by Primokorn** [comment]
Just read this article on gHacks: https://www.ghacks.net/2018/06/29/load-chrome-websites-automatically-in-incognito-mode/
Not sure if it can help but I thought it was worth mentioning it.

**Comment by csagan5** [comment]
I don't think that would apply in this case (Android) because it is more a problem of "intents" rather than embedding an extension code.

**Comment by csagan5** [comment]
Related: https://github.com/brave/browser-android-tabs/pull/328

**Comment by csagan5** [comment]
Fixed in 68.0.3440.121

**Comment by csagan5** [comment]
@rarcher I have added your patch to Bromite some weeks ago, with minor adjustments to allow it to compile on latest Chromium trees. Thanks for the nice work!

All patches published in this project are released under [GNU/GPL v3 license](https://github.com/bromite/bromite/blob/master/LICENSE), while the PR you opened for Brave is under Chromium's license, please let me know if you would like the patch file to mention that it is under a different license or if you are OK with the license I use for Bromite's patches.

**Comment by rarcher** [comment]
@csagan5 No problem, glad it was helpful!

Regarding the license, I'm fine with GNU/GPL v3 if that's your preference.  I'm just happy to see the orphaned PR finally used for something, lol

**Comment by rarcher** [comment]
@csagan5 The issue is that enabling always-incognito mode doesn't convert existing regular tabs into incognito ones.  The Brave people specifically wanted that behavior, and did not wish to merge the patch without it.
