### ISSUE TITLE
Experiencing slow downs sometime

### ISSUE THREAD

**Issue by Rtizer-9** [bromite/bromite#180]
When the browser opens with a few tabs already open, it takes somewhat longer for the present page to load and otherwise as well without any tabs open.

I know you've clearly stated that this browser is focused on privacy and security and not fancy features like theming and such but is there any way to incorporate kiwi's speed optimisations?

I was using kiwi but on his readme's recommendation bromite is now my default ( I also user bromite system webview). If kiwi can be so stable with canary branch and theming and other appreciable features in UI then why can't we achieve speed with fingerprinting protection in bromite. Kiwi's loading time is too good to ignore.

Also can you please suggest what can we do about cross site tracking. Both safari (ITP 2.0) and firefox (Containers) have numerous methods to overcome this problem. I know chromium still don't have Containers but it has extension support.

I'm not asking for extensions but don't you think the fingerprinting protection is somewhat lacking on this front because the cookie in one tab can be easily read by domain in another tab.

Thanks :)

**Comment by csagan5** [comment]
There is currently an issue in Github that basically hides issue templates when accessing Github via mobile; until that is solved please re-submit your issue by using the issue template.

One issue cannot cover multiple topics or questions.
