### ISSUE TITLE
Latest Bromite WebView has incorrect package name.

### ISSUE THREAD

**Issue by tensor-primary** [bromite/bromite#1801]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

97.0.4692.106

### Device architecture

arm64

### Android version

11

### Device model

realme C12 (RMX2189)

### Changed flags

No flags changed.

### Is this bug about the SystemWebView?

Yes

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No.

### Describe the bug

The WebView package name has been changed from com.android.webview to org.bromite.webview which prevents me from updating my WebView provider.

### Steps to reproduce the bug

1) Download the latest WebView release.
2) Install the package.
3) Two Bromite WebView apps now appear in Apps list, having different package names.

### Expected behavior

Installing the latest WebView package should update my currently installed Bromite System WebView which is currently at version 96.0.4664.183.

**Comment by x8xx8x** [comment]
None of the methods mentioned in the installation wiki work because of this.

**Comment by ajay230ps** [comment]
May be this is the issue change on the package name

Old Bromite webview package name: com.android.webview

New Bromite webview package name: org.bromite.webview

**Comment by saurabhinabys** [comment]
So, how can we remedy this on devices with webview already installed as com.android webview?

**Comment by csagan5** [comment]
See https://www.bromite.org/news/2022-02-05-bromite-webview-package-name-change

> So, how can we remedy this on devices with webview already installed as com.android webview?

Follow the [wiki](https://github.com/bromite/bromite/wiki/Installing-SystemWebView) to install it second the new package name; old one should be removed.
