### ISSUE TITLE
Failed to load WebView provider

### ISSUE THREAD

**Issue by syphyr** [bromite/bromite#1807]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

97.0.4692.106

### Device architecture

arm64-v8a

### Android version

7.1

### Device model

T813

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

Yes

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

02-19 21:33:25.597  5728  5728 E AndroidRuntime: FATAL EXCEPTION: main
02-19 21:33:25.597  5728  5728 E AndroidRuntime: Process: org.lineageos.jelly, PID: 5728
02-19 21:33:25.597  5728  5728 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.lineageos.jelly/org.lineageos.jelly.MainActivity}: android.view.InflateException: Binary XML file line #74: Binary XML file line #74: Error inflating class org.lineageos.jelly.webview.WebViewExt
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #74: Binary XML file line #74: Error inflating class org.lineageos.jelly.webview.WebViewExt
02-19 21:33:25.597  5728  5728 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #74: Error inflating class org.lineageos.jelly.webview.WebViewExt
02-19 21:33:25.597  5728  5728 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at org.lineageos.jelly.MainActivity.onCreate(MainActivity.java:140)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6684)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:371)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.webkit.WebView.getFactory(WebView.java:2384)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.webkit.WebView.ensureProviderCreated(WebView.java:2379)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.webkit.WebView.setOverScrollMode(WebView.java:2438)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.view.View.<init>(View.java:4023)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.view.View.<init>(View.java:4146)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.view.ViewGroup.<init>(ViewGroup.java:579)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:632)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:577)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:560)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:547)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at org.lineageos.jelly.webview.WebViewExt.<init>(WebViewExt.java:63)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	... 27 more
02-19 21:33:25.597  5728  5728 E AndroidRuntime: Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:270)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:330)
02-19 21:33:25.597  5728  5728 E AndroidRuntime: 	... 40 more

### Describe the bug

Android Nougat is not detecting any webview source is installed if 97.0.4692.106 is installed to the /system partition. If I install bromite webview 96.0.4664.183 to /system partition and then upgrade to 97.0.4692.106 on the /data partition, it works as expected.  Jelly does not start when the bromite webview 97.0.4692.106 is installed to /system partition because Android is not detecting any webview source is installed, although bromite is still visible in the list of installed system applications.

### Steps to reproduce the bug

1. Install bromite webview to system partition
2. Android does not detect it as a source for webview

### Expected behavior

Android should detect that latest bromite webview is installed to the system partition and let it be selected as default webview.

**Comment by DanGLES3** [comment]
That happens because WebView providers need to have their package names explicitly whitelisted within the system framework, and since now bromite uses a custom package name Android won't detect bromite's WebView

**Comment by syphyr** [comment]
> That happens because WebView providers need to have their package names explicitly whitelisted within the system framework, and since now bromite uses a custom package name Android won't detect bromite's WebView unless the framework is modded (either directly or through an overlay) to accept it

Ah 96.0.4664.183 is com.android.webview and now its org.bromite.webview.  That explains it. Thanks. I am closing this.
