### ISSUE TITLE
Adaptive icon

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#181]
From @Madis0:
> Since you have the build setup already, maybe you can do it by my instructions.
> Here's how I did it:
> 
> Create a new file: `.../Resources/mipmap-anydpi/icon.xml`
> 
> ```
> <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
>     <background android:drawable="@color/ic_background"/>
>     <foreground android:drawable="@mipmap/ic_foreground"/>
> </adaptive-icon>
> ```
> Move/rename the original icon to `.../Resources/mipmap/ic_foreground.png`
> 
> Append a color in `.../Resources/values/Colors.xml`
> 
> `<color name="ic_background">#77ebcc</color>`

**Comment by csagan5** [comment]
@Madis0 so the current Chromium does not have an adaptive icon?

**Comment by Madis0** [comment]
Assuming the [Chromium updater](https://f-droid.org/en/packages/com.dosse.chromiumautoupdater/) I use gives me unmodified variants: yes, there is no adaptive icon on current Chromium.

**Comment by csagan5** [comment]
I think I managed to add it, however there are concerns regarding falling back to the regular icon for Android before SDK26; I am working on that.

<img src="https://user-images.githubusercontent.com/32685696/48450235-ca08e200-e7a5-11e8-9a3c-b7a47fae6fa2.jpg" width="250"/>

**Comment by csagan5** [comment]
Will be fixed in next release `70.0.3538.107`.

@vdmp finally the adaptive icon will work :smiley:
