### ISSUE TITLE
Do not send x-client-data http header

### ISSUE THREAD

**Issue by JustAnUserLol** [bromite/bromite#1811]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

Yes, https://github.com/Hexavalent-Browser/Hexavalent/commit/200eea69ad9199971d398b00b02b6dd4ab30eb65

### Describe the solution you would like

Do not send the x-client-data http header

### Describe alternatives you have considered

None

**Comment by uazo** [comment]
thanks for the report, in bromite it is already deactivated with [ungoogled-chromium-Disable-Google-host-detection.patch](https://github.com/bromite/bromite/blob/master/build/patches/ungoogled-chromium-Disable-Google-host-detection.patch).
in addition, all the management of origin trials, partly related to the header, are disabled with [Disable-third-party-origin-trials.patch](https://github.com/bromite/bromite/blob/master/build/patches/Disable-third-party-origin-trials.patch)
if instead you intend to prove that we are sending them, please open a new bug reporting the way to reproduce it.

**Comment by JustAnUserLol** [comment]
> in bromite it is already deactivated
Cool! :)
