### ISSUE TITLE
Disable JIT by default

### ISSUE THREAD

**Issue by JustAnUserLol** [bromite/bromite#1819]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

Disable JIT by default, Disabling JIT kills half of the bugs in V8 and Eliminates Significant attack surface.

### Describe alternatives you have considered

Let the users manually disable JIT in settings (Which is already implemented).

**Comment by themoonmeetsthesun** [comment]
Doesn't it impact performance?

**Comment by JustAnUserLol** [comment]
> Doesn't it impact performance?

Only on Javascript heavy sites

**Comment by themoonmeetsthesun** [comment]
So wouldn't the login pages of various services become slow when they rely a lot on javascript?

**Comment by themoonmeetsthesun** [comment]
Also is there a need to do this? Cause the setting is already there. I don't understand your issue.

**Comment by uazo** [comment]
I have developed a patch that allows you to insert a new site setting for javascript jit, @csagan5 are you interested? would allow you to remove the global flag and leave the user the choice of being able to activate or deactivate it.

**Comment by JustAnUserLol** [comment]
Fixed by #1832

**Comment by csagan5** [comment]
Fixed in `99.0.4844.55`.
