### ISSUE TITLE
Default search engine

### ISSUE THREAD

**Issue by themoonmeetsthesun** [bromite/bromite#1820]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No.

### Describe the solution you would like

I would like the default search engine to be duckduckgo and not google. It's not great for privacy.

### Describe alternatives you have considered

You can set duckduckgo to be the default browser.

**Comment by JustAnUserLol** [comment]
Please Read the FAQ

**Comment by themoonmeetsthesun** [comment]
My bad, I didn't read it. No worries, I'll close this issue now.
