### ISSUE TITLE
SystemWebView: cannot use with new name

### ISSUE THREAD

**Issue by hanoshita** [bromite/bromite#1825]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

Unfortunately, there is no easy way to use Bromite SystemWebView anymore, please changing the name doesn't resolve anything usually. 

To really be different we will have to change also this libwebviewchromium.so to this libwebviewbromite.so

### Describe alternatives you have considered

org.bromite.webview -> com.android.webview

The statement here: https://www.bromite.org/news/2022-02-05-bromite-webview-package-name-change

The statement here: tba

**Comment by csagan5** [comment]
> Unfortunately, there is no easy way to use Bromite SystemWebView anymore

There is: same way you use the SystemWebView with `com.android.webview` name.

> To really be different we will have to change also this libwebviewchromium.so to this libwebviewbromite.so

Can you please elaborate?
