### ISSUE TITLE
Looking for some pointers

### ISSUE THREAD

**Issue by TechnikEmpire** [bromite/bromite#184]
**Is your feature request related to privacy?**
Yes and no. I want to port and integrate two things of my own.

**Is there a patch available for this feature somewhere?**
Nope.

**Describe the solution you'd like**
I want to port [DistillNET](https://github.com/TechnikEmpire/DistillNET) over to C++ (or java or possible I guess?) and make it the adblocking engine based on URL's only. I could fix up [GQ](https://github.com/TechnikEmpire/GQ) too and use it to strip out ad CSS but URL's should be sufficient.

I'd also like to integrate [NsfwNet](https://github.com/TechnikEmpire/NsfwNET) for video and image filtering of adult content.

**Describe alternatives you've considered**
I'm just starting to explore this concept.

Anyway I'm just wondering if you had any "quick start" advise to do this. Really I just need to know where I can get hold of the requests and responses I guess. Even if you don't have any advice, thanks for your time.

**Comment by csagan5** [comment]
I suggest asking on Reddit on a proper subreddit, this is hardly about Bromite.

**Comment by TechnikEmpire** [comment]
Nah I got it thanks.
