### ISSUE TITLE
Add startpage as a default search engine

### ISSUE THREAD

**Issue by thebizcoder** [bromite/bromite#1852]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

Yes, startpage is a default search engine in Brave

### Describe the solution you would like

Add startpage in default search engine options in bromite

### Describe alternatives you have considered

I have bookmarked startpage and added it to home screen but it is inconvenient to do so, a few months ago a patch came which made recently visited sites to be considered as search engine while after going to amazon many times amazon came under that section but after using startpage in new tabs for searching lots of things startpage didnt came under that option So I request you to add startpage as a default search engine in next patch.

**Comment by JustAnUserLol** [comment]
Please read the [FAQ](./FAQ.md)

**Comment by sebas2day** [comment]
See this comment to fix it yourself: https://github.com/bromite/bromite/discussions/1372#discussioncomment-1318031
