### ISSUE TITLE
Remove **default** politically oriented bookmarks 

### ISSUE THREAD

**Issue by 1kyu** [bromite/bromite#1861]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No.

### Describe the solution you would like

Remove **vostok-sos** from default bookmarks.

### Describe alternatives you have considered

Still remove political views from default bookmarks.

**Comment by csagan5** [comment]
Nope.

**Comment by SevenSystems** [comment]
I have reported this repository for political propaganda. I know the world is in a state of turmoil and the beginning of World War III, but I don't want to see political propaganda for ANY side of ANY sort in the source code repository for a browser. Sorry!

**Comment by K-L-R-3** [comment]
> I have reported this repository for political propaganda. I know the world is in a state of turmoil and the beginning of World War III, but I don't want to see political propaganda for ANY side of ANY sort in the source code repository for a browser. Sorry!

Good. I agree political propaganda is bloat/spam, and maybe even malware depending on your view in  sofware like this. It contributes nothing toward the purpose of a browser.
