### ISSUE TITLE
Google/Chrome strings in Bromite storage page

### ISSUE THREAD

**Issue by jorgeluiscarrillo** [bromite/bromite#1865]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

99.0.4844.55

### Device architecture

arm64-v8a

### Android version

12

### Device model

Pixel 4a

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

There are Google/Chrome strings in Bromite's storage page. The title shows "Google Bromite storage". The option descriptions and dialogs (free up space, clear all data) use Chrome.

### Steps to reproduce the bug

Bromite App info page -> Storage -> Manage space

### Expected behavior

Google/Chrome strings should be replaced with Bromite.

### Screenshots

![Screenshot_20220307-155856](https://user-images.githubusercontent.com/33134232/157138708-04b43225-d8b8-4448-9d3f-f10a2d39ac58.png)

**Comment by csagan5** [comment]
Should be fixed on next release.

**Comment by csagan5** [comment]
Fixed in `99.0.4844.58`.

**Comment by zhmars** [comment]
@csagan5 In this case, [the source change](https://github.com/chromium/chromium/blob/99.0.4844.58/chrome/browser/ui/android/strings/android_chrome_strings.grd#L4085..L4087) of `Bromite storage`could be `<ph name="APP_NAME">%1$s<ex>Bromite</ex></ph> storage` or simply `Bromite storage`. To make sure strings are translated, I need to know the exact source strings. But the changes from `Chromium/Chrome/Google Chrome` to `Bromite` are non-transparent currently (no patch from repo reflect these changes).

As you mentioned in https://github.com/bromite/bromite/issues/546#issuecomment-631271211, they are automatically replaced through a script. Could you upload the script you use? Or maybe we could have a patch for all these changes in repo?

**Comment by csagan5** [comment]
It is a simple search&replace, however I will not release this part for the time being, sorry.
