### ISSUE TITLE
Make DoH feature easier to discover

### ISSUE THREAD

**Issue by Techguyprivate** [bromite/bromite#187]
**Is your feature request related to privacy?**
Kind of. There is a chance some ( most ) people will not read about DNS-over-HTTPS (DoH) option.
They won't be able to see, discover and use it. Without going to about:flags the DoH option is little bit hidden. Little bit as one need to read about somewhere or on the website or github. Although I agree it is shown when installing first time.

**Is there a patch available for this feature somewhere?**
No.

**Describe the solution you'd like**
Making a setting entry, menu entry or option for people to see, discover, use the DoH option easily.

**Describe alternatives you've considered**
Make it clear & easy for it to enable with first time install by specifying the exact steps.

**Comment by csagan5** [comment]
I thought about this, if we tip all users to enable DoH then some may complain that it makes browsing slower. Users should install Bromite after reading the README which remains the main reference material to understand what it is and how to use it.

**Comment by Techguyprivate** [comment]
A  clearly visible option under setting ?

**Comment by Techguyprivate** [comment]
A  clearly visible option under setting ?
