### ISSUE TITLE
Add more search engine options

### ISSUE THREAD

**Issue by bhide-fr** [bromite/bromite#1880]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

I don't know

### Describe the solution you would like

Please ignore if not within the scope of enhancement issues that can be raised.

This would fall within the border category of privacy inho.

Enhancement requested : Add more options for search.

Good example : jQuarks viewer on F-droid including tje following engines:

* Gibiru
* SearX
* StartPage
* Swisscows

Maybe Quant could be added to.

### Describe alternatives you have considered

Changing the browser. But Bromite is good.

**Comment by pixincreate** [comment]
Without reading [FAQs register to search engine](https://github.com/bromite/bromite/blob/master/FAQ.md#can-you-add-this-search-engine-as-default), it's better not to raise a feature request.

**Comment by bocekm** [comment]
You can add Startpage as a default search engine this way: https://github.com/bromite/bromite/discussions/1372#discussioncomment-1318031
