### ISSUE TITLE
Add element hiding for adblocker

### ISSUE THREAD

**Issue by alesimula** [bromite/bromite#189]
**Is your feature request related to privacy?**
No

**Is there a patch available for this feature somewhere?**
Probably

**Describe the solution you'd like**
On many pages a gray or blank box covers the space where the ad was supposed to be, implementing element hiding would make browsing cleaner

**Describe alternatives you've considered**
None

**Comment by csagan5** [comment]
This enhancement request will stay open forever until someone submits a patch for it; I am not going to work on this.

I might close it after a while, in general the amount of improvements that can be done are endless and we should track issues only for those that are planned to be implemented (and actively worked on).

**Comment by thanuj10** [comment]
It seems from the Code view on Github, You have used Easylist filters without element hiding rules. 
Would it be possible to implement Easylist filters with Element hiding rules or does it require the patch you are talking about?

**Comment by csagan5** [comment]
@thanuj10 the adblocking engine in Bromite does not support DOM rules. I do not plan to work on adding DOM support, it would rather correspond to replacing the engine completely.

Additionally, I consider this issue not strictly related to privacy.

**Comment by csagan5** [comment]
We can re-open this if somebody develops or submits a patch.
