### ISSUE TITLE
"Can't Open file" error while Opening a apk file

### ISSUE THREAD

**Issue by JustAnUserLol** [bromite/bromite#1890]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

99.0.4844.58

### Device architecture

armeabi-v7a

### Android version

8.1

### Device model

Samsung Galaxy J2 Core (SM-J260G)

### Changed flags

No flags Changed.

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No.

### Describe the bug

When i try to Open a apk file, it shows the error `Can't Open File`

### Steps to reproduce the bug

1. Download a apk file
2. Click on the apk
3. See Error

### Expected behavior

It should start Apk file install Process.

**Comment by csagan5** [comment]
This is most likely an app permissions issue; screenshot of the error and of the permissions?

**Comment by JustAnUserLol** [comment]
Fixed on Latest Release.
