### ISSUE TITLE
System certificates not used with Android 11

### ISSUE THREAD

**Issue by h1618** [bromite/bromite#1891]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

99.0.4844.58

### Device architecture

arm64

### Android version

11

### Device model

Xiaomi Redmi Note 3 Pro

### Changed flags

chrome://flags not accessible with Via/Bromite System Webview

### Is this bug about the SystemWebView?

Yes

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

1. No.

### Describe the bug

Since upgrading two devices (Xiaomi Redmi Note 3 - kenzo - and Samsung Galaxy Tab 10.1 - N8000) to Android 11, I experience certificate-not-trusted errors with Via Browser (a minimal GUI using Webview) on both on perfect normal websites, as chip.de, bahn.de a.s.o.. I use LineageOS 18.1, Bromite System Webview and Via Browser on both. System Certificates are present and look normal. I never experienced those certificate errors before on Android 9 and 10 (AOSP) and 5 and 6 (MIUI).

### Steps to reproduce the bug

1. With Via Browser and Bromite System Webview open e.g. chip.de
2. Get a PopUp "Certificate not trusted"
3. 

### Expected behavior

no certificate-not-trusted-error expected

### Screenshots

![Screenshot_20220314-132517_Via](https://user-images.githubusercontent.com/6062281/158174665-cd283cc2-885f-4f93-9b28-bad7cec9a8c8.png)

**Comment by JustAnUserLol** [comment]
You cannot access `chrome://flags` via the Bromite SystemWebview, opening `chrome://flags` is only possible in the Bromite Browser.

**Comment by csagan5** [comment]
I have also noticed these certificate errors; it looks like a worse version of #1648; @uazo could it be related to #1554? Or to the corrupted keys for EV certificate validation.

**Comment by uazo** [comment]
> could it be related to https://github.com/bromite/bromite/issues/1554?

possible, but you should have the same problem with the browser

> Or to the corrupted keys for EV certificate validation.

maybe they are not included in the build?
I never even installed the Webview, unfortunately I don't have any app that uses it.
you could delete the support with some `#if`. do you want me to do it?

**Comment by csagan5** [comment]
We are discussing here only the browser issue; there is no support for the SystemWebView.

> > Or to the corrupted keys for EV certificate validation.
> 
> maybe they are not included in the build?

What do you mean? Something crucial changed in how it worked before v99?

**Comment by uazo** [comment]
>  no support for the SystemWebView.

I misunderstood? this issue is not from the webview?

> What do you mean? Something crucial changed in how it worked before v99?

no, I assumed that the webview build might not contain the pins data

**Comment by csagan5** [comment]
> > no support for the SystemWebView.
> 
> I misunderstood? this issue is not from the webview?

You are right, @h1618 has submitted the issue as reproduced on the SystemWebView but I can reproduce it with Bromite. However I noticed that in my case it is due to "make HTTPS-only mode enabled by default" which was enabled in v97: if the first request is a `http://` one redirecting to a `https://` site, it shows a warning message about the site not being encrypted (which is true).

@h1618 can you please try to reproduce the issue with Bromite and check whether connecting to `http://chip.de` shows you the error but not when connecting to `https://chip.de`?

**Comment by AlirezaBaloochi** [comment]
Same issue here,I get the error "This site does not support HTTPS", I can skip it by clicking "continue to site".
was working fine, happened after the latest update.

**Comment by AlirezaBaloochi** [comment]
> Same issue here,I get the error "This site does not support HTTPS", I can skip it by clicking "continue to site". was working fine, happened after the latest update.

I'm using Bromite v 99.0.4844.58 with Android System WebView v99.0.4844.73 on Android 11.
Default Chrome has no issues, so my take is Bromite itself is having a problem.
Chip.de works fine for me, other sites don't.
