### ISSUE TITLE
Search and site suggestions does not work on duckduckgo

### ISSUE THREAD

**Issue by JoeTvx** [bromite/bromite#19]
Even when I enable this in Settings. Is this feature even supported by Bromite? If not, my apologies.

64.3278.0 on Android 8.0.0.

**Comment by csagan5** [comment]
Does it work with Google?

The URLs are specified: https://github.com/bromite/bromite/blob/master/patches/privacy/add-duckduckgo.patch

So it should work, unless some other patch disables them

**Comment by JoeTvx** [comment]
Yes, suggestions work fine for both Google and Bing. Hmm, not sure why ddg is the exception.

I tried this in Chrome, and it works fine. I added the engine by going to duckduckgo.com and using their Add ddg to Chrome button. I can't do the same thing for bromite since the entry is already there by default.

Is there an easy way to see the suggestion URL configuration for and installed version of Bromite?

**Comment by csagan5** [comment]
I figured out why. The URL specified there is incorrect (it comes from an original patch from Inox patchset if I remember correctly) and DuckDuckGo does not support suggestion URLs.

See https://duck.co/ideas/idea/547/query-suggestions-in-json-format-would-be-usuable

That is a question of ~5.5 years ago; I suggest using StartPage which is more transparent than DuckDuckGo, but it also does not have suggestions.

**Comment by JoeTvx** [comment]
I do prefer startpage, but have not been using it because of the lack of suggestions support.

Is it easy at all for Bromite users to add the Google suggestions URL to the startpage search? In Chrome, duckduckgo.com can be added using their Add ddg to Chrome button, which sports suggestions.

**Comment by csagan5** [comment]
They do not offer such feature...I suggest opening a discussion in their forums maybe?

**Comment by JoeTvx** [comment]
Suggestions on startpage works fine on the Brave browser. I'm guessing the suggestions URL is separate from the search engine. In other words, they use Google for suggestions even on the startpage search.

**Comment by csagan5** [comment]
@JoeTvx I went to check in their source code: https://github.com/brave/browser-android-tabs/blob/master/components/search_engines/prepopulated_engines.json#L122

So now I will try using the same definition for DDG, it should work. Thanks for reporting an example of another Chromium-based browser (Brave) where it works.

By the way, I have seen that one can just visit a search engine page and then it is possible to add that browser. This feature must have been added recently in Chromium.

**Comment by JoeTvx** [comment]
Awesome, thank you. If you could also pick up the startpage definitions from Brave, that would be very helpful too since suggestions work on that as well.

Yes, I noticed the feature you're talking about as well, and would be very glad if it did indeed come from Chromium.

OT, but thank you so much for Bromite! The world sorely needs a modern open source browser with no strings attached!

**Comment by csagan5** [comment]
@JoeTvx yes it seems that they found some undocumented API, I will use their definition for StartPage as well. The next release is building so should be available in a day or so.

**Comment by JoeTvx** [comment]
DDG suggestions work now, thank you!

Startpage suggestions don't work though. Nor can I add custom engines. Are there plans to include the latter feature?

**Comment by csagan5** [comment]
@JoeTvx adding custom engines is a feature of Chrome/Chromium, not Bromite. it works so that after visiting a search engine, you can go to the search engines selection in settings and pick it up

**Comment by JoeTvx** [comment]
@csagan5, right, I see that feature in Chromium but not in the latest version of Bromite, and was wondering if you knew why.

**Comment by JoeTvx** [comment]
@csagan5, do startpage suggestions work for you?

**Comment by csagan5** [comment]
@JoeTvx yes. you have to enable site suggestions because they are disabled by default in Bromite

**Comment by JoeTvx** [comment]
I do have site suggestions enabled. It works fine for me in all other search engines except startpage. What gives?

**Comment by JoeTvx** [comment]
Anyone else seeing this with startpage?

**Comment by JoeTvx** [comment]
@csagan5, are you able to reproduce this? Should I open a separate ticket for this? Thanks.
