### ISSUE TITLE
Adding rudimentary support for user scripting

### ISSUE THREAD

**Issue by projectextremum** [bromite/bromite#190]
**Is your feature request related to privacy?**
Perhaps. I hope it would help to modify things on per site basis.

**Is there a patch available for this feature somewhere?**
don't know, there are webextensions which do that, but not expecting these APIs to work in mobile chrome.

**Describe the solution you'd like**
Chrome has rudimentary support for `javascript:` URIs. So I think it should be possible to add site-specific bookmarklets that can be automatically executed on a given site.

**Describe alternatives you've considered**
Bookmarklets didnt work for me. One can always copy paste `javascript` URIs but a troublesome thing.

**Comment by csagan5** [comment]
It would be nice, I thought of this in the past, but unlikely to happen at the current pace of development (myself alone).

It would require an UI part to configure the scripts and an engine part to trigger them when it's needed; it would expand the scope beyond what it is currently (privacy patches alone) and it is not strictly about privacy but more in the realm of Greasemonkey and the like.

I will leave this open for now, but likely will be closed in future as there is no interest to implement it nor maintain the patches needed for it.

**Comment by csagan5** [comment]
@projectextremum that is still an UI to be implemented

**Comment by Madis0** [comment]
>Bookmarklets didnt work for me.

Didn't _work_ or didn't _suit_ you? FYI, bookmarklets can easily be used in two easy ways on mobile Chromium:

1. Bookmark any site
2. Change it's URL to a bookmarklet
3. Go to a site you want to execute the bookmarklet in
4. Search the omnibox for the bookmark name, tap on it
5. Bookmarklet will activate on the current page

or

1. Enable home button
2. Set bookmarklet URL as the home URL
3. Go to a site you want to execute the bookmarklet in
4. Tap the home button

**Comment by projectextremum** [comment]
Problem with bookmarklets is that they are still a lot of manual work.

**Comment by csagan5** [comment]
Two key points:
* this is not related to privacy
* I am not going to work on this feature and seems like nobody else involved in this conversation is

I am closing this.
