### ISSUE TITLE
Presearch (Decentralized Search Engine) as default search engine

### ISSUE THREAD

**Issue by bagaweb** [bromite/bromite#1917]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

no idea

### Describe the solution you would like

Hello I just wanted to ask how to implement Presearch (is a Decentralized Search Engine) as default search engine.

### Describe alternatives you have considered

another browser

**Comment by JustAnUserLol** [comment]
Please read https://github.com/bromite/bromite/blob/master/FAQ.md#can-you-add-this-search-engine-as-default

**Comment by bagaweb** [comment]
Alright thanks, I will switch to Mull.

**Comment by JustAnUserLol** [comment]
> Alright thanks, I will switch to Mull.

btw you can set a custom search engine in Bromite also...

**Comment by bagaweb** [comment]
Hmmmm would you please tell me how?

**Comment by JustAnUserLol** [comment]
> Hmmmm would you please tell me how?

github.com/bromite/bromite/wiki/searchengine

**Comment by bagaweb** [comment]
Thanks @JustAnUserLol 
I have already tried that without succeeding...

> 1. Visit the search engine home page.
> 2. Perform a search.
> 3. The search engine can now be selected as a default.

1.  Step 1 done
2.  Step 2 done
3.  Where or how can I select the search engine as default?

**Comment by JustAnUserLol** [comment]
> Where or how can I select the search engine as default?

Settings -> Search Engine

NOTE: The search engine should support [OpenSearch ](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) to be used as Default Search Engine.

**Comment by bagaweb** [comment]
Thanks I was able to solve the issue.
