### ISSUE TITLE
Show a warning if user tries to enable JIT

### ISSUE THREAD

**Issue by ghost** [bromite/bromite#1931]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No.

### Describe the solution you would like

Show a warning when user tries to enable JIT

Something like :-

"Enabling JIT may make you vulnureble to attacks, Enable it at Your Own Risk"

### Describe alternatives you have considered

None.

**Comment by csagan5** [comment]
There is already a description, it could be improved a bit.

**Comment by csagan5** [comment]
Fixed in `100.0.4896.57`.
