### ISSUE TITLE
Enable IsClearTextPermitted flag by default

### ISSUE THREAD

**Issue by ghost** [bromite/bromite#1935]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

Not i am aware of.

### Describe the solution you would like

Enable IsClearTextPermitted Flag by default

### Describe alternatives you have considered

none.

**Comment by JustAnUserLol** [comment]
The IsClearTextPermitted flag is not enabled by default; Even if it is in the [patch](https://github.com/bromite/bromite/blob/8066120fa37f73e356ff0983b0ec8417c6c5cab5/build/patches/Add-IsCleartextPermitted-flag.patch#L63)
![Screenshot_20220328-201724](https://user-images.githubusercontent.com/95953932/160425037-87e73f71-193c-4d94-80fe-e1206761bad1.jpg)

![Screenshot_20220328-201629-1](https://user-images.githubusercontent.com/95953932/160424780-1148f330-db0d-4e4f-b715-c806ceb4c49c.jpg)
![Screenshot_20220328-200332](https://user-images.githubusercontent.com/95953932/160424862-49f73348-26ea-4df2-9124-a3a5c05b3c06.jpg)

**Comment by uazo** [comment]
> IsClearTextPermitted flag is not enabled by default

everything works as expected.
IsClearText**Permitted** flag is **enabled** by default, so _http_ is allowed.

**Comment by csagan5** [comment]
I can confirm, it is working as intended.
