### ISSUE TITLE
Mobile user agent is not the same in headers and JavaScript

### ISSUE THREAD

**Issue by Aha4593** [bromite/bromite#1936]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

99.0.4844.77

### Device architecture

arm64-v8a

### Android version

10

### Device model

STK-L21

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

If you change the mobile user agent and check it using the "whoer.net" website you can see that the user agent in headers and JavaScript is not the same. But it still works fine in desktop mode.

### Steps to reproduce the bug

1. Change mobile user agent
2. Open "whoer.net" website
3. You will see that it says the headers are not the same
4. Scroll down and it will show the new user agent in headers but it will show your original user agent in JavaScript.

### Expected behavior

It had to show the same user agent through headers and JavaScript.

### Screenshots

![Screenshot_20220328_210838](https://user-images.githubusercontent.com/69200026/160446833-67850575-d9db-403f-b92f-01cb0ddd1c4b.jpg)

**Comment by uazo** [comment]
that script uses `window.navigator["userAgent"]`, I have no idea why this is incorrect

**Comment by csagan5** [comment]
It's ok, we will figure it out eventually. Perhaps the sub-process has the old value?

**Comment by uazo** [comment]
no, i think it is because of the changes they have made regarding the ua reduction, probably if it is active it reconstructs the value from the build, ignoring the changes made

**Comment by csagan5** [comment]
Fixed in `100.0.4896.83`.
