### ISSUE TITLE
Flag or permanent disable of incognito cookie restore

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#1939]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

Cookies are restored even in incognito mode when the app is killed, see https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/profiles/android/java/src/org/chromium/chrome/browser/cookies/CookiesFetcher.java;l=35

It would be best to not restore any cookie when this happens.

### Describe alternatives you have considered

None

**Comment by csagan5** [comment]
@uazo this was originally your idea

**Comment by uazo** [comment]
> Cookies are restored even in incognito mode when the app is killed

... only by oom

if the user closes it, recovery is not possible because they are encrypted with a key put in session, and the session is reset on restart.
