### ISSUE TITLE
adblock control panel for better privacy management

### ISSUE THREAD

**Issue by leedoyle** [bromite/bromite#194]
This is a privacy related feature, as with current implementation the way Adblock functions is somewhat of a black box.  The way it is now it gives no control over adblock and a sense of insecurity.

I would like to be able to choose adblock subscription lists (based on my region, language and own preference) and be able to switch on and off third party javascript and media on websites (for the sake of privacy, security and increased performance).

**Comment by Madis0** [comment]
Duplicate of #2
