### ISSUE TITLE
Wrong info about OS displayed in Bromite android

### ISSUE THREAD

**Issue by robovoice1** [bromite/bromite#1941]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

100.0.4896.57

### Device architecture

arm64

### Android version

12

### Device model

Google Pixel 6 pro  GrapheneOS

### Changed flags

No flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

Samsung build is displayed, in fact it is a Pixel 6 pro

### Steps to reproduce the bug

Go to settings/about bromite

### Expected behavior

Correct info is displayed

### Screenshots

![Screenshot_20220331-154937](https://user-images.githubusercontent.com/92784377/161074723-47c4689d-74a5-45f8-9437-7979abd8fbfc.png)
![Screenshot_20220331-154922](https://user-images.githubusercontent.com/92784377/161074848-f1419a18-1c4c-4d05-9f43-c20bf02a4950.png)

**Comment by AlbertEienstein** [comment]
This is not a bug; In fact, Bromite changes the 'User Agent' to prevent fingerprinting and That's the same reason it shows wrong info about OS.

**Comment by robovoice1** [comment]
Thanks. Closing this "bug".

**Comment by csagan5** [comment]
I will document this in the README.md.

The model displayed in the About view could probably be changed as well with a different patch.
