### ISSUE TITLE
Support Extended DoH Adresses

### ISSUE THREAD

**Issue by AzureB1te** [bromite/bromite#1945]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

Only in desktop browsers as of my knowleadge. 

### Describe the solution you would like

Currently, only basic DoH adresses are allowed. 
An example would be https://dns11.quad9.net/dns-query
As you know, Bromite's ad-blocking capabities are rather limited. So I propose support for a service like Next DNS as the solution for this. The adresses look like this
https://dns.nextdns.io/config
Currently, Bromite doesn't support these adresses. (Neither does upstream as of my knowleadge). 

### Describe alternatives you have considered

N/A

**Comment by n-buna404** [comment]
It should works when you use custom dns.
For example, https://basic.rethinkdns.com/1:0B9_AP__-P8gATSAgABAAAAg works fine on bromite from my own testing

**Comment by csagan5** [comment]
> So I propose support for a service like Next DNS as the solution for this. The adresses look like this https://dns.nextdns.io/config Currently, Bromite doesn't support these adresses. (Neither does upstream as of my knowleadge).

What is the format you are referring to? Is it a standard format?
