### ISSUE TITLE
Remove the recent tabs entry from hamburger menu when history is disabled

### ISSUE THREAD

**Issue by AzureB1te** [bromite/bromite#1946]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

Not sure 

### Describe the solution you would like

When you run Bromite with history off, the recent tabs menu is redundant. I suggest removing this. 

### Describe alternatives you have considered

Allow customization of the hamburger menu, to freely enable/disable enteies

**Comment by csagan5** [comment]
This is unrelated to privacy and constitutes a minor hindrance.
