### ISSUE TITLE
WebView integration failed

### ISSUE THREAD

**Issue by dic1911** [bromite/bromite#1951]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

v100.0.4896.57

### Device architecture

arm64-v8a

### Android version

12

### Device model

Pixel 4a 5G

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

Yes

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

I couldn't have Bromite System Webview to show in the WebView selector in developer options.

### Steps to reproduce the bug

1. Patched the values in `frameworks/base/core/res/xml/config_webview_packages.xml` just like the wiki page mentioned
2. Build/Compile the ROM
3. The build boots up without usable WebView provider

### Expected behavior

Bromite WebView to show up as default and the only WebView provider.

**Comment by csagan5** [comment]
> Please note that no support for System WebView installation is provided.
