### ISSUE TITLE
Dialog to store passwords does not show anymore

### ISSUE THREAD

**Issue by diresi** [bromite/bromite#1956]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

100.0.4896.57

### Device architecture

arm64

### Android version

10

### Device model

Xiaomi MI 8

### Changed flags

enable-tab-groups=enabled

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No.

### Describe the bug

When not using Android's autofill API Bromite doesn't offer to store manually entered credentials on websites anymore, i.e. when logging into github.com.
I tried both enabling/disabling "native Android autofill" in the settings and then log into websites, this doesn't seem to make a difference.

Autofill API itself seems to work when enabled, i.e. it offered access to password-store.

Plain Chromium shows a popup asking whether to save the password.

### Steps to reproduce the bug

1. Go to Settings/Passwords and set "Save passwords" to on, "Enable native Android autofill" to off.
2. Go to github.com and log out if necessary
3. Sign in by typing your credentials
4. Try to save credentials in Bromite, notice it doesn't ask whether it should do so.

### Expected behavior

It should show a popup asking wether to save the password for the given site and do so, if confirmed.
Upon the next visit to this site it should offer to fill in those credentials again.

**Comment by csagan5** [comment]
Most likely a bug introduced in [99.0.4844.55](https://github.com/bromite/bromite/blob/master/CHANGELOG.md#990484458) with the removal of contextual search.

**Comment by csagan5** [comment]
It was still working in `99.0.4844.77` so the bug must have been introduced with `100.0.4896.57`.

**Comment by csagan5** [comment]
@uazo do you have any insight on this? I am currently debugging it, asking just in case you have some serendipitous insight on it.

**Comment by uazo** [comment]
> do you have any insight on this? 

I'm sorry I don't know, one of my faults is the lack of memory.
I would have looked at it today, but you screwed me :) with yesterday's release, I have to realign my environment with the latest one, then I look at it.

**Comment by csagan5** [comment]
Sorry :) so far I could only understand that when a form is submitted with a successful login, somehow it is not recognised as such and thus the dialog will not appear.

**Comment by diresi** [comment]
Thank you for taking care of this issue, also It's nice following your conversation :)
Is there anything I can do to help you?

**Comment by uazo** [comment]
@csagan5 the bug is [here](https://source.chromium.org/chromium/chromium/src/+/main:components/password_manager/core/browser/password_manager.cc;l=1016;drc=4b03575fc3a5f7e1fd5cde04d33c204572fd9c29;bpv=1;bpt=1?q=PasswordManager::OnLoginSuccessful&ss=chromium%2Fchromium%2Fsrc) because it enters the `if`
now I check what has changed

**Comment by uazo** [comment]
the bug is in [Remove-signin-integrations.patch](https://github.com/bromite/bromite/blob/master/build/patches/Remove-signin-integrations.patch#L2908).  that method must return `true`
will you take care of fixing it?

**Comment by csagan5** [comment]
Thanks for finding this; yes, I will update the patch for next release.

**Comment by csagan5** [comment]
Fixed in `100.0.4896.92`.

**Comment by diresi** [comment]
Perfect! Works like a charm again. Thanks a lot!
