### ISSUE TITLE
Icon is pretty blurry

### ISSUE THREAD

**Issue by L11R** [bromite/bromite#197]
**Bromite version**

Version: `71.0.3578.72`
Arch: `arm64`
Android version: 8.1 (Oreo)

**Is the bug reproducible with latest version?**
`Yes`

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
`No`

**Describe the bug**
I see issue #181 as resolved, but I just downloaded the latest build and it still pretty blurry :(

**To Reproduce**
1. Install app.
2. See this blurry icon.

**Expected behavior**
Sharp icon like any other on my phone.

**Screenshots**
![screenshot_20181203-090558 2](https://user-images.githubusercontent.com/5345489/49355934-d4e6d080-f6da-11e8-8ba3-a5808f9647d9.png)

**Comment by L11R** [comment]
Thanks, hope will be fixed!

**Comment by csagan5** [comment]
@L11R no problem, the template is always useful as other users in the future (with a newer version that has the fix) might check here the history of a problem.

The current icon does not use vector drawables, I should be able to fix that.

**Comment by L11R** [comment]
@csagan5 I guess vector not the only solution. Some other icons on my phone definitely just raster with high definition like 256x256 or even 512x512.

**Comment by csagan5** [comment]
@L11R yes, that is true, I think the conversion to raster I use is just not very good and adds unnecessary blur (and it is more evident on round shapes without contour).

**Comment by L11R** [comment]
After `71.0.3578.76` update seems like icon now sharp as should! Will do small donation later, thanks for your work.
