### ISSUE TITLE
Is it possible to add a url cleaner?

### ISSUE THREAD

**Issue by dstrelnikov** [bromite/bromite#1978]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No.

### Describe the solution you would like

Some kind of URL cleaner extension in order to remove tracking while following the links. 

### Describe alternatives you have considered

I'm not aware of any alternatives.

**Comment by fourbearscourses** [comment]
should be possible with a UserScript.
