### ISSUE TITLE
Consider a more lightweight filter list

### ISSUE THREAD

**Issue by Noexpert** [bromite/bromite#198]
On my tablet, Bromite still lags and scrolling is janky when adblock is enabled.
It's a Huawei MediaPad M3 8 Lite.

This is the same issue described here: https://github.com/bromite/bromite/issues/90
Could a smaller filter list help?

[Blockada](https://github.com/blokadaorg/blokada) uses the "lightweight" [Energized Blu](https://github.com/EnergizedProtection/block) 83,952 line filters: 
https://raw.githubusercontent.com/EnergizedProtection/EnergizedBlu/master/energized/blu_go.txt

**Comment by ouzowtf** [comment]
Why do you open another issue knowing that such an issue already exists?
And if you use Blockada, why do you use adblock in Bromite?

**Comment by csagan5** [comment]
> On my tablet, Bromite still lags and scrolling is janky when adblock is enabled.
> It's a Huawei MediaPad M3 8 Lite.
> 
> This is the same issue described here: #90

That issue was reproducible with Chromium, thus unrelated to adblock filters. Have you read the whole issue and tested with Chromium?

> Could a smaller filter list help?
> 
If it is reproducible with Chromium no; otherwise you can and and should test with adblock enabled/disabled, but this issue you reported is missing the issue template (either you reported from mobile or you willingly deleted it). Please note that anything reported without issue template cannot be used for any bug troubleshooting or feature enhancement.

> [Blockada](https://github.com/blokadaorg/blokada) uses the "lightweight" [Energized Blu](https://github.com/EnergizedProtection/block) 83,952 line filters:
> https://raw.githubusercontent.com/EnergizedProtection/EnergizedBlu/master/energized/blu_go.txt

I have tried in the past to run some tests with the UltraPrivacy list(s), however a lot of testcases would fail so I never changed it. If we switch now the lists in Bromite, lots of users will complain about it, so the proper solution is still #2 and there users can specify the lists they like. I will consider the list you mentioned as a possible default when #2 is resolved.

**Comment by Noexpert** [comment]
@ouzowtf 
> Why do you open another issue knowing that such an issue already exists?
That issue is closed.

> And if you use Blockada, why do you use adblock in Bromite?
Blockada doesn't block Google search results.

**Comment by Noexpert** [comment]
@csagan5 

Understood re bug template, and here it is:

**Bromite version**
Version: 71.0.3578.85
Arch: arm64-v8a
Android version: 7.0

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding Chromium version?**
No. Also not reproducible in Bromite when Adblock is off.

**Is the bug a crash?**
No

Describe the bug A clear and concise description of what the bug is.
Janky, choppy scrolling on websites as images as loaded.

**To Reproduce Steps to reproduce the behavior:**
    Go to bbc.co.uk/news
    Scroll down to rapidly to the bottom of the page
    
**Expected behavior** 
Scrolling should be smooth and image appearing smoothly as is the case in Chromium.

**Comment by csagan5** [comment]
> **Can the bug be reproduced with corresponding Chromium version?**
> No. Also not reproducible in Bromite when Adblock is off.

Then if this is due to the adblock engine, there is nothing I can do. #2 might help but replacing the engine is out of question; patches for improvements are welcome.

**Comment by Noexpert** [comment]
OK thanks.
One suggestion to improve this: [Samsung Internet Browser](https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser&hl=en_GB) is Chromium based and has a number of content blockers.

When one of these are activated it does not impact scrolling at all.
Perhaps this will give you some ideas as to how to improve scrolling.

**Comment by csagan5** [comment]
> One suggestion to improve this: [Samsung Internet Browser](https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser&hl=en_GB) is Chromium based and has a number of content blockers.
> 
> When one of these are activated it does not impact scrolling at all.
> Perhaps this will give you some ideas as to how to improve scrolling.

Where is the source code?

**Comment by csagan5** [comment]
> I believe the source code is here:
> https://opensource.samsung.com/reception/receptionSub.do?method=sub&sub=F&searchValue=SBrowser
> 
> EDIT
> Or if that link doesn't work, go here: http://opensource.samsung.com/reception.do
> And search for "sbrowser".

It gives errors in both cases.

Those are contributions that Samsung decides to give upstream to Chromium, but not the source code of the full browser and of the adblocker part in particular.

**Comment by Noexpert** [comment]
Yes, their website is not very stable at the moment.

You could try:
(1) Navigating: -> Mobile (link at the top) -> Samsung (in the tree link on the left) -> Third page of results and then you'll see SBrowser v7 with a link to SBrowser.tar.gz.

(2) Or you can try this link:
https://opensource.samsung.com/reception/receptionSub.do?method=sub&sub=T&menu_item=mobile&classification1=mobile_application&classification2=samsung

As I said, it might be worth a few minutes of your time to see how they do it.

**Comment by Noexpert** [comment]
(3) Or if you're struggling with the above, I've uploaded it here (file available for the next 30 days):
https://ufile.io/awg6s

**Comment by csagan5** [comment]
@Noexpert I started the download from their website, quite slow but it'll do. I will give a look when it's done, thanks.

I suspect it will not contain individual patches so it's not trivial to use the code on top of Chromium codebase.

Even if I find the relevant section, I doubt any effort to replace or change the engine can be started.

**Comment by csagan5** [comment]
As I suspected the code contains no git commits information...so one has to diff it against Chromium versions to find out the minimum changeset.

**Comment by Noexpert** [comment]
No problem.
I'll follow https://github.com/bromite/bromite/issues/203 in the meantime.

Thanks

**Comment by csagan5** [comment]
For the records, the Samsung Browser source code is based on Chromium 59.0.3071.125 

I suspect this would be no different from the CAF codebase I checked some time ago.
