### ISSUE TITLE
Canvas fingerprinting deception

### ISSUE THREAD

**Issue by TheFireKahuna** [bromite/bromite#2009]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

Currently on a Pixel 6 Pro, latest Bromite, GrapheneOS latest, the bromite fingerprinting test, and amiunique  provide a unique Canvas/getRect fingerprint on default settings. Also a unique mediadevices fingerprint on amIUnique.

### Describe alternatives you have considered

Possibly because of GrapheneOS but unsure.

**Comment by csagan5** [comment]
Working as intended, see https://github.com/bromite/bromite/wiki/Fingerprinting
