### ISSUE TITLE
Camera screen not launching when requested by website

### ISSUE THREAD

**Issue by ElderHallow** [bromite/bromite#2019]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

100.0.4896.135

### Device architecture

arm64-v8a

### Android version

12

### Device model

Pixel 5

### Changed flags

Web Feed enabled
Allow user certificates
Bottom address bar

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No.

### Describe the bug

The camera screen launches but remains blank. I am unable to use it to scan QR codes. 

### Steps to reproduce the bug

1. Go to a website that needs the camera
2. Allow the camera permission on the site
3. Camera screen loads but remains blank. 
4. Green dot in corner of phone screen shows indicating that the camera is in use.

### Expected behavior

The camera screen usually displays and allows me to scan QR codes. This is not happening.

### Screenshots

![Screenshot_20220424-113317](https://user-images.githubusercontent.com/83273463/164972336-f3686f12-a273-4f28-8761-4b08c4226812.png)

**Comment by uazo** [comment]
> Go to a website that needs the camera

could you indicate the url?

**Comment by ElderHallow** [comment]
Hi thanks for getting back to me.

The URL is:
https://test-for-coronavirus.service.gov.uk/report-result/barcode/scan

Thanks!

**Comment by uazo** [comment]
Sorry but that site says
```
If you're outside the UK
You cannot access UK coronavirus services from outside the UK. 
```

**Comment by ElderHallow** [comment]
Oh no! It's weird because every other browser I use the camera engages and
works. It's just Bromite it doesn't work on and it's only that site as
well. The funny thing is, that it did work until about two updates ago.

Never mind I'll have to use Chrome in future for this.

Thank you for your time.

Alex.
