### ISSUE TITLE
AMP links not sanitised

### ISSUE THREAD

**Issue by thanuj10** [bromite/bromite#202]
**Bromite version**

Version: `71.0.3578.98`
Arch: `arm`
Android version: Nougat 7.1.2

**Is the bug reproducible with latest version?**
Yes.

**Can the bug be reproduced with corresponding Chromium version?**
Not applicable. Chromium based browsers feature AMP links. Disabling AMP links is a Bromite specific feature.

**Describe the bug**
Browsing through Google Search results presents AMP Links.

**To Reproduce**
1. Go to Google.com
2. Search for anything
3. Tap on an AMP link

**Expected behavior**
AMP links should be skipped and user must directly be taken to the original website.
I have tested with 2 different websites and that seems to be result.

**Comment by thanuj10** [comment]
Interestingly I found this when investigating issue about laggy scrolling on low-end devices when AdBlocking is enabled. Can confirm that AdBlocking makes scrolling laggy on Bromite.

**Comment by csagan5** [comment]
> Interestingly I found this when investigating issue about laggy scrolling on low-end devices when AdBlocking is enabled. Can confirm that AdBlocking makes scrolling laggy on Bromite. Lag occurs when images are loading and once images load the lag dissappers.

You need a separate issue for that, we cannot discuss it here as this one is about the AMP links.

**Comment by thanuj10** [comment]
> You need a separate issue for that, we cannot discuss it here as this one is about the AMP links.

I shall open a seperate issue for that.

**Comment by csagan5** [comment]
I have updated this issue to reflect the fact that AMP sanitisation is not working regardless of the AdBlock being enabled or not.

**Comment by csagan5** [comment]
Fixed in `71.0.3578.104` (not yet released)
