### ISSUE TITLE
When "disabling" `move-top-toolbar-to-bottom` Flag It actually Enables It.

### ISSUE THREAD

**Issue by fourbearscourses** [bromite/bromite#2024]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

100.0.4896.135

### Device architecture

armeabi-v7a

### Android version

8.1

### Device model

SM-J260GDDU8AUD1

### Changed flags

move-top-toolbar-to-bottom, offline-indicator-v2, cleartext-permitted

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No.

### Describe the bug

When Disabling the `move-top-toolbar-to-bottom` flag, It actually enables It instead of Disabling It.

### Steps to reproduce the bug

1. Go to `chrome://flags#move-top-toolbar-to-bottom`
2. "Disable" It
3. Restart
4. See

### Expected behavior

It should **Disable** It, Enabling it When the user actually Disables It does not make sense.

### Screenshots

![Screenshot_20220425-131936-1](https://user-images.githubusercontent.com/103592465/165045506-512c3414-587d-4419-bd39-98407dc24d0b.jpg)

**Comment by virtualb1** [comment]
https://github.com/bromite/bromite/issues/1996#issuecomment-1102532459
That flag is accessible from the accessibility settings, it will be removed from chrome://flags
