### ISSUE TITLE
Update the Description of `Ads` site setting

### ISSUE THREAD

**Issue by fourbearscourses** [bromite/bromite#2026]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

No

### Is there a patch available for this feature somewhere?

I don't know.

### Describe the solution you would like

The "default" Description of the `Ads` Site Setting, is misleading for Bromite.

This is what it says :
`Block ads on sites that show intrusive or misleading ads.`

That isn't the case in Bromite, because The bromite ad blocker doesn't discriminate between "Misleading or Intrusive" or "Acceptable" ads, It blocks all of Them.

Hence, the Description should be Changed.

### Describe alternatives you have considered

None.

**Comment by csagan5** [comment]
Fixed in `102.0.5005.67`.
