### ISSUE TITLE
Laggy scrolling on various devices

### ISSUE THREAD

**Issue by thanuj10** [bromite/bromite#203]
**Bromite version**

Version: 71.0.3578.101
Arch: ARM and ARM64
Android version: Nougat 7.1.2(ARM) & Marshmallow 6.0(ARM64)

**Is the bug reproducible with latest version?**
Yes.

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No as Chromium does not have Bromite's Adblocking engine.

**Describe the bug**
Browsing on a page with lots of images and elements with Adblocking enabled, Causes the scrolling to be laggy. The laggy scrolling seems to resolve once the images and elements are completely loaded. It also happens on Google search results page.

**To Reproduce**
1. Go to any news website or www.google.com
2. Scroll down the page while images are loading
3. See laggy scrolling while images and elements are loading.

**Expected behavior**
A little bit stutter is accepeted as Chromium and Latest Chrome has the issue(Little stutter as images load, No lag). But Bromite just completely freezes for some Microseconds before responding to our scroll.

**Comment by thanuj10** [comment]
Using Modern Apk for ARM and ARM64 Seems to help a bit, But not by much. Using ARM apk on an ARM64 Device amplifies the laggy scrolling. 
My ARM device just freezed for each second an image loads up at flickr.com sign up page. This does not happen when adblocking is disabled. Interestingly, Images never loaded at flickr.com when adblocking was enabled but device lagged, Adblocking disabled, Images were cycling and bromite expericed micro-stutters as Chromium and Chrome experience, No where near like Bromite's lag.

**Comment by thanuj10** [comment]
I've tried enabling Lazy Frame loading for images, But that does not improve anything. I felt like it made scrolling a bit more laggy.

Also I used unsplash.com but the website does make the scrolling laggy. I think because the website loads 5 images before we even scroll over to them.

**Comment by csagan5** [comment]
> Also I used unsplash.com but the website does make the scrolling laggy. I think because the website loads 5 images before we even scroll over to them.

That is the point. You need a reference website to make tests and I picked that one.

**Comment by csagan5** [comment]
I think it's not just about images but any content (which has URLs to be checked by the adblocker).

I don't know what could be the resolution for this issue. #2 is going to help as you can choose your own filters.

I am not going to replace the adblock engine with a different one.

This issue won't fix, likely #2 will mitigate it.

**Comment by csagan5** [comment]
@Noexpert also on this one, the resolution can be #2 or at least with #2 more tests can be done.

I do not know what changed in v71 vs v70 that made lagging a bigger problem; the adblocking code already runs on the I/O thread so it would not be expected to affect the UI rendering (but it seems it is).
