### ISSUE TITLE
Move pop-up toolbar to the bottom when using bottom navigation-bar

### ISSUE THREAD

**Issue by M86xKC** [bromite/bromite#2030]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

No

### Is there a patch available for this feature somewhere?

probably yes, but I was not able to find it

### Describe the solution you would like

move the toolbar to the bottom when bottom navigation-bar is activated with the flag.

![image](https://user-images.githubusercontent.com/32685696/165966005-147d89db-e801-46c1-b652-6d3b30e2393d.png)

### Describe alternatives you have considered

N/A

**Comment by M86xKC** [comment]
context: https://github.com/bromite/bromite/issues/2011#issuecomment-1113336037

**Comment by csagan5** [comment]
Fixed in `101.0.4951.53`.
