### ISSUE TITLE
Bromite.org is not mobile-friendly

### ISSUE THREAD

**Issue by Madis0** [bromite/bromite#204]
**Bromite version**

Version: `71.0.3578.101`
Arch: `arm64`
Android version: `Oreo 8.1`

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
Yes

**Is the bug a crash?**
No

**Describe the bug**
The website is about a mobile browser and catered to a mobile audience (the download section). However, it doesn't look responsive on a mobile browser, such as Bromite itself.

**To Reproduce**
1. Go to [bromite.org](https://bromite.org)
2. See small text/zoomed out content

**Expected behavior**
A website with responsive design.

**Screenshots**
N/A

**Comment by lowtrucks** [comment]
lol.

**Comment by Madis0** [comment]
Well, the website repo has issue support disabled. Regardless, I've made a PR now: https://github.com/bromite/bromite.github.io/pull/1

**Comment by csagan5** [comment]
Discussion continues on that PR.
