### ISSUE TITLE
Add setting for allowing screenshots in Incognito mode

### ISSUE THREAD

**Issue by Etim-Orb** [bromite/bromite#2042]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

I sometimes struggle with taking screenshots, since I use Bromite in an Always Incognito manner. I saw the new Incognito settings menu under the privacy settings and thought an "Allow screenshots in Incognito mode" settings would be great.

### Describe alternatives you have considered

The only solution I have thought of is written above.

**Comment by csagan5** [comment]
There is already a flag for this.

**Comment by Etim-Orb** [comment]
@csagan5 I didn't know that. I'm not really familiar with flags so I prefer regular settings.

**Comment by csagan5** [comment]
> * I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)

^

**Comment by Etim-Orb** [comment]
@csagan5 Could you specify what do you think I overlooked in the Readme?

**Comment by csagan5** [comment]
The flag that allows screenshots in incognito mode.

**Comment by Etim-Orb** [comment]
That's great but I would personally prefer a settings toggle.

**Comment by ArchangeGabriel** [comment]
I would also prefer a settings toggle, other apps do that and it’s more discoverable. Also, the flag in the README was outdated, I PR’ed https://github.com/bromite/bromite/pull/2075 for that.
