### ISSUE TITLE
Popups being able to be blocked/diverted to another tab without changing tabs

### ISSUE THREAD

**Issue by UnboltedWork** [bromite/bromite#2043]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

Well I know that modern content and ad-blocker's also feature popup blockers like uBlock Origin.

### Describe the solution you would like

Have a setting in the "Privacy and Security" settings section which allows you to block popups. Simply a dialog will popup will and giving you an option to view that popup, because some popups may be helpful like Google Translate ones etc.

### Describe alternatives you have considered

I think this would also be great too! Insteading of blocking them, maybe have a feature which diverts the popup to another tab AND not switch automatically.

**Comment by AzureB1te** [comment]
This is something I have a lot of trouble with. Great suggestion

**Comment by uazo** [comment]
to better understand, can you provide some example url?

**Comment by AzureB1te** [comment]
> to better understand, can you provide some example url?

I'm not the original poster, but I can provide websites I had trouble on. 
Any derivative of soap2day (for example soap2day.ac) triggers popups when clicking basically anywhere.

**Comment by fourbearscourses** [comment]
Already Possible via User Scripts. bundling the feature into the Browser would require regular updates to block as much pop-ups as possible.

**Comment by uazo** [comment]
> Any derivative of soap2day (for example soap2day.ac) triggers popups when clicking basically anywhere.

I can't reproduce it, happens with the latest version of bromite?

> Already Possible via User Scripts. bundling the feature into the Browser would require regular updates to block as much pop-ups as possible.

you may be right, but I would be interested in understanding why they are not blocked.

**Comment by lipici** [comment]
I dont have a problem with these settings with last version plus disabled java git.

Also i think these are default settings but i always adjust my settings so you can give it a try.

![Screenshot_20220504-164351](https://user-images.githubusercontent.com/46893370/166695109-6c33efbd-ed5a-4fa6-8951-2b0f20981c02.png)
![Screenshot_20220504-164445](https://user-images.githubusercontent.com/46893370/166695117-6575cb7b-3867-4f66-a6ce-9181e728b7ab.png)

**Comment by lipici** [comment]
![Screenshot_20220504-165303](https://user-images.githubusercontent.com/46893370/166696217-41c45349-43ca-45aa-9016-8854910905e5.png)

**Comment by csagan5** [comment]
> Have a setting in the "Privacy and Security" settings section which allows you to block popups.

There is already a site setting for it.

> Simply a dialog will popup will and giving you an option to view that popup, because some popups may be helpful like Google Translate ones etc.

A popup to allow a popup? That would be a bad idea.

**Comment by BigDogg99** [comment]
> A popup to allow a popup? That would be a bad idea.
a pop to allow or diable pop from certain site. like if its usefull popup i have alow it once and forget about it and if its junk then i have abilty to disable it

**Comment by BigDogg99** [comment]
> to better understand, can you provide some example url?

[you can not watch anything in videovard in this browser ](https://9anime.id/watch/shikimoris-not-just-a-cutie.zlljw/ep-11)  in oneclick six tab try to open
