### ISSUE TITLE
Allow Blocking/Allowing `Third-party sign-in` on specific sites

### ISSUE THREAD

**Issue by fourbearscourses** [bromite/bromite#2047]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

Right Now, `Third-party sign-in` cannot be allowed/blocked for specific sites, and that's a problem, like you may want to block `Third-party sign-in for a specific site, and not allow for other sites to protect privacy.

Therefore, there should be the feature to allow/block `Third-party sign-in` on a specific site.

### Describe alternatives you have considered

none

**Comment by lipici** [comment]
![Screenshot_20220504-162936](https://user-images.githubusercontent.com/46893370/166691556-366ec270-eb69-40b2-b51c-9ab038debb26.png)
![Screenshot_20220504-162944](https://user-images.githubusercontent.com/46893370/166691562-343c90bb-0e7b-4144-8a05-07852855333b.png)
![Screenshot_20220504-163044](https://user-images.githubusercontent.com/46893370/166691566-62ea356d-956e-4d86-ae64-29f75f13b263.png)

Its working, for everysite.

**Comment by lipici** [comment]
![Screenshot_20220504-163343_1](https://user-images.githubusercontent.com/46893370/166692500-e096c63b-c5de-45f7-b6f1-cf29d2c3a19f.png)

**Comment by csagan5** [comment]
How does third-party sign-in currently work in Bromite?

**Comment by uazo** [comment]
> How does third-party sign-in currently work in Bromite?

Setting to indicate whether browser should allow signing into a website via the browser FedCM API.

**Comment by lipici** [comment]
> How does third-party sign-in currently work in Bromite?

Bro, what offtopic ? I just proved you that third party cookies works for every specific site but if you deactivate third party cookies from browser settings they are still active in specific browser settings.

**Comment by csagan5** [comment]
@lipici read the issue title. This is not about cookies, please stop posting here about that.

**Comment by csagan5** [comment]
> > How does third-party sign-in currently work in Bromite?
> 
> Setting to indicate whether browser should allow signing into a website via the browser FedCM API.

And does it work without Play Store integrations? I have never tried this feature.

**Comment by uazo** [comment]
no, I don't think there is any external library involved:
https://source.chromium.org/chromium/chromium/src/+/main:content/browser/webid/README.md;bpv=1;bpt=0

**Comment by lipici** [comment]
If you block third party cookies how can you log using third party sign in ? Can you log without cookies ?

**Comment by uazo** [comment]
> Can you log without cookies ?

no, for now:
```
  // TODO(npm): FedCM is currently restricted to contexts where third party
  // cookies are not blocked.  Once the privacy improvements for the API are
  // implemented, remove this restriction. See https://crbug.com/1304396.
```

**Comment by csagan5** [comment]
@uazo what do you think, is making this site-specific a lot of work?

**Comment by uazo** [comment]
it's already there, we just have to change the default value to off

![image](https://user-images.githubusercontent.com/29201891/168414056-9437d27a-542e-4931-a229-24349aca912c.png)

**Comment by lipici** [comment]
> it's already there, we just have to change the default value to off
> 
> ![image](https://user-images.githubusercontent.com/29201891/168414056-9437d27a-542e-4931-a229-24349aca912c.png)

Dosent work.

**Comment by uazo** [comment]
> Dosent work.

any way to verify it?

**Comment by lipici** [comment]
You block them then when you try to login to linkedin or steam from third party site, still working.

**Comment by lipici** [comment]
I mean i log in with twitter account, linkedin, steam on any other site with them blocked. And this it was on all bromite version, not just on last one.

**Comment by csagan5** [comment]
> it's already there, we just have to change the default value to off

Ok, then let's add this too.

**Comment by uazo** [comment]
> And this it was on all bromite version, not just on last one.

I can't figure out if it's a bug or a new request. how does it work in chromium vanilla? do you detect the same behavior as bromite? the option disables the use of FedCM API not the possibility of logging in in third-party contexts.

**Comment by csagan5** [comment]
@uazo this feature needs third-party cookies in order to work; we are not discussing third-party cookies here. If they are disabled then the feature will not work, even if allowed.

**Comment by uazo** [comment]
>  If they are disabled then the feature will not work, even if allowed.

correct, I understand

**Comment by csagan5** [comment]
> > it's already there, we just have to change the default value to off
> 
> Ok, then let's add this too.

I checked this further; it is called internally `FEDERATED_IDENTITY_API` (or `webid-api`) and currently you can already set the default for all sites to be `BLOCKED` and then change an individual site to be `ALLOWED`; I do not think there is a privacy concern to make us want to set this as disabled by default. If you have reasons otherwise please comment here.

**Comment by uazo** [comment]
> If you have reasons otherwise please comment here.

https://github.com/fedidcg/FedCM/blob/main/privacy_questionnaire.md#5-do-the-features-in-your-specification-introduce-new-state-for-an-origin-that-persists-across-browsing-sessions
