### ISSUE TITLE
Odd behaviour with search or site suggestions when using bottom toolbar

### ISSUE THREAD

**Issue by IconBunnyGoing** [bromite/bromite#2049]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

101.0.4951.53

### Device architecture

arm64-v8a

### Android version

10

### Device model

Huawei Nova CDY-NX9B

### Changed flags

![Screenshot_20220419_123637](https://user-images.githubusercontent.com/96681422/166685186-46110bc8-6459-4cac-bef4-62fb0682320e.jpg)

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

When scrolling up through the search and site suggestions after inputting a character such that there are enough suggestions for it to be scrollable, the keyboard hides then shows again, leading to a janky experience. It somehow also resets the scroll position of suggestions to the bottom upon the keyboard reappearing, making it difficult to reach the top.

### Steps to reproduce the bug

1. Tap on address/search bar.
2. Start to search. Make sure there are enough suggestions for it to scroll. Example: 'e'.
3. Scroll up.

### Expected behavior

Either the keyboard should not hide itself when scrolling up, or the keyboard should not reappear after hiding.

**Comment by csagan5** [comment]
Fixed in `101.0.4951.69`.

**Comment by uazo** [comment]
> Fixed in 101.0.4951.69.

unfortunately the issue must be reopened. unfortunately my fix does not work, or at least it does not work in (my) device, while in the emulator it goes. i think i need to test it with multiple android versions.
