### ISSUE TITLE
Wrong device showing in 'google accounts' website

### ISSUE THREAD

**Issue by peta9** [bromite/bromite#205]
**Bromite version**
71.0.3578.104

Arch: arm
Android version: marshmallow 6.0.1

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding Chromium?**
Not sure

**Is the bug a crash?**
No

**Describe the bug**
Whenever I sign in my google account from this browser, it shows wrong device name as 'this device' (e. g. just now it is showing as **samsung galaxy j7** where, it should be **lenovo tab 2 x30f**. Not sure if it is a security issue.

**To Reproduce**
1. Go to https://accounts.google.com
2. Sign with a google account
3. Go to 'security' section
4. Expand the list of devices signed in
5. Look up the current device (as 'this device')

**Expected behavior**
It should show exactly the same device name.

**Screenshots**
![screenshot_20181224-142326](https://user-images.githubusercontent.com/44788763/50395087-eece7d00-0787-11e9-9d2a-002dea14a2b8.png)

**Comment by thanuj10** [comment]
If you signed into your Google account from Bromite, Then yes, The wrong device sign-in is intended. This is due to the fingerprint changes in Bromite for additional privacy.

**Comment by csagan5** [comment]
@peta9 yes, your correct device model is not reported in the user agent string (but a different, popular one); this is a feature of Bromite
