### ISSUE TITLE
Link Shortener skips

### ISSUE THREAD

**Issue by ag721git** [bromite/bromite#2055]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

Bypass or skip t.co/* or other link shortener services to go straight to the actual url. 
When using twitter on bromite it presents the real url but when actually clicking the link, we're redirected to twitters tracker t.co version. Chrome extensions like fastforward (listed below) allow one to skip the tracking redirect but bromite doesn't allow extensions. 
https://fastforward.team/example-links

It would be awesome if bromite could implement this skip natively into bromite and help close this tracking hole. This would also increase browsing speeds as every link clicked has to wait to redirect through the shortener site. 

### Describe alternatives you have considered

Tried to find and also write my own userscripts (an awesome feature in bromite) but was not able to either implement this correctly or find a working version available.

**Comment by uazo** [comment]
@csagan5 has already indicated the reason in other issues for which it is difficult to maintain that functionality directly in the browser.

I honestly do not see privacy problems related to links of that type if they are simple static 302 redirects (please prove me wrong), for those that point to intermediate pages that set cookies (or similar) my idea is always to make a patch that delete the storage when the page changes (it is one thing I'll do), in the meantime, there is the always incognito. I read that brave adopts another method, using ephemeral storage, but I don't know the details yet.

for sites that show a link and then lead to something else, perhaps with tracking parameters, unfortunately I think that the only correct way to proceed is to better look for some userscript capable of working in bromite (and possibly make it known to everyone :) made especially for that particular site or ask them to make a version on purpose or to never log in to that site (I realize, somewhat difficult).

instead, if you find a public maintained list with rules similar to those used by adblocks which eliminate tracking parameters, it might be different, and it would be interesting to verify it.

if there were to be a way at the network level it would be different, but, as far as I know, there isn't.

**Comment by uazo** [comment]
some useful information: https://github.com/privacycg/nav-tracking-mitigations
it looks like disconnected has some list, ref https://privacycg.github.io/nav-tracking-mitigations/#mitigations-firefox

**Comment by csagan5** [comment]
> @csagan5 has already indicated the reason in other issues for which it is difficult to maintain that functionality directly in the browser.

This is not the main reason: the main reason is that the browser must be neutral: you give an URL, it goes there. No rewriting, no AMP, no nothing.



> I honestly do not see privacy problems related to links of that type if they are simple static 302 redirects (please prove me wrong)

These URL shorteners are mostly used to track visits so you can know how many visits you sent to site X and how many conversions happened.

> instead, if you find a public maintained list with rules similar to those used by adblocks which eliminate tracking parameters, it might be different, and it would be interesting to verify it.

Was asked in #1978, it would require a dedicate separate project

**Comment by uazo** [comment]
> [csagan5](https://github.com/csagan5) closed this

so, without talking about it?

> it looks like disconnected has some list

what do you think about it?

**Comment by uazo** [comment]
> This is not the main reason: the main reason is that the browser must be neutral: you give an URL, it goes there. No rewriting, no AMP, no nothing.

that's not what I propose, I don't want to change the url, the idea of using ephemeral storage is interesting.

> can know how many visits you sent to site X

you're right, by static 302 I actually meant [301 Moved Permanently](https://en.wikipedia.org/wiki/HTTP_301) 

>  it would require a dedicate separate project

 maybe i never told you, but i would be able to bring  brave code in bromite, or at least understand what it does

> > it looks like disconnected has some list
>
> what do you think about it?

this question still applies! :)

**Comment by csagan5** [comment]
> > it looks like disconnected has some list
> 
> what do you think about it?

Quoting:
> Fourth, Brave uses a list-based approach for identifying bounce tracking URLs where the destination URL is present in the URL of the intermediate tracking URL. In such cases, Brave will skip the intermediate navigation and request the destination URL instead. For example, if Brave Browser observes the user about to navigate to the URL https://tracker.example/bounce?dest=https://destination.example/, the browser might replace the navigation to tracker.example/bounce, with a navigation to https://destination.example/. This list is maintained by Brave, and is drawn from a mix of crowd-sourcing and existing open-source projects.

Note "Maintained by Brave".

I still think it is not worth it, it would break the principle that the browser is neutral with the URL and would require a separate list similar to what is mentioned in #1978

> > can know how many visits you sent to site X
> 
> you're right, by static 302 I actually meant [301 Moved Permanently](https://en.wikipedia.org/wiki/HTTP_301)

There is no difference in terms of what the server-side can track. 301 or 302 is just a hint for the client to remember (or not) the redirect.

> > > it looks like disconnected has some list
> > 
> > 
> > what do you think about it?
> 
> this question still applies! :)

You replied to your own comment.

> i would be able to bring brave code in bromite

You should first check:
1. license
2. whether it is relevant for Bromite
3. whether it requires manually curated lists

I will not merge anything that requires manually curated lists.
