### ISSUE TITLE
Bromite Webview implementation doesn't show in Android Pie

### ISSUE THREAD

**Issue by bkb3** [bromite/bromite#206]
iirc, pie has com.android.webview package removed completely and uses Chrome's WebView. It, however, can use the package com.google.android.webview (Android system WebView, installable from play store) if available (this option is hidden in the developer settings). As such, bromite's WebView doesn't show up. 

https://imgoat.com/uploads/45117b0e0a/179383.png

**Comment by csagan5** [comment]
> No

You tested with Chromium Webview? I doubt it.

> I think it's because Bromite uses the package name `com.android.webview` which was (probably) removed starting from Android Pie.

Metropolitan legend. The package name does not matter, see upstream Chromium issue tracker for more.

You cannot install the System Webview without root; see https://github.com/bromite/bromite/wiki/Installing-SystemWebView for some (community-contributed) instructions; in general the issue tracker is not the place to go for support in installing the Webview.

**Comment by bkb3** [comment]
Thank you for the link. The problem is fixed by installing as a system app.

![image](https://imgoat.com/uploads/c5bde74a8f/181524.png)

**Comment by bkb3** [comment]
Thanks you for the link. It worked after installing as a system app. Awesome!

![image](https://imgoat.com/uploads/c5bde74a8f/181524.png)

For anyone having the same problem, convert to system app, reboot and install again.

**Comment by SixFingeredAmish** [comment]
Does this mean that there is no non-root way to install BromiteWebView on Android 9?

**Comment by bkb3** [comment]
@SixFingeredAmish 
Unfortunately no. Installing a different WebView without root and making it work, itself would be huge vulnerability in the system.  Iirc, there's discussion about this on chromium WebView pages
