### ISSUE TITLE
1Password doesn't get website info from Bromite

### ISSUE THREAD

**Issue by BaronZemo** [bromite/bromite#2065]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

101.0.4951.53

### Device architecture

arm64

### Android version

12

### Device model

Pixel 5a

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

In most browsers, using the 1Password Autofill feature will have the information on the current website to assist with autofill. For instance, if I'm on a google login page and bring up the keyboard and hit the "Autofill with 1Password" button appearing above the keyboard, I get the 1Password prompt that states "Select the account that you want to use with google.com". It will then show 1 or more usernames that I can select to autofill my password. Within Bromite, however, I get "Select the account that you want to use with Bromite." I do not have the logins listed that are associated with the particular website I am on. 

### Steps to reproduce the bug

1. Install 1Password
2. In Settings -> Autofill, ensure that Autofill and Accessibility are checked. This will prompt you for system wide permissions for both of these services.
3. In Bromite, go to bark.us/login
4. Tap in Email or Password fields. 
5. Keyboard should appear with "Autofill with 1Password" button appearing above keyboard.
6. Tap on the 1Password button, using fingerprint or pin authentication if necessary.
7. You will get the prompt "Select the account that you want to use with Bromite."

Repeat steps 3 through 6 for Chrome, Firefox, or Brave.
You will get the prompt "Select the account that you want to use with bark.us."

### Expected behavior

I should get the prompt 
"Select the account that you want to use with bark.us." with my bark username/email appearing as an option.

### Screenshots

The screenshots do not grab the 1Password prompt.

**Comment by uazo** [comment]
I'm sorry, but from what I understand 1password is not available as an opensource application, so I can't verify it.
the possible alternative is to have some technical indication directly from 1password team to compare with, you can try this way.

**Comment by csagan5** [comment]
Support was asked on their forums here: https://1password.community/discussion/114142/support-for-chromium-browser

> 5\. Keyboard should appear with "Autofill with 1Password" button appearing above keyboard.

It could be a 1Password bug then?

If you find out where the bug is in Bromite please comment on this issue so that it can be re-opened or submit a new one.
