### ISSUE TITLE
blocking of European Union cookie consent messages

### ISSUE THREAD

**Issue by maxi831** [bromite/bromite#2068]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

There is a website which is appropriately named "i don't care about cookies" (https://www.i-dont-care-about-cookies.eu/) which also offers a regularly updated filter list, that can be used with an adblocker. The URL for the adblock filter list is: https://www.i-dont-care-about-cookies.eu/abp/

### Describe the solution you would like

A way to add a **second** adblock filter list in Bromite, for example.

### Describe alternatives you have considered

Since you can set only one filter list in Bromite, the only solution I can think of is running my own server that combines the regular adblock filter list with the "i don't care about cookies" filter list and then enter that URL into the app. This of course would be a very cumbersome solution. Personally these obtrusive cookie consent messages have become very annoying to me, just like ads before adblocker and I do waste considerable time when browsing the internet on my phone because of them. Regardless of my european issue, I just wanted to say, because I don't know where else to, that I love your app, it's great, it's the only browser I use on my phone and I am very thankful for the developers behind it.

**Comment by Disqu3-mirOir-qt** [comment]
i don,t care about cookies not good solution because some website if block consent system not work , the best solution is to manipulate the js on the frontend

**Comment by AzureB1te** [comment]
Good news! Bromite already supports IDAC. You'll need to enable userscript support, then install [this script](https://github.com/xarantolus/bromite-userscripts/releases/latest/download/cosmetic.user.js)

**Comment by csagan5** [comment]
I think this is not possible without cosmetic filtering, which is not supported by the [Bromite/Chromium adblock engine](https://github.com/bromite/bromite/wiki/AdBlocking)

**Comment by hxd2772** [comment]
I am thinking about making my own unified adblock hosts and i dont care about cookies filter will be added along with many others but you can convert filter lists to bromite compatible ones using ruleset-converter.
