### ISSUE TITLE
Downloading page (as mhtml) not working.

### ISSUE THREAD

**Issue by bat999** [bromite/bromite#2076]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

101.0.4951.69

### Device architecture

arm

### Android version

8.1

### Device model

Xiaomi Redmi Go

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

Downloading page (as mhtml) not working.

### Steps to reproduce the bug

Visit a website...
www.bromite.org
Download the page.
Message says Downloading file...
But it doesn't complete.

### Expected behavior

With Chromium the message says Downloading file....
Then says File downloaded

PS
"Is this bug happening in an incognito tab?"
afaik It's not permitted to download pages in incognito mode.

**Comment by csagan5** [comment]
I cannot reproduce this.

**Comment by bat999** [comment]
Hi
I realize that mhtml download feature is not related to privacy or security.
 
Please will somebody look again at this problem.

The fault seemed to appear between
Bromite 100.0.4896.135
and
Bromite 101.0.4951.53

It's still not working for me with...
Bromite 104.0.5112.91

But it works OK with
Chromium 104.0.5112.91

**Comment by bat999** [comment]
Hi
Please will somebody look at this problem.

I've tested it again with clean installs.

Bromite 101.0.4951.39
Does work OK.

Bromite 101.0.4951.53
Does not work OK.

**Comment by csagan5** [comment]
> Bromite 101.0.4951.53
> Does not work OK.

This is not the latest version of Bromite.

Do you have any error in `adb logcat` related to this download operation?

**Comment by bat999** [comment]
> > Bromite 101.0.4951.53
> > Does not work OK.
> 
> This is not the latest version of Bromite.


> It's still not working for me with... Bromite 104.0.5112.91
> 
> But it works OK with Chromium 104.0.5112.91

Bromite 104.0.5112.91 is the latest version.

> 
> Do you have any error in `adb logcat` related to this download operation?

No

**Comment by bat999** [comment]
I suppose there must be a clash between recent Bromite builds and my Xiaomi's UI.
I have the choice...
Either
Bromite 101.0.4951.39
Or
Latest Chromium

Thanks for trying.
