### ISSUE TITLE
External Download Manager 

### ISSUE THREAD

**Issue by brnwlshubh** [bromite/bromite#2086]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

I don't know about such patch

### Describe the solution you would like

Please Add an option for External Download Files.
As sometimes the link expires for large size files then we have to re-download the file from starting.
After Adding this feature we can resume the file by adding new link from downloading agent.

### Describe alternatives you have considered

I've tried Firefox Repo Fennec.It contains this feature.

**Comment by brnwlshubh** [comment]
I'm aware of these issues #1675 #1400 #1203 #442 #147.
But it was closed due to template issue.
That's why I opened new issue #2086.
Please try to implement this feature ASAP.
Thanks in advance.

**Comment by csagan5** [comment]
How would this technically work? Is an intent necessary? In Fennec it seems to have been implemented here: https://github.com/mozilla-mobile/android-components/pull/7923

> Please try to implement this feature ASAP.

No such thing here, it may or may not be implemented and nobody can tell when.

**Comment by Poopooracoocoo** [comment]
How is this related to privacy by the way?

**Comment by csagan5** [comment]
I think it would require some big changes to the logic handling downloads; if someone wants to submit a patch I can consider it.

> How is this related to privacy by the way?

It is not.

**Comment by uazo** [comment]
> I think it would require some big changes to the logic handling downloads;

it doesn't seem like that to me, the kiwi code seems to have that function, it would be enough to retrieve it.
I'll think about it but unfortunately it is not now in my priorities, if there is anyone who wants to try I can help

**Comment by csagan5** [comment]
> it doesn't seem like that to me, the kiwi code seems to have that function, it would be enough to retrieve it.

Only if the license allows it; otherwise implementation must be done without copying any code.

> I'll think about it but unfortunately it is not now in my priorities, if there is anyone who wants to try I can help

Even if patch is submitted it can still be rejected if it is too invasive; also, it is not about privacy as I mentioned earlier.

**Comment by uazo** [comment]
> Only if the license allows it; otherwise implementation must be done without copying any code.

sure

> Even if patch is submitted it can still be rejected if it is too invasive; also, it is not about privacy as I mentioned earlier.

sure again!
