### ISSUE TITLE
Autoplay blocking is not working properly

### ISSUE THREAD

**Issue by Blaze-Thunder** [bromite/bromite#2096]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

102.0.5005.67

### Device architecture

arm64

### Android version

12.1

### Device model

OnePlus 7 pro

### Changed flags

chrome://flags/#bookmark-bottom-sheet
chrome://flags/#enable-tab-groups
chrome://flags/#move-top-toolbar-to-bottom
#bookmarks-improved-save-flow
#bookmarks-refresh
#export-bookmarks-use-saf

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

When opening webpages with autoplay of video, even though autoplay is set to blocked in site settings the video autoplays. But after a refresh of the webpage, video doesn't autoplay. Always on first load the video autoplays.

### Steps to reproduce the bug

1. Go to www.ndtv.com
2. Open any link with video available
3. The video on page autoplays with muted audio
4. Do a refresh. It doesn't autoplay now.

### Expected behavior

Video should not autoplay on the first load

**Comment by uazo** [comment]
thanks for the report, it is a behavior to investigate, because, unlike youtube where the page is not replaced (and therefore user activation persists between one navigation and the next), it seems to me that the behavior of that site is the loading of a new page.

**Comment by csagan5** [comment]
I confirm the bug when clicking on "Live TV".

**Comment by va-utils** [comment]
The same behavior can be observed on the website http://lenta.ru (version 103)

**Comment by csagan5** [comment]
Fixed in `103.0.5060.126`.
