### ISSUE TITLE
Anti-tracking javascript injection breaks translate quick answer

### ISSUE THREAD

**Issue by 0rlaf** [bromite/bromite#210]
Bromite version

Version: 71.0.3578.110
Arch: arm64
Android version: Pie

Is the bug reproducible with latest version?
- Yes

Can the bug be reproduced with corresponding Chromium version?
- No

Is the bug a crash?
- No

Describe the bug:

- In-page translator doesn't work.

<details><img src="https://i.ibb.co/wWTPfNY/IMG-20181230-120620.jpg"></details>

- Go to "www.google.com" and search "translate" 
- Try to translate something with in-page translator (not dedicated page) 
- Nothing happen and the text appeared overlapped 

Expected behavior
- Expected working translation and not overlapped text in first input textbox.

**Comment by csagan5** [comment]
Fixed in 71.0.3578.120
