### ISSUE TITLE
History threshold don't work

### ISSUE THREAD

**Issue by invman** [bromite/bromite#2104]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

102.0.5005.67

### Device architecture

arm

### Android version

10

### Device model

Galaxy J4

### Changed flags

move-top-toolbar-to-bottom

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No.

### Describe the bug

History don't get deleted after the specified interval on the "Expire history days threshold" setting, it just works if i change to "No history".

### Steps to reproduce the bug

1. Go to "Settings"
2. Enter in "Privacy and Security"
3. Change the "Expire history days threshold" interval

### Expected behavior

The navigation history should be deleted after the specified interval, but it doesn't.

**Comment by csagan5** [comment]
Fixed in `102.0.5005.96`.
