### ISSUE TITLE
Private DNS overrides DNS over HTTPS

### ISSUE THREAD

**Issue by arpitgupta** [bromite/bromite#211]
on Android Pie and I have setup private DNS to cloudfare DNS over tls url. On bromite I enabled DNS over HTTPS and set it to cloudfare. With this setup my connection to cloudfare remains over tls instead of HTTPS. I have tried disabling async DNS flag but that does not help.

I am not sure if this is expected behavior or not. Running 71.0.3578.110

**Comment by csagan5** [comment]
Try re-submitting the issue via desktop, there is an issue template to be filled in for issues and it does not show on mobile.
