### ISSUE TITLE
Yandex turbopages blocking

### ISSUE THREAD

**Issue by va-utils** [bromite/bromite#2112]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

Brave?

### Describe the solution you would like

Good afternoon. I would really like to be able to block "turbo pages" in Yandex search. Yandex replaces pages in search results for popular sites with its simplified pages. I would like to be able to navigate to the original pages.

### Describe alternatives you have considered

Brave Browser.

**Comment by csagan5** [comment]
This is something that should be done via [UserScripts](https://github.com/bromite/bromite/wiki/UserScripts).
