### ISSUE TITLE
Opening shortened links from another app in Bromite that resolve to URLs compatible with yet another app does not open the compatible app

### ISSUE THREAD

**Issue by radical6** [bromite/bromite#2117]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

102.0.5005.92

### Device architecture

arm64-v8a

### Android version

11

### Device model

Poco X3 Pro (M2102J20SG)

### Changed flags

enable-tab-groups

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No.

### Describe the bug

Opening a link displayed on another app in Bromite, which redirects to a URL compatible with another app, will not open the second app when clicking the corresponding app in the following Open with app dialogue. Example: 

1.  Clicking on a link to a Twitch stream on a twitter app will display an Open with app prompt, with Bromite and Chrome as the options.
2. If I select Bromite in the prompt displayed at the end of (1), Bromite will open with the address bar displaying _t.co/..._ in the URL, then another Open with app prompt will be displayed with Twitch as one of the options (as the URL is now compatible with it)
3. If I select Twitch in the prompt displayed at the end of (2), nothing happens. But if I had selected Chrome at the end of (1) instead, then Twitch will open if I select it at the end of (2).

### Steps to reproduce the bug

1. Use an app that has a native link shortener (e.g. Twitter with t.co/ links)
2. Click a link whose resolved URL is compatible with a different app (e.g. Twitch links in a tweet)
3. Open the link with Bromite app

### Expected behavior

The app compatible with the links should be able to open with the link whose URL is resolved within the Bromite app.

**Comment by csagan5** [comment]
I think this is disabled because it requires Play Store integrations.

**Comment by csagan5** [comment]
Bromite will disable all URL-to-app navigations, see #2205, so whatever support is currently present will be dropped.
