### ISSUE TITLE
Bromite is freezing.

### ISSUE THREAD

**Issue by GithubUser4778** [bromite/bromite#2124]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

102.0.5005.92

### Device architecture

arm64-v8a

### Android version

11

### Device model

redmi note 8

### Changed flags

No flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

Bromite is extremely lagging while using user scripts recommended by filtrie. When adding an high domains included filterlists instead of default. It causing to freeze the browser too long or just wait too pong.

### Steps to reproduce the bug

1.go to setting
2.click on user scripts
3.add filters recommended by filtrie
4.restart the browser.
5. Start browsing......

### Expected behavior

Smooth and fast experience with user scripts.

**Comment by csagan5** [comment]
This is not a bug in Bromite and there is nothing Bromite can do to fix user scripts that take too many resources.
