### ISSUE TITLE
Allow user to add custom Search URL

### ISSUE THREAD

**Issue by hulluwagon** [bromite/bromite#2125]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

Let user add a search URL they like. Using with Incognito on by default it is impossible to add any search engine because those does not appear in search engine list.

```
Select Searh engine

( ) Google
( ) Duck
.....................
( ) Custom URL
___________________
```

1. Select Custom URL.
2. Input `https://localhost/query?searchfor=%s&raw=1`
3. Bromite should use that

### Describe alternatives you have considered

Use Mozilla Firefox

**Comment by csagan5** [comment]
> Using with Incognito on by default it is impossible to add any search engine because those does not appear in search engine list.

That is not true.

**Comment by csagan5** [comment]
See [my comment here](https://github.com/bromite/bromite/issues/2100#issuecomment-1146634918)
