### ISSUE TITLE
Swap search engine mid search

### ISSUE THREAD

**Issue by Gottarocket** [bromite/bromite#2129]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

I have whoogle running on my server and I have selected it as my search engine. Since I use it locally I use 192.168.x.x URL as the search engine URL. But when I go outside or if server is down or If I cant connect to server for any reason and whoogle isnt accessible then I will have manually type mojeek.com or any searx instances and search my query. I would like a secondary search engine ready so when first search engine has issue it can redirect to second one. I know this is too much but consider if google or duckduckgo goes down anytime we will have to manually type the URL or change search engine again until its resolved. Yes bookmarks will help me quickly access other search engine websites but a option like one mentioned above would be helpful. Selfhosting has more privacy benifit no matter how FLOSS  search engine we use. So this option would help those who have selfhosted instances.

### Describe alternatives you have considered

I can use domain name I have but my server can be connected externally using VPN so would have to do all those changes in order to use only domain URL in search engine. This can be helpful to others too so that we can swap search engine when typing query. There should  be drop down on the left hand like we have on our desktop using shortcut CTRL+K.

**Comment by csagan5** [comment]
You can put a proxy in front of your search engine and fallback when your main search engine fails; it is not the job of the browser to do this.
