### ISSUE TITLE
Many apps are crashing with the last Bromite Webview update

### ISSUE THREAD

**Issue by Asbesbopispa** [bromite/bromite#213]
I tried by choosing the classic Android one and it doesn't happen. 
I'm on LineageOS 15.1 (Android 8.1), LeEco Le Pro 3 rooted with Magisk.
Bromite Browser works normally. 
Let me know if there are logs I can attach there.

**Comment by nishanthkarthik** [comment]
`01-07 09:23:04.276 F/chromium(9238): [FATAL:aw_browser_terminator.cc(81)] Render process (9258)'s crash wasn't handled by all associated  webviews, triggering application crash.`

**Comment by meijkl** [comment]
Can confirm the issue (using Nexus 6p with AICP 14.0-beta/Pie).
Example: GMX Mail App, doesn't show mails (crashes on attempt) , only mail overview

**Comment by thanuj10** [comment]
For me the whole browser crashes upon opening. Reproducible on Chromium builds also.

**Comment by csagan5** [comment]
@Asbesbopispa please re-submit it by using the issue template; the issue template is not visible via mobile, you need to visit Github with a desktop user-agent or click on "Desktop version".

**Comment by csagan5** [comment]
Duplicate of #216
