### ISSUE TITLE
No proxy DNS when using SOCKS4/5

### ISSUE THREAD

**Issue by 51522** [bromite/bromite#2134]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

If you use SOCKS-proxy, DNS requests go through it. I use DNSCrypt-proxy2 always and everywhere, even with TOR Browser, because I don't trust output nodes. I need to be able to switch DNS traffic to system when using proxy.

### Describe alternatives you have considered

No

**Comment by uazo** [comment]
have you tried disabling secure DNS or setting it as "Use your current service provider"?

**Comment by 51522** [comment]
Hello!
Secure DNS is off because I'm using DNSCrypt. Of course, i can enable this, but all dns requests will go around DNSCrypt and only one server will be used. This is not a privacy solution.

**Comment by uazo** [comment]
sorry I do not understand.
dnscrypt is a daemon that replaces the standard android dns client?

**Comment by 51522** [comment]
dnscrypt-proxy 2 - A flexible DNS proxy, with support for encrypted DNS protocols.

**Comment by uazo** [comment]
I understood that, but I wonder how you configured it, you didn't write it.
you should enable us to reproduce the issue.

**Comment by 51522** [comment]
On devices with root, requests are redirected from port 53 to port dnscrypt-proxy2 by iptables rules.
iptables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to-destination 127.0.0.1:5353
iptables -t nat -A OUTPUT -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1:5353

**Comment by 51522** [comment]
On non-rooted devices, I use the invisible pro program. The program uses a local VPN to redirect traffic.

**Comment by 51522** [comment]
Thank you for the clarification. I hope I find another way.

**Comment by csagan5** [comment]
> I looked at the code: what you ask is rather complicated because a new `NetworkSessionContext` without proxy should be created, which is not foreseen by chromium.
> So assuming that the code to be modified is [this](https://source.chromium.org/chromium/chromium/src/+/main:net/dns/dns_transaction.cc;l=1344;drc=1946212ac0100668f14eb9e2843bdd846e510a1e?q=MakeUdpAttempt&ss=chromium%2Fchromium%2Fsrc) we need to create a new one in order not to pass by [AddToNetworkContextParams](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/net/system_network_context_manager.cc;l=934;drc=043baafbe3cfbf96887b4f20e57be9f6286e7e39;bpv=1;bpt=1).

@uazo when using SOCKS proxies DNS lookups that go to the Android system will not go through the SOCKS proxy, is this the issue?

**Comment by uazo** [comment]
> using SOCKS proxies DNS lookups that go to the Android system will not go through the SOCKS proxy

no, also the dns requests goes through the proxy. the request is to bypass the proxy

**Comment by csagan5** [comment]
Then it is working as intended. For any special use you can always make your own proxy and run it on the phone.
