### ISSUE TITLE
Add feature to set custom search engine to a self-hosted search

### ISSUE THREAD

**Issue by jahway603** [bromite/bromite#2139]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

Not that I'm aware of

### Describe the solution you would like

When choosing a search engine, I would like the option to set a custom search engine to a self-hosted one, such as SearX or YaCy (as examples).

### Describe alternatives you have considered

No alternatives available as I believe this feature would require changes to the app's code. This feature might also not be possible with the Bromite codebase, but I'm uncertain which is why I'm filing this feature request.

**Comment by michitux** [comment]
Have you tried visiting the search engine you want to add, searching for something and then opening the search engine settings? There should be a section below the built-in search engines that lists recently visited search engines. For me this worked on searx.be, I couldn't find a public YaCy instance to test.

**Comment by csagan5** [comment]
See https://github.com/bromite/bromite/wiki/SearchEngines
