### ISSUE TITLE
PWAs selectively work. Either there is a bug or the F.A.Q needs updating

### ISSUE THREAD

**Issue by UttermostUsername** [bromite/bromite#2143]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

102.0.5005.96

### Device architecture

arm

### Android version

12.0

### Device model

Google Pixel

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

1. No

### Describe the bug

PWAs work for some sites and not others. I am aware of #498 however the F.A.Q indicates that no PWA should work. This is not the case. Two examples of working PWA's are outlook and simplelogin. An example of a non-working PWA is google maps.

### Steps to reproduce the bug

Use the install to home screen feature on the prior indicated websites.

### Expected behavior

The F.A.Q should be updated to indicate that only google PWA don't work instead of "PWAs are only supported as home shortcuts; WebAPKs will not work because they are generated server-side on googleapis.com (which is not allowed in Bromite)."

I'm also not sure why googleapis.com is blocked in bromite with no clear toggle off. The behavior of blocking googleapis.com should have a toggle and I don't see where it is indicated that the behavior exists. If there isn't a place where this behavior is indicated it should be.

Additionally confusing is that under "Does Bromite support DRM media?" It says "This means for example that requests to Android license servers will be performed (www.googleapis.com)" which seems to indicate that googleapis.com is not actually blocked. So which is it and why are PWA from google broken?

**Comment by csagan5** [comment]
> PWAs work for some sites and not others. I am aware of #498 however the F.A.Q indicates that no PWA should work. This is not the case. Two examples of working PWA's are outlook and simplelogin.

The F.A.Q. does not say that no PWA should work, it says that WebAPKs do not work. Are those two examples WebAPKs?

> Two examples of working PWA's are outlook and simplelogin. An example of a non-working PWA is google maps.

Can you provide all these PWAs URLs?

> I'm also not sure why googleapis.com is blocked in bromite with no clear toggle off. The behavior of blocking googleapis.com should have a toggle and I don't see where it is indicated that the behavior exists. If there isn't a place where this behavior is indicated it should be.

Nothing will be changed in Bromite because you say or think so; we can have a discussion and then figure out whether there is something to improve or not. Since you say "I'm also not sure why googleapis.com is blocked in bromite" perhaps we should start from that before talking about changes?

> Additionally confusing is that under "Does Bromite support DRM media?" It says "This means for example that requests to Android license servers will be performed ([www.googleapis.com](http://www.googleapis.com))" which seems to indicate that googleapis.com is not actually blocked.

`googleapis.com` (and other URLs widely used within Chromium) is blocked for all the internal networking, except for DRM.

> why are PWA from google broken?

First let's see the answers to previous questions.

**Comment by UttermostUsername** [comment]
> The F.A.Q. does not say that no PWA should work, it says that WebAPKs do not work. Are those two examples WebAPKs?

I do not know what the difference is between PWAs and WebAPKs. Here is screenshot of what I assume is simplelogin's PWA/WebAPK. If there is a difference why is WebAPK listed under PWA in the F.A.Q?

> Can you provide all these PWAs URLs?

Simplelogin: `app.simplelogin.io/auth/login`
Outlook: I didn't realize this but the PWA doesn't work until you are signed in. This is probably a bad example, appologies. The link is `outlook.office.com`
Google maps: `www.google.com/maps`

What outlook and simplelogin look like on the home screen
![Screenshot_20220619-135851](https://user-images.githubusercontent.com/91044478/174498458-18754748-a7d2-4164-8fa9-bda45425c5ed.png)

What google maps looks like on the home screen
![Screenshot_20220619-135848](https://user-images.githubusercontent.com/91044478/174498457-614aec90-ace2-4c3c-b9f0-1f983ce6d2cc.png)

What simplelogin looks like when opened. Note that it isn't opened in the browser, but rather as its own app. This is different from google maps which opens in the browser when selected from the home screen.
![Screenshot_20220619-135254](https://user-images.githubusercontent.com/91044478/174498456-c38b0fcd-9647-45ef-84b4-d15a9dec72be.png)

> Nothing will be changed in Bromite because you say or think so; we can have a discussion and then figure out whether there is something to improve or not. Since you say "I'm also not sure why googleapis.com is blocked in bromite" perhaps we should start from that before talking about changes?

I have questions on the following: Does bromite take it upon itself to block trackers? Does the adblocking list not have the capability to do this? My understanding was that chromium has google urls in it by default, and bromite removes those urls from the app. Is that why googleapis.com is blocked? I thought this process just removed any google url connections that cause app telemetry regardless of where the actual user is browsing.
 
> `googleapis.com` (and other URLs widely used within Chromium) is blocked for all the internal networking, except for DRM.

So if an exception is made for specific situations is this situation not a valid exception?

**Comment by csagan5** [comment]
> > The F.A.Q. does not say that no PWA should work, it says that WebAPKs do not work. Are those two examples WebAPKs?
> 
> I do not know what the difference is between PWAs and WebAPKs. Here is screenshot of what I assume is simplelogin's PWA/WebAPK.

You can search online what is a WebAPK using your favorite search engine.

> If there is a difference why is WebAPK listed under PWA in the F.A.Q?

Because they are related; after you search online you might find this page that explains how they are related: https://web.dev/webapks/

This functionality is blocked in Bromite because it would use Google's servers; it would also pass a key as you can see in https://github.com/bromite/bromite/issues/498#issuecomment-596057866

I am not an expert of PWAs/WebAPKs but they are not part of the open web, not at least in the way they are implemented in Chromium since they require an intermediate server to generate an APK.



> > Can you provide all these PWAs URLs?
> 
> Simplelogin: `app.simplelogin.io/auth/login` Outlook: I didn't realize this but the PWA doesn't work until you are signed in. This is probably a bad example, appologies. The link is `outlook.office.com` Google maps: `www.google.com/maps`

Did you test these with [Chromium](https://www.bromite.org/chromium)?



> I have questions on the following: Does bromite take it upon itself to block trackers? Does the adblocking list not have the capability to do this? My understanding was that chromium has google urls in it by default, and bromite removes those urls from the app. Is that why googleapis.com is blocked? I thought this process just removed any google url connections that cause app telemetry regardless of where the actual user is browsing.

It is blocked because it is used internally in Chromium without any user interaction, it is explained on that article as well: https://web.dev/webapks/

This is unrelated to adblocking and user navigation.

**Comment by UttermostUsername** [comment]
> > > The F.A.Q. does not say that no PWA should work, it says that WebAPKs do not work. Are those two examples WebAPKs?
> > 
> > 
> > I do not know what the difference is between PWAs and WebAPKs. Here is screenshot of what I assume is simplelogin's PWA/WebAPK.
> 
> You can search online what is a WebAPK using your favorite search engine.

I did. According to [this](https://www.inovex.de/de/blog/progressive-web-apps-vs-webapks/) site a WebAPK shows an installation screen like a normal web app. Installing the PWA from google maps does not. This makes me believe the PWA from google maps is not a "WebAPK"

> > If there is a difference why is WebAPK listed under PWA in the F.A.Q?
> 
> Because they are related; after you search online you might find this page that explains how they are related: https://web.dev/webapks/

That reasoning makes sense.

Seperate to that issue: That site is another example that makes me believe that the google maps PWA is not a webAPK. When installed with, say brave, there is no installation screen, no app "in Android's app settings", and it functions the same as simplelogin's PWA. The only difference is that on bromite the google maps PWA doesn't get added to home-screen, instead a shortcut is.
 
> This functionality is blocked in Bromite because it would use Google's servers; it would also pass a key as you can see in [#498 (comment)](https://github.com/bromite/bromite/issues/498#issuecomment-596057866)

So why does google maps load at all? That requires using Google's servers. Is there a list of IP's that bromite blocks? What is the reasoning behind there not being a toggle for blocking what I'm assuming is interpreted as trackers?

> I am not an expert of PWAs/WebAPKs but they are not part of the open web, not at least in the way they are implemented in Chromium since they require an intermediate server to generate an APK.

If every server can implement its own PWA why is that not an open web thing? That doesn't give Google some kind of proprietary power.

> > > Can you provide all these PWAs URLs?
> > 
> > 
> > Simplelogin: `app.simplelogin.io/auth/login` Outlook: I didn't realize this but the PWA doesn't work until you are signed in. This is probably a bad example, apologies. The link is `outlook.office.com` Google maps: `www.google.com/maps`
> 
> Did you test these with [Chromium](https://www.bromite.org/chromium)?

I have done that now and the bug from bromite replicates in that version of chromium. If the question in the bug template "Can the bug be reproduced with corresponding Chromium version?" means to use that particular chromium app, then I apologize. I thought it meant any app that is using chromium as a base.

I tested it with Brave which "Upgraded to Chromium 102" where the google maps PWA is installed exactly the same was as the simplelogin PWA. On Brave there is no "similar install screen as shown below (2)" as indicated at https://www.inovex.de/de/blog/progressive-web-apps-vs-webapks/. There is also no corresponding settings for the installed google maps PWA (also just like simplelogin's PWA).

> > I have questions on the following: Does bromite take it upon itself to block trackers? Does the adblocking list not have the capability to do this? My understanding was that chromium has google urls in it by default, and bromite removes those urls from the app. Is that why googleapis.com is blocked? I thought this process just removed any google url connections that cause app telemetry regardless of where the actual user is browsing.
> 
> It is blocked because it is used internally in Chromium without any user interaction, it is explained on that article as well: https://web.dev/webapks/

What is considered "internally ... without any user interaction"? Is it only google services which fall under this label?

> This is unrelated to adblocking and user navigation.

Does adblocking in bromite exist solely to remove visual ads or does it also exist to block data collection of websites using filter lists? Ublock, for example, blocks trackers and ads regardless of if the tracker is a visible ad.

**Comment by csagan5** [comment]
> > Did you test these with [Chromium](https://www.bromite.org/chromium)?
> 
> I have done that now and the bug from bromite replicates in that version of chromium. If the question in the bug template "Can the bug be reproduced with corresponding Chromium version?" means to use that particular chromium app, then I apologize. I thought it meant any app that is using chromium as a base.

Yes, it means that, it is explained there when you submit the issue. Since the bug replicates then you need to report it upstream (also explained in the template when submitting the issue).
