### ISSUE TITLE
An option to disable Sharing hub

### ISSUE THREAD

**Issue by Manifoldme** [bromite/bromite#2146]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

No

### Is there a patch available for this feature somewhere?

no, since last update doesn't work anymore

### Describe the solution you would like

an on/off switch 

### Describe alternatives you have considered

Any implementation/solution to get rid of the Sharing hub would be greatly appreciated.

**Comment by csagan5** [comment]
Can you provide a screenshot of this sharing hub in Bromite?

**Comment by Manifoldme** [comment]
I tried to attach the screenshot, unfortunately unsuccesful, if you don't mind I uploaded a link to my Dropbox with the screenhot.
https://www.dropbox.com/s/9m57eyqoio4vyr4/Bromite_Hub.jpg?dl=0

The issue with the a new Sharing hub is that it is not able to copy any word alone but the entire link attached to it, so a dictionary, for instance, is rendered usless.

**Comment by csagan5** [comment]
![LKnfe6qg](https://user-images.githubusercontent.com/32685696/174883805-33eb0aeb-491d-4d8f-821c-157d3d528eec.jpeg)

How do you make this hub appear?

**Comment by Manifoldme** [comment]
By marking a word and pushing a share button afterwards.

**Comment by csagan5** [comment]
> Any implementation/solution to get rid of the Sharing hub would be greatly appreciated.

Why should this sharing hub be disabled? If the user does not use it, it does not do anything by itself; or is there something I am missing?

**Comment by krisu5** [comment]
> > Any implementation/solution to get rid of the Sharing hub would be greatly appreciated.
> 
> Why should this sharing hub be disabled? If the user does not use it, it does not do anything by itself; or is there something I am missing?

I wish it was possible to disable at least in flags page.

Reason why is that it doesn't give me anything actually useful (I never even use screenshot options) and it only gives you most used share options that you used with Chromium, otherwise you have to tap "more" button, which I would likely do anyways because of habit.

**Comment by Manifoldme** [comment]
> 
> Why should this sharing hub be disabled? If the user does not use it, it does not do anything by itself; or is there something I am missing?

It's about options, dude. There are people out there who need that option.
Your rational though is 100% correct if a user doesn't use nothing including a SharingHub or even better a digital device then there is no issue with the digital device consequently with SharingHub.
Thanks for helping out to find a solution.
The solution for now is Brave, Privacy-Browser and all Firefox based browsers.

**Comment by krisu5** [comment]
> > Why should this sharing hub be disabled? If the user does not use it, it does not do anything by itself; or is there something I am missing?
> 
> It's about options, dude. There are people out there who need that option. Your rational though is 100% correct if a user doesn't use nothing including a SharingHub or even better a digital device then there is no issue with the digital device consequently with SharingHub. Thanks for helping out to find a solution. The solution for now is Brave, Privacy-Browser and all Firefox based browsers.

No need to be so hostile, he just wants opinions.

**Comment by Manifoldme** [comment]
> 
Don't you see? He is mocking me/us, just take a glimpse at our conversation, he already have all the info he needs including screenshots with examples to the questions “Why?”  I uploaded to the cloud and made them accessible for him, he still asking questions I already answered in excess.

**Comment by uazo** [comment]
I'm sorry but you are a bit exaggerated. 
these seem to me to be more than legitimate questions considering that it is necessary to understand the motivations before spending (free) time for a development that, among other things, you do for others.

**Comment by Manifoldme** [comment]
> I'm sorry but you are a bit exaggerated. these seem to me to be more than legitimate questions considering that it is necessary to understand the motivations before spending (free) time for a development that, among other things, you do for others.

Browser developer who asks how to make SharingHub to appear… ROFL
I’m sorry but he is not even an average user, let alone a developer.
I hoped that some developer will eventually take over, but 22 days later, the same guy appears again
asking the same questions that would be appropriate for an eighty year’s old guy without any idea that a browser is not a TV show.
All it tells me, that actual Bromide developers do not interested in any kind of discussion hence some elderly dude without technical understanding helping out to filter issues and requests.

**Comment by csagan5** [comment]
I am closing this; not because of the despicable comments but because there is no plan to disable the sharing hub. It's there, it does not hurt privacy, changing it has nothing to do with Bromite's mission.
