### ISSUE TITLE
Incognito icon remains in notification area after exiting

### ISSUE THREAD

**Issue by jrjordao** [bromite/bromite#215]
**Bromite version**
Version: 71.0.3578.120 (and previous versions)
Arch: arm
Android version: 6.0.1

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
N/A (Chromium does not have Exit action, right?)

**Is the bug a crash?**
No

**Describe the bug**
When using incognito, after exit'ing the incognito icon remains in the notification area.

**To Reproduce**
1. Open incognito tab (incognito icon appears in the notification area)
2. Exit
3. Incognito icon remains

**Expected behavior**
After exit, the incognito icon should disappear.

**Comment by thanuj10** [comment]
It is the intended behavior of all chromium/blink based browsers to remind you of the incognito tabs. Incognito mode icon remains in the notification panel until you tap it to close tabs

**Comment by csagan5** [comment]
@jrjordao it is working as intended; Android apps do not really exit like software on a desktop computer

**Comment by jrjordao** [comment]
@csagan5 
Sure, but if the Exit action closes all incognito (and regular) tabs and I have the "close tabs on exit" option selected, why keep the incognito tab notification in that case? There are effectively no incognito tabs left running / to close.
