### ISSUE TITLE
SOCKS5 proxy command line configuration not working

### ISSUE THREAD

**Issue by miquecg** [bromite/bromite#2159]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

102.0.5005.96

### Device architecture

arm64

### Android version

11

### Device model

OnePlust 5T

### Changed flags

enable-command-line-on-non-rooted-devices

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

I've noticed a problem with latest Bromite version 102.0.5005.96 on Android. I have a SOCKS5 proxy configured long time ago using a `chrome-command-line` file located in `/data/local`.

`_ --proxy-server="socks5://proxy-server.com" --host-resolver-rules="MAP * ~NOTFOUND , EXCLUDE proxy-server.com"`

It worked like a charm until now. Required `Enable command line on non-rooted devices` flag is enabled.

Downgrading to 102.0.5005.92 version fixes the problem.

Chromium 102.0.5005.96 does not exhibit this behaviour.

### Steps to reproduce the bug

1. Open browser
2. Type any url on the address bar
3. Connection does not happen

### Expected behavior

Being able to browse using a SOCKS5 proxy as before.

**Comment by uazo** [comment]
there seems to be an upstream bug, try with:

```
echo --a=1 --proxy-server="socks5://proxy-server.com" --host-resolver-rules="MAP * ~NOTFOUND , EXCLUDE proxy-server.com" \ 
    > /data/local/chrome-command-line
```
the bug is: the first parameter is not taken into account ("--a = 1")

**Comment by miquecg** [comment]
Yep, it seems. That trick fixes the issue.

Maybe the `_` in front of my example is not being handled properly.

**Comment by csagan5** [comment]
I will close this as it appears to not be a bug.

**Comment by miquecg** [comment]
Yes, it's not a bug. I somehow got tricked because when applied the suggested fix the resulting parameters where unquoted (they must be escaped), so I ended up using a different outgoing server, which at that time worked, making me think the problem was on the arguments parsing.

Problem was indeed on the proxy server not being functional.

Just for the sake of reference:

> For production build on a non-rooted device, you need to enable "Enable command line on non-rooted devices" in chrome://flags, then set command line in /data/local/tmp/chrome-command-line. When doing that, mind that the first command line item should be a "_" (underscore) followed by the ones you actually need. Finally, manually restart Chrome ("Relaunch" from chrome://flags page might no be enough to trigger reading this file).

https://www.chromium.org/developers/how-tos/run-chromium-with-flags/#android
