### ISSUE TITLE
Website login menu not loading

### ISSUE THREAD

**Issue by rjames94** [bromite/bromite#2169]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

102.0.5005.96

### Device architecture

arm64-v8a

### Android version

11

### Device model

OnePlus 7 Pro

### Changed flags

No flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No.

### Describe the bug

Visiting www.bovada.lv and clicking on login button at the top right fails to load login menu. Nothing happens when the button is pressed.

### Steps to reproduce the bug

1. Navigate to www.bovada.lv
2. Press login button at top right of web page

### Expected behavior

A floating login menu/screen should pop up asking for username and password

**Comment by Provider-1** [comment]
Something's wrong with their fingerprint module (canvas fingerprint?).
I would say it's intentional on their part as no browser that prevents fingerprinting seems to work properly.

**Comment by csagan5** [comment]
I cannot reproduce this issue, they are trying to use a cross-origin frame so Bromite blocks it; we will not change Bromite to allow this.
