### ISSUE TITLE
Icon for opening incognito window

### ISSUE THREAD

**Issue by jrjordao** [bromite/bromite#217]
**Is your feature request related to privacy?**
Yes

**Is there a patch available for this feature somewhere?**
No

**Describe the solution you'd like**
Have a way to start Bromite in incognito mode, via a second icon created upon installation.

**Describe alternatives you've considered**
Add config option for running incognito when starting manually (from icon). In other words, keep the existing option for "incognito when opening links" and add a new option for "incognito when starting manually".

**Comment by jrjordao** [comment]
Explaining my use case a bit better (hopefully)...

The links I receive in email messages, like the GitHub notifications, usually are to be open in regular mode, so that I don't need to login everytime in the target website. So, I keep the "Open links in incognito tabs always" option off.

However, when manually starting Bromite for web navigating, I most often use incognito mode. So, it would be great to have a way to start directly in incognito mode, instead of having to start with regular window and from it launch the incognito window.

Hope I made myself clear.

Thanks for your great work.

**Comment by ouzowtf** [comment]
There is a shortcut for a new tab and a new incognito tab which you could set as app icon on the homescreen of your launcher, if you use Android 8 ( I think) or newer.

**Comment by csagan5** [comment]
@jrjordao long-tap the Bromite icon and create a shortcut launcher for the incognito mode to launch the app.
