### ISSUE TITLE
Password menu in setting does not open

### ISSUE THREAD

**Issue by Bantul-the-great** [bromite/bromite#2188]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

103.0.5060.121

### Device architecture

arm64-v8a

### Android version

10

### Device model

Redmi Note 7s

### Changed flags

No

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No.

### Describe the bug

When I go into "**SETTING**" of BROMITE and tap the "**PASSWORD**" menu , it does not open... It just does nothing... I've cleared the data of the app and tried again but it does not open at all.. It is not reproducible in the "CHROMIUM" contemporary...

### Steps to reproduce the bug

1. Open BROMITE
2. Open SETTINGS
3. Tap on PASSWORD menu
4. It does not do anything.

### Expected behavior

It should have shown the sub menus under PASSWORD menu, such as- SAVE PASSWORDS, AUTO SIGN-IN, etc.....

**Comment by csagan5** [comment]
Fixed in `103.0.5060.126`.
