### ISSUE TITLE
Problem with text in adressbar

### ISSUE THREAD

**Issue by va-utils** [bromite/bromite#2196]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

103.0.5060.121

### Device architecture

armeabi-v7a

### Android version

12.0

### Device model

Samsung A51

### Changed flags

No flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

I can't highlight the text in the address bar, the text (url) is not visible

### Steps to reproduce the bug

click on the address bar with the text

### Expected behavior

see the text and be able to highlight

### Screenshots

![Screenshot_20220714-182329_Bromite](https://user-images.githubusercontent.com/16035531/179018459-cd32ddc2-72e6-4649-beef-b71d2e4fc2f8.jpg)

**Comment by uazo** [comment]
tested with a real A51 in browserstack (but A10), it is not possible to reproduce it.

![image](https://user-images.githubusercontent.com/29201891/179021360-551020a3-e8d5-49c0-93b5-1634c69d13fb.png)

happens to you only with the toolbar moved below?
do you have a non-standard keyboard? if so, can you try to change it?

**Comment by va-utils** [comment]
I have it only from the bottom. I tried the standard keyboard, it's the same with it

**Comment by uazo** [comment]
I'm sorry, there is little I can do unless you help us narrow down the possibilities.
the first thing that comes to mind is that the bar is hidden from the keyboard since opening the keyboard causes the resize of the view (which, however, seems to be received, from your image the other elements move up).
For example, try to rotate the device with the keyboard open, for now I can't think of anything else.

**Comment by openwick** [comment]
I have the same issue too. Unable to edit a url or copy it from the url bar. Option is not coming like in chrome pr Brave.

 PS: Bitwarden auto fill is also not working properly. Only username is getting filled many times only in bromite. Should I create another bug report?

**Comment by csagan5** [comment]
@va-utils please report back the results of testing that @uazo asked, otherwise we cannot do anything because issue is not reproducible.

@openwick here we discuss only the address bar problem, if you can reproduce it please give instructions; for the other issue you need to open a separate one.
