### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by besweeet** [bromite/bromite#22]
Samsung's internet browser for Android recently added a dark mode feature and it works quite well. Is it possible to add something similar?

**Comment by csagan5** [comment]
I am sorry, this has been discussed already, the feature of dark mode has nothing to do with privacy enhancements/security/adblocking which are the goals of Bromite.

I believe Chromium developers are adding similar features too.

**Comment by besweeet** [comment]
Where was it discussed before? Just curious, as I can search there first before making a post here.

**Comment by csagan5** [comment]
No worries, mostly on the XDA thread: https://forum.xda-developers.com/search/thread/3687258?query=dark

**Comment by LCichanowiczPMG** [comment]
@csagan5, that is a very disappointing position to take.  Dark mode has a great impact on usability.  Operating systems now provide dark modes, and enable applications to honor the OS setting.

https://stuffandnonsense.co.uk/blog/redesigning-your-product-and-website-for-dark-mode
