### ISSUE TITLE
Erase all persisted site data storaged in "user data" when I close all windows.

### ISSUE THREAD

**Issue by vrsovin** [bromite/bromite#2200]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

no

### Describe the solution you would like

When we navigate in a lot of sites, they persist data in "user data", that can be view in Android Settings --> Apps & Notifications --> Bromite --> Storage & Cache --> User data. The only path that I found to erase this data without reset app is opening Bromite privacy settings and using Clear Browsing Data. The chromium for desktop (PC) have an option to erase all data on quit, called "Clear cookies and site data when you close all windows". So, I want to suggest you to bring this option to Bromite. It happens in incognito only mode and normal mode.

### Describe alternatives you have considered

Erasing all app data or clearing data in privacy settings, but it is boring.

**Comment by csagan5** [comment]
> So, I want to suggest you to bring this option to Bromite. It happens in incognito only mode and normal mode.

In incognito mode the data is already erased.

If you want all data to be removed on exit you should use always-incognito mode or set the history to 0.
