### ISSUE TITLE
Grey Icon and error installing & updating  from F-droid.

### ISSUE THREAD

**Issue by Techguyprivate** [bromite/bromite#222]
**Bromite version**

Version: `71.0.3578.115...`
Arch: `arm` or `arm64` 
Android version: Oreo

**Is the bug reproducible with latest version?

Yes.

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**

Not in chromium, but for installing chromium too.  yes.

Is the bug a crash?

No.

**Describe the bug**

From the last two week, bromite , vanilla chromium & system webview are showing error when trying to upgrade or install from F-droid. The icons are grey when browsing in F-droid too for both Bromite , chromium, system webview. 

**To Reproduce**
1. Go to f-droid
2. Click on Search
3. Try to install any bromite products like Bromite browser, System webview, or Vanilla Chromium.
5. Clicking on install or update button 10 times too, doesn't work. 

Huge sorry for the Large pic &  quality of the gif .

![screenshot_2019-01-10-20-36-21-54](https://user-images.githubusercontent.com/43615747/50977718-cdd98c00-14ea-11e9-8f20-a7d9b14d5ec5.png)
![screenshot_2019-01-10-20-35-56-83](https://user-images.githubusercontent.com/43615747/50977720-cdd98c00-14ea-11e9-8e97-84a761c20062.png)
![screenshot_2019-01-10-20-35-34-13](https://user-images.githubusercontent.com/43615747/50977721-ce722280-14ea-11e9-86ec-f78ff4a00c8b.png)
![screenshot_2019-01-10-20-35-22-15](https://user-images.githubusercontent.com/43615747/50977722-ce722280-14ea-11e9-85b8-b6a65b0ae82a.png)
![screenshot_2018-12-31-12-08-50-46](https://user-images.githubusercontent.com/43615747/50977723-cf0ab900-14ea-11e9-97ec-2577b4408ba7.png)
![screenshot_2018-12-31-12-08-28-24](https://user-images.githubusercontent.com/43615747/50977724-cf0ab900-14ea-11e9-971c-4ea97fa16b45.png)

![record_20190110203949 7](https://user-images.githubusercontent.com/43615747/50979682-ee0b4a00-14ee-11e9-8188-5c4c4f8ed9b3.gif)

**Expected behavior**
Should upgrade or install.

**Screenshots**

**Comment by Techguyprivate** [comment]
Youtbe link explaining the bug cause the gif is not good. 

Watch in 2xxx speed. 

https://www.youtube.com/watch?v=BnCwbDA_nWc

**Comment by csagan5** [comment]
@Techguyprivate there is a news section (with an RSS feed) on the official website: https://www.bromite.org/#news

https://www.bromite.org/news/2018-12-21-new-fdroid-repository-url

**Comment by Techguyprivate** [comment]
Solved. Problem occuring from last 6 months actually . Thank you.
