### ISSUE TITLE
Cannot Install BromiteWebView on latest stock android 9 version

### ISSUE THREAD

**Issue by bdashore3** [bromite/bromite#223]
**Bromite version**

Version: `71.x`
Arch: arm64
Android version: Pie

**Describe the bug**
I've installed Bromite webview using the instructions on the wiki, nanodroid, and as a user app, but it doesn't work and causes it not to pop up in developer options

**To Reproduce**
1. Install Bromite either as a system app or user app (tried via WebViewStub or just plain old Webview folder)
2. Reboot device
3. Doesn't show up

**Expected behavior**
I expected Bromite to show up in the WebView options, but I only see Chrome and a disabled android webview

![br1](https://user-images.githubusercontent.com/8082010/51063064-46157f80-15c7-11e9-848f-2c4ab1928947.png)
![br2](https://user-images.githubusercontent.com/8082010/51063065-46ae1600-15c7-11e9-91cf-255197706c24.png)

**Comment by csagan5** [comment]
@bdashore3 this is not a bug of the Bromite SystemWebView, you might need support to make it work; I suggest asking on XDA or some other Android forums

**Comment by csagan5** [comment]
@bkb3 what procedure did you use to convert it to a system app? I am asking so we can improve the [wiki page](https://github.com/bromite/bromite/wiki/Installing-SystemWebView), used as a reference for users.

**Comment by bkb3** [comment]
@csagan5 I used [/system/app mover](https://f-droid.org/en/packages/de.j4velin.systemappmover/) app available on f-droid to convert to system app. After rebooting, I installed the app again on top of the system app. 
Here's the screen record of the process.
[![Bromite System Webview installation on Android Pie](https://imgoat.com/uploads/ecca5b6365/184874.gif)]

**Comment by csagan5** [comment]
@bkb3 that app requires root; I can list this procedure with the animation in the wiki page as an alternative, thanks!
