### ISSUE TITLE
One-click privacy

### ISSUE THREAD

**Issue by bege10** [bromite/bromite#224]
Version: `71.0.3578.123`
Arch: `arm` 
Android version: LineageOS for microG 2019/1/8

I'd like to have the option to clear all data with exit like Firefox for Android does. Each time to go to the settings is quite uncomfortable.

**Comment by csagan5** [comment]
You have an always-incognito mode and an option to close all tabs on exit; enabling both will give you your desired effect.

**Comment by bege10** [comment]
Not really: If I do what you recommend I don't have a history during the browsing session. That's what I need.
If clear all with exit is not possible a direct access to clearing all private data via menu (not via settings) would be helpful.
