### ISSUE TITLE
"More on Wikipedia" button using DuckDuckGo search engine does not redirect to Wikipedia-app

### ISSUE THREAD

**Issue by AxeldeWater** [bromite/bromite#2249]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

104.0.5112.63

### Device architecture

arm

### Android version

11

### Device model

Motorola moto g60s (XT2133-2)

### Changed flags

move-top-toolbar-to-bottom

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No.

### Describe the bug

When using DuckDuckGo as the default search engine, and searching for something, there is sometimes a wikipedia article about the topic you searched for. Sometimes that window shows a "Wikipedia" link/button:

![Screenshot_20220808-153302-127](https://user-images.githubusercontent.com/110288748/183430337-856e8422-d84c-4a82-8dfa-b71c0a0108d7.png)

For other articles though (could be language related), the button in this window says "More on Wikipedia":

![Screenshot_20220808-144053-451](https://user-images.githubusercontent.com/110288748/183427799-c8800b5c-827b-4c8d-94f5-7b17d0dc427a.png)

Clicking the "More on Wikipedia" link does NOT redirect to the Wikpedia app at all. Clicking the "Wikipedia" link sometimes works, sometimes doesn't. Instead it just opens the mobile browser page of that article. Doing this on Chromium, Google Chrome, Firefox and DuckDuckGo Browser works as expected and is not bugged.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Set DuckDuckGo as default search engine
2. Install the Wikipedia app from F-Droid (or any other way, just make sure you have the wikipedia app)
3. Search for "flatland" in Bromite
4. The Wikipedia infobox should now show up, with the link to Wikipedia. If it doesn't, refresh the page. 
5. Click on the link. It now should send you to the browser site instead of the Wikipedia app.

### Expected behavior

Clicking the button should redirect you to the app.

**Comment by AxeldeWater** [comment]
I think it sometimes even doesn't work for normal links.

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> No

With the same Chromium version this does not happen?

**Comment by AxeldeWater** [comment]
When I tried it worked as expected, but it could be that it exists there too. But when I tried it didn't. The bug is really unpredictable.

**Comment by AxeldeWater** [comment]
I tried it again in Chromium (today's version though), no bug like this that I could find. This new version of Bromite though: still there.

**Comment by uazo** [comment]
> Clicking the button should redirect you to the app.

I would say, however, to be careful with a possible bugfix: with the transfer of information between the browser and the applications, information related to navigation could also be sent (and vice versa after all).
a good compromise would be to filter that data, but it is often encoded and therefore difficult to clean, as well as different for application.

if I may have my say, I believe that the browser should never automatically open an application (that is, it must work as if it were in incognito mode). What do you think about it?

**Comment by AxeldeWater** [comment]
This is not needed. First time opening a link that can redirect to another app, Android itself asks you permission to open that other app if such link is clicked. If this permission is denied, it won't ever open the app clicking on such, if a one time permission is given it opens te app only that time and asks it again next time, if you give permission it will always open the app.

**Comment by csagan5** [comment]
> if I may have my say, I believe that the browser should never automatically open an application (that is, it must work as if it were in incognito mode). What do you think about it?

There is already a flag to control this, it is referenced in README.md.

> The bug is really unpredictable.

@AxeldeWater I assume the flag `#disable-external-intent-requests` is in default state since you did not report as changed it in the bug; can you spot any difference in `adb log` when the bug manifests vs when it does not?

**Comment by AxeldeWater** [comment]
I'm sorry, I don't know how adb log works. Were you able to reproduce the bug? 

(Yes that flag is on default)

**Comment by AxeldeWater** [comment]
https://user-images.githubusercontent.com/110288748/188327736-2590a1f3-18cf-41df-ac90-d3b8a349d3c9.mp4

**Comment by csagan5** [comment]
You should check the `adb logcat` output for clues on what happens when it works vs when it does not work.

**Comment by AxeldeWater** [comment]
I don't know if I'm clear or not.

I don't know how to get this output.

**Comment by uazo** [comment]
> I don't know how to get this output.

go to `chrome://crashes` and generate a report, logcat is present in the resulting file

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> No

I can reproduce it with Chromium.

Note: this happens only when using localised results and when clicking on the info tile suggestion, not when clicking on the main results. It is an interesting glitch but not a Bromite bug.
