### ISSUE TITLE
chrome://bookmarks does not show Mobile bookmarks directly

### ISSUE THREAD

**Issue by varaki** [bromite/bromite#2251]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

104.0.5112.63

### Device architecture

arm64-v8a

### Android version

12.0

### Device model

Poco X3 Pro

### Changed flags

smooth-scrolling, enable-quic, enable-gpu-rasterization, enable-zero-copy, enable-parallel-downloading

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

Since Bromite does not have a feature to pin websites to the new tab page I enable the Homepage option and set
**chrome://bookmarks/** as the url to be used as a workaround of this missing feature:

![image](https://user-images.githubusercontent.com/23281360/183656721-5e7ae355-e0b5-4874-82f2-873dc32c2c97.png)

So far it was working with the previous bromite version [103.0.5060.140](https://github.com/bromite/bromite/releases/tag/103.0.5060.140)) and showed all my bookmarks saved into **Mobile bookmarks**:

![image](https://user-images.githubusercontent.com/23281360/183656576-2cfd4760-a760-4fb4-9479-a0920dc9b948.png)

With the new version, it shows some kind of root bookmarks location, so you have to additionally select Mobile bookmarks to show them:

![image](https://user-images.githubusercontent.com/23281360/183656995-66009fa8-ba40-4e73-80ad-e87f853228c4.png)

### Steps to reproduce the bug

1. Enable and set Homepage to chrome://bookmarks/
2. Press the home icon in the browser
3. It will show a root bookmarks location with three options, so you have to additionally click on Mobile bookmars to show them

### Expected behavior

Pressing the home button should show the Mobile bookmars folder directly, when Homepage is enabled and set to chrome://bookmarks/ as before.

**Comment by uazo** [comment]
use a link like this:
```
chrome-native://bookmarks/folder/3
```
you can find it by browsing the bookmarks and displaying the link.
you can use that link as your homepage

**Comment by varaki** [comment]
> use a link like this:
> 
> ```
> chrome-native://bookmarks/folder/3
> ```
> 
> you can find it by browsing the bookmarks and displaying the link. you can use that link as your homepage

Nice, thank you very much!

**Comment by csagan5** [comment]
Is this worth documenting in the wiki?

**Comment by varaki** [comment]
> Is this worth documenting in the wiki?

I think so, yes.
