### ISSUE TITLE
some website can't be accessed if you connect with a firewall app

### ISSUE THREAD

**Issue by holequantum** [bromite/bromite#2262]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

104.0.5112.91

### Device architecture

arm64-v8a

### Android version

12.0

### Device model

moto edge 20

### Changed flags

none

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

no

### Describe the bug

if you use a firewall app
https://f-droid.org/en/packages/com.celzero.bravedns/
i am using this in firewall mode and does not block anything any app but if this firewall is running you can open all websites.
some websites can't be opened
https://hotstar.com
https://www.bromite.org
And many more

websites can be opened
https://www.eff.org/
https://www.mojeek.com/
### Steps to reproduce the bug

install rethink dns app and use it in firewall mode now search on google or duckdockgo or do anything else all works except that website

### Expected behavior

strange that you can open all website but not that one if you are in firewall mode.

**Comment by Tronikelis** [comment]
I have that same firewall app from f-droid and this is happening for me too. I can't open about 50% of the websites, I get an error which says "This site can't be reached, the connection was reset. ERR_CONNECTION_RESET"

**Comment by holequantum** [comment]
I have tried with both fdroid one and playstore one.
Just to be more confident as fdroid compiled themself and in playstore the devs compiled and sgin them in both case i find this bug which is not the case in other browser i have change in firefox.

**Comment by Tronikelis** [comment]
All other browsers work fine. It's a shame, I really enjoy the additional features of Bromite :/

**Comment by holequantum** [comment]
> All other browsers work fine. It's a shame, I really enjoy the additional features of Bromite :/

You should not say like that bromite is developed by extremely talented but very few no. Of dev so you can't access the best bug free experience but. Can be better if you can provide the fix yourself.
Hopefully casgan or uzzo will fix it soon.

**Comment by csagan5** [comment]
Check your DNS settings in Bromite.

**Comment by holequantum** [comment]
> 

It is on current service provider and rethinkdns app is a multifunctional app which have both firewall and dns features and i have checked it on my 3 devices it was same so if you can checl it yourself.
My finding is if you are using only rethink dns there is no issue and it is using vpn protocol for dns and no isssue what so ever now if you use both firewall and dns both it breaks stuff like some website will not open at all which is not a issue for chrome or firefox. If can test it.
