### ISSUE TITLE
Edit, Copy and share option not popping up when URL is selected in the address bar

### ISSUE THREAD

**Issue by openwick** [bromite/bromite#2266]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

104.0.5112.91

### Device architecture

arm64-v8a

### Android version

11

### Device model

Mi Poco x2

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

When a url is clicked on the address bar normally the option to edit and share should pop up but it is not popping up in Bromite. I have tested in Bromite, Chromium, Chrome and Brave and only bromite has this issue. It is there since 103 version and thought it would be fixed in later version but wasn't hence I am reporting it. I am attaching images for reference.

### Steps to reproduce the bug

1. Open a site and go to address bar and click it
2. Try to copy the URL

Option to copy and edit wont come and it is the bug.

### Expected behavior

Option to copy and edit should pop up and it is not coming in bromite.

### Screenshots

Bromite: 
![Screenshot_2022-08-16-18-00-56-476_org bromite bromite](https://user-images.githubusercontent.com/78715124/184883355-252a5044-57e5-4bc2-8d39-fbe1fc3c817e.jpg)

Chrome:
![Screenshot_2022-08-16-18-01-13-321_com android chrome](https://user-images.githubusercontent.com/78715124/184883364-e958cca8-bd9f-47a2-a3a8-2294fc1ad83a.jpg)
Brave:
![Screenshot_2022-08-16-18-01-56-900_com brave browser](https://user-images.githubusercontent.com/78715124/184883366-6f981a6c-7728-42d0-bb9f-80aa2ae763f2.jpg)
Chromium:
![Screenshot_2022-08-16-18-07-09-749_org bromite chromium](https://user-images.githubusercontent.com/78715124/184883372-38b2c99a-47ab-4ef1-b199-e2fcd60b3f5d.jpg)

As you can see edit copy and share option is popping up on all browsers except bromite.

**Comment by KokichaKolevTM** [comment]
Go to chrome://flags/#enable-search-ready-omnibox and select option "Enabled". I have mine like that and works without a problem.

**Comment by openwick** [comment]
@KokichaKolevTM Thanks It worked but why is not enabled in the first place? I will close this issue once @csagan5 confirm it is intentional.

**Comment by uazo** [comment]
@openwick see [here](https://github.com/bromite/bromite/pull/796#issuecomment-722688636)

**Comment by openwick** [comment]
@uazo according to this [comment](https://github.com/bromite/bromite/pull/796#issuecomment-721298741) in the PR you mentioned, the expected default behaviour is to have Omnibox always enabled. But that is not the case as mentioned in my issue. I have to manually enable this `chrome://flags/#enable-search-ready-omnibox` to make omnibox working. So that means omnibox is not enabled by default. So did something change or is this the new default?

Also from what I understand your PR  shows the URL along with the omnibox if the flag is enabled else just the omnibox just like in the Brave screenshot I attached  is that correct? So what flag do I have to enable to get this option as I could find that flag in the PR link you commented.

**Comment by csagan5** [comment]
The flag `#enable-search-ready-omnibox` is disabled by default; to get the extra menu items (edit, copy, share) you need to enable it, that is the "search-ready" omnibox.
