### ISSUE TITLE
Backport from v106 Issue 1300214: External Favicon Links Leak Browser History

### ISSUE THREAD

**Issue by uazo** [bromite/bromite#2269]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.
- [X] This is a feature request for the Bromite browser; not the website nor F-Droid nor anything else.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

Yes
https://bugs.chromium.org/p/chromium/issues/detail?id=1300214

### Describe the solution you would like

I never asked you, but do you think we should backport these changes or shall we wait?
Maybe can fix #788

### Describe alternatives you have considered

Wait for v106

**Comment by csagan5** [comment]
In the past I have already backported patches from future versions; we could add it to v105.

**Comment by csagan5** [comment]
Fixed in `105.0.5195.41`.
