### ISSUE TITLE
AMP still getting through on Google submenus when searching for a movie, product etc

### ISSUE THREAD

**Issue by thanuj10** [bromite/bromite#227]
**Bromite version**

Version: `72.0.3626.120`
Arch: ARM64
Android version: 9.0/Pie

**Is the bug reproducible with latest version?**
Yes.

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No.

**Is the bug a crash?**
No.

**Describe the bug**
When you Google something, Say a movie, You get a box with submenus such as cast, reviews etc. The links provided on those submenus still open up as AMP links i.e they aren't sanitized.

**To Reproduce**
1. Go to www.google.com and search for a product, movies etc
2. Click on reviews or anyother submenu.
3. Scroll down to find AMP links
4. Tap and see them open the AMP form.

**Expected behavior**
Webpages should open the original website and not Google's AMP version.

**Screenshots**
None.

**Comment by csagan5** [comment]
The AMP removal functionality is for the **search** results; regardless, I cannot see the AMP links you refer to.

@thanuj10 please specify an example search and which URLs you find, this report is too vague.

**Comment by thanuj10** [comment]
@csagan5 Is it okay if i post my issue as a .gif template?

**Comment by csagan5** [comment]
@thanuj10 sure, but that's more work for you. we only need here what you type in the search box and the URL in search results that is AMP but you believe it should not

**Comment by thanuj10** [comment]
@csagan5 Google seemed to have changed the search beahvior i think. I'm not getting public audience reviews today. Please close this issue for now. Ill update the here if at all i encounter the issue again.

**Comment by thanuj10** [comment]
The links as you asked for - 
https://www.google.com/search?q=murder+on+the+orient+express&oq=murder+o&ie=UTF-8&hl=en#wptab=s:H4sIAAAAAAAAAONgVuLVT9c3NEw2ys7Kyco1esTozS3w8sc9YSmnSWtOXmO04eIKzsgvd80rySypFNLjYoOyVLgEpVB1ajBI8XOhCvHsYuJyy8zJDUoty0wtX8SqkltalJJapJCfp1CSkaqQX5SZmleikFpRUJRaXKxQBFZVDACdUlHskwAAAA

(CLICK ON THE REVIEWS SECTION)

**Comment by csagan5** [comment]
Clicking on any review does not open an AMP page; even if it did, these are special search results.
