### ISSUE TITLE
HTTP/3 feature 

### ISSUE THREAD

**Issue by cooky0** [bromite/bromite#2281]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.
- [X] This is a feature request for the Bromite browser; not the website nor F-Droid nor anything else.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

no

### Describe the solution you would like

whould bromite browser enable http/3 feature in next update ?

### Describe alternatives you have considered

not

**Comment by csagan5** [comment]
This is something available from upstream Chromium.
