### ISSUE TITLE
youtube ads can't be blocked

### ISSUE THREAD

**Issue by holequantum** [bromite/bromite#2282]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

104.0.5112.91

### Device architecture

arm64-v8a

### Android version

12.0

### Device model

motorola edge 20

### Changed flags

none

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

Yes

### Is this bug a crash?

none

### Describe the bug

it can't block any ads in youtube where as ublock with firefox can actually block ads in youtube even brave can block ads in youtube.

### Steps to reproduce the bug

open youtube.com and see some videos random you will find ads.

### Expected behavior

it should skip the ads just like brave and firefox+ublock

### solution
regex blocking
https://github.com/slyfox1186/pihole-regex
https://stackoverflow.com/questions/71649752/block-youtube-ads

**Comment by holequantum** [comment]
Beave does block ads nicely in youtube and other area so it can look ifor help in ads blocking department from brave

**Comment by kdien** [comment]
@ziadhussain007 you do realize this is a free project that some awesome devs just work on in their own time with no compensation?

It's one thing to file bug reports and/or suggest features, but another thing to just be entitled, rude, and ungrateful, which is what you're doing. Are you contributing, monetarily or otherwise, to this project in any way? If it doesn't work for you, simply leave and don't use it.

**Comment by ziadhussain007** [comment]
Sorry bro I didn't mean ever to be disrespectful to you , I know you are great dev and you do awsome jobs and this heavy project needs time and effort , again sorry for any misunderstanding, I just wanted to add some thoughts to you , and of course thats a great project and great efforts you do

**Comment by holequantum** [comment]
https://github.com/uBlockOrigin/uAssets
ublock can block ads we can have its own blocklist to help block ads from youtube

**Comment by csagan5** [comment]
Please read FAQs before opening issues.
