### ISSUE TITLE
Flag/Site settings for disabling webfonts

### ISSUE THREAD

**Issue by pritkr** [bromite/bromite#2304]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.
- [X] This is a feature request for the Bromite browser; not the website nor F-Droid nor anything else.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

Reasons to block webfonts: Privacy, security, bandwidth, aesthetic of default fonts [[1]](https://collinmbarrett.com/block-web-fonts/) [[2]](https://security.stackexchange.com/questions/150950/why-does-our-web-security-team-block-web-fonts) 
Reasons to not block webfonts: breaks some sites which use icon fonts
Solution: A flag/site settings permission for webfonts which has webfonts enabled and require manual action to disable webfonts
Maybe there was a flag to disable this `--disable-remote-fonts` 

### Describe alternatives you have considered

Alternative filter for adblocking engine to block webfonts and instructions to do so(ublock origin can do this)

**Comment by uazo** [comment]
can you help me understand the privacy issue? How does downloading a webfont differ from download a script or an image?
On the other hand, with respect to security, has there ever been a CVE that signals a bug on the management of fonts in android?

as tecnical triage, there is the switch `--disable-remote-fonts` acting on
```
bool ContextAllowsDownload(ExecutionContext* context) {
  if (!context) {
    return false;
  }
  if (const auto* window = DynamicTo<LocalDOMWindow>(context)) {
    const Settings* settings =
        window->GetFrame() ? window->GetFrame()->GetSettings() : nullptr;
    return settings && settings->GetDownloadableBinaryFontsEnabled();
  }
  // TODO(fserb): ideally, we would like to have the settings value available
  // on workers. Right now, we don't support that.
  return true;
}
```
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/css/font_face.cc;drc=d78df4a8b353bd4dbafb730d83e621d5f97106ba;bpv=1;bpt=1;l=831
context: https://bugs.chromium.org/p/chromium/issues/detail?id=722511

it seems that it does not act on the workers, but the download is done via [FontResource::Fetch](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/loader/resource/font_resource.cc;l=56;drc=d78df4a8b353bd4dbafb730d83e621d5f97106ba;bpv=1;bpt=1) and then it is turned over to the browser process via mojo for the real request, so some changes will probably need to be done

**Comment by csagan5** [comment]
> as tecnical triage, there is the switch `--disable-remote-fonts`

This could be turned to a flag?

> can you help me understand the privacy issue? How does downloading a webfont differ from download a script or an image?

I think this is similar to third-party scripts downloads. At some point someone could request also to be able to disable third-party-anything.

I am going to close this as I do not think it's worth adding.
