### ISSUE TITLE
App not instaled

### ISSUE THREAD

**Issue by overtube** [bromite/bromite#2309]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

104.0.5112.91 (Official Build) (32-bit) 

### Device architecture

armeabi-v7a

### Android version

7.1

### Device model

Samsung SM j200h, on chrome://version section writed: "SAMSUNG SM-G960U"

### Changed flags

no flags chaged

### Is this bug about the SystemWebView?

Yes

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

The packageappears to be corrupt

### Describe the bug

After download from releases section, arm_systemWebview.apk.
And after I try install them I have this words: 'App not installed' 
The package appears to be corrupt

### Steps to reproduce the bug

This bug happened on latest avaliable at the moment, system web view.app from release section on github

### Expected behavior

I was install then and give this error again and again, after re-download, 3 times I get the same error.

### Screenshots

![ec123355-bf6c-4965-b413-55b7baf2f594](https://user-images.githubusercontent.com/15115920/188337169-ffe4b511-6b7d-4d80-b161-63aaf298befd.png)

**Comment by holequantum** [comment]
Can you check the file integrity with hash
https://github.com/bromite/bromite/releases/download/104.0.5112.91/brm_104.0.5112.91.sha256.txt

In linux `sha256sum filename.extension`
In mac `shasum -a 256 /path/to/file`

**Comment by holequantum** [comment]
And try to install fdroid and then add bromite repo and then install bromite if that works.
https://www.bromite.org/fdroid
https://f-droid.org/

**Comment by overtube** [comment]
Checksum correct. 
Installing via f-droid client not help.
Also I try installing them using adb and getting same error.

**Comment by overtube** [comment]
After cleaning dalvik/art cache and remove app installing again all work, all done, thanks

**Comment by csagan5** [comment]
Using `adb logcat` you can see more details about the reason of failure; it is usually wrong architecture or not enough space on the internal SD.
