### ISSUE TITLE
Bromite crashing upon launch

### ISSUE THREAD

**Issue by SphinxTwo** [bromite/bromite#231]
**Bromite version**

Version: `72.0.3626.68`
Arch:  `arm64` 
Android version: Oreo (8.1.0)

**Is the bug reproducible with latest version?**
`Bug must be reproducible with latest version`
Yes.

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No.

**Is the bug a crash?**
Yes, I pasted my logcat through Pastebin.
https://pastebin.com/hAf3dEn4

**Describe the bug**
Launching Bromite causes the application to crash. "Bromite has stopped."

**To Reproduce**
1. Launch Bromite.
2. See error

**Expected behavior**
Just using and launching the Browser without it crashing on startup.

**Screenshots**
![screenshot_20190122-102954_nova launcher](https://user-images.githubusercontent.com/13336168/51546184-9bf0ef80-1e31-11e9-858f-6241e7f78934.jpg)

**Comment by csagan5** [comment]
@SphinxTwo can you reproduce it with a freshly installed Bromite?

I suspect the crash is due to some specific tab.

You also have other crashes in that logcat not related to Bromite.

**Comment by SphinxTwo** [comment]
Okay, So I have tried it with the Chromium version as I should have done before in which I replied "No" to. 

Here is my Pastebin log with a freshly installed Bromite: https://pastebin.com/wepQYk79

Since this seems to be occurring with the latest Chromium version as well, should this issue be labelled as invalid?

**Comment by csagan5** [comment]
> Here is my Pastebin log with a freshly installed Bromite: https://pastebin.com/wepQYk79

Ok, so it happens also without any tab open. Unfortunately the crash is not telling much about where in the code the problem might be.



> Since this seems to be occurring with the latest Chromium version as well, should this issue be labelled as invalid?

I suggest waiting for another Chromium release (not built as part of the Bromite project) to see if it is an upstream problem; you might also want to try more recent Chromium builds done here as part of the Bromite project, as the bug might be fixed upstream.

But since the bug is reproducible in Chromium you should test it using Chromium builds only.

I suggest focusing for now on reproducibility of the bug, let's see if somebody else can reproduce it.

**Comment by SphinxTwo** [comment]
Alright. I updated the recent Pastebin link with only Error logs, hopefully it can narrow it down. I can try installing it on my two other Android devices, (S9+ on Pie Beta) and (Galaxy S5 on a custom rom) if needed.

**Comment by csagan5** [comment]
> I updated the recent Pastebin link with only Error logs, hopefully it can narrow it down.

It does not depend from you or the logs, this type of crash unfortunately does not tell precisely why it is happening.

> I can try installing it on my two other Android devices, (S9+ on Pie Beta) and (Galaxy S5 on a custom rom) if needed.

It would be useful to understand if it happens only on Oreo for example.

**Comment by SphinxTwo** [comment]
I have tried installing Bromite on the following Devices:

- Samsung Galaxy S5 (AospExtended Pie Rom): Installed and works normally.
- Samsung Galaxy S7 Edge (Stock Samsung Android Oreo 8.0.0): Installed and no crashes either.
- Samsung Galaxy S9+ (Samsung Pie Beta): Also works and no crashes.

 I also tried installing the latest Chromium builds and the results are the same as above.

It seems like it has to be related to my specific device as of now. Which is a Samsung Galaxy Note 9. I'll wait for another upstream release and see if it fixes the issue.

**Comment by csagan5** [comment]
@SphinxTwo I would look into those stagefright crashes, perhaps solving that will also solve this (although I would still consider it an upstream bug)

**Comment by eldervamp** [comment]
I got a Samsung Galaxy S9+ w/ Android 8.0 Oreo and any Chromium browser with 72.xxx build or above crashes the moment I launch it. 71.xx or below builds works fine for me. Makes me wonder why the stable Google Chrome for android is still at 71.xxx. Waiting on Android 9.0 Pie download to see if it solves the crashes.

**Comment by csagan5** [comment]
@SphinxTwo @eldervamp please try to reproduce using [Chrome Beta](https://play.google.com/store/apps/details?id=com.chrome.beta&hl=en_US) which is mostly Chromium; if it is reproducible also there then an upstream bug report is in order, otherwise please report back.

**Comment by SphinxTwo** [comment]
@csagan5 I just tried launching Chrome Beta which is currently v72.0.3626.64, and it doesn't crash for me.

**Comment by csagan5** [comment]
@SphinxTwo can you see if Bromite's Chromium build is still affected? https://github.com/bromite/chromium/releases/tag/72.0.3626.73

**Comment by SphinxTwo** [comment]
That chromium build also crashes for me as well.

**Comment by eldervamp** [comment]
@csagan5 No crashes using Chrome Beta v72.0.3626.73. But the Bromite Chromium Build from above link crashes on me :(

**Comment by csagan5** [comment]
@SphinxTwo @eldervamp can you post the crash dump from logcat? Only the Bromite crash dump section is necessary.

**Comment by eldervamp** [comment]
@csagan5 First time doing a logcat..lol. Hope this is it. 
[logcat.txt](https://github.com/bromite/bromite/files/2793753/logcat.txt)

**Comment by SphinxTwo** [comment]
@csagan5 Here's my crash dump https://pastebin.com/pbuvCqq6

**Comment by csagan5** [comment]
> @csagan5 Here's my crash dump 

@SphinxTwo can you please submit the one with latest Bromite?

> @csagan5 First time doing a logcat..lol. Hope this is it.

@eldervamp it does not contain any crash dump, see how it looks from @SphinxTwo's dump

**Comment by eldervamp** [comment]
@csagan5 Sorry, not sure how to do that. I'll stick with the 71.xx build in the meantime.

**Comment by SphinxTwo** [comment]
New Update: Just updated my Note 9 to Android Pie and the crashing seems to be fixed.

**Comment by eldervamp** [comment]
Yes, My Galaxy S9+ has Android Pie also and no more crashes. Looks like the bug is on Oreo.
