### ISSUE TITLE
arm64 bromite/webview navigator.platform return wrong value

### ISSUE THREAD

**Issue by ghost** [bromite/bromite#2318]

**Comment by csagan5** [comment]
This happens when you install the armv8 APK.

**Comment by csagan5** [comment]
I observe the same value with Vanilla Chromium, `Linux armv81`. It means that the Chromium/Bromite ELFs are 32bit.

**Comment by csagan5** [comment]
I cannot reproduce this; I think that the APK contains both versions and the appropriate one is automatically used. @uazo @wchen342 @chirayudesai do you know about this?

**Comment by csagan5** [comment]
`ReduceUserAgent` is enabled by default in Bromite, so this is already expected behaviour. I assume that my test with Chromium is invalid for some other reason.
