### ISSUE TITLE
Some websites load completely dark webpages

### ISSUE THREAD

**Issue by peta9** [bromite/bromite#232]
**Bromite version**`72.0.3636.68`
Arch: `arm`
Android version: `6.0.6`

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding Chromium release?**
Not sure

**Is the bug a crash?**
No

**Describe the bug**
**Some** websites load completely dark webpages (i.e. screen turns black).

**To Reproduce**
Steps to reproduce the behavior _(not always reproducible)_:
1. Go to
http://bilimneguzellan.net/bouncing-cubes-and-π-3blue1brown/
https://www.playstation.com/en-gb/explore/psp/
https://www.gamespot.com/forums/offtopic-discussion-314159273/i-m-starting-to-think-that-dr-phil-is-a-staged-sho-31081273/
https://news.abs-cbn.com/news/01/22/19/pnp-claims-drop-in-2018-nationwide-crime-volume
other websites may be tried out.
**P.S.** It was for me a first time visit to each of those websites using the google search engine.
2. Allow the webpages to load
3. See the black screen

**Expected behavior**
They should load normally.

**Comment by csagan5** [comment]
@peta9 what is the error? You can use [Remote debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/) to inspect the faulty situation.

**Comment by csagan5** [comment]
@peta9 you have removed mentions of errors.

Please use remote debugging to check what is happening with and without adblocking. If the bug is not reproducible then there is little that can be done here.
