### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by edentw** [bromite/bromite#233]
**Is your feature request related to privacy?**
No

**Is there a patch available for this feature somewhere?**

**Describe the solution you'd like**

**Describe alternatives you've considered**
Some menu functions of the browser are in English, so is there an open third party to assist in translation?

**Comment by csagan5** [comment]
No third party that I know of; it is sufficient to submit a patch to this project for inclusion to address the missing translations problem.

I have seen many times a request for the translations to be added but no patch submitted so far by anybody.

**Comment by Madis0** [comment]
Aren't translations available upstream?

**Comment by csagan5** [comment]
@Madis0 not for the new menu items, but I would not know how to add them.

Patches welcome.
