### ISSUE TITLE
Adding ACTION_WEB_SEARCH intent

### ISSUE THREAD

**Issue by ouzowtf** [bromite/bromite#234]
**Is your feature request related to privacy?**
No, not really.

**Is there a patch available for this feature somewhere?**
I'm not sure.

**Describe the solution you'd like**
It would be nice if Bromite would support the ACTION_WEB_SEARCH intent other apps may use to search from their apps.

**Describe alternatives you've considered**
My alternative is not having this implemented :D

This request is mainly to check if this is easy to implement and you think it's useful, even if it's not for privacy reasons.
Chromium and Chrome doesn't offer this currently.

**Comment by csagan5** [comment]
@ouzowtf I suggest pursuing this upstream, not related to privacy at all and additionally cumbersome to develop
