### ISSUE TITLE
Incognito Mode Disables Regular Browsing Mode

### ISSUE THREAD

**Issue by js290** [bromite/bromite#2346]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

105.0.5195.41

### Device architecture

arm64

### Android version

12.0

### Device model

Moto X4

### Changed flags

move-top-toolbar-to-bottom

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

1. No

### Describe the bug

When `Always open links in incognito` is enabled, it is no longer possible to open regular (_cognito_) browser windows/tabs.

### Steps to reproduce the bug

1. Settings -> Privacy and security -> Incognito mode -> enable Always open links in incognito
2. Relaunch Bromite
3. Inability to open non-incognito tabs

### Expected behavior

`Always open links in incognito` should not prevent opening regular browser tabs (_cognito_ mode?).  The expectation is for Bromite to open links from other Android apps in incognito mode.  But, regular browsing mode should still function when using Bromite.

**Comment by uazo** [comment]
> to open links from other Android apps in incognito mode.

maybe you are confusing "Always open links in incognito" with the other option "Open external links in incognito".
with the former disabling normal mode is intended

**Comment by csagan5** [comment]
It is working as intended; if you think there is any documentation that can be improved feel free to suggest those improvements.
