### ISSUE TITLE
Unavailable F-Droid repository in Russia

### ISSUE THREAD

**Issue by black-cerberon** [bromite/bromite#235]
Hello, can you change IP of _fdroid.bromite.org_ or make mirror, because it blocked in Russia?
https://isitblockedinrussia.com/?host=fdroid.bromite.org

**Comment by csagan5** [comment]
@black-cerberon I am sorry for this issue, but they blocked an entire subnet of the CDN used for the F-Droid repository and I have no way to ask the CDN provider to change the IP address; even if it were changed, another subnet block could recreate the same problem.

You can always use the releases here on Github (which are official) or possibly APKMirror (https://www.apkmirror.com/apk/bromite/bromite/) which is unofficial but uploaded also regularly.
