### ISSUE TITLE
Unable to access 192.168.1.1

### ISSUE THREAD

**Issue by thebizcoder** [bromite/bromite#2356]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

105.0.5195.41

### Device architecture

arm64-v8a

### Android version

12.1

### Device model

Realme 5 Pro

### Changed flags

No flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

In this version of bromite i am unable to access 192.168.1.1 to change my router settings while in bromite 104... Versions it was working perfectly fine.

The error message  i get is:
This site can’t be reached192.168.1.1 refused to connect.
Try:

Checking the connection
ERR_CONNECTION_REFUSED

### Steps to reproduce the bug

1. Go to 192.168.1.1

### Expected behavior

It should connect to 192.168.1.1

### Screenshots

![git](https://user-images.githubusercontent.com/91343931/192508813-c3f21af6-f9e8-4405-852c-7877857fe158.jpg)

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> No

I do not believe this is true. Please test with Chromium, this is not a bug in Bromite.

**Comment by Disqu3-mirOir-qt** [comment]
![Screenshot_20220928-144236_1.jpg](https://user-images.githubusercontent.com/41585567/192781532-afaed6ee-3bf8-40bb-bed0-c285c8794b55.jpg)

i think related to isp side and not bromite in my side work

**Comment by IOrlandoni** [comment]
thanks
