### ISSUE TITLE
Permissions cannot be requested

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#2357]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

105.0.5195.41

### Device architecture

arm64-v8a

### Android version

12.1

### Device model

OnePlus 10

### Changed flags

`#disable-external-intent-requests` set to disabled

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

On Android 12 permissions cannot be requested, despite app having the permission (for example geolocation).

### Steps to reproduce the bug

1. Disable `#disable-external-intent-requests`
2. go to maps.google.com
3. click on the bottom-right circle to locate yourself
4. permissions prompt will be visible
5. when clicking on any option there is a Retry/Cancel dialog saying "This site can't ask for your permission"

Cannot be reproduced with Android 11.

### Expected behavior

Permission should be retrieved and saved.

### Screenshots

![image](https://user-images.githubusercontent.com/32685696/192650844-1b3dae1a-90a9-41d7-a1eb-aa818bb5bb41.png)

**Comment by csagan5** [comment]
@uazo any idea?

**Comment by uazo** [comment]
I look at it

**Comment by uazo** [comment]
unfortunately I can't reproduce it with the emulator and android 12 and 13 (I can't find 12.1).

but the code of the popup is [showFilteredTouchEventDialog](
https://source.chromium.org/chromium/chromium/src/+/main:components/permissions/android/java/src/org/chromium/components/permissions/PermissionDialogController.java;l=216;drc=a432cd59d51281057ba2a2673ca645a9600bb927;bpv=1;bpt=1?q=showFilteredTouchEventDialog&ss=chromium%2Fchromium%2Fsrc) while the check is instead in [setupFilterTouchForSecurity](https://source.chromium.org/chromium/chromium/src/+/main:components/browser_ui/modaldialog/android/java/src/org/chromium/components/browser_ui/modaldialog/ModalDialogView.java;l=236;drc=a432cd59d51281057ba2a2673ca645a9600bb927;bpv=1;bpt=1?q=setupFilterTouchForSecurity&ss=chromium%2Fchromium%2Fsrc) and is relative to [FLAG_WINDOW_IS_PARTIALLY_OBSCURED](https://developer.android.com/reference/android/view/MotionEvent#FLAG_WINDOW_IS_PARTIALLY_OBSCURED)

Isn't that maybe you have something that has the rights to draw on top of other apps?

**Comment by csagan5** [comment]
I think I found it, it is an OEM installed app by Samsung. Thanks for looking into it.

I guess it can be closed.
