### ISSUE TITLE
Bromite blocks map & radarlayer from https://sataako.fi even when adblocker disabled

### ISSUE THREAD

**Issue by huuhaa** [bromite/bromite#2360]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

105.0.5195.147

### Device architecture

arm64-v8a

### Android version

12.1

### Device model

Nokia 7 Plus

### Changed flags

'no flags changed' none blue highlighted, some enabled by default

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

1. No

### Describe the bug

When I go to https://sataako.fi bromite blocks map & weather radar view even when adblock disabled.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to https://sataako.fi
2. Either give or deny persmissions
3. Map & radar data not showing. note when those are showed, it shows data for Finland

### Expected behavior

Expected behavior is to show map & radarlayer on top of map (Finland), no ads on page so expected that should work also with adblock enabled.

Tested to worked with following browsers:

Mulch 106.0.5249.65
iode browser (firefox based)
calyx chromium (bromite fork with adblocker)

### Screenshots

Not working screenshots from Bromite:
![SS1](https://user-images.githubusercontent.com/469355/193038816-9727da20-70ec-4b32-b41c-d7e763f0781a.jpg)
![SS2](https://user-images.githubusercontent.com/469355/193038830-b0ed9d1d-85b6-4194-bb48-72adf939b7ce.jpg)
![SS3](https://user-images.githubusercontent.com/469355/193038832-ed5fd4f5-5d7c-4f13-a0d1-2cb0c19403ed.jpg)

Working example screenshot from Mulch:
![Working_example_with_Mulch](https://user-images.githubusercontent.com/469355/193038912-a41f9da2-8421-4320-a6ea-af3d8e2443f2.png)

**Comment by uazo** [comment]
the behavior of bromite is correct. 
you have to activate webgl via site settings for that site to work in bromite.

**Comment by huuhaa** [comment]
@uazo Indeed, that solves the problem, thanks!
