### ISSUE TITLE
Proxy bypass rules aren't working 

### ISSUE THREAD

**Issue by RENOMIZER** [bromite/bromite#2372]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

105.0.5195.147

### Device architecture

arm64-v8a

### Android version

11

### Device model

Lenovo TB-J606F

### Changed flags

No flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

Bypass rules for proxy do not work in any ways. Checking or unchecking "reverse meaning of bypass rules" doesn't help either.

### Steps to reproduce the bug

1. Go to Settings - Privacy and security - Proxy configuration
2. Configure single or per-scheme proxy lists.
3. Enter the bypass rules.
4. Apply changes.
5. Check proxy status with specialized website.

### Expected behavior

For websites mentioned in bypass rules to send traffic through proxy, while for the others to send traffic directly.

### Screenshots

![Screenshot_2022-10-03-16-59-13-781](https://user-images.githubusercontent.com/94466218/193596475-2dd74261-6edf-4f8c-85bc-55d5bf31a8b9.jpeg)
Proxy is configured and website is in bypass rules.
![Screenshot_2022-10-03-16-59-31-670](https://user-images.githubusercontent.com/94466218/193596679-c27c1c47-0254-4f75-ad1b-88c7ac239892.jpeg)
Website keeps using proxy

**Comment by uazo** [comment]
I've never used that function, but in the [documentation](https://chromium.googlesource.com/chromium/src/+/main/net/docs/proxy.md#Proxy-bypass-rules) it doesn't mention quotes.
have you tried without?

**Comment by RENOMIZER** [comment]
> I've never used that function, but in the [documentation](https://chromium.googlesource.com/chromium/src/+/main/net/docs/proxy.md#Proxy-bypass-rules) it doesn't mention quotes. have you tried without?

Ah, yes. Removing quote marks did help. Thank you.
