### ISSUE TITLE
Bromite crashes in some circumstances when using PWAs and always incognito

### ISSUE THREAD

**Issue by rowboatz** [bromite/bromite#2375]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

105.0.5195.147

### Device architecture

arm64-v8a

### Android version

12.1

### Device model

Pixel 6, Android 13

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

[0701f134-0d87-4e9d-abb4-73b3215e7e90.zip](https://github.com/bromite/bromite/files/9714719/0701f134-0d87-4e9d-abb4-73b3215e7e90.zip)

### Describe the bug

When "always open links in incognito" is enabled **and** both Bromite itself **and** a Bromite PWA are loaded, Bromite crashes **either** a few seconds after the PWA is closed **or** instantly when trying to open a tab in Bromite after closing manually all the tabs.

Observations :
- pretty sure this did not happen before 105
- crashes no matter what website is loaded, as long as it loads as a PWA (twitter.com for example)
- crashes only when "always open links in incognito" is toggled on, seems other settings have no effect
- seems not to crash under any circumstance as long as **only one** of either Bromite itself or a Bromite PWA is loaded at a time (present in the android recent apps view)

### Steps to reproduce the bug

1. On the home screen, tap on a shortcut that will load a website **as a PWA** (twitter.com for example)
2. Open Bromite itself without closing the PWA, an incognito tab is automatically loaded
3. Close the blank incognito tab by tapping the "tabs" button and swiping on the tab
4. Tap the "+" button to open a new tab
5. Bromite crashes instantly

**OR**

1. Open Bromite
2. Go to the home screen, tap on a shortcut that will load a website **as a PWA** (twitter.com for example)
3. Close the PWA
4. Bromite crashes after a few seconds without any other user input

### Expected behavior

Bromite doesn't crash in any circumstance when using both regular browsing and PWAs at the same time.

**Comment by Scoojo** [comment]
I also have this issue, happens when I'm browsing newzit.com , a news aggregator. The whole browser will suddenly exit, and, I'll have to manually open it again.

**Comment by burakowski** [comment]
I have the same problem, I hope [this logcat](https://pastebin.com/uEMKU9Fs) may help to fix the issue.

**Comment by uazo** [comment]
can you check if the bug is present in the latest version? thanks.

**Comment by rowboatz** [comment]
Not reproducible anymore! No crashes at all since last update.

P.S. I highly appreciate both your and csagan5's work on Bromite in general! Cheers!
