### ISSUE TITLE
Website cannot be clicked normally

### ISSUE THREAD

**Issue by edentw** [bromite/bromite#238]
**Bromite version**

Version: v72.0.3626.73
Arch: arm64
Android version: 7.0 nrd90m

**Is the bug reproducible with latest version?**
Yes!

**Can the bug be reproduced with corresponding [Chromium]
No,

**Is the bug a crash?**
No

**Describe the bug**
https://today.line.me
The link to this news report cannot be clicked normally, so I hope you can overhaul this issue!

**To Reproduce**
This site should be able to be clicked and turned to content!

**Expected behavior**

**Other**
Can the adblock part be added to the custom whitelist function?

Thank you!

**Comment by ouzowtf** [comment]
I have no problem to open this page, although I don't understand anything that's written there.

**Comment by edentw** [comment]
> I have no problem to open this page, although I don't understand anything that's written there.

I am not referring to the opening of the website, but the pages inside can not be clicked open!

**Comment by csagan5** [comment]
Will be fixed in next release `72.0.3626.81` (not yet released)
