### ISSUE TITLE
Allow opening of links in external apps in incognito mode

### ISSUE THREAD

**Issue by stantios** [bromite/bromite#2380]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.
- [X] This is a feature request for the Bromite browser; not the website nor F-Droid nor anything else.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

This was implemented before but only for non incognito mode and it is somewhat annoying for me when I'm browsing in incognito mode that apps don't open when clicking on a link that should redirect to an app.

### Describe alternatives you have considered

Maybe there could be a toggle for if they want to allow 'Open links in external apps' in the privacy section, off course it would be off by default.

**Comment by stantios** [comment]
There was a patch for this but I can't find it anymore in the latest release.

**Comment by uazo** [comment]
from a privacy point of view is a big problem because it is not possible to block data that the `Intent` contains, and so it is possible to link the navigation made by the browser with that of the application.
In fact, it would be better never to allow any browser to open applications.

**Comment by stantios** [comment]
I understand that, but maybe it could be added as a flag again to allow apps through incognito mode so the user gets a choice of if they want to allow apps through incognito.

**Comment by uazo** [comment]
personally, I am not convinced. it would be much better to check whether it is possible to eliminate unnecessary information per application.
you could start by making a list of applications and the information that is passed on by the browser to understand what they are going through.

**Comment by stantios** [comment]
Why was it removed as a patch in the first place?

**Comment by csagan5** [comment]
> There was a patch for this but I can't find it anymore in the latest release.

There has never been. Feel free to find it if you think otherwise.

> In fact, it would be better never to allow any browser to open applications.

As documented in README there is a flag, `#disable-external-intent-requests` and intents are disabled by default.

> you could start by making a list of applications and the information that is passed on by the browser to understand what they are going through.

We are not going to add a list of applications and the special cases for their intents in Bromite.

> Why was it removed as a patch in the first place?

There has never been one and Chromium/Chrome also do not allow intents while in incognito.

Since this feature request is about making privacy worse it has no place in Bromite, sorry.
