### ISSUE TITLE
False HTTP Warning

### ISSUE THREAD

**Issue by PassionateG1t** [bromite/bromite#2386]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

105.0.5195.147

### Device architecture

arm64-v8a

### Android version

12.0

### Device model

SM-A515F

### Changed flags

#enable-parallel-downloading

#enable-tab-groups

#context-menu-search-with-google-lens (Disabled)

#strict-origin-isolation

#enable-prerender2 (D.)

#omnibox-trigger-for-prerender2 (D.)

#enable-throttle-display-none-and-visibility-hidden-cross-origin-iframes

#dynamic-color-buttons-android

#close-all-tabs-modal-dialog

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

I use the Random Searx Redirector (https://searx.neocities.org) as default search engine. Interestingly, while the website supports HTTPS, when I search the omnibox initially says it's HTTP and then would proceed to upgrade it to HTTPS. However, upgrade doesn't always occur and a warning prompt says that the connection isn't secure (refer to screenshot) but in fact it is secure because when I press "continue to site" it takes me to the HTTPS version. This happens often but not consistently, also with a few other websites.

### Steps to reproduce the bug

1. Make Random Searx Redirector default search engine
2. Search anything

### Expected behavior

Results appear normally without the hassle of failing to upgrade to HTTPS

### Screenshots

![yeveusbsb](https://user-images.githubusercontent.com/107609269/194745918-25f15a10-a216-4868-9387-6d504dbf36bd.jpg)

**Comment by uazo** [comment]
it is not a false positive, bromite behaves correctly.
opensearch xml points to http, look:

```
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
   <ShortName>Random Searx</ShortName>
   <Description>Random Searx Redirector</Description>
   <InputEncoding>UTF-8</InputEncoding>

   <Url type="text/html" method="get" template="http://searx.neocities.org/#">
                                                ^^^^----------------
   <Param name="q" value="{searchTerms}"/>
   <Param name="category_general" value="on"/>
</Url>
</OpenSearchDescription>
```
source: https://searx.neocities.org/opensearch.xml?method=GET&autocomplete=

**Comment by uazo** [comment]
I think it is due to [this](https://bugs.chromium.org/p/chromium/issues/detail?id=1282375) or something similar, which was another report from us, unfortunately still pending

**Comment by csagan5** [comment]
There is no backend and there is no exception list; if there was one in Chromium, it would be removed altogether.
