### ISSUE TITLE
UI Unresponsive after Opening URL through Share Menu

### ISSUE THREAD

**Issue by heartlessglasses** [bromite/bromite#2388]
On the latest version, using the Open URL in Bromite option in the share menu opens the URL in a new tab, but the UI (the whole top bar) becomes completely unresponsive, necessitating a restart.

**Comment by deepspaceaxolotl** [comment]
Could someone delete this issue perhaps? I submitted a proper version of it, and importantly, the bot here used my old username which I plan on changing so it isn't tied to this account and Github-related things. That won't change it in the bot's comment, though, so I'd appreciate having it (or rather, this issue) removed, especially as this is a redundant issue.

**Comment by deepspaceaxolotl** [comment]
Changed my username, would appreciate some help having this deleted so I can keep my online identities separate! (Not sure who's an admin of this repo other than @csagan5.)
