### ISSUE TITLE
Page occasionally loads fully black and unresponsive

### ISSUE THREAD

**Issue by IOI-655321** [bromite/bromite#239]
**Bromite version**

Version: 72.0.3626.73
Arch: arm64
Android version: Andoird P

**Is the bug reproducible with latest version?**
Sometimes

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No

**Is the bug a crash?**
No

**Describe the bug**
When visiting some pages following a download link to www.filescdn.net I get a completely black page, the page stays black when clicking back button and reloading the page or choosing desktop version etc.  I have to close the tab and re-open this to get it back to normal.

**To Reproduce**
1. Find a link to www.filescdn.net for a download
2. Click on the link
3. Page sometimes loads completely black
4. Press back button and the original page is also black ad refreshing doesn't help.

**Expected behavior**
Page loads normal

**Comment by csagan5** [comment]
@IOI-655321 can you reproduce the issue with latest version `72.0.3626.81`?
