### ISSUE TITLE
Awful performance in WebGL apps

### ISSUE THREAD

**Issue by xslvrxslwt** [bromite/bromite#2390]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

Bromite v105.0.5195.147

### Device architecture

arm64

### Android version

12.1

### Device model

Poco X3 NFC (surya)

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No.

### Describe the bug

Huge WebGL renderer performance regression (compared to Chromium and Kiwi), almost 300% worse.

### Steps to reproduce the bug

1. Go to 'https://webglsamples.org/aquarium/aquarium.html'
2. Change number of fishes to 30000
3. Compare FPS to Chromium/Kiwi/Mozilla/etc.

### Expected behavior

Frames doesn't drop to 1-3FPS

### Screenshots

Bromite 
![Screenshot_20221011-131327_Bromite](https://user-images.githubusercontent.com/105242066/195077311-b5b0bebd-e75e-47a9-b506-64e20ef06bd0.png)

Kiwi (same as Chromium)
![Screenshot_20221011-131432_Kiwi Browser](https://user-images.githubusercontent.com/105242066/195077367-7c7bbf8c-cfe2-4676-bf01-118f3e6925bb.png)

**Comment by uazo** [comment]
try to enable javascript jit too. my mobile goes from 30 to 60 fps.

**Comment by xslvrxslwt** [comment]
> try to enable javascript jit too. my mobile goes from 30 to 60 fps.

That was it. Enabling JavaScript JIT makes it even faster than Chromium, but I'll keep this open in case further improvements can be made in case Chromium isn't using JS JIT yet performing relatively the same (correct me if I'm wrong, didn't even look ab it)

**Comment by csagan5** [comment]
I add a FAQ in fdb76cc, but the default will not be changed; it is unfortunately a very profitable vector for vulnerabilities.
