### ISSUE TITLE
Clickable things are unresponsive with bromite

### ISSUE THREAD

**Issue by libellula** [bromite/bromite#2399]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

105.0.5195.147

### Device architecture

arm64

### Android version

12.1

### Device model

SM-G780G-DS

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No.

### Describe the bug

Try to search anything with google. Then, in the results page, click on the banner "Google" above the search bar. It should bring you back to the home page, but with bromite it's not even clickable. The same behaviour can be reproduced on any site that asks you to agree with their policy, accepting cookies etc... the options aren't clickable and you are forced to browse the page with the window open.

### Steps to reproduce the bug

Go to google.
Search something.
Click on the colored "google" above the search bar. 

### Expected behavior

Nothing happens. It should be clickable, but it's not responsive instead.

### Screenshots

![Screenshot_20221018-212519_Samsung Internet](https://user-images.githubusercontent.com/61087558/196525741-7999cbcd-9084-4dd0-b8ae-c6585b2b8309.jpg)

**Comment by csagan5** [comment]
The logo click handler is replaced by the anti-AMP patch; for other websites they might have Javascript breakage due to the adblocker; test them individually with and without the adblocker to see if that is the case.
