### ISSUE TITLE
Can't browse on public Wi-Fi networks like McDonalds

### ISSUE THREAD

**Issue by cdysthe** [bromite/bromite#24]
I get connection errors and warnings when connected to certain public Wi-Fi networks like McDonald. Unfortunately I depend on those connections. Is there a way to get Bromite to work with insecure Wi-Fi networks like that.

**Comment by csagan5** [comment]
This is not specific of Bromite, you should get the same errors with regular Chrome. They have tightened up security in Chromium/Chrome, it is a welcome improvement.

You should probably enter the network with the popup "access to network required", then use Bromite or Chrome.

**Comment by cdysthe** [comment]
I see that this is closed but it worked in Chrome and not in Bromite. I tried both several times at a McDonalds. In Chrome I got the terms acceptance page from McDonald's. In Bromite only the error message

**Comment by csagan5** [comment]
@cdysthe can you add the address of the page and screenshot of the error? It could be an adblocking error

**Comment by cdysthe** [comment]
@csagan5 I will next time I go to McDonalds or another public Wi-Fi that requires tern acceptance. Might take some time now during Xmas.

**Comment by csagan5** [comment]
@cdysthe let me know, I believe it's an adblock filter problem
