### ISSUE TITLE
Bromite shows a preview of the homepage at startup

### ISSUE THREAD

**Issue by afermar** [bromite/bromite#2402]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

105.0.5195.147

### Device architecture

arm64-v8a

### Android version

10

### Device model

Xiaomi Mi A2 Lite

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

When I open bromite, instead of loading the homepage, it only shows a preview of the homepage and i'm unable to interact with the page until i manually reload it.

### Steps to reproduce the bug

1. Go to settings -> homepage and add "https://google.com" as custom homepage.
2. Navigate to your added homepage.
3. Close Bromite
4. Open Bromite again

### Expected behavior

Load homepage at startup and don´t show only a preview

### Screenshots

![Screenshot_20221020-180322_1](https://user-images.githubusercontent.com/99222323/197001131-674e6165-f8c3-4c07-b032-412eea33f9d3.png)

**Comment by n-buna404** [comment]
This is not a bromite bug but rather feature(freeze dried tab) that Google introduced during V105. It should be reproducible in corresponding Chromium version.
For info on how to disable this and google motivation of introduction see
https://github.com/bromite/bromite/discussions/2336

**Comment by afermar** [comment]
@n-buna404 Thank you! That was it.
