### ISSUE TITLE
Bottom toolbar causes white stripe at top in tab view

### ISSUE THREAD

**Issue by Gravemind2015** [bromite/bromite#2407]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

106.0.5249.72

### Device architecture

arm64-v8a

### Android version

12.0

### Device model

Samaung M51, Nokia 6.1

### Changed flags

Move-top-toolbar-to-bottom(enabled), Tab-Grid-Layout(Enabled new tab variant)

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

* I have been using tab grid option for about a year now. 
* Today (24 oct 2022) the layout suddenly reverted to strip mode, where each tab shows up as a single strip with website icon at left, and close button on right.
* Since bottom toolbar was enabled, there's a blank white strip at the top now.
* I was on 105, upgraded to version 106.0.5249.72 via f-droid bromite repo, also tried clearing data and at last, clean install of 106 but it persists.
* The grid tab flag no longer works, none of the available settings have any effect.
* Corresponding chromium (fresh install) doesn't expose this flag, so can't confirm if white stripe could occur. 

### Steps to reproduce the bug

1. Fresh install
2. Go to settings>accessibility
3. Enable 'Move toolbar to bottom'
4. Restart bromite
5. The tab bar is on bottom but now in tab page there's a white stripe on top.

### Expected behavior

* I did a fresh install on my nokia 6.1 (android 12 lineageOS) too. Version 106.0.5249.72
* Grid tabs are enabled by default and the flag for it is set to 'default'
* No stripe issue in grid mode.
* Expected behaviour I guess would be grid view working?

Dunno if flags are controlled by google, which might explain why both devices are behaving differently (staged rollout?). I'd expect grid view to stay considering it's the default view on a fresh install on the unaffected 6.1 device (I also have a personal bias towards it :-P)

### Screenshots

![CamScanner 10-24-2022 23 20_1](https://user-images.githubusercontent.com/116586720/197593499-201d9b02-44cb-43ba-a937-3ab1740f1ba2.jpg)
![CamScanner 10-24-2022 23 20_2](https://user-images.githubusercontent.com/116586720/197593509-64094b3b-adbb-4848-be4a-3a997c4da9ed.jpg)
![CamScanner 10-24-2022 23 20_3](https://user-images.githubusercontent.com/116586720/197593513-eeb1b171-bcc0-4749-9d15-b2cf9408b478.jpg)
![CamScanner 10-24-2022 23 24_1](https://user-images.githubusercontent.com/116586720/197593518-491afe92-f286-47c4-937a-90c079304c93.jpg)
![CamScanner 10-24-2022 23 24_2](https://user-images.githubusercontent.com/116586720/197593520-0beb846d-92d5-4e0d-9782-bd46d4310aeb.jpg)

**Comment by Gravemind2015** [comment]
Update: I tried chrome stable and dev, and both had this strip view. However no bottom bar flags so can't replicate.

But, I found yet another glitch:

When tab list view is full, and a new tab is opened via clicking an external link, the new tab gets hidden 'behind" the bottpm tab bar. Tab is still present and accessible by activating a visible tab, and swiping on the bottom bar to reach the new one. Further new tabs push it 'up', making it visible.

**Comment by uazo** [comment]
@Gravemind2015 thank you for the report, honestly in the v106 I had never detected it.

**Comment by Gravemind2015** [comment]
Hey, just wanted to update, I just opened bromite and it's mysteriously fixed now. I swear I didn't touch anything in the meantime: it wasn't fixed a few hours ago, now it is. 

Also, tried reverting the flag Tab Grid Layout to 'default' and still the grid tabs stick. Also the white stripe at top is gone (Yay).

I apologise if this report was unnecessary and it was (somehow) google fiddling with stuff (although I don't want to think google should affect bromite?) but I'm really happy to see it fixed ☺️

Closing this now as it's resolved. Thanks again for the amazing work 👍

**Comment by csagan5** [comment]
This issue will be fixed in the first v107 release, @uazo has contributed the fix.

**Comment by gilangkpg** [comment]
Hi @csagan5 , I'm not sure if it is related to that fix but after updating to v107 I got 2 problems with my tab groups.

1. my tab groups are out of order (I have 20+ tab groups open).
2. The default new tab location for bottom toolbar is now on top unlike before where it's conveniently at the bottom (and my preference). If I disabled bottom toolbar, the new tab location will be at the bottom instead. To be clear I'm talking about where the new tab open not the 'new tab' button.

I've been messing around with flags with no luck, hopefully you guys can at least revert the new tab location stuff (or make an option regarding to it)

Cheers

**Comment by Gravemind2015** [comment]
> 2. The default new tab location for bottom toolbar is now on top unlike before where it's conveniently at the bottom (and my preference). If I disabled bottom toolbar, the new tab location will be at the bottom instead. To be clear I'm talking about where the new tab open not the 'new tab' button.


Yep, I'm also quite confused while using tab view vs switching through tabs by swiping on the address bar. But IIRC it was intentionally done, not a mistake. 

I too personally prefer a bottom bar+ bottom new tab layout. Top bar = bottom tab layout and bottom bar = top tab layout seem logical and consistent, but the bottom bar option is usually used to aid one hand operation and reachability, and now new tabs aren't really rechable when they're being created at the top. This also kinda negates the beautiful gesture-up-from-addressbar feature unless the device is tiny or user has large fingers to reach above the old tabs.

**Comment by uazo** [comment]
To sum up, you would like the order of the tabs to be from newest to oldest, I can try...

**Comment by Gravemind2015** [comment]
Sorry, I probably wasn't clear enough with my post. What I'd personally prefer is the behaviour up until version 106. Moving address bar to bottom won't affect the tab area, the older tab will be at top, and newer tab would be created towards bottom. This way, both address bar and newer tabs would be easier to reach and interact with.
I've made some basic illustration, tab 1 is oldest, 3 will be newest, and in both illustrations address bar will be at bottom (just the difference between what changed in 107 vs what used to be, and why previous implementation was probably better):
![CamScanner 11-18-2022 12 49_1](https://user-images.githubusercontent.com/116586720/202646290-58d95879-50f0-4b05-a472-27220466eb1d.jpg)
![CamScanner 11-18-2022 12 49_2](https://user-images.githubusercontent.com/116586720/202646309-ef37bf60-a55c-4435-a99a-878714fb0b33.jpg)

**Comment by uazo** [comment]
what I propose is, from bottom left, newest to oldest:

![image](https://user-images.githubusercontent.com/29201891/202647284-668e2782-934d-4177-8f32-fe8e53f94608.png)

**Comment by Gravemind2015** [comment]
Essentially yes, new tabs on bottom. But from your particular screenshot it might look weird to go right to left:
![CamScanner 11-18-2022 13 07_1](https://user-images.githubusercontent.com/116586720/202647803-1b4c7b4a-03a5-41fc-b8d4-043fd04be291.jpg)

This was the original implementation which seems a bit more natural (although for RTL language users the above might seem more correct I guess):
![CamScanner 11-18-2022 13 07_11](https://user-images.githubusercontent.com/116586720/202647975-42781e42-4ae4-4449-bfce-eee998fceb7a.jpg)

Edit: just to add that this is purely cosmetics and just the position of new tab. Hair splitting if you will :-)

**Comment by uazo** [comment]
Your last proposal is more complicated (in terms of code intervention)

**Comment by Gravemind2015** [comment]
Oh, sorry, didn't realise it'd be hard. I was just curious if the v.106 and older implementation could be reimplemented alongside all other changes done in v.107 (basically reverting only the tab page layout behaviour).

But either way, if your proposal is easier to implement, it'll still be of great help than the current implementation in 107 where new tabs always created upwards are basically unreachable once the page is filled with older tabs. Thanks.

**Comment by uazo** [comment]
> Oh, sorry, didn't realise it'd be hard. I was just curious if the v.106 and older implementation could be reimplemented alongside all other changes done in v.107 (basically reverting only the tab page layout behaviour).

Of course! it is possible to give the user a choice, adding a new preference is simple and has no impact on maintenance

**Comment by Gravemind2015** [comment]
> Of course! it is possible to give the user a choice, adding a new preference is simple and has no impact on maintenance

Thanks again for quick reply, and yep, an option under the 'Move toolbar to bottom' (or a submenu that only shows up once this is activated) would be great to have.

**Comment by csagan5** [comment]
This whole discussion should have been in a separate issue: #2456
