### ISSUE TITLE
Unable to install from f-droid

### ISSUE THREAD

**Issue by bluebarnacles** [bromite/bromite#241]
I added the new repo URL and key fingerprint from the bromite.org site to f-droid:

https://fdroid.bromite.org/fdroid/repo?fingerprint=E1EE5CD076D7B0DC84CB2B45FB78B86DF2EB39A3B6C56BA3DC292A5E0C3B9504

E1EE5CD076D7B0DC84CB2B45FB78B86DF2EB39A3B6C56BA3DC292A5E0C3B9504

When I try to install bromite I get an f-droid error message:

Error installing Bromite
/data/user/0/org.fdroid.fdroid/cache/apks/fdroid.bromite.org--1/repo failed to verify!

**Comment by csagan5** [comment]
@bluebarnacles clear the cache of your F-Droid client

**Comment by csagan5** [comment]
@bluebarnacles you should not remove the fingerprint from the URL, it must work with the correct URL and fingerprint otherwise it is insecure

**Comment by bluebarnacles** [comment]
I entered the fingerprint in the optional fdroid repo fingerprint field, so I guess fdroid is checking it. I just wasn't able to add the repo when I entered the URL with the query string in the URL field and also entered the fingerprint in the fingerprint field.

**Comment by csagan5** [comment]
OK, it might be a bug in F-Droid client.

**Comment by luontokoodaus** [comment]
@bluebarnacles solved here: https://github.com/bromite/bromite/issues/308
