### ISSUE TITLE
Downloading page (as mhtml) not working.

### ISSUE THREAD

**Issue by bat999** [bromite/bromite#2410]
[logcat.txt](https://github.com/bromite/bromite/files/9864249/logcat.txt)
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

106.0.5249.72

### Device architecture

arm

### Android version

8.1

### Device model

Xiaomi Redmi Go

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

Downloading page (as mhtml) not working.
This is a re-hash from here --> https://github.com/bromite/bromite/issues/2076
It's a regression.
Last Known Good Build was Bromite 101.0.4951.39
Attached logcat.txt gives an output > 3000 lines, then I interrupted it.

### Steps to reproduce the bug

Visit a website...
www.bromite.org
Download the page.
Message says "Downloading file..."
But it doesn't complete.

### Expected behavior

With Chromium the message says "Downloading file..."
Then says "File downloaded"

**Comment by uazo** [comment]
for me it is not reproducible. I have also tried various templates in browserstack, but I just can't reproduce the problem.
the only thing i see abnormal in the log is
```
10-25 21:52:02.312  1233  1588 E ActivityTrigger: activityStartTrigger: not whiteListedorg.bromite.bromite/org.chromium.chrome.browser.app.download.home.DownloadActivity/1664390640
```
but I honestly don't know what it means.

in https://github.com/bromite/bromite/issues/2076 you say:

> disable automatic offline pages saving by default (thanks to uazo)

I apologise I had not seen it.
to re-establish that function, I had added a flag `offline-pages-auto-save` disabled by default:

![image](https://user-images.githubusercontent.com/29201891/198052861-639d1a2a-a901-4c19-bf2f-e7df76c4df6a.png)

try to enable it.

**Comment by bat999** [comment]
**try to enable it.**

Hi uazo
That's fixed it!

:-)

The "**offline-pages-auto-save**" flag was set to Default as you said.
When I enabled it the mhtml file downloaded OK.

So that's it...
With flag set to Default or Disabled it doesn't work.
With flag set to Enabled it does work.

Thanks for your help.
I will close the issue now.

**Comment by bat999** [comment]
Hi
**#offline-pages-auto-save** isn't listed in "New flags:" section of README.md.
(Now been fixed)

I'm not sure what this flag is supposed to do, or how to use it.
I probably don't need it.
But I do need to download mhtml files.

**Comment by csagan5** [comment]
The flag `offline-pages-auto-save` is part of the always incognito patch.
@bat999 are you in incognito mode when attempting these save operations? Is your device reporting to be online?

**Comment by bat999** [comment]
> are you in incognito mode when attempting these save operations?
**No**

> Is your device reporting to be online?
**The device is online when viewing a website and downloading the page.**

**Comment by csagan5** [comment]
I also cannot reproduce this problem; @uazo any idea why in @bat999's case it's going through `RecentTabHelper::ContinueSnapshotWithIdsToPurge()` instead of `RecentTabHelper::SavePageCallback()`?

**Comment by uazo** [comment]
> I also cannot reproduce this problem; uazo any idea why in bat999's case

How can you say that happens that?
more likely because of the changes in `RecentTabHelper::ContinueSnapshotAfterPurge`

However, I don't understand why we can't reproduce it. @bat999 can't you send a video?

**Comment by bat999** [comment]
@bat999 can't you send a video?
No

**Comment by uazo** [comment]
is a pity. 

> The device is online when I'm viewing a website and downloading the mhtml file.

the only way to reproduce what you are saying is going into offline mode before hit the download button.
But you say you don't do that...

**Comment by bat999** [comment]
> But you say you don't do that...

You think I might visit a website, then disconnect from the internet, then try to download the mhtml file?
Definitely not!

**Comment by bat999** [comment]
Hello again

I have reverted to **Bromite 101.0.4951.39** and it's working just fine.
However...
If I visit a website 
and then disconnect from the internet
and then download the mhtml file
**It works!
It works!
It works!**

So it seems that normal (previous)  behaviour is to allow dowloading mhtml files when **offline**.
(Though I have never even thought to do such a thing)

And the behaviour of Bromite 106 with the **offline-pages-auto-save flag**...
"The only way to reproduce what you are saying is going into **offline** mode before hit the download button"

That's a differentce, **online or offline** shouldn't affect the mhtml downloading function.
It should work for both, like with Bromite 101.0.4951.39.

**Comment by bat999** [comment]
Hi
Ignore what I said in my previous post.
I have inconsistent results with **Bromite 101.0.4951.39**.
It **always** downloads mhtml files Ok when **online**.
But only **sometimes** when **offline**.
So maybe those offline downloads are from **cache**.

**Comment by bat999** [comment]
@uazo
This **OfflinePagesInDownloadHomeOpenInCct** is in the chromium code...
https://source.chromium.org/chromium/chromium/src/+/main:components/offline_pages/core/offline_page_feature.cc

It is **Enabled** by default.
All your flag does is **Disable** it by default.

I think it works like this...

When flag is Enabled it automatically stores some data for every open page in a hidden cache.
To save a page as an mhtml file in the Downloads folder it downloads some more data to add to that which is already cached.
But when flag is Disabled there's nothing stored in that cache for it to use.

Or  maybe you have a better explanation...
:-S

**Comment by uazo** [comment]
> When flag is Enabled it automatically stores some data for every open page in a hidden cache.
To save a page as an mhtml file in the Downloads folder it downloads some more data to add to that which is already cached.
But when flag is Disabled there's nothing stored in that cache for it to use.

I am aware of this, but deactivating that flag does not inhibit the function called up manually by the user.
It must be something else, but the complexity of the code does not allow me to understand what it is, I would need a device like yours to verify but I do not have it available, sorry

**Comment by bat999** [comment]
>  **a device like yours to verify...**

That's OK.

I'm not **afraid** to Enable the flag in Bromite because now I know it is **normal** behaviour in Chromium.
;-)

**Comment by csagan5** [comment]
Since issue has not been fixed I will leave it open for a while longer.

**Comment by bat999** [comment]
> Since issue has not been fixed I will leave it open for a while longer.

Hi
Have I got news for you guys.
I CAN save a page as mhtml when OFFLINE!

So maybe there are two methods used...
Some devices...
Download (fresh) data from the web
And
Some devices...
Transfer (stale) data from a cache

Seems my crafty phone uses that second method.
Even though message says "Downloading" file...
It's probably only "Transferring" data from cache and storing it in an mhtml file in the Downloads folder.
https://en.wikipedia.org/wiki/MHTML

In their useful Google Chrome Help Page they do say...
"You need to be online to save a page".
https://support.google.com/chrome/answer/7343019?hl=en&co=GENIE.Platform%3DAndroid&oco=1
But that's not true for my phone (Bromite with flag Enabled).
Could be it's a CYA clause to allow for all devices.

Current situation with Bromite is...
offline-pages-auto-save DISABLED by default
Some users may NEED to ENABLE it.

Alternative could be...
offline-pages-auto-save ENABLED by default
Some users may WISH to DISABLE it.

But I would like to know...
**What is the benefit/advantage when this feature OfflinePagesInDownloadHomeOpenInCct is DISABLED?**

**Comment by csagan5** [comment]
Custom content tabs use do not use incognito, see https://bugs.chromium.org/p/chromium/issues/detail?id=1148275

So having it disabled is better from privacy perspective.

@uazo in https://source.chromium.org/chromium/chromium/src/+/main:chrome/android/java/src/org/chromium/chrome/browser/offlinepages/downloads/OfflinePageDownloadBridge.java;l=81;drc=ceb5f7a570260bf7d588af1c7f049334681f7fdb;bpv=1;bpt=1?q=offlinepagedownloadbridge&ss=chromium%2Fchromium%2Fsrc I cannot understand why it would not work when this flag is disabled. Perhaps we need logs?

However since this issue is not reproducible I might have to close it.

**Comment by bat999** [comment]
What is the benefit/advantage when this feature OfflinePagesInDownloadHomeOpenInCct is DISABLED?
> Custom content tabs use do not use incognito, see https://bugs.chromium.org/p/chromium/issues/detail?id=1148275
> 
> So having it disabled is better from privacy perspective.
> 
OK, I understand.
And with flag disabled it forces download from web and prevents transfer from cache.

My phone doesn't like that, it is designed to be thrifty.

The instruction is "Save a page from Chrome to read later".
And that's what it does, nothing about "Download a fresh page from the web to read later".

I don't mind, it's OK with me to close this.

**Comment by uazo** [comment]
>  I cannot understand why it would not work when this flag is disabled. Perhaps we need logs?

I can't tell you, I had also tried with many devices in browserstack without being able to reproduce the issue, so even with more log I don't know if we would get out of it.

**Comment by csagan5** [comment]
Ok, thanks everyone; until there is a way to reproduce this with Android Virtual Devices it will stay closed.
