### ISSUE TITLE
build error with latest 2 version patch

### ISSUE THREAD

**Issue by calvin2021y** [bromite/bromite#2422]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

106.0.5249.163

### Device architecture

arm64

### Android version

11

### Device model

galaxy s10

### Changed flags

no flags

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

NO

### Describe the bug

build stop with error:

```sh
../../chrome/browser/commerce/price_tracking/android/price_tracking_notification_bridge.cc:9:10: fatal error: 'chrome/browser/commerce/price_tracking/android/jni_headers/PriceTrackingNotificationBridge_jni.h' file not found
#include "chrome/browser/commerce/price_tracking/android/jni_headers/PriceTrackingNotificationBridge_jni.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

### Steps to reproduce the bug

1. sync to the version
2. apply patch from bromite_patches_list.txt
3. start build

The build stop work since `106.0.5249.72`,  before this version build without problem.

The `file_type_policies.h` and relate protobuf file is not generated during the process. 

### Expected behavior

expect it build without error

**Comment by csagan5** [comment]
> This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

This is not about the browser, see also https://github.com/bromite/bromite#how-to-build

You can open a discussion to get help from the community.
