### ISSUE TITLE
Privacy of Iranian users / socks 5 support 

### ISSUE THREAD

**Issue by parsemojiman1** [bromite/bromite#2426]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.
- [X] This is a feature request for the Bromite browser; not the website nor F-Droid nor anything else.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

Hello bromite developer team, i am using your browser and it has been a fantastic experience, but I'm living in Iran and there has been a heavy governmental censorship that includes blocking proxies and vpns. We need more proxy features in your app that can connect us to the free world. The most important feature we need is Socks 5 proxy support and if it's technically possible vmess, vless, Trojan and shadowsocks proxy support.
Iranians will be really thankful to your team if you make these changes in next updates.

### Describe alternatives you have considered

Supporting socks 5 , vless, vmess, Trojan and shadowsocks proxies

**Comment by csagan5** [comment]
SOCKS5 is already supported in Bromite as @arm64-v9a said, see https://github.com/bromite/bromite/wiki/ProxyConfiguration

What is missing is authentication support (for both HTTPS and SOCKS proxies).
