### ISSUE TITLE
Tab grid layout flag not working 

### ISSUE THREAD

**Issue by jollran2005** [bromite/bromite#2430]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

106.0.5249.163

### Device architecture

arm64-v8a

### Android version

12.1

### Device model

OnePlus Nord 2 5G (DN2101)

### Changed flags

smooth-scrolling
adaptive-button-in-top-toolbar-customization
parallel-downloading
tab-grid-layout
paint-preview-startup

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No.

### Describe the bug

tab grid view is enabled but isn't working. It still shows normal tab layout in tab switcher.

### Steps to reproduce the bug

1. Enable tab-grid-layout in chrome://flags
2. Relaunch bromite

### Expected behavior

Expected tab switcher to display grid view

**Comment by broot5** [comment]
I solved this by uncheck "Simplified view for open tabs" in Setting > Accessiblity
![Screenshot_20221116_012057](https://user-images.githubusercontent.com/29516943/201971870-2e6346e5-30fb-4dec-af92-57d2609cfa2d.png)

**Comment by jollran2005** [comment]
> I solved this by uncheck "Simplified view for open tabs" in Setting > Accessiblity ![Screenshot_20221116_012057](https://user-images.githubusercontent.com/29516943/201971870-2e6346e5-30fb-4dec-af92-57d2609cfa2d.png)

I can confirm this works, thanks!
