### ISSUE TITLE
White Foreground on White Background

### ISSUE THREAD

**Issue by js290** [bromite/bromite#2436]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser (not about the website, building Bromite, F-Droid or anything else).

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

106.0.5249.163

### Device architecture

arm64

### Android version

12.0

### Device model

Moto X4

### Changed flags

* `Move top toolbar to bottom`

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

When `Apply dark theme to site` is selected, elements with white backgrounds also have white foreground, which makes the foreground text unreadable.  If `Apply dark theme to site` is unchecked, then the foreground is black and viewable.

### Steps to reproduce the bug

1. Bromite Settings -> Theme -> Apply dark theme to site
2. Visit website where white background cannot be converted to black, and notice foreground text remains white rendering it invisible.

### Expected behavior

If white background cannot be inverted to black, keep foreground text as black (on white background).

### Screenshots

![Screenshot_20221106-175109_Trebuchet](https://user-images.githubusercontent.com/4715607/200199810-a674497f-4253-4496-b6b1-84356175b352.png)
![Screenshot_20221106-175008_Trebuchet](https://user-images.githubusercontent.com/4715607/200199812-f233734f-7345-4e59-a79c-51ad9b6c6929.png)

**Comment by csagan5** [comment]
> ### Changed flags
> * `Move top toolbar to bottom`

Can you reproduce this problem without this flag?

**Comment by js290** [comment]
yes:
![Screenshot_20221119-195543_Trebuchet](https://user-images.githubusercontent.com/4715607/202877783-a34a0d4b-acd1-4ccb-aec5-2c1f23e2c42a.png)

**Comment by csagan5** [comment]
Can you reproduce this with the [Chromium version provided by this project](https://www.bromite.org/chromium)?

**Comment by js290** [comment]
No, vanilla Chromium does not have `Apply dark theme to sites, when possible` option.

**Comment by csagan5** [comment]
@js290 yes, it is there but you need to enable the flag `#darken-websites-checkbox-in-themes-setting` first.

This functionality is not part of a Bromite patch, Bromite only changes the checkbox to be visible without having to toggle the flag. If you have problems with this please open a Chromium bug upstream.

**Comment by js290** [comment]
looks like a year old [bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=1274124) on Chromium.
