### ISSUE TITLE
Group Tabs

### ISSUE THREAD

**Issue by DeMoN100** [bromite/bromite#2442]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.
- [X] This is a feature request for the Bromite browser; not the website nor F-Droid nor anything else.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

no

### Describe the solution you would like

![Screenshot_20221110_010035](https://user-images.githubusercontent.com/8564572/201012690-ce21b862-dc13-4fd4-b056-37009bacdf0d.jpg)

### Describe alternatives you have considered

na

**Comment by n-buna404** [comment]
Bromite had Tab Groups. Just not by default u can enable them via
`chrome://flags/#enable-tab-groups`
