### ISSUE TITLE
User-Agent could be used to fingerprint/track users

### ISSUE THREAD

**Issue by rmtsrc** [bromite/bromite#2465]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser (not about the website, building Bromite, F-Droid or anything else).

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

107.0.5304.114

### Device architecture

arm64

### Android version

13

### Device model

Pixel 4

### Changed flags

N/A

### Is this bug about the SystemWebView?

Yes

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

By default the Bromite User-Agent is set as:

`Mozilla/5.0 (Linux; Android 13; SAMSUNG SM-G960U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36`

However, the [SAMSUNG SM-G960U aka Samsung Galaxy S9](https://en.wikipedia.org/wiki/Samsung_Galaxy_S9) can only be upgraded to **Android 10** (One UI 2.5) via an official Samsung OTA update. A custom Android 13 ROM could be used, but is unlikely.

Due to the unique unlikely combination of Android 13 being run on a SAMSUNG SM-G960U, this could make Bromite users easily trackable/fingerprintable.

(Workaround: Bromite allows the User-Agent to be manually customized to a more recent phone)

### Steps to reproduce the bug

1. Type "Whats my user agent" into Google
2. View result

### Expected behavior

User-Agent could either be set to one of the following. Making it harder to identify/track Bromite users.
- The current most popular Android phone model and the Android version that matches the latest officially supported Android version of that phone
- Remove the custom model and use the devices real model name/number

**Comment by csagan5** [comment]
> Due to the unique unlikely combination of Android 13 being run on a SAMSUNG SM-G960U, this could make Bromite users easily trackable/fingerprintable.

This is already the case due to the adblock filters, it has been discussed in the past in various issues; thanks for opening this issue, I will consider changing this or removing it altogether.

**Comment by rmtsrc** [comment]
> This is already the case due to the adblock filters

Good point this would stop some tracking, but if they're using custom made tracking that's not automatically blocked or [web server log analysis software](https://en.wikipedia.org/wiki/Web_log_analysis_software) is being used to analyze all incoming raw requests (e.g. from Apache, Nginx logs etc) then they could still assume anyone using a Galaxy S9 with Android 11 or higher is using Bromite.

**Comment by uazo** [comment]
> Making it harder to identify Bromite users.

just out of curiosity, https://github.com/PoneyClairDeLune/bromite-block
apart from that, trust me, there are plenty of ways to understand that the browser is bromite.
since we are talking about it, I would consider the opposite, i.e. to claim to be bromite

**Comment by csagan5** [comment]
> they could still assume anyone using a Galaxy S9 with Android 11 or higher is using Bromite.

Bromite does not try to hide that it is Bromite; it tries to reduce what private information is exposed while you browse the web, that's all.

> > Making it harder to identify Bromite users.
> 
> just out of curiosity, https://github.com/PoneyClairDeLune/bromite-block

There has never been any discussion about client hints here, so this is the first time I hear that the approach is wrong. Also: Bromite does not actively try to spoof itself as another browser, it is what it is: a Chromium fork. The stance is unchanged: https://github.com/bromite/bromite/wiki/Fingerprinting

**Comment by csagan5** [comment]
Fixed in `108.0.5359.75`.

**Comment by uazo** [comment]
can we discuss it? 
I don't really agree, I would have preferred then to delete the information completely rather than leave it intact.
because frankly, I don't understand what the sites could possibly need to know what device I am using if not for statistics (and fingerprinting).

**Comment by csagan5** [comment]
> can we discuss it?

Next time please raise it earlier, I mentioned that it might be removed [here](https://github.com/bromite/bromite/issues/2465#issuecomment-1321107526).

> I don't really agree, I would have preferred then to delete the information completely rather than leave it intact.

The correct model can already be detected using in a few other ways; it was replaced to make it a little more difficult to mass-harvest this information for profiling. This was never about detecting Bromite but simply about spoofing details about the user.

> I don't understand what the sites could possibly need to know what device I am using if not for statistics (and fingerprinting).

It's mostly for targeted ads and profiling in general.

**Comment by uazo** [comment]
> Next time please raise it earlier

I misunderstood the meaning of 'remove'

> The correct model can already be detected using in a few other ways

any examples? would be things to make disappear.
as far as I know, what they can detect the device's features, but not the model. for example, if it has the dual screen or dual camera, but not the model directly.
I would also be in favour of not displaying the amount of memory/cpu/storage, but it has nothing to do with this issue.


> It's mostly for targeted ads and profiling in general.

precisely.

**Comment by csagan5** [comment]
> > The correct model can already be detected using in a few other ways
> 
> any examples? would be things to make disappear. as far as I know, what they can detect the device's features, but not the model. for example, if it has the dual screen or dual camera, but not the model directly. I would also be in favour of not displaying the amount of memory/cpu/storage, but it has nothing to do with this issue.

With WebGL enabled it is possible to brute-force the model of GPU silicon; without that one can use display resolution, memory, CPU and perhaps some other detail to figure it out.

The best we can do for this is re-introducing the spoofing as it was originally, one model for each Android version, to be a bit more realistic, but it's not worth much.

Returning empty string or an exception seems like a worse option to me.

**Comment by uazo** [comment]
> Returning empty string 

I would do this instead. brave also [does](https://github.com/brave/brave-core/blob/master/chromium_src/content/common/user_agent.cc) this.
brave removes also the android version, although, from memory, it can be obtained anyway by checking the list of available codecs

**Comment by csagan5** [comment]
Wouldn't returning the AVD model be marginally better in this case? Although some sites might use that as a signal of malicious intents.

**Comment by uazo** [comment]
> Wouldn't returning the AVD model be marginally better in this case? 

some examples?
anyway, why so much trouble? we don't lie, we just don't say it. Are you worried that some sites are no longer working?

**Comment by csagan5** [comment]
> anyway, why so much trouble? we don't lie, we just don't say it. Are you worried that some sites are no longer working?

I am not worried and I am not going to rush this either.
Each change must have some valid rationale behind it and it must be documented in each patch.

In the past Bromite has used a different model based on the Android version. Other alternatives are to hide the Android version as well.

**Comment by Universalizer** [comment]
(Deleted)

**Comment by csagan5** [comment]
@Universalizer you can use discussions, this issue is closed and would not have much visibility anyways

**Comment by csagan5** [comment]
> There has never been any discussion about client hints here, so this is the first time I hear that the approach is wrong. Also: Bromite does not actively try to spoof itself as another browser, it is what it is: a Chromium fork. The stance is unchanged: https://github.com/bromite/bromite/wiki/Fingerprinting

Related past discussions:
* #1830
* #973

**Comment by Universalizer** [comment]
To @csagan5, cross-reference in new discussion ?,

Just let me inform you, I'm on SDK 29, My custom override user-agent is working absolutely fine.

**Comment by ale5000-git** [comment]
Isn't possible to remove the Android version, have a list of devices and return a random device name from the list every time?
