### ISSUE TITLE
Consider kPermuteTLSExtensions

### ISSUE THREAD

**Issue by uazo** [bromite/bromite#2467]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.
- [X] This is a feature request for the Bromite browser; not the website nor F-Droid nor anything else.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

N/A

### Describe the solution you would like

we should consider whether to activate that flag

>The TLS protocol used for HTTPS begins with a ClientHello message. This message contains a set of extensions. Using a fixed extension order can encourage server implementers to fingerprint Chrome and then assume specific implementation behavior. 

https://chromestatus.com/feature/5124606246518784

it should be checked whether the [JA3 value](https://github.com/salesforce/ja3) changes with that flag.
example `https://tls.incolumitas.com/fps?all=1` **caution: do not follow that link!**

### Describe alternatives you have considered

N/A

**Comment by csagan5** [comment]
Sounds interesting but in case of problems I expect that it would be very difficult to understand what's going on because on each reload behaviour could be different.

**Comment by uazo** [comment]
if you agree, I would start by putting it in `chrome://flags`, then we'll see.

**Comment by uazo** [comment]
Some info on https://tlsfingerprint.io/
Chromium intent to ship on v110 https://chromestatus.com/feature/5124606246518784
Mozilla positive https://github.com/mozilla/standards-positions/issues (709)

**Comment by csagan5** [comment]
> if you agree, I would start by putting it in `chrome://flags`, then we'll see.

Sure.

**Comment by csagan5** [comment]
I am going to enable this by default on next release; I can also add the flag so that it can be disabled.

**Comment by uazo** [comment]
if you can do it, it's better for me for now. I think about the other changes you asked for.

**Comment by csagan5** [comment]
Fixed in `108.0.5359.75`.

There is no flag for it but it can be easily added later.

**Comment by uazo** [comment]
I realised that if the proxy is configured, that flag has no effect.
It is not a bug, but it is correct because the websites do not see the (bromite) packet as it passes through the proxy.
it's probably something to write in the wiki.

**Comment by csagan5** [comment]
There is only a feature but not an user-reachable flag; what should be mentioned in the wiki? That using a proxy does not permute TLS extensions? Why is that though? The proxy is not doing MiTM.

**Comment by uazo** [comment]
> Why is that though?

The intention of permuting extensions order is to minimise TLS fingerprinting at the network level, which is negated if a proxy is used that does not have extension permutation.
