### ISSUE TITLE
Apply cosmetic filtering (to hide empty white spaces) when blocking ads

### ISSUE THREAD

**Issue by Riotous** [bromite/bromite#247]
**Is your feature request related to privacy?**
No, this is cosmetic. 

**Is there a patch available for this feature somewhere?**
Kiwi Browser currently implements cosmetic filtering when blocking ads to avoid too much whitespace after blocking ads. Source code is below. I'd be more specific but I'm not knowledgeable enough to point to the specific patch in the code.
https://github.com/kiwibrowser/android

**Describe the solution you'd like**
I'd like a solution that fills in as much blank space that is left over after blocking ads. It makes for a much better browsing experience when you only scroll through things you want to read instead of large sections of empty space. 

**Describe alternatives you've considered**
I haven't considered any alternatives. I just think cosmetic filtering is nice to have to supplement adblocking.

**Comment by Bluscream** [comment]
Possible alternative: cat GIFS

**Comment by csagan5** [comment]
> Source code is below. I'd be more specific but I'm not knowledgeable enough to point to the specific patch in the code.
> https://github.com/kiwibrowser/android

Kiwi is not open source, see also https://github.com/kiwibrowser/android/issues/12

**Comment by Riotous** [comment]
@csagan5 Sorry, I didn't know about that dev doing things that way. I guess the next best place to look is uBlock Origin?
https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters

**Comment by csagan5** [comment]
@Riotous uBlock Origin is an extension, Chromium/Bromite are written in C++ and Java. The adblock engine is written in C++.

Feel free to develop a patch for this, but I have no intention to develop any as I estimate it would require some major rework of the adblock engine.

**Comment by Bluscream** [comment]
Wow, you really have no humor 🤦‍♂️
