### ISSUE TITLE
Add option to disable Screen Security for Always Incognito mode

### ISSUE THREAD

**Issue by mariobrostech** [bromite/bromite#2476]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.
- [X] This is a feature request for the Bromite browser; not the website nor F-Droid nor anything else.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

I'm not sure if there's an existing patch available for this feature.

### Describe the solution you would like

I'd like a solution which allows the user to disable Screen Security while using the "Always open links in incognito" setting in Bromite.

While Screen Security is a great feature to prevent OS-level and application-level spying of webpage contents, many people that use Always Incognito mode do so to prevent websites from storing data persistently. Many of these users have reasonably secure ROMs and applications running on their devices, and Screen Security in these settings just serves as a nuisance when trying to take screenshots of webpages or share their contents without using links.

This feature should be disabled by default and should serve as a supplement to the existing Incognito Mode settings that similarly compromise some privacy for the sake of convenience. This still provides far better security and privacy than not using Always Incognito mode at all (which is the current alternative; see the next section for more info).

### Describe alternatives you have considered

I have considered disabling browser history and using the browser in non-incognito mode; however, this still allows persistent storage of site data. I would prefer to keep Always Incognito mode activated and have a toggle that could allow me to continue to share my screen or take screenshots with Bromite open.

**Comment by daankata** [comment]
There is a flag available at `chrome://flags` called **#incognito-screenshot** which enables screenshots for incognito mode.

**Comment by mariobrostech** [comment]
Thanks for pointing this out! I had no idea this was a flag in Chrome's settings. That toggle doesn't just appear to enable screenshots; it also disables Screen Security by making incognito windows visible in the multitasking view. Is there any way this can be incorporated into a Bromite settings toggle, similar to one I'm describing in my issue, or would that be considered out-of-scope?

**Comment by csagan5** [comment]
> That toggle doesn't just appear to enable screenshots

It enables screenshots while in incognito mode; if this is not working and you can reproduce it please open a separate issue.



> it also disables Screen Security by making incognito windows visible in the multitasking view

This is how Android works.



> Is there any way this can be incorporated into a Bromite settings toggle, similar to one I'm describing in my issue

The feature already exists; it cannot be hidden from the multitasking view, see above.

I am closing this because there is no feature to implement; feel free to reply otherwise.

**Comment by mariobrostech** [comment]
Hi @csagan5,

I think you may have misunderstood my reply. I was trying to say that the Chrome flag pointed out to me does exactly what I'm asking for. My suggestion was to add an option to Bromite's Incognito Mode settings that simply acts as a user-facing toggle to enable or disable the flag for users that don't know it exists or otherwise wouldn't want to mess with browser flags themselves.

Thanks again for your consideration!

**Comment by csagan5** [comment]
I see; it would indeed be nicer but we have a lot of flags and maintaining them as preferences requires more work as well. Until a decision is made about that I prefer to keep them as-is.


> * I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)

All existing flags introduced in Bromite are documented in the README.

**Comment by mariobrostech** [comment]
I completely understand that. Thanks again for looking into this!
