### ISSUE TITLE
Suggestion: Remove Political Bookmarks

### ISSUE THREAD

**Issue by neo-neo1** [bromite/bromite#2479]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.
- [X] This is a feature request for the Bromite browser; not the website nor F-Droid nor anything else.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

Removable political links are baked into Bromite when opening new tabs. This is intrinsically a slippery slope on political premises. Moreover, this goes against the ethos this browser represents - or so I thought. 

### Describe alternatives you have considered

N/A

**Comment by netty0** [comment]
Good point. It's ethical decisions like these which ultimately can act as a catalyst for forks.

**Comment by neo-neo1** [comment]
Unfortunate when a project based on "privacy and freedom" becomes injected with political virtues. I have no choice but to delist this browser from a highly trafficed open source listing. This projects description is misrepresented and co-opted by personal polity. If do happen to reverse your decision, kindly let me know.
