### ISSUE TITLE
Unable to log into Github with Bromite

### ISSUE THREAD

**Issue by shrimprugbysnowowl** [bromite/bromite#2483]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser (not about the website, building Bromite, F-Droid or anything else).

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

108.0.5359.106

### Device architecture

arm64

### Android version

13

### Device model

Google Pixel 4a

### Changed flags

Enabled incognito-screenshot

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

Something appears to not allow a successful login to Github following the correct entry of credentials. Instead of a prompt from Github for an emailed 2FA code, the result is given in the screenshot below.

![Screenshot_20221203-125552](https://user-images.githubusercontent.com/59341190/205457300-46010cc3-44b0-46d4-b2e7-c6aee9e7db37.png)

Disabling Bromite's adblocking did not change the result.

This issue is not present when logging in using a different browser, such as Vanadium for example, with the same network configuration.

I have experienced this issue in the previous version of Bromite as well but waited for the latest update.

### Steps to reproduce the bug

Visit https://github.com/login using the latest version of Bromite and enter proper credentials.

### Expected behavior

Successful login or prompt for 2FA code emailed from Github.

**Comment by rowboatz** [comment]
Have you disabled the HTTP refferer in settings? If yes, try with it enabled.

I think it is the culprit here, however I'm not sure what can be done to solve this issue if anything since that toggle is probably not standard at all.

**Comment by shrimprugbysnowowl** [comment]
Yep! That was it. I was able to log in with Bromite this time.

Are there any security or privacy concerns with leaving that setting enabled?

**Comment by rowboatz** [comment]
[Here's some information](https://developer.mozilla.org/en-US/docs/Web/Security/Referer_header:_privacy_and_security_concerns).

The security and privacy implications of leaving the refferer header enabled are probably quite insignificant in practice.

**Comment by uazo** [comment]
> The security and privacy implications of leaving the refferer header enabled are probably quite insignificant in practice.

bromite, with that option active, actually does not pass the referrer only when navigating is between different top sites, which does not allow the target site to know who opened it via this method.
it is already [planned](https://github.com/bromite/bromite/issues/2397#issuecomment-1323219332) to change that option to make it more understandable

**Comment by shrimprugbysnowowl** [comment]
Excellent, thank you both, @rowboatz and @uazo, for the additional info as well. The issue that I described initially has been resolved. Appropriate to close?
