### ISSUE TITLE
Allow Incognito Tabs to be closed on exit

### ISSUE THREAD

**Issue by stantios** [bromite/bromite#2484]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.
- [X] This is a feature request for the Bromite browser; not the website nor F-Droid nor anything else.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

I would like it so when you exit the app, all the tabs close so they don't stay per browsing session. This is already implemented with normal tabs with the option 'Close all tabs on exit' but this option doesn't work with incognito tabs which is annoying.

### Describe alternatives you have considered

Make a button / toggle in the 'Incognite Mode settings where you can say of you want Incognito Tabs to be closed upon exiting the app.

**Comment by uazo** [comment]
>  Make a button / toggle in the 'Incognite Mode settings where you can say of you want Incognito Tabs to be closed upon exiting the app.

I don't understand, the incognito tabs are already not retained when the application is restarted. 
could you indicate the steps to reproduce?

**Comment by SynapseScribe** [comment]
for me bromite is crashing when searching anything via search bar. v108.0.5359.75
was not crashing before

this happens if always on incognito mode is enabled.

later edit: updating to last version, fixed it for me

**Comment by bat999** [comment]
> for me bromite is crashing when searching anything via search bar. v108.0.5359.75 was not crashing before
> 

Current version is v108.0.5359.106
Try it

**Comment by stantios** [comment]
> > Make a button / toggle in the 'Incognite Mode settings where you can say of you want Incognito Tabs to be closed upon exiting the app.
> 
> I don't understand, the incognito tabs are already not retained when the application is restarted. could you indicate the steps to reproduce?

No history is kept but I keep getting the notification 'Close all Incognito tabs' even though Bromite is fully closed.

**Comment by csagan5** [comment]
> No history is kept but I keep getting the notification 'Close all Incognito tabs' even though Bromite is fully closed.

That is a bug in upstream Chromium, it is not a feature request for Bromite.
