### ISSUE TITLE
compile inside ROM

### ISSUE THREAD

**Issue by ort163** [bromite/bromite#249]
I tried to replace the apk inside
`https://github.com/LineageOS/android_external_chromium-webview/tree/lineage-16.0/prebuilt/arm`
by the correct 
[arm apk](https://www.bromite.org/system_web_view
)
Compile the ROM.

Does this mean I am running a proper Bromite System Web View? Sorry to ask support in bug report.
Thanks

**Comment by csagan5** [comment]
You should ask in LineageOS forums/reddit, here it is about Bromite, I have no idea.
