### ISSUE TITLE
Default search engine gets geolocation permissions by default

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#250]
**Bromite version**

Version: `72.0.3626.108`
Arch: `x86`
Android version: any

**Is the bug reproducible with latest version?**
Yes

**Describe the bug**
A fresh install of Bromite has the DSE (default search engine) permissions, in particular geolocation, allowed by default.

Hinted at in #246

**Comment by csagan5** [comment]
Fixed in `72.0.3626.114` (not yet released).

**Comment by exv3** [comment]
Same issue with `ARM` (`72.0.3626.114`)

https://imgur.com/a/FGyps3K

**Comment by csagan5** [comment]
@exv3 that will not happen on a new installation, it is authorised only because it was already previously (either manually or by a previous version)

**Comment by exv3** [comment]
I can confirm, it's blocked by default after I reinstalled Bromite

Thanks and keep up good work!
