### ISSUE TITLE
Unable to change download location

### ISSUE THREAD

**Issue by Enkidu70** [bromite/bromite#2526]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser (not about the website, building Bromite, F-Droid or anything else).

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

v108.0.5359.156

### Device architecture

arm64

### Android version

13

### Device model

OnePlus 8T (KB2003)

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No.

### Describe the bug

In README.md, there is written "allow changing default download storage location". But I am not able to.

I have a similar problem like written at https://github.com/bromite/bromite/discussions/1814#discussioncomment-2221890 by @Spider19996.<br>(I granted all permissions to access media.)

Currently downloads are just stored in <_my storage_>/Download and I am not able to change that folder.<br>
(Many other apps are able to store in a selectable folder.)

Tnx in advance.

### Steps to reproduce the bug

1. Set Bromite to ask download folder every time
2. Download something, e.g. https://f-droid.org/F-Droid.apk
3. Try to change download location. Here it only looks like:

![grafik](https://user-images.githubusercontent.com/1456895/210079631-5f2ff41f-a1e4-45ae-9bba-a6c905c0dda1.png)

### Expected behavior

The standard SAF dialog to grant access to a certain folder, e.g. <_my storage_>/Download.

**Comment by csagan5** [comment]
You can choose between SD card and internal storage, there is no specific folder choice. It has always been like this, also in Chromium.
