### ISSUE TITLE
Not an issue, just a question: Why does Bromite need to be installed as both a system app and a user app?

### ISSUE THREAD

**Issue by AnonVendetta** [bromite/bromite#253]
I don't see any way to post a question without posting an issue, so apologies for that.

Anyway, other webview packages function fine when installed only as a system app. Even with Google's Android System WebView, it can be updated via standalone APK or Play Store, but there is no *NEED* to update, it still is fully functional.

So, why does Bromite need to be installed twice? I'm sure there is a technical explanation for this besides "just do it because that's the way it is", I'd like to hear it. I love the technicalities of things.

Thanks!

**Comment by csagan5** [comment]
> I don't see any way to post a question without posting an issue, so apologies for that.

That is on purpose, the issue template is not optional. You can ask your question on Reddit or XDA.

**Comment by DragoCubed** [comment]
Would be nice if that were in the readme
