### ISSUE TITLE
Invalid certificate at domain fdroid.bromite.org

### ISSUE THREAD

**Issue by xwosch** [bromite/bromite#255]
Follow https://fdroid.bromite.org/fdroid/repo?fingerprint=E1EE5CD076D7B0DC84CB2B45FB78B86DF2EB39A3B6C56BA3DC292A5E0C3B9504

and get an error: certificate common name is invalid(Subject is *.netlify.com not fdroid.bromite.com)

**Comment by csagan5** [comment]
You have some DNS cache problem.
