### ISSUE TITLE
Continue playing video after screen lock.

### ISSUE THREAD

**Issue by AnimeAnalPRO** [bromite/bromite#2558]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser (not about the website, building Bromite, F-Droid or anything else).

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

Bromite v108.0.5359.156 WebView

### Device architecture

arm64-v8a

### Android version

12.0

### Device model

Poco X3 PRO MiUI 13.0.8.0

### Changed flags

-

### Is this bug about the SystemWebView?

Yes

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

Using the Via browser shell when watching videos on Youtube or other sites, the video continues to play with the sound with the screen locked. This error does not appear on the native SystemWebView.

### Steps to reproduce the bug

Turn on any video and lock the screen.

### Expected behavior

Maybe this error is the correct operation of BromiteWebView. If this is true, it may release a Magisk module to disable such a function.

### Screenshots

-

**Comment by n-buna404** [comment]
Tested and this is reproducible since I use this fairly evenly.
Well if the contributor needs second opinion. I personally think that this bug/feature (background playback) is useful for me.
Youtube even charge premium for this feature.
The best case for both world if this can be toggle on or off via flags.

**Comment by AnimeAnalPRO** [comment]
> Tested and this is reproducible since I use this fairly evenly. Well if the contributor needs second opinion. I personally think that this bug/feature (background playback) is useful for me. Youtube even charge premium for this feature. The best case for both world if this can be toggle on or off via flags.
-
I forgot to add that if you go back to the previous page with the "back" button during the video playback, the sound from the video will also be played. Yes, the function is useful, but I would like it to be optional

**Comment by n-buna404** [comment]
For the second one, I cannot reproduce that. When I press back and page go to back to a previous page with video. There is no sound just the previous video media playback key will appear for short while then disappear (maybe because autoplay is blocked?). 

> I forgot to add that if you go back to the previous page with the "back" button during the video playback, the sound from the video will also be played. Yes, the function is useful, but I would like it to be optional

**Comment by AnimeAnalPRO** [comment]
> For the second one, I cannot reproduce that. When I press back and page go to back to a previous page with video. There is no sound just the previous video media playback key will appear for short while then disappear (maybe because autoplay is blocked?).
> 
> > I forgot to add that if you go back to the previous page with the "back" button during the video playback, the sound from the video will also be played. Yes, the function is useful, but I would like it to be optional
-
As for the latter, it may depend on the site.

**Comment by theFireProject** [comment]
> ## Features not related to privacy
> * ...
> * allow playing videos in background tabs and disable pause on switching tabs

This is not a bug. The feature is mentioned in the [README](https://github.com/bromite/bromite#features-not-related-to-privacy).

Background playback is extremely useful. Some platforms like YouTube block background playback on smartphones (on the website and in the app). This way you can bypass that restriction.
