### ISSUE TITLE
Update Please

### ISSUE THREAD

**Issue by blogmangit** [bromite/bromite#2564]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.
- [X] This is a feature request for the Bromite browser; not the website nor F-Droid nor anything else.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

Please Update. 

### Describe alternatives you have considered

No Alternative Considered.

**Comment by HarriBuh** [comment]
Since the lack of an update is a security risk and Bromite is just the best and most secure Chrome Browser out there, I second this.

**Comment by Universalizer** [comment]
**Good to quote as “Excellent or All-excellent (Best of all) or Finest or Outstanding browser”**

My personal view ; opinion / suggestion (optionally).

**Comment by HarriBuh** [comment]
Still nothing, it's getting ridiculous. Any other FOSS browser or Chromium based browsers with focus on privacy you would recommend? I tried Mull (Firefox based), but it's slow af and Privacy Browser, which is quite uncomfortable to handle.

**Comment by leacha69** [comment]
https://github.com/macchrome/droidchrome / https://chromium.woolyss.com/

**Comment by drk002** [comment]
Brave

**Comment by HarriBuh** [comment]
Brave is too bloated and still has no option for "always incognito mode" or "clear cache on exit" mode. I've just ended my trail of the latest version. What I can recommend is @leacha69 's great mention called "droidchrome". It is very similar to Bromite in terms of privacy options and even uses Bromite's ad blocking dat-file. Tbh, it actually seems more like a fork of Bromite itself lol.

**Comment by blogmangit** [comment]
> https://github.com/macchrome/droidchrome / https://chromium.woolyss.com/
> 

no extension support right ?

**Comment by HarriBuh** [comment]
Correct.

**Comment by MetaApo13** [comment]
> Brave is too bloated and still has no option for "always incognito mode" or "clear cache on exit" mode. I've just ended my trail of the latest version. What I can recommend is @leacha69 's great mention called "droidchrome". It is very similar to Bromite in terms of privacy options and even uses Bromite's ad blocking dat-file. Tbh, it actually seems more like a fork of Bromite itself lol.

Their github repo seems to have very little in the way of a description. Is it really a fork of bromite? Has it been modified in any way that alters the original features (visible as well as behind the scenes) of bromite? Only a readme is present in the code section.

**Comment by uazo** [comment]
![image](https://user-images.githubusercontent.com/29201891/217743309-ab8e3a4e-1fac-4ff1-898c-094fc0bae06d.png)

that's my repo.
if you really want to use it, use it directly from https://github.com/uazo/bromite-buildtools/releases

> Is it really a fork of bromite?

Yes. With all of csagan5's modifications and in addition a few of my own being tested.

> Has it been modified in any way that alters the original features 

If you mean malicious code, no, there is obviously no such thing, apart from bugs.

**Comment by Dunge** [comment]
Yeah it's been over a month now since Bromite show that vulnerable outdated version warning? I honestly thought this project was more popular than that, surprising nobody seems to bother. Is the development abandoned?

And sorry to the commenters above, but for something as important as my main web browser I would prefer not to use an experimental fork by some random user with just a few downloads, I kinda expect to use a browser that has been properly vetted by third parties and used by thousands of people.

**Comment by HarriBuh** [comment]
@Dunge Understandable, but do you really think uazo is a "random user"? That doesn't fit reality 😂

**Comment by HarriBuh** [comment]
@uazo But why should a replace a stable (-looking) version of (your) Droidchrome browser with another one (of yours) that has been labeled as "test version"? Are they both on the same level of development?

**Comment by HarriBuh** [comment]
@uazo Are you talking about Droidchrome or your very own fork mentioned above? I'm kinda confused now 🥲

**Comment by uazo** [comment]
I don't know what Droidchrome is, I'm not connected to that user at all, that's not my repo. Just so you know. Then, as far as I'm concerned, you can install whatever you want.

**Comment by MetaApo13** [comment]
This is a pleasant surprise. Being a rather popular project, I felt it to be a bit weird that I couldn't find a better maintained bromite fork. Thanks to @uazo for their work in sustaining bromite as a chromium browsing option. The test version is much appreciated.

**Comment by EverEve** [comment]
Hello, is there any schedule for next update? I think we are 2 months away from the last Chromium updates.
Thanks.

**Comment by HarriBuh** [comment]
Looks like csagan5 stepped down completely, for whatever reason. I would advice you to start looking for alternatives, like uazo's own Bromite fork, @EverEve

**Comment by ghost** [comment]
Sweet uazo - big thanks for your fork! Do you plan on releasing ARM 32bit version? Some of them older tablets needs Bromite (110+) protection!

**Comment by EverEve** [comment]
Sorry, is it possible to set autoupdate from this latter repository or will I have to periodically check and download the apk?

Thanks

**Comment by ghost** [comment]
> Sorry, is it possible to set autoupdate from this latter repository or will I have to periodically check and download the apk?
> 
> Thanks

Also wondering this, definetly switching to the @uazo version if it can "auto update" (the notification that appears) like the standard version :)

**Comment by Dunge** [comment]
I believe most users using the application got it via F-Droid  and are waiting for this repo to receive updates. I doubt uazo will be able to take ownership?

**Comment by eskimododo** [comment]
Tried uazo test builds, not really stable. Suggest u guys hold off for a while n wait for stable release from uazo.

**Comment by EverEve** [comment]
In the meanwhile I have switched to Via Browser (on the Play Store).

**Comment by SkewedZeppelin** [comment]
@EverEve Via browser is a WebView browser with [trackers](https://reports.exodus-privacy.eu.org/en/reports/mark.via.gp/latest/) from [Verzion](https://reports.exodus-privacy.eu.org/en/trackers/25/) in it, it is the complete opposite of what Bromite is.

Furthermore because it depends on the system WebView, if you're on stock Android you're literally using the Google Chrome WebView provider with all of its telemetry.

Not to mention how the WebView widget is meant to add web content to an app, not create a full browser and is fundamentally limited in that it cannot provide any per-site process or data isolation or disable privacy breaking features like WebRTC.

**Comment by EverEve** [comment]
@SkewedZeppelin Thanks, I have an old phone (modded with Lineage OS) and need a lightweight browser to browse those 5 or 6 websites I need to check while I am away from the PC. 
If you have a good alternative to suggest, I will happily try it.

**Comment by uazo** [comment]
build bromite for arm32 is easy if you have an average linux machine, unfortunately due to a issue in sysbox, my ci does not support it.

> version if it can "auto update" (the notification that appears) like the standard version :)

Of course I could, but I don't because I'm hoping for some communication from carl, getting to that would mean losing hope.
And then bromite is the result of Carl's work, it is not my intention to override him.

> Tried uazo test builds, not really stable.

I'm glad you tried it. if you detect instability you are welcome as a [reporter](https://github.com/uazo/bromite-buildtools/issues).

**Comment by melohr** [comment]
I rely heavily on bromite browser and WebView on multiple devices from the f-droid build and would therefore love to see this great project stay alive (and as is).
There was a similar situation with the owncloud/nextcloud bookmark app (https://gitlab.com/bisada/OCBookmarks) which had a handover to another main maintainer without breaking the f-droid build chain. Perhaps this could be a viable way also here.

But as updates kept coming quick and regular up to mid December, perhaps there are other reasons why he's not active anymore (accident, etc.). If so, let's hope it's not serious and he gives a sign of life soon!

**Comment by salad612** [comment]
Brave actually does have an option to clear data and cache on exit, the only issue is you have to press exit in the menu instead of just closing it. As for the bloat, it takes some changed in settings but you can get rid of most of it

**Comment by csagan5** [comment]
> https://github.com/macchrome/droidchrome / https://chromium.woolyss.com/

The former has used Bromite's patches in the past (probably still does) and never released any source code; the latter never replied about this problem and still hosts binary-only releases.

Closing as this should have been a discussion, not a feature request.
