### ISSUE TITLE
Fix a 0-day by rebuilding

### ISSUE THREAD

**Issue by Madis0** [bromite/bromite#257]
**Is your feature request related to privacy?**
Yes.

**Is there a patch available for this feature somewhere?**
Upstream.

**Describe the solution you'd like**
Google has announced that the latest Chromium has received a hotfix for a 0-day bug. ([1](https://chromereleases.googleblog.com/2019/03/stable-channel-update-for-desktop.html), [2](https://chromereleases.googleblog.com/2019/03/chrome-for-android-update.html)). Although Bromite is already on 73, I don't know whether it is fixed on the current build, so a rebuild based on latest would be appreciated.

**Describe alternatives you've considered**
N/A

**Comment by ouzowtf** [comment]
https://forum.xda-developers.com/android/apps-games/app-bromite-chromium-plus-adblocking-t3687258/post79056854

**Comment by Madis0** [comment]
Thanks.

**Comment by csagan5** [comment]
> Bromite is already on 73, I don't know whether it is fixed on the current build, so a rebuild based on latest would be appreciated.

Learning how to verify whether it is patched or not by yourself would be appreciated :wink: You should not trust other people for this if you really care about it.
