### ISSUE TITLE
Block Page Redirections to unwanted sites which is very bothering. 

### ISSUE THREAD

**Issue by GET100PERCENT** [bromite/bromite#2572]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.
- [X] This is a feature request for the Bromite browser; not the website nor F-Droid nor anything else.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

I am not sure , but in ublock origin extension is added enabled, the problem vanishes both in Firefox and kiwi browser next. 
Below are some screenshots of the redirected sites which doesn't seem to be good for privacy reasons. 
![chrome_screenshot_10 Feb 2023 08_58_50 GMT+05_30](https://user-images.githubusercontent.com/116144024/217993642-9177dd1d-c390-4bd0-862b-24e346075cdb.png)
![chrome_screenshot_10 Feb 2023 08_58_10 GMT+05_30](https://user-images.githubusercontent.com/116144024/217993659-f56edd21-7a90-4ae6-85c2-05a85c9683b2.png)

### Describe the solution you would like

I think , It can be implemented in bromite ads filter.

### Describe alternatives you have considered

If ublock origin extension is added to bromite , the page Redirections will not happen.
In firefox with ublock origin,  pages are not being automatically redirected to an unwanted site, when the same link is pressed.

**Comment by Disqu3-mirOir-qt** [comment]
Bromite support userscript 

// ==UserScript==
// @name Block Popups and Redirects
// @namespace https://www.example.com/
// @version 0.2
// @description Block popups and redirects on any web page
// @author Your Name
// @match *://*/*
// @grant none
// ==/UserScript==

window.addEventListener('beforeunload', function(e) {
  e.preventDefault();
  e.returnValue = '';
});

var oldOpen = window.open;
window.open = function() {
  return null;
};
