### ISSUE TITLE
Update? 

### ISSUE THREAD

**Issue by ghost** [bromite/bromite#2575]
Is the project dead or paused? The App warns me im using an old Version and no update so far... 

Would be nice if someone could tell me whats going on.

And thx for the great work so far

**Comment by UnlimitedCookies** [comment]
It's daily business. Once Bromite falls behind the current chromium stable version they warn you that you might be susceptible to security bugs that have been publicized and fixed in chromium, but not yet in Bromite.

Last activity was about 2 weeks ago, so I wouldn't say that the project is dead.

But what concerns me a little is that the F-Droid repo is not reachable. At least F-Droid threw a warning at me saying that it couldn't fetch the current release file.

**Comment by ghost** [comment]
> 

I think i wrote somewere that one of the Developers quit the Project. Don't remember where

**Comment by DKB-91** [comment]
If you don't mind some slight instability (I had crashes on changing some settings, but no on browsing, then again I don't log in with Bromite), I recommend Uazo's test builds if you want to use an updated but still beta version of Bromite.

https://github.com/uazo/bromite-buildtools

Aside crashes when fiddling with settings and lists with his new built in Adblock and IIRC a crash when changing timezones and browser language, it works like a charm when browsing the web, at least for me.

(Sorry if I got something wrong English isn't my first language)

It's one way to use Bromite while on the latest chromium version until the main project gets updated up to speed.

**Comment by ghost** [comment]
> If you don't mind some slight instability (I had crashes on changing some settings, but no on browsing, then again I don't log in with Bromite), I recommend Uazo's test builds if you want to use an updated but still beta version of Bromite.
> 
> https://github.com/uazo/bromite-buildtools
> 
> Aside crashes when fiddling with settings and lists with his new built in Adblock and IIRC a crash when changing timezones and browser language, it works like a charm when browsing the web, at least for me.
> 
> (Sorry if I got something wrong English isn't my first language)
> 
> It's one way to use Bromite while on the latest chromium version until the main project gets updated up to speed.

Ahhh thx very much

**Comment by towfikomar** [comment]
![Uploading Screenshot_2023-02-19-10-48-23-54_bf5286d428c97f865e4b51a5afbaefcd.jpg…]()

**Comment by towfikomar** [comment]
![Screenshot_2023-02-19-10-48-23-54_bf5286d428c97f865e4b51a5afbaefcd](https://user-images.githubusercontent.com/114739840/219922873-625b9b57-48a7-48ab-972a-0b7f5bf13b6f.jpg)

**Comment by csagan5** [comment]
> But what concerns me a little is that the F-Droid repo is not reachable.

It will be restored probably on Monday.

> I think i wrote somewere that one of the Developers quit the Project. Don't remember where

Nobody quit anything.

**Comment by ghost** [comment]
> > But what concerns me a little is that the F-Droid repo is not reachable.
> 
> It will be restored probably on Monday.
> 
> > I think i wrote somewere that one of the Developers quit the Project. Don't remember where
> 
> Nobody quit anything.

Ahhhh okay thx for the reply

**Comment by nad0vs** [comment]
> > But what concerns me a little is that the F-Droid repo is not reachable.
> 
> It will be restored probably on Monday.
> 
> > I think i wrote somewere that one of the Developers quit the Project. Don't remember where
> 
> Nobody quit anything.

Man, I was worrying my heart out over the fdroid thing, am setting up a phone for GF and it kept not working out 

Glad to hear everything is fine and the repo is being restored.
