### ISSUE TITLE
Share Vector Browser Icon

### ISSUE THREAD

**Issue by scribblemaniac** [bromite/bromite#258]
**Is your feature request related to privacy?**
No

**Is there a patch available for this feature somewhere?**
No

**Describe the solution you'd like**
Could you please share the new icon for Bromite in a format like svg? Based on the criteria for #120, it seems like you should have this already, but I can't find it anywhere on this or the Github Pages repository*. This would be very useful for anyone that wants to feature Bromite, and you would be able to use it to fix the blurry images in the README and on the official website.

**Describe alternatives you've considered**
Sharing the VectorDrawable used for the launcher icon would also be a good start and would be at least sufficient for my needs, although it would not fix the issues mentioned above.

*Maybe you have some of this up, but I've searched around quite a bit and have been unable to find any of these resources aside from the favicon-related pngs used for the website. Some pointers would be helpful if a better version is online somewhere.

**Comment by csagan5** [comment]
I am sorry, but this is not a bug or a feature request, and the icon is not shared to discourage the release of spoofed versions.

Most people interested into this want to either create a customised version of Bromite or a malicious version, which are both detrimental for this open source project.

You are allowed to use all the patches released under GPLv3 but you do not need to brand it as Bromite to use the patches.

**Comment by scribblemaniac** [comment]
That's just silly. Anyone capable of applying your patches and compiling the code is capable of extracting the resources from your apk releases. And any capable designer could copy your logo in a matter of minutes too. The only people you're hindering are a) the people viewing your website and b) the people who want to reference your application (ex. in blogs or lists) but don't have either of the aforementioned skills.

If this was such a deterrent, you would see other open source browser doing this, but they're not. Most of them either have svgs available as a press package or in their source, or at the very least bitmap images that match the size they are displayed at.

**Comment by csagan5** [comment]
> Anyone capable of applying your patches and compiling the code is capable of extracting the resources from your apk releases. And any capable designer could copy your logo in a matter of minutes too.

In both cases you would be infringing copyright.

> Sharing the VectorDrawable used for the launcher icon would also be a good start and would be at least sufficient for my needs

You have not explained what you intend to do and what are your needs, and yet you are requiring something from an open source project. Let me be clear: you are not entitled to anything.

**Comment by scribblemaniac** [comment]
> In both cases you would be infringing copyright.

I'm not sure why you think someone who is creating a spoofed version would care about this.

> You have not explained what you intend to do and what are your needs, and yet you are requiring something from an open source project. Let me be clear: you are not entitled to anything.

I am not requiring anything, nor do I feel entitled to anything, I am merely making a request. If you really want to know what I intend to do with it, I was intending to add bromite to https://github.com/alrra/browser-logos.

**Comment by akianaki** [comment]
![image](https://user-images.githubusercontent.com/54785442/64086426-5b286400-cd8c-11e9-87a0-f495731b2287.png)


https://github.com/akianaki/brom-/blob/master/ite.svg
