### ISSUE TITLE
Can't add userscript - Invalid script header

### ISSUE THREAD

**Issue by Xav0314** [bromite/bromite#2598]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser (not about the website, building Bromite, F-Droid or anything else).

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

108.0.5359.156

### Device architecture

arm64-v8a

### Android version

13

### Device model

SM-G781B

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

getting `Invalid script header. Invalid RunAtDeclaration document-body` trying to add user script

userscript works on Kiwi with Tampermonkey extension

### Steps to reproduce the bug

1. Download script from https://sleazyfork.org/en/scripts/441079-chaturbate-enhancer
2. Go to user scripts settings
3. Click on Add Script and select the downloaded script

### Expected behavior

Script is added and able to activate

### Screenshots

![Screenshot_20230310_193857_Bromite](https://user-images.githubusercontent.com/127565191/224441433-897c5e87-36cd-4813-96ac-fa946eacb553.png)

**Comment by improperdev** [comment]
Hi,

We are creators of Chaturbate Enhancer userscript. Have you managed to resolve this issue? We no longer use "document-body" run-at in favor of "document-start". Does this error occur on latest version (2.1.9)?

**Comment by Xav0314** [comment]
Tested the script and it install fine but nothing works. 
Bromite's implementation of userscripts is very primitive, had problems with dozens of userscripts.
I don't think they are going to futher develop this app, so i'm just going to close this issue

I switched to kiwi with tampermonkey and everything works in that app
