### ISSUE TITLE
Always request desktop site for certain domains of choice

### ISSUE THREAD

**Issue by futurk** [bromite/bromite#2602]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.
- [X] This is a feature request for the Bromite browser; not the website nor F-Droid nor anything else.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No.

### Describe the solution you would like

It would be extremely convenient to have an option named "Desktop mode" in the Permissions menu from which user can toggle on/off for any website.

![screenshot](https://i.ibb.co/gjJTQJK/Screenshot-20230315-155628-Bromite.png)

I usually like to browse web in normal mode but some websites can be designed awfully which can also be very annoying.

### Describe alternatives you have considered

Settings >> User Agent >> Current behaviour for desktop mode toggle in hamburger menu
enables "always request desktop site **unconditionally**" (i.e., for every website)
related issue: https://github.com/bromite/bromite/issues/780
This feature does not have to be removed though.
If I were to enable this feature it affects negatively because some websites like Youtube function slow in Desktop mode.

**Comment by Universalizer** [comment]
Might be helpful https://github.com/bromite/bromite/discussions/2530#discussioncomment-4578877

**Comment by futurk** [comment]
> Might be helpful [#2530 (comment)](https://github.com/bromite/bromite/discussions/2530#discussioncomment-4578877)

Helped.
