### ISSUE TITLE
F-Droid Repo Not Working

### ISSUE THREAD

**Issue by oneofmanyacdcfans** [bromite/bromite#261]
The F-Droid repository for this project is not working. After adding the repo, F-Droid gives the error "failed to get index file, all other repos returned no error." I have double and triple checked the URL, I'm using the newest one. The fingerprint is correct as well. I even tried uninstalling and reinstalling F-Droid itself and adding the Bromite repo before any others.

**Comment by csagan5** [comment]
You should submit an issue to the F-Droid client repository on Gitlab, this repository here is for the Bromite browser itself.

**Comment by oneofmanyacdcfans** [comment]
My mistake. I am new to GitHub. Thank you 😌

On March 12, 2019 4:22:19 PM EDT, Carl <notifications@github.com> wrote:
>You should submit an issue to the F-Droid client repository on Gitlab,
>this repository here is for the Bromite browser itself.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bromite/bromite/issues/261#issuecomment-472165695

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bushrang3r** [comment]
Is this the URL you used?

https://fdroid.bromite.org/fdroid/repo?fingerprint=E1EE5CD076D7B0DC84CB2B45FB78B86DF2EB39A3B6C56BA3DC292A5E0C3B9504

Worked for me just now.

**Comment by oneofmanyacdcfans** [comment]
I did a copy and paste of that link and I'm getting the same result. But if it's working for you, then it must be something related specifically to my device or OS. I'm using an HTC Desire 510 on KitKat 4.4.2, unmodified factory ROM.  I attached a screenshot of the error I'm getting. 

On March 12, 2019 8:30:09 PM EDT, bushrang3r <notifications@github.com> wrote:
>Is this the URL you used?
>
>https://fdroid.bromite.org/fdroid/repo?fingerprint=E1EE5CD076D7B0DC84CB2B45FB78B86DF2EB39A3B6C56BA3DC292A5E0C3B9504
>
>Worked for me just now.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bromite/bromite/issues/261#issuecomment-472233085

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by luontokoodaus** [comment]
@oneofmanyacdcfans solved here: https://github.com/bromite/bromite/issues/308
