### ISSUE TITLE
Qwant search engine

### ISSUE THREAD

**Issue by bushrang3r** [bromite/bromite#262]
(It would be great if the issue field was pre-filled with the template when submitting an issue)

Bromite version

Version: 73.0.3683.70
Arch: arm
Android version: pie

Is the bug reproducible with latest version?
Yes.

Can the bug be reproduced with corresponding Chromium version?
...

Is the bug a crash?
No

To Reproduce

Look at bromite.org

Notice it lists qwant as a search engine

In bromite app, go to settings > search engine and notice there is no qwant listed

**Comment by csagan5** [comment]
Fixed in `73.0.3683.79`

**Comment by csagan5** [comment]
> (It would be great if the issue field was pre-filled with the template when submitting an issue)

It is a limitation of Github; they said they do not know when it will be fixed, if ever. You can see the template when using Github in desktop mode.

**Comment by bushrang3r** [comment]
Oh, I wondered if that was the case. I knew I'd seen the template pre-filled somewhere before. 
Thank you sir!
