### ISSUE TITLE
F-Droid repo auto update

### ISSUE THREAD

**Issue by salevdns** [bromite/bromite#264]
**Describe the bug**

I have the F-Droid Privileged Extension installed and it's working with auto install of updates for apps from the official F-Droid and Guardian repo. But for apps from the Bromite repo I just get a notification that it's ready to install and then have to manually install it via the Android package installer dialog.

**To Reproduce**

Install the F-Droid Privileged Extension and F-Droid

Add the Bromite repo to F-Droid

Try to install Bromite through F-Droid

**Expected behavior**

Bromite gets installed and updated automatically in the background.

**Comment by salevdns** [comment]
Related: [https://code.briarproject.org/briar/briar/issues/1424](https://code.briarproject.org/briar/briar/issues/1424)

**Comment by csagan5** [comment]
I am sorry but you should report this bug to the F-Droid client repository.
