### ISSUE TITLE
DNS over HTTPS not working!

### ISSUE THREAD

**Issue by miyume11** [bromite/bromite#265]
**Bromite version**

Version: 73.0.3683.70
Arch: arm
Android version: 4.4.4

hello, DNS over HTTPS not working when i use **OpenVPN** app ( openvpn for android )
it is work when all VPN app is disconnect but when VPN app is ON, DOH not work!

**Comment by csagan5** [comment]
It works for me.

**Comment by miyume11** [comment]
have you test on android 4.4.4 (kitkat) ? 
i test on 2 device v 4.4.4 and see this issue. 
this issue occure when open vpn is on

also i see android 5 above do not have this issue

**Comment by csagan5** [comment]
@miyume11 you have to submit the issue with the issue template (does not show from mobile).
