### ISSUE TITLE
Official Magisk module

### ISSUE THREAD

**Issue by V10lator** [bromite/bromite#266]
**Is your feature request related to privacy?**
No

**Is there a patch available for this feature somewhere?**
Somebody created a working repo, just go ahead, clone it and push it to magisk: https://github.com/rwxr-xr-xis/magisk-bromite-webview

**Describe the solution you'd like**
Bromite WebView in the form of a magisk module allows the installation on currently unsupported devices without interferring with SafetyNet.

**Describe alternatives you've considered**
Alternative is to replace the webview.apk on the system partition which will break SafetyNet.

**Comment by csagan5** [comment]
@V10lator I have mentioned the SafetyNet breakage on the [wiki page](https://github.com/bromite/bromite/wiki/Installing-SystemWebView)

That working repo was created by @rwxr-xr-xis.

The submission to Magisk is here: https://github.com/Magisk-Modules-Repo/submission/issues/255

From what I understand, a Magisk repository has to contain not just the source code but binary/APK/.so files as well?

**Comment by V10lator** [comment]
Didn't know the other module was already submitted, that's great. So I think this request is invalid untill the other guy abandones the module?

I don't know much about magisk modules but I think there is some metadata (name, version, file permissions, ...) and the file(s) that should be replaced on the system. Not sure if folder structure has to be like on the flash storage or is dictated by metadata. Take all of this with a grain of salt through as again: I don't know much on that topic.

**Comment by csagan5** [comment]
> Didn't know the other module was already submitted, that's great. So I think this request is invalid until the other guy abandons the module?

Anybody can submit anything to Magisk, it is simply not officially endorsed.

I also did not say I would want to maintain an official one; if submitting a Magisk module requires committing binary files to github, I prefer not to and to keep the current official APK releases.

**Comment by csagan5** [comment]
Discussion continues on https://github.com/Magisk-Modules-Repo/submission/issues/255

There will be no official Bromite SystemWebView Magisk module unless it can be maintained in a clean way.

**Comment by igalic** [comment]
> Somebody created a working repo, just go ahead, clone it and push it to magisk: https://github.com/rwxr-xr-xis/magisk-bromite-webview

whelp, that repo is gone now, and https://github.com/Magisk-Modules-Repo/submission/issues/255#issuecomment-477618075 was closed because when it still existed, it used a now outdated module format.

**Comment by csagan5** [comment]
I noticed; I am unwilling to commit to maintain a Magisk module because of the effort needed...additionally, I do not seem to find how they implement signatures (if any). I suspect there are not.

**Comment by igalic** [comment]
i would love to say, oh sure! ***I*** will look into this, but not only am i lacking time, i'm also lacking know-how of Bromite itself: https://github.com/bromite/bromite/issues/283

**Comment by csagan5** [comment]
@igalic I think there is no difference between any Webview and Bromite's one, in terms of installation/packaging

**Comment by rwxr-xr-xis** [comment]
I deleted the repo because I did not the time to update it to the latest magisk module template at the time, I'll create another one again this week when I get some time
