### ISSUE TITLE
Add my personal search engine

### ISSUE THREAD

**Issue by alexmat** [bromite/bromite#267]
**Is your feature request related to privacy?**
Yes

**Is there a patch available for this feature somewhere?**
No

**Describe the solution you'd like**
I run my own search engine instance and would like to be able to use it by default. This works well in Brave.

**Describe alternatives you've considered**
None

**Comment by csagan5** [comment]
What search engine instance?

If it works well in Brave you could ask on the Brave forums how that is possible so that the same patch can be used here.

**Comment by csagan5** [comment]
Duplicate of #91.

**Comment by thestinger** [comment]
It's already possible to add custom search engines. You need to visit a compatible search engine and then it will show up as a possibility to add it in the search engine settings.
