### ISSUE TITLE
Clicking add to homescreen fails to add website to homescreen

### ISSUE THREAD

**Issue by alexmat** [bromite/bromite#268]
**Bromite version**

Version: 73

**Is the bug reproducible with latest version?**
Yes

**Is the bug a crash?**
No

**Describe the bug**
Clicking add to homescreen fails to add website to homescreen.

**To Reproduce**
1. Go to any website
2. Click on settings -> add to homescreen
3. See confirmation text
4. Icon not present on homescreen

**Expected behavior**
Icon to show up on homescreen

**Comment by csagan5** [comment]
The part about testing with Chromium is not optional.
