### ISSUE TITLE
AdBlock filter breaks website

### ISSUE THREAD

**Issue by ede-tw** [bromite/bromite#269]
**Bromite version**
Version: 73.0.3683.82
Arch:`arm64`
Android version: 7.0 NRD90M

**Is the bug reproducible with latest version?**
No

**Can the bug be reproduced with corresponding [Chromium]
N/A

**Is the bug a crash?**
N/A

**Describe the bug**
The website image does not load properly

**To Reproduce**
I suspect that the opening of Adblock will prevent image loading

**Expected behavior**
Must be able to load the image all

**Screenshots**
http://tw.appledaily.com

**Other**
If I give you some translation files, do you know how to join the program?

**Comment by csagan5** [comment]
Have you checked with developer tools what is the problem?

**Comment by ede-tw** [comment]
@csagan5 
adblock_entries.h
Hello there:
I looked at the h file and it seems to be related to this.
imp.appledaily.com

and so,
Can you include this in the exception list?
img.appledialy.com.tw
The image is placed inside

thank you!

**Comment by csagan5** [comment]
That website has code to detect adblockers; you should ask uBlock Origin to fix the issue, if possible, as it can be reproduced with any browser in mobile mode.
