### ISSUE TITLE
Search and site suggestions does not work on startpage

### ISSUE THREAD

**Issue by JoeTvx** [bromite/bromite#27]
Similar to #19, which is now fixed. Suggestions work fine on duckduckgo, Bing, and other engines, just not on the newly added startpage.

**Comment by gdm85** [comment]
It works for me, please try with upcoming **63.0.3239.144** (not yet released).

**Comment by csagan5** [comment]
Should be fixed already, can you check with next release?

**Comment by JoeTvx** [comment]
Confirmed, suggestions for startpage work fine in 63. 0. 3239.122.

Thank you for the fix! Closing.
