### ISSUE TITLE
Cannot log into GitHub with bromite (U2F)

### ISSUE THREAD

**Issue by Chaz6** [bromite/bromite#272]
My GitHub account has U2F enabled. Whilst I can log in using Chrome, when I put in my username and password with Bromite it just goes back to the login page (no warning about incorrect password).

I installed the latest arm64 version onto my Wileyfox Swift 2 Plus just now.

**Comment by csagan5** [comment]
@Chaz6 please re-submit the issue using the issue template (displayed in Github desktop mode because of a Github limitation)

**Comment by Bluscream** [comment]
The thing is, users will prefer switching to another browser instead of wasting time on this
