### ISSUE TITLE
Unable to log into github account (FIDO U2F)

### ISSUE THREAD

**Issue by Chaz6** [bromite/bromite#277]
**Bromite version**

Version: `73.0.3683.97`
Arch: `arm64`
Android version: `oreo`

**Is the bug reproducible with latest version?**
`Yes`

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
`No`

**Is the bug a crash?**
`No`

**Describe the bug**
I am unable to sign into github.com using a fido u2f token, which works in Chromium.

**To Reproduce**
1. First set up one of more fido u2f tokens on your github account using a desktop browser (see https://help.github.com/en/articles/configuring-two-factor-authentication#configuring-two-factor-authentication-using-fido-u2f for help)
2. Open Bromite and go to `https://github.com/signin`
3. Enter your username and password then tap `Sign in`
4. The U2F dialog appears briefly then disappears.

**Expected behavior**
The U2F dialog should remain active long enough to enable a token to be used.

**Screenshots**
N/A

**Comment by csagan5** [comment]
@Chaz6 have you tried with Adblock disabled?

**Comment by Chaz6** [comment]
@csagan5 I turned off Adblock and it still did not work.

**Comment by csagan5** [comment]
@Chaz6 do you confirm that with Chromium `73.0.3683.97` (from https://www.bromite.org/chromium) it works fine?

**Comment by nm111** [comment]
AFAIK FIDO on android requires play services (com.google.android.gms:play-services-fido)

**Comment by nikodll** [comment]
Th real probleem is that it doesn't even offer to use one of the back-up codes for your Google account (they're provided when you have second-factor authentication enabled)
