### ISSUE TITLE
Apps' redirecting on Bromite doesn't work

### ISSUE THREAD

**Issue by Asbesbopispa** [bromite/bromite#279]
**Bromite version**

Version: `73.0.3683.105`
Arch: `arm64`
Android version: `Android 9 Pie LineageOS 16`

**Is the bug reproducible with latest version?**
`Yes`

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
`No, I tested that.`

**Describe the bug**
If an application wants to open Bromite to show me a page, Bromite doesn't even attempt to load that link. 

**To Reproduce**
1. Open F-Droid for example
2. Click on a random app
3. Press on 'Homepage' or 'Issues' 
4. Open with Bromite
5. It doesn't show the page. 

**Expected behavior**
I should see the page I've been linked to. 

**Screenshots**
I uploaded a short video: https://imgur.com/a/EOVyN2F

**Comment by schneekluth** [comment]
Same here. Android 8, OxygenOS 5.0.8, OnePlus 3.

**Comment by jslawler** [comment]
Same issue, Android 9, OxygenOS 9.0.4, OnePlus 6.

**Comment by BlackDex** [comment]
Same for Nokia 7 Plus with Android One Pie 9 March patches

**Comment by skinnx86** [comment]
Ditto on Pixel 2 Android 9 March security patch.

Downgrading failed, but uninstalling then choosing the v73.0.3683.97 works. I didn't choose a x.x.x.105 release just incase.

**Comment by csagan5** [comment]
This is related to #132.

Should be fixed in next release.

**Comment by csagan5** [comment]
Fixed in `73.0.3683.107`.

**Comment by Asbesbopispa** [comment]
I confirm, it works now. Thank you for your amazing work!

**Comment by skinnx86** [comment]
Ditto, works now. Merci!
