### ISSUE TITLE
[Bromite 74] Snippets section in new tab page

### ISSUE THREAD

**Issue by kowith337** [bromite/bromite#282]
I tried to find both flags and settings to remove preloaded snipplet articles, but none of any options to completely remove them, only the **hide/show** toggle button.

Expected some data will leaks to Google and their partners

> **Bromite version**: 74.0.3729.80 (arm64)
> **Actual hardware**: HTC one E9Plus Dual Sim
> **Actual OS**: Android 5.0.2
> **Command line**: `--use-mobile-user-agent --top-controls-show-threshold=0.5 --top-controls-hide-threshold=0.5 --orderfile-memory-optimization=off --use-mobile-user-agent --enable-pinch --enable-viewport --validate-input-event-stream --main-frame-resizes-are-orientation-changes --disable-composited-antialiasing --enable-dom-distiller --flag-switches-begin --autoplay-policy=user-gesture-required --bypass-app-banner-engagement-checks --disable-webrtc-hw-decoding --disable-webrtc-hw-encoding --dns-over-https-server=https://dns.adguard.com/dns-query --disable-offer-store-unmasked-wallet-cards --enable-offline-auto-reload-visible-only --disable-quic --site-per-process --force-color-profile=srgb --force-effective-connection-type=Unknown --force-show-update-menu-badge --force-update-menu-type=unsupported_os_version --memlog=manual --reader-mode-heuristics=adaboost --wallet-service-use-sandbox=0 --enable-features=AndroidNightMode,AndroidSiteSettingsUIRefresh,AndroidSpellCheckerNonLowEnd,AppNotificationStatusMessaging,AutoFetchOnNetErrorPage,AutocompleteRetentionPolicyEnabled,AutofillDoNotUploadSaveUnsupportedCards,AutofillLocalCardMigrationUsesStrikeSystemV2,AutofillRestrictUnownedFieldsToFormlessCheckout,BackgroundLoadingForDownloads,BloatedRendererDetection,BlockTabUnders,CCTModule,CCTModuleCache,ChromeDuet,ClearOldBrowsingData,ClipboardContentSetting,ContextualSearchSecondTap,ContextualSuggestionsOptOut,DontPrefetchLibraries,DownloadHomeV2,DownloadProgressInfoBar,DownloadsLocationChange,EnableFilesystemInIncognito,EnforceTLS13Downgrade,ForegroundNotificationManager,FramebustingNeedsSameOriginOrUserGesture,IPH_DemoMode,IncognitoStrings,InterestFeedContentSuggestions,LanguagesPreference,LazyFrameLoading,LazyImageLoading,MarkHttpAs,ModalPermissionDialogView,NewNetErrorPageUI,NoCreditCardAbort,OfflinePagesDescriptiveFailStatus,OfflinePagesDescriptivePendingStatus,OfflinePagesShowAlternateDinoPage,OverrideTranslateTriggerInIndia,ParallelDownloading,RecurrentInterstitialFeature,SafeBrowsingUseLocalBlacklistsV2,TranslateAndroidManualTrigger,UnifiedConsent,site-isolation-for-password-sites,stop-in-background --disable-features=AffiliationBasedMatching,AllowSignedHTTPExchangeCertsWithoutExtension,AndroidOmniboxPreviewsBadge,AsyncDns,AutofillCreditCardAblationExperiment,AutofillCreditCardAssist,AutofillImportNonFocusableCreditCardForms,AutofillPrefilledFields,AutofillSaveCreditCardUsesStrikeSystem,AutofillSaveCreditCardUsesStrikeSystemV2,AutofillSendExperimentIdsInPaymentsRPCs,AutofillShowTypePredictions,AutofillUpstream,AutofillUpstreamEditableCardholderName,AutofillUpstreamEditableExpirationDate,AwaitOptimization,BuiltInModuleAll,BundledConnectionHelp,ClientLoFi,ContentSuggestionsCategoryOrder,ContentSuggestionsCategoryRanker,ContentSuggestionsDebugLog,ContentSuggestionsNotifications,ContentSuggestionsThumbnailDominantColor,ContextualSearchRankerQuery,ContextualSuggestionsButton,ContextualSuggestionsIPHReverseScroll,DataReductionProxyDecidesTransform,DataReductionProxyEnabledWithNetworkService,DataSaverLiteModeRebranding,DeviceMotion,DeviceOrientation,ExperimentalProductivityFeatures,ExperimentalUi,ExploreSites,GenericSensor,GenericSensorExtraClasses,GrantNotificationsToDSE,HomepageTile,ImprovedGeoLanguageData,InlineUpdateFlow,KeepPrefetchedContentSuggestions,LitePageServerPreviews,MobileIdentityConsistency,NTPArticleSuggestions,NTPAssetDownloadSuggestions,NTPBookmarkSuggestions,NTPButton,NTPOfflinePageDownloadSuggestions,NTPSnippetsIncreasedVisibility,NewEncodeCpuLoadEstimator,NoScriptPreviews,NoStatePrefetch,OfflineIndicatorAlwaysHttpProbe,OfflinePagesCT,OfflinePagesCTSuppressNotifications,OfflinePagesInDownloadHomeOpenInCct,OfflinePagesLivePageSharing,OfflinePagesLoadSignalCollecting,OfflinePagesPrefetching,OfflinePagesRenovations,OfflinePagesResourceBasedSnapshot,OfflinePreviews,OfflineRecentPages,OptimizationHints,OutOfBlinkCors,Previews,ResourceLoadScheduler,ResourceLoadingHints,SafeBrowsingTelemetryForApkDownloads,SafeSearchUrlReporting,SearchReadyOmnibox,ServiceWorkerImportedScriptUpdateCheck,SignedHTTPExchange,SiteExplorationUi,SyncPseudoUSSFavicons,SyncPseudoUSSHistoryDeleteDirectives,SyncPseudoUSSPreferences,SyncPseudoUSSPriorityPreferences,SyncPseudoUSSSupervisedUsers,SyncSupportSecondaryAccount,SyncUSSAutofillProfile,SyncUSSAutofillWalletData,SyncUSSAutofillWalletMetadata,SyncUSSBookmarks,TopSitesFromSiteEngagement,UseNewAcceptLanguageHeader,UseSuggestionsEvenIfFew,UserActivationV2,WebNFC,WebPaymentsPerMethodCanMakePaymentQuota,WebRtcHWH264Encoding,WebRtcHWVP8Encoding,WebRtcHybridAgc,WebXR,WebXRGamepadSupport,WebXRHitTest,google-password-manager --flag-switches-end`

**Comment by csagan5** [comment]
@kowith337 that is an impressive list of switches, I would hope that all of them are already disabled by default or via code eviction in Bromite, however it would be nice to (separately, in one or more different issues) track whether they are or not as I cannot tell in a glimpse.

To go back on your issue about snippets: I assume we are talking about "NTP remote suggestions", as they seem to be called internally.

Bromite is already disabling them by default with this patch https://github.com/bromite/bromite/blob/master/build/patches/Disable-NTP-remote-suggestions-by-default.patch which has been used for quite some time now.

As far as I can see there is no article fetched with these default settings.

> one of any options to completely remove them, only the hide/show toggle button.

Can you please explain how to verify this? e.g. how do you know that the articles are still being downloaded? (because they should not, according to the default settings of Bromite).

**Comment by kowith337** [comment]
I cannot clearly confirm once clear data and start over with reconfigured settings and flags, I guess some flags value was reset or reconfigured after update to newer version.

Here's a configuration after I've reset app data and start over again.

`--use-mobile-user-agent --top-controls-show-threshold=0.5 --top-controls-hide-threshold=0.5 --orderfile-memory-optimization=on --use-mobile-user-agent --enable-pinch --enable-viewport --validate-input-event-stream --main-frame-resizes-are-orientation-changes --disable-composited-antialiasing --enable-dom-distiller --flag-switches-begin --autoplay-policy=user-gesture-required --disable-best-effort-tasks --disable-webrtc-hw-decoding --disable-webrtc-hw-encoding --blink-settings=disallowFetchForDocWrittenScriptsInMainFrame=true --dns-over-https-server=https://dns.adguard.com/dns-query --disable-offer-store-unmasked-wallet-cards --enable-offline-auto-reload-visible-only --disable-quic --site-per-process --force-effective-connection-type=Unknown --force-show-update-menu-badge --force-update-menu-type=unsupported_os_version --memlog=manual --reader-mode-heuristics=adaboost --disable-smooth-scrolling --wallet-service-use-sandbox=0 --enable-features=AndroidNightMode,AndroidSiteSettingsUIRefresh,AutofillDoNotUploadSaveUnsupportedCards,AutofillLocalCardMigrationUsesStrikeSystemV2,AutofillNoLocalSaveOnUploadSuccess,AutofillRestrictUnownedFieldsToFormlessCheckout,AutofillSaveCreditCardUsesStrikeSystem,AutofillSaveCreditCardUsesStrikeSystemV2,BloatedRendererDetection,BlockTabUnders,CCTModule,CCTModuleCache,ClearOldBrowsingData,ClipboardContentSetting,ContextualSearchSecondTap,ContextualSearchUnityIntegration,ContextualSuggestionsOptOut,CustomContextMenu,DontPrefetchLibraries,DownloadProgressInfoBar,DownloadsAutoResumptionNative,DownloadsLocationChange,ForegroundNotificationManager,FramebustingNeedsSameOriginOrUserGesture,IncognitoStrings,LanguagesPreference,LazyFrameLoading,LazyImageLoading,LsdPermissionPrompt,ManualPasswordGenerationAndroid,MarkHttpAs,ModalPermissionDialogView,OverrideTranslateTriggerInIndia,ParallelDownloading,RecurrentInterstitialFeature,SSLCommittedInterstitials,SafeBrowsingUseLocalBlacklistsV2,TabGridLayoutAndroid,TabGroupsAndroid,TabSwitcherOnReturn,TranslateAndroidManualTrigger,UnifiedConsent,site-isolation-for-password-sites,stop-non-timers-in-background --disable-features=AffiliationBasedMatching,AndroidOmniboxPreviewsBadge,AndroidSurfaceControl,AsyncDns,AutofillCacheQueryResponses,AutofillCreditCardAblationExperiment,AutofillCreditCardAssist,AutofillDynamicForms,AutofillEnableCompanyName,AutofillImportNonFocusableCreditCardForms,AutofillKeyboardAccessory,AutofillManualFallbackAndroid,AutofillPrefilledFields,AutofillProfileClientValidation,AutofillProfileServerValidation,AutofillRefreshStyleAndroid,AutofillSendExperimentIdsInPaymentsRPCs,AutofillShowFullDisclosureLabel,AutofillShowTypePredictions,AutofillTokenPrefixMatching,AutofillUpstream,AutofillUpstreamEditableCardholderName,AutofillUpstreamEditableExpirationDate,AwaitOptimization,BackgroundTaskComponentUpdate,BuiltInModuleAll,BundledConnectionHelp,CCTTargetTranslateLanguage,ChromeDuet,ClientLoFi,ContentSuggestionsCategoryOrder,ContentSuggestionsCategoryRanker,ContentSuggestionsDebugLog,ContentSuggestionsNotifications,ContentSuggestionsThumbnailDominantColor,ContextualSearchRankerQuery,ContextualSuggestionsButton,ContextualSuggestionsIPHReverseScroll,DataReductionProxyDecidesTransform,DataReductionProxyEnabledWithNetworkService,DataSaverLiteModeRebranding,DeviceMotion,DeviceOrientation,DownloadHomeV2,EnableFilesystemInIncognito,ExpensiveBackgroundTimerThrottling,ExperimentalProductivityFeatures,ExperimentalUi,ExploreSites,GenericSensor,GenericSensorExtraClasses,GrantNotificationsToDSE,HTTPSServerPreviewsUsingURLLoader,HomepageTile,IPH_DemoMode,ImprovedGeoLanguageData,InlineUpdateFlow,InterestFeedContentSuggestions,KeepPrefetchedContentSuggestions,LitePageServerPreviews,LookalikeUrlNavigationSuggestionsUI,MobileIdentityConsistency,NTPArticleSuggestions,NTPAssetDownloadSuggestions,NTPBookmarkSuggestions,NTPButton,NTPOfflinePageDownloadSuggestions,NTPSnippetsIncreasedVisibility,NetworkService,NetworkServiceInProcess,NewContactsPicker,NewEncodeCpuLoadEstimator,NewPhotoPicker,NoScriptPreviews,NoStatePrefetch,OfflineIndicator,OfflinePagesCT,OfflinePagesCTSuppressNotifications,OfflinePagesCTV2,OfflinePagesInDownloadHomeOpenInCct,OfflinePagesLivePageSharing,OfflinePagesLoadSignalCollecting,OfflinePagesPrefetching,OfflinePagesRenovations,OfflinePagesResourceBasedSnapshot,OfflinePagesShowAlternateDinoPage,OfflinePreviews,OfflineRecentPages,OmniboxNewAnswerLayout,OmniboxRichEntitySuggestions,OmniboxSpeculativeServiceWorkerStartOnQueryInput,OmniboxVoiceSearchAlwaysVisible,OptimizationHints,OutOfBlinkCors,Previews,QueryInOmnibox,RTCUnifiedPlanByDefault,ResamplingInputEvents,ResamplingScrollEvents,ResourceLoadScheduler,ResourceLoadingHints,SafeBrowsingTelemetryForApkDownloads,SafeSearchUrlReporting,SearchReadyOmnibox,ServiceWorkerImportedScriptUpdateCheck,ServiceWorkerLongRunningMessage,SharedArrayBuffer,SignedHTTPExchange,SiteExplorationUi,SyncPseudoUSSFavicons,SyncPseudoUSSHistoryDeleteDirectives,SyncPseudoUSSPreferences,SyncPseudoUSSPriorityPreferences,SyncPseudoUSSSupervisedUsers,SyncUSSAutofillProfile,SyncUSSAutofillWalletData,SyncUSSAutofillWalletMetadata,SyncUSSBookmarks,SyncUSSPasswords,TopSitesFromSiteEngagement,UseDownloadOfflineContentProvider,UseNewAcceptLanguageHeader,UserMediaScreenCapturing,WasmCodeCache,WebAssemblyBaseline,WebAssemblyThreads,WebNFC,WebPaymentsPerMethodCanMakePaymentQuota,WebRtcHWH264Encoding,WebRtcHWVP8Encoding,WebRtcHybridAgc,WebXR,WebXRGamepadSupport,WebXRHitTest,stop-in-background --flag-switches-end`

**Comment by csagan5** [comment]
> I cannot clearly confirm once clear data and start over with reconfigured settings and flags, I guess some flags value was reset or reconfigured after update to newer version.

The flags are `enable-ntp-remote-suggestions` and `enable-ntp-suggestions-notifications`, and they are both disabled by default in Bromite (you can verify in `chrome://flags` that nothing changes if you switch them to default, as the default is already disabled).

@kowith337 I need to know what is the problem that you are seeing on your screen (if any) or logs, otherwise if the bug cannot be reproduced I cannot do anything with the report.

**Comment by BUAWF** [comment]
@kowith337
After this Update the same issue occured with Me too ! Head over to chrome://flags/#interest-feed-content-suggestions this was enabled in larger images for Me, so I Disabled it & its gone Now. Hope this may help You.

**Comment by csagan5** [comment]
@BUAWF the `interest-feed-content-suggestions` feature flag is disabled by default in Chromium, perhaps you had enabled it manually?

**Comment by my-password-is-password** [comment]
This happened to me too.  It was enabled and set to "larger images" in v74.0.3729.80 and I didn't do it.  I basically had disabled everything related to NTP in flags.

**Comment by kowith337** [comment]
> 
> 
> the `interest-feed-content-suggestions` feature flag is disabled by default in Chromium, perhaps you had enabled it manually?

I remember I didn't see those snippets in the prior version before upgrade.

**Comment by ouzowtf** [comment]
Those settings are _not_  enabled for me in v74.0.3729.80 after the upgrade.

**Comment by csagan5** [comment]
> I remember I didn't see those snippets in the prior version before upgrade, so the snippets was disabled already or I've set it to disable and then...

It's possible that when a setting is set to `disabled` (not `default`) and then upstream changes it from `disabled` to something else, they migrate the `disabled` value to a new setting.

I do not doubt you have experienced these issues but we have to verify them from a scratch installation because of all these complicated possible scenarios.

**Comment by kowith337** [comment]
Confirm case from @my-password-is-password that if you've previously configured `#interest-feed-content-suggestions` will be changed from `Disabled` to `Enabled (larger images)`

![interest-feed-content-suggestions](https://i.imgur.com/1jCdZn0.png)
![Enable large images](https://i.imgur.com/YBbGneZ.png)

OK, it seems like some flags was added more choices and cause that things turned on, even you've turned off already in previous version.

Here's a diff between versions after I've self hardening configured.

___

### 73.0.3683.107 (Self-hardening flags configured)
> `--use-mobile-user-agent --top-controls-show-threshold=0.5 --top-controls-hide-threshold=0.5 --orderfile-memory-optimization=off --use-mobile-user-agent --enable-pinch --enable-viewport --validate-input-event-stream --main-frame-resizes-are-orientation-changes --disable-composited-antialiasing --enable-dom-distiller --flag-switches-begin --autoplay-policy=user-gesture-required --disable-contextual-search --disable-accelerated-2d-canvas --disable-accelerated-video-decode --disable-cast-streaming-hw-encoding --disable-webrtc-hw-decoding --disable-webrtc-hw-encoding --blink-settings=disallowFetchForDocWrittenScriptsInMainFrame=true --dns-over-https-server=https://dns.adguard.com/dns-query --disable-offer-store-unmasked-wallet-cards --disable-offline-auto-reload-visible-only --disable-offline-auto-reload --disable-quic --site-per-process --force-effective-connection-type=Unknown --force-show-update-menu-badge --force-update-menu-type=unsupported_os_version --reader-mode-heuristics=adaboost --reduced-referrer-granularity --v8-cache-options=none --wallet-service-use-sandbox=0 --enable-features=AndroidSiteSettingsUIRefresh,AutocompleteRetentionPolicyEnabled,AutofillRestrictUnownedFieldsToFormlessCheckout,BloatedRendererDetection,BlockTabUnders,ClearOldBrowsingData,ClipboardContentSetting,ContextualSearchUnityIntegration,ContextualSuggestionsOptOut,DontPrefetchLibraries,DownloadsLocationChange,ExplicitLanguageAsk,ForegroundNotificationManager,FramebustingNeedsSameOriginOrUserGesture,IncognitoStrings,LanguagesPreference,LazyFrameLoading,LazyImageLoading,MarkHttpAs,MaterialDesignIncognitoNTP,ModalPermissionDialogView,ModalPermissionPrompts,ParallelDownloading,SSLCommittedInterstitials,SafeBrowsingUseLocalBlacklistsV2,SoundContentSetting,SupervisedUserCommittedInterstitials,TranslateAndroidManualTrigger,UnifiedConsent,resume-background-video,stop-in-background,stop-non-timers-in-background --disable-features=AffiliationBasedMatching,AllowRemoteContextForNotifications,AllowSignedHTTPExchangeCertsWithoutExtension,AndroidAutofillAccessibility,AndroidOmniboxPreviewsBadge,AndroidPayIntegrationV1,AndroidPayIntegrationV2,AndroidPaymentApps,AppNotificationStatusMessaging,AsyncDns,AutoFetchOnNetErrorPage,AutofillCacheQueryResponses,AutofillCreditCardAblationExperiment,AutofillCreditCardAssist,AutofillImportNonFocusableCreditCardForms,AutofillKeyboardAccessory,AutofillPrefilledFields,AutofillRichMetadataQueries,AutofillSendExperimentIdsInPaymentsRPCs,AutofillShowTypePredictions,AutofillUpstream,AutofillUpstreamEditableCardholderName,AutofillUpstreamEditableExpirationDate,AutomaticPasswordGeneration,AwaitOptimization,BundledConnectionHelp,CCTModuleCache,CCTModulePostMessage,CCTModuleUseIntentExtras,ChromeDuet,ClientLoFi,ContentSuggestionsCategoryOrder,ContentSuggestionsCategoryRanker,ContentSuggestionsDebugLog,ContentSuggestionsFaviconsFromNewServer,ContentSuggestionsNotifications,ContentSuggestionsThumbnailDominantColor,ContextualSearchMlTapSuppression,ContextualSearchRankerQuery,ContextualSuggestionsButton,ContextualSuggestionsIPHReverseScroll,DataReductionProxyDecidesTransform,DataReductionProxyEnabledWithNetworkService,DataSaverLiteModeRebranding,DetectingHeavyPages,DeviceMotion,DeviceOrientation,DownloadHomeV2,EphemeralTab,ExpensiveBackgroundTimerThrottling,ExperimentalAppBanners,ExperimentalProductivityFeatures,ExperimentalUi,ExploreSites,GamepadVibration,GenericSensor,GenericSensorExtraClasses,GrantNotificationsToDSE,HomepageTile,IPH_DemoMode,IPv6Probing,ImageCaptureAPI,ImprovedGeoLanguageData,InterestFeedContentSuggestions,KeepPrefetchedContentSuggestions,LayeredAPI,LitePageServerPreviews,NTPArticleSuggestions,NTPAssetDownloadSuggestions,NTPBookmarkSuggestions,NTPButton,NTPOfflinePageDownloadSuggestions,NTPSnippetsIncreasedVisibility,NetworkService,NetworkServiceInProcess,NewContactsPicker,NewEncodeCpuLoadEstimator,NewNetErrorPageUI,NewPhotoPicker,NoCreditCardAbort,NoScriptPreviews,NoStatePrefetch,OfflineBookmarks,OfflineIndicator,OfflineIndicatorAlwaysHttpProbe,OfflinePagesCT,OfflinePagesCTSuppressNotifications,OfflinePagesCTV2,OfflinePagesInDownloadHomeOpenInCct,OfflinePagesLivePageSharing,OfflinePagesLoadSignalCollecting,OfflinePagesPrefetching,OfflinePagesRenovations,OfflinePagesResourceBasedSnapshot,OfflinePagesSharing,OfflinePagesShowAlternateDinoPage,OfflinePagesSvelteConcurrentLoading,OfflinePreviews,OfflineRecentPages,OmniboxSpeculativeServiceWorkerStartOnQueryInput,OmniboxVoiceSearchAlwaysVisible,OptimizationHints,OutOfBlinkCors,OverrideTranslateTriggerInIndia,PassiveDocumentEventListeners,PassiveDocumentWheelEventListeners,PassiveEventListenersDueToFling,PasswordsKeyboardAccessory,PayWithGoogleV1,Previews,ProtectSyncCredentialOnReauth,PwaPersistentNotification,QueryInOmnibox,RegionalLocalesAsDisplayUI,ResamplingInputEvents,ResamplingScrollEvents,ResourceLoadScheduler,ResourceLoadingHints,SafeBrowsingTelemetryForApkDownloads,SafeSearchUrlReporting,SearchReadyOmnibox,ServiceWorkerImportedScriptUpdateCheck,ServiceWorkerLongRunningMessage,ServiceWorkerPaymentApps,ServiceWorkerServicification,SignedHTTPExchange,SiteExplorationUi,SyncPseudoUSSFavicons,SyncPseudoUSSHistoryDeleteDirectives,SyncPseudoUSSPasswords,SyncPseudoUSSPreferences,SyncPseudoUSSPriorityPreferences,SyncPseudoUSSSupervisedUsers,SyncSendTabToSelf,SyncStandaloneTransport,SyncUSSAutofillProfile,SyncUSSAutofillWalletData,SyncUSSBookmarks,TopSitesFromSiteEngagement,TranslateRankerEnforcement,TranslateUI,UseNewAcceptLanguageHeader,UseSuggestionsEvenIfFew,UserActivationV2,UserMediaScreenCapturing,WebNFC,WebPaymentsJustInTimePaymentApp,WebPaymentsMethodSectionOrderV2,WebPaymentsModifiers,WebPaymentsPerMethodCanMakePaymentQuota,WebPaymentsSingleAppUiSkip,WebRtcHWH264Encoding,WebRtcHWVP8Encoding,WebRtcHybridAgc,WebRtcUseEchoCanceller3,WebXR,WebXRGamepadSupport,WebXRHitTest,WebXROrientationSensorDevice,ZeroSuggestRedirectToChrome,google-password-manager,protect-sync-credential --flag-switches-end`

### 74.0.3729.80 (Previous configuration was changed after upgrade)
> `--use-mobile-user-agent --top-controls-show-threshold=0.5 --top-controls-hide-threshold=0.5 --orderfile-memory-optimization=on --use-mobile-user-agent --enable-pinch --enable-viewport --validate-input-event-stream --main-frame-resizes-are-orientation-changes --disable-composited-antialiasing --enable-dom-distiller --flag-switches-begin --autoplay-policy=user-gesture-required --disable-accelerated-2d-canvas --disable-accelerated-video-decode --disable-webrtc-hw-decoding --disable-webrtc-hw-encoding --blink-settings=disallowFetchForDocWrittenScriptsInMainFrame=true --dns-over-https-server=https://dns.adguard.com/dns-query --disable-offer-store-unmasked-wallet-cards --disable-offline-auto-reload-visible-only --disable-offline-auto-reload --disable-quic --site-per-process --force-effective-connection-type=Unknown --force-show-update-menu-badge --force-update-menu-type=unsupported_os_version --reader-mode-heuristics=adaboost --reduced-referrer-granularity --v8-cache-options=none --wallet-service-use-sandbox=0 --enable-features=AndroidSiteSettingsUIRefresh,AutocompleteRetentionPolicyEnabled,AutofillRestrictUnownedFieldsToFormlessCheckout,BloatedRendererDetection,BlockTabUnders,ClearOldBrowsingData,ClipboardContentSetting,ContextualSearchUnityIntegration,ContextualSuggestionsOptOut,DontPrefetchLibraries,DownloadsLocationChange,ForegroundNotificationManager,FramebustingNeedsSameOriginOrUserGesture,IPH_DemoMode,IncognitoStrings,InterestFeedContentSuggestions,LanguagesPreference,LazyFrameLoading,LazyImageLoading,MarkHttpAs,ModalPermissionDialogView,ParallelDownloading,SSLCommittedInterstitials,SafeBrowsingUseLocalBlacklistsV2,SupervisedUserCommittedInterstitials,TranslateAndroidManualTrigger,UnifiedConsent,stop-in-background,stop-non-timers-in-background --disable-features=AffiliationBasedMatching,AllowRemoteContextForNotifications,AllowSignedHTTPExchangeCertsWithoutExtension,AndroidAutofillAccessibility,AndroidOmniboxPreviewsBadge,AppNotificationStatusMessaging,AsyncDns,AutoFetchOnNetErrorPage,AutofillCacheQueryResponses,AutofillCreditCardAblationExperiment,AutofillCreditCardAssist,AutofillImportNonFocusableCreditCardForms,AutofillKeyboardAccessory,AutofillPrefilledFields,AutofillRichMetadataQueries,AutofillSendExperimentIdsInPaymentsRPCs,AutofillShowTypePredictions,AutofillUpstream,AutofillUpstreamEditableCardholderName,AutofillUpstreamEditableExpirationDate,AutomaticPasswordGeneration,AwaitOptimization,BundledConnectionHelp,CCTModuleCache,CCTModulePostMessage,CCTModuleUseIntentExtras,ChromeDuet,ClientLoFi,ContentSuggestionsCategoryOrder,ContentSuggestionsCategoryRanker,ContentSuggestionsDebugLog,ContentSuggestionsNotifications,ContentSuggestionsThumbnailDominantColor,ContextualSearchMlTapSuppression,ContextualSearchRankerQuery,ContextualSuggestionsButton,ContextualSuggestionsIPHReverseScroll,DataReductionProxyDecidesTransform,DataReductionProxyEnabledWithNetworkService,DataSaverLiteModeRebranding,DeviceMotion,DeviceOrientation,DownloadHomeV2,EphemeralTab,ExpensiveBackgroundTimerThrottling,ExperimentalAppBanners,ExperimentalProductivityFeatures,ExperimentalUi,ExploreSites,GenericSensor,GenericSensorExtraClasses,GrantNotificationsToDSE,HomepageTile,IPv6Probing,ImprovedGeoLanguageData,KeepPrefetchedContentSuggestions,LitePageServerPreviews,NTPArticleSuggestions,NTPAssetDownloadSuggestions,NTPBookmarkSuggestions,NTPButton,NTPOfflinePageDownloadSuggestions,NTPSnippetsIncreasedVisibility,NetworkService,NetworkServiceInProcess,NewContactsPicker,NewEncodeCpuLoadEstimator,NewNetErrorPageUI,NewPhotoPicker,NoCreditCardAbort,NoScriptPreviews,NoStatePrefetch,OfflineIndicator,OfflineIndicatorAlwaysHttpProbe,OfflinePagesCT,OfflinePagesCTSuppressNotifications,OfflinePagesCTV2,OfflinePagesInDownloadHomeOpenInCct,OfflinePagesLivePageSharing,OfflinePagesLoadSignalCollecting,OfflinePagesPrefetching,OfflinePagesRenovations,OfflinePagesResourceBasedSnapshot,OfflinePagesShowAlternateDinoPage,OfflinePagesSvelteConcurrentLoading,OfflinePreviews,OfflineRecentPages,OmniboxSpeculativeServiceWorkerStartOnQueryInput,OmniboxVoiceSearchAlwaysVisible,OptimizationHints,OutOfBlinkCors,OverrideTranslateTriggerInIndia,PassiveDocumentEventListeners,PassiveDocumentWheelEventListeners,PassiveEventListenersDueToFling,PasswordsKeyboardAccessory,Previews,PwaPersistentNotification,QueryInOmnibox,RegionalLocalesAsDisplayUI,ResamplingInputEvents,ResamplingScrollEvents,ResourceLoadScheduler,ResourceLoadingHints,SafeBrowsingTelemetryForApkDownloads,SafeSearchUrlReporting,SearchReadyOmnibox,ServiceWorkerImportedScriptUpdateCheck,ServiceWorkerLongRunningMessage,SignedHTTPExchange,SiteExplorationUi,SyncPseudoUSSFavicons,SyncPseudoUSSHistoryDeleteDirectives,SyncPseudoUSSPreferences,SyncPseudoUSSPriorityPreferences,SyncPseudoUSSSupervisedUsers,SyncSendTabToSelf,SyncUSSAutofillProfile,SyncUSSAutofillWalletData,SyncUSSBookmarks,TopSitesFromSiteEngagement,UseNewAcceptLanguageHeader,UseSuggestionsEvenIfFew,UserActivationV2,UserMediaScreenCapturing,WebNFC,WebPaymentsPerMethodCanMakePaymentQuota,WebRtcHWH264Encoding,WebRtcHWVP8Encoding,WebRtcHybridAgc,WebXR,WebXRGamepadSupport,WebXRHitTest,google-password-manager --flag-switches-end`
