### ISSUE TITLE
Request: More detailed Bromite WebView installation documentation

### ISSUE THREAD

**Issue by igalic** [bromite/bromite#283]
i understand per https://github.com/bromite/bromite/issues/92 that Bromite is provided as-is, but it would be nice to have a better insight into how and why exactly the installation of the SystemView works as it does.

maybe that would help others extend.

**Comment by csagan5** [comment]
@igalic the issue template is mandatory as this Github project is just for the bugs/feature requests; for discussions I guess the best place would be XDA or Reddit
