### ISSUE TITLE
Removing sync & google service option

### ISSUE THREAD

**Issue by zputnyq** [bromite/bromite#285]
**Is your feature request related to privacy?**
No, it's design related I think

**Is there a patch available for this feature somewhere?**
...

**Describe the solution you'd like**
Bromite doesn't sync, I thik it's better if sync & google service option in setting and under setting » privacy are removed, but if this possible ofc
**Describe alternatives you've considered**
...

Thanks I really appreciate it

**Comment by zputnyq** [comment]
![_20190417_061540](https://user-images.githubusercontent.com/31039796/56250811-1badf380-60db-11e9-8704-fd4a0c70b658.JPG)
![_20190417_061716](https://user-images.githubusercontent.com/31039796/56250835-3e400c80-60db-11e9-8455-d4ca5304cdab.JPG)

**Comment by Disqu3-mirOir-qt** [comment]
yes good idea remove +1

**Comment by csagan5** [comment]
Fixed in `74.0.3729.106`.
