### ISSUE TITLE
Some sites with bad rendering

### ISSUE THREAD

**Issue by c-sanchez** [bromite/bromite#286]
Some sites have a bad rendering.

By example this occurs with trust.zone website
https://www.trust.zone/
![image](https://i.ibb.co/4JKqsKM/2019-04-17-10-03-56.png)

This dont's occurs with Brave, Kiwi or Chrome browsers

Version: Bromite v74.0.3729.86
Arch: x86
Android version: 4.4.4 kitkat

**Comment by BugReporterGit** [comment]
Test without ad blocker.

**Comment by c-sanchez** [comment]
> Test without ad blocker.

Oh! Yes, without ad blocker works properly the rendering in that site.
