### ISSUE TITLE
Desktop mode always / by site

### ISSUE THREAD

**Issue by c-sanchez** [bromite/bromite#288]
Brave browser for android have an option to enable always the Desktop mode.
Can be nice to have a similar option or even better some option to have the desktop mode by default with certain sites selected by the user. Maybe an "remember desktop mode"?
![img1](https://i.ibb.co/sJKVvn7/2019-04-18-17-06-08.png)
![img2](https://i.ibb.co/chBTYqM/2019-04-18-17-06-20.png)

Where "Modo escritorio" is the "Desktop mode" option in the brave settings.

**Comment by lowtrucks** [comment]
you can enable it by yourself, if you have root rights. details are here:

https://forum.xda-developers.com/showpost.php?p=76303079&postcount=173
