### ISSUE TITLE
themability past version 71

### ISSUE THREAD

**Issue by petep0p** [bromite/bromite#290]
**Bromite version**

Version: 72 and beyond
Arch: all
Android version: 8.0.0 (but probably all)

**Is the bug reproducible with latest version?**
yes (because the theme developers say that they still cannot theme bromite later than v71)

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
I'm not really clear on this part. please let me know if this is where it should be submitted.

**Is the bug a crash?**no

**Describe the bug**
I'm not totally clear on what the cause is, but this seems to be specific to bromite. because my understanding is very imperfect, please just let me know if this should go to chromium. basically, it seems that bromite can no longer be themed by extensions such as Swift installer because some parts of the underlying code are encrypted or something like that. i think chrome and chromium had this problem for version 72 and some later versions, but that this has been corrected since then. however, because of some peculiarity of what build bromite uses, bromite is still not themable past version 71.

**To Reproduce**
(i don't know how to build theme overlays so I'm not sure how to reproduce it)

**Expected behavior**
i would expect to be able to theme the app with an overlay for the latest version.

**Screenshots**
n/a

**Comment by csagan5** [comment]
> I'm not totally clear on what the cause is, but this seems to be specific to bromite. because my understanding is very imperfect, please just let me know if this should go to chromium. basically, it seems that bromite can no longer be themed by extensions such as Swift installer because some parts of the underlying code are encrypted or something like that. i think chrome and chromium had this problem for version 72 and some later versions, but that this has been corrected since then. however, because of some peculiarity of what build bromite uses, bromite is still not themable past version 71.

@petep0p what are your sources for this?
