### ISSUE TITLE
Widget Bromite Bookmarks Not Working

### ISSUE THREAD

**Issue by GodApollon** [bromite/bromite#293]
**74.0.3729.86**

Version: 74.0.37.29.86.
Arch:  arm64
Android version: 8.1 / Miui10 Global

**Describe the bug**
I click on any bookmark that I have in the "bookmarks widget" and it doesnt open Bromite at all. In chrome browser it works fine. Thanx

**Comment by csagan5** [comment]
Works fine here.

**Comment by GodApollon** [comment]
Yes you are right, I use Nova launcher Prime,I just tested this and It's their fault, in all other launchers is working fine. I have  sent an email to Nova Support.
