### ISSUE TITLE
Tab titles are black in dark mode

### ISSUE THREAD

**Issue by Noahmatada** [bromite/bromite#294]
**Bromite version**
Version: v74.0.3729.106
Arch: arm64
Android version: 9.0 Pie

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No

**Describe the bug**
When dark mode is enabled, tab titles remain black against a dark gray background, making them difficult to read. Incognito tabs' titles have white text and are perfectly readable as regular tabs should be. 

**To Reproduce**
1. Go to Settings
2. Click on Dark mode and turn it on
3. Go back and click on the tab button next to the menu button in top left to bring up tabs page
4. See that tab titles are hard to read

**Expected behavior**
The text for tab titles is white, making it readable against the dark gray background

**Screenshots**
![Screenshot_20190422-134326__01](https://user-images.githubusercontent.com/38673393/56515169-48ac3d00-6505-11e9-8680-ae1237e1fbd6.jpg)

**Comment by csagan5** [comment]
> **Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
> No

Really?

Please report this bug upstream to Chromium.

**Comment by Noahmatada** [comment]
The corresponding Chromium version does not have a dark mode option in the menu. Is there some way to enable it that I'm missing?
