### ISSUE TITLE
Google Search not looking right

### ISSUE THREAD

**Issue by intrnl** [bromite/bromite#297]
**Bromite version**

Version: `74.0.3729.122`
Arch: `arm64`
Android version: oreo

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No

**Describe the bug**
Google search pages end up looking incorrect with things being flipped

**To Reproduce**
1. Search on Google

**Expected behavior**
It should look normal just like Chromium

**Screenshots**
![Screenshot of Google Search page in Bromite](https://cdn.discordapp.com/attachments/555277203676594186/572914013315530762/Screenshot_2019-05-01-05-28-50-723_org.bromite.bromite.png)

**Comment by csagan5** [comment]
@intrnl I don't understand, what is being flipped?

**Comment by csagan5** [comment]
@intrnl interesting problem; however I would not know where to start to find the reason of this. Might be due to the anti-AMP changes.

Closing because there is no intent to fix
