### ISSUE TITLE
SafetyNet and Bromite when building a custom ROM

### ISSUE THREAD

**Issue by Iolaum** [bromite/bromite#298]
According to the [wiki](https://github.com/bromite/bromite/wiki/Installing-SystemWebView#installation-options) installing webview on your ROM breaks SafetyNet. Does that hold up even when one replaces aosp chromium webview with bromite when **building** the ROM?
(It was not clear to me from the wiki if that is also the case.)

**Comment by csagan5** [comment]
@Iolaum issues here should follow the issue template; for questions I suggest using XDA.
