### ISSUE TITLE
Version 74.0.3729.141 broken on fdroid

### ISSUE THREAD

**Issue by BaronKrause** [bromite/bromite#299]
Version 74.0.3729.141 on fdroid installs but is never detected as installed. If you update to it, it will still see the old version and say you need an update, if you fresh install it will think it didn't install at all, even though it did.

This is on a Samsung s8+ running Oreo if it has any impact.

**Comment by ouzowtf** [comment]
I had no problem updating from .122 to .141 via F-Droid on an Oreo running OP3T

**Comment by csagan5** [comment]
@BaronKrause there is no issue template and regardless it sounds like an issue for the F-Droid client, not Bromite
