### ISSUE TITLE
Add StartPage search engine

### ISSUE THREAD

**Issue by andrin55** [bromite/bromite#3]
Hello

Could you please add the StartPage search engine to the preinstalled ones?
https://www.startpage.com

Thank you

**Comment by csagan5** [comment]
Yes; to add my personal opinion: I do not trust either Google, DuckDuckGo or StartPage.

They are all used closed source technology and could be malicious actors, for what we know. But there is nothing better so I fully support the use of non-Google search engines for the goals of Bromite.

**Comment by andrin55** [comment]
> Yes; to add my personal opinion: I do not trust either Google, DuckDuckGo or StartPage.

Me neither... But you can try to at least spread your data and not giving it all to one big company.

**Comment by csagan5** [comment]
To be fair, they have this: https://www.startpage.com/eng/protect-privacy-qa.html#q10

Which is a bit more than what others offer...

**Comment by csagan5** [comment]
I made the patch and it's building; it might take as long as 24h to finish...

I will publish the patch as well once it builds correctly (can never be sure until it's done)

**Comment by andrin55** [comment]
Alright. Thank you for your support.

**Comment by csagan5** [comment]
FYI, slightly related, I coded in also this patch: https://github.com/bromite/bromite/blob/master/patches/privacy/remove-google-click-tracking.patch

It makes clicking on Google search results sensibly faster, plus of course removes the tracking.

So, using the default search engine (Google) becomes slightly less invasive (server is informed about what you searched but not about what you clicked).

**Comment by dimqua** [comment]
> I fully support the use of non-Google search engines

Offtopic, but you may like [Searx](https://asciimoo.github.io/searx/) in this case. :-)

**Comment by andrin55** [comment]
Searx looks promising. But Bromite would need a function to add custom search engines...

**Comment by andrin55** [comment]
> FYI, slightly related, I coded in also this patch: https://github.com/bromite/bromite/blob/master/patches/privacy/remove-google-click-tracking.patch

Does that extract the link from the Google redirect? If yes when does it do so:
![image](https://user-images.githubusercontent.com/2856476/31756692-8d7b0d2e-b4a5-11e7-8a51-3877575f5d7f.png)

Long pressing on the "The Decline of Wikipedia" search result shows me the Google redirect link instead of the real one. Does it replace the link after clicking on it?

**Comment by csagan5** [comment]
> Searx looks promising. But Bromite would need a function to add custom search engines...
Sorry, but it's so bad that hurts eyes to look at those results...nobody would use it. I am afraid we are ages away from a search engine that is decent, open source and not profiling you.

**Comment by csagan5** [comment]
> Long pressing on the "The Decline of Wikipedia" search result shows me the Google redirect link instead of the real one. Does it replace the link after clicking on it?

@andrin55 no you're right, the patch I added is incomplete :( thanks for reporting this. I missed the href being changed because it's correct in the original source, then JS must be changing it

**Comment by andrin55** [comment]
> I knew about Searx. Sorry, but it's so bad that hurts eyes to look at those results...nobody would use it. I am afraid we are ages away from a search engine that is decent, open source and not profiling you.</offtopic>

Well you could create a custom skin for it. But I get your point google looks much better.

**Comment by csagan5** [comment]
Yeah, not just esthetic, I am afraid the quality of results is so bad that practically people wouldn't use it even if it were an available option. For now DuckDuckGo and StartPage will do.

**Comment by csagan5** [comment]
Closed via 256fe0ec37742c277d04299d1016496338e24687

**Comment by a-silvia** [comment]
Sorry for piping in on this thread but I wanted to voice support for the request to add searx into the available list of search engines!

**Comment by voxitme** [comment]
> Sorry for piping in on this thread but I wanted to voice support for the request to add searx into the available list of search engines!

+1 here. Provided many instances are there ([see here](https://searx.space/) ), I think the custom search adding functionality as this is implemented is just fine.
However, I noticed a weird behavior in Bromite as well as every chromium-android builds I tried : searx (0.17), and whatever the instance is, doesn't show up in "recently visited" in the custom search adding menu.
Whereas on ungoogled-Chromium-windows it does.
However, it works for some other engines I tried, eg duckduckgo.
Do you have any idea about what's going on with this @csagan5 ?
