### ISSUE TITLE
Unable to login to Google account v74

### ISSUE THREAD

**Issue by AlternativeZero** [bromite/bromite#300]
**Bromite version**

Version: `74+`
Arch: arm64
Android version: Pie

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
It's a SystemWebView issue.

**Is the bug a crash?**
No.

**Describe the bug**
When logging into a Google account, it get's stuck after hitting I agree and doesn't continue, this issue doesn't appear on v73.

**To Reproduce**
1. Login to a google account
2. Input email and password
3. Click "I agree"
4. Stuck in endless loop

**Expected behavior**
Successful login and added new google account.

**Screenshots**
![Screenshot_20190508-190534_microG_Services_Core](https://user-images.githubusercontent.com/32092294/57363505-9642ce00-71c4-11e9-91a4-a28294dc5a7e.png)

**Comment by csagan5** [comment]
I cannot reproduce this issue; please use the remote debugging features to see what is the error in console

**Comment by AlternativeZero** [comment]
I have a logcat on the original issue I made on the [microg page](https://github.com/microg/android_packages_apps_GmsCore/issues/770) since I thought it was a problem with it, could you take a look and see if what I provided exampled the problem?

**Comment by csagan5** [comment]
I had already seen that, this is not an error logged in the logcat. Most likely it's a Javascript error.

You need to use this: https://developers.google.com/web/tools/chrome-devtools/remote-debugging/

**Comment by AlternativeZero** [comment]
I tried but couldn't get anything to show up when logging in through settings to add an account, logging in through the brower works fine, sorry.

**Comment by csagan5** [comment]
Accounts are not supported, see README

**Comment by AlternativeZero** [comment]
But it was working normally on v73 and before.

**Comment by csagan5** [comment]
@AlternativeZero it still works fine.

To see why it's not working in your case you would have to use this: https://developers.google.com/web/tools/chrome-devtools/remote-debugging/

**Comment by wilmarcdw** [comment]
His login issue isn't Bromite specific. Pretty much anyone with microG and Chrome/Chromium webview v74 is having login issues. Currently the only workaround is to downgrade (uninstall updates) to v73 or earlier. Once logins are successful one can go back up if desired.

**Comment by csagan5** [comment]
@wilmarcdw ok, thanks for mentioning that. I had not noticed this was about the SystemWebView.

All issues submitted here should be about the browser, the SystemWebView is provided as-is.

Also this section of the bug report is misleading:

> **Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
> It's a SystemWebView issue.

Even if it is a SystemWebView issue you can test with the Chromium SystemWebView to verify whether it's a Bromite-specific issue or not; as @wilmarcdw reports this is not.
