### ISSUE TITLE
Bookmarks export doesn't work on v74.0.3729.141

### ISSUE THREAD

**Issue by zongou** [bromite/bromite#301]
**Bromite version**

Version: 74.0.3729.141
Arch: arm64
Android version: pie

**Describe the bug**
Bookmarks export doesn't work on my device, it shows me a page telling my file was not found

**To Reproduce**
1. Go to bookmarks
2. Click on export
3. See error

**Expected behavior**
Should create a html file

**Screenshots**

**Comment by csagan5** [comment]
You need to grant write permissions first through some other means; try saving a download for example.

After that bookmarks export will show you the HTML file.
