### ISSUE TITLE
Possibility to choose to use 1.0.0.1 in Cloudflare "DNS over HTTPS" setting instead of 1.1.1.1

### ISSUE THREAD

**Issue by iz8mbw** [bromite/bromite#305]
**Bromite version**

Version: `74.0.3729.154`
Arch: `arm64`
Android version: ... (example: `8 - Oreo`)

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
`Bug must NOT be reproducible with Chromium to be qualified as a Bromite bug`

**Is the bug a crash?**
No

**Describe the bug**
Hi.
Since my mobile operator blocks ALL traffic to 1.1.1.1 I cannot use Cloudflare for "DNS over HTTPS" in Bromite.
Luckily 1.0.0.1 is not blocked.
How is it possible to "specify" to Bromite to use 1.0.0.1 in Cloudflare "DNS over HTTPS" setting?
Thank you!

**To Reproduce**
You should try to block traffic to 1.1.1.1 and you are unable to use Cloudflare for "DNS over HTTPS"

**Expected behavior**
Possibility to choose to use 1.1.1.1 or 1.0.0.1 in Cloudflare for "DNS over HTTPS" setting.

**Comment by csagan5** [comment]
This is a feature request, not a bug; it might be possible in the future if somebody implements customisation of the DoH endpoint but it's not currently planned.

I am sorry for your situation but you can try using another DoH provider or building a custom version.

**Comment by iz8mbw** [comment]
Ok, it can be a 'feature request', but if Cloudflare has two different IP for DNS, why Bromite use only 1.1.1.1?
I expect, as for about all systems, that if primary DNS (1.1.1.1) does not work, Bromite will try on secondary DNS (1.0.0.1).
So Bromite will use only and always 1.1.1.1. 
And this is not a bug?

**Comment by iz8mbw** [comment]
Just to clarify, I expect that Bromite will "mark" 1.1.1.1 as unavailable and switch to 1.0.0.1 if after some seconds 1.1.1.1 is unreadable or does not answer to DoH requests.

**Comment by ouzowtf** [comment]
If Chromium has only one IP for an alternate DNS, someone has to implement a routine for saving and using a second IP. If csagan5 does not want to do this or has no time for this, we should be perfectly fine with it or you could provide a pull request for it.
The browser doesn't know automagically of a maybe existing second IP for your DNS provider, if the first one is not reachable.

**Comment by iz8mbw** [comment]
Personally I don't have skills to do that PR. Anyway I reported to you that behavior and I hope when you have time if you can do some to avoid my problem. Thank you!
