### ISSUE TITLE
Place exported bookmarks in the “Mobile bookmarks” folder

### ISSUE THREAD

**Issue by zongou** [bromite/bromite#306]
**Is your feature request related to privacy?**
Not related to privacy, just for the convenience of use

**Is there a patch available for this feature somewhere?**
kiwi browser could do that
https://github.com/kiwibrowser/android
I want the same function as it has
**Describe the solution you'd like**
Place the exported bookmarks in the folder “Mobile bookmarks”，so I don't need to move bookmarks to it manually.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you have considered.

**Comment by csagan5** [comment]
No, thanks.

You can either use Kiwi or move them manually.
