### ISSUE TITLE
Does not recognize phone model correctly

### ISSUE THREAD

**Issue by zongou** [bromite/bromite#307]
**Bromite version**

Version: `74.0.3729.162`
Arch:  `arm64`
Android version: ..pie
**Is the bug reproducible with latest version?**
`yes`

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
`no, only appears with bromite
**Is the bug a crash?**
No

**Describe the bug**
Doesn't show correct phone model in settings, it recognize my phone as "ONEPLUS A6000", but my cellphone is "MI 8",and it affects browser  user agent as well, I have tested that on echo.opera.com

**To Reproduce**
1. Go to 'settings'
2. Click on 'about bromite'
3. See error

**Expected behavior**
Should show the correct cellphone [model](url)

**Screenshots**
If applicable, add screenshots to he
![Screenshot_2019-05-19-05-54-02-055_org bromite chromium](https://user-images.githubusercontent.com/23202896/57975391-96c83980-79fa-11e9-9352-af296ac5385d.png)
![Screenshot_2019-05-19-05-53-54-008_org bromite bromite](https://user-images.githubusercontent.com/23202896/57975392-9760d000-79fa-11e9-8a45-d6633f521a3a.png)

**Comment by csagan5** [comment]
Working as intended.
