### ISSUE TITLE
Error installing Bromite: repo failed to verify

### ISSUE THREAD

**Issue by luontokoodaus** [bromite/bromite#308]
**Bromite version**
Version: Latest
Arch: arm64
Android version: 8.0

**Is the bug reproducible with latest version?**
Yes

**Is the bug a crash?**
No

**Describe the bug**
The bug shown in the screenshot below prevents me from being able to install the app. I have added the repo link correctly, including the fingerprint.

My device is rooted and running Android 8.0. I have also tried clearing the F-Droid cache and redownloading F-Droid.

**To Reproduce**
1. Go to F-Droid and add the repository
2. Type in Bromite
3. Click install

**Expected behavior**
Expected I can download and install the app from F-Droid

**Screenshots**
Screens:
1. https://i.imgur.com/267zXL9.png
2. https://i.imgur.com/6BLLscJ.png

----------------------------------

It seems there are quite a few other threads about this dating back quite a long time. I've a feeling it's something to do with my device being rooted.

1. https://github.com/bromite/bromite/issues/241
2. https://github.com/bromite/bromite/issues/161
3. https://gitlab.com/fdroid/fdroidclient/issues/728
4. https://github.com/bromite/bromite/issues/261
5. https://forum.xda-developers.com/android/apps-games/app-bromite-chromium-plus-adblocking-t3687258/page121

As this is happening to quite a few people. I would suggest maybe trying to talk to the F-Droid devs about why this happens, as this literally prevents people from being able to download the app at all.

**Comment by csagan5** [comment]
The storage reason mentioned in https://gitlab.com/fdroid/fdroidclient/issues/728 is one possible reason. Another reason I have read about is when permissions declared by the APK differ from those declared in the repository; this is not the case for Bromite.

> As this is happening to quite a few people. I would suggest maybe trying to talk to the F-Droid devs about why this happens, as this literally prevents people from being able to download the app at all.

This would not work at all, since I cannot reproduce the issue and I cannot be of any help in troubleshooting. You should open an issue upstream or comment on an existing one once you have individuated the exact problems using the F-Droid logs from logcat.

You did a good job tracking previous similar issues however this issue tracker is for Bromite issues so I suggest trying to address it upstream as there is literally nothing I can do to help with it.

**Comment by luontokoodaus** [comment]
I've solved this issue myself.

This is how the repository should be listed in F-Droid **exactly**: https://i.imgur.com/YRdWu0R.png
_Compare this to the second image I sent in my first post in this thread, and you will see what the problem was (signature was included in the URL box and again in the signature box)_

The cause is simply just confusion on my part (and it seems so for others too) as to how the URL should be entered into F-Droid and also what I suggested before. It's a verification missmatch that occurs because the signature is present in both the URL (top box in screenshot) and in the fingerprint box. Removing the trailing signature from the URL and formatting it as shown in the screenshot works fine.

The app shows up correctly along with its icon and is downloadable.

@csagan5 I am quite surprised you did not notice the problem in the second image I sent, that the URL is in fact wrongly set. I suggest perhaps adding clearer instructions to the bromite repo page that the signature is NOT to go into the first box where the repo URL is to be entered, but only in the bottom. It's a bit confusing because you changed the URL to include the signature, but F-Droid won't accept the signature in the URL.

**Comment by csagan5** [comment]
> I am quite surprised you did not notice the problem in the second image I sent (and even in the posts of others I linked), that the URL is in fact wrongly set

You mean in this image? https://i.imgur.com/6BLLscJ.png
There is only the URL displayed there, not the fingerprint box **and** the URL box. That would perhaps give away some redundancy, but it is still a completely fine URL for the repository.

Also, I fail to understand why you expect me to be an expert or even knowledgeable of the F-Droid client.
I still think F-Droid client should handle this URL gracefully.

In fact when I add the repository by copying the link to the clipboard it works fine for me, as F-Droid client recognises it automatically and pre-fills the boxes. You have to go our of your way and paste again the URL in the URL box while the fingerprint box is still populated.

You should ask for a fix upstream e.g. the fingerprint should be automatically removed from the URL if it is in the URL box.

Explain them how to reproduce the error, the F-Droid client version etc.

There are pretty high chances somebody reported it already.

> This would not have happened if we weren't expected to copy-paste the QR code's URL into F-Droid

As I said, it works fine if you let F-Droid automatically get it from the clipboard. I cannot be aware of all bugs of the F-Droid client (trust me, there are a few, check their issue tracker) if they do not happen while I use it and every user can have a different usage path that triggers different bugs.

I will add a clarification to the website, but I believe that is not the solution, the solution would be a usability bugfix upstream.

**Comment by looeee** [comment]
I'm experiencing the same issue.
