### ISSUE TITLE
Bromite crashing when downloading pictures or files

### ISSUE THREAD

**Issue by Asbesbopispa** [bromite/bromite#309]
**Bromite version**

Version: `75.0.3770.50`
Arch: `arm64`
Android version: `Pie LineageOS 16`

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
Nope, it works in Chromium

**Is the bug a crash?**
Yes, there's the [logcat_05-23-2019_13-59-14.txt](https://github.com/bromite/bromite/files/3212017/logcat_05-23-2019_13-59-14.txt)

**Describe the bug**
Bromite crashes when I try to download any pictures or files.

**To Reproduce**
1. Go to a random website
2. Long-press on a random picture
3. Save it
4. Crash

**Expected behavior**
It should save pictures or files without any problems.

**Screenshots**
![Screenshot_20190523-140449_Bromite](https://user-images.githubusercontent.com/31346754/58251620-56ebb400-7d64-11e9-9834-563acd382d75.png)
![Screenshot_20190523-140457_Bromite](https://user-images.githubusercontent.com/31346754/58251623-58b57780-7d64-11e9-8889-2cc0bccfd127.png)

**Comment by csagan5** [comment]
I have verified this bug and it appears to be related to the adblock filter; I am working on a solution for next release.

**Comment by Asbesbopispa** [comment]
I tried to download a picture without enabling the adblock filter and it works, as you wrote. As always, thank you for your amazing work!

**Comment by csagan5** [comment]
Fixed in `75.0.3770.53`.

**Comment by Asbesbopispa** [comment]
Just updated the browser, I can download pictures and other things without problems now.
