### ISSUE TITLE
Google webview 

### ISSUE THREAD

**Issue by DenyDarko** [bromite/bromite#312]
**Is your feature request related to privacy?**
Νο

**Is there a patch available for this feature somewhere?**
Unfortunately No

**Describe the solution you'd like**
Many official build roms do not include com.android.webview but expecting com.GOOGLE.android.webview inside framework res as package name. 

Is there a possibility that you can produce a release with that package name as alternative? 

**Describe alternatives you've considered**
There aren't any. 
Perhaps patching framework-res file which I don't have the knowledge to do.

**Comment by csagan5** [comment]
See https://github.com/bromite/bromite/wiki/Installing-SystemWebView#about-the-package-name
