### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by tw-e** [bromite/bromite#314]
**Is your feature request related to privacy?**
Yes!

**Is there a patch available for this feature somewhere?**
Yes!

**Describe the solution you'd like**
1.DOH or DOT
Can you add quad101 dns to the built-in browser?
https://blog.twnic.net.tw/2018/12/28/1803/
https://blog.twnic.net.tw/2018/07/02/1086/
He is a Taiwanese language, so you will have to translate it yourself into English.

2.Can you add these two rules for reinforcement?
Fanboy's Enhanced Trackers List
AdGuard Tracking Protection filter

**Describe alternatives you've considered**
No!

**Comment by csagan5** [comment]
Quad101 does not even have a valid certificate on their website https://china-pharm.ru/ (which I assume it's the official one).

**Comment by tw-e** [comment]
This is the official address:
https://101.101.101.101/index_en.html

**Comment by csagan5** [comment]
@tw-e do they have a privacy policy document that explains how exactly they will treat the data they collect? If yes, where is it? It is not linked from that page.

**Comment by tw-e** [comment]
@csagan5 
I haven't seen it yet, but only the middle section is very simple. If you don't think so, skip this section first.
