### ISSUE TITLE
how to install bromite SystemWebView on Android 4.4 ?

### ISSUE THREAD

**Issue by DiegoRRR** [bromite/bromite#315]
Hi

Please give me a link to download the SDK19 build.
On my computer, I can't select SDK19 build, it is disabled.
On my tablet, SDK19 build is selected by default, but I can't get it, as soon as it is downloaded it deletes it because it says the file is harmful...

Then, there is no /system/app/webview folder in Andoid 4.4, and the webview was not an apk in Android 4.4...
So how can I install it, please ?

**Comment by csagan5** [comment]
@DiegoRRR you might want to ask this on XDA/Reddit, I do not offer support for installation of the SystemWebView
