### ISSUE TITLE
Support For Extensions

### ISSUE THREAD

**Issue by icejr** [bromite/bromite#316]
**Is your feature request related to privacy?**
Yes, By adding support for extensions users can use numerous privacy extension (ex. UblockOrigin, HTTPS Everywhere, Privacy Badger and many more)

**Is there a patch available for this feature somewhere?**
Yes, Kiwi Browser has support for extensions and it's based on Chromium. They have a repo on their github.

**Describe the solution you'd like**
Request to devs to add extension support.

**Describe alternatives you've considered**
Two channels of bromite, one with extension support and one without.

**My personal reasons**
I personally don't like Kiwi because it's not very privacy friendly. But they have extension support which is cool but I still prefer Bromite and recommend to everyone. Will be happy if bromite gets extension support. And users can add their own adblock list through Ublock.

**Comment by csagan5** [comment]
Sorry, but I am not committing to the development of extensions for Chromium/Bromite on Android.

> They have a repo on their github.

Please report back the patches needed to get **working** extensions on Chromium for Android and I might check them out; as far as I know there is none available online.
