### ISSUE TITLE
crash with bromite system webview after playing media.

### ISSUE THREAD

**Issue by ort163** [bromite/bromite#317]
**Bromite version**

Version: `75.0.3770.82.`
Arch: `arm`
Android version: ... nougat (lineageos)

**Is the bug reproducible with latest version?**
`Bug must be reproducible with latest version` Yes

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**  NO

With chrome system webview from 'google play' works fine. 
Also OK with AOSP webview from AOSP(!)

**Is the bug a crash?**

yes. `adb logcat`
 .
`libc: Fatal signal 7 (SIGBUS), code 0, fault addr 0x94e567f6 in tid 9971 (Chrome_IOThread)
`

**Describe the bug**

**To Reproduce**
1. Go to '...' http://loan-trading.net/sa-re-ga-ma-pa/?sin=ef2tkqds0r0s
2. Click on '....' Play video
3. Now press back button
4. App/webview stops. Open app again or Mute until device restarts

**Expected behavior**

No crash.

**Screenshots**

**Comment by csagan5** [comment]
@ort163 I cannot use that single line of the logcat, please post the whole debug section (you can remove privacy-sensitive details)
