### ISSUE TITLE
User-defined DoH/DoT server addresses

### ISSUE THREAD

**Issue by tw-e** [bromite/bromite#320]
**Is your feature request related to privacy?**
Yes

**Is there a patch available for this feature somewhere?**
No

**Describe the solution you'd like**
Can you open the user-defined input "DOH" or "DOT" server address?

**Describe alternatives you've considered**
None

**Comment by csagan5** [comment]
I am not going to develop an user interface for this feature; if somebody comes up with a patch and it's of good quality, I might integrate it.
