### ISSUE TITLE
PAC proxy field is empty after reloading/opening proxy config page or saving setting

### ISSUE THREAD

**Issue by r4sas** [bromite/bromite#323]
**Bromite version**

Version: `75.0.3770.86`
Arch: `arm64`
Android version: 8.1.0
**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No, cause it's Bromite feature.

**Is the bug a crash?**
No

**Describe the bug**
I'm filling proxy list in PAC format for all schemes, but after applying changes or reloading proxy settings page field becomes empty but dotted selector leaves on saved place.

**To Reproduce**
1. Open proxy configuration page
2. Select configuration type (for example set dot on ` Use single proxy list for all schemes` setting)
3. Fill field with PAC configuration.
I tested it with that rule:
```
function FindProxyForURL(url, host) {
  if (isPlainHostName(host)) {
    return "DIRECT";
  } else {
    return "PROXY 127.0.0.1:3128";
  }
}
```
4. Press `Apply` button

**Expected behavior**
Edited field must be filled with current saved configuration

**Comment by csagan5** [comment]
@r4sas that is not a PAC rule, that is a script. You can only enter PAC rules there.

**Comment by r4sas** [comment]
According to project's wiki:
> The proxy lists must be specified in PAC format.

Link points to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_(PAC)_file#Description), where exaples written as scripts.
Or here we need to write only return value, like `PROXY 127.0.0.1:3128`?

**Comment by csagan5** [comment]
@r4sas there are examples also on the wiki, none as scripts.

**Comment by r4sas** [comment]
Thank you.
