### ISSUE TITLE
Option to toggle CSS

### ISSUE THREAD

**Issue by PeterBadzhakov** [bromite/bromite#324]
**Is your feature request related to privacy?**
Yes - various ways of extracting data/user input via CSS have been found. Mainly interested in aesthetic and peformance boost.

**Is there a patch available for this feature somewhere?**
None I've found.

**Describe the solution you'd like**
A complete analogy to the JavaScript toggle button, but for CSS. Or anything close.

**Describe alternatives you've considered**
Using mobile firefox - Bromite is considerably a faster browser overall.
Forking Bromite and neutering the CSS parser - Impossible to maintain.

**Comment by csagan5** [comment]
This is unrelated to privacy; the best you could do is submit a patch that adds an option for it, but it would not be on the burger menu.

**Comment by Madis0** [comment]
@PeterBadzhakov Try the option "simplified view for web pages" under accessibility settings.
