### ISSUE TITLE
S-Pen remote not recognized

### ISSUE THREAD

**Issue by Qik000** [bromite/bromite#325]
**Bromite version**

Version: 75
Arch: arm64
Android version: Pie

""Screenshots**
![Screenshot_20190625-001335_Air command](https://user-images.githubusercontent.com/32220535/60055797-1672b380-96df-11e9-8a88-8c514ffeeb51.jpg)

**To Reproduce**
1. Go to bromite
2. Click on spen button
3. It says that spen remote is not compatible with the app

**Expected behavior**
The remote should function like in chrome, 1 click for back and double click for forward

**Comment by csagan5** [comment]
> It says that spen remote is not compatible with the app

You should ask the vendor of S-Pen to add support for Bromite.
