### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by tw-e** [bromite/bromite#326]
**Is your feature request related to privacy?**
No!

**Is there a patch available for this feature somewhere?**
No!

**Describe the solution you'd like**
Hi,
Can the order of the menus be rearranged?
![Screenshot_20190625-151623_Chrome Beta](https://user-images.githubusercontent.com/51475468/60090087-6bacd480-9774-11e9-93bc-115f0fb5ddc0.jpg)
![Screenshot_20190625-152432_Bromite](https://user-images.githubusercontent.com/51475468/60090119-79faf080-9774-11e9-86da-5252c1b20277.jpg)
I mean, as far as possible in the order of the original version? Can you?

**Describe alternatives you've considered**
No,

**Comment by csagan5** [comment]
@tw-e they are better in the current order.
