### ISSUE TITLE
Custom ad-blocking rules

### ISSUE THREAD

**Issue by alekksander** [bromite/bromite#33]
Cannot find any todo/roadmap in this repo. When aprox. is it planned to introduce custom blocking rules? i'd love to import few of  my ublock lists and then try to use this browser instead of so—so firefox.

**Comment by csagan5** [comment]
I opened initially this feature request here: #2 

However I closed it because we would never support DOM-based rules; I would still add it (or accept patches for it) if I had the time and patience.

The biggest problem is that one would need to bake-in some UI to manage the filters. Not trivial.

**Comment by dimqua** [comment]
@csagan5 will it work for Bromite's SystemWebView?

**Comment by DI555** [comment]
@dimqua , if it will work thrue the page smth. like 'about:adblock', I hope so ;)

**Comment by csagan5** [comment]
@dimqua I did not read your question back then; it is needed some UI to manage the adblock filters.

I merge this issue to #2
