### ISSUE TITLE
speeddial 

### ISSUE THREAD

**Issue by franco27** [bromite/bromite#334]
I'd like a speeddial in Bromite.  
To be able to pin websites.

thanks

**Comment by franco27** [comment]
Apparently, you don't want to add this feature. It's a shame!  I uninstall then.

**Comment by ouzowtf** [comment]
Your comment is a shame and I'm sure nobody will miss your installation :shrug:

**Comment by franco27** [comment]
I don't see why you don't like my comment. I express my dissatisfaction.  

No written explanation for the reason. We close it and that's it!
