### ISSUE TITLE
UA constantness

### ISSUE THREAD

**Issue by DI555** [bromite/bromite#337]
**Is your feature request related to privacy?**
Features that are not related to privacy are unlikely to be considered.

Yes, browser always skips to mobile UA, not possible to work normally((

**Is there a patch available for this feature somewhere?**

Yes, Brave team solved this problem in Q4, 2018.

**Describe the solution you'd like**

Need to be that 'Desktop UA' switch be remembered, once it switched on or switched off. And great to be a setting of default UA in options -> site settings .
And very needed two flags with string values for that 'Mobile UA' and 'Desktop UA' .

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you have considered.

Each time need to go to menu and press 'Desktop UA' mode.

**Comment by csagan5** [comment]
> Yes, Brave team solved this problem in Q4, 2018.

Did you locate the patch?

**Comment by DI555** [comment]
I searched brave repos now,  and seems they hide it or inject it in a bigger one((
But I'm pretty sure that they solved that problem last year Q4(just without possibility of write ua strings in flags).
But they won't fix a problem without a patch, yes?

**Comment by DI555** [comment]
I found here
https://github.com/brave/browser-android-tabs/pull/391/commits
and alittle here
https://github.com/brave/browser-android-tabs/pull/379

**Comment by csagan5** [comment]
@DI555 this feature request is not about privacy, and there is not an easily available patch; thus there is really no interest to develop and maintain this feature for the lifetime of Bromite project.

**Comment by DI555** [comment]
Wow, the desicion to decide what ua is in use by user, it's imo a privacy...
Ok. But do you accept a FR about just 2 flags with strings for these mobile and desktop modes? Honestly, very uncomfortable when browser always skips to mobile mode((.
