### ISSUE TITLE
Extensions support, patch

### ISSUE THREAD

**Issue by DI555** [bromite/bromite#338]
**Is your feature request related to privacy?**
Features that are not related to privacy are unlikely to be considered.

yes, extensions may enforce privacy to a higher level

**Is there a patch available for this feature somewhere?**

yes

https://github.com/kiwibrowser/privacy_patches/blob/master/Add-support-for-extensions-on-Android.patch

Imho, if this patch is workable, it should be forked here, because this patch is a revolution;)!
And it should be developing more and polishing!
I grabed it here:
https://github.com/kiwibrowser/privacy_patches

**Describe the solution you'd like**

support of browser extensions on android platform

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you have considered.
User.js support, but it's only some kind of part of extensions(

**Comment by csagan5** [comment]
That is a scam; that patch is not usable.

**Comment by zsoltsandor** [comment]
Sorry for reopening this issue, but it might be worthwhile to check on this, reconsider again. 
I have been using Bromite for a while, but I'm definitely missing the extension support. I used Yandex browser for that, but it has its own issues, or Firefox, but that doesn't integrate well.
Then I found Kiwi. 
Scam, or not the usage shows that the extension support does work.
Please see the attached screenshots (sorry they are in Hungarian, but the important info is visible). 
![Screenshot_20200103-205928_Kiwi_Browser](https://user-images.githubusercontent.com/4585996/71746200-87540e80-2e6c-11ea-9f0a-3e441b640392.png)
![Screenshot_20200103-210037_Kiwi_Browser](https://user-images.githubusercontent.com/4585996/71746201-87eca500-2e6c-11ea-9530-9f777ecbdda4.png)
![Screenshot_20200103-205940_Kiwi_Browser](https://user-images.githubusercontent.com/4585996/71746203-87eca500-2e6c-11ea-8a76-bf8b61f70172.png)
![Screenshot_20200103-205953_Kiwi_Browser](https://user-images.githubusercontent.com/4585996/71746204-87eca500-2e6c-11ea-815b-6db5eb046586.png)

**Comment by zsoltsandor** [comment]
Also, a screenshot from a root file manager, so you can see that the extension folders are there indeed. 
![Screenshot_20200103-211639_File_Manager](https://user-images.githubusercontent.com/4585996/71746967-b53a5280-2e6e-11ea-82b7-a6ff793cce66.png)

**Comment by csagan5** [comment]
@zsoltsandor there is no patch available and I am not going to develop and maintain one. How do we solve it?

**Comment by zsoltsandor** [comment]
Apparently Brave is planning something similar, and it was suggested for Vivaldi too. I suppose Brave would publish the patch accordingly.
