### ISSUE TITLE
Crash when accessing vugu.org

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#339]
**Bromite version**

Version: `75.0.3770.132`
Arch: `arm64`
Android version: `pie`

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No

**Is the bug a crash?**
Yes; logcat dump not yet available.

**To Reproduce**
1. Go to www.vugu.org
2. Scroll down a bit
3. See crash

**Comment by csagan5** [comment]
> **Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
> No

I was mistaken; this can also be reproduced with Chromium, although it might be related to the build flags or safe mode.

**Comment by csagan5** [comment]
@thestinger @wchen342 can you reproduce this crash with Vanadium/ungoogled-chromium-android?

**Comment by wchen342** [comment]
I tested on Lineage 16 (=pie) and yes, it crashes both vanilla and ungoogled chromium. The first crash actually nuked every background process, but the memory usage seems fine.

**Comment by thestinger** [comment]
It's triggered by memory exhaustion and I can reproduce the issue in Chrome on the stock OS too, so it should just be reported upstream.

**Comment by csagan5** [comment]
OK, thanks for checking @wchen342 @thestinger.

@thestinger feel free to report it upstream if you like; I will not.

**Comment by csagan5** [comment]
> I can reproduce the issue in Chrome on the stock OS too

FYI, I could not before creating this issue, and still cannot.

**Comment by thestinger** [comment]
@csagan5 Scroll up and down on the page a whole bunch. Also, make sure you actually have the latest stable release which is 75.0.3770.143 (https://chromereleases.googleblog.com/2019/07/chrome-for-android-update.html). I closely follow the upstream stable releases, but they use staged rollouts for their own deployments and it can take weeks before the releases reach 100% of people using the app. It's entirely possible that you're still on an older version despite staying up-to-date.

**Comment by csagan5** [comment]
@thestinger you're right, the testing device I was using had `74.0.3729.157` so that's why I could not reproduce it there.
