### ISSUE TITLE
Twitch is lagging a lot

### ISSUE THREAD

**Issue by ikuinenluuseripaska** [bromite/bromite#34]
When I'm watching twitch streams with bromite browser all the streams are lagging a lot, and I'm skipping frames like crazy. I don't have this issue on default chrome browser.

I'm using Arm64 build on nougat 7.0.

**Comment by csagan5** [comment]
Is this an issue on latest Bromite only? as said on the XDA forums I can make (after next release) a build with H264 optimizations disabled for you to test with.

**Comment by csagan5** [comment]
Please test with a pre-release version (https://github.com/bromite/bromite/releases/tag/64.0.3282.149) to see if still happens and report back.

**Comment by csagan5** [comment]
This was likely due to building the Beta channel of Chromium instead of the Stable channel as it should be; it has been since fixed.
