### ISSUE TITLE
Bromite Magisk Module

### ISSUE THREAD

**Issue by alexa-v2** [bromite/bromite#341]
@csagan5 Recently you and I were discussing making the Magisk module official

However, with no explanation you archived the upstream repository citing "radically different views on security and management", thereby making the ongoing discussion there impossible to continue

I'm intending to push my curl binaries _built from source_ in the next update to 3.8 but at the moment need to keep the module working

I will be more than happy to discuss our differences and come to a compromise over them. I'm eager to make this work, to meet you in the middle. I've done a bit so far to get this up to your standards, I'd be happy to go a bit further. Please advise me of any further concerns regarding the module

**Comment by alexa-v2** [comment]
And FYI I only forked your repo to make PRs to yours. Only way I know how to do it without the Magisk repo being a downstream. I commit to mine, and PR to yours

**Comment by alexa-v2** [comment]
Sorry for any misunderstanding @csagan5

**Comment by alexa-v2** [comment]
Waiting for a response on reproducible builds for the existing binaries currently

If I don't get one within a few days I'll look into building for Android from official source

**Comment by alexa-v2** [comment]
https://github.com/Zackptg5/Curl-for-Android-Build-Script

**Comment by csagan5** [comment]
@alexa-v2 please continue to maintain the module on your own, in an unofficial fashion. I have no interest to make it an official project.

**Comment by alexa-v2** [comment]
After all that sh*t you drug me through, now it's just this? Just get brushed off. Wow, think you're right, don't want anything to do with this team
