### ISSUE TITLE
AdBlocker not Working

### ISSUE THREAD

**Issue by PECONAUT** [bromite/bromite#343]
**Bromite version**

Version: 75.0.3770.139
Arch: arm64
Android version: Android 9 (Pie)

**Is the bug reproducible with latest version?**
Yes

**Describe the bug**
AdBlocker not working. Tested the same site with bromite and Fennec. Ads starting showing up in Bromite. I have AdBlocker enable via Magisk call Energized and still didn't matter 

**To Reproduce**
1. Go to [https://www.ratemyprofessors.com/g00/ShowRatings.jsp?tid=1242792&i10c.ua=1&i10c.encReferrer=aHR0cHM6Ly93d3cucmF0ZW15cHJvZmVzc29ycy5jb20vZzAwL1Nob3dSYXRpbmdzLmpzcD90aWQ9MTI0Mjc5MiZpMTBjLnVhPTEmaTEwYy5lbmNSZWZlcnJlcj0maTEwYy5kdj0xNQ%3d%3d&i10c.dv=15]
2. Wait a few
3. Ads appear

**Expected behavior**
Ads are supposed to be block

**Screenshots**
Video Expires in a week
https://filebin.net/1zu7tlyi8jrkbtmk/ScreenRec_20190727_064350.mp4?t=2utrgo4w

**Comment by csagan5** [comment]
You should report this issue to the uBlock origin maintainers; adblocker works fine.
