### ISSUE TITLE
Adblock detection protection

### ISSUE THREAD

**Issue by M86xKC** [bromite/bromite#345]
**Is your feature request related to privacy?**
Yes

**Is there a patch available for this feature somewhere?**
I don't think so!

**Describe the solution you'd like**
Adding an [(adblock) list](https://easylist-downloads.adblockplus.org/antiadblockfilters.txt) to Bromite, which blocks ad-block detection It is also very small (~20KB) ~500 rules

**Describe alternatives you've considered**
I not aware of any alternatives. Will be happy to hear your suggestions

Thank you for the great work 🤗

**Comment by beerisgood** [comment]
None add-on or config can prevent  that detection for 100%. If the site use element X to test, the add-on/ filter need to update too

**Comment by M86xKC** [comment]
@beerisgood that's also the case with adblockers. Websites use new types of ads and the filters need to be updated accordingly. No ?

**Comment by beerisgood** [comment]
Yes. It's always a cat-mouse game

**Comment by M86xKC** [comment]
@csagan5 Sorry for my ignorance!
I issued this from a git client not the desktop and the client does not support issue templates yet :)

**Comment by csagan5** [comment]
@M86xKC I had tried adding a similar list in the past, but it's not very effective because the Bromite adblock engine does not support advanced DOM rules.

I can try for next release, but not sure how much it would help.

**Comment by M86xKC** [comment]
Is this included in the current version ?
I still get pop-ups

**Comment by csagan5** [comment]
This will be possible with #2
