### ISSUE TITLE
Ability to change search settings

### ISSUE THREAD

**Issue by ZaphodBeeblebroxSr** [bromite/bromite#346]
**Is your feature request related to privacy?**

Maybe

**Is there a patch available for this feature somewhere?**

Yes

**Describe the solution you'd like**

I change my search settings in most browsers, mainly for night mode, and to have an unfiltered search. I set Startpage with a custom config URL as my homepage in Bromite, but since you added Startpage as a default, whenever I search with the address bar, it goes to the default white background search.

I can change the search engine to "Startpage Custom" in Firefox with their similar "Always Private" mode and a custom Startpage search.

**Describe alternatives you've considered**

I've enabled cookies for Startpage but it won't keep the cookies around the "clear cookies on exit" setting.

**Comment by csagan5** [comment]
Where is the patch you mention as available?

To save the search settings you will have to allow cookies; there is currently no way to store settings in URL and customisation of a search engine's URLs goes beyond the scope of Bromite (privacy & ad-blocking).

**Comment by ZaphodBeeblebroxSr** [comment]
It was working just fine before the last couple updates without cookies. I've also allowed cookies,  just for Startpage. Is there no way to remove the built in search engines so I can add my Startpage custom URL? That's how they tell you to do it without cookies.

Basically if it never worked, then that's fine, but I've never had cookies on and always had Bromite clear everything on exit, but only recently has it started doing this.

It's not an epic issue, I was just wondering is all.
