### ISSUE TITLE
Browser language error

### ISSUE THREAD

**Issue by OrcaStrike** [bromite/bromite#347]
**Bromite version**

Version: `76.0.3809.91`
Arch: `arm64`
Android version: `Marshmallow`

**Is the bug reproducible with latest version?**
`Yes`

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
`invalid`.

**Is the bug a crash?**
___

**Describe the bug**
Contents of browsers and website visible in Phone's system language instead of browser language(English) selected in Language section of settings.

**To Reproduce**
1. Go to 'Menu'

**Expected behavior**
I want contents of browser and website should visible in Browser selected language(English) instead of System language.

**Screenshots**
![Screenshot_2019-08-05-10-42-32-716_org bromite bromite](https://user-images.githubusercontent.com/53293465/62440804-4ea1f300-b76f-11e9-9ac7-a19bd9f00a1f.png)
![Screenshot_2019-08-05-10-39-00-965_org bromite bromite](https://user-images.githubusercontent.com/53293465/62440805-4f3a8980-b76f-11e9-91a8-71a1e77f0062.png)
![Screenshot_2019-08-05-10-38-52-776_org bromite bromite](https://user-images.githubusercontent.com/53293465/62440806-4fd32000-b76f-11e9-810e-6a22a3eeaac2.png)

**Comment by csagan5** [comment]
> `invalid`.

@OrcaStrike why did you write `invalid` here? What are the results of testing this issue with the corresponding Chromium version?

**Comment by OrcaStrike** [comment]
Well, I am not sure. I don’t have any exp on GitHub or writing or understanding code.
Since, there is not any other way to give any feedback.

“What are the results of testing this issue with the corresponding Chromium version?”
I don’t understand fully either. I think the answer should be yes or no. 
Look, my phone’s (Redmi 3S) system language is hindi and browser language is English, but still menu and some web content setting displayed in Hindi. As you saw in screeenshots.


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
