### ISSUE TITLE
Always incognito mode enhancements

### ISSUE THREAD

**Issue by miladmaz12** [bromite/bromite#349]
**Is your feature request related to privacy?**
Yes

**Is there a patch available for this feature somewhere?**
No

**Describe the solution you'd like**
Is there a way for incognito mode to work on third party Chrome Custom Tabs support? Where I can click a link on an app and it goes to incognito?

Also, when always incognito mode is enabled on the Bromite app it crashes main regular new tab, what if the user still wants to be in incognito mode while wanting to go use the regular new tab?

**Describe alternatives you've considered**
N/A

**Comment by csagan5** [comment]
> Is there a way for incognito mode to work on third party Chrome Custom Tabs support?

I had attempted to add support for this, but it was not possible.

> Also, when always incognito mode is enabled on the Bromite app it crashes main regular new tab, what if the user still wants to be in incognito mode while wanting to go use the regular new tab?

There is already an issue open for this.
