### ISSUE TITLE
Night mode feature

### ISSUE THREAD

**Issue by pdimri** [bromite/bromite#35]
I really like the browser and using it. I am really looking for night mode feature like caf based browsers have. Any plan to include the night mode feature .

**Comment by csagan5** [comment]
See also #5. This has been asked many times, no plans to add it for now.

**Comment by pdimri** [comment]
Yes you can include the night mode on /off in the settings.

**Comment by csagan5** [comment]
This is a very popular feature request however it has nothing to do with improving the privacy of browsing, so I am not sure it fits for this project. I am sorry but I am closing this as there are no plans to implement it
