### ISSUE TITLE
URL box request

### ISSUE THREAD

**Issue by jungleballs** [bromite/bromite#350]
After the new update, when I click the URL box, it erases the URL and gives me a drop down menu. I'm not able to edit the URL of the page I'm on. Is there any way to change this so I can edit URLs?

**Comment by Zoraver** [comment]
In chrome://flags, set #enable-search-ready-omnibox to disabled.

**Comment by csagan5** [comment]
I will see to change the default, but @jungleballs all issues must be submitted with the correct template.
