### ISSUE TITLE
Search suggestion not working

### ISSUE THREAD

**Issue by user456532** [bromite/bromite#351]
When i start typing i can't see the suggestions. I am using Google search engine.
How can i activate it?
![Screenshot_2019-08-10-19-27-44-953_org bromite bromite](https://user-images.githubusercontent.com/53977065/62824348-08042c80-bba5-11e9-8218-f67d20cd32d1.png)
![IMG_20190810_192654](https://user-images.githubusercontent.com/53977065/62824349-089cc300-bba5-11e9-805a-9aa1eb868d25.jpg)

As you can see con the first picture ut should appear "bromite" in dropdown menu but it's not available

**Comment by csagan5** [comment]
@user456532 issues must be submitted with the issue template.

I will look into this problem, it is due to some upstream re-arrangement of the menu entries that makes them hidden by default in Bromite.

**Comment by csagan5** [comment]
Fixed in `76.0.3809.115`
