### ISSUE TITLE
Cannot install Bromite WebView again after it was removed

### ISSUE THREAD

**Issue by timaschew** [bromite/bromite#352]
**Bromite System WebView**

Version: `76.0.3809.100`
Arch: `arm` 
Android version: Lineage OS 16 (Android 7.1.2 + Magisk)

**Describe the bug**
I was able to install the System WebView once, after I've deleted it I was not able to install it again.

**To Reproduce**
1. Stop and Disable Android System WebView
2. open terminal rename original webview in /system/app/webview
3. copy Bromite WebView to /system/app/webview/webview.apk
4. reboot (Android WebView is gone, not listed in Apps, show system apps checked)
5. open terminal and run `pm install webview.apk`
6. verify Bromite is listed in the Apps
7. uninstall Bromite WebView and activate Android System WebView again
8. do steps 1-6 again, but not installation of Bromite doesn't work anymore

The error is: **com.android.webview signatures do not match the previously installed version; ignoring!**

BTW: I uninstalled Bromite WebView because I was not able to select it as the system-wide WebView implementation. Now I want to try it with the **/system/app mover** but I'm not able to

**Comment by csagan5** [comment]
@timaschew you might have better luck on XDA Forums or Reddit, I only provide the System WebView build but I cannot help with it.

I think something is missing in your report: perhaps there was a Chrome webview active before, so the Android Webview `com.android.webview` had never been activated before. Once it has been activated then Android will remember and pin the signature, which does not match for Bromite SystemWebView (same package name `com.android.webview`).
