### ISSUE TITLE
Freezing on webpages (loss of scrolling)

### ISSUE THREAD

**Issue by aluo-x** [bromite/bromite#353]
**Bromite version**

Version: `76.0.3809.100`
Arch: `arm64`
Android version: 9.1

**Is the bug reproducible with latest version?**
It has been repeatable since Bromite 75, and persists on the latest version without any setting or flag changes. Also occurs with adblock disabled

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No, issue does not occur on corresponding Chromium version

**Describe the bug**
When scrolling to a section of an webpage, scrolling using one finger becomes ineffective and the page can only be moved using 2 finger zoom. Page becomes very laggy, refreshing the page allows scrolling again, until you scroll to the same position and the page freezes again.

**To Reproduce**
1. Go to https://m.aliexpress.com/
2. In the top search bar, search for any term. An example will be to search for 'laptop'
3. Click on any listing, scrolling quickly down to the very bottom and up the page of product listing
4. Page freezes
5. Also occurs on certain sites using Discus

**Expected behavior**
Ideally the page should not freeze.

**Comment by aluo-x** [comment]
Additionally, I believe this bug happened simultaneously with an increase of graphical glitches during tab switching. Sometime during Bromite 75 and persisting to 76, tab switching on slow network connections (when pages are loading), causes the tab switches to freeze and graphical artifacts (edges of the tab to persist) during tab flicking.

**Comment by csagan5** [comment]
Related: #284

**Comment by aluo-x** [comment]
I admit I am not really familiar with the Android/Chromium debug and build process, but I wonder how realistic it would be time wise to bisect the bug to a specific commit, or potentially to an individual patch.

**Comment by csagan5** [comment]
@aluo-x there is an incredible amount of commits from upstream, and little or no changes within Bromite itself.

It is more proper to bisect the Bromite patches alone in this case, since Chromium does not have the problem.

My strategy here would be to make the anti-fingerprinting patch configurable via an option toggle (same as ungoogled-chromium), as I think that patch might be responsible.

**Comment by expobar** [comment]
@csagan5 I also happen to have this issue with [Vanadium](https://github.com/GrapheneOS/Vanadium). Tested Chrome, Edge, and Brave and all three works well.

**Comment by csagan5** [comment]
@expobar if that is the case, then anti-fingerprinting would not be responsible. You should report the issue also in the Vanadium issue tracker, cc @thestinger

**Comment by csagan5** [comment]
I have verified that it happens regardless of anti-fingerprinting patches being present or not.

**Comment by Adrymate9** [comment]
Hi, I have the same problem! As I quickly scroll down on any web page, the scrolling tries to freeze, it gets slow.
Particularly where I clearly see this behavior is on Facebook. At times, it is unusable.

**Comment by jeikobu614** [comment]
For me scrolling on site like aliexpress is really fluid, don't see any freezing until you load lots of images. According to Disqus, it freezes only a tab, reload resolves the frozen page. But it's only if you really try to fast scroll.

**Comment by Adrymate9** [comment]
In my case it is for almost all the sites I visit. Some it shows more others less. And some like Facebook I don't know can use.

I hope it is resolved to use this browser that I love!

**Comment by csagan5** [comment]
This should be fixed with `77.0.3865.81`, which uses Chromium ad blocker engine.

**Comment by Adrymate9** [comment]
Already update, it works perfect! Thank you thank you very much!

**Comment by csagan5** [comment]
> @csagan5 I also happen to have this issue with [Vanadium](https://github.com/GrapheneOS/Vanadium). Tested Chrome, Edge, and Brave and all three works well.

@expobar if the issue has been resolved, then either Vanadium was never affected (it does not have Bromite's adblock engine) or it has a different issue?

**Comment by expobar** [comment]
@csagan5 I think the latter. I've been using Vanadium prior to this issue being reported,  had the same issue on the same site and other Alibaba sister sites. I only realized it was a browser issue when it was reported here. On a side note, scrolling on Alibaba sites appears to be working now with Vanadium on Android 10.
