### ISSUE TITLE
Bug in bookmark loading/exporting

### ISSUE THREAD

**Issue by aluo-x** [bromite/bromite#354]
**Bromite version**

Version: `76.0.3809.100.`
Arch: `arm64`
Android version: 9.1

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
Does not apply to Chromium since bookmark export/import is unique to Bromite on android

**Describe the bug**
Exported bookmarks do not show up in the bookmarks window, but they appear in the site suggestions during autocomplete

**To Reproduce**
1. Bookmark a few sites
2. Export the bookmarks
3. Delete/Reset Bromite
4. Import the bookmarks

**Expected behavior**
The exported bookmarks should be visible in the bookmarks menu.

**Comment by csagan5** [comment]
@aluo-x as far as I know closing and re-opening the app makes them appear; have you tested that?

**Comment by aluo-x** [comment]
@csgan5 this does not seem to be the case. It seems like the exported bookmarks have a structure where the bookmarks are placed in a folder so they are not shown in the bookmarks page, but they still show up in auto-suggest bar

**Comment by csagan5** [comment]
@aluo-x the bookmarks are all shown right after import in an `Imported` subfolder under the `Bookmarks bar` folder.

You can move them elsewhere after import.

**Comment by aluo-x** [comment]
As far as I can see, no subfolders are visible. Are you sure this behavior occurs when tapping on the bookmarks from the top right menu of Bromite on Android?

**Comment by csagan5** [comment]
@aluo-x you must have provided storage access first in order for import/export to work
