### ISSUE TITLE
YouTube videos not opening

### ISSUE THREAD

**Issue by bill4gr** [bromite/bromite#355]
**Bromite version**

Version: `76.0.3809.100`
Arch: `arm64`
Android version: 9
Brand: Huawei Mate 10 Pro

**Is the bug reproducible with latest version?** 
Yes

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?** 
No 

**Is the bug a CRASH?**
No 

**Describe the bug**
YouTube videos results do not open or redirect to YouTube app.. Works fine if turn on the desktop mode.. Chromium works in both modes.. 

**To Reproduce**
1. Go to 'search a video in google'
2. Click on 'any result'
3. See error

**Expected behavior**
To open the video in YouTube app

**Screenshots**
Not necessary.

**Comment by csagan5** [comment]
@bill4gr what is the error?

**Comment by bill4gr** [comment]
I do a google search.. Let's say "Lost in Paradise".. I get the google results and I click on the 1st Youtube video "Evanescence Lost in Paradise".. and nothing happens.. At Chromium it redirects to Youtube app and plays the video. At Bromite it's like dead.

**Comment by csagan5** [comment]
I cannot reproduce this error; it might be due to your preferred application settings.

You will need to do a better bug report by using https://developers.google.com/web/tools/chrome-devtools/remote-debugging/ for example.

**Comment by bill4gr** [comment]
Cleared cache, reinstalled and solved..
So sorry!
