### ISSUE TITLE
Build error when applying patches

### ISSUE THREAD

**Issue by Lnoma** [bromite/bromite#356]
**Bromite version**

Version: `76.0.3809.115`
Arch: `arm64`

**Is the bug reproducible with latest version?**
Yes, 76.0.3809.110

**Describe the bug**
I have an error when I try to apply Bomite patches on 76.0.3809.115 Chromium sources. I have an error to apply the patch "0003 Add a proxy configuration page" that fails on "chrome/browser/autocomplete/chrome_autocomplete_provider_client.cc:236"

**To Reproduce**
1. Checkout Chromium branch v76.0.3809.115
2. Checkout Bromite v76.0.3809.115
3. Try to apply patches to Chromium

> root@debian:~/chromium/src# git am ../bromite/build/patches/*patch
> 
> Application de  Add a flag for DNS-over-HTTPS
> Application de  Add an always-incognito mode
> Application de  Add a proxy configuration page
> error: the patch failed : chrome/browser/autocomplete/chrome_autocomplete_provider_client.cc:236
> error: chrome/browser/autocomplete/chrome_autocomplete_provider_client.cc : patch does not apply
> le patch a échoué à 0003 Add a proxy configuration page
> The copy of the patch that failed is found in: .git/rebase-apply/patch
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".

**Expected behavior**
The patches are applied without any problems.

**Comment by csagan5** [comment]
https://github.com/bromite/bromite/blob/master/README.md#how-to-build
