### ISSUE TITLE
Cannot update without reinstall from v63

### ISSUE THREAD

**Issue by FunkyH** [bromite/bromite#36]
Hi,

First of all: Nice work! Keep going with this project!

When i try to update the installed app an error occurs. "APK isn't compatible with the installed one". I took the right version of the APK (it's a little bit confusing though^^). Nevertheless, I tried the other  APK to check if anything happens. Same thing. Had to reinstall the app to apply the update.

Any ideas?

Have to check it again, with the new release.

Thank you very much!

**Comment by cdysthe** [comment]
I had the same issue with the previous update. Had to remove the older one and install as new. The latest update went as normal for me.

**Comment by FunkyH** [comment]
Good to know, thanks for reply. hopefully it'll work out next time for me as well.

**Comment by csagan5** [comment]
@FunkyH yes this is a "known issue" when upgrading from v63 to v64, although it is not clear the reason. I suspect something changed in the Chromium codebase.

It will probably not happen again for some time or ever again.

**Comment by csagan5** [comment]
Closing as there is no clear cause of the bug nor any plan to fix it.
