### ISSUE TITLE
Automatic deletion of Cookies and such (Settings - Privacy)

### ISSUE THREAD

**Issue by HyknuF** [bromite/bromite#360]
**Is your feature request related to privacy?**
Yes

**Is there a patch available for this feature somewhere?**
Only with manual interaction

**Describe the solution you'd like**
The downloaded files should leave untouched. I'd suggest to let the menu as it is now, just add an option "clear on exit" or similar.

**Describe alternatives you've considered**
see above

**Comment by csagan5** [comment]
There is already an option to remove cookies on exit: `Keep cookies only until you quit your browser`, under `Site settings` -> `Cookie`.

However it is affected by a bug: #142 

Thus there is no feature to implement here, it already exists.
