### ISSUE TITLE
Performance issue with SystemWebview after update

### ISSUE THREAD

**Issue by M86xKC** [bromite/bromite#362]
**Bromite version**

Version: ` > v72.0.3626.119`
Arch: `arm64` 
Android version: `9.0`
Device model: `Samsung Galaxy J7 Pro 2016`

**Is the bug reproducible with latest version?**

Yes.

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**

I think the performance issue is related to the additions that were in the `Bromite v72.0.3626.120` release.

    

> 
> - add support for resource type in adblock engine (fixes https://github.com/bromite/bromite/issues/115)
> - adblock engine speed optimizations
> - **use adblock engine also in SystemWebView**
> - add back uBlock Origin and EasyList filters
> -  added Fanboy's Annoyance List
> 

**Is the bug a crash?**

No

**Describe the bug**

Recently I updated my SystemWebview from an older version to the most recent one. And immediately I notice a huge performance issue (lag) in all applications dependent on Webview. After testing different versions I found the issues appeared starting from ` Bromite v72.0.3626.120 ` till the most recent one.

I think It is more obvious to noticed on a lower-end (mid-range device), because of the low processing power.

**To Reproduce**

1. Update to any version ` > v72.0.3626.119 `
2. the lag happens when loading the page & scrolling 

**Expected behavior**

Normal behavior (no lag)

**Screenshots**

I wanted to record the screen, but I found it was not clear from the video because of the low quality of the video recording 10fps    ¯\_(ツ)_/¯

**Comment by csagan5** [comment]
You have to test with the Chromium WebView, this might be related to #353 which happens also without adblock.

**Comment by M86xKC** [comment]
I thing this is not related to the other issue. I have no problem in the regular Bromite app, but rather in apps that depend on SystemWebView.

I have tried [this SystemWebView](https://github.com/wchen342/ungoogled-chromium-android/releases/download/76.0.3809.100-1/SystemWebView_arm64.apk) and didn't have any problems (lag).

**Comment by Adrymate9** [comment]
hello, the version I try to use is v76.0.3809.129. ARM64. phone Huawei mate 9 with android 8.0. It really works very badly, freezing at all times when scrolling through the web pages.

I tried what they follow, using v72.0.3626.120I had no luck is still missing in the same way.

Hopefully they can fix it in the next update. I love this browser.

**Comment by M86xKC** [comment]
@Adrymate9

Try v72.0.3626.119 and see if the issue still persists ?

And btw how did you change the systemwebview on unlocked bootloader, just curious :wink:

**Comment by Adrymate9** [comment]
Now I am going to try this version that I suggest and come back to comment on the experience

Regarding systemwebview, I'm really new to this and I don't understand what you mean or how I should proceed with this. I would appreciate your help on this topic.

**Comment by Adrymate9** [comment]
@M86xKC Effectively in version 72.0.3626.119 I also have the same problem.

**Comment by csagan5** [comment]
> I have tried [this SystemWebView](https://github.com/wchen342/ungoogled-chromium-android/releases/download/76.0.3809.100-1/SystemWebView_arm64.apk) and didn't have any problems (lag).

You need to test with the Chromium SystemWebview provided by this project.

**Comment by Adrymate9** [comment]
@csagan5 I have installed systemwebview x64 that proposes bromite. But once downloaded it does not appear in the corresponding section in the developer settings of my phone.

I don't know how to make it work above default systemwebview Help.

**Comment by M86xKC** [comment]
> You need to test with the Chromium SystemWebview provided by this project.

How can I get this ?

**Comment by csagan5** [comment]
> How can I get this ?

https://www.bromite.org/chromium for latest version

**Comment by M86xKC** [comment]
No issues what so ever.

**Comment by Adrymate9** [comment]
https://github.com/bromite/bromite/issues/362#issuecomment-528173763

I can not download this. I downloaded systemwebview that is listed in the latest version of bromite.

But I have the problem that the file is downloaded, it is in my file folder but it does not appear in the developer configuration section to be able to change it.

**Comment by M86xKC** [comment]
https://github.com/bromite/bromite/wiki/Installing-SystemWebView

**Comment by Adrymate9** [comment]
Once downloaded the file arm64_systemwebview.apk I cannot run it, there is also the option to select it in "systemwebview deployment configuration" of my phone.

Only the "Google webview" option appears. 

I hope to be clear in the explanation. 

We: I am not a root user. If that helps.

**Comment by csagan5** [comment]
> No issues what so ever.
> I tried the latest version btw (76.0.3809.129)

We can conclude it's adblock-related; the issue might change radically with the next release (v77) of Bromite SystemWebView as the NetworkService must be used; you will have to test with that one once it's released.

However, even if the issue is acknowledged, we cannot fix it if it's simply caused by the AdBlocker.
