### ISSUE TITLE
Toolbar controls at the bottom

### ISSUE THREAD

**Issue by Wilker-a** [bromite/bromite#363]
**Is your feature request related to privacy?**
No.

**Is there a patch available for this feature somewhere?**
Brave and a couple of closed-source browsers.  
Aditionally, i saw the issue #150 from last october, but i'm still posting this one because i thought it would be good to post this one with the template and a few more details.

**Describe the solution you'd like**
I would like to have available an opt-in feature which makes the main controls of the browser available at the bottom of the screen, including the 'tabs', 'home', 'bookmark', 'menu' buttons and etc., with the intention of making the browser usable with one hand without much struggle.

**Describe alternatives you've considered**
An option to move the current toolbar ("url bar") to the bottom would be good too (along with the copy-paste toolbar menu that occasionally appears too, maybe). An option to move the 'tab' and 'menu' buttons to the left to make it easier to use with the left hand would be nice too.

what do you think? :3

thank you for reading btw \^w\^

**Comment by csagan5** [comment]
It is not related to privacy -> it will not be developed for Bromite.

**Comment by Madis0** [comment]
Enable `chrome://flags/#enable-chrome-duet` and restart twice.

**Comment by Wilker-a** [comment]
thank you for that, it helps a lot \^_\^

**Comment by abh153k** [comment]
> Enable `chrome://flags/#enable-chrome-duet` and restart twice.

I dont know why it requires you to restart *twice*
