### ISSUE TITLE
Make regular tabs accessible after turning on always incognito mode

### ISSUE THREAD

**Issue by M86xKC** [bromite/bromite#364]
**Is your feature request related to privacy?**
Yes

**Is there a patch available for this feature somewhere?**
Not aware of any

**Describe the solution you'd like**
When enabling ` Settings > Privacy > Open links in incognito tabs always `, non-incognito tabs become inaccessible (you can not open a regular tab even manually), so my suggestion is keep the current setting (external links always open in incognito mode) but make the regular tab available when opening one manually.

**Describe alternatives you've considered**
Not aware of any

**Comment by csagan5** [comment]
@rarcher would you be interested in updating [the patch](https://github.com/bromite/bromite/blob/76.0.3809.129/build/patches/Add-an-always-incognito-mode.patch) for this feature?

**Comment by rarcher** [comment]
@csagan5 Unfortunately, certain legal restrictions in the contract with my current client prevent me from working on it right now...maybe after this contract ends, though that could be quite a long time from now.

**Comment by csagan5** [comment]
I understand; given the complexity introduced by the development of this feature, I have to reject it.

The current bugs should be fixed first.

**Comment by rarcher** [comment]
Understandable.  Thanks for your consideration, and I hope we can work together again in the future.
