### ISSUE TITLE
Bromite is reporting an outdated version of Chromium in useragent

### ISSUE THREAD

**Issue by Michalko589** [bromite/bromite#365]
**Bromite version**

Version: `76.0.3809.129`
Arch: `arm64`
Android version:  `9.0`

**Is the bug reproducible with latest version?**

Yes.

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**

No, it's privacy-enhancements related.

**Describe the bug**

Bromite is spoofing User Agent for privacy reasons. While spoofing device model and Android version is fine, I think Bromite shouldn't spoof Chromium version for compatibility reasons. It has little to no effect on privacy and it may break pages that rely on the latest Chromium features. 

**To Reproduce**

Bromite is reporting the following UA on the latest build:

`Mozilla/5.0 (Linux; Android 8.0.0; SM-G960F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Mobile Safari/537.36`

**Expected behavior**

Bromite should return a correct Chromium version, while Android version and phone model should stay spoofed:

`Mozilla/5.0 (Linux; Android 8.0.0; SM-G960F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.129 Mobile Safari/537.36`

**Comment by Madis0** [comment]
See #103 #138 #156 #162 #205 #307.
