### ISSUE TITLE
Listing on privacytools.io

### ISSUE THREAD

**Issue by blacklight447-ptio** [bromite/bromite#367]
Dear Bromite community, 
I am a team member of the website privacytools.io where we recommend privacy friendly and secure alternatives to mainstream technology. We have been fond of Bromite for a while, but haven't been able to list it since we only made desktop recommendations.

Soon we will be expanding our browser section to recommend alternatives on other platforms, and we would really like to list Bromite as our recommend secure chromium based alternative. how ever for this to happen, we also need a 120x120 image of the Bromite logo.

So far I have unfortunately only been able to find the logo on Bromite.org, but that one is sadly to small and will be blurry if we used it. So would anyone here be able to point out where we can find 120x120 (or bigger) versions of the Bromite logo? that way we can start sending more users your way :). 

For those interested in our PR were we include Bromite:https://github.com/privacytoolsIO/privacytools.io/pull/1256#issuecomment-526931773

Kind regards,
Blacklight.

**Comment by JonahAragon** [comment]
https://github.com/bromite/bromite/issues/258#issuecomment-526978880

**Comment by csagan5** [comment]
@JonahAragon let me know if you still need the logo, I can provide it via email.

FYI Chromium should be written with uppercase 'c'
