### ISSUE TITLE
Tracker block counting

### ISSUE THREAD

**Issue by Wilker-a** [bromite/bromite#368]
**Is your feature request related to privacy?**
Yes.

**Is there a patch available for this feature somewhere?**
Brave has a counter for different tracker and fingerprinting methods, while DuckDuckGo specifies the trackers which were blocked.

**Describe the solution you'd like**
A subtle but visible button available on the screen which lets you see how many trackers and fingerprinting methods were present before blocking, how many HTTP requests were converted to HTTPS*, among other things. This might let people think twice before sharing links with others who might not be using the browser.
###### * (if this feature is available. otherwise it is a topic for another issue)

**Describe alternatives you've considered**
This info could be available in the padlock icon, where the site signature is available. maybe just the conter is enough to appear upon clicking, while making the icon have an exclamation mark whenever a fingerprinting method is detected.

what do you think? :3

###### edit: typo and formatting

**Comment by csagan5** [comment]
I am not going to develop this feature.

**Comment by Madis0** [comment]
Counters like that are useless anyway. Read this: https://github.com/gorhill/uBlock/wiki/About-"This-other-extension-reports-more-stuff-blocked!"
