### ISSUE TITLE
Bromite is not installed on Xiaomi Redmi 5 Android 7.1.2

### ISSUE THREAD

**Issue by anarbus** [bromite/bromite#369]
Version: `76.0.3809.129`
Arch: `arm`
Android version: 7.1.2
Device model: Xiaomi Redmi 5

I tried to install it in every possible way, but in the end it never worked ...

In developer mode, I cannot select bromite
Only AOSP "WebView is available"

My smartphone has an ROOT, I replaced the apk in systems/app/webviev, this also did not help

How can I install bromite on my smartphone?
Help me please

**Comment by csagan5** [comment]
I am sorry, the issue tracker is not for support; you can try to ask support on XDA or Reddit.
