### ISSUE TITLE
Option to toggle Javascript

### ISSUE THREAD

**Issue by FunkyH** [bromite/bromite#37]
One big thing I am missing in Bromite is to customize disable / enable javascript on each site/domain, like Noscript or Umatrix.

Is it possible to add it to Bromite?

Would be amazing!

**Comment by csagan5** [comment]
I had actually started coding something in this direction a few months ago, then left it as work in progress. Yes it is possible we will have this feature in future.

**Comment by csagan5** [comment]
I have added this functionality but just as a shortcut in the :hamburger: menu to the global settings for Javascript; this will be available in the next release.

**Comment by iamrohanbro** [comment]
Great

**Comment by csagan5** [comment]
Fixed in `65.0.3325.204`
