### ISSUE TITLE
App allow access

### ISSUE THREAD

**Issue by Rossq30** [bromite/bromite#370]
**Bromite version**

Version: `77.0.3865.81`
Arch: `arm64
Android version: `9.0`
Device model: `ASUS Zenfone Max Pro M1 ZB602KL`

**Is the bug reproducible with latest version?**

Yes

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**

Can not test 

**Is the bug a crash?**

No

**Describe the bug**

I use an app called tasker, which is an automation app. Of its most recent features is to give tasker the permissions to access Google drive. Which gives you the ability to automate certain aspects of Google drive, for example you can ask tasker to make a backup of your micro sd on a weekly schedule to Google drive, in your chosen directory. 

However the Google dialogue only works partly, with bromite system Web view. This also affects all apps that may require permissions from Google services

**To Reproduce**

1. Download tasker
2. Open tasker
3. Grant tasker acsses to any dialogs that show during the launch of the app
4. Create a new task
5. Give task a name
6. Tap on the plus icon
7. Tap on Google drive
8. Tap on GD sign in
9. Tick the box for full acsses
10. Tap back arrow key, to the left of the task name in tasker
11. Tap on the play ▶ icon bottom left 
12. Google dialogue should display, asking you to choose a Google account. 

**Expected behavior**

It should ask you would you like to give this app permissions to Google drive

**Screenshots**

**Comment by csagan5** [comment]
There is no Android user profile + account integration in Bromite SystemWebView, so I don't think this can ever work.
