### ISSUE TITLE
PAC scripts not being loaded through file:// scheme

### ISSUE THREAD

**Issue by retardTonic** [bromite/bromite#371]
**Bromite version**

Version: `77.0.3865.81`
Arch: `arm`
Android version: `7.1.2`

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
N/A

**Is the bug a crash?**
No

**Describe the bug**

Support for PAC scripts supplied through file:// scheme is broken since version 77(?)

This might be some kind of regression in Chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=839566)

**To Reproduce**

1. Go to Settings -> Privacy -> Proxy configuration
2. Select 'Use PAC URL'
3. Enter full path to a working PAC script (e.g. file:///storage/emulated/0/example.pac)
```
// Example script
function FindProxyForURL(url, host) {
    return "DIRECT";
}
```

3. Check 'Do not allow fallback...'
4. Click 'Apply'
5. Go to any site
6. Page is not available, `ERR_MANDATORY_PROXY_CONFIGURATION_FAILED`

**Expected behavior**

Browser attempts to load a page.

**Comment by csagan5** [comment]
> **Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
> N/A

You need to test it with the corresponding Chromium version.

**Comment by DudmasterUltra** [comment]
This still doesn't work for me
