### ISSUE TITLE
'Tap to search' doesn't work

### ISSUE THREAD

**Issue by serialpotato** [bromite/bromite#373]
**Bromite version**

Version: 77.0.3865.81
Arch:  `arm64`
Android version: 7.
Device model: HTC-10

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding [Chromium]
No, it works perfectly ok on brave, kiwi & chrome.

**Is the bug a crash?**
No

**Describe the bug**
Chrome, or chrome based browsers have a feature called 'Tap to search'. When you select a text, it lets you google that word without opening a new tab. It's pretty great for vocabulary and serve as a dictionary.

**To Reproduce**

1. Open any webpage
2. Select a word
3. You will find that it won't auto-search, like tap-to-search normally does

**Expected behavior**
When you select a word by tapping on it, on a webpage, it automatically googles it without opening a new page.

It should be able to function like other chrome based browsers at least. A user should have the option whether to use it or not, so that those who dislike it then can opt out while, others, like me, can use it.

Please bring this feature. I really like your work, but this is the only thing, besides non-smooth scrolling/ browsing, i would love the bromite team to sort out.

**Comment by csagan5** [comment]
> No, it works perfectly ok on brave, kiwi & chrome.

You have to test it with the same Chromium version as Bromite; you need to pick it from https://github.com/bromite/chromium/releases

**Comment by serialpotato** [comment]
It works with chromium too.

**Comment by serialpotato** [comment]
> > No, it works perfectly ok on brave, kiwi & chrome.
> 
> You have to test it with the same Chromium version as Bromite; you need to pick it from https://github.com/bromite/chromium/releases

Please open this issue.

**Comment by csagan5** [comment]
> It works with chromium too. No bug there

It also works with Bromite.

**Comment by serialpotato** [comment]
> > It works with chromium too. No bug there
> 
> It also works with Bromite.

It doesn't. That's why i reported.

**Comment by csagan5** [comment]
@serialpotato the problem is that options to control tap to search and suggestions are not visible, upstream moved them in a menu available only for the logged-in account. You cannot use it probably because it's a disabled option by default. This problem can be tracked with #375

**Comment by serialpotato** [comment]
> @serialpotato the problem is that options to control tap to search and suggestions are not visible, upstream moved them in a menu available only for the logged-in account. You cannot use it probably because it's a disabled option by default. This problem can be tracked with #375

Thanks for insight. For reference, I didnt have to login into any of the chromium based browsers and chromium itself, for it to work. It just works out of the box. How do i work around it? I have been following bromite closely for the last 2-3 months. And this option hasn't worked for me once on bromite, even when the option of tap to search was available in the bromite settings (unlike now, when I cant even find it's relevant setting)

**Comment by serialpotato** [comment]
> upstream

ok, f me. So, by upstream, you mean chromium doesn't have it anymore, from which you fork out? Because, I refute this and am ready to provide proof if you need, as it works without any issues on chromium. And without needing to log in, or doing anything out of the box.

**Comment by csagan5** [comment]
> For reference, I didnt have to login into any of the chromium based browsers and chromium itself, for it to work. It just works out of the box.

That is the meaning of "enabled by default"; in Bromite it is "disabled by default".

> I refute this and am ready to provide proof if you need, as it works without any issues on relevant chromium version. And that too without needing to log in, or doing anything out of the box.

That's because it is enabled by default in Chromium.
