### ISSUE TITLE
Boot loop after installing BromiteWebView from Magisk

### ISSUE THREAD

**Issue by iyesin** [bromite/bromite#374]
**Bromite version**

Version: `77.0.3865.81`
Arch: `arm64`
Android version: `8.0`
Device model: `Xiaomi/omni_gemini/gemini:7.1.2/NJH47F`

**Is this bug about the SystemWebView?**
No

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding Chromium version?**
I have no idea. I just updated BromiteWebView from Magisk.

**Is the bug a crash?**
Since it is boot loop, I can't provide you logcat data.

**Describe the bug**
Very slow boot logo for about 10 minutes, reboot and recovery menu

**To Reproduce**

1. Go to Magisk modules
2. Click find updated BromiteWebView
3. Click update
4. Agree to reboot
5. Get boot loop

**Expected behavior**
Work like nothing changed

**Comment by csagan5** [comment]
> **Is this bug about the SystemWebView?**
> No

But you seem to say that this is about the SystemWebView.

Regardless, I don't understand what is the bug to be fixed here. You need support for your installation with Magisk, I suggest using XDA or Reddit.

**Comment by OffifialMITX** [comment]
If you have TWRP, go to it and wipe the data. Your files will be kept but all non-system apps and settings will be deleted.
