### ISSUE TITLE
README.md needs updating regarding Dark Mode

### ISSUE THREAD

**Issue by BlackDex** [bromite/bromite#376]
**Bromite version**

Version: `77.0...`
Arch: `n/a`
Android version: `n/a`
Device model: `n/a`

**Is this bug about the SystemWebView?**
No

No support for SystemWebView installations is provided.

**Is the bug reproducible with latest version?**
Not a Bug

**Can the bug be reproduced with corresponding Chromium version?**
Not a Bug

Please pick the same version of Chromium as Bromite from here: https://github.com/bromite/chromium/releases
If the bug is reproducible then it might be a configuration issue or an upstream bug. Upstream bugs can be reported on the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) and do not forget to read [Chromium project bug reporting guidelines](https://www.chromium.org/for-testers/bug-reporting-guidelines) first.

**Describe the bug**
README.md needs updating

**To Reproduce**
Opening README.md

1. Go to 'README.md'
2. Scroll down to 'Can you add dark mode/some cool themes?'
    https://github.com/bromite/bromite#can-you-add-dark-modesome-cool-themes
4. The answer is No, which should be Yes now.

**Expected behavior**
Having the correct answer :).

**Comment by csagan5** [comment]
@BlackDex the dark mode in Bromite is the one available from Chromium; I have removed it.
