### ISSUE TITLE
Set proxy to "None" will not fallback to system proxy

### ISSUE THREAD

**Issue by kowith337** [bromite/bromite#377]
**Bromite version**
> Version: `77.0.3865.95 (1568938391)`
> Arch: `arm64 (ChromeModernPublic)`
> Android version: `9.0`
> Device model: `XT1970-3 (kane)`

**Is this bug about the SystemWebView?**
> No

**Is the bug reproducible with latest version?**
> I'm using current release version

**Can the bug be reproduced with corresponding Chromium version?**
> No, because vanilla chromium doesn't have `Proxy` feature.

**Is the bug a crash?**
> No, this bug doesn't occur any crash attempts.

**Describe the bug**
> Bromite set proxy to `None` by default, If you didn't touch or config anything in `chrome://proxy` and have setup to use proxy at APN or Wi-Fi, Bromite will use system proxy.
> 
> However, if you've changed and revert back to `None`, it will use direct connection and it's impossible to revert, unless you've reset app data. (that's mean cleanup everything!)

**To Reproduce**
> 1. Set proxy at Wi-Fi or APN
> 2. Open Bromite, then do test to known your IP address (e.g. search `IP address` on DuckDuckGo)
> 3. Go to `chrome://proxy`, change to another value, apply change, then reset to **None**, then apply change.
> 4. Do step 2 again.

**Expected behavior**
> Bromite should revert back to system proxy, not direct connections.

**Screenshots**
> ![image](https://user-images.githubusercontent.com/16535467/65691552-3aa5ae00-e09b-11e9-9098-1a7d25e486e5.png)
> ![image](https://user-images.githubusercontent.com/16535467/65691612-56a94f80-e09b-11e9-92ba-a45519099201.png)

**Notes**
> Make sure you didn't have any VPN running, either main or work profile.
>

**Comment by csagan5** [comment]
This happens because the current proxy gets overriden; we need another option `Default` that can be used to point the proxy settings to those existing before any change takes place.
