### ISSUE TITLE
SystemWebView not blocking ads

### ISSUE THREAD

**Issue by ploink** [bromite/bromite#379]
**Bromite version**

Version: 77.0.3865.104
Arch: arm64
Android version: 9.0
Device model: Xiaomi Pocophone F1 ('Beryllium') running Resurrection Remix ROM.

**Is this bug about the SystemWebView?**
Yes

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding Chromium version?**
The corresponding **Bromite** version does block ads.

**Describe the bug**
Bromite systemwebview is installed via magisk and verified with 'Webview test' app. I [posted about this](https://forum.xda-developers.com/showpost.php?p=80350155&postcount=222) as user Fruitrat on XDA. 

When visiting https://ads-blocker.com/testing I see ads.
The bromite web browser app does not show any ads on the same page.
The problem was also reported on XDA by [xk0niR ](https://forum.xda-developers.com/android/apps-games/app-bromite-chromium-plus-adblocking-t3687258/post80290489#post80290489)and  [atti9935](https://forum.xda-developers.com/android/apps-games/app-bromite-chromium-plus-adblocking-t3687258/post80357115#post80357115) but no issue was filed yet (or I did not find it).

Bromite fingerprinting mitigations test scores 5/9 for both Bromite systemwebview (with Webview test) and the Bromite browser app.

1. Install the magisk module 
2. Visit site with ads using webview test app.

**Expected behavior**
No adds on website

**Screenshots**
![NoAdBlock](https://user-images.githubusercontent.com/3049492/65831147-b3348680-e2b6-11e9-89aa-a62e83c05aa1.png)

**Comment by csagan5** [comment]
I have checked how to re-implement adblocking for the webview in a few ways, all of them are not easy to complete or maintain.

The webview did not originally have adblocking features and due to upstream changes we have to revert back to that status.

**Comment by ploink** [comment]
Thank you for your efforts. One would almost think that upstream makes ad blocking difficult on purpose, but if you ever find a good way to re-implement it for future versions, I would highly appreciate if the feature returns.

I am on CarbonRom now and v77 does block ads, but not reliably. It leaves whitespace where ads used to be and sometimes they appear anyway, where v76 blocks reliably and does not leave whitespace.

**Comment by csagan5** [comment]
@ploink it is related to the introduction of NetworkService, and that is indeed related to the deprecation of adblock extensions.

Going forward the feature for SystemWebView would best be implemented using the subresource filter, but that would require some development effort and since it's not the main purpose of this project I cannot commit to that.
