### ISSUE TITLE
FATAL EXCEPTION: File doesn't exist: /vendor/overlay/treble-overlay-webview.apk

### ISSUE THREAD

**Issue by TeslaBargain** [bromite/bromite#380]
**Bromite version**

Version: `77.0.3865.104`
Arch: `arm64`
Android version: `9.0`
Device model: `ONEPLUS A6003`

**Is this bug about the SystemWebView?**
Yes

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding Chromium version?**
No

**Is the bug a crash?**
Yes

I don't have the locat file at hands right now, but the DKB TAN2go banking app crashes because of the error `FATAL EXCEPTION: File doesn't exist: /vendor/overlay/treble-overlay-webview.apk`

**Describe the bug**

LOS 16 comes with with the regular Android System WebView and I have installed Bromite System WebView using the according Magisk module.

When using the Magisk module for installing Bromite System WebView systemless-ly, it replaces the regular Android System WebView instead of adding it to be chosen from the developer options.

My problem is, that my banking app DKB TAN2go just crashes when Bromite System WebView is in use (FATAL EXCEPTION: File doesn't exist: /vendor/overlay/treble-overlay-webview.apk) and I'm not sure if that is because of having Bromite System WebView installed systemless-ly with Magisk or because of Bromite System WebView itself.

When I remove Bromite System WebView by removing the according Magisk module, that banking app is working again with the regular Android System WebView.

**To Reproduce**

1. Have a rooted ROM with Magisk and regular Android System WebView in use.
2. Install Bromite SystemWebView using the according Magisk module.
3. Try to start the app DKB TAN2go and it will crash with the shown error.

**Expected behavior**

Either to have more than one System WebView installed (if that prevents the crash of that app) or have Bromite SystemWebview provide the missing file as per error message (if that is possible and the problem is caused by Bromite SystemWebview itself).

**Comment by csagan5** [comment]
The SystemWebView is provided "as is", like everything else. There is no support provided for the countless ways it can be installed (including the Magisk module, which is in no way officially endorsed) and break such installations.

Your best option is to ask somewhere else.

**Comment by csagan5** [comment]
FYI, the issue template already mentions "No support for SystemWebView installations is provided."
