### ISSUE TITLE
Revert changes to bring back option for page preloading

### ISSUE THREAD

**Issue by mthomos** [bromite/bromite#383]
**Is your feature request related to privacy?**
Features that are not related to privacy are unlikely to be considered.

**Is there a patch available for this feature somewhere?**
If yes then provide URL and license information.

**Describe the solution you would like**

Do not ask "I would like feature X which is available in browser Y"; such issues are closed immediately.

**Describe alternatives you have considered**
A clear and concise description of any alternative solutions or features you have considered.

In your patch for safe preloading, you remove fully the option for page preloading. Can you at least revert this change specifically for page preloading? Of course by default it will be disabled.

**Comment by csagan5** [comment]
You have left most of the template blank.

Regardless, this option was removed by upstream Chromium (together with others, moved under the Sync settings), I have already considered to bring it back.
