### ISSUE TITLE
Support password autofill framework

### ISSUE THREAD

**Issue by hernan-fernandez** [bromite/bromite#384]
In order to make the browser more widely used. It would be good to be able to use the passwords stored in the Android framework

By example this is a new recently installed Firefox without any user account or password synchronization.

It suggests the saved passwords using the autofill framework. Please note that the browser didn't had any synced password.

![Screenshot_2019-10-12-21-25-40-770_org mozilla fenix](https://user-images.githubusercontent.com/9675622/66719279-1c8ebc00-edc4-11e9-8ee7-95de9b84a9f9.jpg)

Thanks for considering this

**Comment by hernan-fernandez** [comment]
Please reopen this as the template has been added.

**Comment by csagan5** [comment]
> No tested on chromium, tested on chrome and firefox and doesn't happen

This is not optional; follow the instructions that you deleted from the [template](https://github.com/bromite/bromite/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
