### ISSUE TITLE
Can you help me build custom chromium with a donnation

### ISSUE THREAD

**Issue by GenderAPI** [bromite/bromite#385]
Hi we want to do special chromium android

if it is possible can you help us with some donation to you

requrements;

- chrome extensions enabled
- installed default chrome extension (from google web store so i can update when ever i want)
- need android studio source code

is it possible?

**Comment by PatSpiegel** [comment]
just read instruction https://chromium.googlesource.com/chromium/src/+/master/docs/android_build_instructions.md
