### ISSUE TITLE
Unable to enable page predictions

### ISSUE THREAD

**Issue by mthomos** [bromite/bromite#387]
**Bromite version**

Version: '78.0.3904.63`
Arch: `arm64`
Android version: `9.0`
Device model: 'Xperia XZ1'

**Is this bug about the SystemWebView?**
No

**Is the bug reproducible with latest version?**

Yes

**Can the bug be reproduced with corresponding Chromium version?**
Not provided yet

**Is the bug a crash?**
bug

**Describe the bug**

It is impossible to enable page prediction in privacy settings

**To Reproduce**

1. Go to Privacy settings
2. Tap to enable Use page predictions
3. Tap to enable Preload pages for faster browsing
4. Press back button to return Settings Menu
5. Go to Privacy settings again

**Expected behavior**

Use page predictions and Preload pages for faster browsing are disabled and not enabled

**Comment by mthomos** [comment]
I think that the changes about PREF_NETWORK_PREDICTIONS in this patch should be reverted https://github.com/bromite/bromite/blob/master/build/patches/Disable-safe-browsing.patch

**Comment by csagan5** [comment]
@mthomos yes, it's a mistake - it will be fixed in next release.

**Comment by nikolowry** [comment]
Can confirm that https://github.com/bromite/bromite/commit/28e950d9beaafe30f683959d1789cf9915ac8d38 resolves this issue
