### ISSUE TITLE
Store StartPage settings without cookie

### ISSUE THREAD

**Issue by ron42** [bromite/bromite#392]
**Is your feature request related to privacy?**
No

**Is there a patch available for this feature somewhere?**
No

**Describe the solution you would like**
Store StartPage settings by using its modified OpeanSearch URL instead of a cookie (for example: https://www.startpage.com/do/mypage.pl?prfh=enable_stay_controlEEE0N1NsuggestionsEEE1N1Ngeo_mapEEE1N1Nwikipedia_iaEEE1N1Nother_iaEEE1N1Ndisable_open_in_new_windowEEE0N1Ndisable_video_family_filterEEE1N1Nenable_post_methodEEE1N1Nenable_proxy_safety_suggestEEE0N1Ndisable_family_filterEEE1N1NsslEEE1N1Nlanguage_uiEEEenglishN1NlanguageEEEenglishN1Nwt_unitEEEcelsiusN1Nnum_of_resultsEEE10N1Nlang_homepageEEEs/dark/en/&t=dark)

**Describe alternatives you have considered**
Cope with saving the said settings as a cookie and selectively clear cookies for other sites.

**Comment by csagan5** [comment]
> No

During submission with the issue template it is specifically written that if this is not about privacy it will not be considered.
