### ISSUE TITLE
Unable to open and go inside Sync and Google services

### ISSUE THREAD

**Issue by Techguyprivate** [bromite/bromite#393]
Chromium version : 78.0.3904.63 ( not Bromite )

Version: 78.0.3904.63
Arch:  arm64
Android version: android 9 pie
Device model:  realme 2 pro(RMX1807)  , samsung galaxy m30s (SM-M307F)

**Is this bug about the SystemWebView?**
No

**Is the bug reproducible with latest version?** Yes

**Can the bug be reproduced with corresponding Chromium version?**
 Yes.

**Is the bug a crash?** 

Not full crash. Kind of . Chromium restart to homepage.

![Record_2019-10-22-17-23-52_66a3b1c2c181ff92b8bf945e748b6fb7 (1)](https://user-images.githubusercontent.com/43615747/67290294-8a8e5e00-f4fd-11e9-9f40-895bcf257bc6.gif)

**Describe the bug**
Clicking on Syncc and Google services , chromium crashed and comes to homepage.

**To Reproduce**
Install the latest vanilla chromium .

Go to setting.

click on sync and google services. 

**Expected behavior**
It should open sync and Google services.

It should open sysnc and google services having various option inside it like disabling safe saerch, page prediction etc.

**Comment by csagan5** [comment]
Fixed in `78.0.3904.93`.
