### ISSUE TITLE
"Features to disable"

### ISSUE THREAD

**Issue by Madis0** [bromite/bromite#397]
**Is your feature request related to privacy?**
Privacy, sustainability (less patches needed), better configurability for users (somewhat better UX)

**Is there a patch available for this feature somewhere?**
No, but creating a patch for this would make some other patches unnecessary

**Describe the solution you would like**
I would like to have user-customizable fields (like text fields in settings) for target arguments [--disable-features](https://peter.sh/experiments/chromium-command-line-switches/#disable-features). It seems to be like `chrome://flags` but for permanently hardcoded features. A list of features [can be found from Chromium source](https://cs.chromium.org/search/?q=_features.cc&p=1&sq=package:chromium&type=cs).

For example, disabled features could include
`OmniboxUIExperimentHideFileUrlScheme, OmniboxUIExperimentHideSteadyStateUrlScheme,OmniboxUIExperimentHideSteadyStateUrlTrivialSubdomains,OmniboxUIExperimentHideSteadyStateUrlPathQueryAndRef,SearchReadyOmnibox`.
That could already make [this patch](https://github.com/bromite/bromite/blob/master/build/patches/Disable-search-ready-omnibox-by-default.patch) and partly [this patch](https://github.com/bromite/bromite/blob/master/build/patches/Disable-omission-of-URL-elements-in-Omnibox.patch) irrelevant.

**Describe alternatives you have considered**
It is also possible to just set those as a target argument without giving the user customization over them.

**Comment by csagan5** [comment]
You are mixing up flags, preferences and features. Most features can be controlled with a flag; there is a certain logic that expresses how flags, preferences and features are loaded at startup, it's not as simple as you think and I do not wish to mess with that, without considering migrations etc.

**Comment by Madis0** [comment]
I was using the Chromium terms, but fair enough. 

Wouldn't hardcoding the target argument `--disable-features=SearchReadyOmnibox` be wiser than [patching the file](https://github.com/bromite/bromite/blob/master/build/patches/Disable-search-ready-omnibox-by-default.patch) itself though?

**Comment by csagan5** [comment]
Individual patches allow builders to pick/discard them while hardcoding everything for the `--disable-features` command line flag would not allow that; without considering that users can currently use `--disable-features` on Android and they would not be able to use `--enable-features` or `--disable-features` anymore.
