### ISSUE TITLE
Add Bromite to F-Droid

### ISSUE THREAD

**Issue by andrin55** [bromite/bromite#4]
Hello 

Wouldn't it be nice if Bromite was in some sort of an app-store so we can receive updates for it automatically?
I guess the F-Droid app-store would be a great place for this app.

Thank you

**Comment by csagan5** [comment]
There is already an open request there, opened since day 1: https://gitlab.com/fdroid/rfp/issues/378

Kinda stalled though. They might not have the build power for it.

**Comment by andrin55** [comment]
Alright. How about Google Play Store?

**Comment by csagan5** [comment]
Yeah, might do that eventually. In particular to avoid other people squatting it there with malware (happened in the past)

**Comment by csagan5** [comment]
Let's see what happens upstream at F-Droid repo, it doesn't seem too well for now. I think the easiest way is to provide an updater through F-Droid, but it's also not really open source anymore..

**Comment by Madis0** [comment]
What about XDA Labs? It has the target audience and you have posted it on its forums too.

**Comment by cdysthe** [comment]
XDA Labs would be my preference. F-Droid would work too.

**Comment by csagan5** [comment]
@Madis0 @cdysthe I have attempted uploading at XDA Labs every time somebody has mentioned it on the XDA thread; it gives a connection refused error because of the large .apk uploads, I assume. Furthermore, does not allow specifying an .apk per android architecture from what I could see.

There is no clear way to ask for support from the devs of XDA Labs, I have posted on their thread but it looks like an endless complaints stream and no individual replies provided. That's not going to work.

What they should have is an issue tracker somewhere, not just a forum thread of 50 pages. If you find a way to submit a bug report (and get it solved), then I would use that too.

**Comment by cdysthe** [comment]
@csagan5 Thank you for trying. There are other similar browser projects on XDA Labs like Tugabrowser so it should be possible, but I'm not able to help with making it work unfortunately. Right now the latest Bromite update doesn't work for me so I am happy not to get it automatically 😉

**Comment by csagan5** [comment]
@cdysthe I added an automated test to prevent that problem again in the future (broken adblock filters); they added an invalid filter `/$file/analytics.` in EasyPrivacy list and that caused the breakage.

I can give a try again in future.

**Comment by csagan5** [comment]
Reopening because there seems to be some activity [upstream](https://gitlab.com/fdroid/rfp/issues/378).

**Comment by speednroll** [comment]
They did not think about making a separate repository for f-droid? how do microg or firefox (unofficial)

**Comment by csagan5** [comment]
This is again stuck upstream; I spent quite a lot of time trying to build with F-Droid VMs, but it does not work. Virtual kernel and ethernet bugs...

**Comment by genofire** [comment]
Why nobody try to add it by a PR at https://gitlab.com/fdroid/fdroiddata ?

**Comment by csagan5** [comment]
@genofire it was already open, see the link in the first comment of this issue which is the RFP and then there you can find the MR in fdroiddata.

There are no more plans to add support to the official F-Droid repository.

**Comment by csagan5** [comment]
Looks like the official F-Droid repository will soon sport a Chromium fork: https://gitlab.com/fdroid/fdroiddata/merge_requests/3351

(This is not Bromite but I thought to mention it, since it was started after [this Bromite issue](https://github.com/bromite/bromite/issues/65))
