### ISSUE TITLE
Data Saver will not stay enabled. 

### ISSUE THREAD

**Issue by cdysthe** [bromite/bromite#40]
I can not enable the Data Saver feature in settings. As soon as I leave the setting and come back it's disabled again. Not that I neccesarily want to use it, but is it disabled for a reason or is it a bug?

**Comment by csagan5** [comment]
It cannot be used because it needs Google APIs and it is anyway against Bromite's purpose of defending privacy.

There are no plans to disable UI integration parts of it.
