### ISSUE TITLE
Youtube videos cannot be started from browser

### ISSUE THREAD

**Issue by HigH-HawK** [bromite/bromite#401]
**Bromite version**

Version: `78.0.3904.72`
Arch: `arm64`
Android version: `9.0`
Device model: `HTC U11 plus`

**Is this bug about the SystemWebView?**
No (Don't think so)

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding Chromium version?**
No

**Is the bug a crash?**
No

**Describe the bug**

I open Bromite and use the search or type web address bar to search for something. Upon searching, it opens the google search page and shows the results. If there are any Youtube videos, it shows the video results but when I click on them, the browser only jumps to the top of the page and nothing else happens. In other browsers, this opens the Youtube app or website. I went through the settings as I thought it would be some sort of configuration preventing the Youtube app or website from opening but couldn't find anything. (Maybe I wasn't looking for the right thing). 

**To Reproduce**

1. Tap the `Search or type web address` bar
2. Enter your search and hit search
3. If Google finds Youtube videos corresponding your search, tap on the video
4. See how the browser just jumps to the top of the page. 

**Expected behavior**

I expect the Youtube app or website to open, when tapping on the video in the Google search result, instead the browser just jumping to the top of the page.

**Comment by csagan5** [comment]
@HigH-HawK this is not reproducible; I suspect it's due to your preferred app settings

**Comment by HigH-HawK** [comment]
@csagan5 if you mean the settings in the Bromite app, I have to disagree as I haven't changed anything apart from the Theme (changed to Dark).

I even un- and reinstalled the app but without success.

**Comment by csagan5** [comment]
No, I meant the default app for Youtube.

**Comment by HigH-HawK** [comment]
As I wrote in my initial post, it works with other browsers such as Firefox, Chrome (default on HTC) and the Chromium.

I got it to work in Bromite now as well and this is how I have done it:

Before uninstalling Bromite, I cleared the cache and data and reinstalled the app freshly. Now I can click on Youtube videos and it opens the Youtube app. So just uninstalling the Bromite seems to have left stuff on the phone.

It's working now.

**Comment by csagan5** [comment]
> So just uninstalling the Bromite seems to have left stuff on the phone.

That's not possible; see also: https://android.stackexchange.com/a/12321

**Comment by HigH-HawK** [comment]
Well, I just pointed out what I noticed and what my solution was and it worked. Not sure why it only worked that way but it did.

**Comment by ov1d1u** [comment]
I'm having a similar issue but it seems to be related to my Google account. If I click on a YouTube video in Google results while I'm signed in nothing will happen, but if I sign out a pop-up asking me to open the link with YouTube or Bromite will appear. Still couldn't figure out why this happens.
