### ISSUE TITLE
Login to Sony PSN not working in Bromite

### ISSUE THREAD

**Issue by HigH-HawK** [bromite/bromite#402]
**Bromite version**

Version: `78.0.3904.72`
Arch: `arm64`
Android version: `9.0`
Device model: `HTC U11 plus`

**Is this bug about the SystemWebView?**
No

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding Chromium version?**
No

**Is the bug a crash?**
No

**Describe the bug**

With previous versions of Bromite, I could login to the Sony PSN website but with the current version it doesn't work anymore. I enter my username and password and click on login and get an error message. (see previously attached screenshot) I tried the stock Chrome and downloaded Firefox as well as Chromium and the login works in these three, just Bromite causes this issue. I guess there is a security option/setting in Bromite which prevents the login but so far I could not find any option or setting which could cause it. 

Is there any way to find out what option/setting is blocking the login?

**To Reproduce**

1. Go to `https://id.sonyentertainmentnetwork.com/signin/`
2. Enter username / password and click on Sign In

**Expected behavior**

It should log someone in, instead giving an error message, just like in Chrome, Chromium, Firefox, etc.

**Screenshots**
![PartialScreenshot_20191102-104744](https://user-images.githubusercontent.com/33863449/68089725-358f0800-fe6c-11e9-9cd0-d5b088ba7f78.png)

**Comment by HigH-HawK** [comment]
**Bromite version**

Version: `78.0.3904.72`
Arch: `arm64`
Android version: `9.0`
Device model: `HTC U11 plus`

**Is this bug about the SystemWebView?**
No

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding Chromium version?**
No

**Is the bug a crash?**
No

**Describe the bug**

With previous versions of Bromite, I could login to the Sony PSN website but with the current version it doesn't work anymore. I enter my username and password and click on login and get an error message. (see previously attached screenshot) I tried the stock Chrome and downloaded Firefox as well as Chromium and the login works in these three, just Bromite causes this issue. I guess there is a security option/setting in Bromite which prevents the login but so far I could not find any option or setting which could cause it. 

Is there any way to find out what option/setting is blocking the login?

**To Reproduce**

Steps to reproduce the behavior:
1. Go to `https://id.sonyentertainmentnetwork.com/signin/`
2. Enter username / password and click on Sign In
4. See error

**Expected behavior**

It should log someone in, instead giving an error message, just like in Chrome, Chromium, Firefox, etc.

**Screenshots**
![PartialScreenshot_20191102-104744](https://user-images.githubusercontent.com/33863449/68089725-358f0800-fe6c-11e9-9cd0-d5b088ba7f78.png)

**Comment by csagan5** [comment]
@HigH-HawK have you tried disabling the ad blocker?

**Comment by HigH-HawK** [comment]
@csagan5 I disabled the AdBlocker and tried it again but unfortunately without success.

**Comment by csagan5** [comment]
@HigH-HawK please connect your device to a desktop Chrome following https://developers.google.com/web/tools/chrome-devtools/remote-debugging

Then you can see in the console the errors

**Comment by HigH-HawK** [comment]
I have done this now and saw one error in the Console:

`POST https://auth.api.sonyentertainmentnetwork.com/2.0/ssocookie 403 (Forbidden)`

So if I'm not mistaken, it looks like a required cookies cannot be set?

**Comment by csagan5** [comment]
@HigH-HawK my conclusion is that they use browser fingerprinting. It's a violation of GDPR so anybody in EU can sue them for it.

You can try telling them that browser fingerprinting is a violation of privacy and anyways not a good/smart thing to do from the perspective of browser use, but I doubt they will do anything about it.

**Comment by HigH-HawK** [comment]
I see! This also shows, that none of the other tested browser are protecting the user from fingerprinting. I will get in touch with Sony and see if and what they say about this. I do however agree with you, that they are not going to do anything about it.

Thanks for your help.

**Comment by csagan5** [comment]
@HigH-HawK in next release you can use two `chrome://flags` flags to disable two types of anti-fingerprinting countermeasures, but it might not be sufficient in this specific case and in general I would stay away from websites which **require** fingerprinting.

**Comment by HigH-HawK** [comment]
@csagan5 Thanks for the info, I'll be happy to test it though. I also contacted Sony, just need to be patient now and see what they are going to say about it.

Thanks again for your help

**Comment by HigH-HawK** [comment]
With the new release `78.0.3904.93` and disabling the flag `chrome://flags/#fingerprinting-canvas-measuretext-noise` the login to the PSN network works again.

I contacted Sony about this but have not had any response so far (pretty sure I will never get any response either).
