### ISSUE TITLE
Navigation bar is white when dark theme is enabled

### ISSUE THREAD

**Issue by jorisludolf** [bromite/bromite#403]
**Bromite version**

Version: `latest`
Arch: `arm64`
Android version: (example: `10.0`)
Device model: (example: `ONEPLUS A6013`)

**Is this bug about the SystemWebView?**
No

No support for SystemWebView installations is provided.

**Is the bug reproducible with latest version?**

Yes

**Can the bug be reproduced with corresponding Chromium version?**

Yes

**Is the bug a crash?**

No

**Describe the bug**

One OxygenOS based devices the navigation bar is solid white unless it's told to be transparent which results in the navigation bar being white when the dark theme is applied.

**To Reproduce**

Use the app in dark mode

**Expected behavior**

The navigation bar be black to blend in with the rest of the UI

**Screenshots**
![Screenshot_20191104-054426](https://user-images.githubusercontent.com/56967367/68101573-2fc61080-fec6-11e9-99c0-a256eeb91ce1.jpg)

[This](https://github.com/andOTP/andOTP/pull/417)  commit for another app seems to explain the problem.

**Comment by csagan5** [comment]
> **Can the bug be reproduced with corresponding Chromium version?**
> 
> Yes

@jorisludolf you need to report the bug upstream to Chromium, as it is written in the template while you submit bugs here:https://github.com/bromite/bromite/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#can-the-bug-be-reproduced-with-corresponding-chromium-version
