### ISSUE TITLE
"Search ready" omnibox unavailable

### ISSUE THREAD

**Issue by brianclemens** [bromite/bromite#404]
### Bromite version
Version: `78.0.3904.72`
Arch: `arm64`
Android version: `8.1.0`
Device model: `angler`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug
The chromium "search-ready" omnibox is unavailable in chrome://flags.  It should be available at chrome://flags/#enable-search-ready-omnibox.  I can see that the search-ready omnibox was disabled by default after #350, in which @jungleballs did not understand that they could edit the URL by pushing the 'pencil' button.  The new omnibox is very handy because it has one-button URL copying (instead of fidgeting with a share menu or having to select all the URL text and long-pressing to copy), so I think it's foolish to disable it by default.

### Steps to reproduce the bug
1. Go to 'chrome://flags/#enable-search-ready-omnibox'
2. Observe lack of flag

### Expected behavior
1. Go to 'chrome://flags/#enable-search-ready-omnibox'
2. Find and enable flag
3. Enjoy new omnibox

**Comment by csagan5** [comment]
> in which @jungleballs did not understand that they could edit the URL by pushing the 'pencil' button. The new omnibox is very handy because it has one-button URL copying (instead of fidgeting with a share menu or having to select all the URL text and long-pressing to copy), so I think it's foolish to disable it by default.

This whole part is off-topic; we don't discuss here which feature is best or not, everyone has opinions.

The bug report is about the missing flag; upstream has completely removed the flag leaving the feature enabled and that Bromite has restored the flag to allow to use it or not; somehow the flag is not showing up and will have to look into it.

**Comment by brianclemens** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Right then.  Is there a mailing list or something to discuss the decision to have the old style inbox set as default?                                                                                                                                                                                                                                                                                                                        From: notifications@github.comSent: November 6, 2019 17:22To: bromite@noreply.github.comReply-to: reply@reply.github.comCc: brian@tiuxo.com; author@noreply.github.comSubject: Re: [bromite/bromite] "Search ready" omnibox unavailable (#404)  
in which @jungleballs did not understand that they could edit the URL by pushing the 'pencil' button. The new omnibox is very handy because it has one-button URL copying (instead of fidgeting with a share menu or having to select all the URL text and long-pressing to copy), so I think it's foolish to disable it by default.

This whole part is off-topic; we don't discuss here which feature is best or not, everyone has opinions.
The bug report is about the missing flag; upstream has completely removed the flag leaving the feature enabled and that Bromite has restored the flag to allow to use it or not; somehow the flag is not showing up and will have to look into it.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by brianclemens** [comment]
Right then.  Is there a mailing list or someplace to discuss the decision of setting the old style omnibox as default?

**Comment by HigH-HawK** [comment]
@brianclemens as @csagan5 said, he will look into it 😉

> somehow the flag is not showing up and will have to look into it.

Just give him some time and who knows, it might be back in the next or following the next release 👍🏼

**Comment by csagan5** [comment]
> Is there a mailing list or someplace to discuss the decision of setting the old style omnibox as default?

For discussions I generally refer to reddit (no specific subreddit) or [this XDA thread](https://forum.xda-developers.com/android/apps-games/app-bromite-chromium-plus-adblocking-t3687258), although I do not always participate there.

You can open a new bug here asking to invert the default, since this issue is about having the flag visible.

This specific issue has been fixed and will be released on next release.
