### ISSUE TITLE
DNS-over-HTTPS - support for other providers

### ISSUE THREAD

**Issue by wioxjk** [bromite/bromite#405]
**Is your feature request related to privacy?**
Yes

**Describe the solution you would like**
It would be great if we users would be able to be given the option to manually enter a DoH address instead of the not so privacy friendly providers like Google or Cloudflare

**Comment by csagan5** [comment]
The feature is planned; beware that the providers you choose should be not only privacy friendly in their statements but also accountable for such statements. That's why only the current list of providers is there.

**Comment by wioxjk** [comment]
I was more thinking about being able to use your own DoH-servers :)

**Comment by csagan5** [comment]
Yes, that will be possible also.

**Comment by csagan5** [comment]
Fixed in `78.0.3904.114` (not yet released).
