### ISSUE TITLE
[Question] How to export browsing history?

### ISSUE THREAD

**Issue by AlexanderRitter02** [bromite/bromite#407]
**The problem**
I would like to export my browsing history (no matter which format) to view it and use it in other programs.

Bromite allows exporting your bookmarks.
However there is no option to export your _browsing history_ (the urls you visited).

The wiki entry ["Migrating user data - Without root"](https://github.com/bromite/bromite/wiki/Migrating-user-data#without-root) using `adb backup` didn't work.
This is because of `android:allowBackup="false"` in the AndroidManifest.xml (also in chrome).
_This presents no possible way, atleast to my knowledge, to backup the history without root_

**Question**
If there is a wiki entry there must surely be some way, that's why I am asking. Sorry for bothering you about such a minor thing.
_Is there a way to backup my browsing history and how does it work?_

**Device info:**
- Android version: 9.0
- Non-rooted
- Bromite version: 78.0.3904.72

**Comment by csagan5** [comment]
It's not possible because it's not possible in upstream Chromium and there are no patches in Bromite for this. 

If you have proof that the allowBackup setting would help you can open a feature request about that.
