### ISSUE TITLE
Sharing a youtube video cuts off part of URL after domain

### ISSUE THREAD

**Issue by jjakob** [bromite/bromite#409]
### Bromite version

Version: `78.0.3904.72`
Arch: `aarch64`
Android version: `7.1.2`
Device model: `Xiaomi kenzo`

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

I can't install Chromium since the bromite f-droid repo is down.

### Is the bug a crash?

No

### Steps to reproduce the bug

1. Go to m.youtube.com. Log in. (Not sure if login is necessary)
2. Under the account menu, select to show the desktop site. You'll be redirected to www.youtube.com.
3. Open any video.
4. Go to the menu and click share. Select any app (one that's convenient to see the shared link). The shared URL will be https://www.youtube.com/
5. Refresh the page. Share again. The full video URL is shared now.
6. click play on the video. Share again. The URL is truncated again.

### Expected behavior

The shared URL should be identical to the one in the navbar.

### Screenshots
n/a

**Comment by csagan5** [comment]
> I can't install Chromium since the bromite f-droid repo is down.
You can download it from the official website or github, the repository is the last of the 3 possibilities.

**Comment by jjakob** [comment]
Sorry, I didn't know the downloads were on the website. I checked it and it's a bug in Chromium so I'll report it upstream.
