### ISSUE TITLE
Google translate doesnt work

### ISSUE THREAD

**Issue by the4anoni** [bromite/bromite#41]
Like in title - no pop up like in android/pc version asking do you want translate this page. Guys please ,thats  only one thing i must keet 2 browsers (this and chrome stable). 
I have latest arm lollipop version.

**Comment by the4anoni** [comment]
Just add an option to use own api keys

**Comment by antonin-lebrard** [comment]
This is intended as written in the changelog.md : https://github.com/bromite/bromite/blob/master/CHANGELOG.md

To be precise the detection of a webpage in foreign language and its translation sends a lot of information to Google. 
And from what I understand this repo try to be an equivalent as the ungoogled-chromium repository

**Comment by the4anoni** [comment]
why closed ?

**Comment by Primokorn** [comment]
@the4anoni 
This question has been answered on XDA. That's he closed it I guess. Here is his XDA 

> If it is about Google services not working (signin, translations, data saver etc), it is not even a bug. The best we can do is completely remove the integrations that Google does not want to give to users of Chromium and its forks (which is fine, their servers their choice), but that will take some time.

**Comment by csagan5** [comment]
Please read at least the README before submitting an issue; it is mentioned in the F.A.Q.s that it cannot work and the reason why.

**Comment by the4anoni** [comment]
But it can. It works in debian chrominium....
