### ISSUE TITLE
Google Search page titles disappear

### ISSUE THREAD

**Issue by proteriax** [bromite/bromite#410]
### Bromite version

Version: `78.0.3904.93`
Arch: `arm64`
Android version: `9.0` and `10.0`
Device model: OnePlus

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Only reproducible with the latest version.

### Can the bug be reproduced with corresponding Chromium version?
No.

### Is the bug a crash?
No

### Describe the bug
Texts disappeared from Google search results.

### Steps to reproduce the bug

1. Search any keyword on Google, with JavaScript and ad-blocking on and desktop mode off.

### Expected behavior
1. Search results have title texts.

### Actual behavior
1. They do not.

### Screenshots
![Screenshot_20191111-111452](https://user-images.githubusercontent.com/8125011/68602549-8ad2a700-0474-11ea-8ec4-abf6c85fa0e7.jpg)

**Comment by HigH-HawK** [comment]
I tried this as well and can reproduce it. If you switch off Javascript, it works again. It looks a bit different though.

**Comment by csagan5** [comment]
Fixed in `78.0.3904.105`
