### ISSUE TITLE
F-Droid repo: Failed to Verify

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [bromite/bromite#413]
### Bromite version

Installed Version: `78.0.3904.72 (1571703171)`
Try to install: `78.0.3904.93 (1572653621)`
Arch: `arm`
Android version: `9.0 Linageos 16 with F-Droid and without GApps`
Device model:  `Samsung Galaxy S5`

### Describe the bug

Cannot update Bromite with F-Droid.
Error Message after downloading and trying to install:

Error while installing Bromite: (Translation of "Fehler beim Installieren von Bromite" [DE])

/storage/emulated/0/Android/data/org.fdroid.fdroid/cache/apks/fdroid.bromite.org--1/rel_78.0.3904.93_ arm_ChromeModernPublic.apk failed to verify!

**Comment by csagan5** [comment]
Duplicate of #412
