### ISSUE TITLE
Pages will crash on Bromite if the device is rotated

### ISSUE THREAD

**Issue by ubergeek77** [bromite/bromite#414]
### Bromite version

Version: `78.0.3904.93`
Arch: `arm64`
Android version: `10.0`
Device model: `Pixel 3 XL`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

_**Yes**_

### Is the bug a crash?

Not exactly, more details below

### Describe the bug

If a page is rotated (due to the device being rotated) in any capacity, i.e. Portrait -> Landscape or Landscape -> Portrait, the page will crash and display the generic message "Aw, Snap! Something went wrong while displaying this webpage."

The page will work correctly if refreshed in the new rotation position - it's only the action of rotating the page that causes the page to crash.

### Steps to reproduce the bug

1. Open the browser
2. Load a page
3. Rotate the page
4. The page will crash

### Expected behavior
The page should not crash upon rotating the device.

---

I realize that this bug is reproducible in Chromium, and that this isn't a Bromite-specific bug. However, I cannot find a bug for it on the Chromium issue tracker, and I don't see any way to report the bug on the Chromium bug tracker (I don't even see a "log in" or "new issue" button).

However, since I can't find discussion of this bug anywhere, even via a web search, I am wondering if the bug is limited in scope to the unique set of users Bromite attracts - rooted Android users - and perhaps hasn't been caught by "standard" users who do not use rooted phones. I also understand that rooting a phone generally does not interfere with apps, but I find it strange that info on this bug has been nonexistent so far.

This bug *does not* occur on proprietary Chrome builds from the Play Store.

This bug did not start in the most recent build of Bromite. I know that there have been at least 2, perhaps 3 releases of Bromite since this started occurring, but I do not know the exact version in which it started. But this is definitely a more recent bug, as I haven't had a bug in Bromite anywhere near this level of severity for as long as I've used Bromite until now.

Since the bug also occurs for me in the latest equivalent of Chromium, the purpose of this issue is to gather more information about the bug, see if it affects other Bromite users, and hopefully get a more technical understanding of why the bug occurs so that it can be submitted to Chromium's fairly strict bug tracker. But any workarounds in the meantime are also very welcome.

**Comment by csagan5** [comment]
> I realize that this bug is reproducible in Chromium, and that this isn't a Bromite-specific bug.

There are some patches applied to the Chromium version built here, although it's a minimum set. See https://github.com/bromite/bromite/blob/master/build/chromium_patches_list.txt

The one with biggest impact is the safe browsing disabling; however in this case I cannot reproduce it so I suggest you gather some information from the crash log (adb).

**Comment by ubergeek77** [comment]
Am I still supposed to get some info from adb or will that not be necessary?

**Comment by csagan5** [comment]
@ubergeek77 if you want to understand why the problem happens on your device, and what possibly is the root cause
