### ISSUE TITLE
Clarification about Bromite SystemWebView update process

### ISSUE THREAD

**Issue by Master0ne** [bromite/bromite#415]
@csagan5, I am using LOS 16 for microG which provides weekly OTA ROM updates, and since the Bromite SystemWebView Magsik module is still broken for apps hidden in Magisk, I have installed the Bromite SystemWebview apk using the file manager of TWRP as per your instructions from the [Installing SystemWebView](https://github.com/bromite/bromite/wiki/Installing-SystemWebView) Wiki page.

Can you please confirm that the Bromite SystemWebview apk indeed needs to be installed

1. to `/system/app/webview` after each and every ROM update
2. to `/system/app/webview` whenever the apk gets updated
3. like a regular app whenever the apk gets updated

and can you please explain why the apk needs to be installed as a regular app in addition to the installation in `/system/app/webview`?

It may be beneficial to add that additional information to the Wiki page in case others may have been confused about this as well.

**Comment by csagan5** [comment]
@Master0ne (2) is not necessary at all, as far as I understood, and it's not what the wiki page says.



> can you please explain why the apk needs to be installed as a regular app in addition to the installation in `/system/app/webview`?

It doesn't.

Please bear in mind that those instructions are aggregated from multiple people/experiences/devices and I cannot ever test all the combinations.

**Comment by Master0ne** [comment]
@csagan5 sorry, I thought that Wiki page has been written by you and I don't know a better place than to bring this matter up.

How can (2) not be necessary? I mean without updating `/system/app/webview/webview.apk` after a new version of Bromite SystemWebview becomes available, how else would it get updated in that folder?

I have added the Bromite F-Droid repo, so Bromite and Bromite SystemWebView updates are handled by F-Droid. Whenever an update to Bromite SystemWebView shows up, I let F-Droid perform the upgrade, but where does F-Droid install it to? Obviously not to `/system/app/webview/` (because then all it needs is a rooted phones and F-Droid and the whole manual installation with renaming and copying to `/system/app/webview/` would be unnecessary).

That's where my confusion is coming from. When / under what conditions does `/system/app/webview/webview.apk` need to be upgraded / reinstalled?

And although I didn't test what happens if not done, but the Wiki clearly says:

> You can use /system/app mover to convert the Bromite SystemWebView APK to a system app. **After rebooting, the app must be installed again on top of the system app.**

and

> **Install the Bromite SystemWebview apk file as you would for any other app. The apps that need the webview will crash if you do not install the Bromite SystemWebView apk after rebooting.**

I think if the Bromite SystemWebview apk hadn't been installed as a regular app, it would not show up in F-Droid as installed and thus wouldn't get upgraded by F-Droid when a newer version becomes available. But what point is there in having Bromite SystemWebview apk in F-Droid if the installation as regular app is not needed and F-Droid doesn't install it to `/system/app/webview/` anyway?

**Comment by csagan5** [comment]
> how else would it get updated in that folder?

It doesn't. It will be loaded from the regular apps folder.

> where does F-Droid install it to?

Regular applications folder.

> When / under what conditions does `/system/app/webview/webview.apk` need to be upgraded / reinstalled?

This has already been asked and replied to.

> I think if the Bromite SystemWebview apk hadn't been installed as a regular app, it would not show up in F-Droid as installed

This is not true.

> what point is there in having Bromite SystemWebview apk in F-Droid if the installation as regular app is not needed and F-Droid doesn't install it to `/system/app/webview/` anyway?

The non-system installation acts as an overlay over the system one, and being more up-to-date and with the same signature gets priority.

For further questions please refer to some other resource (Reddit, XDA) since everything being discussed here applies to any SystemWebView and not specifically to Bromite or Chromium's one.

I will see if wording of the wiki page can be updated/improved.
