### ISSUE TITLE
Import Passwords from a .csv file like desktop chrome

### ISSUE THREAD

**Issue by mthomos** [bromite/bromite#416]
**Is your feature request related to privacy?**
No

**Is there a patch available for this feature somewhere?**
No

**Describe the solution you would like**
Importing passwords from file a .csv file like desktop Chrome. When going to Settings> Passwords, a 3 dot button should exist. On button tap a import option should appear.

**Describe alternatives you have considered**
Another possible solution is enable Desktop chrome settings and from there we can import passwords like desktop Chrome.

**Comment by csagan5** [comment]
Both import and export would need to be addressed; I am not going to develop this feature but I can consider a patch submission.

**Comment by Poopooracoocoo** [comment]
@csagan5 You might want to add this to your FAQ

**Comment by csagan5** [comment]
@Poopooracoocoo there have not been many questions about this to consider it "frequent"; I have not left it open because I think it's not an important feature, nor one that users would need often.
