### ISSUE TITLE
Automatic downloads not disabled ?

### ISSUE THREAD

**Issue by Albnu14** [bromite/bromite#418]
I disabled automatic downloads for all sites from sites settings
**The behaviour I expect** : to get a dialog asking 'what to do with the download' or 'open with' espically for PDF files and videos which I want opened with another app rather than downloaded,
**What I got** : bromite starts downloading right away without giving me the choice.

Is this behaviour a bug ? or am I just expecting too much?.

**Comment by Albnu14** [comment]
If I may ask, does this label mean that I'm the only one facing the issue 'problem is from my side' or that I should ask somewhere else?

**Comment by csagan5** [comment]
@Albnu14 you need to submit the bug via Github desktop mode so that you will see the template.

If you already submitted it in desktop mode then do not remove the template because it must be followed.

**Comment by Albnu14** [comment]
@csagan5 sorry, since I'm pretty new to github.
I will edit the issue with the template and reopen it in a few hours, would that be a problem ? If so , should I open a new issue?

**Comment by csagan5** [comment]
@Albnu14 the template does not show if you use mobile, it's a GitHub bug but they do not express when they will fix it, if ever.

It will be easier if you create a new one.

**Comment by Albnu14** [comment]
Okay ,thanks I will do as you suggest and open a new issue once I update to the last version of bromite.

**Comment by Albnu14** [comment]
Okay ,thanks I will do as you suggest and open a new issue once I update to the last version of bromite.
