### ISSUE TITLE
the site can't be visited when the certificates did not matched

### ISSUE THREAD

**Issue by geol** [bromite/bromite#419]
My ssl certificate is for the site which domain name like example.com, I can visit it through example.com. But when I was on lan, I visit the lan ip for the site just like https://192.168.2.100, it was banned and show this message "ERR_CERT_COMMON_NAME_INVALID". And I setup two domain names for this site but one certificate setup, as the same, the other domain name can't be visited because "ERR_CERT_COMMON_NAME_INVALID". Sorry I'm not good at English, please tell me if you understood or not.

### Bromite version

Version: `76.0...`
Arch: `arm` or `arm64` or `x86`
Android version: 7.1.2
Device model: Nexus 7 2012

### Is this bug about the SystemWebView?
No

No support for SystemWebView installations is provided.

### Is the bug reproducible with latest version?

Do not report bugs which are not reproducible with latest version

### Can the bug be reproduced with corresponding Chromium version?

Please pick the same version of Chromium as Bromite from here: https://github.com/bromite/chromium/releases
If the bug is reproducible then it might be a configuration issue or an upstream bug. Upstream bugs can be reported on the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) and do not forget to read [Chromium project bug reporting guidelines](https://www.chromium.org/for-testers/bug-reporting-guidelines) first.

### Is the bug a crash?

If yes then individuate and post the logcat dump (remove privacy sensitive information, if any), otherwise remove this section.

### Describe the bug

Write here a clear and concise description of the bug.

### Screenshots

If applicable, add screenshots to help explain your problem. Otherwise remove this section.

**Comment by csagan5** [comment]
> Can the bug be reproduced with corresponding Chromium version?

You have missed this step.
