### ISSUE TITLE
Cannot share a URL to Bromite

### ISSUE THREAD

**Issue by cdysthe** [bromite/bromite#42]
Sometimes i want to share a URL to my browser to display it there. Other browsers appear in the Share menu but Bromite doesn't. I hope that can be fixed or added if considered a feature request.

**Comment by csagan5** [comment]
I do not know how to enable this or why it is not working by default; if somebody can explain more or provide a patch, we can add the feature.

**Comment by csagan5** [comment]
@cdysthe share a URL from which app? You are trying to share it from an app to the browser?

**Comment by cdysthe** [comment]
@csagan5 There are apps that open web content that can also be displayed in the browser. Apps like RSS readers and e-mail clients. Those apps often have a share option where I find "Add to Firefox", "Open in LastPass" or "Open in Edge". When I select that share I get the web content shown in that browser. There's no "Open in Bromite" option in the share menu.

**Comment by csagan5** [comment]
I believe this problem has to be fixed in such apps, it is not an Android or Bromite level setting.

**Comment by AndhikaWB** [comment]
I believe his app is not the problem. I think it is something called intent which responded to the share intent made by his app. In this case, Bromite is missing that intent. Reopen this issue?

Reference: https://code.tutsplus.com/tutorials/android-sdk-implement-a-share-intent--mobile-8433

**Comment by AndhikaWB** [comment]
Oh, you can even test it on Bromite share feature and you will also have "Open in Edge" etc. option. If you have Edge or other app installed.

**Comment by csagan5** [comment]
@AndhikaWB does Chromium have such functionality? Bromite is 99% Chromium, code-wise.

**Comment by AndhikaWB** [comment]
Honestly, I think it doesn't. Sorry, can't test it right now due to limited cellular data.

As for myself, I rarely use this 'share' feature, but will be useful when I can't copy URL directly in some apps and paste it in Bromite.

**Comment by AndhikaWB** [comment]
@csagan5 Firefox is open source and add a menu 'Add to Firefox'. Some open source file manager like 'Amaze' (F-Droid) will also add a menu 'Save as..' to the share list.

I would recommend Amaze because it has fewer code than Firefox. I also learned that some apps will also write the intent to AndroidManifest.xml (example: Total Commander, not open source.

**Comment by csagan5** [comment]
The feature might have some use (although not privacy related), but until Chromium adds support for it I cannot see it coming to Bromite. If you find some patch for Chromium for this functionality I might consider adding it.

**Comment by earthsound** [comment]
You define the intent filters in your manifest.

https://developer.android.com/training/sharing/receive

**Comment by csagan5** [comment]
@earthsound that is not sufficient, you need also to write the corresponding code to handle the intents.

**Comment by earthsound** [comment]
@csagan5 does chromium have code to handle intents? https://chromium.googlesource.com/chromium/src/+/master/chrome/android/java/AndroidManifest.xml
https://chromium.googlesource.com/chromium/src/+/HEAD/chrome/android/java/src/org/chromium/chrome/browser/IntentHandler.java

**Comment by csagan5** [comment]
> does chromium have code to handle intents?

Not those intents.
