### ISSUE TITLE
DOH Issue

### ISSUE THREAD

**Issue by icejr** [bromite/bromite#422]
### Bromite version

Version: `78.0.3904.105`
Arch: `arm64`
Android version: `10.0`
Device model: `whyred`

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

AFAIK corresponding Chromium version doesn't support DOH

### Is the bug a crash?

No

### Describe the bug

I've set Private DNS to `one.one.one.one` which supports DOT and enabled DOH with Cloudflare but `https://1.1.1.1/help` shows both DOT and DOH as inactive. tried turning off DOH in Bromite but still DOT shows inactive.

I strongly believe that this is Bromite's issue because DOH was working fine couple of months back while DOT showing inactive. tested Fenix (Nightly) DOH works with inactive DOT.

### Steps to reproduce the bug

1. Turn on Private DNS.
2. Enable DOH in Bromite.
3. Check `https://1.1.1.1/help`

### Expected behavior

I expect DOH to work while using Private DNS with DOT.

### Screenshots

None.

**Comment by csagan5** [comment]
I think this might be a duplicate of #336 e.g. Android system overrides the browser's DNS selection.

**Comment by csagan5** [comment]
@icejr can it be reproduced with latest version? You will have to specify the DoH URL by yourself, see https://www.bromite.org/doh

**Comment by icejr** [comment]
@csagan5 DOH is working! thanks...
mind if I know what was the issue?

**Comment by csagan5** [comment]
@icejr I will reply in #336
