### ISSUE TITLE
Youtube no longer plays in the background

### ISSUE THREAD

**Issue by peta9** [bromite/bromite#424]
### Bromite version

Version: `78.0.3904.105`
Arch: `arm`
Android version: `9.0`
Device model: Nokia 1

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

Not a feature of chromium

### Is the bug a crash?

No

### Describe the bug

Youtube videos cannot be played in the background

### Steps to reproduce the bug

1. Go to 'https://m.youtube.com'
2. Play any video
3. Put Bromite in the background
4. See bug

### Expected behavior

Youtube videos are expected to play in the background

**Comment by csagan5** [comment]
Fixed in `78.0.3904.119`
