### ISSUE TITLE
Allow "Exit" option to clear browsing data

### ISSUE THREAD

**Issue by CodeBoy66** [bromite/bromite#426]
### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

Not that I am aware of

### Describe the solution you would like

It would be nice to allow the "Exit" option to also clear browsing data. Currently the only way to clear browsing data is through the browsing or privacy sub-menu ( 2 or 3 steps) and the "Exit" option only clears tabs. Would it be possible to allow an option for the "Exit" button to clear all browsing data....

![img_eggsif_6999906214329787283](https://user-images.githubusercontent.com/58365937/69910823-e5ee1e80-13ce-11ea-8b96-518874569558.jpg)

(or I suppose go off of whatever you already have checked/unchecked in the privacy sub-menu)....

![Screenshot_20191201-000820_Bromite](https://user-images.githubusercontent.com/58365937/69910830-0ddd8200-13cf-11ea-9ce7-cd8270b40bdf.jpg)

 as well as all open tabs - essentially a full session clear with one click. 

### Describe alternatives you have considered

No practical alt solutions

**Comment by iamrobox001** [comment]
There could be a check mark to Clear data on exit, like how Firefox does it.
Or a new option in the menu, Clear and Exit

**Comment by kef71** [comment]
I agree, an option to clear all cached data on exit would be awesome.

**Comment by csagan5** [comment]
You can achieve the same functionality (except for history) by enabling `Incognito mode` and `Close tabs on exit`.

**Comment by CodeBoy66** [comment]
> You can achieve the same functionality (except for history) by enabling `Incognito mode` and `Close tabs on exit`.

@csagan5 
Hi, sorry for the late response, was traveling for the last few weeks and not checking here. I know you can get _very close_ to that functionality with what you mentioned but it's not really the same thing especially since then you are forced to keep no history at all, which is not necessarily very efficient - sometimes it's useful to be able to go in the review your browsing history _within the current session._

I was hoping just for one of the options mentioned above- either a *Clear & Exit* option, or what Firefox has which allows you to toggle on / off whether or not the data gets cleared when you exit in one of the many ways. To me it seems like for a privacy Centric browser the ability to, Simply put, do your business, and then nuke everything with one press, rather than having to navigate two or three different menus every time, seems like it should be a given. Imo.

**Comment by csagan5** [comment]
@CodeBoy66 in Bromite you can enable the option to clear the cookies automatically on exit.



> To me it seems like for a privacy Centric browser the ability to [...] rather than having to navigate two or three different menus every time, seems like it should be a given. Imo.

We can all have opinions, that's a given. The available alternatives are those mentioned already: always-incognito mode or enabling close tabs + clear cookies on exit.

**Comment by csagan5** [comment]
@CodeBoy66 to give more context: this feature has been requested in the past, but if it were implemented then the next feature users would need is the possibility to add site exceptions.

If you enable the settings to close tabs and clear cookies on exit, what browsing data is left?
* cache
* history

I assume you want to keep the history (but history URLs are also used for tracking) and remove the cache. In the end there is not much difference from incognito mode and because of the need of per-site exceptions this is something that is better handled upstream. I could not develop it even if I wanted.
