### ISSUE TITLE
Countering incognito mode detection scripts

### ISSUE THREAD

**Issue by baybal** [bromite/bromite#428]
### Is your feature request related to privacy?

Incognito mode detection prevent users from using it

### Is there a patch available for this feature somewhere?

Lots of assorted patches at the moment

### Describe the solution you would like

I think, adding at least basic countermeasures like filesystem API fingerprint fuzzing should be a no brainer

### Describe alternatives you have considered

I think there is really no easy shortcut, and it will be a long whack a mole with ad companies as new ways to detect incognito are being found

**Comment by csagan5** [comment]
> Lots of assorted patches at the moment

But you have not mentioned any, the template says `If yes then provide URL and license information.`

> I think, adding at least basic countermeasures like filesystem API fingerprint fuzzing should be a no brainer

Patches are welcome.

The `EnablePersistentFilesystemInIncognito` feature is already enabled by default by upstream Chromium, if you know more about current ways to detect incognito mode with Chromium v78+ please explain and/or submit upstream feature requests.

**Comment by baybal** [comment]
EnablePersistentFilesystemInIncognito does not conceal the different storage sizes in incognito and normal modes.

Performance metric scripts are way harder to defeat, and am not sure if few patches going around offer a net benefit.

I think I will spend this weekend collecting those patches.
