### ISSUE TITLE
Video playback not working

### ISSUE THREAD

**Issue by lovebromite** [bromite/bromite#429]
### Bromite version

Version: `78.0.3904.105`
Arch: `arm64`
Android version: `9.0`
Device model: `A6013`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug
A lot of videos do not play anymore, since the last 2-3(?) releases of Bromite, while they do play in Chromium. For convenience I've added the output from chrome://media-internals of a random video:

render_id: 64
player_id: 54
origin_url: https://m.9gag.com/
frame_url: https://m.9gag.com/gag/aQ1g7PK
frame_title: The dog is made of fast
surface_layer_mode: kAlways
url: https://img-9gag-fun.9cache.com/photo/aQ1g7PK_460svav1.mp4
total_bytes: 360587
streaming: false
single_origin: true
range_header_supported: true
pipeline_state: kStopped
info: Effective playback rate changed from 0 to 1
bitrate: 220761
found_audio_stream: false
found_video_stream: true
height: 240
max_duration: 13.067
start_time: 0
time_base: 1/15360
video_codec_name: av1
video_is_encrypted: false
width: 426
error: video decoder initialization failed
event: PLAY
pipeline_error: DECODER_ERROR_NOT_SUPPORTED
duration: 13.067

### Steps to reproduce the bug

1. Go to 'https://m.9gag.com'
2. View any video on the page
3. See error

### Expected behavior
Videos should play normally, but they hang on the first frame.

**Comment by csagan5** [comment]
> they do play in Chromium.

The one you reported https://m.9gag.com/gag/aQ1g7PK does not play on Chromium.

I am afraid this might be caused by a codec problem.
