### ISSUE TITLE
Option to ignore ERR_CERT_AUTHORITY_INVALID is missing

### ISSUE THREAD

**Issue by ssokolow** [bromite/bromite#431]
### Bromite version

Version: `78.0.3904.105`
Arch: `arm`
Android version: `6.0.1; SM-G955U Build/M4B30Z`
Device model: LG-D820 (Hand-me-down Nexus 5 with no SIM used for testing web apps)

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
How do you define "latest version"? I'm on the newest version available through the official Bromite F-Droid repository.

### Can the bug be reproduced with corresponding Chromium version?
Yes.

### Is the bug a crash?
No.

### Describe the bug
I have some LAN-only projects which I want to access from my test phone, but they use features that are only available over HTTPS. As they're not visible on the public Internet, I can only use a self-signed certificate for them.

Firefox Mobile and dangerously out-of-date versions of Chrome/Chromium allow me to bypass the self-signed certificate error, but some of the features I want to experiment with (such as non-polyfilled ImageCapture API) require something else.

However, current Bromite and Chromium versions don't provide an option to bypass the self-signed certificate error and proceed to the page.

I'd report this to Chromium upstream, but I have a very strong impression that this is `RESO NOTABUG` (to use Bugzilla parlance) just like various anti-user-empowerment Google decisions that Bromite has reversed.

(Note that I do *not* want to add the self-signed certificate as a trusted CA. I only want to trust it for this one site and I'd be OK with clicking "proceed anyway" every time I visit it.)

### Steps to reproduce the bug

1. Connect to something served with a self-signed certificate
2. Note that there's no option to bypass the error (and, since it's not Desktop chromium, there's no way to edit the command-line flags to change that)

### Expected behavior

There should be some kind of link/button which enables bypassing self-signed certificate errors.

### Screenshots

I get an "isn't allowed by your app or organization" error.

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> Yes.

As the template explains then you have to report this upstream.

**Comment by ssokolow** [comment]
What if I re-file it as a feature request?

**Comment by csagan5** [comment]
@ssokolow there are probably already issues opened upstream about this.

On Android you can create a launcher to pass the `--ignore-certificate-errors` command-line switch or you can install your own CA certificate on Android itself.

I understand you see it as a feature regression but it is out of scope for Bromite thus I do not commit to implement and/or include a feature change downstream.

**Comment by ssokolow** [comment]
> On Android you can create a launcher to pass the `--ignore-certificate-errors` command-line switch.

Bromite picks it up and complains about it being a security hazard, and still gives me `ERR_CERT_AUTHORITY_INVALID`, but thanks anyway.

Even knowing it existed, it took me far longer than it should to craft a search which successfully pulled up instructions for how to enable and use `/data/local/tmp/chrome-command-line`

(I guess I'll have to go with adding the CA cert I was hoping to avoid.)
