### ISSUE TITLE
Adblock help page doesn't exist

### ISSUE THREAD

**Issue by Madis0** [bromite/bromite#434]
### Bromite version

Version: 78.0.3904.130
Arch: `arm64`
Android version: `9.0`
Device model: OnePlus A5010

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is the bug a crash?

No

### Describe the bug

The help page in adblock settings (https://www.bromite.org/custom-filters) returns 404

### Steps to reproduce the bug

1. Open menu
2. Go to settings
3. Click on AdBlock settings
4. Click on Visit help page

### Expected behavior

A page with descriptive contents instead of an error page. Either change the URL in browser or create a page there.

### Screenshots

N/A

**Comment by csagan5** [comment]
@Madis0 you need to wait for GitHub to publish the page

**Comment by csagan5** [comment]
Should be up in minutes.
