### ISSUE TITLE
block speedial sites in new tab page

### ISSUE THREAD

**Issue by sviluppoSoftware** [bromite/bromite#436]
### Is your feature request related to privacy?
no

### Is there a patch available for this feature somewhere?
no

### Describe the solution you would like
it would be useful to be able to block speedial sites in new tab page so that they aren't removed when the browser data are deleted (cookies, history, etc..)

### Describe alternatives you have considered
implement a more fast access to mobile bookamarks , like an icon beside the address bar

**Comment by csagan5** [comment]
The scope of this feature is Chromium for Android and not Bromite.
