### ISSUE TITLE
snapdrop.net doesnt't work properly

### ISSUE THREAD

**Issue by ZeDeedIsDone** [bromite/bromite#438]
### Bromite version

Version: `78.0.3904.130`
Arch: `arm`
Android version: (example: `6.0`)
Device model: (example: `PLK-L01C636B375`)

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No, it works normally on the Chromium version

### Describe the bug

snapdrop.net, a website that kinda imitates airdrop, isn't working (sending/receiving messages/files)

### Steps to reproduce the bug

1. Go to snapdrop.net on Bromite
2. Go to snapdrop.net on any other web browser
    (Both browsers can now see one another)
4. Try to send a message or a file through snapdrop.net on either bromite or another web browser

### Expected behavior

The message or files should be received by the other web browser or bromite respectively.

**Comment by csagan5** [comment]
Bromite does not include Play Service integrations which are needed for this functionality.

**Comment by csagan5** [comment]
I might be wrong and this could be a duplicate of #470.

Please test with next release which will address that issue.
