### ISSUE TITLE
Run at startup permission

### ISSUE THREAD

**Issue by headcreep** [bromite/bromite#439]
### Bromite version

Version: `78.0.3904.130`
Arch: `arm64`
Android version: 7
Device model: vs987

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes
Do not report bugs which are not reproducible with latest version

### Can the bug be reproduced with corresponding Chromium version?
Unknown

### Is the bug a crash?
Yes

### Describe the bug
If "run at startup" permission is disabled, bromite cannot launch at all. chrome failed to startup with an unexpected error. Why does bromite have that run at startup persimmon when it is completely unnecessary? It should not need to be run on device boot. If the user needs this on android, then there are apps that do not require root that can achieve this. However, on the contrary, trying to disable run at startup maybe impossible without root. Only the bare essential apps should be launched on boot or reboot. Bromite developers need to respect that resources are limited on some devices more than others and having the run at startup permission is both unwanted and unnecessary as it attributes to stress on devices with many apps installed with no benefit. Imagine you have 100 apps installed and all of them run at start. That paints an ugly picture.

### Steps to reproduce the bug

1. Launch Apk permission remover
2. Uncheck "run at startup" save and install Bromite.apk
3. Open Bromite after package install
4. Bromite error "chrome failed to startup with an unexpected error"
### Expected behavior
Every app I have used apk permission removed to disable run at startup has worked without issue until I tried it on bromite. The expectation is that users ought to be able to have Bromite installed without having the app run at startup.

**Comment by ouzowtf** [comment]
You should check with the same Chromium version too
