### ISSUE TITLE
Ad blocker not working

### ISSUE THREAD

**Issue by rohang02** [bromite/bromite#444]
### Bromite version

Version: `79.0.3945.94`
Arch: `arm64`
Android version: `9.0` (Android One)
Device model: `Xiaomi Mi A3`

### Is this bug about the SystemWebView?
`No`

### Can the bug be reproduced with corresponding Chromium version? 

`Not related to Chromium`

### Describe the bug

Ads show up on almost all websites even with "Block ads" turned on.

### Steps to reproduce the bug

Visit any website having ads.

Pages I visited in this example: 

`https://m.timesofindia.com/`
`https://m.economictimes.com/`

### Expected behavior

Ads shall not show up.

### Screenshots

![Screenshot_20191221-104030](https://user-images.githubusercontent.com/47921164/71303569-c1d79900-23e0-11ea-8575-9e5b297aaad0.png)

![Screenshot_20191221-105545](https://user-images.githubusercontent.com/47921164/71303574-cbf99780-23e0-11ea-9ebc-ebb20f353c14.png)

**Comment by csagan5** [comment]
@rohang02 please close the app and re-open it recording the adb logcat output, then submit it here. I suggest collecting it like this:
```
adb logcat | grep AdBlockUpdaterService
```

So that there is no privacy-sensitive or anyway unnecessary log information included.

**Comment by subi54** [comment]
Cannot reproduce. Adblocker working as expected.
