### ISSUE TITLE
Authenticity verification of the latest version failed

### ISSUE THREAD

**Issue by fi007** [bromite/bromite#446]
Of course I have imported the public key, but the latest version didn't pass the authenticity verification. Here is the result.

gpg2 --verify brm_79.0.3945.94.sha256.txt.asc
gpg: assuming signed data in 'brm_79.0.3945.94.sha256.txt'
gpg: Signature made 2019-12-20 07:42:36 +0000 GMT
gpg:                using RSA key ***
gpg: Can't check signature: No public key

**Comment by csagan5** [comment]
@fi007 thanks for reporting, it was built on a different box than usual so I will check and follow up.

**Comment by csagan5** [comment]
@fi007 will re-create this issue

**Comment by csagan5** [comment]
Issue has now been fixed; I will investigate about which build box caused the issue.
