### ISSUE TITLE
incognito mode broken 

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [bromite/bromite#450]
Version: v79.0.3945.94 
Arch: arm
Android version: 8.1
Device model:  mate 10 lite

Is this bug about the SystemWebView?

No

Is the bug reproducible with latest version?

This behaviour only appears in the latest build version.

Can the bug be reproduced with corresponding Chromium version?

If this means the same kind of thing happens on Chrome, then no.

Is the bug a crash?

No.

Describe the bug

when enabled incognito open always , when try open link apps example youtube , telegram ....  apps closed 

Steps to reproduce the bug

1. Enabled always open incignito mode
2. try open link with random apps

**Comment by djetzen** [comment]
It is not only incognito mode, also in normal mode. At the moment for me it is not possible to watch any videos at all.

**Comment by randomshell** [comment]
@djetzen I don't see a new release on holiday. If you like a workaround, first open bromite in background, switch to another app and click the link you want.

**Comment by csagan5** [comment]
@Disqu3-mirOir-qt I cannot reproduce this issue; links open in incognito mode regularly when it's enabled.

**Comment by randomshell** [comment]
@csagan5  here is adb logcat opening link from another app [open.txt](https://defuse.ca/b/1OTHi8dc). As said in previous comment, it crashes only if bromite isn't already running in the background, otherwise it opens the link in new tab without issues.
Latest release working is 78.0.3904.130.

Any more info I need to add?

**Comment by csagan5** [comment]
@randomshell this bug report is not about a crash, if you experience a crash please first check if issue does not already exist and then open a new issue and attach the log here on GitHub (see [documentation on how to do that](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests)).

**Comment by randomshell** [comment]
The description of the bug is the same. From logs it appears to be a crash, anyway bromite closes when trying to open link from another app.
Do I really need to open a new issue for a possible mistake in the bug report?
