### ISSUE TITLE
Video player freezes after 1 second

### ISSUE THREAD

**Issue by valpamp** [bromite/bromite#455]
### Bromite version

Version: 79.0.3945.107
Arch:  arm64
Android version: 10.3.0
Device model: SM-G955U, Build/QKQ1.190716.003

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
Yes, the behavior is exactly the same.

### Is the bug a crash?
No, only the video player freezes, but the app continues working normally.

### Describe the bug
The video player freezes infallibly after 1 second of playtime. The bug is reproducible in the corresponding Chromium versions, and is also reproducible on Bromite versions .100, .94. **Downgrading to version 78.0.3904.130 fixes the issue.**

### Steps to reproduce the bug
1. Go to https://vimeo.com/311983548
2. Click on the play button.

### Expected behavior
Watch the video start normally and freeze after 1 second of playtime. Notice that the video continues preloading and that in this specific case (Vimeo) the video restarts automatically and freezes again after 1 second. On other websites (e. g. Facebook, YT, etc.) the video simply stops playing.

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> Yes, the behavior is exactly the same.

As explained [while submitting the issue](https://github.com/bromite/bromite/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#can-the-bug-be-reproduced-with-corresponding-chromium-version) you have to report such issues upstream, not here.

Possibly related: #445
