### ISSUE TITLE
Consider adding ecosia as a search engine option?

### ISSUE THREAD

**Issue by lachlanallison** [bromite/bromite#456]
### Is your feature request related to privacy?
Ecosia is a search engine aimed at plating trees around the world but they also claim to be privacy friendly. It would be nice to have this search engine as a built in option in Bromite. However I am not sure if the privacy of this search engine is comparable to others added (Startpage/Qwant).
https://info.ecosia.org/privacy

### Is there a patch available for this feature somewhere?
n/a

### Describe the solution you would like
Ecosia added as search engine option.

### Describe alternatives you have considered
Ignore this issue if it doesn't meet privacy requirements.

**Comment by csagan5** [comment]
@lachlanallison see https://github.com/bromite/bromite/wiki/SearchEngines

There is no need to add more search engines since they can be added upon first visit, see the mentioned wiki page.

**Comment by lachlanallison** [comment]
Cheers, didn't realise that.
