### ISSUE TITLE
Add qwant search engine

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#46]
https://www.qwant.com/

It is a France-based company that says being respectful of users' privacy.

It should be possible to add it in Bromite.

**Comment by Primokorn** [comment]
There's also tracking in Qwant. Their privacy policy is still way better than Google, Bing...

**Comment by csagan5** [comment]
Yes, I am adding it to enlarge the alternatives available. I was not aware of this search engine, it seems fair and it might please others too.

Added in upcoming `65.0.3325.176`.
