### ISSUE TITLE
Add support extensions

### ISSUE THREAD

**Issue by OmlineEditor** [bromite/bromite#462]
Add support for plugins and extensions from the store:
https://chrome.google.com/webstore/category/extensions

- There are extensions for easier cleaning of the cookies.
- There are extensions for better and more flexible ad blocking and tracking.
- there are extensions to mask and change the "user-agent" string ...

The basis of the browser is the same, so the extensions should stand up without problems.

**Comment by Merith-TK** [comment]
They said they cant do it, 

but if they take ideas from kiwi browser they can 
Kiwi browser can install extensions from there, 
but yeah im gonna use Bromite instead of brave once i finnish reading all my stories i have in tabs.

**Comment by ouzowtf** [comment]
No, kiwi patches can't be used, because the available sources of kiwi are not working ones. Nobody knows what's happening in kiwi, except the developer.

**Comment by csagan5** [comment]
This issue is missing the template, which is not optional.

Also, you should search the issue tracker before submitting.
