### ISSUE TITLE
Whitespace after Ad is blocked

### ISSUE THREAD

**Issue by RuthlessRuler** [bromite/bromite#463]
### Bromite version

Version: 79.0.3935.111
Arch: arm64
Android version: 9.0
Device model: Harpia(G4 Play)

### Is this bug about the SystemWebView?
No

No support for SystemWebView installations is provided.

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

Nope

### Is the bug a crash?

Nope

### Describe the bug

Often ads are blocked but leave behind whitespace instead of it. The whitespace too should be removed.

### Steps to reproduce the bug

1. Visit a website, Eg. coolztricks.com
2. There is white space on top after the ad is blocked. The whitespace should also be removed.

### Expected behavior

No whitespace should be shown.

**Comment by csagan5** [comment]
I can accept a patch for cosmetic fixes, but there will be no development on this.
