### ISSUE TITLE
Cannot access to a needed web page

### ISSUE THREAD

**Issue by angelog0** [bromite/bromite#464]
### Bromite version 

Version: `79.0.3945.107`
Arch: `arm64`
Android version: (example: `8.0.0`)
Device model: `SM-G955U Build O00623`

As a teacher I need to connect to this [page](https://re23.axioscloud.it/Secret/REStart.aspx?Customer_ID=93015960581) where I can handle my classes (it is an Institutional page of the School). When I try, it load the page for an instant then shows the [logoff](https://re23.axioscloud.it/Secret/RELogOff.aspx?Error_Desc=[9996]%20L%27utente%20Non%20possiede%20il%20Livello%20di%20Autorizzazione%20all%27uso%20di%20questa%20Procedura.&Error_Parameters=Non%20sono%20disponibili%20informazioni%20aggiuntive#b) page, more precisely the End Session page. On the same system I can work with that page using Chrome, even with DuckDuckGo search engine and enabling or disabling all the setting for privacy protection (at least, for what I know...) Maybe there is some setting in Bromite I have to change.. but which?

Thanks

**Comment by csagan5** [comment]
@angelog0 have you tried disabling the ad blocker for the site?

**Comment by angelog0** [comment]
I disabled completely the ad blocker... but it didn't help...

**Comment by csagan5** [comment]
@angelog0 try to login from the home page

**Comment by angelog0** [comment]
The login page of my School has this address `https://re2.axioscloud.it/Secret/REStart.aspx?Customer_ID=SCHOOL_CODE`, where `SCHOOL_CODE` is an integer number of 11 digits. Usually the School site has an icon for that address. Clicking it, it loads the login page containing the fields for user ID and password (and other informations).

I noticed the when the login page is loaded (with Chrome or Chromiumiu on Windows or GNU/Linux), the address bar contains this address `https://re2.axioscloud.it/Secret/RELogin.aspx` and not what one has clicked previously. So I copy/pasted this last address in a new tab of the browser (on Windows or GNU/linux) but this does not give the login page but the logoff page! with an address like this `https://re2.axioscloud.it/Secret/RELogOff.aspx?Error_Desc=[9996]%20L%27utente%20Non%20possiede%20il%20Livello%20di%20Autorizzazione BLA BLA BLA`.

Now, in Bromite ALL this occurs just clicking the login page of the School!

**Comment by angelog0** [comment]
BTW, on the tablet where Bromite is installed, I applied **all** Bromite settings to Chrome (at least, those I have found) but Chrome continues to behave as expected... so it seems that the different behavior relies in Bromite patches or something similar... it is a pity I cannot use Bromite for my work, I need to connect there daily.

Also the ungoogled Chromium from [here](https://chromium.woolyss.com/#android) gives the same result of Bromite... WHAT A PITY!

**Comment by randomshell** [comment]
I used remote debugging to understand  what is the issue because the error displayed isn't useful. So Bromite doesn't send referrers and the website wants them for csrf checking. I saw this on not many websites and is obsolete and insecure.

@csagan5 What do you think on send referrers in the context of same domain to allow this checks? I don't think it's a privacy issue.

**Comment by csagan5** [comment]
@randomshell that is something handled by upstream, not Bromite.

@angelog0 you have skipped submitting the issue with the issue template. The issue template requests to test with [Chromium](https://www.bromite.org/chromium) first. If it is a Chromium issue then it is not a Bromite bug.

**Comment by angelog0** [comment]
Chromium works as expected on GNU/Linux, Windows and macOS (all builds from [woolyss](https://chromium.woolyss.com)), and also with all Bromite settings that one can apply to Chromium. Just the Android version does not work, but [there](https://github.com/macchrome/droidchrome/releases/tag/v79.0.3945.123-r706915-Ungoogled-And64) I read `with Bromite` patches...

@csagan5, I don't understand:
> you have skipped submitting the issue with the issue template

[here](https://github.com/bromite/bromite/issues/464#issuecomment-573900409) I tried to describe the issue as accurately as I could.

In any case this issue is closed and I flagged the above thing just for completeness. Thanks.

**Comment by randomshell** [comment]
@csagan5 I already tried with Chromium build from bromite.org and it works.

**Comment by angelog0** [comment]
@csagan5 wrote:
> The issue template requests to test with Chromium first.

I just tried this `chr_arm64_ChromeModernPublic.apk` (`79.0.3945.123`) from the link you proposed and it works as expected, no issues. BTW, I found it very very similar to Chrome, just the icon seems to be a bit different...

**Comment by angelog0** [comment]
Just for completeness, I tried also Brave browser on the Android device and on other OS and it works with that web page (even with all Bromite settings I can set). So, it seems that only **Bromite** _doesn't_... :-(

**Comment by randomshell** [comment]
@csagan5 what do you mean upstream? I thought I will find the `referer` term in this repo but didn't find any patch that mentions it. What am I missing?

@angelog0  why do you need to attack bromite and annoy with what a pity etc?
I did take a look at this issue and my findings are above. Now it's up to the maintainer or a contributor to write a fix.
Use another browser for this website until then or be more friendly. Firefox lite is 6MB.

**Comment by csagan5** [comment]
> what do you mean upstream?

The upstream for Bromite is the Chromium project.

> why do you need to attack bromite and annoy with what a pity etc?

@randomshell I understand your good intentions but we have to refrain from this type of feedback as it can heat up conversations. Unfortunately a thick range of users will ignore that the issue template specifically mentions to not compare with other browsers in this way and we have to still be kind and patient. I will not however be motivated to follow up on issues which do not fully follow the template, even if there are real bugs behind, as it makes it very hard to reproduce and individuate issues.

As for the specific issue, thanks for digging out the correlation with referers, I think I have a clue, see my reply in #470.

**Comment by csagan5** [comment]
@angelog0 the issue has been individuated as part of #470 and it will be fixed on next release; please verify that after the release.

**Comment by angelog0** [comment]
@csagan5, the issue I flagged seems fixed in the last release. Thanks.
