### ISSUE TITLE
F-Droid Repo Down?

### ISSUE THREAD

**Issue by tvdmitrii** [bromite/bromite#465]
It seems like encryption certificate for F-Droid repo expired. Browser give an error when following the repo url, and F-Droid app says "Error getting F-Droid index file -> No mirrors available"

**Comment by csagan5** [comment]
Thanks for reporting; try again in a couple hours, it should be fixed now.

**Comment by antzi** [comment]
The same thing happens now. Maybe the certificate has to be renewed again?
