### ISSUE TITLE
Per site adblock & javascript is less user friendly & breaks incognito

### ISSUE THREAD

**Issue by aluo-x** [bromite/bromite#466]
### Bromite version

Version: `79.0.3945.123`
Arch: `arm64`
Android version: `10.0`

### Describe the bug

Since `79.0.3945.107`? there is now per site javascript & adblock settings, which can be accessed by tapping on the top left corner of the navigation bar.

There are a 3 issues with this, the first two are related to usability and are not critical; while the last one is I think more important, as it kind of breaks incognito.

1. The javascript & adblock settings are harder to discover
* The top left of the navigation tool bar is not usually used during the normal browsing process
* There is no obvious indication that javascript and adblock can be controlled after tapping the tool bar

2. To disable/enable javascript & adblock requires more user operations
* In the past with global javascript & adblock, you need exactly 3 taps to change state
 -- tap top right three dots menu
 -- tap disable adblock
 -- tap page to close menu, and the website auto-refreshes with adblock disabled
* Currently you need 6 taps to change state
 -- tap top left of navigation bar
 -- tap site settings
 -- tap adblock
 -- tap disable
 -- tap return
 -- refresh page

3. Per-site javascript & adblock settings are saved, even in "open all tabs in incognito", and with "close tabs on exit"
 * If you choose to disable javascript or adblock on a site, you can see the per-site settings in the chrome settings. There is no obvious way to clear all these per site settings

**Comment by aluo-x** [comment]
To replicate issue 3:
1. Enable `Open all tabs in incognito`, enable `Close tabs on exit`. Restart Bromite
2. Go to a site, for example `google.com`
3. Disable per site adblocking, by using top left button
4. Refresh page, and quit Bromite
5. Start Bromite, go to settings, go to `Site settings` -> `Ads`
6. `google.com` will be listed as an exception

**Comment by csagan5** [comment]
@aluo-x the issue template is not optional; the issues you reported should be reported upstream to Chromium, they will probably reply that it is by design (except for the lack of refresh perhaps).

I am not going to change Bromite back to have a global toggle for ads/javascript; related: #133

**Comment by ArsenArsen** [comment]
As a note, one can still globalu disable both JavaScript and adblock in the settings.  
Now, as for my actual question: could the shortcuts in the 3 dots menu be added back to apply per-site? I, and surely many others, found them very useful, and at least in my case they would still be useful even if they were per site.
