### ISSUE TITLE
Smartthings app cannot log into samsung account with bromite as default  browser.

### ISSUE THREAD

**Issue by famewolf** [bromite/bromite#468]
### Bromite version

Version: `79.0...`
Arch: `arm64` 
Android version: (example: `9.0`) Oxygenos 10 (Android 10)
Device model: (example: `SM-G960UZKABST`) Oneplus 7 Pro

### Is this bug about the SystemWebView?
No

No support for SystemWebView installations is provided.

### Is the bug reproducible with latest version?
Yes

Do not report bugs which are not reproducible with latest version

### Can the bug be reproduced with corresponding Chromium version?
N/A 
Please pick the same version of Chromium as Bromite from here: https://github.com/bromite/chromium/releases
If the bug is reproducible then it might be a configuration issue or an upstream bug. Upstream bugs can be reported on the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) and do not forget to read [Chromium project bug reporting guidelines](https://www.chromium.org/for-testers/bug-reporting-guidelines) first.

### Is the bug a crash?
No

### Describe the bug

Write here a clear and concise description of the bug.
With bromite set to default browser upon running the smartthings app it attempts to open the samsung login page.  If running bromite it takes you to a page telling you that you are running an unsupported browser and will have to change to a supported one.  Under chrome login page shows as normal.  If the user is already signed in bromite works just fine until the next time they prompt you to relogin.
![Screenshot_20200116-182347](https://user-images.githubusercontent.com/4558832/72571424-84eead00-388d-11ea-97c4-34467001964a.jpg)

### Screenshots

If applicable, add screenshots to help explain your problem. Otherwise remove this section.

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> N/A

@famewolf this part is not optional

**Comment by famewolf** [comment]
> > ### Can the bug be reproduced with corresponding Chromium version?
> > N/A
> 
> @famewolf this part is not optional

In my description I did state that the login worked just fine when using chrome and I am on the latest version.

**Comment by ouzowtf** [comment]
This site just uses browser sniffing and excludes all other browsers.
You can't fix and maintenance such issues (and fake a different browser) per site as an individual, most time not even as a company (for example ask the former Opera and now Vivaldi browser developers).

**Comment by famewolf** [comment]
In the past a plugin has allowed the user to specify whatever useragent they wanted to get around issues like this (at least on the desktop).   **I'd consider the smartthings app not being able to be used when using bromite (and I confirmed the same with brave) to be a pretty major issue since it's the most popular hub used to link devices to both amazon alexa and google home.**  If you can't login you can't scan for new devices and that CAN'T be done from the web page using a desktop browser.

**Comment by ouzowtf** [comment]
It could get better with [this](https://www.androidpolice.com/2020/01/14/chrome-wants-to-kill-browser-user-agent-strings-cites-compatibility-and-privacy-concerns/) or it stays the same shit as now ¯\_(ツ)_/¯

**Comment by csagan5** [comment]
> In my description I did state that the login worked just fine when using chrome and I am on the latest version. What sense does it make to fully close an actual issue because you want one clarified piece of information?

@famewolf that is not what happened here. The issue template asks for you to test with the corresponding Chromium version (**not** chrome, **not** the version you have installed) and you have decided to write `N/A` instead. I am sorry, that is not accepted. I know that it takes extra work, but that is how we keep the project running (by requesting the issue reporter to do some tests and fill in the template).

As for this specific issue, it will stay closed because it is currently still **incomplete**, as no one has tested it with the [current Chromium version](https://www.bromite.org/chromium).

You might want to follow #470 as I guess that it is _probably_ the same issue.
