### ISSUE TITLE
Consider turning "Search Ready Omnibox" ON by default

### ISSUE THREAD

**Issue by Sangeppato** [bromite/bromite#469]
### Bromite version

Version: 79.0.3945.123
Arch: arm64
Android version: 10
Device model: Xiaomi Mi A2

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is the bug a crash?

No

### Describe the bug

In #350 it was incorrectly stated that it's not possible to edit the URL anymore with the "Search Ready Omnibox" feature enabled and for this reason the feature was disabled (or at least, this is what I understood). I personally prefer the newer Search Ready function and it has been the default in Chromium, Chrome and Brave for some time now, I'd ask you to consider setting it back as default, mainly because it looks to me that the only complaint about it was based on wrong assumptions.
In case you prefer not to enable the function, I'd at least suggest to mention the flag in the README, under the "Flag" section.

### Steps to reproduce the bug
 Search Ready Omnibox is disabled by default

### Expected behavior

Search Ready Omnibox should be enabled by default

**Comment by csagan5** [comment]
@Sangeppato although it might seem that the default was changed only because of that issue, that is not the main reason. The biggest motivation to change it is to keep the functionality to edit/select directly without another tap.

How would you mention it in the README? There is plenty of other defaults changed which are not,  as the README explains that reading the changelog and patches is necessary to have the full picture.

**Comment by Sangeppato** [comment]
I understand then.

About the README: sorry, I wasn't clear, I mean that since the flag was retired from the upstream Chromium (or at least, I can't find it), it should probably be mentioned amongst the "Flags which have been retired from upstream Chromium but are still available in Bromite".

**Comment by csagan5** [comment]
Alright, I have mentioned it; thanks for spotting this. 

If many users miss the functionality we could add a FAQ for it, but it's not currently the case.

**Comment by Sangeppato** [comment]
Got it, thanks!

**Comment by csagan5** [comment]
@Sangeppato next time feel free to make a PR to the README!
