### ISSUE TITLE
Feature to exclude sites from ad-blocking 

### ISSUE THREAD

**Issue by cdysthe** [bromite/bromite#47]
There are sites that won't work with ad-blocking enabled. It would therefore be good with an option to exclude sites. I'm not talking about rules, just a simple option to exclude sites.

**Comment by csagan5** [comment]
Not simple to implement; sorry, I have no plans to add such feature. It would require to create additional UI for it.

**Comment by cdysthe** [comment]
Understood. But couldn't it be part of the site options at the far left of the URL bar? Just askin' :)
