### ISSUE TITLE
Jumps and freezes during the scroll.

### ISSUE THREAD

**Issue by Adrymate9** [bromite/bromite#475]
### Bromite version

Version: `79.0.3945.139`
Arch: arm64
Android version: 10.0
Device model: MI9TPRO ( K20 PRO)

### Is this bug about the SystemWebView?
No

No support for SystemWebView installations is provided.

### Is the bug reproducible with latest version?
Yes
Do not report bugs which are not reproducible with latest version

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug
When you open any web page and try to move on it, there are slowdowns, brakes during scrolling, and small freezes that make the browsing experience very complicated.  lack of fluency during navigation.

### Steps to reproduce the bug

1. Go to www.rosario3.com or https://m.lacapital.com.ar
2. Scroll down to notice the cuts and continuous jumps of the page
3. You will notice cuts and slowdowns during scrolling on the website

### Expected behavior

Smooth and uncut scrolling during web page scrolling. clear and concise description of what you expected to happen.

**Comment by csagan5** [comment]
@Adrymate9 please disable the ad blocker for the sites you mentioned, repeat the test and report back.

**Comment by Adrymate9** [comment]
Unfortunately it continues to fail.  I followed if suggestion, I disabled the bromite ad blocker.  and web pages continue to throw the same problem when scrolling over them.

**Comment by csagan5** [comment]
@Adrymate9 then the same issue must be reproducible with Chromium

**Comment by csagan5** [comment]
If you want to troubleshoot this issue further please see https://developer.android.com/studio/profile/android-profiler

This profiling must be done with the device that exhibits the behaviour, first with Chromium then with Bromite.
