### ISSUE TITLE
Chromium WebView package does not exist

### ISSUE THREAD

**Issue by ioogithub** [bromite/bromite#477]
### Bromite version

Version: `Bromite v79.0.3945.139`
Arch: `arm64`
Android version: `9.0` LineageOS 16.0 nightly, rooted
Device model: (example: `river`)

### Is this bug about the SystemWebView?
Yes

### Is the bug reproducible with latest version?
Yes

### Is the bug a crash?
Yes

### Describe the bug
After Webview is installed, apps calling it crash with logcat "Chromium WebView package doss not exist".

In Settings-> WebView Implementation there are no entries (empty)

### Steps to reproduce the bug
1. Verifying allowed webview packages
Yes, "com.android.webview" exists without a corresponding E: signature block

2. Installation with root file manager or TWRP
Yes, all steps followed using TWRP no errors.

3. Install the Bromite SystemWebview apk file as you would for any other app
Yes, app installs successfully, can be updated from F-Droid

4. The apps that need the webview will crash if you do not install the Bromite SystemWebView apk after rebooting. Once the installation is complete it will be possible to update the SystemWebView without root.
Even after installation, apps still crash.

### Expected behavior
Installation instructions were followed precisely, no errors but at the end there is no WebView implementation. I can restore the default but as soon as Bromite is installed it doesn't show up under WebView implementations.

**Comment by csagan5** [comment]
As explained when submitting the issue, there is no support here for the SystemWebView. You can try on Reddit or XDA; there is no difference between Bromite's one and any other.
