### ISSUE TITLE
Proxy profiles

### ISSUE THREAD

**Issue by cs-nero** [bromite/bromite#479]
### Is your feature request related to privacy?
Yes.

### Is there a patch available for this feature somewhere?

I do not know.

### Describe the solution you would like

Add profiles (for example a dropdown menu) in proxy configuration for having the opportunity to switch between different proxy settings quickly.

### Describe alternatives you have considered

----

**Comment by csagan5** [comment]
@cs-nero this feature would require some UI work, I can accept patches but I would be unable to develop it.
