### ISSUE TITLE
Can't install ARM64 Bromite Lollipop build on Amazon Fire HD 10 (2017).

### ISSUE THREAD

**Issue by vaguerant** [bromite/bromite#48]
The Amazon Fire HD 10 is a Fire OS 5.6 tablet, meaning it's roughly an Android Lollipop tablet. It is a 64-bit device. Compatibility with normal Android Lollipop apps is usually very good.

Downloading the current ARM64 Lollipop (SDK21) build, as recommended for this device by bromite.org, and attempting to install it results in a standard "App not installed" error.

The standard ARM build does install without complaint.

I'm not rooted or anything but if there's anything I can run without root to get necessary diagnostic information (i.e. something more helpful than "App not installed"), feel free to suggest it.

**EDIT:** Ran a benchmarking app which reports that the Fire HD 10 runs on Android 5.1.1 (32-bit). I assume this is the issue--the processor is 64-bit, but with 32-bit Android I imagine 64-bit apps can't be installed?

**EDIT2:** This XDA-Developers thread about the Fire HD 8 seems to suggest something a bit different:
https://forum.xda-developers.com/hd8-hd10/help/amazon-compile-32-bit-instead-64-bit-t3754149

> It's actually a weirdly compiled 64 bit version, which has 32 bit as properties in build.prop (armv7 vs arm64, or something like that). [...] The whole thing is a bit of a mess.

> Strangely enough, this tablet 'can' run 64-bit native libraries.

**Comment by csagan5** [comment]
I suggest you try the Monochrome build? It might be just for this purpose. You can find it in the Releases.

**Comment by vaguerant** [comment]
Unfortunately, no luck here. Opening the ARM64 Monochrome build APK gives the following error:

> Parse Error
> There was a problem parsing the package.

**Comment by csagan5** [comment]
Ok, but this is not a problem of Bromite. The device you mentioned runs 32bit Android as you said, if you will run 64bit Android then you can install the 64bit versions.
