### ISSUE TITLE
Wrong file name when downloading the file

### ISSUE THREAD

**Issue by USB3-2-10Gbit** [bromite/bromite#481]
### Bromite version

Version: `79.0.3945.139`
Arch: `arm64`
Android version: (`9.0`)
Device model: (`Redmi Note 8`)

### Is the bug reproducible with latest version?

Yes

### Steps to reproduce the bug

1. Go to https://c.mi.com/thread-2831947-1-0.html and register in this forum.
2. Click on 'Mi Calculator.apk' to download.
3. See under Bromite "Downloads". You can see that the file name '74f1a883-d2b1-418e-9047-d56ef624febb.zip'. But this is wrong, 'Mi Calculator.apk is correct.

If I use a desktop browser on my Windows PC e.g Opera no problem.

**Comment by USB3-2-10Gbit** [comment]
Why is it closed?

Bromite creates a wrong name during download.

If I use a desktop browser on my PC, I do not get a zip file.

In this case Mi Calculator.apk

What's the problem?

**Comment by USB3-2-10Gbit** [comment]
Why is it closed?

Bromite creates a wrong file name during download.

What's the problem?

**Comment by csagan5** [comment]
@USB3-2-10Gbit you submitted the issue without testing with the corresponding Chromium version. You need to follow the instructions present in the issue template.

**Comment by USB3-2-10Gbit** [comment]
> @USB3-2-10Gbit you submitted the issue without testing with the corresponding Chromium version. You need to follow the instructions present in the issue template.

I have updated the report. I can confirm no problems with the same Chromium version on Android. Only in Bromite gives the problem.

**Comment by csagan5** [comment]
@USB3-2-10Gbit you need to use the same version as in https://www.bromite.org/chromium

The problem you reported is not reproducible.

**Comment by USB3-2-10Gbit** [comment]
> @USB3-2-10Gbit you need to use the same version as in https://www.bromite.org/chromium
> 
> The problem you reported is not reproducible.

I used the same chromium version as you said.
Here screenshots. Bromite has this problem. It always downloads as zip file and not as apk file

Bromite 80.0.3987.78
![Screenshot_2020-02-09-14-09-04-863_org bromite bromite_1](https://user-images.githubusercontent.com/60332877/74102787-298ba400-4b47-11ea-8005-ca094175a1f1.jpg)


Chromium 80.0.3987.78
![Screenshot_2020-02-09-14-](https://user-images.githubusercontent.com/60332877/74102797-3f996480-4b47-11ea-8326-fbc2b3acd985.jpg)
