### ISSUE TITLE
Freeze UA by upstream value

### ISSUE THREAD

**Issue by Madis0** [bromite/bromite#483]
### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

[Upstream](https://bugs.chromium.org/p/chromium/issues/detail?id=955620) already has the feature, it is just hardcoded to disable for now

### Describe the solution you would like

Bromite could enable the feature _kFreezeUserAgent_ under `third_party/blink/public/common/features.h` in order to replace/simplify the patch [User-Agent-anonymize.patch](https://github.com/bromite/bromite/blob/master/build/patches/User-Agent-anonymize.patch)

### Describe alternatives you have considered

Wait for M81, which brings a flag to toggle it; wait for M83 which partly [enables it upstream](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/-2JIRNMWJ7s/yHe4tQNLCgAJ) or wait for M85, which enables it fully upstream.

**Comment by csagan5** [comment]
Fixed in `80.0.3987.95`.

**Comment by Madis0** [comment]
Google [currently unfroze the major version](https://bugs.chromium.org/p/chromium/issues/detail?id=955620#c12) in Canary 84, [due to Client Hints postponing.](https://groups.google.com/a/chromium.org/d/msg/blink-dev/A4wxFpvqUfA/yBjL6B0QDgAJ)

**Comment by csagan5** [comment]
Bromite will follow upstream on this, that means the major version will be disclosed in the User-Agent as well.
