### ISSUE TITLE
Cannot download files (SD card not found)

### ISSUE THREAD

**Issue by alissonlauffer** [bromite/bromite#485]
### Bromite version

Version: `80.0.3987.78`
Arch: `arm64`
Android version: `10.0`
Device model: `Moto G5S Plus`

### Is the bug reproducible with latest version?

Yes.

### Can the bug be reproduced with corresponding Chromium version?

No.

### Is the bug a crash?

No.

### Describe the bug

When I try to download something, It shows me a "SD card not found" error message.

### Steps to reproduce the bug

1. Try to download any file
2. See error

### Expected behavior

The file is downloaded.

### Screenshot
![Screenshot_20200207-132955_Bromite](https://user-images.githubusercontent.com/29029632/74047332-ebf41300-49ae-11ea-8012-bb580042aaed.png)

**Comment by norbertc** [comment]
same issue encountered on my pixel 4 xl. using the arm64 build.

**Comment by csagan5** [comment]
Do these devices have an external microSD card?

**Comment by BlueMax** [comment]
When clicking 'Download' the popup re-opens immediately. You can hammer it. Nothing in logcat.

LOS17.1

**Comment by alissonlauffer** [comment]
> Do these devices have an external microSD card?
> 
> And also: what happens when clicking `Download`?

Currently I'm using just the internal storage of my smartphone (which is an eMMC storage). The behavior is the same as @BlueMax said.

**Comment by alissonlauffer** [comment]
currently appears that the problem is only occurring on Android 10.

**Comment by norbertc** [comment]
logcat when trying to press download repeatedly:

`
02-10 01:07:32.388  1302  1498 E InputDispatcher: Window handle Window{cc9b457 u0 org.bromite.bromite/com.google.android.apps.chrome.Main} has no registered input channel
02-10 01:07:33.966 22906 26083 D OpenGLRenderer: endAllActiveAnimators on 0x736f369800 (InsetDrawable) with handle 0x737219d140
02-10 01:07:33.970  1302  2007 E InputDispatcher: Window handle Window{fd0b29d u0 org.bromite.bromite/com.google.android.apps.chrome.Main} has no registered input channel
02-10 01:07:33.981  1302  1498 E InputDispatcher: Window handle Window{fd0b29d u0 org.bromite.bromite/com.google.android.apps.chrome.Main} has no registered input channel
02-10 01:07:34.411 22906 26083 D OpenGLRenderer: endAllActiveAnimators on 0x736f441300 (InsetDrawable) with handle 0x73a31a09e0
02-10 01:07:34.416  1302  1498 E InputDispatcher: Window handle Window{f931e10 u0 org.bromite.bromite/com.google.android.apps.chrome.Main} has no registered input channel
02-10 01:07:34.837 22906 26083 D OpenGLRenderer: endAllActiveAnimators on 0x736f51fa00 (InsetDrawable) with handle 0x73721518e0
02-10 01:07:34.841  1302  2007 E InputDispatcher: Window handle Window{cca1a79 u0 org.bromite.bromite/com.google.android.apps.chrome.Main} has no registered input channel
02-10 01:07:34.851  1302  2007 E InputDispatcher: Window handle Window{cca1a79 u0 org.bromite.bromite/com.google.android.apps.chrome.Main} has no registered input channel
02-10 01:07:35.244 22906 26083 D OpenGLRenderer: endAllActiveAnimators on 0x736f5d7100 (InsetDrawable) with handle 0x737219d700
02-10 01:07:35.253  1302  1498 E InputDispatcher: Window handle Window{ad5eb0f u0 org.bromite.bromite/com.google.android.apps.chrome.Main} has no registered input channel`

**Comment by norbertc** [comment]
logcat when trying to press download repeatedly:

02-10 01:07:32.388  1302  1498 E InputDispatcher: Window handle Window{cc9b457 u0 org.bromite.bromite/com.google.android.apps.chrome.Main} has no registered input channel
02-10 01:07:33.966 22906 26083 D OpenGLRenderer: endAllActiveAnimators on 0x736f369800 (InsetDrawable) with handle 0x737219d140
02-10 01:07:33.970  1302  2007 E InputDispatcher: Window handle Window{fd0b29d u0 org.bromite.bromite/com.google.android.apps.chrome.Main} has no registered input channel
02-10 01:07:33.981  1302  1498 E InputDispatcher: Window handle Window{fd0b29d u0 org.bromite.bromite/com.google.android.apps.chrome.Main} has no registered input channel
02-10 01:07:34.411 22906 26083 D OpenGLRenderer: endAllActiveAnimators on 0x736f441300 (InsetDrawable) with handle 0x73a31a09e0
02-10 01:07:34.416  1302  1498 E InputDispatcher: Window handle Window{f931e10 u0 org.bromite.bromite/com.google.android.apps.chrome.Main} has no registered input channel
02-10 01:07:34.837 22906 26083 D OpenGLRenderer: endAllActiveAnimators on 0x736f51fa00 (InsetDrawable) with handle 0x73721518e0
02-10 01:07:34.841  1302  2007 E InputDispatcher: Window handle Window{cca1a79 u0 org.bromite.bromite/com.google.android.apps.chrome.Main} has no registered input channel
02-10 01:07:34.851  1302  2007 E InputDispatcher: Window handle Window{cca1a79 u0 org.bromite.bromite/com.google.android.apps.chrome.Main} has no registered input channel
02-10 01:07:35.244 22906 26083 D OpenGLRenderer: endAllActiveAnimators on 0x736f5d7100 (InsetDrawable) with handle 0x737219d700
02-10 01:07:35.253  1302  1498 E InputDispatcher: Window handle Window{ad5eb0f u0 org.bromite.bromite/com.google.android.apps.chrome.Main} has no registered input channel

**Comment by MatthewKelly** [comment]
I've rolled back to the last version of 79.  Version 80 has a number of new bugs.

**Comment by csagan5** [comment]
@BlueMax @alissonlauffer but does the device have a microSD inserted?

> I've rolled back to the last version of 79. Version 80 has a number of new bugs.

That will expose you to security vulnerabilities.

**Comment by alissonlauffer** [comment]
> @BlueMax @alissonlauffer but does the device have a microSD inserted?

No. It's weird because on Chromium build it works fine.

**Comment by csagan5** [comment]
@alissonlauffer Chromium comes with different defaults; please go to Settings -> Download and disable the prompt for download and see if the problem persists.

On Android 10 the security model is different and that might be part of the issue and the reason why Chromium had made changes to the download functionality.

**Comment by csagan5** [comment]
@alissonlauffer on the Chromium build with the prompt enabled it will show the same error, there is already an error reported upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=1045642

**Comment by gonrhcp** [comment]
Having the same issue with a OnePlus 7 and Android 10, on latest bromite version

**Comment by csagan5** [comment]
@gonrhcp 
> go to Settings -> Download and disable the prompt for download and see if the problem persists.

**Comment by tiagossa1** [comment]
Mi 9T/K20 with Android 10, same problem and I don't even have SD card. @csagan5 's temp fix is working though.

**Comment by csagan5** [comment]
@tiagossa1 thanks for reporting; that is not a temp fix though: the feature is broken in Chromium, see https://bugs.chromium.org/p/chromium/issues/detail?id=1045642

So until they fix that bug (if they will) there is nothing else we can do here; I will keep the default as per Chromium so that the prompt is avoided.

**Comment by norbertc** [comment]
@csagan5 unfortunately, the prompt is returning automatically. I disabled the "ask to where to save file” in settings but it still prompts when I tried to download some files in apkmirror. upon checking the settings again, it is enabled automatically.

**Comment by azakosath** [comment]
For me the workaround is not working. But what I noticed is that as soon as the prompt pops up, the download starts and continues unless you press cancel. You can find it at 
`/data/data/org.bromite.bromite/cache`
as a temp file, just copy it to download folder and rename it.

**Comment by csagan5** [comment]
@norbertc @azakosath please ask upstream on the Chromium issue tracker about a solution/workaround for this issue; it has nothing to do with Bromite patches.

**Comment by norbertc** [comment]
@csagan5 upstream marked it as closed(wontfix) but the following [commit](https://chromium.googlesource.com/chromium/src.git/+/840354fa26f3db0cd56b6c9accc4e3eab2a1c81d) relates to this bug.

**Comment by csagan5** [comment]
@norbertc it is marked as `wontfix` but a [commit](https://github.com/chromium/chromium/commit/840354fa26f3db0cd56b6c9accc4e3eab2a1c81d) has been done for it that looks like a fix? Odd. In this case we will get it in Bromite on next release.

**Comment by csagan5** [comment]
I have included the upstream fix in latest version `80.0.3987.118`, can someone please check if it addresses the issue?

**Comment by norbertc** [comment]
@csagan5 unfortunately, issue still persist on my pixel 4 xl.

**Comment by csagan5** [comment]
Yes, now I realise that the `DCHECK` removal is pointless for this bug because no `DCHECK`s run on non-debug builds.

A solution should come from upstream, if you can reproduce it with Chromium then you should report it there.

**Comment by alissonlauffer** [comment]
Funny fact: Google Chrome is force-disabling the "Ask where to save files" option. Even if enabled, no pop-up is shown.

**Comment by csagan5** [comment]
Related issue downstream (Vanadium): https://github.com/GrapheneOS/Vanadium/issues/56

@alissonlauffer upstream started affecting the functionality ~8 months ago, see the discussion in https://github.com/GrapheneOS/Vanadium/issues/17

From my understanding this is due to the more strict security settings of Android 10.

**Comment by norbertc** [comment]
one workaround that worked for me is to allow bromite to install unknown apps. e.g. app info on bromite -> enable install unknown apps. it results in download error message in the notification but the file was really downloaded.

**Comment by adrkable** [comment]
> one workaround that worked for me is to allow bromite to install unknown apps. e.g. app info on bromite -> enable install unknown apps. it results in download error message in the notification but the file was really downloaded.

This worked for me

**Comment by apptester235** [comment]
> one workaround that worked for me is to allow bromite to install unknown apps. e.g. app info on bromite -> enable install unknown apps. it results in download error message in the notification but the file was really downloaded.

Fixed the issue but would like to see a proper fix be implemented

**Comment by csagan5** [comment]
@norbertc @apptester235 you can report your findings upstream on the [Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1045642), it might help finding a solution. I do not know if it is already fixed in v81.

**Comment by csagan5** [comment]
It is not yet fixed in v81, however Chromium developers are discussing a fix here: https://chromium-review.googlesource.com/c/chromium/src/+/2057806

There are some security concerns mentioned there but there is hope to have this fixed in next release of Bromite.

**Comment by csagan5** [comment]
The fix has been [committed](https://github.com/chromium/chromium/commit/680e32224e520327e455db3be93db13f73c0172d), however it is available for v82. I will backport it for Bromite v81.

**Comment by csagan5** [comment]
Please confirm that this issue is solved in latest `81.0.4044.63`

**Comment by norbertc** [comment]
@csagan5 it's now working properly. thanks!
