### ISSUE TITLE
To Remove AMP and load the site normally

### ISSUE THREAD

**Issue by mehta1190** [bromite/bromite#488]
### Bromite version

Version: 80.0.3987.78
Arch: arm
Android version: 8.1

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

Not applicable. Disabling AMP links is a Bromite-specific feature.

### Is the bug a crash?

No

### Describe the bug

Some pages still show in the AMP form.

### Steps to reproduce the bug

1. Search for "india news" in omnibox.
2. In the **top stories** section, skip the first few links (the first 4). The rest of them open in AMP form.

### Expected behavior

The links should open without AMP. A similar privacy patch may be looked upon which is working fine in a separate browser (Kiwi), with GPL-3.0. Not sure if its the latest one.
Corresponding link - https://github.com/kiwibrowser/privacy_patches/blob/master/Add-possibility-to-remove-AMP-from-search.patch

**Comment by csagan5** [comment]
> Not sure if its the latest one.

It is not and the functionality there is bogus; Bromite version is much more advanced.

**Comment by csagan5** [comment]
Fixed in `80.0.3987.95`.
