### ISSUE TITLE
Webview Issue

### ISSUE THREAD

**Issue by iamrohanbro** [bromite/bromite#49]
Hi dev, I'm an arm64 8.0 user, so I'm using the latest monochrome public build which has integrated webview.
The issue is that if I disable the android system webview, this webview isn't working whenever required. On the other had if I install the normal Google chrome it handles all webviews even if system webview is disabled. 
Thank you.

**Comment by csagan5** [comment]
I believe you must install also Bromite's SystemWebView, as noted here: https://github.com/bromite/bromite/wiki/Installing-SystemWebView

**Comment by iamrohanbro** [comment]
@csagan5, I already had performed what's written in the wiki. My stock ROM zui 3.5 allows disabling/freezing android system webview, I disabled it buy still bromite webview wasn't able to intercept the requests properly and few apps were crashing which was fixed after I enabled the stock webview app. I hope you will fix this is future, in the meantime if I move to custom ROMs I'll provide you a logcat.
Thank you.

**Comment by csagan5** [comment]
@iamrohanbro you said you installed Monochrome and wanted to use the Webview inside Monochrome:
> Hi dev, I'm an arm64 8.0 user, so I'm using the latest monochrome public build which has integrated webview.
The issue is that if I disable the android system webview, this webview isn't working whenever required. 

Bromite's SystemWebView needs to be installed.

**Comment by kbitr** [comment]
Hey, can you explain this any further?

As I read https://chromium.googlesource.com/chromium/src/+/lkcr/docs/android_build_instructions.md#Multiple-Chrome-APK-Targets I thought Monochrome already included Webview. Why is Bromite's SystemWebView still necessary? 

Installing it also as a user app and under development options there is still only Chrome.

**Comment by iamrohanbro** [comment]
Yeah that's what I wanted to say. Its supposed to contain webview and that's supposed to work when required.

**Comment by csagan5** [comment]
Monochrome does not install the SystemWebView. Monochrome contains it (embedded), in its 32bit version so that when it matches the one running on the system they will share some memory and thus reduce the memory footprint. It is a trick for memory optimisation, and I have no idea about what other usages the Monochrome version might have, but for sure it is not to replace Android's SystemWebView.

**Comment by AndhikaWB** [comment]
It's an issue with the ROM itself. Android will be looking for `com.android.webview` or `com.android.chrome`, not `org.chromium.chrome` (or other package name). It is almost impossible to change it on release build (of the ROM), maybe enabling developer options or using Xposed?

Reference: https://groups.google.com/a/chromium.org/forum/m/#!topic/android-webview-dev/apA8HXJpGr0

**Comment by csagan5** [comment]
@AndhikaWB it's not the package name. The package must also be signed with specific allowed keys declared in the ROM, so changing the name alone does not help for officially released ROMs. Custom ROMs might include the package name and the whitelist the key (or disable the key verification).

**Comment by AndhikaWB** [comment]
Sorry then, on KitKat device, I use this [module](http://repo.xposed.info/module/net.typeblog.webview) so I thought it will be working on Nougat/Oreo too.

**Comment by csagan5** [comment]
@AndhikaWB with root, yes.

**Comment by csagan5** [comment]
I have updated my comments to mention that Monochrome indeed offers a webview, see https://github.com/bromite/bromite/wiki/Installing-SystemWebView#use-via-monochrome
