### ISSUE TITLE
How to individually add startpage

### ISSUE THREAD

**Issue by mitchrob1234** [bromite/bromite#492]
Hello,

I am an avid user of Bromite and recommend it to everyone I know.

I also use StartPage as my search engine.  I have seen that you removed StartPage from your default list of search engines, and that you have your reasons.  

My request/question is: How can I add startpage to my instance of bromite.

**Comment by subhinay** [comment]
Settings > Homepage
Use for new tabs - [x]
Open this page:
`chrome://newtab`

**Comment by Madis0** [comment]
https://github.com/bromite/bromite/wiki/SearchEngines or https://support.startpage.com/index.php?/Knowledgebase/Article/View/1102/0/how-do-i-add-the-startpage-home-screen-icon-to-my-iphone-or-android-device

**Comment by bocekm** [comment]
You can add Startpage as a default search engine this way: https://github.com/bromite/bromite/discussions/1372#discussioncomment-1318031
