### ISSUE TITLE
Add a new Variation to Chrome_Duet

### ISSUE THREAD

**Issue by basimaslamts** [bromite/bromite#496]
### Is your feature request related to privacy?
Nop

Features that are not related to privacy are unlikely to be considered.

### Is there a patch available for this feature somewhere?
Nop

If yes then provide URL and license information.

### Describe the solution you would like
The feature which "had" in Chrome duet (in #flags) to have "add new tab+tab switch+search" option need to come back. Please add it as a new variation to Bromite's Chrome duets.

Do not ask "I would like feature X which is available in browser Y"; such issues are closed immediately.

### Describe alternatives you have considered
Alternative considered are shown in the images
![Screenshot_2020-02-19-08-43-57-850_org bromite bromite](https://user-images.githubusercontent.com/57472154/74799004-600ab100-52f5-11ea-9a66-faa594ff2c78.jpg)

A clear and concise description of any alternative solutions or features you have considered.

**Comment by csagan5** [comment]
You need to ask this to Chromium developers, not here.

**Comment by Poopooracoocoo** [comment]
@basimaslamts submit an issue here: https://bugs.chromium.org/p/chromium/issues/list 
and link it to us and we'll star it. I know Chrome 80 removed and changed some stuff like the context menu which is now so annoying.

**Comment by basimaslamts** [comment]
Thanks.. the link is provided. They added the feature request to untriaged
for the team

https://bugs.chromium.org/p/chromium/issues/detail?id=1053933#c1
