### ISSUE TITLE
Video Playback Not Working/Flicker ARM64 Android 9

### ISSUE THREAD

**Issue by helloiamaman** [bromite/bromite#497]
### Bromite version

Version: `80.0.3987.109`
Arch:`arm64`
Android version: `9.0`
Device model: A5010 OnePlus 5t 8gb ram

### Is this bug about the SystemWebView?
No

No support for SystemWebView installations is provided.

### Is the bug reproducible with latest version?
Yes, only started with this version; previous plays videos with no issue.

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug
Trying to play videos on Reddit, Vimeo etc does not work and results in a still image or blank space where the video should be playing with the entire browser flickering.  

### Steps to reproduce the bug

1. Go to 'reddit or vimeo'
2. Click play on 'any video'

### Expected behaviour
Video plays with no flickering.

### Actual behaviour
Video will not play & full browser flickering.

**Comment by Abrakian** [comment]
Same here
Android Pie w/  ARM64 Version

**Comment by kef71** [comment]
Same here. Browser crashes when trying to play a video.
LineageOS 16 ARM64

**Comment by kef71** [comment]
In fact, the browser crashes on any website with embedded videos.

**Comment by csagan5** [comment]
@helloiamaman please fetch the log with adb logcat; you need to test with the corresponding Chromium version

@Abrakian @kef71 please test with the matching Chromium version aa well

**Comment by csagan5** [comment]
Fixed in `80.0.3987.118`.

**Comment by csagan5** [comment]
Related: #445

**Comment by helloiamaman** [comment]
Bug has returned in 89.0.4389.100

**Comment by csagan5** [comment]
@helloiamaman please do not create an issue and then comment on all the other closed issues; make #1022 complete and we can discuss it there.

**Comment by helloiamaman** [comment]
> @helloiamaman please do not create an issue and then comment on all the other closed issues; make #1022 complete and we can discuss it there.

The comments were posted prior to issue. I was checking to make sure I didn't duplicate an open issue. Saw you had mentioned the flag would be set by default and to test. I wasn't sure if posting in closed issues was worthwhile so opened an issue once I saw all relevant issues were closed. I'm not that familiar with GitHub etiquette, please forgive my ignorance. I'm future I will do one or the other & as for making the other issue template complete; I did my best on mobile. I work in healthcare and haven't been near my PC in months. Hopefully someone can help more.
