### ISSUE TITLE
Can't install PWA app

### ISSUE THREAD

**Issue by Offerel** [bromite/bromite#498]
### Bromite version

Version: `v80.0.3987.109`
Arch: `arm64`
Android version: (example: `10.0`)

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

yes

### Describe the bug

Im want to use Bromite as target for a PWA app or better as some sort of test environment. It seems that it is not possible to "install" a PWA. However i can add the PWA as Shortcut in Android Launchers Startpage. However, if i use the Standard Chrome Browser the same PWA is installed as app and i can use the app after that as Share Target.

### Steps to reproduce the bug

1. Start Bromite
2. Load the PWA in the adressbar (for testing purpose, its only a local adress in LAN)
3. Open menu
4. Tap to add shortcut to desktop/launcher
5. Shortcut is added to launcher, but its only a shortcut and no installation
6. Cant use the Shortcut as Share target

### Expected behavior

The PWA is installed and can be used as share target, like with Chrome from Play Store.

**Comment by csagan5** [comment]
PWAs need support for WebAPKs, see https://developers.google.com/web/fundamentals/integration/webapks

My best guess is that this is disabled because Bromite is not built with the Google Play binary blobs; have you checked the logs with `adb logcat`?

**Comment by Offerel** [comment]
I cant use adb at my device, since USB seems to be broken on that device. But if if your explanation is correct, this would mean, that PWA's (at least installation) cant be supported by Bromite. Is that right?

**Comment by csagan5** [comment]
By looking at the code it should work; the logs might tell what is the problem.

**Comment by Offerel** [comment]
Do you know another way to get the protocols than via the adb? As I said before, my USB port doesn't seem to work. I did a hard reset today and hoped that this fixed the USB port, but nothing has changed.

**Comment by csagan5** [comment]
I guess you charge it wirelessly?

Try this approach:
1. connect phone and laptop/PC on same network (wireless)
2. install a terminal app on the phone
3. run `adb tcpip 5555` from such terminal (you can use any port)
4. from your laptop/PC run `adb connect 192.168.x.x:5555` (use the correct IP and port)

Then you will be able to run `adb logcat` from your laptop/PC.

**Comment by Offerel** [comment]
Yes im charging since many years and never looked back :-)

BTW OT Question: Currently im on work and can't add the device to the same WiFi network to test it out, but can I use after connecting other adb command to? To remove bloatware, start backups, change captcha portal and so on?

**Comment by csagan5** [comment]
> If i use `adb tcpip 5555` in termux, i get `adb: inaccessible or not found`.

I was mistaken; there is no way to do this without USB or root.

**Comment by csagan5** [comment]
The reason why it does not work it's because it is necessary to contact some Google server to get back the WebAPK; in adb logs you can see:

```
03-07 08:37:15.897 13632 13702 E chromium: [ERROR:url_request.cc(586)] Block URL in URLRequest: https://webapk.9oo91eapis.qjz9zk/v1/webApks/?alt=proto&key=[some key]
03-07 08:37:15.897 13632 13702 E chromium: [ERROR:trk_protocol_handler.cc(17)] Blocked URL in TrkProtocolHandler: trk://https//webapk.9oo91eapis.qjz9zk/v1/webApks/?alt=proto&key=[some key]
03-07 08:37:15.898 13632 13632 W chromium: [WARNING:webapk_installer.cc(609)] WebAPK server returned response code -1.
```

In Bromite we block all requests to googleapis.com. I will add this information to the F.A.Q.
