### ISSUE TITLE
Bug in menu that appear when long press on a word or phrase to doing a search

### ISSUE THREAD

**Issue by sviluppoSoftware** [bromite/bromite#500]
Bromite version
Version: all
Arch: arm
Android version: 8.1 and 9 (probably earlier)

Is this bug about the SystemWebView?
No

Is the bug reproducible with latest version?
yes

Describe the bug
when I select a word or phrase and use the menu that appears to do a search it always shows Google as a search engine even if I have set another as default, however the search is performed through the engine selected in the settings.

Expected behavior
Show the search engine that i have set as default in settings

**Comment by csagan5** [comment]
You have skipped the Chromium test; that is not optional.
