### ISSUE TITLE
add support exstension

### ISSUE THREAD

**Issue by KonoromiHimaries** [bromite/bromite#501]
### Is your feature request related to privacy?

yes

### Is there a patch available for this feature somewhere?

https://github.com/NeverDecaf/chromium-web-store#readme

### Describe the solution you would like

https://github.com/yourduskquibbles/webannoyances#demonstration

### Describe alternatives you have considered

https://github.com/yourduskquibbles/webannoyances#mobile

**Comment by Madis0** [comment]
The first link is for a totally different thing - it is for browsers that support extensions but not Chrome Web Store specifically.

The other two links are irrelevant to the suggestion.
