### ISSUE TITLE
Error when enable DNS-over-HTTPS

### ISSUE THREAD

**Issue by tigerbit85** [bromite/bromite#507]
When  set and  enable "DNS-over-HTTPS" most time show error 
For example
"This site can’t be reachedThe webpage at https://github.com/bromite/bromite/releases might be temporarily down or it may have moved permanently to a new web address.
ERR_DNS_TIMED_OUT"

OR

"Your connection was interruptedA network change was detected.
ERR_NETWORK_CHANGED"

After refreshing the site loads
Please fix the bug.

**Comment by tigerbit85** [comment]
😕😕😕

**Comment by tigerbit85** [comment]
confusedconfusedconfused
I don't know what you mean by closing the post
But I'm using the latest version 80.0.3987.118 ARM Lollipop and above (SDK21)
My device Android 6 Samsung
I have the problem mentioned

**Comment by csagan5** [comment]
You need to submit the issue using GitHub desktop mode, a template will be displayed and you should follow that.

Before reporting issues you should search for similar issues already reported.

The error you are seeing is due to slow network or slow DoH server, there is no bug to fix in Bromite.
