### ISSUE TITLE
Custom brand for WebView on Android 8+

### ISSUE THREAD

**Issue by Madis0** [bromite/bromite#51]
From at least Android 8+ [(but maybe Android 5+ according to this) ](https://developer.chrome.com/multidevice/webview/overview), users can have and swap between multiple webviews on developer settings. Therefore, in theory, AOSP WebView, [Google WebView](https://play.google.com/store/apps/details?id=com.google.android.webview) and Bromite WebView could all co-exist. 

By testing, first two worked well, but Bromite's maybe needs something more to differ besides a package name change, as with that it installs but doesn't get selectable. 

Therefore I am suggesting, why not make at least one version use a completely custom branding - name, package name, icon, etc. That would make it easier and non-destructive for users of latest Android version.

**Comment by dimqua** [comment]
You can only swap between AOSP's WebView, Google's WebView and Chrome's WebView.

> completely custom branding - name, package name

You can't use it in this case.

**Comment by Madis0** [comment]
Oh right, versions of Chrome also used that. Then perhaps it is reasonable to spoof one of them, as they can be uninstalled at user's will without requiring root or other tweaks.

**Comment by csagan5** [comment]
As far as I know/remember, it is still like @dimqua said. I have no recent experience with this; I had played around with the System Webview (rooted/non-rooted scenarios), but some years before I started Bromite and I do not think such experience is still applicable.

I would have no problem using the proper branding, but if there is still such limitation enforced then we have to keep having the APK pose as another application.

It is unfortunate but it is probably an attempt at keeping the brand/product together, similarly to what Apple does in forbidding non-Safari Webkit engines on iOS.

@Madis0 from what I heard/read, you can modify the APK with some editor to have a different exposed package name and see what happens.

Closing as there is no action to be taken.
