### ISSUE TITLE
Screenshots are outdated

### ISSUE THREAD

**Issue by pitsi** [bromite/bromite#510]
### Bromite version

Version: 81.0.4044.63
Arch: arm64
Android version: 9.0
Device model: Nokia 5 TA-1024

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
Yes

### Is the bug a crash?
No

### Describe the bug
I was looking for a chromium based browser for my android phone and I decided to give bromite a shot. I checked its features and screenshots on bromite.org and downloaded it from there, selecting arm64 as the architecture and for "lollipop and above". I downloaded the apk and installed it as usual.
But when I launched it, I discovered that it looks nothing like the screenshots on the site. For instance, as you can see on the screenshot below, the options for "enable javascript" and "enable adblock" are completely missing! It just looks like the stock chrome/chromium browser. I did not dig further to check the other features after that.
On top of above, I got some popup ad window on some site, so I assume adblock was not working...

### Steps to reproduce the bug
1. Open any site, e.g. bromite's page on github on my screenshot
2. Click on the 3 dots on the top left corner
3. Notice the missing options I mentioned above

### Expected behavior
The forementioned options should appear

### Screenshots

![Screenshot_20200318-201710](https://user-images.githubusercontent.com/5880037/76995769-08de1780-6959-11ea-960c-52207473a9bd.png)

**Comment by csagan5** [comment]
> I did not dig further to check the other features after that.

You can read about them in the README.

The screenshots are obsolete and need to be replaced; the ad blocker and Javascript options are accessible individually for each site, or from the Site settings for all sites.

**Comment by pitsi** [comment]
Thank you for the info :)
I will look up the rest of the features now. Feel free to close the issue report.
