### ISSUE TITLE
bromite doesn't show bitwarden notification

### ISSUE THREAD

**Issue by sivuda** [bromite/bromite#511]
Version: 80.0.3987
Android 9
OnePlus 5t and Moto Z3 play

Bromite doesnt play nice with bitwarden. Never was able to get the notification over the username/password field. I always had a persistent notification on bronite to beat the issue.. But now with the new update of bitwarden where persistent notifcation is replaced with overlay permission, im no more able to log into anything on bromite. The overlay appears briefly when selecting a field but not long enough to be able to tap on it.

**Comment by abh153k** [comment]
Same problem
