### ISSUE TITLE
Icons not removed from notification bar after download in incognito mode

### ISSUE THREAD

**Issue by linux019** [bromite/bromite#512]
### Bromite version

Version: `81.0.4044.70`
Arch: `arm64`
Android version: `7.1`
Device model: HTC U11 EYES

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
True

### Can the bug be reproduced with corresponding Chromium version?
No

### Describe the bug

Write here a clear and concise description of the bug.

### Steps to reproduce the bug

1. Open a tab in incognito
2. Download any file from any site
3. Once download started the icon remains in notification bar even if try to force stop bromite
4. Only reboot of the phone can remove icons

![photo_2020-03-22_18-33-22](https://user-images.githubusercontent.com/15028965/77254828-1f8fb180-6c6c-11ea-8087-cb2380d5e378.jpg)

### Screenshots

If applicable, add screenshots to help explain your problem. Otherwise remove this section.

**Comment by csagan5** [comment]
Can anyone else reproduce this issue?

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> No

There are reports online that it can be reproduced with Chromium.
