### ISSUE TITLE
Hide Navigation Bar in Full-screen mode

### ISSUE THREAD

**Issue by 0450** [bromite/bromite#515]
### Is your feature request related to privacy?

Features that are not related to privacy are unlikely to be considered.

No.

### Is there a patch available for this feature somewhere?

No.

### Describe the solution you would like

Allow Navigation Bar to be hidden when viewing videos in Full-screen.

### Describe alternatives you have considered

- Toggle notification bar in settings
- Gestures to hide notification bar
- Remove notification bar completely

**Comment by csagan5** [comment]
Sorry, this is not related to privacy - you should ask upstream (Chromium) about the feature
