### ISSUE TITLE
Canvas - Yahoo Finance chart is black

### ISSUE THREAD

**Issue by stalkerandrew** [bromite/bromite#52]
how to reproduce:

1. open this link: https://finance.yahoo.com/quote/SGDIDR=X/?guccounter=1
2. if 1d is not available, try 5d
3. you will see the graph is black.

what you expect:
graph.

what came out:
black, nothing?

can it work on latest google chrome:
yes

**Comment by csagan5** [comment]
This is probably due to the canvas anti-fingerprinting measures we take in Bromite. I will think about a possible solution.

**Comment by csagan5** [comment]
Other examples possibly related:
* https://www.tradingview.com/chart/?symbol=BITFINEX:BTCUSD
* https://www.is.fi/

**Comment by csagan5** [comment]
Fixed in 67.0.3396.88
