### ISSUE TITLE
Remove tracking fields from URLs

### ISSUE THREAD

**Issue by ritcher** [bromite/bromite#521]
### Is your feature request related to privacy?

Yes.

### Is there a patch available for this feature somewhere?

Not that I'm aware of.

### Describe the solution you would like

Implement a feature that analyzes each link accessed by the user, in order to find tracking elements in the URL and remove them before making the request to the server

Example:

The user tries to access the following link in his browser: `http://www.example.org/index.html?utm_source=search_engine`.

At this point, Bromite analyzes the link and removes the `utm_source` parameter from the end of the URL (since this is a parameter related to [Google Analytics](https://en.wikipedia.org/wiki/UTM_parameters)).

Therefore, the final link accessed by the user would be: `http://www.example.org/index.html` and not `http://www.example.org/index.html?utm_source=search_engine`.

### Describe alternatives you have considered

For the syntax of the list of rules (which Bromite would use to detect and remove tracking parameters), I believe [this file](https://github.com/KevinRoebert/ClearUrls/blob/master/data/data.min.json) could be used as a basis ([see how it works](https://gitlab.com/KevinRoebert/ClearUrls/-/wikis/Technical-details/Rules-file)). It's licensed under the [LGPL-3.0](https://github.com/KevinRoebert/ClearUrls/blob/master/LICENSE) and is part of the [ClearURLs](https://github.com/KevinRoebert/ClearUrls) project.

**Comment by csagan5** [comment]
This would be a burden to maintain within the browser since there is no extensions support.
