### ISSUE TITLE
Bromite website: wrong Android version description

### ISSUE THREAD

**Issue by drygdryg** [bromite/bromite#522]
https://github.com/bromite/bromite.github.io
![Screenshot_2](https://user-images.githubusercontent.com/43933400/78703483-e5ccd500-7912-11ea-98af-2ad3c484480e.png)
SDK 19 is Android 4.4 (KitKat), not Jelly Bean.

**Comment by csagan5** [comment]
Fixed, thanks for your report!

**Comment by drygdryg** [comment]
Thanks for the feedback. But the word KitKat is written together. Source: https://www.android.com/versions/kit-kat-4-4/

**Comment by csagan5** [comment]
Fixed.
