### ISSUE TITLE
F-Droid repo does not sync

### ISSUE THREAD

**Issue by impreza233** [bromite/bromite#523]
### Bromite version

Version: 81.0.4044.97
Arch: arm64
Android version: 9.0
Device model: Redmi Note 5

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug

The repos available in  aren't working anymore on F-Droid. Searching for updates generates an error in this app, so I can't update Bromite automatically.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to F-Droid app and add the repos available in https://www.bromite.org/fdroid
2. Refresh in the updates tab on F-Droid
3. Wait for a moment

### Expected behavior

It should show the updates and not throwing an error. 

### Screenshots

![Screenshot_2020-04-13-12-02-33-375_org fdroid fdroid](https://user-images.githubusercontent.com/25793051/79112377-b852b200-7d7e-11ea-9849-1fc1de29f177.jpg)

**Comment by csagan5** [comment]
@impreza233 check your `adb logcat` for the F-Droid errors, I cannot reproduce this issue.

**Comment by impreza233** [comment]
Thanks for the info!!

That's my F-Droid logcat for more info: 

04-13 12:19:55.839 15053 15173 E UpdateService: Error updating repository https://fdroid.bromite.org/fdroid/repo
04-13 12:19:55.839 15053 15173 W System.err: org.fdroid.fdroid.IndexUpdater$UpdateException: Error getting F-Droid index file
04-13 12:19:55.839 15053 15173 W System.err:    at org.fdroid.fdroid.IndexV1Updater.update(IndexV1Updater.java:179)
04-13 12:19:55.839 15053 15173 W System.err:    at org.fdroid.fdroid.UpdateService.onHandleWork(UpdateService.java:477)
04-13 12:19:55.839 15053 15173 W System.err:    at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
04-13 12:19:55.839 15053 15173 W System.err:    at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
04-13 12:19:55.839 15053 15173 W System.err:    at android.os.AsyncTask$2.call(AsyncTask.java:333)
04-13 12:19:55.839 15053 15173 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-13 12:19:55.839 15053 15173 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-13 12:19:55.839 15053 15173 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-13 12:19:55.840 15053 15173 W System.err:    at java.lang.Thread.run(Thread.java:764)
04-13 12:19:55.842 15053 15173 W System.err: Caused by: java.io.IOException: No mirrors available
04-13 12:19:55.842 15053 15173 W System.err:    at org.fdroid.fdroid.FDroidApp.getNewMirrorOnError(FDroidApp.java:287)
04-13 12:19:55.842 15053 15173 W System.err:    at org.fdroid.fdroid.IndexV1Updater.update(IndexV1Updater.java:152)
04-13 12:19:55.842 15053 15173 W System.err:    ... 8 more

If you have some question, don't hesitate to say me that :)
