### ISSUE TITLE
GPS switching on randomly in Lineage OS 17.1, was fine in Lineage OS 16

### ISSUE THREAD

**Issue by gut5** [bromite/bromite#524]
### Bromite version

Version: 81.0.4044.97
Arch: arm
Android version: 10
Device model: Nexus 6 (shamu)

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?
Haven't attempted

### Is the bug a crash?
No

### Describe the bug

GPS switches itself on randomly when opening the Bromite app. Did not happen under previous Android/Lineage OS version.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Open app
2. Look at top bar

### Expected behavior

Expected no GPS to randomly switch itself on

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> Haven't attempted

@gut5 if it's reproducible with Chromium then it's a Chromium issue, as explained in the issue template:

> Please pick the same version of Chromium as Bromite from here: https://github.com/bromite/chromium/releases
> If the bug is reproducible then it might be a configuration issue or an upstream bug. Upstream bugs can be reported on the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) and do not forget to read [Chromium project bug reporting guidelines](https://www.chromium.org/for-testers/bug-reporting-guidelines) first.

**Comment by gut5** [comment]
Just tried doing that. It doesn't happen in Chromium. Can this be reopened? Also should I provide a logcat?

**Comment by csagan5** [comment]
> Can this be reopened?

Yes, it can.
