### ISSUE TITLE
GPS switching on randomly in Lineage OS 17.1, was fine in Lineage OS 16

### ISSUE THREAD

**Issue by gut5** [bromite/bromite#525]
### Bromite version

Version: 81.0.4044.97
Arch: arm
Android version: 10
Device model: Nexus 6 (shamu)

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug
GPS switches itself on randomly when opening the Bromite app. Did not happen under previous Android/Lineage OS version.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Open app
2. Look at top bar

### Expected behavior

Expected no GPS to randomly switch itself on

**Comment by csagan5** [comment]
@gut5 next step is to test the **same** Bromite version on Android 9.

Also, I do not exactly know how Bromite/Chromium can trigger the "GPS switch on" effect. Can you verify which tabs you have open? At the very least there must be a tab which has a site with granted permissions for location sharing.

**Comment by gut5** [comment]
Not to be rude but going back to an earlier version of Android/LineageOS is just not worth it over this bug.

**Comment by csagan5** [comment]
That's fine; since no one is going to make the tests I will close it.

**Comment by Iey4iej3** [comment]
How do you know that it is `bromite` using GPS? If you look at the system setting: `Settings` -> `Location` -> `App permission`, and choose `Show system` in the drop-down menu, you can see the last query of location for each app. And I cannot distinguish GPS and network location queries in Android Q (LOS 17.1).
