### ISSUE TITLE
Option to toggle Adblock engine globally

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#53]
An option to toggle the adblock engine globally; could use the existing "Allow ads" setting in Chromium.

**Comment by DragoCubed** [comment]
The adblocker is pretty good but some sites don't work properly with it. I would love for it to be customisable like Ublock Origin but we should be able to turn it off for some sites or globally first.

**Comment by csagan5** [comment]
Fixed in 67.0.3396.72
