### ISSUE TITLE
[Request] Could someone share a really good custom filter list?

### ISSUE THREAD

**Issue by pythonInRelay** [bromite/bromite#531]
I'm having trouble making my own and I don't want to pay for iblocklist's outdated lists.

Has anyone made one? Could you please share it, the default blocklist doesn't really catch anything and I'm getting so many ads still.

**Comment by csagan5** [comment]
There are no paid lists that work with Bromite (that I know of).

> the default blocklist doesn't really catch anything and I'm getting so many ads still.

How is that possible? Have you tried finding out the cause?

**Comment by pythonInRelay** [comment]
The cause is that the blocklist just doesn't block very many ads. Your policy is that you allow what you consider 'good' ads. I don't differentiate. All ads are bad. I still see ads littered everywhere on e.g. Reddit.com, Yahoo News, MSNBC et cetera.

If you allowed users to install Addons themselves like e.g. [Kiwi](https://github.com/kiwibrowser/src) does. I could just use uBlock Origin or something, but you only provide a blocklist method like the old p2p edonkey days...

**Comment by ritcher** [comment]
How about [EnergizedProtection/block](https://github.com/EnergizedProtection/block)? They provide blacklists compatible with the Bromite filter mechanism. Also see [EnergizedProtection/block#329](https://github.com/EnergizedProtection/block/issues/329).

**Comment by csagan5** [comment]
> Your policy is that you allow what you consider 'good' ads.

There is no such thing, it's a made up statement. The lists used are mentioned in the README, there is no special distinction for ads.

> If you allowed users to install Addons themselves

You can submit and support the extensions patch for the coming years, it's open source.

> hey provide blacklists compatible with the Bromite filter mechanism.

I was not aware of that.

**Comment by csagan5** [comment]
> if anyone pays for the iblocklist suite, which is basically the only real blocklist that is actually updated in .dat format.

That is not the same format as the filters used in Bromite.

**Comment by csagan5** [comment]
> I still see ads littered everywhere on e.g. Reddit.com, Yahoo News, MSNBC et cetera.

Perhaps you should check whether you have ads disabled or the filters failed downloading.

**Comment by pythonInRelay** [comment]
> 
> 
> > I still see ads littered everywhere on e.g. Reddit.com, Yahoo News, MSNBC et cetera.
> 
> Perhaps you should check whether you have ads disabled or the filters failed downloading.

Ads definitely aren't 'enabled'. Could you tell me how to check if the filters failed to download? Seems very unlikely. Some ads are blocked for sure, but I still see so many that they might as well all just be allowed.

> 
> 
> How about [EnergizedProtection/block](https://github.com/EnergizedProtection/block)? They provide blacklists compatible with the Bromite filter mechanism. Also see [EnergizedProtection/block#329](https://github.com/EnergizedProtection/block/issues/329).

If the above doesn't work I'll try this too. Thank you!



> 
> 
> > if anyone pays for the iblocklist suite, which is basically the only real blocklist that is actually updated in .dat format.
> 
> That is not the same format as the filters used in Bromite.

Are you certain? You can get the lists in .dat format but only if you pay.

> You can submit and support the extensions patch for the coming years, it's open source.

This is good to know, but why don't you guys do this yourselves? This is just an innocent question btw. If the ability is there to do it on a user-by-user basis that's nice but I can't imagine why you wouldn't allow the people who wanted to, to just install extensions by default. I think that most people are going to want to install one or two extensions only. If I could install uBlock Origin on top of Bromite, I wouldn't need anything else and it'd be my daily driver.

Thanks for all of your replies and assistance btw.

**Comment by csagan5** [comment]
> Ads definitely aren't 'enabled'. Could you tell me how to check if the filters failed to download? Seems very unlikely. Some ads are blocked for sure, but I still see so many that they might as well all just be allowed.

Check the logs with `adb logcat`, you can filter for lines which contain `AdBlockUpdaterService`.

See also: https://www.bromite.org/custom-filters

> Are you certain? You can get the lists in .dat format but only if you pay.

There is no `.dat` format, it is a generic file extension. This is how the subresource filter is generated: https://github.com/chromium/chromium/blob/master/components/subresource_filter/FILTER_LIST_GENERATION.md

> This is good to know, but why don't you guys do this yourselves?

See https://github.com/bromite/bromite/blob/master/FAQ.md#does-bromite-support-extensions
