### ISSUE TITLE
Any Way To Disable Hyperlink Ping Tracking?

### ISSUE THREAD

**Issue by uazo** [bromite/bromite#534]
### Is your feature request related to privacy?

Yes.

### Is there a patch available for this feature somewhere?

I don't know.

### Describe the solution you would like

Please refer to https://chromium.googlesource.com/chromium/src/+/80a809a3566fe87ecbf2d7255ff7af4a7ee2fcb8

### Describe alternatives you have considered

Check if it is possible to make a patch to disable ping tracking.

**Comment by uazo** [comment]
here https://chromium.googlesource.com/chromium/blink/+/master/Source/core/loader/PingLoader.cpp  I found the source code

**Comment by csagan5** [comment]
It is already disabled, see https://github.com/bromite/bromite/blob/81.0.4044.106/build/patches/Modify-default-preferences.patch
