### ISSUE TITLE
Adblock domains resolved

### ISSUE THREAD

**Issue by gkrishnaks** [bromite/bromite#536]
### Bromite version

Version: `81.0.4044.106`
Arch:  `arm64` 
Android version: 10
Device model: (example: `SM-G960UZKABST`)

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
It is related to bromite's adblock. I am using default filter list that came with bromite. 

### Describe the bug
Ad resources from domains like ad.doubleclick.net and google-analytics .com and other ad domains are still resolved by Bromite. I observed by monitoring the DNS-Over-Https logs tagged to my Bromite. I expect that the domain names shouldn't even be resolved if adblock is working and adblock should just simply return nxdomain or whichever method is preferred to return ad domains. 
Also, is there a way to test that the bromite adblock is actually working? 

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Look at DNS over Https logs generated by browsing in bromite. 

### Expected behavior

Ad domains from filter list shouldn't even be resolved via DNS.

**Comment by csagan5** [comment]
> Ad resources from domains like ad.doubleclick.net and google-analytics .com and other ad domains are still resolved by Bromite.

The filter does not block everything under a certain domain but most times only specific URLs. This would explain why you see resolution of the domains of ads/trackers.

There could be some other reason for the domain to be resolved even when all URLs under the domain should be blocked; feel free to investigate that.

> Ad domains from filter list shouldn't even be resolved via DNS.

As explained above, this is not something you should expect.

> Also, is there a way to test that the bromite adblock is actually working?

Check for lines with `AdBlockUpdaterService` in your `adb logcat` output; if the filters are downloaded correctly then you can expect that it is working.
