### ISSUE TITLE
custom-filters are not working in case of my custom url for filter list

### ISSUE THREAD

**Issue by jnpatel2811** [bromite/bromite#538]
### Bromite version

Version: `v78.0.3904.130` & `v81.0.4044.106`
Arch: `arm`
Android version: (example: `5.0`)
Device model: (example: `SM-SPH720`)

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Bug description
So I wanted to use the Bromite Custom Ad Block Filters feature introduced in release v78.0.3904.130 (https://www.bromite.org/custom-filters) with my custom list hosted at some url and I'm making sure to send `Last-Modified` field in the response header.

#
So I downloaded the APKs from your GitHub repo releases
v78 https://github.com/bromite/bromite/releases/tag/78.0.3904.130
v81 https://github.com/bromite/bromite/releases/download/81.0.4044.106

#
To create the filters_list.dat file, I used ruleset_converter you provided (got it from https://github.com/bromite/filters/releases/tag/78.0.3904.130 )
Attached both the files, raw urls and converted file

I created my custom filter file and hosted using local python server and used your html files only (https://github.com/bromite/filters)

### Steps to reproduce the bug

Steps to reproduce the bug:
1. I hosted same .html and filters_list.data on python local server
2. clicked on Settings -> AdBlock settings -> Filters URL and entered URL, which is, http://192.168.x.y/filters/filter_list.dat
3. killed app and reopen so that it should fetch the filter_list.dat from my server, I checked in "Network Connections" app that one call from "Bromite" app is going to my custom url.
4. I tried to access web urls kept in filters file and I was able to access it. It wasn't blocked!

### Expected behaviour
I expected that the urls I kept in filters file, it should block the urls but i was able to access those URLs.
#
Please HELP me out in this issue.

### Screenshots
![Screenshot_2020-04-26-23-13-18](https://user-images.githubusercontent.com/18471502/80315413-18346880-8815-11ea-87b4-de42c2bccf07.png)
![Screenshot_2020-04-26-23-13-32](https://user-images.githubusercontent.com/18471502/80315421-1b2f5900-8815-11ea-8820-4ff3c83c457c.png)
![Screenshot_2020-04-26-23-13-43](https://user-images.githubusercontent.com/18471502/80315424-1d91b300-8815-11ea-9828-89c3e7f3c863.png)

### URL filter files
<img width="640" alt="Screen Shot 2020-04-26 at 11 22 25 PM" src="https://user-images.githubusercontent.com/18471502/80315379-d99eae00-8814-11ea-88ce-bdb15d16cd3b.png">
<img width="639" alt="Screen Shot 2020-04-26 at 11 23 15 PM" src="https://user-images.githubusercontent.com/18471502/80315391-f20ec880-8814-11ea-874c-49520a6e2d12.png">

**Comment by csagan5** [comment]
> I created my custom filter file and hosted using local python server and used your html files only

Only the filters file is necessary.

> 3\. killed app and reopen so that it should fetch the filter_list.dat from my server, I checked in "Network Connections" app that one call from "Bromite" app is going to my custom url.

Check the output of `adb logcat` and look for `AdBlockUpdaterService` lines. Most likely there is a problem with your webserver.

You need to test with current version of Bromite, bug reports with older versions of Bromite are not actionable.

**Comment by jnpatel2811** [comment]
[``](

> url

)

**Comment by jnpatel2811** [comment]
> Only the filters file is necessary.

Using `filter_list.dat` file only. html files are for wrapper web page!

> Check the output of adb logcat and look for AdBlockUpdaterService lines. Most likely there is a problem with your webserver.

Sure. will check once. For that, I'll have to get the whole chromium code, your patches to make debuggable build. I tried this on your build only (got it from `Releases` on your Github repo).
So not sure what can go wrong with that!

> You need to test with current version of Bromite, bug reports with older versions of Bromite are not actionable.

I tested on the latest build as well, which is , `v81.0.4044.106`

**Comment by csagan5** [comment]
> For that, I'll have to get the whole chromium code, your patches to make debuggable build. I tried this on your build only (got it from `Releases` on your Github repo).
> So not sure what can go wrong with that!

No, you do not need a debug build, you need the official Bromite release installed on a device and the  `adb` tool on a laptop/PC. See [the official documentation about adb logcat](https://developer.android.com/studio/command-line/logcat).

**Comment by randomshell** [comment]
@jnpatel2811 maybe https://github.com/bromite/bromite/issues/506#issuecomment-596101249?

**Comment by jnpatel2811** [comment]
@csagan5 i'm getting these logs :
`I/chromium(17516): [INFO:adblock_updater_service.cc(139)] AdBlockUpdaterService: MostRecentIndexedVersion = 1.3.12.28032
I/chromium(17516): [INFO:download_filters_task.cc(155)] DownloadFiltersTask: fetching URL 'http://192.168.105.75:8484/filters/filter_list.dat' with method HEAD
I/chromium(17516): [INFO:download_filters_task.cc(155)] DownloadFiltersTask: fetching URL 'http://192.168.105.75:8484/filters/filter_list.dat' with method HEAD
I/chromium(17516): [INFO:download_filters_task.cc(182)] DownloadFiltersTask: downloaded 107 bytes in 944023ms from 'http://192.168.105.75:8484/filters/filter_list.dat' to '/data/data/org.bromite.bromite/cache/.org.chromium.Chromium.miwnrW' with net_error 0 and error 0
I/chromium(17516): [INFO:adblock_updater_service.cc(229)] AdBlockUpdaterService: indexing filters with version 1.3.25.62884
I/chromium(17516): [INFO:ruleset_service.cc(322)] RulesetService: successful parsing.
I/chromium(17516): [INFO:ruleset_service.cc(448)] RulesetService: valid version: 1
I/chromium(17516): [INFO:verified_ruleset_dealer.cc(39)] OpenAndSetRulesetFile: /data/data/org.bromite.bromite/app_chrome/Subresource Filter/Indexed Rules/27/1.3.25.62884/Ruleset Data is valid: 1
`

Looks like it is properly getting parsed. Still I was able to access the web urls blocked in the filters file. 
i.e. there is one filter rule which should block `taboo.com` but I can access it, same for other 2 URLs as well. 
Please check the images in use description for filters file.

**Comment by jnpatel2811** [comment]
> @jnpatel2811 maybe [#506 (comment)](https://github.com/bromite/bromite/issues/506#issuecomment-596101249)?

@randomshell Nope. I'm getting `Last-Modified` correctly! please check logs I've pasted in previous answer.

**Comment by jnpatel2811** [comment]
@csagan5 I have one doubt: To generate final filters url, I have created normal text file and then used your `ruleset_converter` and command as shown at `https://www.bromite.org/custom-filters`

#

Your's command is just 
`ruleset_converter --input_format=filter-list \
		--output_format=unindexed-ruleset \
                --input_files=easyprivacy.txt,easylist.txt \
		--output_file=filters.dat`


#
but on chromium filter list generation page, there are 2-3 more steps. Do I have to run those as well?
```
1. ninja -C out/Release/ subresource_filter_tools
2. out/Release/ruleset_converter --input_format=filter-list --output_format=unindexed-ruleset --input_files=filterlist.txt --output_file=filterlist_unindexed
3. out/Release/subresource_indexing_tool filterlist_unindexed filterlist_indexed
```

Please help me out!

**Comment by jnpatel2811** [comment]
> @jnpatel2811 no, it's just that command. What is the output of `ruleset_converter`? Are you sure you are not getting errors there?

Yes @csagan5 
No output in terminal and no errors, just `filter_list.dat` file gets generated.

#
Please take a look at my `filter_list.txt` file and generated `filter_list.dat` :

<img width="640" alt="Screen Shot 2020-04-26 at 11 22 25 PM" src="https://user-images.githubusercontent.com/18471502/80315379-d99eae00-8814-11ea-88ce-bdb15d16cd3b.png">
<img width="639" alt="Screen Shot 2020-04-26 at 11 23 15 PM" src="https://user-images.githubusercontent.com/18471502/80315391-f20ec880-8814-11ea-874c-49520a6e2d12.png">

**Comment by csagan5** [comment]
> Please take a look at my `filter_list.txt`

It would be better to put the text here rather than a screenshot.

**Comment by csagan5** [comment]
@jnpatel2811 the filters are working as expected. They block **subresources**; the webpage you are loading is not a subresource thus is never blocked. You can see that the subresources matching the filters are being blocked because of the broken taboola styles.

**Comment by jnpatel2811** [comment]
@csagan5 Ohh!!
Thanks for the clarification.

Also, can you please guide me for any other way to block web pages as well? I'm required to have URL site blocker as well in my browser?

**Comment by csagan5** [comment]
> Also, can you please guide me for any other way to block web pages as well? I'm required to have URL site blocker as well in my browser?

Sorry, I do not know how you can achieve this. Perhaps you could look into policies, but it does not seem supported in Android: https://support.google.com/chrome/a/answer/7532419?hl=en

**Comment by jnpatel2811** [comment]
> > Also, can you please guide me for any other way to block web pages as well? I'm required to have URL site blocker as well in my browser?
> 
> Sorry, I do not know how you can achieve this. Perhaps you could look into policies, but it does not seem supported in Android: https://support.google.com/chrome/a/answer/7532419?hl=en

Oh Ok. Thanks @csagan5 !

**Comment by faxotherapy** [comment]
Hi, suppose I wanted to block BBC for testing, I'd normally use `||bbc.co.uk^` in my custom filter. Will the domain be completely blocked? I'm asking this, because after updating `easylist.txt` with the site, and using the `ruleset_converter` command, the site is still not blocked in Bromite.

I used exactly this command:
```shell
ruleset_converter --input_format=filter-list \
		--output_format=unindexed-ruleset \
                --input_files=easyprivacy.txt,easylist.txt \
		--output_file=filters.dat
```

Thanks for your help
