### ISSUE TITLE
ERR_NETWORK_CHANGED error shows briefly before loading website

### ISSUE THREAD

**Issue by razorsoup** [bromite/bromite#539]
### Bromite version

Version: 81.0.4044.127
Arch: arm64
Android version: 10.0
Device model: SM-G973U

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug
When opening a link from another application, Bromite displays an error page briefly before opening the correct site. This seems to only happen if Bromite was not already running.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Close Bromite
2. Open link from another application (eg Reddit) in Bromite
3. See error screen
4. See link finish opening

### Expected behavior
I would expect the error to not be displayed considering that Bromite successfully loads the page. 

### Screenshots
Here's a screenshot of the error page I'm seeing pop up before the actual page loads.
https://i.imgur.com/x2pDR7g.jpg

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> No

This is not correct. See https://duckduckgo.com/?q=chrome+ERR_NETWORK_CHANGED

**Comment by razorsoup** [comment]
Interesting. I wasn't able to reproduce it with Chromium on my end. But I guess this is not a Bromite specific issue then. Sorry for that.
