### ISSUE TITLE
direct apk download from gmail client doesn't work.

### ISSUE THREAD

**Issue by stalkerandrew** [bromite/bromite#54]
bug/feature?

how to reproduce:
1. download gmail on android if you haven't.
2. open gmail, login, click burger menu, settings, general settings, untick "open web links in gmail"
3.send an email with apk download url to your gmail.
4. using your gmail client to open the download link will open bromite(if you only have bromite as default).
5. bromite opened and closed.

what you expected:
downloading file

what happened:
bromite open and close.

does it work on latest chrome:
yes

**Comment by csagan5** [comment]
@stalkerandrew you need to report which Bromite version you are using and the stacktrace dump you find in the logs (`adb logcat`), as I assume it is crashing
