### ISSUE TITLE
Changing User Agent in Bromite?

### ISSUE THREAD

**Issue by junomarian** [bromite/bromite#541]
How i can change user agent in Bromite Browser? I want to use mozilla user agent string. Is it possible on rooted device?

**Comment by ritcher** [comment]
I think you were looking for the `--user-agent` chrome flag.

Example:

```
adb shell echo "chrome --user-agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0'" > '/data/local/chrome-command-line'
```

The command line above will change your user agent to: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0`.

**Comment by junomarian** [comment]
> I think you were looking for the `--user-agent` chrome flag.
> 
> Example:
> 
> ```
> adb shell echo "chrome --user-agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0'" > '/data/local/chrome-command-line'
> ```
> 
> The command line above will change your user agent to: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0`.

And what if i have no pc? but i have rooted phone.

**Comment by ritcher** [comment]
> And what if I have no pc how i can run this abd command? I have rooted phone. At what location to create this file?

Just remove the `adb shell` from the command line and run it in a terminal emulator (e.g Termux) with root access. It will work as well.
