### ISSUE TITLE
DNS over HTTPS- The site cant be reached

### ISSUE THREAD

**Issue by basimaslamts** [bromite/bromite#543]
### Bromite version

Version: `81.0.4044.127'
Arch: `arm` or `arm64` or `x86`
Android version: (example: `9.0`)
Device model: (example: `SM-G960UZKABST`)
Arm64
### Is this bug about the SystemWebView?
Yes/No
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

I'm not sure

### Is the bug a crash?

No

### Describe the bug

If DNS over HTTPS is on, the relevant portion of browsing ends up in a page saying site cant be reached

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Turn on https over dns
2. Add  any service provider
3. Browse for 15 minutes on random sites by searching from google and other
4. At some point you get "site cant be reached"

### Expected behavior

I've seen  few people have come up with this issue in this repo. But they were closed because of not following issue template.
https://github.com/bromite/bromite/issues/502

**Comment by csagan5** [comment]
Repeat your tests on Wi-Fi. It's most likely your provider limiting your traffic because they can't snoop your regular DNS queries.
