### ISSUE TITLE
I18n support for new menu

### ISSUE THREAD

**Issue by zhmars** [bromite/bromite#546]
### Is your feature request related to privacy?

No.

### Is there a patch available for this feature somewhere?

No.

### Describe the solution you would like

Hi, I notice some menu introduced by patches is not localized. Could you please consider adding i18n support for that? I would like to translate bromite into my language.

Please feel free to close this since the feature is not related to privacy.

Screenshot: https://imgur.com/a/PVi5bd2

### Describe alternatives you have considered

Sorry, I dont know.

Edited: remove some screenshots and fix typo.

**Comment by csagan5** [comment]
I understand the problem but I would need somebody to submit a patch for this as I am not able to correctly add the translations.

**Comment by csagan5** [comment]
A partial fix has been released with `83.0.4103.46`.

**Comment by csagan5** [comment]
@zhmars please check if your latest patch looks good on this pre-release: https://github.com/bromite/bromite/releases/tag/83.0.4103.53

Otherwise feel free to open a new PR.

**Comment by zhmars** [comment]
Thanks. Everything looks good except the `About Bromite` menu in setting page. Do you know anything about this?

Screenshot: https://imgur.com/a/ko0hE3y

**Comment by csagan5** [comment]
Fixed in `83.0.4103.53`.

**Comment by csagan5** [comment]
@zhmars that part is automatically replaced through a script, for now I will keep it like this

**Comment by zhmars** [comment]
Ok, thanks a lot for your explanation.
