### ISSUE TITLE
Android autofill doesn't work

### ISSUE THREAD

**Issue by kdrag0n** [bromite/bromite#547]
### Bromite version

Version: 81.0.4044.106.1586736791
Arch: `arm64`
Android version: 10
Device model: Pixel 2 XL

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

Yes

### Describe the bug

According to #348, Bromite should support Android's autofill framework, but it doesn't work on any of my devices. I've tried Bitwarden and 1Password password managers, and none of them detect any login fields in Bromite, while they work with all the other browsers I've tried. Chrome and Firefox Preview have been verified to work.

### Steps to reproduce the bug

1. Enable autofill in any password manager (**not** using accessibility)
2. Go to any website with a login field (e.g. https://github.com/login)
3. Focus the username/email or password field
4. Notice how no popup appears

### Expected behavior

Autofill popup appears under the login field.

### Screenshots

Not working in Bromite:
![image](https://user-images.githubusercontent.com/7930239/81140421-1efe6200-8f1e-11ea-8bed-80f8f7d93af7.png)

Working in Firefox Preview:
![image](https://user-images.githubusercontent.com/7930239/81140414-19088100-8f1e-11ea-99af-bb8ae93ac459.png)

Working in Chrome:
![image](https://user-images.githubusercontent.com/7930239/81140507-6b49a200-8f1e-11ea-9c73-4da5e664c7af.png)

**Comment by csagan5** [comment]
> Working in Chrome:

You should test with the corresponding **Chromium** version, no other browser/version matters.

When testing with Chromium a popup will appear asking you to login to your Google account. That is why this feature is not supported.

> 1. Enable autofill in any password manager (**not** using accessibility)

The native autofill manager needs some Google Play Services integration which is disabled in Bromite because it would require building with a proprietary binary and integrating with some service. We are staying away from those as much as possible.

**Comment by kdrag0n** [comment]
It doesn't work in Bromite's build of Chromium. There are no popups at all, not even a Google account popup.

Android autofill does **not** have anything to do with Google Play Services. I just tested two random apps from the official F-Droid repo (CloudMare and FairEmail) that have no integration with Play Services, and autofill works perfectly in both of them.

**Comment by kdrag0n** [comment]
@csagan5 could this issue be re-opened? As I said above, Android autofill does not have anything to do with Google Play Services. In my testing, several randomly sampled apps from the official F-Droid repository *all* have working autofill. The F-Droid repo prohibits apps with Google Play Services, so there can't be a correlation there.

I just tested autofill with some more Chromium-based browsers. Vanilla trunk builds of Chromium from [Download Chromium](https://download-chromium.appspot.com/) are also broken, but Brave is not, so I suspect that Bromite needs to change something when building Chromium to make it work.

**Comment by csagan5** [comment]
@kdrag0n those apps you tested are not browsers, Chromium variants have a different integration for the autofill feature. Brave uses Google Play Services integrations.

I have tested this already in the past (you have not), it cannot work without enabling the Play Services blob. Feel free to make your own build and verify it yourself.

**Comment by csagan5** [comment]
See also:
* https://github.com/bitwarden/mobile/issues/159#issuecomment-637816327
* https://github.com/Kunzisoft/KeePassDX/issues/551#issuecomment-637814250 (this contains a summary of the situation)

The upstream issue seems to be https://bugs.chromium.org/p/chromium/issues/detail?id=1015381

**Comment by PeterHindes** [comment]
could someone make a diff patch. i would like to use it with the integration anyway. ill just run my own builds with a patch.

**Comment by Socalix** [comment]
**A solution is here!**
I just tried adding Bromite to the `autofill_compat_mode_allowed_packages` as indicated by Kiwibrowser here: https://github.com/kiwibrowser/src.next/issues/64#issuecomment-887592298

With this command:
```adb shell settings put global autofill_compat_mode_allowed_packages "$(adb shell settings get global autofill_compat_mode_allowed_packages):org.bromite.bromite[url_bar]"```

After restarting (must) Bromite - autofill password managers work great! 
Just for curiosity, I tried removing Chrome from this setting and autofill no longer works in Chrome. :smile: 

@csagan5 I see Kiwibrowser is trying to get on the default list, do you think Bromite could get on it too?

**Comment by csagan5** [comment]
@Socalix that sounds very interesting, thanks for reporting back; so this would work even without using the Play Store integration, just by making sure that vanilla Android contains Bromite's package name?

I think it would be hard to convince Android developers to add Bromite, but we could try. Meanwhile the workaround could be mentioned in the FAQs.

**Comment by Socalix** [comment]
@csagan5 Yes, it works as soon as you set this value and restart the browser. My understanding is that it triggers some translation layer between accessibility and autofill API. It will be interesting to know who/what/where decides to put those values there. Brave browser managed to get on that list, so I don't see a reason why others would not.

The tricky part with manually setting it, is that there's something that keeps resetting the value, so it doesn't stay there for more than a few hours. :(

**Comment by plantroon** [comment]
> @csagan5 Yes, it works as soon as you set this value and restart the browser. My understanding is that it triggers some translation layer between accessibility and autofill API. It will be interesting to know who/what/where decides to put those values there. Brave browser managed to get on that list, so I don't see a reason why others would not.
> 
> The tricky part with manually setting it, is that there's something that keeps resetting the value, so it doesn't stay there for more than a few hours. :(

I found that it resets itself at 22:30 (CEST) for me. I did not figure out what mechanism is resetting it either.

**Comment by kdrag0n** [comment]
There's no default value for the `autofill_compat_mode_allowed_packages` setting in AOSP; the `url_bar` values come from Google Play Services, which provisions and overwrites settings periodically. The best solution I can think of (assuming you're not using a custom ROM, where it would be possible to add a hacky override to the system) is restoring the settings periodically using an app like Tasker.

Of course, the ideal solution would be to get Bromite added to Google's list, but I can't see that happening because it's not on the Play Store.

**Comment by lippling** [comment]
> **A solution is here!** I just tried adding Bromite to the `autofill_compat_mode_allowed_packages` as indicated by Kiwibrowser here: [kiwibrowser/src.next#64 (comment)](https://github.com/kiwibrowser/src.next/issues/64#issuecomment-887592298)
> 
> With this command: `adb shell settings put global autofill_compat_mode_allowed_packages "$(adb shell settings get global autofill_compat_mode_allowed_packages):org.bromite.bromite[url_bar]"`
> 
> After restarting (must) Bromite - autofill password managers work great! Just for curiosity, I tried removing Chrome from this setting and autofill no longer works in Chrome. 😄
> 
> @csagan5 I see Kiwibrowser is trying to get on the default list, do you think Bromite could get on it too?

I use GrapheneOS and the workaround does not work for me.

**Comment by famo** [comment]
> There's no default value for the `autofill_compat_mode_allowed_packages` setting in AOSP; the `url_bar` values come from Google Play Services, which provisions and overwrites settings periodically. 

What about ROMs without GPS, but microG? I assume microG could theoretically set this value?

> The best solution I can think of (assuming you're not using a custom ROM, where it would be possible to add a hacky override to the system) is restoring the settings periodically using an app like Tasker.

For this to work one still needs root access, which really limits the scope of that solution..

> Of course, the ideal solution would be to get Bromite added to Google's list, but I can't see that happening because it's not on the Play Store.

See above, would it be useful to open an feature request on [mircoG](https://github.com/microg/GmsCore), @kdrag0n ?
Ideally microG could implement a setting where a user can choose apps to add the the `autofill_compat_mode_allowed_packages` list.
This way at least some systems would work...


Btw, this still wouldn't enable native autofill, but rather the compatibility mode (see [autofill-services](https://developer.android.com/guide/topics/text/autofill-services)), so further progress on this might should be tracked in an another issue.


@csagan5 
> The upstream issue seems to be https://bugs.chromium.org/p/chromium/issues/detail?id=1015381

This issue is resolved by now, does it help for native autofill in bromite?

**Comment by csagan5** [comment]
> Btw, this still wouldn't enable native autofill, but rather the compatibility mode (see [autofill-services](https://developer.android.com/guide/topics/text/autofill-services)), so further progress on this might should be tracked in an another issue.
> 
> @csagan5

It is unclear to me what needs to be changed in Bromite, so not sure what the new issue would contain.

**Comment by uazo** [comment]
> also, please open another issue with your device details
> Sure. Will do so later.

please fill in your details so let us understand

**Comment by PurpleCodingWizard** [comment]
> > also, please open another issue with your device details
> > Sure. Will do so later.
> 
> please fill in your details so let us understand

Sorry for late reply
 But, apparently, it worked once or twice on amazon.com so atleast it works in some sites out there. I will try to file a bug report after I get the time to test more later

**Comment by csagan5** [comment]
> Sorry, I had to manually type the version as there's no copy function in settings. This is the latest that shows in github releases.

Please edit the issue description with the correct version, it is not optional; none of the template questions are.
