### ISSUE TITLE
Add Startpage again

### ISSUE THREAD

**Issue by Poid-bit** [bromite/bromite#548]
### Is your feature request related to privacy?
yes

### Is there a patch available for this feature somewhere?
no

### Describe the solution you would like
Add Startpage to the default list of search engines again
Startpage has been relisted on privacytools.io
https://blog.privacytools.io/relisting-startpage/
Concerns about the company have been settled

### Describe alternatives you have considered

Adding it manually but for an unknown reason it's not appearing in my list even though I visited it

**Comment by csagan5** [comment]
It would be nice to search the issue tracker about proposing again the same feature.

See https://github.com/bromite/bromite/issues/435#issuecomment-578050585

> Adding it manually but for an unknown reason it's not appearing in my list even though I visited it

It works for other search engines. You should check with Startpage why that does not work.

**Comment by Poid-bit** [comment]
I still don't understand why you don't leave the decision to the user, as you even allow search engines like google, but oh well. 
![Shrug](https://i.imgur.com/KPsNfRg.gif)

**Comment by bocekm** [comment]
You can add Startpage as a default search engine this way: https://github.com/bromite/bromite/discussions/1372#discussioncomment-1318031
