### ISSUE TITLE
force-device-scale-factor changes bromite tab design

### ISSUE THREAD

**Issue by Baltazar500** [bromite/bromite#550]
### Bromite version

Version: 75.0.3770.109
Arch: arm64
Android version: 5.1
Device model: Highscreen Boost 3 Pro

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Not tested

### Can the bug be reproduced with corresponding Chromium version?

Not tested

### Is the bug a crash?

No

### Describe the bug

Bromite changes tab design from mobile to desktop when using the option --force-device-scale-factor in /data/local/chrome-command-line (used with the --user-agent switch to permanently enable the desktop mode for sites).

### Steps to reproduce the bug

Write to /data/local/chrome-command-line chrome --force-device-scale-factor=1.75

### Expected behavior

Do not change tab design when using force-device-scale-factor

### Screenshots

http://i1.sendpic.org/i/wi/wiKPDNwre...9ugdQjuO4Q.jpg

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> Not tested

That is not optional. If it is a Chromium issue you need to report to them.
