### ISSUE TITLE
Black stripe on top

### ISSUE THREAD

**Issue by 314resqi** [bromite/bromite#556]
### Bromite version

Version: 81.0.4044.127/81.0.4044.106
Arch: arm64
Android version: 10
Device model: sm-m205fn

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug
black stripe between status bar and bromite window

### Steps to reproduce the bug
disable your wifi and data and black bar appears

### Expected behavior
there isnt supposed to be black bar

### Screenshots
https://imgur.com/gallery/QU3WxtI
1 internet on
2 internet off
3 internet off, bromite and system ui set to light mode

**Comment by csagan5** [comment]
Can anyone else reproduce this issue?

@314resqi can you see anything possibly related in the logs (`adb logcat`)? No need to post here your logs, but if you do please remember to remove personal information.

**Comment by 314resqi** [comment]
i will into it

**Comment by 314resqi** [comment]
what kind of arguments should i use in adb?
long, time, raw etc 
to make it easier for you?

**Comment by csagan5** [comment]
@314resqi does not matter; what matters is some indication of what the black bar is

**Comment by csagan5** [comment]
Please check if issue is fixed with this pre-release: https://github.com/bromite/bromite/releases/tag/83.0.4103.53
