### ISSUE TITLE
[Bug] Chromium Version Bug

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [bromite/bromite#557]
### Bromite version
Version: `81.0.4044.127`
Arch: `arm64`
Android version: `10.0`

### Describe the bug
Got a weird issue `chrome://version` chromium version is not matching with https://chromium.woolyss.com (Chromium Offical Site) chromium version dectection API 
Showing chromium version something older version & seems calling the `User Agent` version

### [Note]
Tested with other chromium based browsers like opera and brave. And the version is matching !
Confused if it's occured due to Anti-Fingerprinting. I am using Android 10

![Screenshot_20200510-190226](https://user-images.githubusercontent.com/54761717/81500103-a4ed2500-92f1-11ea-8025-996123272fa0.jpg)
![Screenshot_20200510-190420](https://user-images.githubusercontent.com/54761717/81500112-afa7ba00-92f1-11ea-99a5-71daab37f31c.jpg)

**Comment by csagan5** [comment]
It's working as intended; see [Features](https://github.com/bromite/bromite#features) and #156.
