### ISSUE TITLE
SystemWebView crashes when opening a site or application

### ISSUE THREAD

**Issue by brunoalvieira** [bromite/bromite#558]
### Bromite version

Version: 81.0.4044.127
Arch: `x86` ('x64' not tested)
Android version: 7.1.2
Device model: Virtualbox (Android-x86 Project)

### Is this bug about the SystemWebView?
Yes

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
Yes

### Is the bug a crash?
Yes

### Describe the bug
I open the Web View Test or other Web View application based and after several time, this app crashes.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Download Android x86 7.1.2 R3, install it , creating a virtual machine in VirtualBox, with 1556 MB or higher, Linux 2.6/3/4.x (32 bits)
2. Go to the /system/app/webview (use file manager with root access). Delete the native webview.apk and paste the Bromite/Chromium Web View app and rename it as webview.apk (as recommended by the Bromite project); then, reboot the system
3. Go to the Web View Test, check if system recognize the Bromite/Chromium corresponding version
4. Try access a site (for example, Twitter) and verify this behavior

### Expected behavior

The expected behavior is to open the website and persist as usual, as expected from everyday use, without affecting the functioning of the Web View-based app.

### Screenshots

![VirtualBox_Android 7 1 2_10_05_2020_19_50_23](https://user-images.githubusercontent.com/39491972/81513497-59da0e80-92ff-11ea-8ebd-a85308dc4d3e.png)
![VirtualBox_Android 7 1 2_10_05_2020_19_57_15](https://user-images.githubusercontent.com/39491972/81513498-5a72a500-92ff-11ea-9c30-2ea633c8bb43.png)

**Comment by csagan5** [comment]
You should post the logs of the crash, not screenshots of the logs.
