### ISSUE TITLE
Add support for (Chromium) extensions

### ISSUE THREAD

**Issue by BlackWinnerYoshi** [bromite/bromite#560]
### Is your feature request related to privacy?

Certain extensions can increase privacy, so I consider this a yes.

### Is there a patch available for this feature somewhere?

URL: https://github.com/kiwibrowser/src
License: BSD-3-Clause

### Describe the solution you would like

As Kiwi Browser recently went open-source and supports Chromium extensions, I think other Chromium-based browsers should add support for extensions, including Bromite.

### Describe alternatives you have considered

The only alternative I considered is changing the browser base to Firefox, but obviously that won't happen.

**Comment by csagan5** [comment]
Please search the issue tracker before creating new issues.
