### ISSUE TITLE
Automated-domain-substitution.patch failes to apply in 83.0.4103.46

### ISSUE THREAD

**Issue by danielfullmer** [bromite/bromite#561]
When applying `Automated-domain-substitution.patch` on `83.0.4103.46` using `git apply`, it fails with the following error:

```
error: corrupt patch at line 142767
```

Here are the lines surrounding line 142767 of `Automated-domain-substitution.patch`:
```patch
--- a/third_party/blink/web_tests/ietestcenter/css3/bordersbackgrounds/background-attachment-local-scrolling.htm
+++ b/third_party/blink/web_tests/ietestcenter/css3/bordersbackgrounds/background-attachment-local-scrolling.htm
@@ -29,7 +29,7 @@
 <html xmlns="http://www.w3.org/1999/xhtml">
     <head>
-        <link rel="author" title="Microsoft" href="http://www.microsoft.com/" />
+        <link rel="author" title="Microsoft" href="http://www.m1cr050ft.qjz9zk/" />
         <link rel="help" href="http://www.w3.org/TR/css3-background/#the-background-attachment" />
         <meta name="flags" content="" />
         <meta name="assert" content="If 'background-attachment: local' the background scrolls along with the element's contents (the UA may treat 'background-clip: border-box' as the same as 'background-clip: padding-box')." />
```

However, compare this with the chromium source:
https://chromium.googlesource.com/chromium/src.git/+/refs/tags/83.0.4103.46/third_party/blink/web_tests/ietestcenter/css3/bordersbackgrounds/background-attachment-local-scrolling.htm

The hunk in `Automated-domain-substitution.patch` looks to be missing the line immediately before the changed line:
```
<title>CSS Test: Scrolling when background-attachment: local</title>
```

Perhaps this is a result of the strange characters included in that line? There are surrounding hunks (see the one changing `background-size-aspect-ratio.htm`) which have the same issue with missing the `<title>` line. However, hunks which do not have those special characters in the `<title>` do not have the same problem

**Comment by csagan5** [comment]
See https://github.com/bromite/bromite#how-to-build

I am sorry, no support is provided for builds.

**Comment by csagan5** [comment]
@danielfullmer try with latest version of the patch; you should use `git am` though.

**Comment by danielfullmer** [comment]
With the latest patch (using `git am`), I have the following failures on `Automated-domain-substitution.patch`:

```
error: patch failed: chrome/browser/ui/android/strings/android_chrome_strings.grd:1547
error: chrome/browser/ui/android/strings/android_chrome_strings.grd: patch does not apply
error: patch failed: components/ntp_tiles/resources/default_popular_sites.json:1
error: components/ntp_tiles/resources/default_popular_sites.json: patch does not apply
error: patch failed: components/policy/resources/policy_templates.json:19862
error: components/policy/resources/policy_templates.json: patch does not apply
```

This is against `83.0.4103.46`.

**Comment by csagan5** [comment]
Try against `83.0.4103.53`, that's the one I am targeting for next release.

**Comment by danielfullmer** [comment]
No worries, I ended up running `domain_substitution.py` from `ungoogled-chromium` manually.
