### ISSUE TITLE
Page info no longer displays full URL

### ISSUE THREAD

**Issue by Madis0** [bromite/bromite#564]
### Bromite version

Version: `83.0.4103.46`
Arch: `arm64`
Android version: `10`
Device model: `ONEPLUS A5010`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

Yes, it is indeed an upstream bug. **Posting it here as a feature request as I think it was intended by the Chromium Team.** Or, well, even if they fix it upstream, it would take a whole major version to do it, as the release of 83 is nearing soon - perhaps Bromite can make a temporary patch meanwhile.

### Is the bug a crash?

No

### Describe the bug

The page info popup that describes connection security, permissions etc no longer displays the full URL but only the host.

### Steps to reproduce the bug

1. Open https://www.bromite.org/news/2020-05-12-bromite-v83-release
2. Tap the padlock
3. Note the URL

### Expected behavior

Expected to see https://www.bromite.org/news/2020-05-12-bromite-v83-release but only saw https://www.bromite.org/

### Screenshots

Posted to upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1082051

**Comment by csagan5** [comment]
It's a feature request for Bromite rather than a bug.

It must have been recently changed (after `83.0.4103.34`), could you find the commit?

**Comment by Madis0** [comment]
This seems to be the one, as suggested in the upstream bug.
https://chromium-review.googlesource.com/c/chromium/src/+/2055806

**Comment by csagan5** [comment]
They have hidden it to avoid exposing username and password.

**Comment by Madis0** [comment]
Yeah, but apparently the path hiding was not intended and is being fixed right now, which is great.

**Comment by csagan5** [comment]
In this case better wait upstream about it.
