### ISSUE TITLE
How to add custom search engine

### ISSUE THREAD

**Issue by TachyonRSA** [bromite/bromite#566]
If I understand correctly, I just need to browse to a search engines OpenSearch page and I should be able to add it. But when I went to StartPage (https://www.startpage.com/en/opensearch.xml), I don't see the search engine under the settings.

Am I doing something wrong?

**Comment by bocekm** [comment]
You can add Startpage as a default search engine this way: https://github.com/bromite/bromite/discussions/1372#discussioncomment-1318031
