### ISSUE TITLE
Page request to require explicit permissions

### ISSUE THREAD

**Issue by Wilker-a** [bromite/bromite#567]
### Is your feature request related to privacy?

Yes.

### Is there a patch available for this feature somewhere?

[IceCat browser](https://www.gnu.org/software/gnuzilla/) (MPL-2.0) has an extension to make this action out of the box, but i don't know much about the license of it (as in which license it uses currently).

### Describe the solution you would like

for every new domain and subdomain that the browser visits, each and every request coming from, and going to another subdomain and domain including father domains, are to be blocked and prevented until explicit permission is given via a checkbox list of all the domains which the site ever asked the browser to make a request to. this would improve the transparency provided from the sites by a lot.

because this is a function that would be used quite frequently, it would be best to have it accessible by no more than two taps or clicks (preferably one).

### Describe alternatives you have considered

number of requests blocked to be displayed constantly like in the Icecat/Firefox extension is really useful, but maybe (color|symbol)-coded item lists based on what it tries to access by recognizing the outgoing headers would be a good addition also (unless there is a detail that i am missing, like potential risk from the browser storing request information).

i think the padlock icon button as a place to put privacy-related settings and information is underappreciated by many browsers despite the few useful straightforward functions, so i think the list of domain permissions should go there, built in a way to separate the certificate information from the list and the rest of the settings, while the number of blocked domains should appear over the padlock itself.

permissions for redirecting in non obstructive prompt dialogs could be useful too. \^\^

thank you for reading \^w\^

**Comment by csagan5** [comment]
This would require massive work on the UI and I cannot even try to do that. There are no chances that this can be implemented with some easy patch and the benefits are dubious: what is the criteria that an user should use to accept or deny some subresource?

**Comment by Wilker-a** [comment]
there are likely some better methods to select those, but the usual criteria that i use is usually

1. do i really need this resource to use the page?
2. do i trust this domain?

what i end up with is that i enable the minimum to get the page running what i need. e.g i don't need anything cosmetic to show me a news article, much less enable the dozens of domains where the page asks me to go all at once, but i would likely need to enable image loading from a specific subdomain to show me relevant images on issues at Gitlab or Github. i believe this would decrease the surface through which the sites can trick the browser into giving more data.

btw i've just learned about uBlock Origin now, which allows the browser to do that too with a couple more tools. it is under the GPLv3. would a shortcut to the extension tools be easy to implement in the padlock and be worth it?

**Comment by Madis0** [comment]
You are probably better off using uMatrix or NoScript in Firefox, Yandex (closed) or Kiwi (somewhat abandoned), until the community figures out how to feasibly port extensions to (more) Chromium browsers. For a simpler request, though, perhaps iframe blocking could be a thing?

**Comment by csagan5** [comment]
> would a shortcut to the extension tools be easy to implement in the padlock and be worth it?

Absolutely not, it would be a mess and without even considering the maintenance cost. You cannot fit a desktop extension on an phone screen.

As written in the FAQs it's not possible to bring individual extensions inside Bromite. There is not much we can do here, the use case goes beyond the purpose of this browser.

**Comment by Wilker-a** [comment]
a staightforward Yes or No checkbox list could to allow domains could easily fit in a phone screen, no? as i am writing this i have the extension that pretty much works like this, but i mentioned about its tools as a shortcut, not the extension itself. but i understand what you mean..

**Comment by Madis0** [comment]
You're asking for a too niche use case though, perhaps try AdAway or NetGuard for a browser-independent management.

**Comment by Wilker-a** [comment]
i thought the objective of this feature would be to reduce the attack surface of the browser to avoid tracking, like most other privacy features in this browser. i don't think that NetGuard is relevant here.. (i don't know enough about AdAway to tell the same).
