### ISSUE TITLE
black bar 2: *purple is the new black

### ISSUE THREAD

**Issue by 314resqi** [bromite/bromite#569]
### Bromite version

Version: 83.0.4103.53
Arch: arm64
Android version: 10
Device model: sm-m205fn

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?
No ?

### Is the bug a crash?
No

### Describe the bug
Black bar is still there, but now its labeled.
When my internets off, its says in my native language  "no internet connection".
Then i turn my net on and the bar and status bar turns blue-purple-ish and it says "online again",
after 2 (or so) sec it dissapears

### Screenshots
http://imgur.com/gallery/8JcRIOO

**Comment by 314resqi** [comment]
i wanted to post some adb logcat but i was busy

**Comment by csagan5** [comment]
@314resqi the log may not tell anything about this, but how do we know it's coming from Bromite? 

> No ?

You have to test with Chromium.
