### ISSUE TITLE
Option for various UI mods switch

### ISSUE THREAD

**Issue by D0ve** [bromite/bromite#57]
As I know there are several mods of UI hardcoded inside android build,
1. for desktop  -  tabs+all buttons and bars
2. for tablet  -  tabs+medium buttons
3. for smartphone  -  minimal elements
(may be more , 4. for phablet  -  tabs+several buttons)

Great to be an option to switch between those modes (al least for now in about:flags)
Goal for example: using tabs in smartphone...
Many thanks in advance!

**Comment by csagan5** [comment]
@D0ve I do not understand, what mods do you see in the current Bromite build?

**Comment by D0ve** [comment]
I mean various interfaces for different android devices with different size screen!
On tablet I see tabs with more buttons, on smartphone I see minimal interface( and without buttons(.

**Comment by csagan5** [comment]
This project has no interest in developing on merging patches for UI features, sorry.

**Comment by D0ve** [comment]
Interesting, why? Why not to use tabs on smartphones?
Because someone in G. desided to give tabs and more ui elemes for tablets only, and put the lack of it for smartphones... . Imho no need much , but only get rule that switch , that  decide what  gadget is used... .

**Comment by Madis0** [comment]
I highly doubt there are more than two hardcoded layouts, it is just mobile or tablet according to your DPI. The desktop browser is a whole another codebase (though I believe the renderer and some stuff are forked to mobile).
