### ISSUE TITLE
Bookmark all tabs

### ISSUE THREAD

**Issue by DragoCubed** [bromite/bromite#570]
### Is your feature request related to privacy?

I think it's more about freedom. It's also related to performance. Bromite allows you to import and export your bookmarks which is an amazing addition. 

### Is there a patch available for this feature somewhere?

No
### Describe alternatives you have considered

a new folder could be created without prompt and allow users to access it quickly from a snackbar button, much like bookmarking a page.

**Comment by csagan5** [comment]
This has nothing to do with privacy.

**Comment by csagan5** [comment]
As I [commented here](https://github.com/wchen342/ungoogled-chromium-android/issues/26#issuecomment-637777685) it looks like this feature already exists for Desktop. We might be able to get it on Android too, minus the UI part.

**Comment by csagan5** [comment]
Filed upstream here: https://bugs.chromium.org/p/chromium/issues/detail?id=1130144

**Comment by csagan5** [comment]
Fixed in `88.0.4324.187`.

@uazo if you see the patch, I tried to use a dedicated folder but the bookmarks in it would disappear after exiting the browser. If you can spot where is the bug, we can restore that part. Right now it saves to mobile folder.

**Comment by uazo** [comment]
I'll look at it but for now I'm fixing #831  by allowing the save upon request with the dialog and it seems to work (you can save directly in the cloud!). I just miss the preference and the strings.
