### ISSUE TITLE
Webview build error with tag 83.0.4103.46

### ISSUE THREAD

**Issue by scanno** [bromite/bromite#573]
When trying to build Chromium and Webview using the tag 83.0.4103.46, the building of webview fails. Chromium itself builds without failure.

The Webview build fails with:

```
In file included from ../../components/component_updater/adblock_updater_service.cc:18:
In file included from ../../components/component_updater/adblock_updater_service.h:34:
In file included from ../../components/component_updater/download_filters_task.h:31:
In file included from ../../services/network/public/cpp/shared_url_loader_factory.h:15:
In file included from ../../services/network/public/cpp/resource_request.h:20:
In file included from ../../services/network/public/cpp/optional_trust_token_params.h:10:
android_clang_arm/gen/services/network/public/mojom/trust_tokens.mojom.h:32:10: fatal error: 'url/mojom/origin.mojom.h' file not found
#include "url/mojom/origin.mojom.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
Complete build log is available

Building with 
chrome_modern_public_apk 64 bit version
system_webview_apk 64 bit version

Building without the Bromite pacthes is succesful.

**Comment by csagan5** [comment]
No support is provided for building; try the Chromium development mailing list.

**Comment by scanno** [comment]
No need to go the the Chromium dev list. Without the bromite patches everything builds without problems.

**Comment by csagan5** [comment]
Maybe you need this fix: https://stash.netitwork.net/projects/IR/repos/iridium-browser/commits/dab46313f1b41e8cd591d2c0e5e610a8c7f3afbc

I do not have this failure because possibly the file was previously generated.

That file is generated through `mojom_bindings_generator.py`: 
https://source.chromium.org/chromium/chromium/src/+/master:out/Debug/gen/url/mojom/origin.mojom.h

**Comment by scanno** [comment]
Is building.
One thing though, the Automated-domain-substitution patch does not apply.
Seems there is a patch missing. An example:

```
diff --git a/components/ntp_tiles/resources/default_popular_sites.json b/components/ntp_tiles/resources/default_popular_sites.json
--- a/components/ntp_tiles/resources/default_popular_sites.json
+++ b/components/ntp_tiles/resources/default_popular_sites.json
@@ -1,8 +1,8 @@
 [
     {
-        "large_icon_url": "https://www.chromium.org/_/rsrc/1484148948583/apple-touch-icon.png",
+        "large_icon_url": "https://www.ch40m1um.qjz9zk/_/rsrc/1484148948583/apple-touch-icon.png",
         "title": "Chromium - The Chromium Projects",
-        "url": "https://www.chromium.org/Home"
+        "url": "https://www.ch40m1um.qjz9zk/Home"
     },
     {
         "large_icon_url": "https://www.bromite.org/android-icon-192x192.png",

```

The last line is incorrect. In reality that line says:
`        "favicon_url": "https://codereview.chromium.org/static/favicon.ico",
`
Also on line 9515 of the patch it says
```
@@ -1547,16 +1547,16 @@ Your Google account may have other forms of browsing history like searches and a
         Google Terms of Service
       </message>
       <message name="IDS_GOOGLE_TERMS_OF_SERVICE_URL" desc="URL for Google terms of service" translateable="false">
-        https://policies.google.com/terms
+        https://policies.9oo91e.qjz9zk/terms
       </message>
```
The offset should be 1553 instead of 1547

The first example feels like there is a patch missing in your published set of patches (i checked out the master branch).

**Comment by csagan5** [comment]
> The first example feels like there is a patch missing in your published set of patches

Yes, I run some script to replace the text of Chromium with Bromite so most probably that's the cause, I have updated the patch in 4c4dd71.
