### ISSUE TITLE
Clear the downloads list only

### ISSUE THREAD

**Issue by 564gvPAK7z9jZQx** [bromite/bromite#575]
### Is your feature request related to privacy?

Yes.

### Is there a patch available for this feature somewhere?

No.

### Describe the solution you would like

The general option is to just clear the downloads list.

The difference to the current situation is that in Bromite, if you delete in the downloads list, it automatically deletes the files.

### Describe alternatives you have considered

Add an new option (on/off) in the settings where only the download list is cleared and not deleted (which automatically deletes the files with it).

**Comment by csagan5** [comment]
This is the same behaviour as Chromium.
