### ISSUE TITLE
Delete browser data on exit

### ISSUE THREAD

**Issue by 564gvPAK7z9jZQx** [bromite/bromite#577]
### Is your feature request related to privacy?

Yes.

### Is there a patch available for this feature somewhere?

No.

### Describe the solution you would like

A new option to extend the quit function.

When the extended exit function is set up, you can decide what exactly will be deleted when you exit the app (when you click on the "Exit" button).

The template (UI design, selection) from the section "Privacy -> Clear browsing data" can be taken completely.

Basic:
Time range
Browsing history
Cookies and site data
Cached images and files

Advanced:
Time range
Browsing history
Cookies and site data
Cached images and files
Saved passwords
Auto-fill form data
Site settings

### Describe alternatives you have considered

N/A

**Comment by csagan5** [comment]
Search the issue tracker before submitting new issues.
