### ISSUE TITLE
Chrome Duet malfunction

### ISSUE THREAD

**Issue by spinoza-dat** [bromite/bromite#580]
Version: `83.0.4103.53`
Arch: `arm64`
Android version: `9.0`
Device model: `ZUK Z2121`

Chrome Duet doesn't work in Home-Search-Tab Switcher Variation.

I tried on same version of Vanilla Chromium, everything's fine there.

1. Go to `chrome://flags/`
2. Go to Chrome Duet
3. Select Home-Search-Tab Switcher Version
4. Relaunch
5. Chrome Duet will be set on Home-Search-Share Version, but it you go again to chrome://flags/ it will be shown as Home-Search-Tab Switcher.

The bug started showing up on 83.0.4103.46 from what I'm seeing, since going back to 81.0.4044.127 fixes that.

![Screenshot_20200516-131720_Bromite](https://user-images.githubusercontent.com/63900993/82120490-cb461100-9786-11ea-97fa-283e402904a3.png)

**Comment by soriter546** [comment]
This is literally the reason I had to switch from Bromite (which I loved) to Brave :( 
I hope it gets fixed soon.

**Comment by Realex-fire** [comment]
Bug still exists, verified on android 10.

**Comment by spinoza-dat** [comment]
@Realex-fire just check the changelog, it won't be fixed until you'll see "#580 fixed" there. I'm sure they'll do it someday, they always do an excellent job, just give them time. You can rollback to 81 if you need it

**Comment by basimaslamts** [comment]
Thanks mahm for bringing up the issue.. me also wanted to do so.. screenshot is provided

**Comment by Bec-de-Xorbin** [comment]
Chrome Duet will be removed in version 84 anyway, so not much point to fix this bug...

**Comment by basimaslamts** [comment]
@Bec-de-Xorbin I wish there would be an alternative to chrome duet like it got evolved from chrome home

**Comment by spinoza-dat** [comment]
@Bec-de-Xorbin what? Why? This is so dumb, why would they remove such a useful feature? I don't want to migrate to Brave just to have a reachable toolbar for my lil thumb... Will they implement something else? An alternative?

**Comment by spinoza-dat** [comment]
That part of the code could be taken from Kiwi Browser, they are keeping it on

**Comment by csagan5** [comment]
> But this would be a huge mistake

Report it upstream on the Chromium issue tracker; Bromite tries to maintain minimal UI changes, the project is about privacy.

**Comment by basimaslamts** [comment]
I'm sure chromium doesn't love Chrome duet. I know this because I had registered a proposition regarding adding more options to Chrome duet. Now the status of the proposition is unknown.

**Comment by csagan5** [comment]
With the upcoming release of v84 this bug does not apply anymore.

**Comment by Oymate** [comment]
> @Bec-de-Xorbin I don't want to migrate to Brave just to have a reachable toolbar for my lil thumb.

Firefox? It is in their nightly.

**Comment by spinoza-dat** [comment]
> Firefox? It is in their nightly.

I didn't know that, thank you so much!

**Comment by spinoza-dat** [comment]
@csagan5 on Vanilla Chromium 83 there is no issue. This means it's a Bromite and Ungoogled-Chromium bug, not an upstream issue. Please reopen #580

**Comment by csagan5** [comment]
> on Vanilla Chromium 83 there is no issue.

@spinoza-dat that is not the current version.

**Comment by spinoza-dat** [comment]
@csagan5 but it's an old bug. Duet isn't even supported in newer versions of Chromium, wasn't it deprecated? How could it be bugged? In the previous versions it used to work fine, while since v79 it hasn't been working on Bromite

**Comment by csagan5** [comment]
@spinoza-dat only the current version is supported; if Duet is not supported in recent versions of Chromium, what is the bug to fix (in recent versions of Bromite)?

**Comment by spinoza-dat** [comment]
@csagan5 duet only works in home/search/share configuration. The home/search/tab switcher option in the flag changes nothing (see the screenshot I attached to the first post) while it should replace the share button with the tab switcher button. It used to work until v81 of Bromite, then stopped working on Bromite but never had any problems on Chromium.
Since search and tab switcher are the main requested buttons in bottom toolbars (just look at every other browser with bottom toolbar, the tab switcher is ALWAYS at the bottom) duet without the home/search/tab switcher is almost useless.

**Comment by csagan5** [comment]
@spinoza-dat I want to help, but I do not really know all combinations of (current) Chromium flags. Let's continue this conversation on #697; see my last comment.
