### ISSUE TITLE
The F-droid mirror is slow...very slow

### ISSUE THREAD

**Issue by takase1121** [bromite/bromite#581]
Sorry for not following the issue template but the F-droid repo for Bromite is extremely slow (Around 8kb/s?). I am unable to update my Bromite.

**Comment by csagan5** [comment]
@takase1121 download it from [GitHub releases](https://github.com/bromite/bromite/releases); there is a bug in the F-Droid client that makes it keep downloading the same update over and over again, thus there is a limitation applied.
