### ISSUE TITLE
Android TV version

### ISSUE THREAD

**Issue by locodocoman** [bromite/bromite#583]
### Is your feature request related to privacy?

Yes, but only partially.

### Is there a patch available for this feature somewhere?

No.

### Describe alternatives you have considered

There are few browser that are optimized for Android TV and none that is privacy-oriented.

Hi,

I enjoy using your browser on mobile phones so Iwas  wondering, would you ever consider building a version optimized for Android TV? 

Thanks for all your work,
Loco

**Comment by csagan5** [comment]
You need to ask this upstream to the Chromium project, it is out of scope for Bromite.
