### ISSUE TITLE
Webview response

### ISSUE THREAD

**Issue by docbt** [bromite/bromite#585]
Hi,

thank you for this wonderful webview implementation.
I am using a firewall with dns ad blocking lists (hosts) together with your webview.

Is there any chance to replace the default look of "webiste not found"?
Is the website not found site gernerated by webview?

It would be very nice to answer just with a blank page on speciic dns return codes!
The in-app ads would look much better like this...

Thanks greetings
doc

**Comment by docbt** [comment]
Hi Carl,
I updated my post with the required information for a feature request.
Thanks, Greetings
doc

**Comment by csagan5** [comment]
@docbt feature requests which are not about privacy are not considered, it's written in the issue template.
