### ISSUE TITLE
Tab switcher button does not appear and can not be enabled

### ISSUE THREAD

**Issue by lucianlau** [bromite/bromite#587]
### Bromite version

Version: `8.3.0.4103.53`
Arch: `arm64`
Android version: `9.0`
Device model: `Mi Pad 4 LTE`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

Yes

### Is the bug a crash?

No

### Describe the bug

Tab switcher button doesn't appear and can't be enabled.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to '+' and add additional tabs
2. Expect to see tab switcher button but none appears just additional tabs

### Expected behavior

Expect to see tab switcher button but none appears just additional tabs
### Screenshots

![Screenshot_20200520-182543](https://user-images.githubusercontent.com/6175314/82423779-9cea6d80-9ac7-11ea-81df-560fbecb97ad.jpg)

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> Yes

If this is reproducible with Chromium then you need to ask upstream on the Chromium issue tracker about the bug.
