### ISSUE TITLE
Crashes continuously

### ISSUE THREAD

**Issue by abh-oss01** [bromite/bromite#588]
### Bromite version

Version: `83.0.4103.53`
Arch: `arm64`
Android version: `8.1`
Device model: Xolo ZX

### Is this bug about the SystemWebView?
No

### Is the bug a crash? -- Yes
[Here is the logcat](https://del.dog/ippiselaif.txt)

### Screenshots

Actual behaviour --  https://imgur.com/a/T9aZncB

**Comment by csagan5** [comment]
> Version: `83.0.4103.53`

This is not the latest version.

Duplicate of #565

**Comment by abh-oss01** [comment]
I have mentioned the latest version at the top, I mentioned the older version so as to iterate from which version the crash had started.
