### ISSUE TITLE
Exception for sites in terms of cookie deletion on browser exit

### ISSUE THREAD

**Issue by pilsnerbeer** [bromite/bromite#591]
### Describe the solution you would like
An option to create exception for website (facebook.com, *.google.com) to shield this website from its cookies being removed if the "keep cookies only until you quit browser" option is selected. Similar system is being used by Cookie AutoDelete plugin on browsers. 

The "cookie" menu of the app offers "Add site exception". At first, I though this to be the feature I am requesting, however it instead provides an exception to saving and storing cookies in whole. What I am thinking is a whitelist for certain sites.

![p](https://user-images.githubusercontent.com/36133540/82726580-612cef00-9ce5-11ea-888a-310e6a40a0be.jpg)

**Comment by basilgello** [comment]
I solved exactly this problem by using Site Engagement functionality available in any Chromium browser. Here is how I usually utilize it:

1. In the "normal" mode (i.e NOT incognito or always-incognito one!), open the website you wish to keep cookies saved and login to it.
2. Set a bookmark for the website and open several pages. If webpages on the site have videos, play them several times.
3. Go to Settings - Privacy - Delete Private Data and select Extended tab. Delete the whole history.
4. Before deletion, the "Delete data from all sites including these" popup window appears. UNCHECK the sites you wish to keep cookies for.
5. Close the browser. Make sure the "Delete cookies on exit" checkmark is NOT active!

Usually, I use always-incognito mode for 99% websites. For those websites needing authorization / saved sessions, I switch always-incognito mode off, restart browser and visit the necessary website. When browsing is complete, I just clear all history following the steps above.

**Comment by csagan5** [comment]
@basilgello that looks like an interesting functionality, I was not aware of it.

@pilsnerbeer a feature like this would take too much work to implement, I cannot commit to such effort.

**Comment by pilsnerbeer** [comment]
Understandable, thanks for consideration.
