### ISSUE TITLE
Search suggestions in incognito mode

### ISSUE THREAD

**Issue by JennLo23** [bromite/bromite#593]
### Is your feature request related to privacy?

Yes as having search suggestions enhances the incognito experience with negligible detriment to privacy.

### Is there a patch available for this feature somewhere?

Sorry I don't know.

### Describe the solution you would like

I would like to be able to have search suggestions in the address bar while in incognito mode as an option, if not as the default behaviour. Perhaps a UI toggle under Privacy or a flag.

### Describe alternatives you have considered

I can take the extra step of opening the search engine website directly but this doesn't solve the reduced functionality issue which the incognito address bar has compared to that of ordinary browsing.

**Comment by csagan5** [comment]
> negligible detriment to privacy.

Opinions differ.

I have looked into how this works, it does not seem easy to enable this feature. I would not know how anyways and Chromium must have reasons to not allow it; the code already expects that suggestions do not happen in incognito mode so it would be difficult to make sure all that code is incognito-compatible.

Feel free to submit a patch if you manage to do this right, but I have no intention to work on this feature.
