### ISSUE TITLE
Selecting Google as the search engine changes the address

### ISSUE THREAD

**Issue by den43** [bromite/bromite#595]
### Bromite version

Version: 83.0.4103.76
Arch: arm64
Android version: 10
Device model: Pixel 3a

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No (Checked Chromium version 83.0.4103.76)

### Is the bug a crash?

No

### Describe the bug

When you change the search engine in Bromite to Google, the address changes to "9oo91e.qjz9zk"

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to Settings
2. Click on Search engine
3. Select Google

### Expected behaviour

The listed address should not change.

### Screenshots
![Screenshot_20200524-155553](https://user-images.githubusercontent.com/47192034/82757368-f6101500-9dd7-11ea-9403-e140e27a6abb.png)

**Comment by csagan5** [comment]
It's a problem with the automated domain substitution; will be fixed in next release.

**Comment by csagan5** [comment]
Fixed in `83.0.4103.93`.

**Comment by brizaldi** [comment]
This is still happening in `v88.0.4324.207`

**Comment by csagan5** [comment]
@brizaldi that is not the latest version.

**Comment by brizaldi** [comment]
hmm, my bad, somehow f-droid not automatically updating, it's fixed after updating bromite manually
