### ISSUE TITLE
Youtube video does not fit to screen in landscape mode .

### ISSUE THREAD

**Issue by Rohan-ult** [bromite/bromite#596]
### Bromite version

Version: `83.0.4103.76`
Arch: `arm`
Android version: (`5.0`)
Device model: ( `MMX-Q391 canvas doodle 4`)

### Is this bug about the SystemWebView?
Yes

### Is the bug reproducible with latest version?
Yes

### Is the bug a crash?
No

### Describe the bug
When I can go to youtube and tap on full screen icons, most of the time video doesn't fit to screen . I have found that same bug using many previous version of bromite web view 84.0.....
Sometimes videos vibrate after paussing video for a while .

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to 'youtube.com'
2. Click on 'any video and click on full screen icon'
3. Pause the video for a while and play the video 

### Expected behavior
You should get 1/4 of screen while playing video . After rotating my phone 180 , it becomes full screen . If you do not get the error , then try with other video . I also dont get 100% of time . Play any video and pause for a while e.g. 1 min , the play again that video . The video should vibrate . If you don't get try again

### Screenshots
![Screenshot_2020-05-25-18-29-42](https://user-images.githubusercontent.com/61697340/82817429-cee04300-9ebe-11ea-8915-1db386229af6.png)

**Comment by csagan5** [comment]
> I have found that same bug using many previous version of bromite web view 84.0...

Please test with the Chromium SystemWebView.
