### ISSUE TITLE
Please add web page dark mode

### ISSUE THREAD

**Issue by rogerxed** [bromite/bromite#597]
Please add web page dark mode like opera browser, dark mode will reduce eye stress.

![Screenshot_20200525-211026](https://user-images.githubusercontent.com/65120278/82827296-5ed8b980-9ecc-11ea-8e0f-7cc5cdd8951e.png)

**Comment by xarantolus** [comment]
When you visit `chrome://flags/`, then search for "dark", you can enable the "Force Dark Mode for Web Contents" option. I really like the "Enabled with selective inversion of non-image elements" mode
