### ISSUE TITLE
Consider blocking "annoyances"

### ISSUE THREAD

**Issue by JennLo23** [bromite/bromite#599]
### Is your feature request related to privacy?

Yes.

### Is there a patch available for this feature somewhere?

The filter lists are already available I believe.
https://fanboy.co.nz/
https://github.com/AdguardTeam/AdguardFilters#adguard-filters

### Describe the solution you would like

I would like for "annoyances" to be blocked which include cookie notifications, terms and conditions notification, newsletter spam etc. In uBlock Origin there are a few lists available such as Fanboy's Annoyances and AdGuard Annoyances. Personally I select both however I'm not sure of best practice in this regard so I would like for this matter to be considered.

### Describe alternatives you have considered

Firefox with Ublock Origin.

**Comment by den43** [comment]
You can already make a custom filter list for yourself:
https://www.bromite.org/custom-filters

**Comment by csagan5** [comment]
Both have been included in the past and either were causing some issue or were not fully working as expected because the subresources filter format does not cover CSS rules.

**Comment by BUAWF** [comment]
> Both have been included in the past and either were causing some issue or were not fully working as expected because the subresources filter format does not cover CSS rules.

Csagan5, try with :-

a. uBlock Annoyances only
b. Adguard Annoyanes only
c. Adguard Annoyances + Adguard Social 
    (there was a cookie notification, when using only adguard annoyances, it doesn't work. When I select both Adguard's Annoyances + Social it works by blocking that notification. Adguard has mentioned that it works by both selecting & doesn't duplicate filters)

d. All the above.

Check in any of the case (a, b, c, or d) it covers CSS.
