### ISSUE TITLE
[question] Chromium as WebView provider

### ISSUE THREAD

**Issue by dimqua** [bromite/bromite#6]
As you may know, Android 7 "Nougat" users [can use](http://opengapps.org/blog/post/2016/10/06/nougat-webview/) Chrome (including beta, dev and canary) builds as relacment for system webview. I'm curious, is it possible to use custom Chromium build that way? I mean, without applying patches to AOSP codebase.

**Comment by csagan5** [comment]
Well, the answer is right there in the link you posted:
> For ROM developers it is a necessity to include a list of valid WebView Providers in the framework config to expose all possible WebView Providers.

So without ROM patches, no it's not possible.
