### ISSUE TITLE
Startpage no longer available

### ISSUE THREAD

**Issue by albertheres** [bromite/bromite#600]
I notice that startpage is no longer available as search engine. It's also not available after visiting startpage.com. In the changelog I notice that startpage was removed from version 79.0.3945.94. My question is: is there a quick fix to make startpage as default search engine again?

**Comment by sorryusernameisalreadytaken** [comment]
You can add startpage.com, see [here](https://github.com/bromite/bromite/issues/435#issuecomment-1007228859).
