### ISSUE TITLE
DuckDuckGo issues

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bromite/bromite#601]
### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

I would like DuckDuckGo to be removed from Bromite. There is a [Lemmy post](https://dev.lemmy.ml/post/31321) about DDG abusing users' privacy

### Describe alternatives you have considered

Setting Qwant as the default search engine

EDIT: I wasn't really sure where to put it, so I decided to write it in the "Feature Request" section. Just wanted to let you guys know that what DDG is doing is really bad

**Comment by csagan5** [comment]
I cannot comment on each statement from that post but I do know why DuckDuckGo is in Bromite: it is one of the search engines in Chromium. The only related patch in Bromite adds the lite version.

If we were to remove this search engine we would also have to remove Google and all the others.

It is left up to the user to do the homework and pick a search engine, there can be no expectation that each of the available search engines are privacy-safe.
