### ISSUE TITLE
SearX search engine will not add in Bromite

### ISSUE THREAD

**Issue by taminaru** [bromite/bromite#602]
### Bromite version
Version: 83.0.4103.76
Arch: arm64
Android version: 10.0
Device model: Xiaomi Redmi Note 5 (whyred) 

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
Yes

### Is the bug a crash?
No

### Describe the bug
Alternative search engines can be added in Bromite as long as they use OpenSearch, SearX uses OpenSearch but cannot be added in Bromite.

Proof as to SearX using OpenSearch: [here](https://github.com/asciimoo/searx/search?q=opensearch&unscoped_q=opensearch)

### Steps to reproduce the bug
1. Go to any SearX instance.
2. Search anything using that instance.
3. Go to Settings > Search engine > look in 'Recently visited', and the instance will not appear.

### Expected behavior
SearX search engine is added.

### Screenshots
![image](https://matrix-client.matrix.org/_matrix/media/r0/thumbnail/chat.endl.site/BeeVszBQqaQZmvSmcgWcLspA?width=800&height=600)

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> Yes

It is not a Bromite bug; search the issue tracker for more information.
