### ISSUE TITLE
Startpage.com as available search engine

### ISSUE THREAD

**Issue by albertheres** [bromite/bromite#604]
### Is your feature request related to privacy?

Sure, startpage.com is a very privacy friendly search engine

### Is there a patch available for this feature somewhere?

I think yes, because startpage.com was included in bromite/chromium before. 

### Describe the solution you would like

I would like to have startpage.com as available search engine in bromite

### Describe alternatives you have considered

I tried Brave browser which has startpage.com as available search engine. But I prefer to use bromite

**Comment by csagan5** [comment]
Search the issue tracker before creating new issues.

**Comment by sorryusernameisalreadytaken** [comment]
You can add startpage.com, see [here](https://github.com/bromite/bromite/issues/435#issuecomment-1007228859).
