### ISSUE TITLE
Add a Privacy Policy

### ISSUE THREAD

**Issue by PEPERSO** [bromite/bromite#605]
Hello,

I've recently noticed that my browser tried to reach www.bromite.org while I was not going on that website. Could you please add a Privacy policy to your website / github project, so that we know what data you collect ? 

Thanks, and thanks for your work !

**Comment by csagan5** [comment]
@PEPERSO all issues must follow the issue template, but your question can be of general use so I will reply.

In a fresh Bromite install there can be only two reasons for connections to the Bromite website:
* the icons in the New Tab Page, so if you remove them this possibility is gone
* the AdBlock updates, see https://github.com/bromite/bromite/wiki/AdBlocking#update-mechanism; change the URL in settings and this is also gone

In both cases the browser contacts the official Bromite website which is hosted via GitHub pages, so I do not have access to any information about visitors but GitHub does.

See https://help.github.com/en/github/site-policy/github-privacy-statement#github-pages

> GitHub may collect User Personal Information from visitors to your GitHub Pages website, including logs of visitor IP addresses, to comply with legal obligations, and to maintain the security and integrity of the Website and the Service.

The Bromite website is static and there are no Javascript-initiated connections to any server (see for yourself here: https://github.com/bromite/bromite.github.io), thus no data collection is happening except the one mentioned above by GitHub themselves.

**Comment by PEPERSO** [comment]
Sorry for the issue template, and thanks for your answer, it is very clear

**Comment by csagan5** [comment]
Privacy policy added: https://www.bromite.org/privacy

Although it's difficult to get this right, I thought it will hopefully be sufficient in this form.

**Comment by PEPERSO** [comment]
Thanks for the update ! Maybe you should add what you explained me in your previous comment, like in a section Bromite app, following Bromite website and bromite f-droid repo, to be clear about the app itself.

Thanks anyway :)

**Comment by PEPERSO** [comment]
Thanks for the update ! Maybe you should add what you explained me in your previous comment, like in a section Bromite app, following Bromite website and bromite f-droid repo, to be clear about the app itself.

Thanks anyway :)

**Comment by PEPERSO** [comment]
Thanks for the update ! Maybe you should add what you explained me in your previous comment, like in a section Bromite app, following Bromite website and bromite f-droid repo, to be clear about the app itself.

Thanks anyway :)

**Comment by PEPERSO** [comment]
Thanks for the update ! Maybe you should add what you explained me in your previous comment, like in a section Bromite app, following Bromite website and bromite f-droid repo, to be clear about the app itself.

Thanks anyway :)

**Comment by PEPERSO** [comment]
Thanks for the update ! Maybe you should add what you explained me in your previous comment, like in a section Bromite app, following Bromite website and bromite f-droid repo, to be clear about the app itself.

Thanks anyway :)

**Comment by PEPERSO** [comment]
Thanks for the update ! Maybe you should add what you explained me in your previous comment, like in a section Bromite app, following Bromite website and bromite f-droid repo, to be clear about the app itself.

Thanks anyway :)

**Comment by PEPERSO** [comment]
Thanks for the update ! Maybe you should add what you explained me in your previous comment, like in a section Bromite app, following Bromite website and bromite f-droid repo, to be clear about the app itself.

Thanks anyway :)

**Comment by PEPERSO** [comment]
Thanks for the update ! Maybe you should add what you explained me in your previous comment, like in a section Bromite app, following Bromite website and bromite f-droid repo, to be clear about the app itself.

Thanks anyway :)

**Comment by PEPERSO** [comment]
Thanks for the update ! Maybe you should add what you explained me in your previous comment, like in a section Bromite app, following Bromite website and bromite f-droid repo, to be clear about the app itself.

Thanks anyway :)

**Comment by PEPERSO** [comment]
Thanks for the update ! Maybe you should add what you explained me in your previous comment, like in a section Bromite app, following Bromite website and bromite f-droid repo, to be clear about the app itself.

Thanks anyway :)

**Comment by PEPERSO** [comment]
Thanks for the update ! Maybe you should add what you explained me in your previous comment, like in a section Bromite app, following Bromite website and bromite f-droid repo, to be clear about the app itself.

Thanks anyway :)

**Comment by PEPERSO** [comment]
Thanks for the update ! Maybe you should add what you explained me in your previous comment, like in a section Bromite app, following Bromite website and bromite f-droid repo, to be clear about the app itself.

Thanks anyway :)

**Comment by PEPERSO** [comment]
Thanks for the update ! Maybe you should add what you explained me in your previous comment, like in a section Bromite app, following Bromite website and bromite f-droid repo, to be clear about the app itself.

Thanks anyway :)

**Comment by PEPERSO** [comment]
Thanks for the update ! Maybe you should add what you explained me in your previous comment, like in a section Bromite app, following Bromite website and bromite f-droid repo, to be clear about the app itself.

Thanks anyway :)

**Comment by csagan5** [comment]
That will be covered by #691
