### ISSUE TITLE
Handles to reorder bookmarks do not appear

### ISSUE THREAD

**Issue by Poopooracoocoo** [bromite/bromite#606]
### Bromite version

Version: 83.0.4103.76
Arch: arm
Android version: 6.0
Device model: SM-G900I

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is the bug a crash?

No

### Describe the bug

When you're selecting bookmarks, the menu buttons beside bookmarks are greyed out instead of being replaced by handles to drag so you can reorder them. Instead you can move bookmarks one by one by tapping on the menu (when not in selection mode) and can move them up or down. I do not have any accessibility services enabled.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Open bookmarks page
2. Click on mobile bookmarks
3. Tap and hold to select one bookmark

### Expected behavior

Handles replace the menu buttons beside bookmarks

### Screenshots

![bromite screenshot](https://user-images.githubusercontent.com/51363864/83263735-6537a000-a202-11ea-9818-04f03572f355.png)

**Comment by Poopooracoocoo** [comment]
This is really strange. I was really convinced that this was the behaviour upstream until I tried it.

**Comment by csagan5** [comment]
I cannot reproduce this issue, I see the handles correctly.

**Comment by Poopooracoocoo** [comment]
@csagan5 any ideas on what might fix it?

**Comment by csagan5** [comment]
Not really; you said it's not reproducible with Chromium so you cannot ask to other Chromium users either.

**Comment by Poopooracoocoo** [comment]
>so you cannot ask to other Chromium users either.

What do you mean? Are you saying that Bromite doesn't change anything to do with the bookmark reordering?

By the way, I tried enabling #enable-bookmark-reorder in chrome://flags and also tried disabling it and also tried default. They all had the same effect: not allowing me to reorder my bookmarks :/

**Comment by csagan5** [comment]
There are no patches related to bookmarks reordering.
