### ISSUE TITLE
Cert for fdroid.bromite.org is invalid/ expired

### ISSUE THREAD

**Issue by beerisgood** [bromite/bromite#607]
Your repository can't be added and used in AuroraDroid / F-Droid with this bug.
see https://www.ssllabs.com/ssltest/analyze.html?d=fdroid.bromite.org

> Warning: Inconsistent server configuration
> 
Server _2604:5040:11:6f7:0:0:0:4e2a_
Valid until | Fri, 29 May 2020 07:09:18 UTC (expired 1 day, 6 hours ago)   EXPIRED
-- | --

Server _69.51.23.180_

Valid until | Fri, 29 May 2020 07:09:18 UTC (expired 1 day, 6 hours ago)   EXPIRED
-- | --

**Comment by csagan5** [comment]
Issue is now resolved, thanks.

**Comment by beerisgood** [comment]
Confirm.
Thanks for the very fast fix!

**Comment by Asbesbopispa** [comment]
I'm having problems with the F-Droid repo too: https://fdroid.bromite.org/fdroid/repo
![Screenshot_20200603-232246_Bromite](https://user-images.githubusercontent.com/31346754/83690516-2d10d280-a5f1-11ea-8285-dc711fc21022.png)

Is it related?

**Comment by csagan5** [comment]
@Asbesbopispa it's not a website to browse, you have to use it through the F-Droid client.

**Comment by Asbesbopispa** [comment]
Ops, forgot to write that the repo disappeared from my F-Droid client and I tried to go directly to the website without trying to add it again. I just added it and it works, sorry for the stupid mistake
