### ISSUE TITLE
DNS Leaks although using SOCKS5 proxy

### ISSUE THREAD

**Issue by cs-nero** [bromite/bromite#614]
Version: `83.0.4103.93
Arch: x86
Android version: 7
Device model: Redmi 5 plus

Is this bug about the SystemWebView?
No

Is the bug reproducible with latest version?
Yes

Can the bug be reproduced with corresponding Chromium version?
No

Is the bug a crash?
No

Describe the bug
I use SOCKS5 tor as proxy server, but the DNS is still my local one. 

Steps to reproduce the bug:
1. Setup a SOCKS5 proxy in the bromite settings. 
2. Go to https://www.dnsleaktest.com and make an extended test.
3. See results.

**Comment by csagan5** [comment]
> Can the bug be reproduced with corresponding Chromium version?
> No

Are you sure? You have tested with Chromium `83.0.4103.93`?

**Comment by cs-nero** [comment]
Bromite version 83.0.4103.93.

**Comment by cs-nero** [comment]
I did not test it, because not much chromium browsers that I know have a config for proxies. It could be that Bromite just needs a support for remote DNS

**Comment by csagan5** [comment]
I have performed this test (with DoH disabled) and there is no leakage.

> I did not test it

Your bug report says that you tested it; it should be possible to test by passing command line options on Android, see https://www.chromium.org/developers/design-documents/network-settings#TOC-Command-line-options-for-proxy-settings
