### ISSUE TITLE
Bromite Search widget does not work when Bromite is closed

### ISSUE THREAD

**Issue by odirf1** [bromite/bromite#615]
### Bromite version

Version: `83.0.4103.46`
Arch: `arm64`
Android version: `10`
Device model: `SNE-LX1`)

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No, this bug only occurred in bromite.

### Describe the bug

If Bromite is closed but I want to use the Bromite search widget, Bromite will not open so that I can search for something.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Stop bromite
2. Click on the widget's search bar
4. See error - Bromite does not open

### Expected behavior

I would expect bromite to open up so I can look for something.

**Comment by basimaslamts** [comment]
It works now. So close ur issue. Thank u
