### ISSUE TITLE
Certificate errors look wrong

### ISSUE THREAD

**Issue by Madis0** [bromite/bromite#618]
### Bromite version

Version: `83.0.4103.93`
Arch: `arm64`
Android version: `10`
Device model: `ONEPLUS A5010`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug
Certificate errors don't look the same as in Chromium and hence provide less information about the problem (except for the error code, which is the same). Also due to the generic error page in Bromite, the error cannot be overridden.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to https://expired.badssl.com/
2. See error

### Expected behavior
Chromium error page

### Screenshots

![Screenshot_20200610-105013](https://user-images.githubusercontent.com/8611110/84242014-eb0ff100-ab08-11ea-94b0-f99cca17dc3e.jpg)
![Screenshot_20200610-105049](https://user-images.githubusercontent.com/8611110/84242040-ef3c0e80-ab08-11ea-8974-0c295e03424a.jpg)

**Comment by Disqu3-mirOir-qt** [comment]
not bromite issue, this issue become webmaster website forgot renew certificat

**Comment by Madis0** [comment]
The issue is about the error itself, which looks different compared to Chromium. The fact that the cert is wrong intended anyway (badssl.com is for testing such things).

**Comment by csagan5** [comment]
I am closing this in favour of #638, they are the same bug and that one describes an issue with a bigger impact.
