### ISSUE TITLE
Suggestion: do not pause video when app goes to background

### ISSUE THREAD

**Issue by danban359** [bromite/bromite#62]
Please. 
You'll be the god sent saviour of the #nogapps community, become rich and rule the interwebs.

**Comment by Primokorn** [comment]
Not related to privacy...

**Comment by csagan5** [comment]
@danban359 you have to unpause it and then it keeps playing in background. The hack works only for Youtube and Vimeo.

**Comment by DragoCubed** [comment]
It sort of is related to privacy. Privacy and Google don't go together. Google blocks playing in the background in this way to make people use the YouTube app and to get YouTube Red. Google does it for their own benefit.

**Comment by csagan5** [comment]
The feature is already there.

**Comment by DragoCubed** [comment]
but that's just a workaround...
