### ISSUE TITLE
WebRTC Device ID Blocking

### ISSUE THREAD

**Issue by DirtyAngelica** [bromite/bromite#620]

**Comment by DirtyAngelica** [comment]
Huge thanks for your hard work! I noticed that Bromite fingerprinting test page is not as robust as BowserLeaks page, which shows that Bromite leaks WebRTC Device ID's and WebRTC capabilities. Firefox has flags to disable that on both Windows desktop and Android mobile platforms, but Chromium does not. For desktop versions of Chromium only extensions (like WebRTC Leak Protection) can block WebRTC Device ID recognition, but Android Chromium platform does not support extensions. It would be great if Bromite could hide WebRTC Device ID's.

**Comment by csagan5** [comment]
@DirtyAngelica please fill-in the issue template, or submit a new issue with the template filled-in.

**Comment by DirtyAngelica** [comment]
I just did! I hope it helped!

**Comment by csagan5** [comment]
There is no leak, the device IDs are regenerated every time the page is loaded.

**Comment by DirtyAngelica** [comment]
I didn't notice that... Was regeneration of ID's something Bromite implemented or is that a default method for Chromium?
