### ISSUE TITLE
automatic connections in Bromite

### ISSUE THREAD

**Issue by cronos1998** [bromite/bromite#623]
Hi,

I have some questions about automatic connections in Bromite.

- sometimes Bromite connects to fastly.com as well as to any-in-201b.1e100.net (the second one is said to be hosted by Google). What purpose do these connections serve? Is there a way to disable them?

- I suppose the connections to 185.199.109.153 and to 185.199.110.153 on startup are for downloading filter lists (or something like that) in order to block ads/trackers. Is this correct?

Thanks

**Comment by csagan5** [comment]
Sorry, you need to follow the issue template; the issue template also suggests to search first.
