### ISSUE TITLE
request feature

### ISSUE THREAD

**Issue by atuolol** [bromite/bromite#626]
a request for added javascript and adblock menu option, back like on very previous version.

because for browsing is very hard without these menu option when accessing annoying website. i updated app into latest version anytime but it seem there nothing. or at least i pray for a miracle but still doesn't change anything at all.

i had no clue how to attach the gone menu option again by myself. i know i'm so damn annoying but i so desperate because for using other these menu option with other way is i need to open the settings > site setting > block javascript. and to allow i have do the same thing anytime. and if i made mistake tap the wrong button i have to tap back and back button again and i have to swipe and find the site setting again.

**Comment by LukeOwlclaw** [comment]
@atuolol this is the same as https://github.com/bromite/bromite/issues/562, right?
