### ISSUE TITLE
Re-add Startpage.com

### ISSUE THREAD

**Issue by UnmetPlayer** [bromite/bromite#628]
### Is your feature request related to privacy?
Yes

### Is there a patch available for this feature somewhere?
Yes

### Describe the solution you would like
Re-adding Startpage.com, it's been re-added to privacytools.io, so I think it should be re-added back to Bromite.

**Comment by Hillmanae** [comment]
I agree. We would be grateful to have it back.

**Comment by UnmetPlayer** [comment]
> 
> 
> I agree. We would be grateful to have it back.

Unfortunately this issue has been closed with not feedback or reason why. So thats cool.

**Comment by csagan5** [comment]
@UnmetPlayer 

```
<!-- Welcome! Thanks for taking time to submit a feature request.
Have you searched the issue tracker? https://github.com/bromite/bromite/issues
Have you read the F.A.Q.s? https://github.com/bromite/bromite/blob/master/FAQ.md
Have you read the README? https://github.com/bromite/bromite/blob/master/README.md
-->
```

**Comment by sorryusernameisalreadytaken** [comment]
You can add startpage.com, see [here](https://github.com/bromite/bromite/issues/435#issuecomment-1007228859).
