### ISSUE TITLE
Error importing old cookies

### ISSUE THREAD

**Issue by JonnyTech** [bromite/bromite#629]
### Bromite version

Version: `83.0.4103.119`
Arch: `arm`
Android version: `10.0`
Device model: `Xiaomi Redmi Go`
SystemWebView? Yes

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Update to 83.0.4103.119
2. Launch [WebApps](https://github.com/tobykurien/webapps) 
3. Select any link
4. See error image

### Expected behavior

Link site should launch

Rebooting does not fix.
Downgrading to previous version is ok.

### Screenshots

![img_1](https://user-images.githubusercontent.com/3584732/85888778-276a6f00-b7e2-11ea-943f-dc5285743f14.jpg)

**Comment by csagan5** [comment]
These are issues due to the installation of the SystemWebView, there is no bug to fix.
