### ISSUE TITLE
Add a translator

### ISSUE THREAD

**Issue by souvikhazra80** [bromite/bromite#63]
Need a inbuilt translator for Bromite.

**Comment by csagan5** [comment]
Sorry, I will not add a translator

**Comment by souvikhazra80** [comment]
OK.NP

**Comment by gmankab** [comment]
if you add translator, i will switch from brave to bromite

**Comment by Universalizer** [comment]
It may require and activate `google apis.com or apis google.com` (probably proprietory libraries) and also interference following user's browser activities that may violate user's privacy, and start user profiling.

For this reason, csagan5 had excellently removed G play integration, binary blobs, G cloud messaging (GCM)

The general query, do we still require such features like "translation integration ❓" at the cost of what to say ?

**Comment by gmankab** [comment]
brave, desktop chromium, and telegram are opensource apps, and they have built-in translator

it's not necessary to use google translate, there are many other translators

**Comment by Universalizer** [comment]
@gmankab, good information catch,

Case that might matter here for 'Outside scope software's translation libraries' :

If Fully Free and Open Source in public domain, (NO trademark's issue),

And License compatibility with Bromite's GNU GPL v3,

Doubt and query : But, still it may, constantly ping their backend servers❓, probably and possibly giving hints of web surfing activities of a `specific or particular User's Real IP address or location`❓

Ultimate decision relies upon, Bromite's project choice and will.

**Comment by Universalizer** [comment]
**@gmankab, Other Alternative Method,**

you can save page for offline

and later 'either' :- 1) share or 2) 'copy/paste text' to your target translation application, available and installed from F-Droid.

Though it may be slightly manual procedure method, but still that will be simply secure privacy.

**Comment by gmankab** [comment]
@Universalizer, too hard
