### ISSUE TITLE
Bromite/Vanadium collaboration

### ISSUE THREAD

**Issue by theaeonsolution** [bromite/bromite#634]
Hi @csagan5, hope you are well! Is there an official way to communicate/collaborate with the Bromite developers. I've been working and studying the Chromium code and docs to help contribute to Vanadium and would also really like to cross-contribute to Bromite. I'm really excited about the work both projects do. Thank you.

**Comment by csagan5** [comment]
@theaeonsolution the official way is to submit patches here; I have been working on it mostly alone and I review and accept PRs as they come in.

You can PM me on Reddit or XDA, but if you want to make a submission we can discuss it publicly on the PR here on GitHub.

**Comment by theaeonsolution** [comment]
Great, thank you for the feedback.
