### ISSUE TITLE
Rsync endpoint for mirroring your fdroid repo

### ISSUE THREAD

**Issue by aelisya** [bromite/bromite#636]
### Is your feature request related to privacy?
Yes, its related to help third party repository to distribute your release (with a mirror) and so help more people to use your privacy feature.

### Is there a patch available for this feature somewhere?
No patch it's a server implementation of rsync endpoint

### Describe the solution you would like
I would like a rsync endpoint of your fdroid repository for mirroring your repo.

**Comment by csagan5** [comment]
There is no rsync endpoint available, you can mirror it using the F-Droid index files.

See also: https://pypi.org/project/fdroid-dl/
