### ISSUE TITLE
Set Minimum TLS Version

### ISSUE THREAD

**Issue by DirtyAngelica** [bromite/bromite#637]
Yes, Yes, Yes

### Is your feature request related to privacy?
Yes (better security usually means better privacy)

### Is there a patch available for this feature somewhere?
On Windows OS, Chrome can enforce minimum TLS via shortcut command "--ssl-version-min=tlsX" where X is the TLS version

### Describe the solution you would like
Bromite flag or Bromite Setting that acts like the "--ssl-version-min=tlsX" 

### Describe alternatives you have considered
Another browser

**Comment by csagan5** [comment]
The minimum TLS version is already set.

**Comment by DirtyAngelica** [comment]
It is set to 1.0 based on browserleaks.com test. 1.0 is not secure. We should have the option to change it to 1.2. Firefox now sets 1.2 as minimum.

**Comment by csagan5** [comment]
The minimum version is already set to 1.2.

**Comment by csagan5** [comment]
Duplicate of #645
