### ISSUE TITLE
Impossible to bypass SSL Error

### ISSUE THREAD

**Issue by i-rme** [bromite/bromite#638]
### Bromite version 

Version: `83.0.4102.93`
Arch: `arm64`
Android version: 10.0
Device model: POCO F1

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug
As we know, browsers validate HTTPS certificates (also called SSL/TLS certs), if they fail (self signed, expired, etc) a message is shown with a button to bypass the validation and proceed.

This is VERY USEFUL because some devices like routers have self signed certificates and if you dont ignore the error you cannot access the web panel.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to https://self-signed.badssl.com/
2. Try to bypass the SSL error
3. No way to do it

### Expected behavior
A button like on Chrome that says "Ignore this warning, proceed" that lets you access the website properly.

### Screenshots
![image](https://user-images.githubusercontent.com/6007737/86837926-e3a81d00-c09f-11ea-8e60-91d1df6328de.png)
Bromite: No way to skip the error

![image](https://user-images.githubusercontent.com/6007737/86838041-01758200-c0a0-11ea-9fb7-da59db9a8382.png)
Chrome: There is a button to skip the warning

![image](https://user-images.githubusercontent.com/6007737/86838126-194d0600-c0a0-11ea-9229-0f98417a9bd8.png)
Chrome: There is a two step proccess, this link finally ignores the warning and lets you use the website.

This is needed because they are multiple bad configured websites, self signed and routers that REQUIRE this functionality.

**Comment by csagan5** [comment]
I think this is the same bug as #618

**Comment by csagan5** [comment]
Fixed in `84.0.4147.90`.

**Comment by i-rme** [comment]
Oh god, it works as a charm.

Let's take a moment to appreciate our open source developers that make Bromite (and so much other software) possible.

**THANK YOU VERY MUCH**

**Comment by caio-vinicius** [comment]
Thank you so much guys.
