### ISSUE TITLE
Could Bromite Browser work atop another webview implementation?

### ISSUE THREAD

**Issue by persmule** [bromite/bromite#642]
**Is your feature request related to privacy?**
Νο

**Is there a patch available for this feature somewhere?**
Unfortunately No

**Describe the solution you'd like**
Does the current Bromite Browser bundled or statically linked with a webview implementation (e.g. Bromite System Webview)? Could Bromite Browser be configured, or built (without bundled with a webview implementation) to work atop the current system webview?

Actually, I am curious about the possibility to run Bromite Browser atop the Vanadium System Webview shipped with GrapheneOS, in order to combine features of the two.

**Comment by csagan5** [comment]
You have some confusion about pretty much everything you mentioned, I suggest to get more familiar with Chromium and then most of your doubts will be cleared out.
