### ISSUE TITLE
DNS-over-HTTPS (DoH) is not working

### ISSUE THREAD

**Issue by Sterilize** [bromite/bromite#643]
Bromite version

Version: 83.0.4103.101
Arch: x64
Android version: 8.1.0 Oreo

Is the bug reproducible with latest version?
Yes

Can the bug be reproduced with corresponding Chromium version?
No

Is the bug a crash?
No

Describe the bug
DoH does not work, I've tried with the adguards dns , and then testing in adguards test page, does not work.

it seems that by putting twice the adguards' doh url(space seperates between the urls) adguard dns does work, weird..

btw for csagan, I wanted to note you that by disabling receivers (I did it through sdmaid) bromite doesnt lose any functionality, in fact it runs more smoothly. (only widgets are not functioning)

**Comment by fromxt** [comment]
I also ran across the same issue on the latest version. It didn't work from time to time.

**Comment by csagan5** [comment]
It might be an internal update bug; please test with latest `84.0.4147.90`, it is working in my tests.
