### ISSUE TITLE
Last closed tab reappears

### ISSUE THREAD

**Issue by sphh** [bromite/bromite#644]
### Bromite version

Version: `83.0.4103.119`
Arch: `arm` (?)
Android version: `8.1.0`
Device model: `Unihertz Jelly Pro`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
?

### Is the bug a crash?
No

### Describe the bug
When I don't close `Bromite`, but just put it into the background, the last closed tab reappears when re-activating `Bromite`.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Open `Bromite`
2. Close the last tab
3. Get another app into the foreground
4. After some time reactivate `Bromite`
5. The last closed tab will be appended to the list of tabs and reloaded

### Expected behavior
The last closed tab should not re-appear.

### Screenshots
n.a.

**Comment by aluo-x** [comment]
I also encountered this issue. But only once, where one tab repeatedly reappeared after reopening bromite. Disappeared after I stopped bromite fully.
