### ISSUE TITLE
No websites will load

### ISSUE THREAD

**Issue by Someguy1519** [bromite/bromite#646]
### Version: 
84.0.4147.90
### Arch: 
arm64
### Android version: 
9.0
### Device model: 
SM-G955U1

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version? 
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug

I get "This site can't be reached" for every website I try to visit on Bromite
No websites will load on Bromite. They load just fine when I load them on another browser.

### Steps to reproduce the bug:
1. Open Bromite
2. Try to load any website
3. 
4.

### Expected behavior

Websites load with no error message

### Screenshots

![Screenshot_20200716-160612_Bromite](https://user-images.githubusercontent.com/27980228/87732880-efbc6a80-c782-11ea-9a77-eea16c351677.jpg)

**Comment by cimarronline** [comment]
Same for me, with Android 8 and ARM.

**Comment by aliglelo** [comment]
same for me , with Android 10.

**Comment by Jeddix** [comment]
As a workaround you can disable Secure DNS and the pages will load again.

**Comment by Sujan319** [comment]
Yes there is by default secure DNS on.so you need to disable it.or (for android<10)if u use DNS put provider template url.In the case of android 10 ,we have private DNS in system ,so better turn off that secure dns on browser.

**Comment by csagan5** [comment]
Will be fixed when `84.0.4147.95` is released.
