### ISSUE TITLE
Adding a built-in tracker blocker

### ISSUE THREAD

**Issue by Sujan319** [bromite/bromite#647]
### Is your feature request related to privacy?
-->Yes .

### Is there a patch available for this feature somewhere?
-->I think so.the link for this given below.
-->https://github.com/duckduckgo/duckduckgo-privacy-extension
### Describe the solution you would like
-->built-in tracker blocker.thats it.

### Describe alternatives you have considered
-->Want highly private features for blocking tracker & other hiding privacy-unfriendly features if available other than this.

**Comment by csagan5** [comment]
See https://github.com/bromite/bromite#filters-credits
