### ISSUE TITLE
Cant block ads on YouTube and its subdomain

### ISSUE THREAD

**Issue by indahud** [bromite/bromite#648]
### Bromite version

Version: `84.0.4147.95`
Arch: `arm64`
Android version: `10.0`
Device model:  `TA-1083`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
Yes

### Is the bug a crash?
No

### Describe the bug
Can't block video as well as banner ads on https://youtube.com and its subdomain.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to 'https://music.youtube.com'
2. Play any song
3. See the ads

**Comment by csagan5** [comment]
I cannot reproduce this.

**Comment by indahud** [comment]
I don't know why you can't reproduce this. Here's screenshot
![Screenshot_20200718-020310](https://user-images.githubusercontent.com/47686324/88143591-1cee9a00-cc15-11ea-8251-31c8307f5207.png)

**Comment by Sujan319** [comment]
I'm also not able to reproduce this.please check if the adblock settings is turn on.reset the custom url to default.if that didn't work unistall & reinstall it.

**Comment by indahud** [comment]
This is kind of weird. After fresh installation browser  can block all Google ad sense on many sites including YouTube. But can't block YouTube Music. However in incognito mode ad blocking works.

**Comment by csagan5** [comment]
@indahud you need to connect the device and use remote debugging to see which requests are not blocked, then submit your findings to the EasyList maintainers.

See also: https://developers.google.com/web/tools/chrome-devtools/remote-debugging

It's not a problem with Bromite but possibly in the filters.
