### ISSUE TITLE
Question regarding adblock filter urls

### ISSUE THREAD

**Issue by Sterilize** [bromite/bromite#649]
if I want to add another additional URL, do I just press "space" and paste my desired url after bromites' url?

And if the answer is positive, what is the limit if there is?

Moreover, how do I know what filter lists is by default in the bromite adblocker? I have been able to find the file in github, but can't open it / its' content isn't presented in github due to the size of the file.

**Comment by Sujan319** [comment]
You can do that .but that gonna do nothing.it is one replace by one.however, you can put any filters you want but only the default filter will work.Even if u just turn the adblock on put any adress(even symbols,letters...) on it only the default will work.
