### ISSUE TITLE
Can not install Bromite v84.0.4147.95 - Android v4.4.2

### ISSUE THREAD

**Issue by Ajaja** [bromite/bromite#650]
Android v4.4.2
https://github.com/bromite/bromite/releases/download/84.0.4147.95/arm_ChromePublic.apk
fails to install.

**Comment by Ajaja** [comment]
If KitKat is not supported anymore, please, fix the home page https://www.bromite.org/

**Comment by Sujan319** [comment]
Yes kitkat is not supported.its from lollipop.So better upgrade your age-old android version.if not possible then buy a new one.u will be upgraded directly to android 10🤣🤣 provided the manufacturer of your country catch up with google.

**Comment by Ajaja** [comment]
If it's from lollipop  now, then  this should be changed:

https://www.bromite.org/
Architecture | Android version
ARM | KitKat 4.4 and above (SDK19)

https://github.com/bromite/bromite
Bromite is only available for Android v4.4 and above.

**Comment by Sujan319** [comment]
Yes you're absolutely right.but to use this browser,that change is not enough for 4.4.2(kitkat).

**Comment by csagan5** [comment]
It looks like this was deprecated in M82: https://groups.google.com/a/chromium.org/forum/m/#!topic/chromium-dev/ypAS49lvN1M

I will update the website and README accordingly
