### ISSUE TITLE
Bromite v84.0.4147.95 - Can't Bookmark Websites Anymore

### ISSUE THREAD

**Issue by DecodeRecode** [bromite/bromite#653]
### Bromite version

Version: `Bromite v84.0.4147.95`
Arch: `arm64`
Android version: Android 10
Device model: Google Pixel 2XL

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
N/A

### Is the bug a crash?
NO

### Describe the bug

With the latest Bromite version I've noticed that I can no longer bookmark a website, at all. I tried several websites and the star (bookmark) icon isn't working. I was able to bookmark websites before the latest update.

### Steps to reproduce the bug

Steps to reproduce the bug:
2. Click/tap on 'star icon (bookmark) doesn't get activated'
3. That's it - bookmark doesn't work

### Expected behavior

The expected behavior is to bookmark the website that I am currently viewing.

**Comment by NM-E** [comment]
It works if you disable always Incognito mode in Privacy. But this will force one to keep cookies in order to modify his bookmarks...

**Comment by DecodeRecode** [comment]
Yes, that is true, but I was able to bookmark just fine with the previous version of Bromite. So what changed? I understand that there is a workaround but I am not the only one that bookmarks websites in Incognito mode. If this isn't possible, then I'll just switch back to DDG.

**Comment by DecodeRecode** [comment]
NM-E, I have made the change to my settings in the browser. I understand that if I disable the incognito mode that I will lose some privacy. I'll keep it this way, and disable the incognito mode for now. Thanks.
