### ISSUE TITLE
Bookmark button not working in the latest build

### ISSUE THREAD

**Issue by Gio1422** [bromite/bromite#654]
---
name: Bug report
about: Create a Bromite bug report

---

### Bromite version

Version: `84.0.4147.95`
Arch: `arm64`
Android version: (example: `9.0`)
Device model: (example: `SM-G960UZKABST`)

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug

when the privacy option 'Open links in incognito tabs always' is on and you have restarted the app, bookmarking option isn't available.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to Settings
2. Then Privacy
3. Switch on 'Open links in incognito tabs always'
3. Restart the app
5. Go to any website
4. Open the three dots menu

### Expected behavior

The bookmark button with a star symbol should be clickable

### Screenshots

![Screenshot_2020-07-25-23-11-32-569_org bromite bromite](https://user-images.githubusercontent.com/47062775/88464547-c27f6300-cecc-11ea-96ac-f3a66bca2a2b.jpg)

**Comment by meelten** [comment]
It's a bug in latest version. Disabling and re-enabling "always incognito" makes bookmarking in incognito mode possible again until browser restart.
It was reported already https://github.com/bromite/bromite/issues/653 and @DecodeRecode should re-open it.

**Comment by DecodeRecode** [comment]
Meelten, I've already closed my ticket. Let's keep Gio1422's ticket open instead. I don't see a reason to reopen mine. Thanks!

**Comment by meelten** [comment]
> Meelten, I've already closed my ticket. Let's keep Gio1422's ticket open instead. I don't see a reason to reopen mine. Thanks!

Then @Gio1422 needs to use template or it'll get closed too.

**Comment by Gio1422** [comment]
What template though

**Comment by DecodeRecode** [comment]
Gio1422, the template that Meelten is referring to is the Bromite issue tracking template that is created when you first open an issue. You can either close out this ticket so you can reopen it and hence get the needed template. Or you can edit your initial entry and literally copy the following template into your ticket: https://github.com/bromite/bromite/commit/398a3aa3440a3cf4d44d9bc26e2a2117fa64fe3b and fill-in the requested items under the hash tags.

Thanks!

**Comment by Gio1422** [comment]
Should be ok, right?

**Comment by DecodeRecode** [comment]
Looks great! Thanks!

**Comment by NM-E** [comment]
Still facing this issue even after today's update. I really hope this is a bug and not a feature. I love always Incognito Tabs!

**Comment by Gio1422** [comment]
same. I don't have a reason to keep browsing history.

**Comment by uazo** [comment]
I confirm the bug. as workaround it is necessary to close the first tab and reopen it. I will try to verify the reason.

**Comment by csagan5** [comment]
Fixed in `85.0.4183.82`.
