### ISSUE TITLE
Support Android 4.4

### ISSUE THREAD

**Issue by Skif-off** [bromite/bromite#655]
In README.md:

> Bromite is only available for Android v4.4 and above.

but as I see, two latest releases (84.0.4147.9*) builded with SDK 21, so minimal version is 5.0. Is it mistake or not?

**Comment by wchen342** [comment]
The minimum supported system is 5.0 now. See #650.

**Comment by Skif-off** [comment]
Sorry, I seen opened issues and I forgot to check closed issues :( I will close now.

**Comment by PizzaProgram** [comment]
It is basically impossible to find the "right / last" version available for older Android tablets.
The changelog also lack of these important infos.

Please provide a list on the front page, what bromite version is the LAST for each android version!
4.1 : 8x.yyy.zzz...
4.2 : ...
4.4 : ...
...etc
