### ISSUE TITLE
#About upstreaming the flag which enables dark mode for webcontens on bromite

### ISSUE THREAD

**Issue by Sujan319** [bromite/bromite#656]
### Is your feature request related to privacy?
-->No.but this feature is needed very much for users like me who do night browsing heavily.it will be very much helpful for me if you implement  this.

### Is there a patch available for this feature somewhere?
-->It is in the chrome://flags with the name "force-dark-mode-for-web-contents"

### Describe the solution you would like
-->So there is many options in that particular flags which i'm talking about.but the best which is work for webcontent is "selective inversion of everything".if you make it a option in the dark mode settings with "dark mode for webpages"so that will be great.

### Describe alternatives you have considered
-->I can think of extensions as alternatives but bromite does not support it.
![Screenshot_20200726-220606](https://user-images.githubusercontent.com/67813061/88484861-852fd980-cf8f-11ea-99b5-8ec9a5c1829d.png)
![Screenshot_20200726-220556](https://user-images.githubusercontent.com/67813061/88484882-aa244c80-cf8f-11ea-9d05-19f6f72672e7.png)

**Comment by csagan5** [comment]
You have to submit your bug report or feature request to Chromium.
