### ISSUE TITLE
Javascript/cookie manager

### ISSUE THREAD

**Issue by AzureB1te** [bromite/bromite#658]
### Is your feature request related to privacy?
Yes,quite majorly

### Is there a patch available for this feature somewhere?
Only extensions,but we're still on mobile chromium.

### Describe the solution you would like

Having a UBO/uMatrix style tab in the three-dot menu,would be amazing. Not only we'd get more control,but the whole browser would be less of a pain to use. No offense,Bromite is amazing,and this is really my only issue.
It could also have a matrix style interface,with javascript,cookies,media and maybe css being the options to enable/disable per domain. Blocking domain would also be cool,but at this point I'm really just asking for UBO/uMatrix to get implemented into Bromite. (i knoe it's not possible)

### Describe alternatives you have considered

Getting extension support would be a great alternative.

**Comment by csagan5** [comment]
This has been asked multiple times, it is not possible to embed this in Android. The UI work needed would be massive.
