### ISSUE TITLE
Clean URL's

### ISSUE THREAD

**Issue by grravity** [bromite/bromite#661]
URL Cleaning is a very annoying task to do manually, on Firefox you can use the CleanURL extension, and it is one thing I miss from it.
Tons of links have extra junk, referral codes, tracking parameters and more thrown at the end. It would be very nice to have links cleaned in Bromite. Especially when navigating to a link (say copied an uncleaned link from someone, and went to that site, it'd clean it before making the connection).

**Comment by grravity** [comment]
I wasn't given a template when creating this issue.

**Comment by csagan5** [comment]
@grravity it's a GitHub bug, it gives the template only in desktop mode

**Comment by grravity** [comment]
> missing-issue-template

I fixed the issue with an edit, can we reopen it please?

**Comment by csagan5** [comment]
@grravity this has been asked before, the answer is the same: we cannot embed a complex extension like this in the browser.

**Comment by grravity** [comment]
I'm not asking for adding an extension, I was giving that as an example and saying code from it may be possible. I could be wrong but I thought I've seen some other Chromium based browsers implement link cleaning, Kiwi or Brave maybe? Could be wrong.
