### ISSUE TITLE
[Request] Restore the Duet flag

### ISSUE THREAD

**Issue by Abacate123** [bromite/bromite#667]
### Is your feature request related to privacy?

No, but why not consider this?

### Is there a patch available for this feature somewhere?

Maybe. You already did this with another flag that Google deprecated before, which was the "enable-horizontal-tab-switcher", which you restored in the 79.0.3945.111 version of Bromite (as mentioned [here](https://github.com/bromite/bromite/blob/master/CHANGELOG.md#7903945111)).

### Describe the solution you would like

If possible, to do the same thing as you did with the tab flag, restore the "enable-chrome-duet" flag, which, as you may know now, seems to be [deprecated](https://www.androidpolice.com/2020/07/15/chrome-84/). That flag made possible to reach things easily at the bottom, so I think it'd be interesting to restore it. From an user perspective, why not?

![image](https://user-images.githubusercontent.com/22762343/89134274-35ef2900-d4fa-11ea-976d-6a9ebcb2c58f.png)

### Describe alternatives you have considered

--

**Comment by csagan5** [comment]
I will enable the flags on next release but it's pointless, the code for duet is disappearing from Chromium.

**Comment by Abacate123** [comment]
Ok, didn't know that, that's sad... Thanks anyways.

**Comment by csagan5** [comment]
Fixed in `84.0.4147.119`.

**Comment by marcdw1289** [comment]
Although the flag is restored it seems it's set to a default and can't be changed. In my case anyway.
TabSwitcher-Menu at the top, Home-Search-Share at the bottom.

The first two are most used by me. After chromium v79 the menu got stuck up there but at least the tab switcher could be brought down. Not the case now it seems.

Still, having the flag back is cool I guess.
