### ISSUE TITLE
[Feature Request] Security Enhancements

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [bromite/bromite#668]
### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

Yes. An extension already has some great privacy features. Check it out
https://github.com/jake-cryptic/AbsoluteDoubleTrace

### Describe the solution you would like

 - Current Timezone Spoofing (GMT +0) (Otherwise 
   there is no meaning of using Proxy/VPN)
 - WebGL & Device Model Fingerprinting Protection 
   (Device Model, Vendor remains unmasked)
   https://browserleaks.com/webgl
 - JS Crypto Currency Mining Domain Blocking
 - WebRTC Device Enumeration Protection
 - Screen Resolution Spoofing
 - Battery API Spoofing
 - Network Information API Spoofing
 - Browser Plugin Fingerprinting Protection
 - Hardware Fingerprinting Protection
 - Beacon/'Ping' Request Blocking
 - Blocks Malicious Top Level Domains
 - Hyperlink Auditing Prevention
 - HTTP Referrer Headers Controls
 - Google Header Tracking Controls
 - E-Tag Tracking Mitigation
 - Removal of URL Tracking Parameters

### Describe alternatives you have considered

As extension support is not available so I think these features can be added to enhance privacy

**Comment by csagan5** [comment]
Feel free to submit patches.
