### ISSUE TITLE
Remove 'Data Saver' menu from settings

### ISSUE THREAD

**Issue by AndhikaWB** [bromite/bromite#67]
The title explain it. There is another Chromium fork called "Brave" which has Data Saver feature (and other Google features) removed by default. It is also open source so you can see the code for reference

**Comment by csagan5** [comment]
Good idea! I am going to check there if there are patches we can pick.

About other features: I will consider that also.

**Comment by csagan5** [comment]
I have picked/adapted a few patches that should hide/disable the data saver, signin and translation parts of the UI.

Unfortunately the Brave developers are not keeping one feature-per-patch, so it is a bit difficult to track the functionality.

**Comment by csagan5** [comment]
Useful patches to hide UI elements that we do not need have been applied, for sync/translate/signin.

Fixed in 67.0.3396.88
