### ISSUE TITLE
Dns over Https is useless without Encrypted sni

### ISSUE THREAD

**Issue by Balachandarsmr** [bromite/bromite#670]
Server Name Indication payload is not encrypted, thus the hostname of the server the client tries to connect to is visible to a passive eavesdropper. So your browsing history exposed to ISP. DOH with ESNI unblock censorship.
Chromium don't support esni but Firefox does. None of Chromium browsers play videos in full screen where Firefox can. Firefox is more secure and private than Chromium.  So i switched to Firefox.

**Comment by aliglelo** [comment]
> Server Name Indication payload is not encrypted, thus the hostname of the server the client tries to connect to is visible to a passive eavesdropper. So your browsing history exposed to ISP. DOH with ESNI unblock censorship.
> Chromium don't support esni but Firefox does. None of Chromium browsers play videos in full screen where Firefox can. Firefox is more secure and private than Chromium. So i switched to Firefox.

I tried firefox preview but found it slow and a bit unfriendly for PWAs
