### ISSUE TITLE
How to add my own lists to adblock in bromite?

### ISSUE THREAD

**Issue by MadScientistAK** [bromite/bromite#672]
I tried adding my own lists to the adblocker that bromite uses. But it doesn't seem to work. What is the correct way to add one's own lists? I tried adding the url to the list by separating the links with commas (,) but that did not work.

**Comment by csagan5** [comment]
See https://www.bromite.org/custom-filters

**Comment by MadScientistAK** [comment]
Is there no way to avoid this building process? I just want to add some adguard filters to further block a few ads that have been bugging me. I don't want to install linux or a subsystem to make my own filters and host them somewhere.

**Comment by MadScientistAK** [comment]
I tried the exact same steps that were written there. They just did not work. I got errors like this one: 

(error:2) Unknown URL rule option:
$csp=worker-src 'none',domain=alltube.pl|alltube.tv|animeteatr.ru|annuaire-bleu.net|bigspeeds.com|biter.tv|bypassed.ws|byter.tv|centrum-dramy.pl|cinemafacil.com|clipwatching.com|coinfaucet.eu|coinhub.win|crictime.com|crictime.is|dekoder.ws|deltabit.co|descargas2020.com|estream.to|estream.xyz|filmonet.com|filmstreamvk.site|flashx.cc|flashx.co|flashx.sx|flashx.to|flashx.tv|flashx.ws|hdvid.tv|hentai-online.pl|hqq.watch|ianimes.co|kinokongo.cc|kinostuff.com|lewd.ninja|love-drama.pl|movie4k.is|pebx.pl|potomy.ru|povw1deo.com|powvideo.cc|powvideo.net|proxyportal.eu|reactor.cc|severita-service.ru|sickrage.ca|sorteosrd.com|tomadivx.tv|unblockall.org|unblocked.gdn|vidtodo.com|vidtodo.me|vidtodo.pro|wallpoper.com|wearesaudis.net|ya3ale.com|yazilir.com|zenexplayer.com

**Comment by csagan5** [comment]
> Is there no way to avoid this building process?

There was a web version, but it would not make a difference in your case.



> I tried the exact same steps that were written there. They just did not work. I got errors like this one:

The invalid rules are skipped; Chromium/Bromite support only a subset of the Adblock Plus filters format.
