### ISSUE TITLE
Exit button not working from overview with no tabs open

### ISSUE THREAD

**Issue by pilsnerbeer** [bromite/bromite#673]
### Bromite version

Version: `83.0...` 84.0.4147.119
Arch: `arm` or `arm64` or `x86` arm64
Android version: (example: `9.0`) 10
Device model: (example: `SM-G960UZKABST`) OP5T

### Is this bug about the SystemWebView?
Yes/No na

### Describe the bug

Exit button doesnt work IF there are no tabs open.

![Screenshot_20200806-100348_1](https://user-images.githubusercontent.com/36133540/89515561-97074d00-d7d7-11ea-944a-fb83e120b37f.jpg)

### Steps to reproduce the bug

Steps to reproduce the bug:
1 open bromite
2 ensure there are no tabs open
3 menu->exit
### Expected behavior

bromite should exit but nothing happens.

**Comment by chknatwork** [comment]
Able to reproduce. However, you can still use back button on your mobile to exit browser.

**Comment by pilsnerbeer** [comment]
I believe just pressing BACK won't exit the browser properly, just close it. I use dedicated "exit" button in order to clear cookies and the only way I've found to do this is through this button.

**Comment by elcste** [comment]
I'm getting the same behavior. Before 84.0.4147.106, which has in the changelog "add exit menu item to overview menu (fixes https://github.com/bromite/bromite/issues/619)", there was no exit option in menu in the overview (with no tabs open). As of that version the menu item is there, but it has never worked for me. Exit in the menu in a tab works and has always worked for me.

**Comment by csagan5** [comment]
> As of that version the menu item is there in the overview menu, but it has never worked for me.

This bug is about using `Exit` with no tabs open; when tabs are present, it works.

@uazo maybe you could also check why this happens when no tabs are open? This is the [patch](https://github.com/bromite/bromite/blob/84.0.4147.106/build/patches/Add-exit-menu-item.patch).

**Comment by uazo** [comment]
I think the problem is that it must also be added in ChromeActivity's onMenuOrKeyboardAction. I try and let you know.

**Comment by uazo** [comment]
yes that's it, just add:

![image](https://user-images.githubusercontent.com/29201891/89770267-d1862800-dafe-11ea-8b4d-6d06cbef9e06.png)

now, would you explain me how to modify the patch alone, perhaps with the use of some software?

**Comment by csagan5** [comment]
> now, would you explain me how to modify the patch alone, perhaps with the use of some software?

It's not possible to modify patches alone; you always need to have the checked-out codebase of Chromium.
I use normal git commands but the best would be to use [quilt](https://wiki.debian.org/UsingQuilt).

> I think the problem is that it must also be added in ChromeActivity's onMenuOrKeyboardAction. I try and let you know.

Did you try this? I will try it as well. Does your change explain why it would work with some tab open but not when no tabs are open?

**Comment by uazo** [comment]
> It's not possible to modify patches alone; you always need to have the checked-out codebase of Chromium.

Maybe I've found a way, taking a cue from https://www.electronjs.org/docs/development/patches.
I do some tests and send a pr with some bash scripts.

> Did you try this? I will try it as well.

Yes, it works. 

>  Does your change explain why it would work with some tab open but not when no tabs are open?

Yes, sure. It's because of line 1946:

```
        if (currentTab == null) {
            return false;
        } else if (id == R.id.forward_menu_id) {
```

without tab, code exits before checking.
