### ISSUE TITLE
Build without non-free unrar

### ISSUE THREAD

**Issue by bbigam** [bromite/bromite#674]
### Is your feature request related to privacy?
Indirectly, as a FOSS issue.

### Is there a patch available for this feature somewhere?
Yes, at Ungoogled Chromium, coming from Debian.
https://github.com/Eloston/ungoogled-chromium/blob/master/patches/core/debian/disable/unrar.patch
https://sources.debian.org/patches/chromium/83.0.4103.116-1%7Edeb10u3/disable/unrar.patch/
Sorry, I'm not sure what the license is, but all Debian patches follow the Debian Free Software Guidelines. Probably same license as Chromium itself.

### Describe the solution you would like

Build Bromite with the patch to remove the non-free unrar. My understanding is that unrar is not actually used in Bromite anyway, since Safe Browsing is disabled. It looks like a rather trivial patch, too. It would be another step toward Bromite being fully FOSS, which indirectly helps privacy too.

### Describe alternatives you have considered
None, I'm happy with Bromite, this would just be another great feature.

Apologies if this is not posted correctly... it's my first time!

**Comment by csagan5** [comment]
Safe browsing is disabled already in Bromite, so it would never run, but regardless it's necessary to remove all non-free binaries, as much as possible.

Fixed in `84.0.4147.121`.
