### ISSUE TITLE
About Implementing "Custom Useragent" in bromite

### ISSUE THREAD

**Issue by Sujan319** [bromite/bromite#676]
### Is your feature request related to privacy?
Yes.it actually masks the browser.

### Is there a patch available for this feature somewhere?
Honestly i don't know.

### Describe the solution you would like
I'm taking about Implementing Custom Useragent in such a way that we can add any Useragent string we want manually.if there is some predefined user agent like PC,tablet,ipad etc,then that will be great.

Though i wonder is it possible to implement these features on chromium build.

### Describe alternatives you have considered
Cant think of any alternatives

**Comment by csagan5** [comment]
This has nothing to do with privacy.

**Comment by Sujan319** [comment]
Oh yes you are right except that this feature gives user flexibility of accesing website in desktop /mac mode or ipad/tablet mode or mobile mode as user wants.by the way i forget you have no time for this little things like implementing custom user strings.it seems like i have to install another browser only for this "custom user -string".I want  bromite to be All -in-one browser that fills the need of user who are using it.but it seems that you have no interest at all especially at that aspect.But one thing i want to say,there is no browser like it now ,not was in past ,hopefully(if all goes well) not will be in future.

**Comment by Sujan319** [comment]
> This has nothing to do with privacy.

Oh yes you are right except that this feature gives user flexibility of accesing website in desktop /mac mode or ipad/tablet mode or mobile mode as user wants.by the way i forget you have no time for this little things like implementing custom user strings.it seems like i have to install another browser only for this "custom user -string".I want bromite to be All -in-one browser that fills the need of user who are using it.but it seems that you have no interest at all especially at that aspect.But one thing i want to say,there is no browser like it now ,not was in past ,hopefully(if all goes well) not will be in future.
