### ISSUE TITLE
QUIC is enabled and bypass adblocking

### ISSUE THREAD

**Issue by bromitebestbrowser** [bromite/bromite#677]
### Bromite version

Version: `84.0.4147.121`
Arch: `arm`
Android version: (`6.0`)
Device model: (example: `SM-G960UZKABST`)

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Is the bug a crash?
No

### Describe the bug
QUIC is enabled and ad sometimes bypass adblocking

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to 'youtube'
2. Click on 'reload in the chrome menu'
3. See error
### Expected behavior
Ads shoud not be shown and encryption should be tls 1.3 not QUIC

**Comment by bromitebestbrowser** [comment]
Sorry everyone im not good at en

**Comment by csagan5** [comment]
Please add steps to reproduce the issue.

**Comment by bromitebestbrowser** [comment]
1.Go to 'youtube'
2.Click on 'reload in the chrome menu'
3.See error

**Comment by bromitebestbrowser** [comment]
If i disable QUIC in flags this won't happen however QUIC is enabled by default

**Comment by csagan5** [comment]
@bromitebestbrowser what is the problem? No ads are bypassed with QUIC.
