### ISSUE TITLE
Could not add  proxy as list - proxy configuration

### ISSUE THREAD

**Issue by basimaslamts** [bromite/bromite#679]
### Bromite version

Version: `84.0.41447.113`
Arch:  `arm64` 
Android version: 9  (example: `9.0`)
Device model: Onclite (example: `SM-G960UZKABST`)

### Is this bug about the SystemWebView?
Yes/No
no

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
I dont know

### Is the bug a crash?
No

### Describe the bug
Proxy Config: It says a "list" , so I added  a list with ";"  but it ends up with the first one

### Steps to reproduce the bug
1. Open proxy configuration
2. take a list of proxys: 
   Eg: 
   PROXY 183.23.3.23:8080;
   PROXY 123.32.35.6:80
3. clicked ON "USE SINGLE PROXY LIST FOR ALL SCHEMES"
   I believe the PAC format is correct in my case on step 2 when reads with step3
4. click on apply
5. Only one proxy is saved instead of a list

Steps to reproduce the bug:
2. Click on '...'
3. Scroll down to '...'

### Expected behavior
It should be a list when add a list but its just one proxy

### Screenshots
Nil

**Comment by csagan5** [comment]
Fixed in `85.0.4183.84`.

**Comment by basimaslamts** [comment]
I checked it. But didn't work

**Comment by uazo** [comment]
@basimaslamts he's right, but I don't understand why.
in my mobile it doesn't work, in the one I used for debugging yes

**Comment by uazo** [comment]
I found the reason for me, I have always activated the anonymous mode
@basimaslamts can you confirm that you have it too? can you try without?

**Comment by csagan5** [comment]
@uazo try showing the source of the page and open the Javascript file `proxy_config.js` from there, then reload it if it's the old cached version.

To try properly one has to install it on the Android Virtual Device (emulator), from scratch.

**Comment by uazo** [comment]
> open the Javascript file proxy_config.js from there, then reload it if it's the old cached version.

I think the bug is the otr profile. 

> To try properly one has to install it on the Android Virtual Device (emulator)

yes, I have to try

**Comment by basimaslamts** [comment]
@uazo , I haven't enabled always on incognito mode

**Comment by uazo** [comment]
@csagan5 does it work for you?

**Comment by csagan5** [comment]
> I think the bug is the otr profile.

@uazo have you tried the procedure I described to refresh the Javascript file?

Yes, it works for me; I tested it before release.

**Comment by uazo** [comment]
> @uazo have you tried the procedure I described to refresh the Javascript file?

yes, it's new version

**Comment by csagan5** [comment]
Just tried in the emulator, it works fine. Maybe wipe the proxy configuration first?

![Screenshot_1598455197](https://user-images.githubusercontent.com/32685696/91322854-7facf580-e7c0-11ea-9b4e-3a7a1595e2a2.png)

**Comment by basimaslamts** [comment]
Guys it worked. 
Enter the next proxy (in PAC) typing space instead of "enter button".

I think the list should be worked both ways

**Comment by uazo** [comment]
> Enter the next proxy (in PAC) by clicking "space" instead of "enter button".

since I have to fix it because of incognito flag, I fix this too
