### ISSUE TITLE
Add flag to toggle DNS-over-HTTPS

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#68]
It is already possible to use DNS-over-HTTPS, albeit with Google servers only.

The implementation present in Chromium follows https://tools.ietf.org/id/draft-ietf-doh-dns-over-https-02.txt

Bromite should expose a flag in `chrome://flags` to toggle this functionality.

**Comment by csagan5** [comment]
Both Google and CloudFlare endpoints work, so next release will have a flag to pick one (or leave it disabled).

**Comment by csagan5** [comment]
Related: https://github.com/AdguardTeam/AdguardDNS/issues/228 and [this XDA post of mine](https://forum.xda-developers.com/showpost.php?p=76817347&postcount=926)

**Comment by Primokorn** [comment]
> albeit with Google servers only.

Just installed the latest update. (arm64_ChromeModernPublic)

The chrome://flags `#enable-dns-over-https` allows us to select between Disabled, Google and CloudFlare.
While using a VPN I made the dns leak test and my ISP is 'CloudFlare'.

**Comment by csagan5** [comment]
@Primokorn in the second comment here I report that also CloudFlare works. If you select CloudFlare (not clear from your comment) then it is expected to see CloudFlare as DNS provider.

Fixed in 67.0.3396.88

**Comment by Primokorn** [comment]
@csagan5 Yep sorry. I didn't notice your second comment.
