### ISSUE TITLE
Closing Issues which aren't solved

### ISSUE THREAD

**Issue by basimaslamts** [bromite/bromite#680]
### Is your feature request related to privacy?
Yes

### Is there a patch available for this feature somewhere?
No

### Describe the solution you would like
#509 #635 #633 and so many other issues where initiated. The developers closed the issues asking to submit patches. If the issue isnt resolved and no patches were updated, please dont close the issue as I have seen before. Let make it open so that any other can submit the patch. Our moto is "Take Back Browser"

### Describe alternatives you have considered
Using Firefox

**Comment by csagan5** [comment]
Thanks for the criticism, however the issue tracker is for bugs and feature requests alone.

**Comment by basimaslamts** [comment]
Then consider it as a feature request

**Comment by csagan5** [comment]
None of the issues you mentioned were closed asking for patches; if the issue is in line with the project goals I will keep it open so that others can help.

**Comment by basimaslamts** [comment]
The project goal is privacy.

Glad that #331 is reopened. Appreciate that..
