### ISSUE TITLE
No adblock when a tab is reopened from "Recent tabs"?

### ISSUE THREAD

**Issue by elcste** [bromite/bromite#681]
### Bromite version

Version: `84.0.4147.121`
Arch: `arm`
Android version: `10`
Device model: `Nokia 1`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
N/A: Bromite adblock issue

### Is the bug a crash?
No

### Describe the bug

When I reopen tabs from the "Recent tabs" menu option, those tabs show ads that are blocked if I navigate to the same page in a different way or just reload the page. I've reproduced on a few sites:

- BBC News [ads *not* shows in UK AFAIK], e.g. https://www.bbc.com/news/world-africa-53713391-
- New York Times [paywall], e.g. https://www.nytimes.com/2020/08/09/science/coronavirus-elephants-wildlife-zoo.html
- CNN, e.g. https://www.cnn.com/2020/08/08/us/duke-university-face-mask-test-trnd/index.html

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Visit a page with ads, such as one of the ones listed above.
2. See there are no ads when adblock is enabled.
3. Close the tab.
4. In another tab, click on the menu, then "Recent tabs", then the tab you just closed.
5. Observe that the reopened tab *does* show ads that were previously blocked.
6. Reload the page. Observe that ads again are blocked.

### Expected behavior

Tabs reopened from "Recent tabs" should have ads blocked like a page opened any other way.

**Comment by csagan5** [comment]
It could be related to the subresource filter not being added in such situation.

> ### Can the bug be reproduced with corresponding Chromium version?
> N/A: Bromite adblock issue

The ad blocker is in fact present also in Chromium, so this could be tested also there - although it uses a very specific default set of ads to block.

**Comment by elcste** [comment]
> The ad blocker is in fact present also in Chromium, so this could be tested also there - although it uses a very specific default set of ads to block.

I thought about that after I posed the issue. If you have any idea how to find a site to test with, I will. I poked around the Chromium source, but everything just said things like what is blocked are ads that violate the "Better Ads Standard", without any block list that I could locate.
