### ISSUE TITLE
Adblocker no longer working

### ISSUE THREAD

**Issue by F4kename** [bromite/bromite#684]
### Bromite version

Arm64
Android version: 10
Device model: Moto one

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
For me yes
84.0.4147.121

 

### navigate to a YouTube video - incognito or normal, ads appear. This also happens on other sites known to have ads (floating banners etc.) It's as if adblock filters are disabled which they are not.

Steps to reproduce the bug: as above

### Expected behavior

I expect to see no ads, this worked before extremely effectively, with previous versions.
Also when I open another app so this browser is in picture in picture mode, upon clicking back to this browser, the video (YouTube) does not always display fullscreen - I have to minimise and them maximise again.

**Comment by csagan5** [comment]
Close the app, upon re-opening it will try to download again the filters.

**Comment by josefschabasser** [comment]
I don't know how many times I have to restart Bromite, but ads aren't hidden anymore. I'll try to downgrade...

**Comment by csagan5** [comment]
@josefschabasser you don't have to downgrade or try another version: restart it and look into the logs with `adb logcat`; most probably it was failing to fetch the filters because of some network issue.
