### ISSUE TITLE
Pop-up blocking not working

### ISSUE THREAD

**Issue by pilsnerbeer** [bromite/bromite#686]
### Bromite version

Version: `84.0.4147.121`
Arch: `arm64`
Android version: `10`
Device model: `OP5T`

### Is this bug about the SystemWebView?
no

### Describe the bug

pop-up blocking doesnt seem to be working and pop-ups are not blocked. I have pop-up blocking set & enabled in Bromite.

### Steps to reproduce the bug

Steps to reproduce the bug:
1 visit a site that will flood you with pop-up ads (try yts.mx and click anything.)
2 pop-ups are opened in new tab

### Expected behavior
pop-ups are blocked (I have only tried & compared with Brave browser so far, which blocks the popups without problems)

**Comment by csagan5** [comment]
> (try yts.mx and click anything.)

The popup blocker works without clicking anything; if you click on something the popup blocker cannot help you, it only blocks popups started without clicking anything.
