### ISSUE TITLE
Wiki Vandalized

### ISSUE THREAD

**Issue by Zoraver** [bromite/bromite#689]
### Bromite version

N/A

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

N/A

### Can the bug be reproduced with corresponding Chromium version?

N/A

### Is the bug a crash?

N/A

### Describe the bug

A string of text containing a likely malicious URL appears to have been inserted into every page of the Bromite wiki. Based on the internet archive, this string was not present as of February 24, 2020. Interestingly, the string was inserted without changing the last edited date of the page.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to <https://github.com/bromite/bromite/wiki>
2. Observe inserted string

### Expected behavior

No potentially malicious URLs in the Bromite wiki

### Screenshots

![IMG_20200817_014035](https://user-images.githubusercontent.com/9345273/90361302-dc274c80-e02b-11ea-9248-0bdd81053cd7.jpg)

**Comment by csagan5** [comment]
It happened on 12,16,17 August; I reverted the edits, thanks for reporting.
