### ISSUE TITLE
Javascript Settings

### ISSUE THREAD

**Issue by AzureB1te** [bromite/bromite#690]
### Is your feature request related to privacy?

It's a privacy feauture.

### Is there a patch available for this feature somewhere?
I don't know of any

### Describe the solution you would like
 
Some weeks ago,I made a feautre request about a js manager tab. While,I completely understand your reasons for not implementing one,I was still thinking about a solution to unbreak sites while browsing with javascript disabled. 
So I came up with not one,but two solution,that shouldn't,(under my limited knowleadge of coding) require too much work. 

Version 1 : The JS toggle.
Simply, a toggle in the three dot menu,to enable/disable javascript for the current site. 
Version 2 : A shortcut to Site Setting
Also in the three dot menu,we could have a shortcut to the site setting of the site currently accesed. 

While I know that this/theese are not small requests to be made,I think they would benefit the browser massively,both for privacy - so more users can run with js disabled -> and only enable js when really needed. (Even tho this is possible at the very moment,the javascript switch/toggle would make it 10-50x as convinient. It would also make the user experience much better.

Do not ask "I would like feature X which is available in browser Y"; such issues are closed immediately. -->

Well , the current state of the browser is an alternative,

**Comment by csagan5** [comment]
You already have a shortcut to site settings: click on the padlock or "i" on the left of the address bar.
