### ISSUE TITLE
Add Metager to the search engine list

### ISSUE THREAD

**Issue by OmBq4rT0QtthMryqjNSc** [bromite/bromite#693]
### Is your feature request related to privacy?

Yes, metager is a search engine to be made to respect the privacy of its users

### Is there a patch available for this feature somewhere?

Not that I know of.

### Describe the solution you would like

Please add metager to the list of search engines, it is totally open source https://gitlab.metager.de/open-source/MetaGer, and has an anonymous view mode like startpage, furthermore, it is based in Germany, a country with good practices for privacy

### Describe alternatives you have considered

I have no other alternatives

**Comment by csagan5** [comment]
Bromite comes with the default search engines selection of Chromium; to add a search engine see https://github.com/bromite/bromite/wiki/SearchEngines
