### ISSUE TITLE
Push notifications not working

### ISSUE THREAD

**Issue by asliwinski** [bromite/bromite#698]
### Bromite version

Version: `84.0.4147.132`
Arch: `arm64`
Android version: (example: `10.0`)
Device model: (example: `VOG-L29`)

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with the latest version?
Yes, you can reproduce it at https://serviceworke.rs/web-push.html

### Can the bug be reproduced with corresponding Chromium version?
No, it works correctly in Chrome

### Is the bug a crash?
No

### Describe the bug
Push notifications don't show up. The permission granting procedure seems to work correctly.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to https://serviceworke.rs/push-get-payload_demo.html
2. Click on 'Request sending a notification'
3. No notifications shows up

### Expected behavior
Notification should show up

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> No, it works correctly in Chrome

You have to test with Chromium as explained in the issue template.

The issue template also suggests to read F.A.Q.s first.
