### ISSUE TITLE
DOH is broken

### ISSUE THREAD

**Issue by VernonStow** [bromite/bromite#700]
### Bromite version

Version: ` 84.0.4147.132`
Arch: `arm`
Android version: `8.1`
Device model: `UMX683CL'

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

Unknown

### Is the bug a crash?

No

### Describe the bug

When DoH is enabled, no internet connection can be made, regardless of which DoH providers are set. This did not occur with the previous build I was using. Uninstalling and reinstalling Bromite did not make a difference. Bromite worked normally after reinstalling, but when I turned DoH on, no connection to websites could be made.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Set DoH to ON
2. Enter any or all of the DoH providers listed on the DoH page
3. No internet page will load (cannot connect to server)
4. Turn off DoH, internet pages load normally

### Expected behavior

Internet pages should load normally

### Screenshots

N/A

**Comment by csagan5** [comment]
This is most likely a problem with your internet provider; works fine on multiple devices I tested.
