### ISSUE TITLE
"Download articles for you on wifi" doesn't work as expected.

### ISSUE THREAD

**Issue by generoberts** [bromite/bromite#702]
I disable that option, but when I visit pages offline, Bromite will try to download them when I'm online and create hidden files  (like .org.chromium.Chromium.XXXXX). Is this expected behavior? At least I didn't notice these many hidden files when I used previous versions.
Bromite 84.0.4147.132
Android 9, F-droid build.

**Comment by csagan5** [comment]
@generoberts please use the issue template
