### ISSUE TITLE
Apply Session-only cookies setting to Site Data

### ISSUE THREAD

**Issue by mikhaelkh** [bromite/bromite#703]
### Bromite version

Version: 84.0.4147.132
Arch: arm
Android version: 7.1.2
Device model: Nexus 5

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug
Although Site Data is not mentioned, it is treated the same way as Cookies. When Cookies are blocked for the site, Site Data is blocked too. Session-only cookies setting should be applied to Site Data as well.

### Steps to reproduce the bug

1. Set Cookies to Session-only
2. Go to website that stores Site Data, e.g. https://github.com
3. Exit Bromite, Open Bromite
4. Go to Site Settings, Storage

### Expected behavior
Site Data should be cleared with Cookies

**Comment by uazo** [comment]
let me answer as a co-author.

yes we know, what is deleted are only cookies, as written here https://github.com/bromite/bromite/issues/142#issuecomment-669246681
chromium/bromite doesn't support session site-data for now. the alternative is incognito mode.

**Comment by csagan5** [comment]
This is not a bug, it's working as intended.
