### ISSUE TITLE
Investigate showing update notification

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#706]
Investigate whether it's feasible to use the update icon with some simple update mechanism (like the adblock filters do).

**Comment by csagan5** [comment]
Some people do it with Tasker: https://www.reddit.com/r/tasker/comments/iduriz/bromite_updater/

**Comment by uazo** [comment]
what about reactivating omaha?

here https://source.chromium.org/chromium/chromium/src/+/master:chrome/android/java/src/org/chromium/chrome/browser/omaha/RequestGenerator.java;l=35 the request and here https://source.chromium.org/chromium/chromium/src/+/master:chrome/android/java/src/org/chromium/chrome/browser/omaha/ResponseParser.java parsing the response

in android it seems the necessary ui is already present

**Comment by uazo** [comment]
I guess you already know, but here's the patch ready to use

https://github.com/ungoogled-software/ungoogled-chromium-android/blob/master/patches/ungoogled-chromium-android/Enable-update-notification.patch

or maybe I misunderstood what you are asking?

**Comment by csagan5** [comment]
> what about reactivating Omaha?

Yes, that was my plan. And point it to the GitHub releases.

> I guess you already know, but here's the patch ready to use

No, I did not know. This could be usable, but I wanted to use the same mechanism used for the AdBlock filters: a check on `Last-Modified` header time of the download URL.

This is how it would work:
* on start check if there is a `PREF_LAST_TIME_UPDATE_NOTIFICATION_KEY` timestamp stored in preferences (like in the patch of ungoogled-chromium); if not present then set it to the [build time](https://github.com/chromium/chromium/blob/99314be8152e688bafbbf9a615536bdbb289ea87/base/build_time.h)
* instead of the `UPDATE_VERSION_URL` it would contact directly https://fdroid.bromite.org/latest/bromite_arm64.apk or https://fdroid.bromite.org/latest/bromite_arm.apk (depending on architecture)
* as it happens for the AdBlock filters, the first request is just a HEAD request
* parse `Last-Modified` from the `HEAD` request and compare to `PREF_LAST_TIME_UPDATE_NOTIFICATION_KEY`; if newer then proceed with `GET` request

The logic above pretty much all exists for the current AdBlock filters patch.

If you are interested you could port the patch; if you find the logic above too complicated I can add it later myself. We will also need a mechanism to disable the auto-updates, and #691 becomes even more important (we should not perform update checks before that exists and is accepted; ideally we would even put a checkbox there for people to disable update checks from the get-go).

**Comment by uazo** [comment]
> if you find the logic above too complicated

no problem

> If you are interested you could port the patch;

I don't know, I have to take a closer look. that patch is all java side, I would be more interested in reactivating the native, because it may be necessary to reactivate the `component_update`, which i think are then used for https://github.com/bromite/bromite/issues/244

**Comment by uazo** [comment]
@csagan5 i am working on this now. the idea is to use as a suffix TARGET_CPU taken from the gn args, but I can't find
https://fdroid.bromite.org/latest/bromite_x64.apk
could you activate that too?

**Comment by csagan5** [comment]
> > This post does not link to that repository, how is it a source for that?
> 
> happened by chance [here](http://g.co/chrome/hiring), one of the links in the Chrome Privacy Sandbox section

Do they link to this repository? https://github.com/bslassey/ip-blindness I cannot find the link.

**Comment by uazo** [comment]
> I cannot find the link.

wow, yes it was [there](http://g.co/chrome/hiring), but now it's gone ...

**Comment by uazo** [comment]
ah, no, it's here

![image](https://user-images.githubusercontent.com/29201891/140280097-91b71507-fe64-4a72-afd6-d591333fa331.png)

**Comment by csagan5** [comment]
Yes, so it is a Google-backed proposal and it has the problems I outlined before. To my eyes this is still not a serious effort at providing any privacy to the user.
