### ISSUE TITLE
Unable to bookmark with "Open links in incognito tabs always"

### ISSUE THREAD

**Issue by jrjordao** [bromite/bromite#708]
### Bromite version
Version: 84.0.4147.132
Arch: arm
Android version: 6.0.1

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
Don't know

### Is the bug a crash?
No

### Describe the bug
When running with the "Open links in incognito tabs always" option enabled, it is not possible to bookmark the current page by clicking on the star icon. This however works fine when running with the aforementioned option disabled and manually opening an incognito window.

### Steps to reproduce the bug
1. Enable "Open links in incognito tabs always" option in settings
2. Restart Bromite
3. Navigate to a page and try to bookmark it by clicking on the star icon (to the right of the address)

**Comment by csagan5** [comment]
Fixed in `85.0.4183.82`.

**Comment by uazo** [comment]
I made a mistake, @jrjordao is right.
I didn't add the patch in bromite_patches_list.txt (in the current build it is not present).
@csagan5 I have not modified that file in the last pull requests, I check if we have lost any others.
I'm sorry, I'll change it from next time!
