### ISSUE TITLE
search widget crashes

### ISSUE THREAD

**Issue by wdcwcwccwxq** [bromite/bromite#711]
Bromite version

Version: 85.0.4183.82
Arch: arm64
Android version: 9.0
Device model: Oneplus A5000

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes, started with current version, no issues previously

### Can the bug be reproduced with corresponding Chromium version? 
No

### Is the bug a crash?
Yes

### Describe the bug
home screen bromite search widget crashes, widget created from the launcher settings.

### Steps to reproduce the bug
1. Go to Launcher Settings
2. Click on create a Bromite search widget on the home screen
3. tap on search widget on homescreen to open bromite duckduckgo search and bromite crashes.

### Expected behavior
before august 21 update, homescreen widget always functioned properly

**Comment by csagan5** [comment]
Cannot reproduce this issue.
