### ISSUE TITLE
"Force Dark Mode for Web Contents" chrome flag is not honored; websites are not in dark mode

### ISSUE THREAD

**Issue by SweetestRug** [bromite/bromite#716]
### Bromite version

Version: `85.0.4183.82`
Arch: `arm` (Android)
Android version: (example: `10.0`)
Device model: (example: `Pixel 3`)

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?

No

### Describe the bug

The chrome flag for 'Force Dark Mode for Web Contents', when set to Enabled, does not seem to have an effect.  Dark Mode is not implemented for websites, even though the force Dark Mode flag is set. This does not happen in the prior version of 84.0.4147.132. 

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to chrome://flags
2. Search for "Dark Mode"
3. Enable the flag
4. Visit any website; Dark Mode is not enabled

### Expected behavior

Dark mode is enabled for all websites

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> No

Have you tested this with the corresponding Chromium version? What is the effect?

**Comment by SweetestRug** [comment]
The most recent version of vanilla chromium (85.0.4183.82, built alongside bromite and downloadable via F-Droid) does not have the same problem. When Dark Mode for all websites is enabled, web sites are rendered in dark mode. Only the current version of Bromite displays the issue.

**Comment by csagan5** [comment]
@SweetestRug there are no changes in Bromite or Chromium related to the dark mode between `85.0.4183.82` and `85.0.4183.84`.

I will try to reproduce this issue with `85.0.4183.82`; which website are you using for a test?

**Comment by csagan5** [comment]
I can reproduce this bug; it works with Chromium `85.0.4183.86` but it does not work with Bromite `85.0.4183.86`. I tested using a wikipedia page.

@uazo any idea? This is a quite odd bug...

**Comment by SweetestRug** [comment]
I found this on numerous websites. For example, forum.manjaro.org and wikipedia. Its good to see that the bug is reproducible, as it is quite odd.

**Comment by Xeunyx-Cypher** [comment]
Just to let you guys know. I'm facing the exact same bug! Didn't face it in the 84 though.

**Comment by uazo** [comment]
> @uazo any idea? This is a quite odd bug...

no by the way is an option that never used.
maybe I'll check.

**Comment by Ridwan-Sobirin** [comment]
I don't know what caused it, but you need to enable "darken websites" in settings -> themes first

**Comment by SweetestRug** [comment]
That solved it!  Thanks for finding the solution!

**Comment by csagan5** [comment]
That is true; you have to either enable Darken websites under Settings -> Themes or disable the feature `#darken-websites-checkbox-in-themes-setting` which was enabled by default in `85.0.4183.82`.
