### ISSUE TITLE
(Request) Uploading compressed archive

### ISSUE THREAD

**Issue by nihalanand697** [bromite/bromite#718]
Hi, not necessary for the majority but is it possible and feasible for you to upload the apk compressed for the minority who are low on data? 
I am attaching an image for a rough comparison to show the difference which is great in conparsion to the apk.
Normal and Ultra imply the compression I chose while compressing the apk with Mix file manager.
Thanks.
![Screenshot_20200826-230909_MiXplorer](https://user-images.githubusercontent.com/47318989/91337690-640e1300-e7f1-11ea-8d78-73a8a5b4b358.png)

**Comment by csagan5** [comment]
@nihalanand697 the file is already downloaded compressed by F-Droid Client or your browser of choice.

**Comment by nihalanand697** [comment]
I might be wrong but i see same size in fdroid repo as well as in github.
![Screenshot_20200827-000354_Foxy_Droid](https://user-images.githubusercontent.com/47318989/91342571-e1895180-e7f8-11ea-8bff-64b8a48d2a4e.png)

**Comment by csagan5** [comment]
See https://en.m.wikipedia.org/wiki/HTTP_compression

**Comment by nihalanand697** [comment]
Sorry but I do not understand it.
Does it mean that the file size is shown as 100+ mb in fdroid but the downloading is done of a compressed version of it?

**Comment by csagan5** [comment]
@nihalanand697 on any normal webserver, yes. But GitHub uses Amazon S3 and they do not have it enabled, unfortunately. I have asked them about it but it's unlikely they will enable it.

If you download from APKMirror (https://www.apkmirror.com/apk/bromite/bromite/) the files are downloaded with compression, so you will save a 100MB file but the bandwidth used will be the compressed amount.
