### ISSUE TITLE
FC when opening

### ISSUE THREAD

**Issue by robertoprubio** [bromite/bromite#719]
### Bromite version

Version: 85.0.4183.82
Arch: arm64
Android version: 10.0
Device model: Xiaomi Mi Note 10 (MIUI 11)

### Is this bug about the SystemWebView?
No

Steps to reproduce the bug:
1. Open the app

Details:

08-27 07:28:53.183 15200 15200 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.bromite.bromite/org.chromium.chrome.browser.ChromeTabbedActivity}: android.view.InflateException: Binary XML file line #24 in org.bromite.bromite:layout/0_resource_name_obfuscated: Binary XML file line #24 in org.bromite.bromite:layout/0_resource_name_obfuscated: Error inflating class org.chromium.chrome.browser.omnibox.LocationBarPhone
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3307)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3446)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2043)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7542)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #24 in org.bromite.bromite:layout/0_resource_name_obfuscated: Binary XML file line #24 in org.bromite.bromite:layout/0_resource_name_obfuscated: Error inflating class org.chromium.chrome.browser.omnibox.LocationBarPhone
08-27 07:28:53.183 15200 15200 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #24 in org.bromite.bromite:layout/0_resource_name_obfuscated: Error inflating class org.chromium.chrome.browser.omnibox.LocationBarPhone
08-27 07:28:53.183 15200 15200 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.view.ViewStub.inflateViewNoAdd(ViewStub.java:272)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.view.ViewStub.inflate(ViewStub.java:305)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at org.chromium.chrome.browser.toolbar.top.ToolbarControlContainer.b(chromium-ChromeModernPublic.apk-stable-1598054951:5)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at org.chromium.chrome.browser.ChromeActivity.I0(chromium-ChromeModernPublic.apk-stable-1598054951:15)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at org.chromium.chrome.browser.ChromeActivity.x0(chromium-ChromeModernPublic.apk-stable-1598054951:26)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at hm0.E(chromium-ChromeModernPublic.apk-stable-1598054951:7)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at Dm0.d(chromium-ChromeModernPublic.apk-stable-1598054951:11)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at hm0.onCreate(chromium-ChromeModernPublic.apk-stable-1598054951:26)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7893)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7880)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3282)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3446)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2043)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7542)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: No implementation found for boolean J.N.M09VlOh_(java.lang.String) (tried Java_J_N_M09VlOh_1 and Java_J_N_M09VlOh_1__Ljava_lang_String_2)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at J.N.M09VlOh_(Native Method)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at gB0.<init>(chromium-ChromeModernPublic.apk-stable-1598054951:18)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at fz0.<init>(chromium-ChromeModernPublic.apk-stable-1598054951:14)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	at org.chromium.chrome.browser.omnibox.LocationBarPhone.<init>(chromium-ChromeModernPublic.apk-stable-1598054951:1)
08-27 07:28:53.183 15200 15200 E AndroidRuntime: 	... 32 more

**Comment by csagan5** [comment]
> 85.0.4183.82

This is not the latest version.
