### ISSUE TITLE
[question] homepage option behavior

### ISSUE THREAD

**Issue by Gnomsen** [bromite/bromite#72]
I activated this flag: `#force-enable-home-page-button` and adjusted my homepage.

Why Bromite doesn't load my setted homepage on every start. When i start Bromite, the regular new tab page appears, but my homepage does not load.

This happens when i start the app after certain time of not using it (maybe 1 hour)
If i start the app every 5 minutes my homepage loads correctly.

Is there a way to fix this behavior?

**Comment by csagan5** [comment]
Please test with the corresponding [Chromium](https://www.bromite.org/chromium) release; I believe this problem is reproducible with Chromium as well.
