### ISSUE TITLE
Certificate for fdroid.bromite.org is expired

### ISSUE THREAD

**Issue by Dnnd** [bromite/bromite#720]
### Describe the bug
It's impossible to interact with Bromite F-Droid repository due to certificate expiration. Simple GET-request via curl : `curl https://fdroid.bromite.org/fdroid/repo` reports the following error:
```
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

### Steps to reproduce the bug
1. Open QR-code from https://www.bromite.org/fdroid in f-droid client
2. Enable Bromite repository
3. Update repositories

Alternatively, use curl to perform GET-request to https://fdroid.bromite.org/fdroid/repo:
1. `curl https://fdroid.bromite.org/fdroid/repo`

### Screenshots
![Screenshot_2020-08-31-00-29-57-256_org fdroid fdroid](https://user-images.githubusercontent.com/20689536/91669887-3d1d4d00-eb21-11ea-8659-d94cec2ae2cf.jpg)

**Comment by OnlinePlayer865** [comment]
I came here to report the same issue. I am having this as well.

**Comment by poppypundit** [comment]
Same for me.

**Comment by csagan5** [comment]
There are some issues on the server hosting this, should be resolved soon.

Thanks for reporting.

**Comment by poppypundit** [comment]
> There are some issues on the server hosting this, should be resolved soon.
> 
> Thanks for reporting.

Thank you for acknowledging 🙏

**Comment by csagan5** [comment]
The server is again reachable and the issue has been resolved.

**Comment by JTBrinkmann** [comment]
**The certificate expired again today.** Apparently the server doesn't automatically update LetsEncrypt certificates?

**Comment by csagan5** [comment]
It does update automatically but can fail for a wide range of reasons; I monitor it but it takes me some time to come around and fix it.
