### ISSUE TITLE
please add support extension

### ISSUE THREAD

**Issue by mohibo** [bromite/bromite#722]
### Bromite version

Version: `83.0...`
Arch: `arm` or `arm64` or `x86`
Android version: (example: `9.0`)
Device model: (example: `SM-G960UZKABST`)

### Is this bug about the SystemWebView? no
Yes/No

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to '...' chrome extensions
2. Click on '...'
3. Scroll down to '...'

### Expected behavior
download a extension

**Comment by subhasishlak123** [comment]
Please

**Comment by subhasishlak123** [comment]
Add

**Comment by subhasishlak123** [comment]
Support

**Comment by subhasishlak123** [comment]
Extension

**Comment by mohibo** [comment]
why is it invalid?

**Comment by mohibo** [comment]
> 
> 
> Please

and

**Comment by Dhyfer1** [comment]
@Bromite More browsers with extensions support are needed for android and the only ones I know so far are Kiwi Browser and Yandex Browser, so when will we see extensions in Bromite?
