### ISSUE TITLE
Consider Remove ETAG header support

### ISSUE THREAD

**Issue by uazo** [bromite/bromite#727]
### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

I don't know.

### Describe the solution you would like

as demonstrated here

https://lucb1e.com/rp/cookielesscookies/

it is possible to use the etag header as cookies even on sites where javascript and cookies are disabled.
according to the evidence, the only way to prevent this possibility is to delete the "cached images and files" as well.

### Describe alternatives you have considered

remove support of etag.
it seems to be possible by changing only one line, here
https://source.chromium.org/chromium/chromium/src/+/master:media/blink/url_index.cc;l=193

**Comment by csagan5** [comment]
This would break the ETag support; Firefox has containers and first party isolation. I believe similar functionality is in Chromium already so that the cache is not accessible cross-domain.

You could make it work behind a toggle, but not sure it's a worth feature to have; the best we have is navigation in incognito mode, the same origin can access the ETag for the duration of that session.

That site is/was cheating, see also: https://bugs.chromium.org/p/chromium/issues/detail?id=858969

**Comment by uazo** [comment]
> That site is/was cheating

no, it's a real way to track people.
the problem with that page is that it wants to give feedback to the user: if you think about it, the exchange of a value generated by a server is real and without any possibility of denying it.

> the best we have is navigation in incognito mode

I absolutely agree.

but then I don't understand. do you want to enhance incognito browsing like normal browsing or vice versa? so as to understand your direction.

**Comment by csagan5** [comment]
> no, it's a real way to track people.
> the problem with that page is that it wants to give feedback to the user: if you think about it, the exchange of a value generated by a server is real and without any possibility of denying it.

Please read the Chromium issue I linked, it explains why the site does not make a proper test.



> do you want to enhance incognito browsing like normal browsing or vice versa? so as to understand your direction.

We can enhance incognito browsing but removing the ETag header is not a proper way to do this. Lookup how the cache works, in particular with strict site isolation.

**Comment by uazo** [comment]
The use of anonymous browsing solves everything obviously because it deletes.

> Please read the Chromium issue I linked, it explains why the site does not make a proper test.
>> This website shows that fingerprinting works but there is no bug in Chrome.

I try to be clearer.

try this i did:
https://run.mocky.io/v3/f5448572-20ab-460c-8795-464843124f51

That page returns

etag: test12342
cache-control: no-cache

FIRST REQUEST:
![image](https://user-images.githubusercontent.com/29201891/92327636-48a9d000-f05b-11ea-8ba0-b3656503ebc8.png)

OTHER REQUEST:
![image](https://user-images.githubusercontent.com/29201891/92327637-4b0c2a00-f05b-11ea-9d5a-cc6fd3d0213a.png)


as indicated here https://source.chromium.org/chromium/chromium/src/+/master:net/http/http_response_headers.cc;l=1012 with `cache-control: no cache`, etag value, set by the server, always return until cache deletion.

**Comment by csagan5** [comment]
> I try to be clearer.

Not necessary; I am referring to this comment: https://bugs.chromium.org/p/chromium/issues/detail?id=858969#c7
