### ISSUE TITLE
CloudFlare -> Cloudflare rename

### ISSUE THREAD

**Issue by xxdesmus** [bromite/bromite#73]
Hi,

Just wanted to point out that CloudFlare should be Cloudflare.

https://blog.cloudflare.com/time-for-an-update/

I didn't want to just open the PR and start renaming things, but I figured I'd give you a heads up.

Thanks,
Justin (I work at Cloudflare)

**Comment by csagan5** [comment]
Ops...my bad for not checking at the source. I will rectify in the (current+2) release (next is already packaged).

I will also re-do the screenshot in the wiki page.

**Comment by xxdesmus** [comment]
Thanks!

**Comment by csagan5** [comment]
Fixed in 67.0.3396.95
