### ISSUE TITLE
Google has just disabled the way to disable autoplay

### ISSUE THREAD

**Issue by baybal** [bromite/bromite#734]
I think this is self explanatory.

The ads that pass your adblock bust your data package in a few seconds now.

The appropriate measure is locate, and rollback that change.

**Comment by csagan5** [comment]
Fixed in `85.0.4183.110`.

**Comment by baybal** [comment]
@csagan5 Carl, the path added in .110 doesn't stop autoplay, it just keep the background playback going.

What I meant was to restore an option to stop video autoplay that was removed in either 83 or 84

**Comment by csagan5** [comment]
@baybal please re-submit the issue with the template (it needs desktop mode), or edit it to have the template. We can continue the discussion after that.
