### ISSUE TITLE
Battery usage

### ISSUE THREAD

**Issue by davexnet** [bromite/bromite#736]
It sure seems high recently. My wifi stats show Bromite only using 1.35 gb since 8/11/20, but battery info shows it using 26% of the battery since it was last charged 4 days ago. I'm not playing media files. That's even worse that Firefox, and that's bad enough. 
Android Pie on Moto G7 Power

### Bromite version

Version: `83.0...`
Arch: `arm` or `arm64` or `x86`
Android version: (example: `9.0`)
Device model: (example: `SM-G960UZKABST`)

### Is this bug about the SystemWebView?
Yes/No

### Steps to reproduce the bug

Steps to reproduce the bug:
2. Click on '...'
3. Scroll down to '...'

**Comment by csagan5** [comment]
@davexnet you would have to test with Chromium alone, as the issue template says.

**Comment by davexnet** [comment]
Which "corresponding Chromium version" - do you mean Google Chrome itself?

**Comment by davexnet** [comment]
Hello -do you mean test it against Google Chrome?What Chromium are you referring to?
Dave H

    On Tuesday, September 8, 2020, 11:48:25 PM PDT, Carl <notifications@github.com> wrote:  
 
 


Closed #736.

**Comment by Poopooracoocoo** [comment]
@davexnet https://www.bromite.org/chromium

**Comment by davexnet** [comment]
Thank you, I'll take a look
