### ISSUE TITLE
Donations from this country are not supported

### ISSUE THREAD

**Issue by bushrang3r** [bromite/bromite#738]
I get this message in PayPal when I try to donate from Japan. Are there some settings in PayPal that prevent people from certain countries from donating?

**Comment by csagan5** [comment]
@bushrang3r if you search online it seems to be a PayPal limitation, nothing I can fix through the settings of the account.

**Comment by SavSanta** [comment]
@csagan5 
How about adding support for a different donation platform? The ones you have a currently are quite limiting. For myself I can't use Patreon but especially for a lot of people do not use cryptocurrency (as it's too complicated)

You're prob missing persons with only 2 donation options

See if you can look into deasibly setting up: 
- Liberapay
- BuyMeACoffee
- Ko-Fi
- SubscribeStar
- GiveSendGo
- GitHub 'Sponsors' via this project tab

If I remember correctly last time I tried to donate thru PayPal and the you sent the funds back. I think they came from Germany. I'm in the USA. So Liberpat should work. Tho also I donate to Debian project at times at the end of the year and they use 'Software in the Public Interest' to collect from more convenient methods to USA citizens on behalf of the Debian. However you may need to be a full-fledged organization to join I don't know 

Additionally these are prob more business like but 
FastSpring is used by DDWRT also Germany based.


There are prob more but those above are what I'm familiar with. Either way your leaving donations I nthe table with only 2 options.
