### ISSUE TITLE
"Exit" not translated

### ISSUE THREAD

**Issue by B0pol** [bromite/bromite#739]
### Bromite version

Version: 85.0.4183.110
Arch: arm
Android version: 9.0
Device model: Poco F1

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?
No, it's added by a bromite patch, Add-exit-menu-item.patch

### Is the bug a crash?
No

### Describe the bug

Exit it not translated

### Steps to reproduce the bug
Steps to reproduce the bug:
1. Change your device language (e.g. german, french…)
2. Open the three dots menu
3. "Exit" is not translated

### Expected behavior
"Exit" is translated

### Screenshots

<img src="https://i.ibb.co/X5XBBGP/Screenshot-20200912-101212-Bromite.png">

It should be "Quitter" in French.

**Comment by csagan5** [comment]
It's not translated for all languages; I will accept patches for the missing translations.

**Comment by erommel** [comment]
Can you guys provide a simple example of a patch that can be used to translate this? This way anyone can just insert translation for the word and make a PR with the patch file.

**Comment by Abacate123** [comment]
I agree with @erommel , I'd also like to translate this browser to my native language.

**Comment by csagan5** [comment]
> Can you guys provide a simple example of a patch that can be used to translate this? This way anyone can just insert translation for the word and make a PR with the patch file.

That patch would not work. It is actually a bit complicated process; first one needs Android Studio to add the translation, then a patch needs to be created using `git`.

**Comment by uazo** [comment]
but, what about using a software like https://weblate.org/?
it seems free for open source projects, but I've never used it
we can extract the strings and keys from the chromium code, and probably with some scripts, generate the corresponding patches/files.

**Comment by csagan5** [comment]
> it seems free for open source projects, but I've never used it

No interest in doing an automation for this; anybody can use any type of automation and then submit the patches.

To go back on the original topic: @zhmars could you explain again the procedure you use? So maybe others can pick up the task.

**Comment by zhmars** [comment]
Sorry for the late response.

Taking Simplified Chinese(zh_CN) as a example. To translate a string, all we need to know are three things: translation, translation id and the locale file.

- translation

  For the string we want to translate, we should find out where they are coming from. In this case, the `Exit` string is added by [Add-exit-menu-item.patch](https://github.com/bromite/bromite/blob/master/build/patches/Add-exit-menu-item.patch).

  We should find all new added strings from the grd(p) files and translate them to your locale.

  `Exit` -> `退出`

- translation id

  We need the [grit](https://github.com/chromium/chromium/tree/master/tools/grit) tool to get it. They could be generated using following command.

  ```sh
  $  python -c 'from grit.extern import tclib;print(tclib.GenerateMessageId("Exit"))'
  9148058034647219655
  ```

  `Exit` -> `9148058034647219655`

- locale file

  Usually, a locale file could be found at the subdirectory of grd(p) files. In this case, the grd file is located at `chrome/browser/ui/android/strings/android_chrome_strings.grd`. And the locale file is located at `chrome/browser/ui/android/strings/translations/android_chrome_strings_zh-CN.xtb`


Now we can append our translation to the file and create a patch for it.

```diff
diff --git a/chrome/browser/ui/android/strings/translations/android_chrome_strings_zh-CN.xtb b/chrome/browser/ui/android/strings/translations/android_chrome_strings_zh-CN.xtb
index 8b4ba9c..edf495d 100644
--- a/chrome/browser/ui/android/strings/translations/android_chrome_strings_zh-CN.xtb
+++ b/chrome/browser/ui/android/strings/translations/android_chrome_strings_zh-CN.xtb
@@ -1264,4 +1264,5 @@
 <translation id="983192555821071799">关闭所有标签页</translation>
 <translation id="987264212798334818">常规</translation>
 <translation id="996149300115483134">动态卡片上的菜单已关闭</translation>
-</translationbundle>
\ No newline at end of file
+<translation id="9148058034647219655">退出</translation>
+</translationbundle>
```

**Note**

`Settings` -> `Privacy and security` -> `Proxy configuration`

The last menu item is added by [this patch](https://github.com/bromite/bromite/blob/master/build/patches/Add-a-proxy-configuration-page.patch). And for the grd(p) changes, it is a little different from others. I still have no idea to make sure it is translated. I tried, but failed.

There are two `About Bromite` menu items and they are not coming from any patches from repo. But we could still add transtions for them(more precisely, one of them).

- `Settings` -> `About Bromite`

  No idea to translate it.

- `Settings` -> `About Bromite` -> `About Bromite`(title)

  The locale file is here: `chrome/browser/ui/android/strings/translations/android_chrome_strings_zh-CN.xtb`

**Comment by csagan5** [comment]
Thanks @zhmars; to make the procedure a bit clearer, I have created this wiki page with instructions: https://github.com/bromite/bromite/wiki/Translations

> The last menu item is added by [this patch](https://github.com/bromite/bromite/blob/master/build/patches/Add-a-proxy-configuration-page.patch). And for the grd(p) changes, it is a little different from others. I still have no idea to make sure it is translated. I tried, but failed.

This text is hard-coded in the HTML and there is no Javascript to translate them, I suppose that is the reason.
