### ISSUE TITLE
Clear browsing data sometimes will not clear all data

### ISSUE THREAD

**Issue by AndhikaWB** [bromite/bromite#74]
Clearing all browsing data (cookies, history, cache, and site settings) will not clear all data.

After clearing data, most visited pages (on new tab) will still show my most visited pages. However, restarting the browser (Bromite) will solve the issue.

Also, after restarting, some sites will still be shown on my history (opened it from the menu) and my recent sites/searches (that dropdown menu when typing on address bar). After that, the most visited sites will appear again (after opening that history).

I already noticed this issue since long ago, but I ignored it because I use my personal phone.

Unless this is only happened to me, it can be fatal to all of us because it's privacy related.

**Comment by csagan5** [comment]
@AndhikaWB does this issue happen with [Chromium](https://www.bromite.org/chromium)?

**Comment by AndhikaWB** [comment]
@csagan5 do you experience this issue too? Just tested Chromium and Brave, all browsers (including Bromite) are having almost the same issue, not all data were cleared by using 'Clear browsing data'.

On Chromium, history sometimes will not be saved when browsing, but may appear on 'Recent Tabs' menu. Clearing all browsing data will clear the history but not the recent tabs, restarting Chromium doesn't solve the problem. This is a bit different from the issue I experienced with Bromite. However, the issue that I experienced on both of them is still about 'clearing browsing data will not clear all data'.

Right now I'm using an ancient Android 4.3 by the way, but I don't think it's OS related. Just close this issue if you think the problem is with the Chromium itself.

**Comment by csagan5** [comment]
@AndhikaWB feel free to take the issue upstream in the Chromium project, then we may check again the status in Bromite. I expect it to be solved upstream and then be solved as well in Bromite.
