### ISSUE TITLE
Option to set a custom search engine yourself

### ISSUE THREAD

**Issue by drewblasphemepatchwork** [bromite/bromite#741]
### Is your feature request related to privacy?

Yes. It would be possible to use privacy friendly search engines and using existing search engines like DuckDuckGo would be more customizable with custom parameters. Also the freedom to choose the search engine yourself should be avaible in a privacy focused browser in my opinion.

### Is there a patch available for this feature somewhere?
No

### Describe the solution you would like

A simple "+" symbol in the search engine menu in settings and a field to type the url of the search engine.

### Describe alternatives you have considered

I considered putting the search engine as an homepage, however this is inconvient.

**Comment by csagan5** [comment]
See https://github.com/bromite/bromite/wiki/SearchEngines

**Comment by schattenpanzer** [comment]
@csagan5 the wiki page claims that you can do that, but the problem is, you can't. You can't add custom search engines like you can in chromium, it's probably a bug since it's not working right now.

Please reopen this issue until the search engine functionality is fixed.

**Comment by csagan5** [comment]
> You can't add custom search engines in bromite as you can in chromium, it's probably a bug.

You can add in Bromite the same search engines that you can add in Chromium. If you have verified that there is a bug, please open an issue describing such bug.
