### ISSUE TITLE
Adding a custom search engine doesn't work

### ISSUE THREAD

**Issue by schattenpanzer** [bromite/bromite#743]
### Bromite version

Version: `85.0.4183.110`
Arch: `arm64`
Android version: `10.0`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

Yes

### Is the bug a crash?

No

### Describe the bug

Adding a custom search engine doesn't work. In chromium, I'd go to the search engine site, right click on the URL bar, 'Edit Search Engines', and it would show up, I can set it as default. I try the same website in bromite, following the instructions from the wiki: https://github.com/bromite/bromite/wiki/SearchEngines

### Steps to reproduce the bug

Steps to reproduce the bug:
1. open bromite
2. visit a preferred search engine website of choice (let's say qwant or searx)
3. 3-dot menu > settings > search engine
4. recently visited search engine site doesn't show up, nor can you add one.

### Expected behavior

I could be wrong but I recall bromite used to allow you to add custom search engines this way, or that there was some menu for it. I recall qwant being an option, it's no longer there, and the wiki says that it's there (wiki was probably not edited in a while). Perhaps it's not a bug, but the feature seems removed or seemingly not working.

**Comment by csagan5** [comment]
It works fine, I have just tried with qwant.com on both Chromium and Bromite and it works as explained on the [wiki page](https://github.com/bromite/bromite/wiki/SearchEngines).

**Comment by schattenpanzer** [comment]
![aqatRdllQk-nDOfq4NWzTQ_10cb78b5614e0ba3efb08b5fa7202c1a02c2185b](https://user-images.githubusercontent.com/66455331/93144376-e171c880-f6b7-11ea-86bf-a2bff8e8c7b2.jpg)
![8q7gBKyMR0aFiQs5_8u6gA_52c9d83eba33463c8b3efdc5c6277b27fe693bb0](https://user-images.githubusercontent.com/66455331/93144380-e171c880-f6b7-11ea-9c7e-3113e554cd77.jpg)

Shouldn't it show up in the search engine settings after visiting a search engine site? @csagan5

**Comment by csagan5** [comment]
> Shouldn't it show up in the search engine settings after visiting a search engine site?

You need to perform a search first. I have updated the [wiki page](https://github.com/bromite/bromite/wiki/SearchEngines) to make it clearer; regardless, you had reported the bug to be reproducible with Chromium - which is a criteria of exclusion as explained in the issue template.
