### ISSUE TITLE
Sharing links of open tabs

### ISSUE THREAD

**Issue by RasaKh** [bromite/bromite#744]
### Is your feature request related to privacy?
Not directly

### Is there a patch available for this feature somewhere?
Not that I know of

### Describe the solution you would like

If you could please add the functionality that allows you to "share" the links of all and/or groups of open tabs, by tapping an option in the menu (three dots) in the tabs area. This allows for easily "sync"ing tabs between two devices by sending them through an IM. 

This function is available in Firefox. 
Thank you.

**Comment by csagan5** [comment]
I cannot commit to develop this functionality, nor it is in line with the project goals.

If someone would develop it I could consider adding the patch.
