### ISSUE TITLE
Is the fdroid repo down?

### ISSUE THREAD

**Issue by pitsi** [bromite/bromite#746]
### Bromite version
Version: 85.0.4183110
Arch: arm64
Android version: 9.0
Device model: Nokia TA-1024 (Nokia 5)

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Not applicable

### Can the bug be reproduced with corresponding Chromium version?
Not applicable 

### Is the bug a crash?
No

### Describe the bug
Your fdroid repo seems to return a 404 error today. 

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Install fdroid on the device or fdroidcl (alternative command line client) on the pc.
2. Install bromite's fdroid repo in it with the instructions shown on its page.
3. Let it update by getting the lists from all the repos.
4. Notice that the repo returns a 404 code, thus it is unavailable.

### Expected behavior
The repo should be online.

### Screenshots
Command line output of fdroidcl instead of screenshots
```
$ fdroidcl update
Downloading https://fdroid.bromite.org/fdroid/repo/index-v1.jar... 
update: could not update index: download failed: 404 Not Found
```
On top of the above, yesterday, ~20 hours ago that I wanted to update bromite, fdroidcl was reporting a time out when trying to download the index file here. Wget was also timing out when trying to download it. Today, wget also fails with a 404 error.
`https://fdroid.bromite.org/fdroid/repo/index-v1.jar`

Url of the repo as shown on bromite's page
`https://fdroid.bromite.org/fdroid/repo`
Url of the repo in my configuration file 
```
$ cat .config/fdroidcl/config.json | grep url
			"url": "https://f-droid.org/repo",
			"url": "https://f-droid.org/archive",
			"url": "https://fdroid.bromite.org/fdroid/repo",
```
Thus it is completely correct, no typos.

**Comment by csagan5** [comment]
Thanks for reporting; it is now fixed.

The timeout was most probably due to the switch to the new server.

**Comment by pitsi** [comment]
Thanks. I just checked with fdroidcl and it works as it should now :)
