### ISSUE TITLE
Add option for setting up UserAgent

### ISSUE THREAD

**Issue by marcinwiacek** [bromite/bromite#747]
### Is your feature request related to privacy? 

YES

### Is there a patch available for this feature somewhere? 

NO

### Describe the solution you would like

Adding option for selecting custom UserAgent header (for example with option for simulating Firefox or Chrome or ability of putting own string)

### Describe alternatives you have considered

There are no other options in Chrome based browsers on Android (?)

**Comment by csagan5** [comment]
It's not related to privacy.
