### ISSUE TITLE
Cannot open source for local file

### ISSUE THREAD

**Issue by marcinwiacek** [bromite/bromite#748]
### Bromite version

Version: 85.0.4183.114
Arch: arm64
Android version: 8
Device model: Samsung S7

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

Unknown

### Is the bug a crash?

No

### Describe the bug

In latest Bromite local files opened from system file explorer don't have source

### Steps to reproduce the bug

1. open bookmarks window
2. export -> it opens created mhtml file in tab (OK)
3. view source -> file displayed using file://storage/... URL (OK)
4. go to system file explorer
5. click on mhtml file -> opened using content://com.sec.... URL (OK)
6. view source -> empty page (NOK)

### Expected behavior

Option view source is unavailable for such files (when there is security problem) or should be available for content://com.se...

**Comment by csagan5** [comment]
The exported bookmarks are saved as `.html` files, not `.mhtml`. I cannot reproduce this issue; please provide different or better steps for reproduction.
