### ISSUE TITLE
Ddg not opening

### ISSUE THREAD

**Issue by abh-oss01** [bromite/bromite#754]
Have you read the README?
Yes

Have you searched the issue tracker?
Yes 
Are you using the latest version of Bromite?
-->Yes

### Bromite version

Version: `85.0.4183.114`
Arch:  `arm64`
Android version: `10`
Device model: realme 6 pro

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug

Duckduckgo.com or ddg.co do not open at all.
Been facing this issue since quite a few of the last versions of bromite (including this one)

Sometimes it opens, but after many many tries of "Reloading", and restart, etc.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to ddg.co or duckduckgo.com
2. Click on enter
3. See error

### Expected behavior

It should open it like any other sites

### Screenshots

![20200927_144419.jpg](https://user-images.githubusercontent.com/56572179/94361175-027ee400-00d0-11eb-8835-ad2b38f7f407.jpg)

Note: I **do not** have DoH (in Settings>Privacy>Secure DNS) turned on.

**Comment by csagan5** [comment]
I cannot reproduce it with the steps you provided; if you can provide steps to reproduce it or explain why this is a Bromite bug, then we can reopen it. Until that I have to conclude it is a problem with your network.

**Comment by abh-oss01** [comment]
- like I said it's sometimes opens, very rarely it does open, but not everytime

and my network is fine, I'm downloading stuff on the pc since a few hours now, no problems there.
