### ISSUE TITLE
Link the issue template in README

### ISSUE THREAD

**Issue by generoberts** [bromite/bromite#756]
Currently, you'll see issues template only(?) when you create an issue in GitHub in a browser. Even googling "bromite issue template" yields nothing, so when you create an issue via, say, unofficial GitHub app on your phone you won't see any template. This leads to many closed issues due to the missing issue template.

**Comment by csagan5** [comment]
GitHub acknowledged the problem and they said they would not do anything about it. My only alternative is to move the issue tracker to GitLab.

I will add some information.
