### ISSUE TITLE
Some DCHECKs failed with current master

### ISSUE THREAD

**Issue by uazo** [bromite/bromite#758]
### Bromite version

Version: `86.0.4240.55` current master
Arch: `arm64`
Android version: tested on `9.0`,`10.0`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Only with DCHECKs on

### Can the bug be reproduced with corresponding Chromium version?

No.

### Is the bug a crash?

Yes, but only in debug

### Describe the bug

Fix failed DCHECKS:

- [ ] "All preferences in the screen should be added in the new order list"
`chrome/android/java/src/org/chromium/chrome/browser/privacy/settings/PrivacySettings.java` at `onCreatePreferences`
To reproduce the bug: open privacy settings preference.
With v86 all new preferences must be listed in `NEW_PRIVACY_PREFERENCE_ORDER`

- [ ] "client_->CanUseSecureDnsTransactions()"
`net/dns/host_resolver_manager.cc` at `DnsTask` ctor
To reproduce the bug: just open chromium.
I think the problem is lack of dns doh address

### Expected behavior

No crash at all.

**Comment by csagan5** [comment]
Any idea how to fix these?

For (1) which preferences are causing it? I guess one of the new ones?
For (2) I understand why it happens: Bromite is in secure mode by default.

**Comment by uazo** [comment]
> Any idea how to fix these?
>
>For (1) which preferences are causing it? I guess one of the new ones?

```
Add a proxy configuration page
Add a option to not persist tabs
Add an always-incognito mode
Disable sync services menu
```

The patches to check are those that modify privacy_preferences.xml without adjust the key in NEW_PRIVACY_PREFERENCE_ORDER, I can do it and make you a pr.
The alternative could be to remove the dcheck if it gives us problems with the application of future fixes, because, I think, they will depend on each other.

> For (2) I understand why it happens: Bromite is in secure mode by default.

yes we have two ways to fix, I think: either leave kDnsOverHttpsFallbackParam to false, or put an address in kDnsOverHttpsTemplatesParam

**Comment by csagan5** [comment]
> The patches to check are those that modify privacy_preferences.xml without adjust the key in NEW_PRIVACY_PREFERENCE_ORDER, I can do it and make you a pr.

Please go ahead, I will fix the other problem with DoH.

**Comment by csagan5** [comment]
> * I think the problem is lack of dns doh address

This DCHECK should fail only if the user has enabled DoH in settings but specified no URLs; can we confirm/deny?

**Comment by uazo** [comment]
> This DCHECK should fail only if the user has enabled DoH in settings but specified no URLs; can we confirm/deny?

I tried uninstalling and reinstalling, the problem is that the flag is active bydefault but is without address (and not in automatic mode). This is the code https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/net/stub_resolver_config_reader.cc;l=126

**Comment by csagan5** [comment]
But the UI is enabled, the user setting should have precedence (it should be disabled by default in the Secure DNS settings UI).

**Comment by uazo** [comment]
> it should be disabled by default in the Secure DNS settings UI

it doesn't seem to be so, try a fresh install

**Comment by csagan5** [comment]
> it doesn't seem to be so, try a fresh install

Yes, this is the problem. The wrong option is pre-selected on a fresh install. I will fix this for next release.

**Comment by csagan5** [comment]
The secure DNS issue (#761) has been fixed; you can submit a patch for the other issue but it is harmless as far as I know (it causes no crashes).

**Comment by csagan5** [comment]
Please open a PR directly if/when you will have a patch for the other issue.
