### ISSUE TITLE
Adding search engine only works with certain Searx instances (possible solution included)

### ISSUE THREAD

**Issue by yurihentai** [bromite/bromite#759]
### Bromite version

Version: `85.0.4183.114`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is the bug a crash?

No

### Describe the bug

Adding a custom search engine works for certain Searx instances but not others. When analyzing each instance's opensearch.xml file, I noticed the one that works with bromite has `/?=` in the search query, and the ones that don't have a `/search?=`. Note that the opensearch.xml changes with certain browsers. I examined the opensearch.xml contents by downloading them through bromite.

### Steps to reproduce the bug

Example working instance:
1. go [here](https://searx.be) and look something up
2. kebab menu > settings > search engines > it's there, it shows up

Example non working instance:
1. go [here](https://search.disroot.org) and look something up
2. kebab menu > settings > search engines > it doesn't show up

You can examine the opensearch.xml by appending it to the url [like so](https://searx.be/opensearch.xml)

### Expected behavior

If it works for one searx instance but not another, then it's not a searx problem. If it works fine in ungoogled-chromium but not in bromite, then it's a bromite problem.

Comparing the two opensearch.xml files, the main difference between a working and nonworking instance is that a nonworking instance has `/search?q={searchTerms}` in the template attribute of the Url tag, and an instance compatible with bromite's interpretation of opensearch has `/?q={searchTerms}` in the same area.

A possible solution for this would be to simply take out `search` in the Url xml tag of the opensearch.xml (use regex or `.replace('/search', '/')`. I know you dislike/distrust Searx because anyone can host it, be it a good or bad organization, and there are also tons of closed issues about Searx as well, but I think this is something that should be genuinely looked at and solved, to put an end to the repetitive issues.

#### other notes

- [this](https://searx.ninja) is another example of a instance that works
- [this](https://searx.gnu.style) is another example of an instance that doesn't work
- if `search` isn't the issue then it's also likely that it could be a GET/POST issue. Some instances use POST instead of GET, however changing an instance's searx settings to use GET instead of POST does not solve the issue

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> No

Chromium behaves the same; you either report this issue to Chromium (if you think it is a bug in Chromium) or to the Searx instances you mentioned as not working.

> * Some instances use POST instead of GET,

Chromium supports only POST.
