### ISSUE TITLE
Rearrange three-dot menu

### ISSUE THREAD

**Issue by AndhikaWB** [bromite/bromite#76]
I think it's possible for the 'Exit' to be rearranged below 'Enable JavaScript' and 'Enable AdBlock' because it shall to be placed at the end of three-dot menu.

And if possible, it would be great if 'Help & feedback' from the menu be removed, most people will never use it anyway. Sorry for bad English.

EDIT: Added screenshot.
![img_20180624_223958](https://user-images.githubusercontent.com/17119394/41820809-e7766898-77c6-11e8-9d09-66829db963de.png)

**Comment by csagan5** [comment]
Yeah it looks bad, I will try to rearrange them. Never could get a grasp of how order works.

**Comment by AndhikaWB** [comment]
I think it would be good if you can rearrange 'Enable JavaScript' and 'Enable AdBlock' below the 'Desktop site' option, so we will have 3 checkbox es in a row.

I don't know tho.. Depends on how hard the code was written.

**Comment by csagan5** [comment]
@AndhikaWB that's how I implemented them originally in the XML: all close to the Desktop site checkbox.

However since I do not know well this Android menu format it never worked...

**Comment by csagan5** [comment]
Fixed in 67.0.3396.101
