### ISSUE TITLE
Crash when tapping on Safe Browsing option

### ISSUE THREAD

**Issue by chromer030** [bromite/bromite#760]
Version: `86.0.4240.66`
Arch: `arm64`
Android version: `7.1.2`

Is this bug about the SystemWebView?
No

Is the bug reproducible with latest version?
Yes

Is the bug a crash?
Yes

Screenshots :

![Screenshot_20201002-131158](https://user-images.githubusercontent.com/13361552/94910699-eef9c180-04b1-11eb-8430-0fa0bcec28ce.png)

**Comment by uazo** [comment]
related with https://github.com/bromite/bromite/issues/758

**Comment by csagan5** [comment]
@uazo it's unrelated to #758, it's due to a leftover menu entry in the XML file; will be fixed on next release.

**Comment by csagan5** [comment]
Fixed in `86.0.4240.70`.

**Comment by stevenchingch** [comment]
I see an 'account' title at the top of the settings page. Is that related to the XML ?
