### ISSUE TITLE
Include more filters in default filters.dat

### ISSUE THREAD

**Issue by krathalan** [bromite/bromite#762]
### Is your feature request related to privacy?
Yes.

### Is there a patch available for this feature somewhere?
Yes, you can find the script here: https://git.sr.ht/~krathalan/miscellaneous-scripts/tree/master/make_bromite_filter
Or clone the repo it is in: `git clone https://git.sr.ht/~krathalan/miscellaneous-scripts`

I have written a script which extracts the current built-in uBlock Origin filters, **adds some custom filters**, and compiles all filter files easily into a filter.dat file ready for use with Bromite. 

You must pass it the location of the `ruleset_converter` binary, e.g.:

` $ bash make_bromite_filter ~/downloads/ruleset_converter`

It downloads all the uBlock Origin filter list `.txt` files with `curl` into an ephemeral `/tmp` folder and outputs the `filters.dat` file in the current directory. It requires the `jq` program to parse the uBlock Origin `assets.json` that contains the list of default uBlock Origin filter lists.

I would be happy to remove the addition of custom filters, or add your own custom filters you already use for the default `filters.dat`. Or you can just fork it yourself and make the changes you want to make. Or you can just close this issue altogether if you already have your own process you like for making a `filters.dat` :) I just thought I would share mine.

### Describe the solution you would like
Building more filters into the default filter.dat.

### Describe alternatives you have considered
Hosting my own `filters.dat`, which I do, at [https://krathalan.net/kraths-filters.dat](https://krathalan.net/kraths-filters.dat). However, it would be nice to see the default filter list include the default uBlock filters. Most people cannot host their own `filters.dat`.

**Comment by krathalan** [comment]
Well I just read the https://github.com/bromite/bromite/wiki/AdBlocking wiki page, but I'm still not sure what mechanism you're using. Regardless, feel free to close if you want.

**Comment by csagan5** [comment]
@krathalan a selection of those uBlock origin lists is already included; I have published the lists used here: https://github.com/bromite/filters/blob/master/lists.txt

Which lists would you add? I cannot add them all indiscriminately, the current set has been tested.

**Comment by BUAWF** [comment]
@csagan5  Possible to add online malicious tracking, as this comes default with uBlock Origin.

**Comment by csagan5** [comment]
I will add those on next update.
