### ISSUE TITLE
Option to enable or disable auto-complete searches and URLs is missing

### ISSUE THREAD

**Issue by Poopooracoocoo** [bromite/bromite#763]
### Bromite version

Version: `86.0.4240.70`
Arch: `arm64`
Android version: `8.0`
Device model: `SM-G950FD`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug
In Chromium the setting is in Sync and Google services. In Bromite that is missing and the account heading remains there but is empty.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Try searching for something in the omnibox
2. No suggestions will show up (at least for me. I updated from Bromite 85 with no flags modified)

### Expected behavior
Auto-complete suggestions would show up and the setting would be in the privacy page.

**Comment by Poopooracoocoo** [comment]
ah #758 is related. as is the `Disable sync services menu` patch.

**Comment by csagan5** [comment]
#758 is not related. These menu entries have been reshuffled by upstream (moved to the account) so they need more work to be visible again.

**Comment by csagan5** [comment]
Fixed in `86.0.4240.73`.
