### ISSUE TITLE
google connect page stuck on loading after use bromite as system webview

### ISSUE THREAD

**Issue by rhjdvsgsgks** [bromite/bromite#765]
### Bromite version

Version: `version 86.0.4240.66`
Arch: `arm64`
Android version: `9.0`
Device model: `a Android phone with aosp-like system`

### Is this bug about the SystemWebView?

Yes

### Is the bug reproducible with latest version?

yes

### Can the bug be reproduced with corresponding Chromium version?

no

### Describe the bug

application which want to login with Google will stuck on loading animation that before "confirm page"

### Steps to reproduce the bug

Steps to reproduce the bug:
1. install and open dynamix(a game)
2. Click the "login with Google" botton on the upper right corner
3. See error(stuck on loading animation)

### Expected behavior

login successfully

### Screenshots

with bromite
![pic](https://user-images.githubusercontent.com/26178113/95013396-80db0900-062f-11eb-966b-1bd07c2aaf99.png)

with chromium
![pic](https://user-images.githubusercontent.com/26178113/95013426-b849b580-062f-11eb-8727-ba72a203c807.png)

**Comment by csagan5** [comment]
No support is provided for the SystemWebView; you could try debugging it with the developer tools.

The Bromite SystemWebView does not have any cloud integration, that might be the reason.
