### ISSUE TITLE
v86.0.4240.70 Video playback problem. 

### ISSUE THREAD

**Issue by Abrakian** [bromite/bromite#766]
### Bromite version

Version: v86.0.4240.70
Arch: arm64
Android version: Android 9.0
Device model: Pixel 3

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Is the bug a crash?
Yes and no (It shows the app crash pop-up window but the app itself still open.

### Describe the bug && Steps to reproduce the bug

￭Go to https://tools.woolyss.com/html5-audio-video-tester/?u=https://github.com/chromium/chromium/raw/master/media/test/data/bear-av1.webm
￭Open any videos that is NOT AV1 codec. 
￭See the crash pop-up window.

Also

Go on Twitter and open any videos will see the crash as well.

### Expected behavior

Playback any videos normally.

**Comment by csagan5** [comment]
@Abrakian we did some tests in #755; can you check if this version works for you?

https://fdroid.bromite.org/fdroid/bromite/v86_arm64_ChromePublic_AImageReader_patched.apk

**Comment by Abrakian** [comment]
> @Abrakian we did some tests in #755; can you check if this version works for you?
> 
> https://fdroid.bromite.org/fdroid/bromite/v86_arm64_ChromePublic_AImageReader_patched.apk

Just checked the version provided above; all video playback are normal. 
Thank you so much!

Should I close this issue now?

**Comment by csagan5** [comment]
No, I will close it with next release. Thanks for testing.

**Comment by Someguy1519** [comment]
I tested the AImageReader patched version of Bromite. Video playback no longer crashes Bromite but now sound doesn't work.

**Comment by Abrakian** [comment]
@Someguy1519 Are you using the version csagan5 provided above? 

I haven't encounter anything audio playback issue whatsoever.

**Comment by Someguy1519** [comment]
> @Someguy1519 Are you using the version csagan5 provided above?
> 
> I haven't encounter anything audio playback issue whatsoever.

Yes I have, sound in certain videos does not work for me.

**Comment by Abrakian** [comment]
> > @Someguy1519 Are you using the version csagan5 provided above?
> > I haven't encounter anything audio playback issue whatsoever.
> 
> Yes I am, sound in certain videos does not work for me.

Linking the webpage or the URL to the video that you are having problem with will be helpful here.

Steps to reproduce the issue && providing logs are also appreciated.

**Comment by Someguy1519** [comment]
https://www.thewatchcartoononline.tv/
Sound doesn't work on any of the videos on this site. Sound on videos worked fine on this site on previous versions of Bromite. How do I provide logs?

**Comment by csagan5** [comment]
@Someguy1519 does sound work on any other site? e.g. YouTube? Your volume might be set to 0.

**Comment by Someguy1519** [comment]
> @Someguy1519 does sound work on any other site? e.g. YouTube? Your volume might be set to 0.

Sound works fine on other sites. Just that particular site where sound doesn't work. I've tried adjusting volume and disabling and reenabling sound in site settings and it still doesn't work for that site.

**Comment by csagan5** [comment]
@Someguy1519 try to figure out which formats do not have audio from this page: https://tools.woolyss.com/html5-audio-video-tester/

Fixed in `86.0.4240.73`.

**Comment by Someguy1519** [comment]
@csagan5 The .mp4 file with Chimera in its filename does not have audio.

**Comment by csagan5** [comment]
@Someguy1519 please follow #755 for the discussion of this problem.
