### ISSUE TITLE
Bromite's website apk download redirects to 404

### ISSUE THREAD

**Issue by albertocoronado** [bromite/bromite#767]
### Bromite version

Version: `83.0...`
Arch: `arm` or `arm64` or `x86`
Android version: (example: `9.0`)
Device model: (example: `SM-G960UZKABST`)

### Is this bug about the SystemWebView?
Yes/No

### Steps to reproduce the bug

Steps to reproduce the bug:
2. Click on '...'
3. Scroll down to '...'

**Comment by albertocoronado** [comment]
The title is the problem. I couldn't figure out another wat to report it.

**Comment by frankjrp** [comment]
@albertocoronado @csagan5 That's because the file name doesn't have the term "Modern" anymore. It used to be like this: **arm64_ChromeModernPublic.apk**.

**Comment by csagan5** [comment]
Thanks; fixed.
