### ISSUE TITLE
Bromite can't open with hidden core module

### ISSUE THREAD

**Issue by lucius100** [bromite/bromite#768]
### Bromite version

Version: 86.0.4240.73
Arch: `arm64
Android version: 10
Device model: Redmi Note 5 Pro Whyred

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?

86.0.4240.73

### Is the bug a crash?

yes

### Describe the bug

Can't open/use/start bromite

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Install Xposed framework
2. Install Hidden core module
3. Activate it.

### Expected behavior

Bromite Closed on itself. It doesn't want to start.

**Comment by Ridwan-Sobirin** [comment]
Mine starts without normally.
Bromite: 86.0.4240.73 arm64
Realme 5 pro PE+ A10
Edxposed + hiddencore module v1.3

**Comment by csagan5** [comment]
@lucius100 can you locate the crash in the logcat?
