### ISSUE TITLE
Password autofill dosen't work

### ISSUE THREAD

**Issue by paritosh9199** [bromite/bromite#769]
The autofill services are not being triggered to open while filling up login forms on various websites. Previously services like Bitwarden, Firefox Lockwise prompted autofill suggestions which dosen't happen anymore on the latest update.

**Comment by csagan5** [comment]
It should be fixed on next release.

**Comment by paritosh9199** [comment]
This issue is still not fixed in the latest update!

**Comment by csagan5** [comment]
What was fixed is the default state of autofill for the forms; for the autofill framework see https://github.com/bromite/bromite/blob/master/FAQ.md#does-bromite-support-the-android-autofill-framework
