### ISSUE TITLE
Change Chrome and Chromium related string to Bromite

### ISSUE THREAD

**Issue by AndhikaWB** [bromite/bromite#77]
It's like changing 'About Chrome' to 'About Bromite', 'Copyright 2018 Google Inc' to 'Copyright 2018 Bromite authors' etc.

Some strings in 'Settings - Privacy' also contain Google and Chrome related string. Although it would be greater to remove unused features from the privacy settings (Security Reports, etc) rather than just changing the string.

**Comment by bn0785ac** [comment]
remove it is expensive ... but bromite bans it (it can't work)

the first i could do myself :+1:

**Comment by csagan5** [comment]
@AndhikaWB coincidentally I had already started this process, so in next release it should look better already :)

**Comment by csagan5** [comment]
Fixed in 67.0.3396.101
