### ISSUE TITLE
Further fingerprint deception

### ISSUE THREAD

**Issue by FreddieOliveira** [bromite/bromite#773]
### Is your feature request related to privacy?

Yes, more specifically to device detection privacy.

### Is there a patch available for this feature somewhere?

Yes, Fennec/Firefox and Tor Browser don't suffer from this problem.

### Describe the solution you would like

When using https://panopticlick.eff.org/ I realized that my GPU model, platform, RAM amount and number of processor cores aren't forged. Despite forging my device model in the user-agent header, it's relatively easy to discover my real device using these values:

![foo](https://user-images.githubusercontent.com/9597536/95506159-fed84080-099e-11eb-9582-3aa13050e679.png)

I'd like for those values to be forged as well.

### Describe alternatives you have considered

Alternatively to forging those values, it's also possible to simply don't give them at all. That's what Fennec/Firefox and Tor Browser do. If you visit https://panopticlick.eff.org/ using them you'll notice that none of GPU and RAM are given, while platform and cores are forged.

**Comment by csagan5** [comment]
> I'd like for those values to be forged as well.

There is no privacy violation in showing all the entries you highlighted to the world; they do not allow to identify anyone individually. You can disable the WebGL one by disabling WebGL.

See also: https://github.com/GrapheneOS/Vanadium/issues/77 and https://github.com/Eloston/ungoogled-chromium/issues/429#issuecomment-422265119
