### ISSUE TITLE
INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION error when installing

### ISSUE THREAD

**Issue by Niek** [bromite/bromite#774]
This issue is happening when installing the latest x86 build of ChromiumPublic.apk (86.0.4240.73):

```bash
$ wget "https://github.com/bromite/bromite/releases/download/86.0.4240.73/x86_ChromePublic.apk" -o bromite.apk
$ adb install bromite.apk
adb: failed to install bromite.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl1211872301.tmp/base.apk: AndroidManifest.xml]
```

Let me know if you need any further details.

**Comment by Niek** [comment]
Output of adb logcat:
```
10-09 09:09:33.644    35    35 I         : free_cache(159344) avail 46314651648
10-09 09:09:33.659   112   138 D         : Zip: EOCD not found, /data/app/vmdl77833989.tmp/base.apk is not zip
10-09 09:09:33.659   112   138 W zipro   : Error opening archive /data/app/vmdl77833989.tmp/base.apk: Invalid file
10-09 09:09:33.659   112   138 D asset   : failed to open Zip archive '/data/app/vmdl77833989.tmp/base.apk'
10-09 09:09:33.660   112   138 E PackageInstaller: Commit of session 77833989 failed: Failed to parse /data/app/vmdl77833989.tmp/base.apk: AndroidManifest.xml
```

**Comment by csagan5** [comment]
Please submit the issue in desktop mode and following the issue template, then it will be possible to find out what the problem could be. It is either a wrong Android version or wrong Android architecture.

**Comment by Niek** [comment]
Here is the info from the template, not sure if it helps:



### Bromite version

Version: `86.0.4240.73`
Arch: `x86`
Android version: `7.0`
Device model: `anbox virtual device`

### Is this bug about the SystemWebView?
No



### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No, the Chromium version installs fine.

### Is the bug a crash?

No

### Describe the bug

Latest APK image does not install on x86

### Steps to reproduce the bug

Steps to reproduce the bug:
```bash
$ wget "https://github.com/bromite/bromite/releases/download/86.0.4240.73/x86_ChromePublic.apk" -o bromite.apk
$ adb install bromite.apk
adb: failed to install bromite.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl1211872301.tmp/base.apk: AndroidManifest.xml]
```

### Expected behavior

Installation should succeed.

**Comment by csagan5** [comment]
I cannot reproduce this issue. Have you verified that the file has the correct sha256 hash?

**Comment by Niek** [comment]
Same issue here with the latest x86 APK:
```bash
$ wget "https://github.com/bromite/bromite/releases/download/87.0.4280.106/x86_ChromePublic.apk" -o bromite.apk
$ adb install bromite.apk
adb: failed to install bromite.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl919221023.tmp/base.apk: AndroidManifest.xml]
```

The host is Anbox running Android 7:
```bash
$ adb shell getprop ro.build.version.release
7.1.2
$ adb shell getprop ro.build.version.sdk
25
```

**Comment by csagan5** [comment]
@Niek what is the sha256 hash of the file you downloaded?

**Comment by Niek** [comment]
Oops, I found the issue... note to self: curl uses `-o`, wget uses `-O`. If you use lowercase `-o` with wget, you pipe the stdout to the file and not the content. 

@csagan5 Thanks for the assistance!
