### ISSUE TITLE
Flag not working: Show darkened search page on Android

### ISSUE THREAD

**Issue by godlyatheist** [bromite/bromite#778]
### Bromite version

Version: `86.0.4240.92`
Arch: `arm`
Android version: `10.0`
Device model: `SM-A716U`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug

Enabling the flag #enable-android-dark-search does not make search result page use dark mode

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to 'chrome://flags"
2. Search '#enable-android-dark-search'
3. Change the flag from Default to Enabled
4. Relaunch Bromite
5. Make any search in the address bar
6. Results page does not use dark mode

### Expected behavior

After step 5 above, results page should use dark mode. Using the "Darken Website" option in Settings-Theme will force the results page to be dark along with all website, but it's not the desired outcome.

**Comment by csagan5** [comment]
> Can the bug be reproduced with corresponding Chromium version?
> No

Behaviour is the same for Chromium.

**Comment by riricky** [comment]
I tried and it's working on chromium. The bug seems only affect bromite app

**Comment by csagan5** [comment]
> I tried and it's working on chromium. 

It is not. I tried with a freshly installed Chromium and it behaves identically. See also #716
