### ISSUE TITLE
One patch failing to apply and more details on build process/settings 

### ISSUE THREAD

**Issue by dan-v** [bromite/bromite#78]
**Version**
Version: `v67.0.3396.95`
Arch: `arm64`

**Is the bug reproducible with latest version?**
Yes.

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No.

**Is the bug a crash?**
If yes then individuate and post the logcat dump (remove privacy sensitive information, if any), otherwise remove this section.
No.

**Describe the bug**
I'm trying to build Chromium with your patches applied to it and having an issue with one patch. I have a few questions:
* There is one patch that is failing to apply (0020 Removed Sync and Translate menu) - you can see output in reproduce section below. I can skip this patch, but wondering how you apply for your builds?
* How do you choose what version of Chromium to build? It looks like you are ahead of current stable (67.0.3396.87) - is there anything you specifically target?
* I'm also curious about your build process in general, I'm assuming you have a script that handles producing all of the APKs - is this something that is publicly available? What do your args.gn options look like? For example, this is what mine currently looks like:
```
target_os = "android"
target_cpu = "arm64"
is_debug = false

is_official_build = true
is_component_build = false
symbol_level = 0

ffmpeg_branding = "Chrome"
proprietary_codecs = true

android_channel = "stable"
android_default_version_name = "$CHROMIUM_REVISION"
android_default_version_code = "$DEFAULT_VERSION"
```

**To Reproduce**
```
  CHROMIUM_REVISION="67.0.3396.95"
  DEFAULT_VERSION=$(echo $CHROMIUM_REVISION | awk -F"." '{ printf "%s%03d52\n",$3,$4}')
  git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git $HOME/depot_tools
  export PATH="$PATH:$HOME/depot_tools"
  mkdir -p $HOME/chromium
  cd $HOME/chromium
  fetch --nohooks android --target_os_only=true || true
  cd src
  git checkout "$CHROMIUM_REVISION" -f 
  git clean -dff
  yes | gclient sync --with_branch_heads --jobs 32 -RDf
  
  git clone --branch ${CHROMIUM_REVISION} https://github.com/bromite/bromite.git ~/bromite
  git am ../../bromite/patches/*.patch
Applying: Increase maximum connections per host from 6 to 15
Applying: Disable third-party cookies by default
Applying: Restore classic new tab page
Applying: Disable battery status service
Applying: Disable GCM status check
Applying: Disable updater pings
Applying: prefs: only keep cookies until exit
Applying: Remove EV certificates
Applying: promo: disable Google promotion fetching
Applying: Disables omission of URL elements in Omnibox
Applying: Modify default preferences
Applying: Do not store passwords by default
Applying: Disable NTP remote suggestions by default
Applying: Disable references to fonts.googleapis.com
Applying: Disable WebRTC by default
Applying: Disable data saver
Applying: Skip the first run and metrics
Applying: Disable signin and data saver preferences
Applying: Disable signin/data reduction promos
Applying: Removed Sync and Translate menu
error: removal patch leaves file contents
error: chrome/android/java/res/drawable-hdpi/settings_translate.png: patch does not apply
error: removal patch leaves file contents
error: chrome/android/java/res/drawable-mdpi/settings_translate.png: patch does not apply
error: removal patch leaves file contents
error: chrome/android/java/res/drawable-xhdpi/settings_translate.png: patch does not apply
error: removal patch leaves file contents
error: chrome/android/java/res/drawable-xxhdpi/settings_translate.png: patch does not apply
error: removal patch leaves file contents
error: chrome/android/java/res/drawable-xxxhdpi/settings_translate.png: patch does not apply
Patch failed at 0020 Removed Sync and Translate menu
The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```

**Expected behavior**
I expect the patches to cleanly apply and would just like to better understand the build process producing these binaries.

**Screenshots**
N/A.

**Comment by tectiv3** [comment]
I also tried .88, .92 and .95 - all failed.
With .88 and .92 failing on `components/gcm_driver/gcm_channel_status_request.cc`

**Comment by csagan5** [comment]
@dan-v I get exactly the same error with that patch :) not sure there is anything we can do about it...it is a limitation of `git apply`: no matter how I create the patch, if it includes a file deletion it will always fail like that or with a different error.

These days I simply fix that specific patch manually and continue the `git am`. I have been thinking to use a modified `git-am.sh` script but I did not do anything yet. If you know about a way to apply patches with deletions (and varying index blobs), please let me know.

> How do you choose what version of Chromium to build?

I pick the latest tag of the current stable major version, so right now latest tag of `v67` (whichever it is).

> I'm also curious about your build process in general, I'm assuming you have a script that handles producing all of the APKs - is this something that is publicly available? What do your args.gn options look like? For example, this is what mine currently looks like:

I had published a version of my build scripts when I was trying to make this work for F-Droid: https://github.com/bromite/bromite/tree/for-fdroid/fdroid

They are however **unsupported** as unfortunately I have no interest/time to support the countless attempts to build Chromium (it is fairly complex, we all have to agree) of all developers of varying degree of expertize (although I strongly encourage that has many people as possible do try to build Chromium to keep it open source).

The scripts have been adapted & improved & extended in this other Chromium fork: https://gitlab.com/thermatk/Unobtainium/

So maybe you can get better support for the build there?

**Comment by csagan5** [comment]
@tectiv3 the patches for .95 are printed from a .95 tree, so you need to use the exact tag or fix the patches yourself.

All published patches work with the corresponding Bromite/Chromium tag.

(If you cannot get out of a failure like the above...well sorry that's why I do not support the build of Chromium, it's too much of a pain :) )

**Comment by dan-v** [comment]
awesome - thanks for the details @tectiv3! much appreciated! also, thanks for your work on keeping these patches up to date!
