### ISSUE TITLE
feature request: "always view the desktop site for all websites"

### ISSUE THREAD

**Issue by frknltrk** [bromite/bromite#780]
### Is your feature request related to privacy?

No.

### Is there a patch available for this feature somewhere?

I know a couple of browsers have that feature but don't know anything about a related patch.

### Describe the solution you would like

An option in settings/preferences which make the browser view the desktop version for all the websites user visits. That is a killing feature for tablet users.

### Describe alternatives you have considered

Support for "Chrome Extensions" so that user can install a "user agent switcher" extension and that extension handles the job.

**Comment by csagan5** [comment]
@uazo interested in this?

**Comment by furkanunluturkk** [comment]
- since old Fennec is gone - now there are actually just a few browsers in F-droid and only 1 is a good fit for tablets to cap it off. if there was such an option, i'd definitely go for Bromite for good.

**Comment by chromer030** [comment]
It's a high demand feature for Tablets , please add it as option or flag.
Will be great.
Thanks very much...

**Comment by furkanunluturkk** [comment]
any progress/news about this?

**Comment by uazo** [comment]
> any progress/news about this?

lack of time! I'm working on it today, almost done.
@csagan5 I thought I'd put it in the settings homepage ...

**Comment by csagan5** [comment]
@furkanunluturkk it is an open source project, people work on the issues as they have time and please.

@uazo do it second your pace; I think it would make more sense as a global site setting

**Comment by furkanunluturkk** [comment]
> @furkanunluturkk it is an open source project, people work on the issues as they have time and please.
> 
> @uazo do it second your pace; I think it would make more sense as a global site setting

i'm totally aware of it and don't have a mind to pressure you guys. it was just out of curiosity. thanks for your great efforts!
btw, is there any way to donate to Bromite project other than Paypal since it's a invalid method in my country. Liberapay doesn't seem to have a credit card option.

**Comment by uazo** [comment]
> as they have time and please

sure, don't worry, it's pure hobby for me

> I think it would make more sense as a global site setting

yes, I think so too but if I put it in the homepage settings I modify fewer files.

unfortunately, if I change

https://source.chromium.org/chromium/chromium/src/+/master:components/browser_ui/site_settings/android/java/src/org/chromium/components/browser_ui/site_settings/SiteSettings.java

I have some problem with dependencies (see https://source.chromium.org/chromium/chromium/src/+/master:components/) which means to modify many files. 

@csagan5  since then who keeps it updated is you, I'll make two versions, then you choose which one to use.

**Comment by Poopooracoocoo** [comment]
Here's what Brave's settings look like :)
![rsz_brave_site_settings](https://user-images.githubusercontent.com/51363864/97104510-7e3c7280-1708-11eb-92ce-490be0afde3c.jpg)
![rsz_brave_desktop_mode_off](https://user-images.githubusercontent.com/51363864/97104508-7da3dc00-1708-11eb-9465-1860e40962a5.jpg)
![rsz_brave_desktop_mode_on](https://user-images.githubusercontent.com/51363864/97104506-7c72af00-1708-11eb-8568-2d335232757b.jpg)

They say that it applies to new tabs.

**Comment by csagan5** [comment]
Fixed in `86.0.4240.181`.

**Comment by chromer030** [comment]
@csagan5  Tested 86.0.4240.181 , working great but it affect on chromium internal pages also for example about:version or about:gpu which make texts and output unpleasant on smartphones. isn't it possible to exclude this pages when bromite is running in smartphone not a Tablet ,  or provide a section in User Agent menu for specifying excluded addresses ?

**Comment by csagan5** [comment]
@uazo on the regular Chromium the `Desktop site` toggle is not visible for native pages, so this never happens. I guess in Bromite we should not set the user agent if the page is native.

**Comment by uazo** [comment]
> toggle is not visible for native pages,

maybe it is a bit more complex, I have to check.
you can know if the navigation is towards a native page (in this case a webui) only after having opened a new tab and after navigation, but that tab, however, with the flag activated has already preset the desktop mode.

I think the same behavior exists in chromium: open the tab, select desktop mode and navigate to chrome://flags, probably the page appears in desktop mode.

I had seen somewhere a method that tells me if a page is native by checking the url, but I don't remember where I had seen it.
in any case, somehow I try to fix it

**Comment by csagan5** [comment]
> I think the same behavior exists in chromium: open the tab, select desktop mode and navigate to chrome://flags, probably the page appears in desktop mode.

Yes, I verified it is like that.



> I had seen somewhere a method that tells me if a page is native by checking the url, but I don't remember where I had seen it.
> in any case, somehow I try to fix it

You can look for example at this: https://source.chromium.org/chromium/chromium/src/+/master:chrome/utility/importer/bookmarks_file_importer.cc;drc=df872ce8fcce25af51aa6b0f9fe8b1135b687524;bpv=1;bpt=1;l=34

There might be other methods that do similar checks.

**Comment by uazo** [comment]
thanks, but I need a java version, what about this?

https://source.chromium.org/chromium/chromium/src/+/master:components/embedder_support/android/java/src/org/chromium/components/embedder_support/util/UrlUtilities.java;l=96

**Comment by csagan5** [comment]
Yes, that is even better.

**Comment by csagan5** [comment]
@uazo I found another bug today: the tabs are restored with the user agent that was set when session was frozen, however the hamburger menu starts always unticked. So you can see a tab in desktop mode while the toggle is off.

**Comment by uazo** [comment]
> the tabs are restored with the user agent that was set when session was frozen, however the hamburger menu starts always unticked

I cannot reproduce this bug. Could you tell me the steps you take?

**Comment by csagan5** [comment]
> I cannot reproduce this bug. Could you tell me the steps you take?

Don't worry, it's too hard to reproduce it. Let's ignore it for now.

**Comment by Poopooracoocoo** [comment]
The toggle is named differently when it's enabled and disabled and reflects its current state. This is not a good experience. Could you please update it to show what will happen when you enable the toggle? :)

**Comment by uazo** [comment]
as I think like @Poopooracoocoo too, patch #807 contains an improvement in that direction
