### ISSUE TITLE
Canvas Fingerprinting 100% Unique

### ISSUE THREAD

**Issue by sergiok707** [bromite/bromite#782]
### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

Unfortunately, I do not know

### Describe the solution you would like

I checked the uniqueness of the prints here: browserleaks.com/canvas
When using Bromite, it always shows a 100% unique fingerprint
I checked on different devices without Bromite, this value is always 95 - 99.88%
I would like this print not to be 100% unique and merge with the total mass of devices

### Describe alternatives you have considered

N/A

**Comment by csagan5** [comment]
See https://github.com/bromite/bromite/wiki/Fingerprinting
