### ISSUE TITLE
Customize Question: How To Modify the New Tab List of Sites?

### ISSUE THREAD

**Issue by gregbythebeach** [bromite/bromite#783]
### Is your feature request related to privacy?
NO

### Is there a patch available for this feature somewhere?
Not aware of.

### Describe the solution you would like
Sites I visit keep building up there in screenshot, is there a way to turn that off? I dont want any icons or sites there. Or at least be able to control what is there.

### Describe alternatives you have considered
Have not found any. Is there a flag perhaps? I tried a few flags I searched but none worked.

Android 9.0
Galaxy s8
Bromite 86.0.4240.92

![95799574-f5561d80-0ca9-11eb-8dc0-5814ef485914](https://user-images.githubusercontent.com/72770751/96046057-bc43b780-0e27-11eb-8381-f68226353f2b.jpg)

**Comment by csagan5** [comment]
For questions refer to Reddit or XDA; one way to disable NTP tiles is to set your home page to `about:blank`.
