### ISSUE TITLE
Browsers that use Bromite System Webview crashes whenever try to download a file

### ISSUE THREAD

**Issue by LITRCA** [bromite/bromite#785]
### Bromite version

Version: `86.0.4240.112`
Arch: `arm64`
Android version:  `10.0`
Device model: `TA-1062`

### Is this bug about the SystemWebView?
Yes

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
Yes
```
time: 1603500218423
msg: Native crash: Trap
stacktrace: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/coral/coral:10/QQ3A.200805.001/6578210:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2020-10-24 08:43:37+0800
pid: 24163, tid: 24260, name: ThreadPoolForeg  >>> mark.via <<<
uid: 10213
signal 5 (SIGTRAP), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:jni_android.cc(138)] Failed to find class org/chromium/components/download/DownloadCollectionBridge
'
    x0  0000000000000000  x1  0000000000000081  x2  000000007fffffff  x3  0000000000000000
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  7f7f7f7fff7fff7f
    x8  0000000000000000  x9  0000000000000000  x10 0000000000000000  x11 00000000ffffff80
    x12 00000076ede238b0  x13 ffffffffffffffff  x14 0000000000000004  x15 ffffffffffffffff
    x16 00000077fbc21950  x17 00000077fbbb0220  x18 00000076f48fc000  x19 00000076f5798388
    x20 00000076f57983a0  x21 00000076f5798398  x22 00000076f5797ec0  x23 00000077fbc1b568
    x24 0000007725189000  x25 00000076f5799020  x26 000000000000006a  x27 00000076f5798370
    x28 0000000000000000  x29 00000076f5798310
    sp  00000076f5797eb0  lr  0000007722a08958  pc  0000007722a08b40

backtrace:
      #00 pc 000000000263eb40  /system/app/Bromite/lib/arm64/libwebviewchromium.so (BuildId: 92534070b2e5a2f6b8a007de26b6561185124ed9)
```

### Describe the bug

Some browsers use system webview instead of a built-in webview kernel to reduce size.
etc. Via ( mark.via )
I have try several browsers of this type, all of them crash whenever I try to download a file.
This bug is 100% reproducible in 86.0.4240.112 and 86.0.4240.99, but never occurs in 85.0.4183.114 and several versions I used before.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to 'https://github.com/bromite/bromite/releases/tag/86.0.4240.112'
2. Click on 'arm64_SystemWebView.apk'
3. See error

### Expected behavior

Pop-up a dialog box confirming the download, while the browser keep running and showing the page normally instead of crash.

**Comment by csagan5** [comment]
Can someone confirm this issue with a similar setup? The stacktrace does not allow to understand much of the problem.

NOTE: there is no support provided for the SystemWebView builds, they might fail on different devices for a multitude of reasons.

**Comment by GeoZac** [comment]
> Can someone confirm this issue with a similar setup? The stacktrace does not allow to understand much of the problem.
I can confirm the issue but the stacktrace is similar to the one in the OP.

**Comment by csagan5** [comment]
@AlreadyFree can you test with the [Chromium SystemWebView](https://www.bromite.org/chromium)?

**Comment by AlreadyFree** [comment]
I would test chromium to see if this was a bug in the main code or a bromite specific bug, but I've always used the nanodroid magisk module to install bromite and updated through fdroid, so I'm really not sure how to install chromium otherwise. I did go back and test earlier bromite versions though and i cam confirm that the problem was introduced with version  86.0.4240.92.
