### ISSUE TITLE
ad block

### ISSUE THREAD

**Issue by sfoklus** [bromite/bromite#786]
Hi, I just wanted to point out that for some reason the adblock does not work properly, as ads appear on every site I visit. 
I tried to clear it's data and reset it and even reinstall the whole app.
Is there any way I can fix this?
I'm new here, so let me know if I'm missing anything, or if it's not the right "category" or "section" to cite this problem.

**Comment by csagan5** [comment]
Please submit the issue from GitHub desktop so that you can fill in the template; without filling-in the template it is not possible to help you correctly, to understand what is the issue or to try to reproduce it.
