### ISSUE TITLE
Search Ready Omnibox flag not working

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#789]
### Bromite version

Version: `86.0.4240.112`
Arch: `arm64`
Android version: `9.0`
Device model: `Galaxy S20`

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Describe the bug

Enabling the `Search Ready Omnibox` flag does not work, the feature stays off.

**Comment by Balachandarsmr** [comment]
These two flags do nothing after enabled. 
chrome://flags/#omnibox-search-ready-incognito
chrome://flags/#enable-search-ready-omnibox

**Comment by csagan5** [comment]
Fixed in `86.0.4240.194`.

**Comment by Balachandarsmr** [comment]
Thank you. It's working. Now bromite is my default browser.
