### ISSUE TITLE
Random and awful questions

### ISSUE THREAD

**Issue by bn0785ac** [bromite/bromite#79]
A
* How can i get chromium tarballs (as bromite do) ... when  buildslave is _crazy_ and doesnt wanna give tarballs

B
* What files should i copy  (from bromite) for get **native adblock** functions  ... _wihout install ublock_

**Comment by csagan5** [comment]
@bn0785ac your first question does not make sense...you are not explaining what is a buildslave. For Bromite I do not use any tarball, just git.

Sorry, I do not offer support for the build process; the patches are named and contain a description, you can easily find them. The only other file you would need is the filters file.
