### ISSUE TITLE
Oauth does not return to app

### ISSUE THREAD

**Issue by DefiCzech** [bromite/bromite#790]
### Bromite version

Version: `86.0.4240.112`
Arch: `arm64`
Android version: `11.0`
Device model: `RP1A.201005.006`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
Yes

### Describe the bug
In app Showly 2 I tried connect to trakt.tv account. Login to account and confirmation was in bromite. After confirmation thé bromite does not reopen the app Showly.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Install Showly 2 https://github.com/michaldrabik/Showly-2.0
2. Open app And open settings by clicking on cog wheel
3. Click on first item `trakt.tv authorization` and open in Bromite
4. Login to trakt.tv and allow showly 2 to use your account.
5. Click to `Yes`
6. Here Is bug, you Are staying in bromite and authorization does not reflect to Showly app.

### Expected behavior
After confirmation on trakt.tv the initial app should reopen as in Chrome or Firefox.

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> Yes

You need to report this bug upstream on the Chromium issue tracker.
