### ISSUE TITLE
Request for bromite launcher icon.

### ISSUE THREAD

**Issue by marchingon12** [bromite/bromite#795]
### Is your feature request related to privacy?
Nope

### Is there a patch available for this feature somewhere?
Nope

### Describe the solution you would like
#258
Just read this, could @csagan5 maybe provide our group with the mipmap-xxhdpi scaled icon via email? We're currently doing a list of open-source apps we recommend and we couldn't find the bromite icon anywhere within the repo. We usually use app/src/main/mipmap-xxhdpi/ic_launcher for icons, but since your repository does not include the icon for fraud issues (which I only found out recently), we'd like to request an icon per mail like you did with the privacytools.io team. This will then understandably not be uploaded online openly in any way possible (it will be uploaded directly onto the README.md, not in .assets). You can view our list here: https://codeberg.org/cami/foss_app_list/src/branch/marchingon12-patch-no-table. The list is not completed yet, we're first looking for every icon to include if possible.

### Describe alternatives you have considered

We could take the icon from privacytools.io or https://raw.githubusercontent.com/bromite/bromite.github.io/master/bromite.png  but since you said in some issue posts that that would be a copyright infringement, we're requesting one via email instead.

**Comment by csagan5** [comment]
The logo is not provided in this repository on purpose to make spoofing a bit more difficult.

> you said in some issue posts that that would be a copyright infringement

That is correct, when someone is provided with any material without a license then the default copyright rules apply; in the case of this project (or any other open source project) it is ok to use the logo for "fair use", but it is not fair to create another app and give it the same name/logo.

Feel free to use that PNG or SVG; I did not explicitly vet or approve its use in https://github.com/privacytools/privacytools.io/pull/1563 but it also falls under "fair use".

**Comment by marchingon12** [comment]
Alright, thanks for your confirmation.
