### ISSUE TITLE
FDroid Repo extremly slow

### ISSUE THREAD

**Issue by Jowat97** [bromite/bromite#797]
Hello there,

the download of an update from the FDroid Repo take up to 20 minutes. This occurs for the Bromite Webbrowser, as well as for the WebView App. Sometimes the download stops also right out of nowhere and I have to start it from the beginning. So to update both apps, it took sometimes up to one hour! And the worst part is, that the display needs to be turned on the whole time and I am not even allowed to get out of the Fdroid app. I't wont download the app in the background.

Don't get me wrong, I love your app and appreciate the hard work behind it. But we have the year 2020 and I need to let my Smartphone turned on up to one hour, without the possibility to use it, just to update two apps? Just for comparison: The update of a new Brave Version takes me about 6-7 seconds and can be done in the background.

This problem occurs already for a long time. But it seems like that it is getting even more worse. I think that there is something pretty wrong with the server, which you are using for the Repo.

BR

**Comment by csagan5** [comment]
The server is GitHub servers, which run on Amazon S3; you need to report this issue to the [F-Droid Client repository](https://gitlab.com/fdroid/fdroidclient/-/issues).

**Comment by uazo** [comment]
> And the worst part is, that the display needs to be turned on the whole time and I am not even allowed to get out of the Fdroid app. I't wont download the app in the background.

as a workaround to this problem, you could try to change the settings of the doze subsystem in android, allowing access to the network for fdroid even with phone in standby  (System Settings/Battery/Battery Optimization/Don’t optimize). 
it worked for me
