### ISSUE TITLE
Allow custom user agent

### ISSUE THREAD

**Issue by gene-scape** [bromite/bromite#798]
### Is your feature request related to privacy?
Yes, it allows for greater privacy by being able to set a more generic user agent, causing the browser fingerprint to be less unique and identifyable. As a side effect, users would gain the ability to circumvent site/feature blockades that are becoming more and more common.

### Is there a patch available for this feature somewhere?
Not to my knowledge.

### Describe the solution you would like
An option to manually enter a custom user agent, or at the very least an option to choose a user agent from a list.

### Describe alternatives you have considered
Tried using the desktop mode, but even though it changes the user agent - it does exactly what it's intended for.. displaying pages as if they're on desktop. This is not needed, nor preferred, in most cases, when only the user agent needs to be changed.

**Comment by csagan5** [comment]
> Yes, it allows for greater privacy by being able to set a more generic user agent, causing the browser fingerprint to be less unique and identifyable.

See https://github.com/bromite/bromite/wiki/Fingerprinting for the strategy in Bromite. There is no intention to make the browser less unique but only less identifiable.

> Tried using the desktop mode, but even though it changes the user agent - it does exactly what it's intended for.. displaying pages as if they're on desktop. This is not needed, nor preferred, in most cases, when only the user agent needs to be changed.

Desktop mode changes the user agent, you will get the same "desktop mode" with every non-mobile custom user agent.

**Comment by csagan5** [comment]
@uazo shall we add a text box to paste an user agent there? My concerns are:
* little value
* for every new bug report we have to question whether the reporter changed the UA or not

**Comment by uazo** [comment]
one question: do we allow mobile or desktop customization ua? or both?

**Comment by csagan5** [comment]
@uazo I would say the desktop one

**Comment by csagan5** [comment]
Fixed in `87.0.4280.68`.

**Comment by DI555** [comment]
> @uazo I would say the desktop one

why would we may possible to change a bouth - desktop one and mobile one - that'll be wiser !!!
