### ISSUE TITLE
Connections to Google servers

### ISSUE THREAD

**Issue by Primokorn** [bromite/bromite#8]
Hi,

I noticed two connections to Google servers while Bromite wasn't running in the foreground.
![2](https://user-images.githubusercontent.com/5938828/31810597-a41e8146-b57c-11e7-88c8-fd225633cc68.PNG)
![screenshot_20171020-080315](https://user-images.githubusercontent.com/5938828/31810598-a451344c-b57c-11e7-8599-5f08d4049420.png)
![1](https://user-images.githubusercontent.com/5938828/31810599-a4861360-b57c-11e7-8922-f12bd855e74a.PNG)

(And today 172.217.21.228 which is also Google).
DuckDuckGo has been set to the default search engine and I didn't use Bromite when these have been established.
Can the filters/patches be strengthened?

Cheers!

**Comment by csagan5** [comment]
Hi there,

actually, I am afraid the answer is no. The goal of [Inox patchset](https://github.com/gcarq/inox-patchset) is more in line with your desire here (I am contributing also patches to that project, but it's separate).

Bromite is more targeted for regular users that do want to use Google features, although trying to disable invasive behaviour where possible.

I will indeed try to pick more patches from Inox in future, but that project is fine with breaking the integration with Google services while here at Bromite we want to keep it (just make it opt-in, rather than always on).

**Comment by Primokorn** [comment]
Gotcha.
I'm using Inox on my Manjaro so thanks for your contribution.
Actually I was surprised to see more connections to Google servers with this browser compared to my other 'Google' browser called [Snapdragon SWE Browser](https://forum.xda-developers.com/android/apps-games/app-code-aurora-swe-browser-m55-t3523365) which is based on Chromium.

**Comment by csagan5** [comment]
Bromite is really just Chromium + some cherry-picked patches for adblocking and privacy, and some other patches developed exclusively for Bromite (like click-tracking removal from Google search results, work in progress).

So far I have not included too invasive Inox/Iridium patches to try to allow some Google services integrations (they work if you use own API keys). I will likely include more patches, minus their explicit/careless breakage.

Compared to other browsers, Bromite is fully open source and all patches are published under GPLv3; closing for now.

If you have other patches to propose for inclusion, you can always submit them individually either as issues or PRs.

**Comment by csagan5** [comment]
BTW, according to some Chromium source code comments, it should be enough to disable all background data from the settings and these connections should not happen.

**Comment by csagan5** [comment]
> So far I have not included too invasive Inox/Iridium patches to try to allow some Google services integrations (they work if you use own API keys). 

I discovered that this is not true; nothing works, so there is no loss of feature.
Regardless I have added patches to tackle as much as possible the unwanted calls to Google servers.

**Comment by csagan5** [comment]
@Primokorn what is the status of this issue? Although I do not plan to block all of them, do you see still some connections going to Google in latest version? They should have been reduced sensibly

**Comment by Primokorn** [comment]
@csagan5 I didn't make specific tests but there's a while that I didn't see an unwanted connection to Google's servers when using your browser.
Definitively better than a few months ago :+1:
