### ISSUE TITLE
Battery API returns actual data

### ISSUE THREAD

**Issue by Slaviro** [bromite/bromite#80]
Why did you remove BRM049_Battery-API-return-nothing.patch after 95 release? Now Browserleaks shows actual battery data. Maybe return it?

**Comment by csagan5** [comment]
@Slaviro thanks for noticing this; this was unintentional, and I forgot to test afterwards. It was discussed in [this comment](https://github.com/Eloston/ungoogled-chromium/issues/429#issuecomment-399578337) and I concluded it was redundant, while obviously it is not.

I will reinstate [the patch](https://github.com/bromite/bromite/blob/67.0.3396.92/patches/BRM049_Battery-API-return-nothing.patch).

**Comment by csagan5** [comment]
Fixed in next release 68.0.3440.72
