### ISSUE TITLE
A pop-up & redirect blocker

### ISSUE THREAD

**Issue by Infamous-Jr** [bromite/bromite#801]
### Is your feature request related to privacy?

Somehow the Pop-ups & force redirect blocker would help in preventing spam & ads from opening up.

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

I know Bromite already have a pop-up & redirect in site settings but it isn't working.
For eg whenever I watch a video & click on the Play button the the website forced redirect to a new tabs which is ads or some money betting sites & many more.
I request you to add dedicated pop-up blocker feature where it's ask for the users permission before opening a pop-up or redirect. 
I have attached a image please have a look. 

### Describe alternatives you have considered

I have tried various ad filters including the fanboy Annoyance, Energized & Adguard but none of them were able to block them. 

![Screenshot_2020-11-06-23-05-35-813_com oh bro](https://user-images.githubusercontent.com/68345385/98396981-a15e0f00-2084-11eb-89c9-7852841c98f9.jpg)

**Comment by Poopooracoocoo** [comment]
I don't get pop-ups on that site (which is a knock-off) with uBO's default filters on a desktop browser. I can't really tell which filters block the pop-ups in the logger but AFAIK, Bromite has all of the filters that uBO's default filters block on that site. I don't know why there are in-site "alerts" and pop-ups on that site. :/ im a total n00b

I agree that the pop-up and redirect blockers in Chromium are quite weak. It was made to not break legitimate uses.

**Comment by Infamous-Jr** [comment]
Bro desktop browsers have support for Ublock extension there but it's different story for an android browser.

I have used the default bromite filter which includes easylist, Ublock, etc but still they are unable to block the redirect on the above website 9anime-tv.com (try playing a video) & it not about just one single website there are tons of other websites which redirect to some nasty or adult website whenever you try to open a thing or link on webpage. 

Don't mind but in my opinion the pop-up & redirect blocker in chromium based browser are completely useless and is just a gimmick. Some of the Browsers are able to Block them with Ublock extension but I don't want to compare them with Bromite which is a privacy & security focused browser.

I know a aggresive pop-up blocker might break some websites which could be a problem for some user that's why I am requesting for a permission based pop-up & redirect blocker as show in the above image. The blocker would ask for users permission before opening a random page(which are mostly ads) since the user knows if the websites is redirecting to a legit page they can allow & if it's just a phishing sites or betting/Adult website then user can ignore the pop-up request & the pop up blocker would automatically decline the website request within a time frame of 5-7 sec if no action has been taken.

In my opinion an ad blocker and a pop-up & redirect blocker is must for a clean and neat experience. And I hope the Developers would give it a thought.

**Comment by Poopooracoocoo** [comment]
>Bro desktop browsers have support for Ublock extension there but it's different story for an android browser.

I was trying to determine which filters Bromite may have been missing by looking at uBO's logger.

>Don't mind but in my opinion the pop-up & redirect blocker in chromium based browser are _completely useless_ and is just a _gimmick_

euphemism much but yeah

**Comment by Infamous-Jr** [comment]
> I was trying to determine which filters Bromite may have been missing by looking at uBO's logger.
> Oh hope you could figure it & then it could be added in the default bromite filter.

**Comment by Infamous-Jr** [comment]
> I was trying to determine which filters Bromite may have been missing by looking at uBO's logger.
Oh hope you could figure it & then it could be added in the default bromite filter but I don't think its possible to blocks redirect with Just some filters. It needs a script which prevents the redirect to open a new tab.

**Comment by Infamous-Jr** [comment]
> I was trying to determine which filters Bromite may have been missing by looking at uBO's logger.

Oh hope you could figure it out  & then it could be added in the default bromite filter but I don't think its possible to blocks redirect with Just some filters. It needs a script which prevents the redirect to open a new tab.

**Comment by csagan5** [comment]
What you would need is customizing a website with user scripts; #792 might help in future, if it is developed.

**Comment by Poopooracoocoo** [comment]
@csagan5 Do you know why Bromite isn't blocking the pop-ups?

**Comment by csagan5** [comment]
@Poopooracoocoo you need to test with Chromium first

**Comment by Poopooracoocoo** [comment]
@csagan5 Chromium doesn't block the pop-ups either but Bromite's ad filters should be blocking them, at least after testing those same filters with uBO on Chrome for desktop.
