### ISSUE TITLE
Disable-scroll-to-text-fragment.patch seems not working

### ISSUE THREAD

**Issue by uazo** [bromite/bromite#803]
### Bromite version

Version: `86.0.4240.194`
Arch: `arm64`
Android version: `10.0`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No, it's a bromite patch.

### Is the bug a crash?

No

### Describe the bug

`Disable-scroll-to-text-fragment.patch` seems not working, TextFragmentAnchor still works.

### Steps to reproduce the bug

Click on https://www.gov.uk/passport-fees#:~:text=Fees%20for%20returning%20supporting%20documents

**Comment by csagan5** [comment]
Yes, it needs to be fixed. I can try a fix on next release (v87).

**Comment by uazo** [comment]
how do you plan to solve it? I personally don't think that disabling the function is conclusive.
I suggest to create a new interstitial page warning the user, who can decide whether to browse that page anyway or browse without the relative hashtag

do you need help with the v87?

**Comment by csagan5** [comment]
I am halfway through the v87 update.

> I suggest to create a new interstitial page warning the user, who can decide whether to browse that page anyway or browse without the relative hashtag

It will be disabled by default and if users want/need it they can turn on the flag. What you propose is too heavy UI-wise, it could rather be a setting than a flag but I do not think we need to move all flags to settings either. So a flag is sufficient here.

**Comment by uazo** [comment]
> I am halfway through the v87 update.

Thank you on behalf of all, a curiosity just I would like to try it too, where do you see what's the next version? the next  what will become stable?

ps: after I delete this ot message

**Comment by csagan5** [comment]
Do not delete it, otherwise messages don't make sense anymore. The release plan of Chromium is here: https://chromiumdash.appspot.com/schedule

There is also https://www.chromestatus.com/features/schedule with more information about the features/bugfixes

**Comment by csagan5** [comment]
Fixed in `87.0.4280.67`.

**Comment by uazo** [comment]
does not seem solved

**Comment by csagan5** [comment]
Should be fixed in `87.0.4280.68` now.

**Comment by csagan5** [comment]
Found the reason: https://github.com/chromium/chromium/commit/40ec96869bffefad335f1d94e05b41d185c7a67a

The web runtime flag is completely ignored; will revert it, this should fix it.

**Comment by csagan5** [comment]
That did not fix it; I believe it is enable because of the origin trial feature, see https://github.com/chromium/chromium/commit/4d08aa3a95b0d9063c484298b591779ab51ffbde

The scroll-to-text-anchor was just confusing, while what we want to disable are text anchors. It might need a separate flag.

**Comment by csagan5** [comment]
Fixed in `87.0.4280.81`. The corresponding flag is now exposed.
