### ISSUE TITLE
"Open new non-incognito tab" / "Open new normal tab" (once incognito default is on)

### ISSUE THREAD

**Issue by claude-cp** [bromite/bromite#808]
### Is your feature request related to privacy?
Absolutely.

### Is there a patch available for this feature somewhere?
There was an [issue](https://github.com/bromite/bromite/issues/364) opened in August 2019 but dropped in Sep 2019 due to the effort at the time, in favor of focusing on bug-fixing. So the related patch to this feature is linked [here](https://github.com/bromite/bromite/blob/76.0.3809.129/build/patches/Add-an-always-incognito-mode.patch). I'm tagging @M86xKC, @csagan5, @rarcher as they were the relevant contributors there (hope you don't mind).

### Describe the solution you would like
The most UX friendly solution would probably be a new button in the menu, "Open new normal tab" / "Open new non-incognito tab". Let's consider there are various issues with using the always-incognito mode (ie one such example, [paywalls](https://github.com/bromite/bromite/issues/695#issuecomment-675545615)).

### Describe alternatives you have considered

1. Dig back through the Bromite settings, then disable "always incognito", then be able to open normal tabs - an action I avoid (and I assume most users using that default) over 90-100% of the times, as it's too cumbersome.
2. Having another browser installed for "normal" / "non-incognito" browsing only.

(3. Honestly.. at times I just end up stopping browsing, not really an alternative but worth mentioning as far as UX goes).

From my side it's easy to say it is worth it. But question remains, how tough is it to implement, and are you willing to consider the effort?

**Comment by claude-cp** [comment]
### Additional notes / thoughts:
Browsing through the opened issues, I saw a good number of issues discussing the option to disable history in normal mode and I think it's tangential to the issue at hand, as "no history" is partially synonymous with "always incognito".
As diligently pointed out [here](https://github.com/bromite/bromite/issues/695#issuecomment-677279589) by @csagan5 in that regard,
> Once that happens you might have some happier users but you are just enabling the misuse of a browser with a combination of settings which give them a false sense of privacy.

I think it's _likely_ that users want the privacy benefits of "no-history" and "incognito" without making the distinction between the two due to.. well, ignorance - myself certainly, until reading that comment and seeing things better for what they are. 

But I do believe that incognito default + "Open new normal tab" as the exception to the rule when needed, will satisfy the browsing desires / needs of users, when thinking of the full picture. And thinking of said full picture, I think this approach would then complete that picture.

**Comment by claude-cp** [comment]
### Additional notes / thoughts:
Browsing through the opened issues, I saw a good number of issues discussing the option to disable history in normal mode and I think it's tangential to the issue at hand, as "no history" is **partially synonymous** with "always incognito".
As diligently pointed out [here](https://github.com/bromite/bromite/issues/695#issuecomment-677279589) by @csagan5 in that regard,
> Once that happens you might have some happier users but you are just enabling the misuse of a browser with a combination of settings which give them a false sense of privacy.

I think it's _likely_ that users want the privacy benefits of "no-history" and "incognito" without making the distinction between the two due to.. well, ignorance - myself certainly, until reading that comment and seeing things better for what they are. 

But I do believe that incognito default + "Open new normal tab" as the exception to the rule when needed, will satisfy the browsing desires / needs of users **and** not giving a false sense of privacy as mentioned, when thinking of the full picture. And thinking of said full picture, I think this approach would then complete that picture.

**Comment by csagan5** [comment]
Related: #728



> So the related patch to this feature is linked [here](https://github.com/bromite/bromite/blob/76.0.3809.129/build/patches/Add-an-always-incognito-mode.patch).

This is not a patch for the feature you are requesting here.

> Let's consider there are various issues with using the always-incognito mode (ie one such example, [paywalls](https://github.com/bromite/bromite/issues/695#issuecomment-675545615)).

It is not explained why you need the feature you are requesting. No features can be added without a rationale.

You want to switch to normal tabs when you hit a paywall, is this the use case?

**Comment by claude-cp** [comment]
> This is not a patch for the feature you are requesting here.

Never said it was. Thought I'd link the _related_ patch where this issue is relevant though, for your ease of navigation / reference.

> No features can be added without a rationale

You seemed open on the issue [that I linked initially](https://github.com/bromite/bromite/issues/364) and ready to consider implementing this feature, without being adamant for a rationale and seemed more concerned in regards to being efficient of the time/effort needed. I'm just one another user re-requesting said feature. Don't take it for being contentious, but what changed / what gives? If it's more about the time/effort, then, well, that's another discussion I guess.

> You want to switch to normal tabs when you hit a paywall, is this the use case?

Yes. That is the use case.

Yet, as I've already mentioned, that's **but one** of the use cases that would be solved. Pragmatically, I linked to that [paywalls](https://github.com/bromite/bromite/issues/695#issuecomment-675545615) comment for the reason that it nicely shows that this would solve:
 - both the paywall use case, as well as, 
 - indirectly, @spinoza-dat 's issue about the inability to "create a shortcut from an incognito tab" too (ie: the ability to access non-incognito tabs will enable him to create the desired shortcuts, too)

So it's as much about the reality that **[various](https://www.reddit.com/r/help/comments/ep3laj/getting_504_errors_only_on_redditcom_in_incognito/)** issues that can be hit on the internet can be solved, if you give the users the ability to [intentionally] choose to open a new non-incognito tab so they can get past various issues they may encounter. This is of course a conscious choice given they specifically have to open a new non-incognito tab.

By default, non-incognito is already possible, so no privacy compromises here, likely the opposite in fact: with this feature, you can then make incognito mode the default and non-incognito the (consciously clicked) exception to the rule - this pretty much makes Bromite a **more** privacy focused browser, if anything.

- So, yes, the paywall use-case. 
- _And_, a more wholesome experience - I wanted to reiterate on this, I think it's solid reasoning honestly (ie I think solving multiple issues is a stronger rationale than your initial ask for one particular use-case).
- _And_, defaulting the browser to incognito with the ability for non-incognito exceptions **[is](https://en.wikipedia.org/wiki/Default_effect)** more privacy focused than the defaulting to "normal" with incognito exceptions.

**Comment by csagan5** [comment]
> You seemed open on the issue that I linked initially and ready to consider implementing this feature, without being adamant for a rationale and seemed more concerned in regards to being efficient of the time/effort needed. I'm just one another user re-requesting said feature. Don't take it for being contentious, but what changed / what gives? If it's more about the time/effort, then, well, that's another discussion I guess.

The browser has changed over the years, both upstream and Bromite itself; any change must be evaluated based on the current feature set.

It is about time/effort only **after** it is acknowledged that it is in line with project goals and worth the effort.

> So it's as much about the reality that **[various](https://www.reddit.com/r/help/comments/ep3laj/getting_504_errors_only_on_redditcom_in_incognito/)** issues that can be hit on the internet can be solved, if you give the users the ability to [intentionally] choose to open a new non-incognito tab so they can get past various issues they may encounter. This is of course a conscious choice given they specifically have to open a new non-incognito tab.

Upstream (Chromium team) already has issues to track and prevent sites to detect incognito; that is the proper solution to the issues you are facing. Each individual problem you may have with incognito needs to be solved in that context.

> * I think solving multiple issues is a stronger rationale than your initial ask for one particular use-case

If it is about multiple use-cases, then we need to discuss each; I doubt you have tracked each of them with the corresponding upstream bug. Nothing will be decided here (for Bromite) without first checking about that.

Multiple use-cases can be bundled and solved with one solution, but we cannot skip to the implementation stage without discussing them first.

So far I have not seen any reason to pursue this, except convenience. It is also not about privacy but about **degrading** privacy in case incognito does not work; that is literally against everything this project is about: I would rather help upstream work on the issues which allow sites to detect incognito than make the browser even more complex to give up on incognito when it is currently not working as expected. I understand the user freedom aspect, but this feature is about giving up on the important battles here - both as an user and as a developer.

**Comment by claude-cp** [comment]
> So far I have not seen any reason to pursue this, except convenience

The "default effect" is more than convenience, it's a real thing with real results, otherwise google would [not be paying apple billions to be set as the default search engine](https://www.theverge.com/2020/7/1/21310591/apple-google-search-engine-safari-iphone-deal-billions-regulation-antitrust) - not sure if you failed to see this or unwilling to consider this real, quite-basic thing, as truth.

> I understand the user freedom aspect, but this feature is about giving up on the important battles here - both as an user and as a developer.

Not sure this argument really holds up, when the default is non-incognito anyway. If non-incognito is the default, which like you yourself said is also about other things than just history - then this is more of an issue than selectively "giving up" on it here and there, and consciously as a choice. I think you're making the mistake of undermining users here more than you should.

But, all this is not new, I've already pretty much said the same things from the start. 

I guess it's up to you from this point, I've said both my desires / needs as a user, I think there was some solid points I made too. 

I now give up and I hope you are willing to re-read my messages and/or reconsider the reasonings. Perhaps other can chime in. As far as I'm concerned, the issue I've opened is still very relevant, and nowhere near resolved. Take it forward or close it, as you see fit.

**Comment by claude-cp** [comment]
> So far I have not seen any reason to pursue this, except convenience

The "default effect" is more than convenience, it's a real thing with real results, otherwise google would [not be paying apple billions to be set as the default search engine](https://www.theverge.com/2020/7/1/21310591/apple-google-search-engine-safari-iphone-deal-billions-regulation-antitrust) - not sure if you failed to see this or unwilling to consider this real, quite-basic thing, as truth.

> I understand the user freedom aspect, but this feature is about giving up on the important battles here - both as an user and as a developer.

Not sure this argument really holds up, when the default is non-incognito anyway. If non-incognito is the default, which like you yourself said is also about other things than just history - then this is more of an issue than selectively "giving up" on it here and there, and consciously as a choice. I think you're making the mistake of undermining users here more than you should.

But, all this is not new, I've already pretty much said the same things from the start. 

I guess it's up to you from this point, I've said both my desires / needs as a user, I think there was some solid points I made too. 

I give up now. Perhaps other can chime in. As far as I'm concerned, the issue I've opened is still very relevant, and nowhere near resolved. Take it forward or close it, as you see fit. However I do hope you are willing to re-read my messages and/or reconsider the reasonings.

**Comment by csagan5** [comment]
> Not sure this argument really holds up, when the default is non-incognito anyway.

> defaulting the browser to incognito with the ability for non-incognito exceptions is more privacy focused than the defaulting to "normal" with incognito exceptions.

By giving users the option to switch to non-incognito, rather than preventing sites from detecting incognito, we are undermining both users' privacy and the incognito feature itself, as more and more sites will adopt those techniques to detect incognito and add paywalls. Our limited resources are IMO better focused on preventing sites to detect incognito rather than maintaining this feature asked here.

> I give up now. Perhaps other can chime in.

I am still waiting for this part to be made explicit:
> If it is about multiple use-cases, then we need to discuss each; I doubt you have tracked each of them with the corresponding upstream bug. Nothing will be decided here (for Bromite) without first checking about that.

Until that, no matter how many chime in, I cannot commit to add this to the project planned features.

> However I do hope you are willing to re-read my messages and/or reconsider the reasonings.

See above; we need a list of use-cases that this feature would cover. You have provided this:
> 1. So, yes, the paywall use-case.
> 2. And, a more wholesome experience - I wanted to reiterate on this, I think it's solid reasoning honestly (ie I think solving multiple issues is a stronger rationale than your initial ask for one particular use-case).
> 3. And, defaulting the browser to incognito with the ability for non-incognito exceptions is more privacy focused than the defaulting to "normal" with incognito exceptions.

I see only one use-case here, bypassing paywalls introduced by sites detecting incognito. If this problem did not exist, what are the other compelling use-cases for this feature?

**Comment by claude-cp** [comment]
> Our limited resources are IMO better focused on preventing sites to detect incognito rather than maintaining this feature asked here.

This is something I can totally agree with - if possible. If not?

**Comment by claude-cp** [comment]
> Our limited resources are IMO better focused on preventing sites to detect incognito rather than maintaining this feature asked here.

This is something I can totally agree with - if possible. If not?

> I doubt you have tracked each of them with the corresponding upstream bug.

Your doubt is valid. I won't either, I came here more as a user than anything, as I've stated ..

But, how is no "3. " not compelling, where in one place you seem to advocate incognito for its added privacy features (actually quite curious what these are, if you allow me to side track this because I'm genuinely curious, was asking myself this too), but here you don't seem to be in favor of using incognito more, as the result of potentially defaulting to that mode?

**Comment by csagan5** [comment]
> This is something I can totally agree with - if possible. If not?

The "If not" part cannot be decided here in this conversation; one has to read about the efforts already made by upstream and understand the challenges. The current design of the incognito feature, where it is going etc.
To put it simple: if upstream has open issues to prevent sites from detecting incognito, we are not going to just bypass it because we do not know about such open bugs nor we believe they can be fixed. We literally know less than the Chromium team on this, so we should inform ourselves first (me included).

> And how is "3. "

"3" is just a reiteration of "1", differently worded.

Please explain "3" without "1", as I asked here:
> If this problem did not exist, what are the other compelling use-cases for this feature?

**Comment by claude-cp** [comment]
3 was more of a suggestion to default the browser itself to that mode ..

**Comment by claude-cp** [comment]
That's a very interesting thing, the core issue of sites being able to detect incognito and I agree it's a real issue very relevant here, I hope it can be solved from the core.

But mainly, it's also not relevant in that I think the idea that one should be able to open a new "non-incognito" as a feature divorced from the fact that it should "solve" an issue or be the consequence of something. Maybe it's no issue, maybe I want to browse normally as the exception just because. Just as I can "open new incognito tab" when the browser's default - that certainly seems to be a "just because" that was accepted with no second thought. Why that, but not this? If divorced, this is another way "1. " and "3. " differ.

**Comment by csagan5** [comment]
> that certainly seems to be a "just because" that was accepted with no second thought.

Many things changed since #364:
* features in Chromium
* features in Bromite
* understanding of how incognito works

Regardless, if implementation was ever started for #364 the same questions arising here would eventually have come up (and hopefully before release).

I do not really think that your strategy of "since you were OK with it in August 2019 then you should be OK with it now" is a winning one; we need to discuss the technical aspects of the problem, not what me or other people say.

> The analogy here could be that "blacklisting is acceptable", "whitelisting is not". I fail to see any valid reasoning why one is acceptable but the other is to be avoided other than the fact that one is not built yet - this takes things back to "effort/time" more than anything else.

It has to not break current design of the incognito feature; the code is organised in a certain way, second its design; ignoring its design principles leads to huge amounts of work and ultimately failure in changing it without understanding it first. That is why it is necessary to know what problem(s) we are trying to solve here. It is a browser, not a notepad application.

**Comment by claude-cp** [comment]
Yep, you know the code, you know what's doable and what isn't. 
I trust you'll do the right thing down the line. You've read my comments and considered my points. That's much appreciated.

**Comment by csagan5** [comment]
@uazo how do you see this feature request? please do not start any patch, we need to discuss it.

The way I see it it is not possible to add it without introducing tens of bugs (because of how incognito/always-incognito is designed); I might be wrong though.

**Comment by uazo** [comment]
>  how do you see this feature request?

yes and i agree with you

> the way I see it it is not possible to add it without introducing tens of bugs (because of how incognito/always-incognito is designed); I might be wrong though.

I agree, I don't think this is the correct way, that patch should be rewritten, because it currently disables "normal" navigation completely. it's probably not a complex thing, but it makes little sense to me.

I think that the idea that browsing anonymously becomes standard browsing is the best one, because among other things, I point out that within the code the same chromium programmers disable some "privacy issues" when you activate anonymous browsing (and they are not just ui features), which fits perfectly with the idea that bromite's default should be that.

And it comes back to the idea of listing what is disabled in anonymous browsing, in order to patch those features to activate them (analyzing them all and verifying if it is possible), and also define what anonymous browsing breaks down

**Comment by M86xKC** [comment]
I agree with the re-writing part! but I'm sure that's not a trivial task and will take a lot of debugging and testing!

I really like the behaviour of the new Firefox's; `Open links in a private tab` when you click on links from other apps it will open them in a private tab instead of a regular one (private by default)*.

I've found a flag (`#cct-incognito`) in chromium-based web browsers, that does something similar (Enables incognito mode for chrome custom tabs, on android) but could not get it to work properly in bromite. also not every app supports opening links in custom tabs (some have options some don't)

*![test](https://user-images.githubusercontent.com/31791780/99874479-2b0ef000-2be0-11eb-8afe-effeec5493cf.jpg)

**Comment by csagan5** [comment]
> I agree with the re-writing part! but I'm sure that's not a trivial task and will take a lot of debugging and testing!

It is always very easy to agree when someone else will do the work :)

> I really like the behaviour of the new Firefox's; `Open links in a private tab` when you click on links from other apps it will open them in a private tab instead of a regular one

This was asked in another issue, see #728

> that patch should be rewritten, because it currently disables "normal" navigation completely. it's probably not a complex thing, but it makes little sense to me.

That might be the only way to allow always-incognito, since Chromium is only recently getting more incognito tabs features. It is worth investigating.

> I think that the idea that browsing anonymously becomes standard browsing is the best one, because among other things, I point out that within the code the same chromium programmers disable some "privacy issues" when you activate anonymous browsing (and they are not just ui features), which fits perfectly with the idea that bromite's default should be that.
> 
Yes, I found some of those as well.

> And it comes back to the idea of listing what is disabled in anonymous browsing, in order to patch those features to activate them (analyzing them all and verifying if it is possible), and also define what anonymous browsing breaks down

Yes, we need to make incognito not detectable, that is the only use case behind this feature request here. Efforts are better focused on fixing that rather than allowing exceptions for all websites which (without user consent) track users.

**Comment by csagan5** [comment]
I am closing this issue; if there are sites which detect incognito please report the issue upstream first.

Examples:
* https://bugs.chromium.org/p/chromium/issues/detail?id=588766
* https://bugs.chromium.org/p/chromium/issues/detail?id=990731
* https://bugs.chromium.org/p/chromium/issues/detail?id=991432
