### ISSUE TITLE
Chrome Custom Tabs working incorrectly

### ISSUE THREAD

**Issue by IronPiston** [bromite/bromite#810]
### Bromite version

Version: `86.0.4220.194`
Arch: `arm64`
Android version: `10.0`
Device model: `ONEPLUS A6003`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug
Chrome custom tabs don't seem to be working correctly. When opening a link from Reddit Sync in Chrome or Chromium, it correctly opens in a custom tab. Using Bromide as the default browser, it instead open in a normal tab in the Bromite app. 

### Steps to reproduce the bug

Steps to reproduce the bug:
1. In Reddit Sync, set default browser as "Chrome Custom Tabs"
2. Click any link within the app
3. Notice that it opens in Bromite rather than a custom tab

Following these steps for Chromium correctly opens in a custom tab.

### Expected behavior
Bromite should open a custom tab using the URL.

**Comment by csagan5** [comment]
> Following these steps for Chromium correctly opens in a custom tab.

How do you set it to Chromium?

**Comment by IronPiston** [comment]
Oh sorry, I didn't explain that well. To test with each browser, I set the default browser under settings to Chromium, Chrome, and then Bromite. Reddit Sync respects the default browser when opening custom tabs. 

When using Chromium and Chrome as the default, custom tabs functioned. Bromite just switched to the app and opened a new tab.

**Comment by uazo** [comment]
@IronPiston  have you selected "Allow custom tab intents" in privacy settings?

**Comment by IronPiston** [comment]
Wow, I didn't realize I didn't have that toggled. Sorry for all the confusion!
