### ISSUE TITLE
Signed into sites even after clear data everything in advanced mode

### ISSUE THREAD

**Issue by sivuda** [bromite/bromite#812]
Yes

### Bromite version

Version: `86.0.4240.194`
Arch: `arm64`
Android version: (11)
Device model: (oneplus 5t)

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes
### Can the bug be reproduced with corresponding Chromium version?

No

### Is the bug a crash?

No
### Steps to reproduce the bug

Steps to reproduce the bug:
1. Sign into any website.
2. Clear data from privacy menu
3. Exit browser
4. Open browser and go to the website from step 1.
5. you're still logged in.

### Expected behavior

Sessions must not pertain after clearing data

**Comment by csagan5** [comment]
@uazo can you reproduce this? Any idea about which patch is responsible?

**Comment by uazo** [comment]
no, I can not reproduce it.

**Comment by csagan5** [comment]
We can reopen it once someone provides steps and the issue is reproducible.
