### ISSUE TITLE
Tinting issue in screen triggered by the elements on webpage. 

### ISSUE THREAD

**Issue by paritosh9199** [bromite/bromite#817]
### Bromite version

Version: `83.0.4280.67`
Arch: `arm64`
Android version: 10 (Oxygen OS 10.3.6)
Device model: OnePlus 7

### Is this bug about the SystemWebView?
I am not sure.

### Is the bug reproducible with latest version?
Yes

### Describe the bug
The screen gets yellowish tint when on certain websites or when clicking on certain element in websites. Exiting the app or just switching to any other app makes screen go back to its set calibration. When the app is opened again with the same webpage the screen gets affected again.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to 'google.com'
2. Search something
3. Click on search bar in webpage (Not the url bar in chrome)
4. See screen get yellow tinted.
5. Switch to any other recent app and see screen go back to normal.

**Comment by csagan5** [comment]
@paritosh9199 this part is not optional:
> Can the bug be reproduced with corresponding Chromium version?

Please make a test with the corresponding Chromium version as explained when submitting the issue and report back your results; then we can reopen the issue.

**Comment by paritosh9199** [comment]
Okay so after some looking around! I found this behaviour in the latest update of chrome too! 

In my case messing with some of the flags in chrome://flags seems to have fixed the problem for now! 

**What I did: **
I set **Forced color profile** flag to default and **Forced colors** and **Dynamic color gamut** to disabled.

**Comment by HyknuF** [comment]
Thanks for posting your workaround. Had the same effect since update to v87. Adjusting these flags fixed it for me as well.

Bromite version: latest
A11, OnePlus6
