### ISSUE TITLE
Cannot access Home Assistant instance using Caddy reverse proxy. Works with other browsers and with other services running on the same server.

### ISSUE THREAD

**Issue by cvsickle** [bromite/bromite#822]
Have you read the README? yes
Have you searched the issue tracker? Yes... Potentially similar? https://github.com/bromite/bromite/issues/590#issuecomment-671274482
Are you sure this is not a Chromium bug? Yes
Are you using the latest version of Bromite? Yes

### Bromite version

Version: `87.0.4280.68 (F-Droid)`
Arch: `ARM64`
Android version: `11.0`, `9.0`, `8.0`, and `7.0` (corresponding to devices below)
Device model: `Pixel 3 (GrapheneOS)`, `SM-T820`, `SM-G930v`, `SHIELD Tablet K1`

### Is this bug about the SystemWebView?
No, but the SystemWebView does the same thing.

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug

I can't say this is a bug with 100% certainty.

Cannot maintain access to Home Assistant (Docker) when accessing via Caddy Reverse Proxy (also Docker). It is accessible in Bromite when using the Local IP Address of the Home Assistant server. It is accessible via the reverse proxy when using basic chromium (and other browsers such as Vanadium and Fennec).

The only browser or webview that behaves this way is Bromite, leading me to believe the issue is here.

I have tried different settings for the encode and header Caddy server directives, but nothing has changed this behavior. The Caddy server configuration found below mirrors other my services on the same server that I DO have access to in Bromite via the reverse proxy. Examples are Jellyfin, Radarr, Sonarr, Nextcloud, etc.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Create a Home Assistant instance on a local server in a Docker Container.
2. Create a DuckDNS subdomain pointing to Public IP address (example.duckdns.org)
3. Create a Caddy Server instance in another Docker Container listening to the DuckDNS subdomain with the following configuration pointing to the Home Assistant web port.

`

example.duckdns.org {
	
	encode gzip
	
	header {
		Strict-Transport-Security max-age=31536000;includeSubDomains;preload
		X-Content-Type-Options nosniff
		X-Frame-Options DENY
		Referrer-Policy no-referrer-when-downgrade
	}
	
	reverse_proxy 192.168.1.XX:8123
	
}

`

4. In Bromite, navigate to the DuckDNS Subdomain.
5. Log in to Home Assistant. Momentarily after logging in, Home Assistant will report that the client is "Unable to connect to Home Assistant". Note that this happens when connected to the local network my server is on and when connecting remotely.

### Expected behavior

Once logged in to Home Assistant, the connection should remain established and not report that it is unable to connect.

**Comment by csagan5** [comment]
Try using [remote debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging); this is most likely working as intended.

The best we could do is add a flag to allow the old unsecure behaviour; upstream is going to fix it in a different way in future.

**Comment by cvsickle** [comment]
Wow. Thanks for the help.

**Comment by cvsickle** [comment]
@csagan5 in your edit, what is upstream going to fix in the future? Again, Bromite is the only browser with this behavior.

**Comment by cvsickle** [comment]
@csagan5 The error I find when remote debugging...

Uncaught (in promise) DOMException: Failed to construct 'WebSocket': Access to this address is not allowed.
    at a (https://example.duckdns.org/frontend_latest/core.7829e4bb.js:1:5575)
    at https://example.duckdns.org/frontend_latest/core.7829e4bb.js:1:6349
    at new Promise (<anonymous>)
    at Object.n [as createSocket] (https://example.duckdns.org/frontend_latest/core.7829e4bb.js:1:6329)
    at i (https://example.duckdns.org/frontend_latest/core.7829e4bb.js:1:10076)
    at https://example.duckdns.org/frontend_latest/core.7829e4bb.js:1:14286

**Comment by csagan5** [comment]
@cvsickle Bromite does not allow a non-local address to access a local address; this is by design and not a bug in Bromite.

I already indicated you how to troubleshoot your application: use the remote debugging tools. You will find out in the network tab that the web application is trying to do exactly what I wrote above, which is not allowed.

Having said that, let me be clear: nobody here has to offer you any kind of support, try harder to troubleshoot the problem and if you can submit evidence that there is a bug in Bromite I will be happy to accept the submission.

**Comment by cvsickle** [comment]
@csagan5 First off, let me apologize... I think we had a miscommunication. It wasn't my intention to suggest that anyone was under any obligation to help me. I see now that the "Wow. Thanks for your help." could have been read sarcastically and wasn't my intention. The "wow" was because I was surprised at myself for not thinking to check the debugger before creating the bug report... that's definitely helpful information. I'm sorry I didn't make that clear.

I understand what you're saying about a non-local address accessing a local address, but I'm not sure that's what's going on, and here's why:

1. I have other services running on the same server as Home Assistant that are accessible via a duckdns address using the same reverse proxy settings that I listed for Home Assistant. For example, I can navigate to "example2.duckdns.org" in Bromite and successfully connect to my Jellyfin server, and everything works as expected.

2. I'm not able to connect to Home Assistant via my reverse proxy when I'm outside of my local network and using Bromite. I get the same type of [websocket error](https://github.com/bromite/bromite/issues/822#issuecomment-733993618) that I get when I'm connected to the local network. All my other services are available, however.

3. Similar to #2, but I am not able to connect to Home Assistant using Bromite through my reverse proxy on devices using an always on VPN (Mullvad) whether or not they are connected to my home network. The VPN is setup to block connections to and from local network devices when it's running, so it should treat the VPN devices as if they are foreign to the network, but I get the same websocket error, despite all my other services working as expected on these devices.

I realize the evidence I'm presenting is circumstantial, but it is what it is. I get the websocket error when I'm connecting to Home Assistant via my reverse proxy only when using Bromite, regardless of what network the device is connected to. Bromite can access all other services on my server over the reverse proxy, and all other browsers that I've tested do not get the websocket error when connecting to the same service using the same device.

If the conclusion is that there is something wrong or insecure with Home Assistant, and only Bromite catches it, then so be it. Again, I've tried Chromium, Vanadium, and Fennec on Android and Firefox and Chrome on Windows, and none of those have this problem. Not a huge deal to me, I can just use a different browser/webview on my Android devices when I want to access Home Assistant, I just wanted to report it because things seem to point to an issue with Bromite. If you'd like any more information from me about this, please let me know.

**Comment by cvsickle** [comment]
@csagan5 please let me know if I'm doing anything wrong, I'm not incredibly familiar with debugging web pages. In the network tab, it looks like there are two connections, both have a status of 200.

![1 requests](https://user-images.githubusercontent.com/38385820/100390078-33f72b80-2ffd-11eb-894b-535c16dd7ad9.png)

But then I went to the sources tab and noticed that nothing from the home-assistant-frontend webpack is being loaded.

![9 sources](https://user-images.githubusercontent.com/38385820/100390159-73257c80-2ffd-11eb-8360-d21eaea32a76.png)

Each one has an error similar to: "Could not load content for webpack://home-assistant-frontend/core.7829e4bb.js (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)"

The uncaught exception that I get with the failure to construct the websocket happens when it's trying to load the last core.7829e4bb.js file from that web pack. Does this information help at all?

**Comment by cvsickle** [comment]
And here's the headers for both of those connections in the network tab.

![2 lovelace_headers](https://user-images.githubusercontent.com/38385820/100390782-93eed180-2fff-11eb-9809-2d5beda010ea.png)

![6 manifest_headers](https://user-images.githubusercontent.com/38385820/100390789-994c1c00-2fff-11eb-9690-604a9073d6f7.png)

**Comment by csagan5** [comment]
> Uncaught (in promise) DOMException: Failed to construct 'WebSocket': Access to this address is not allowed.

This is the error you need to troubleshoot. You need to figure out which address it is trying to reach. Maybe you can ask on StackOverflow or similar, we cannot continue this here, it is not about Bromite.

**Comment by epma01** [comment]
I have the same issue with home-assistant trying to create a WebSocket, from a public address to a public address

FROM: https://ha.---------.net/lovelace/default_view
TO: wss://ha. ---------.net/api/websocket

![ha](https://user-images.githubusercontent.com/49983490/110251644-b9399700-7f81-11eb-806b-fdb52af2700e.jpg)

please reopen this issue
