### ISSUE TITLE
Possible to use Bromite on Android Work Profile? - No Root

### ISSUE THREAD

**Issue by desmonk** [bromite/bromite#827]
### Is your feature request related to privacy?

Yes.

### Is there a patch available for this feature somewhere?

No.

### Describe the solution you would like

Implementation of Bromite on Android Work Profile.

### Describe alternatives you have considered

I removed default system webview on work profile with the help of Island app to test. I did install but upon launching the app I found something more interesting. Apps on work profile rely on webview from User/System. Meaning if I disable both webview apps (not referring to Bromite as it doesn't work on work profile.), apps crash.

But to my surprise apps continued to failed even with work profile webview was enabled. Only solution was to enable both webviews in order for work apps to work.

Can we by any means take advantage of work profile and implement Bromite?

Thank you for your efforts and I truly find it more empowering to have an option to replace the built-in webview.

**Comment by csagan5** [comment]
There is no support for the webview, sorry.

**Comment by desmonk** [comment]
Thank you for your answer. Hope one day we can implement Bromite in Android Work profile instead of webview.
