### ISSUE TITLE
Timezone override display the same value when it sets to "Random"

### ISSUE THREAD

**Issue by CikiMomogi** [bromite/bromite#828]
### Bromite version

Version: `87.0.4280.81`
Arch: `arm`
Android version: `10`
Device model: `Redmi 2` / `wt88047`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No. I did not find such feature in chromium.

### Is the bug a crash?
No

### Describe the bug
All websites that use javascript to check browser timezone display the same result when the timezone override is set to random.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to Settings > Site settings > Timezone override. Set it to "Random"
2. Press exit button. Then open bromite again (relaunch)
3. Go to https://whatismytimezone.com/ 
4. Go to http://browserspy.dk/date.php
5. Go to https://webbrowsertools.com/timezone/
4. All websites display same timezone

### Expected behavior
At least one of those websites should display different timezone.

### Screenshots
![25fcc6bd-47dc-4a9f-a9e5-abefa2e14294](https://user-images.githubusercontent.com/74030149/100551304-e2aa9e80-327f-11eb-91cd-98765662731f.png)
![81f8247d-20cd-415b-aa93-0818efdd1c33](https://user-images.githubusercontent.com/74030149/100551316-f0602400-327f-11eb-9e3c-4ce5e46ce7d3.png)
![8721dbdd-e363-48fa-b2d5-f6f9991b7157](https://user-images.githubusercontent.com/74030149/100551319-f9e98c00-327f-11eb-9b48-40d2b2871bf7.png)

**Comment by uazo** [comment]
yes, actually it was not very random!
thanks for reporting.

**Comment by csagan5** [comment]
Fixed in `87.0.4280.106`.
