### ISSUE TITLE
Cname cloaking blocker

### ISSUE THREAD

**Issue by Dev-i-l** [bromite/bromite#833]
### Is your feature request related to privacy?
Yes

### Is there a patch available for this feature somewhere?
Brave browser and ublock origin already have this
https://github.com/gorhill/uBlock/releases/tag/1.25.0
https://github.com/brave/brave-core/pull/6640

### Describe the solution you would like
cname cloaking is a serious issue, various third party disguise to be first party and hence are not blocked and collect data, i would like to have cname cloaking blocker in bromite

**Comment by csagan5** [comment]
How does it work? The features of Brave are not separated in individual patches.

**Comment by Disqu3-mirOir-qt** [comment]
get Cname in dns record and blocked domain if cname record inside filter

**Comment by Dev-i-l** [comment]
the issue : 
https://github.com/brave/brave-browser/issues/11712
the pr which solved it :
https://github.com/brave/brave-core/pull/6640

sorry for not providing them earlier

**Comment by csagan5** [comment]
I saw those PRs; but do they use a separate list?

**Comment by Dev-i-l** [comment]
not in my knowledge, sir

**Comment by uBlock-user** [comment]
CNAME un-cloaking is only supported in Firefox.

**Comment by csagan5** [comment]
If someone can come up with a patch (and maintain it) I will be glad to consider it for merge; until that, no plans to add this.

**Comment by Harsh-dbey** [comment]
hey @csagan5 i found a solution to this, using blahdns will block cname cloaking. blahdns is foss, a hobby project with no logging. you might as well add this to fixed
