### ISSUE TITLE
site settings on same domain but different protocol not applied properly

### ISSUE THREAD

**Issue by qvtqht** [bromite/bromite#834]
### Bromite version

Version: `83.0...`
Arch: `arm` or `arm64` or `x86`
Android version: (example: `9.0`)
Device model: (example: `SM-G960UZKABST`)

### Is this bug about the SystemWebView?
Yes/No

### Steps to reproduce the bug

Steps to reproduce the bug:
1. global site settings, disable js
2. go to https://qdb.us/
3. site settings, enable js
4. go to http://qdb.us/
5. go to site settings

actual:
js is already set to enabled BUT js doesn't actually run on http site

### Expected behavior

js setting is separate for each protocol

OR

js setting takes effect on both protocols together

### Screenshots

this bug will be included in bug report response study

**Comment by csagan5** [comment]
Please make the Chromium test as required.
