### ISSUE TITLE
consider enabling network isolation key partitioning features

### ISSUE THREAD

**Issue by thestinger** [bromite/bromite#836]
Google appears to be testing some of these via field trials. The tricky part is figuring out which portions of this are ready to enable. It might all be ready already. These features are designed to split up everything other than cookies into partitions keyed based on the first party origin similar to Safari (and frame, going beyond what Safari does).

Extending it to cookies should be enough to fully partition site data, caches, connection pools, etc. when combined with the baseline feature. It's probably still not at the point that this is actually the case yet, but that's the goal for the feature.

Alternatively, could just wait a few months for this to roll out itself. However, some things have been getting delayed due to increased reluctance to make aggressive changes due to COVID-19 fallout. I don't think that's going to apply to this since it shouldn't break anything.

**Comment by thestinger** [comment]
This is also called split cache in some places. It applies to a lot more than the cache though.

**Comment by csagan5** [comment]
@thestinger have you already enabled this in Vanadium?

**Comment by thestinger** [comment]
I want to figure out which subset of it they've started deploying first.

**Comment by csagan5** [comment]
I can give a look tomorrow (+19h)

**Comment by csagan5** [comment]
All the field trials can be found here: https://github.com/chromium/chromium/blob/87.0.4280.81/testing/variations/fieldtrial_testing_config.json

Look for `NetworkIsolation` there.

These are the upstream issues I have found:

* https://bugs.chromium.org/p/chromium/issues/detail?id=1018718
* https://bugs.chromium.org/p/chromium/issues/detail?id=963480

The features used by the field trials are:
* `PartitionConnectionsByNetworkIsolationKey`
* `PartitionHttpServerPropertiesByNetworkIsolationKey`
* `SplitHostCacheByNetworkIsolationKey`
* `AppendFrameOriginToNetworkIsolationKey`
* `SplitCacheByNetworkIsolationKey`
* `UseRegistrableDomainInNetworkIsolationKey`
* `PartitionSSLSessionsByNetworkIsolationKey`

See also: https://github.com/chromium/chromium/blob/87.0.4280.81/net/base/features.cc#L63

There are two field trials, `PartitionConnectionsByNetworkIsolationKey` and `SplitCacheByNetworkIsolationKey`; each field trial enables a certain set of features as you wrote; one of the two Chromium issues is marked as fixed, the other one seems "hanging", but there might be other private issues somewhere else (I hope not).

I will start enabling `SplitCacheByNetworkIsolationKey`, which corresponds to the issue marked as fixed, on the next Bromite release.

**Comment by csagan5** [comment]
`AppendFrameOriginToNetworkIsolationKey` is already enabled by default in Chromium and `UseRegistrableDomainInNetworkIsolationKey` has disappeared as a feature in https://github.com/chromium/chromium/commit/0809a16e472c4df1898537fcc71333087cf4f925, being now enabled by default. The only feature that will be enabled in next Bromite release is `SplitCacheByNetworkIsolationKey`.

**Comment by csagan5** [comment]
Fixed in `87.0.4280.131`.
