### ISSUE TITLE
Mastodon sites don't work properly

### ISSUE THREAD

**Issue by jdaviescoates** [bromite/bromite#838]
### Bromite version

Version: 87.0.4280.81
Arch: dunno
Android version: 8.1.0
Device model: Wileyfox Swift 2 Plus

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is the bug a crash?

No

### Describe the bug

Mastodon sites don't work properly. And if you add them to the homepage as an app, they don't work at all.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to https://social.coop
2. Login
3. All good so far, site loads and gets redirected to https://social.coop/web/timelines/home
4. Refresh page (or just close and reopen Bromite and visit the same tab)
5. Black/ blank screen
6. Have to go back to https://social.coop again to get the site to reload properly

Similarly, when opening the 'app' after adding to homepage I just get a blank black screen.

### Expected behaviour

I expect Mastodon sites to work.

1. Go to https://social.coop
2. Login
3. Site loads and gets redirected to https://social.coop/web/timelines/home
4. Refresh page (or just close and reopen Bromite and visit the same tab)
5. No black/ blank screen

### Screenshots

https://files.uniteddiversity.coop/Screenshot_20201206-000100.png

**Comment by csagan5** [comment]
This cannot be reproduced with Chromium? Have you tried checking the errors via remote debugging?

**Comment by jdaviescoates** [comment]
> This cannot be reproduced with Chromium? 

Correct.  https://social.coop works fine on Chromium (installed from your repo using F Droid)

> Have you tried checking the errors via remote debugging?

No, I'm not sure how to do that? :)

**Comment by csagan5** [comment]
> No, I'm not sure how to do that? :)

You are one search engine search away from it: https://developers.google.com/web/tools/chrome-devtools/remote-debugging

**Comment by ygsk100** [comment]
@csagan5 
Opening `https://oransns.com` will redirect to `https://oransns.com/web/timeline`, and all frame and elements will load.
But when using the Mastodon's PWA which opening `https://oransns.com/web/timeline` at first time, there's a blank page.
Below is logs 

```
react-dom.production.min.js:5058 DOMException: Failed to construct 'WebSocket': Access to this address is not allowed.
    at e.value (https://oransns.com/packs/js/common-4973a023877857629515.js:2:952601)
    at new e (https://oransns.com/packs/js/common-4973a023877857629515.js:2:952430)
    at https://oransns.com/packs/js/common-4973a023877857629515.js:2:586144
    at https://oransns.com/packs/js/common-4973a023877857629515.js:2:586586
    at Object.dispatch (https://oransns.com/packs/js/common-4973a023877857629515.js:2:287407)
    at t.componentDidMount (https://oransns.com/packs/js/application-530c19d36830455099d4.chunk.js:1:92956)
    at ls (https://oransns.com/packs/js/common-4973a023877857629515.js:2:1047133)
    at Su (https://oransns.com/packs/js/common-4973a023877857629515.js:2:1065055)
    at https://oransns.com/packs/js/common-4973a023877857629515.js:2:1084379
    at Va (https://oransns.com/packs/js/common-4973a023877857629515.js:2:1008779)
os @ react-dom.production.min.js:5058
(anonymous) @ react-dom.production.min.js:5568
go @ react-dom.production.min.js:3108
ls @ react-dom.production.min.js:5182
Su @ react-dom.production.min.js:6408
(anonymous) @ scheduler.production.min.js:309
Va @ react-dom.production.min.js:2816
Eu @ react-dom.production.min.js:6204
du @ react-dom.production.min.js:5895
(anonymous) @ react-dom.production.min.js:2851
(anonymous) @ scheduler.production.min.js:309
Va @ react-dom.production.min.js:2816
Ya @ react-dom.production.min.js:2846
Qa @ react-dom.production.min.js:2836
hu @ react-dom.production.min.js:5933
tc @ react-dom.production.min.js:7180
(anonymous) @ react-dom.production.min.js:7363
(anonymous) @ main.js:24
react-dom.production.min.js:2857 Uncaught DOMException: Failed to construct 'WebSocket': Access to this address is not allowed.
    at e.value (https://oransns.com/packs/js/common-4973a023877857629515.js:2:952601)
    at new e (https://oransns.com/packs/js/common-4973a023877857629515.js:2:952430)
    at https://oransns.com/packs/js/common-4973a023877857629515.js:2:586144
    at https://oransns.com/packs/js/common-4973a023877857629515.js:2:586586
    at Object.dispatch (https://oransns.com/packs/js/common-4973a023877857629515.js:2:287407)
    at t.componentDidMount (https://oransns.com/packs/js/application-530c19d36830455099d4.chunk.js:1:92956)
    at ls (https://oransns.com/packs/js/common-4973a023877857629515.js:2:1047133)
    at Su (https://oransns.com/packs/js/common-4973a023877857629515.js:2:1065055)
    at https://oransns.com/packs/js/common-4973a023877857629515.js:2:1084379
    at Va (https://oransns.com/packs/js/common-4973a023877857629515.js:2:1008779)
Ya @ react-dom.production.min.js:2857
Qa @ react-dom.production.min.js:2836
hu @ react-dom.production.min.js:5933
tc @ react-dom.production.min.js:7180
(anonymous) @ react-dom.production.min.js:7363
(anonymous) @ main.js:24
timeline:1 The resource https://oransns.com/packs/js/features/compose-c68c2f048c9457741c11.chunk.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
timeline:1 The resource https://oransns.com/packs/js/features/notifications-d342cffdcff7316bfaad.chunk.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
timeline:1 The resource https://oransns.com/packs/js/features/getting_started-74c1cd31d6bcde40a20c.chunk.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
timeline:1 The resource https://oransns.com/packs/js/features/home_timeline-fcea891384b49101723a.chunk.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

```

logs screenshot:
![Screenshot 2021-04-25 132103](https://user-images.githubusercontent.com/83157156/115984486-24d6d280-a5c9-11eb-9af9-f5e168428ed9.png)

**Comment by ygsk100** [comment]
`DOMException: Failed to construct 'WebSocket': Access to this address is not allowed.`

The error in mastodon sites is probably related to *Block private networks scanning (gateway attacks)* #590

**Comment by csagan5** [comment]
@ygsk100 then you could try figuring out what address they are trying to reach and why. It could also be related to CORS.

**Comment by ygsk100** [comment]
The only websocket request is this, Status Code is `101 Switching Protocols`
```
curl 'wss://oransns.com/api/v1/streaming/?stream=user' \
  -H 'Pragma: no-cache' \
  -H 'Origin: https://oransns.com' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Sec-WebSocket-Key: 6CndD5Ny86Mf/DPikiRwrQ==' \
  -H 'User-Agent: ' \
  -H 'Upgrade: websocket' \
  -H 'Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits' \
  -H 'Cache-Control: no-cache' \
  -H 'Cookie: ' \
  -H 'Connection: Upgrade' \
  -H 'Sec-WebSocket-Version: 13' \
  -H 'Sec-WebSocket-Protocol: ztKl5chXCY3gK_-8MQPIv2oumBcWt4ERYYOpAAxKIyA' \
  --compressed
```

**Comment by ygsk100** [comment]
https://github.com/bromite/bromite/issues/590#issuecomment-738624112

> trying to connect to a server using websocket and I'm using this under a web worker

I've seen that Mastodon will run a service worker...
