### ISSUE TITLE
Twitter ads aren't blocked

### ISSUE THREAD

**Issue by jdaviescoates** [bromite/bromite#839]
### Bromite version

Version: 87.0.4280.81
Arch: dunno
Android version: 8.1.0
Device model: Wileyfox Swift 2 Plus

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

Not applicable as Chromium doesn't have built in as blocking

### Is the bug a crash?

No

### Describe the bug

Twitter ads are not being blocked.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to twitter.com
2. See ads

### Expected behavior

1. Go to twitter.com
2. See no ads (this is what happens when using Firefox Android with ublock origin add-on installed)

### Screenshots

https://files.uniteddiversity.coop/Screenshot_20201206-001746.png

**Comment by SV84** [comment]
Can confirm that. Also ads appear on other sites, like on APKMirror, too.

And this is from last 2-3 releases.

**Comment by csagan5** [comment]
See #840

**Comment by jdaviescoates** [comment]
It's confusing to that you are blaming uBlock origin filters when in both of the tickets you've just closed I've been explicit that in Firefox they work absolutely fine.
