### ISSUE TITLE
Duckduckgo search result ads aren't blocked

### ISSUE THREAD

**Issue by jdaviescoates** [bromite/bromite#840]
### Bromite version

Version: 87.0.4280.81
Arch: dunno
Android version: 8.1.0
Device model: Wileyfox Swift 2 Plus

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

Not applicable as Chromium doesn't have built in as blocking

### Is the bug a crash?

No

### Describe the bug

Ads are not being blocked in Duckduckgo search results

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Do a search on https://duckduckgo.com/
2. See ads

### Expected behavior

1. Do a search on https://duckduckgo.com/
2. See no ads (this is what happens when using Firefox Android with ublock origin add-on installed)

### Screenshots

https://files.uniteddiversity.coop/Screenshot_20201206-002644.png

**Comment by jdaviescoates** [comment]
I was able to 'solve' this by simply turning off ads in Duckduckgo settings (but would've preferred to not even have to do that).

**Comment by tlmnot** [comment]
It will be great without seeing the duckduckgo ads.

**Comment by csagan5** [comment]
I would submit this to the uBlock origin issue tracker, we do not really maintain filters here (just use them).

It might be solved next time there is a filters update, but otherwise you need to track down which filters' list is missing them and report it there.

**Comment by jdaviescoates** [comment]
OK, fair enough I guess, but really this doesn't make any sense to me because using Firefox with uBlock origin I never see ads on Twitter.  So it seems fairly clear the problem must be something Bromite related no not uBlock origin's filter which evidently do work.

**Comment by csagan5** [comment]
@jdaviescoates you can continue the investigation by checking in which filter the rule is. Until that is done I cannot accept it as a bug in Bromite.

**Comment by jdaviescoates** [comment]
I think I read somewhere that Bromite doesn't do CSS filters, is that right? If so, just a wild guess, but maybe that could be the issue.
