### ISSUE TITLE
Error: ERR_NAME_NOT_RESOLVED : Bromite does not connect to any websites

### ISSUE THREAD

**Issue by Frick-David** [bromite/bromite#841]
I installed Bromite through F-droid on my phone. It does not want to connect to any websites and errors out with "Site can not be reached
ERR_NAME_NOT_RESOLVED.
All my other internet connected apps work.
What can I do to test this?

**Comment by Frick-David** [comment]
Have you read the README? Yes,
Have you searched the issue tracker?  Yes, did not see anything similar
Are you sure this is not a Chromium bug? Yes, as Vanadium works.

### Bromite version

Version: 87.0.42
Arch: aarch64 
Android version: 11.0 - GrapheneOS
Device model: Pixel 4a

### Is this bug about the SystemWebView?
I am not sure. Probably not

### Is the bug reproducible with latest version?
I would assume so. GrapheneOS, add Bromite repo, and install it. I would assume this would reproduce it.

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug

No website will connect. Error about ERR_NAME_NOT_RESOLVED

### Steps to reproduce the bug

Steps to reproduce the bug:
Install bromite on grapheneOS
Install bromite from f-droid
open it and try to access a website.

### Expected behavior
It should connect to a website.

**Comment by Frick-David** [comment]
@csagan5  added template

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> Yes, this is reproducible with the corresponding Chromium version.

@Frick-David this means that the bug is not in Bromite. You probably have some issue on your OS DNS settings.
