### ISSUE TITLE
AMOLED Theme

### ISSUE THREAD

**Issue by mizzunet** [bromite/bromite#842]
### Is your feature request related to privacy?
No

### Is there a patch available for this feature somewhere?
1. Provide an overlay APK or
2. Make black theme available in Bromite

### Describe the solution you would like
AMOLED black theme together with dark gray theme

### Describe alternatives you have considered
None, but even with Substratum it can't be achieved as it is encrypted

Thanks 👍

**Comment by rnayabed** [comment]
Why was this rejected? Any particular reason?
