### ISSUE TITLE
Enable Timezone Randomization [By Default]

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [bromite/bromite#844]
### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No. But not impossible

### Describe the solution you would like

Timezone randomization is a great security feature. So it should be enabled by default for both browser and webview

**Comment by csagan5** [comment]
> Timezone randomization is a great security feature.

It is useless if you do not use a VPN. Your IP address tells very well where you are, and thus in which timezone. It is relevant only if you use a VPN, and in such case you can turn it on from the settings.
