### ISSUE TITLE
Disable WebGL Leaks Completely

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [bromite/bromite#845]
### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

Yes. Brave Browser already has this.

### Describe the solution you would like

It leaks so many information about GPU/CPU
So no information related to WebGL should leak (Like Brave Browser)

**Comment by csagan5** [comment]
Search the issue tracker for the related discussions and comment there.
