### ISSUE TITLE
Location Not Detected

### ISSUE THREAD

**Issue by Github-com-foss** [bromite/bromite#847]
Most of Websites Not detect my current Location.
Eg: Google Maps (webapp) not detect my current location, its loading.

![Location](https://user-images.githubusercontent.com/75672019/101642868-81da4d80-3a59-11eb-80d6-b945ce918e3f.jpg)

**Comment by csagan5** [comment]
Please submit the issues using the issue template; it will be visible when using GitHub in desktop mode.
