### ISSUE TITLE
Brightness behaves strange

### ISSUE THREAD

**Issue by anonymix007** [bromite/bromite#848]
### Bromite version

Version: `87.0.4280.81`
Arch: `arm64`
Android version: `10`
Device model: `GM-1910`

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is the bug a crash?

No

### Describe the bug

Image in Bromite lighter than in other apps, transition happens after app minimized/maximized and is highly noticeable

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Open Bromite
2. Go to main screen
3. Wallpaper "blinks": at first moment it is bright, but then it goes to normal, darker state.
4. On new tab there is similar behavior: at first page is light, then (after part of second) dark and then light again

### Expected behavior

No blinks

**Comment by anonymix007** [comment]
UPD: In older versions it worked fine, just checked `86.0.4240.194`

**Comment by csagan5** [comment]
Related: #817

> ### Can the bug be reproduced with corresponding Chromium version?
> No

Have you tested the corresponding Chromium for this issue?

**Comment by anonymix007** [comment]
Yes, I tested it and it worked fine

**Comment by csagan5** [comment]
> Proposed solution from [comment](https://github.com/bromite/bromite/issues/817#issuecomment-731578149) helped.

> I set Forced color profile flag to default and Forced colors and Dynamic color gamut to disabled.

`#force-color-profile` is always preset to default, and `#forced-colors`/`#dynamic-color-gamut` are both disabled by default. This is valid for both Chromium and Bromite; I do not understand how changing these values can have any effect (unless you had them set to something else before), nor how this can be a Bromite bug.

**Comment by anonymix007** [comment]
Installed latest Chromium and Bromite from F-Droid, and checked once again.
In Chromium changing it from default to enabled/disabled has no effect, but in Bromite default is the same as enabled and disabled makes it back to normal (as in old version). Are you sure that default is disabled in Bromite? For me it looks like that it's not.
Maybe there is some patch that started affecting that in v87? 
And it's interesting that as for now all reports (including mine) are from people with OnePlus devices.

**Comment by csagan5** [comment]
> Are you sure that default is disabled in Bromite?

Yes; there are no changes related to the color profiles in Bromite.

**Comment by anonymix007** [comment]
> Yes; there are no changes related to the color profiles in Bromite.
This is at odds with what I see.
Is it possible to set these flags to "disabled" instead of "default" in the next build? 

Could it be vendor-related?

**Comment by Poopooracoocoo** [comment]
I have a feeling it has to do with Samsung's "Vivid" or "Adaptive" display mode.

**Comment by anonymix007** [comment]
I think it's definitely vendor-related. And it looks like that changing screen refresh rate to 60 or to forced 90 hz helps (not auto 90 hz).
It seems that then I press space, "change language" button on keyboard or reopen Bromite screen refresh rate comes from 60 to 90 and to 60 again.
It's also reproduced with Fennec and Chromium now

**Comment by csagan5** [comment]
Since it is reproducible with Chromium please link here the upstream issue if you find it.

**Comment by anonymix007** [comment]
It was even reproducible with Firefox.
Problem reappeared again and I found what caused it in the first place - "auto 90 Hz" setting.
