### ISSUE TITLE
Github Error

### ISSUE THREAD

**Issue by Github-com-foss** [bromite/bromite#849]
### Bromite version

Version: `83.0...`
Arch: arm
Android version: (example: `10`)
Device model: (example: `SM-G960UZKABST`)

### Is this bug about the SystemWebView?
No

### Is the bug a crash?
No

### Describe the bug

Github is getting error while signing in incognito mode...

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Turn on always incognito mode '...'
2. Go github website '...'
3. Enter username and password '...'

### Screenshots

![101640147-2490cd00-3a56-11eb-8abc-ffa4c7d948e4](https://user-images.githubusercontent.com/75672019/101718254-d5cf4b80-3ac6-11eb-9105-d7923dd3be10.jpg)

**Comment by marcdw1289** [comment]
That's probably a third party cookie blocking thing. A PITA when using the site with Toby Kurien's WebApps.
Anyway, in Site Settings I changed the cookie settings from the default to block third party cookies in incognito mode. I was able to log in. When set back to the default I get the 404 page.
You could add github to the exception list and logins will work.

**Comment by csagan5** [comment]
Cannot reproduce with a fresh install.
