### ISSUE TITLE
Some websites seem to have imprecise click maps

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#85]
On websites like for example Reddit there is difficulty/impossibility to select menu items or buttons.

This might be due to the anti-fingerprinting mitigation in place for client rects.

**Comment by csagan5** [comment]
I am not sure anymore about this issue; can somebody else reproduce clicking issues on Reddit or similar sites?

**Comment by Slaviro** [comment]
What exactly doesn't work? I'm using Bromite Webview and Lightning Browser - menus working, post menus working, buttons clicking.

**Comment by csagan5** [comment]
@Slaviro sometimes clicking on Menu -> Inbox leads to a different page (like if I clicked something below the menu). Flipping to horizontal does not show this behaviour.

I am not sure though what is the cause, just speculation so far.

**Comment by csagan5** [comment]
Cannot reproduce this anymore.
