### ISSUE TITLE
Location Not Detected

### ISSUE THREAD

**Issue by Github-com-foss** [bromite/bromite#850]
### Bromite version

Version: `83.0...`
Arch: `arm`
Android version: (example: `10`)
Device model: (example: `SM-G960UZKABST`)

### Is this bug about the SystemWebView?
No

### Describe the bug

Most of Websites Not detect my current Location.
Eg: Google Maps (webapp) not detect my current location, its loading.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to Google maps website
2. Click on GPS icon (popup show show or deny)
3. If i click allow, its loading not detect my current location
4. Error

### Screenshots

![101642868-81da4d80-3a59-11eb-80d6-b945ce918e3f](https://user-images.githubusercontent.com/75672019/101718759-e3390580-3ac7-11eb-8896-9d077782b58a.jpg)

**Comment by csagan5** [comment]
> Can the bug be reproduced with corresponding Chromium version?

You have not filled in this section. I can re-open the issue after this test.

**Comment by Github-com-foss** [comment]
I tried on brave also same issue happen. But it works well in Firefox.

**Comment by marcdw1289** [comment]
On my current setup (OnePlus 8T, Android 11 OxygenOS) the location works with both Bromite v87...106 and Brave.
Reset and cleared site data for Google and tested. After allowing location, pressed the GPS button and it showed my general area. Pressing again it zooms in to my neighborhood.

If location is not working in either browser for you then it may be specific to your device or OS settings(?).
