### ISSUE TITLE
Tor Proxy support

### ISSUE THREAD

**Issue by NatureHog** [bromite/bromite#853]
### Is your feature request related to privacy?

Yes.

### Is there a patch available for this feature somewhere?

I don't know...

### Describe the solution you would like

I would like to be able to use my Tor proxy (using Orbot) to run through Bromite, so all the HTTPS traffic in Bromite is going though the Tor Network.

### Describe alternatives you have considered

Using other browsers...

**Comment by isuldor** [comment]
Have you tried configuring Bromite to use Orbot as a proxy?
https://github.com/bromite/bromite/wiki/ProxyConfiguration

**Comment by NatureHog** [comment]
Thanks! I didn't know how to use the PAC format.
