### ISSUE TITLE
Share website will crash Bromite

### ISSUE THREAD

**Issue by Fei1Yang** [bromite/bromite#858]
### Bromite version

Version: 87.0.4280.106
Arch: arm64
Android version: crDroid 11.0
Device model: Redmi K30 5G

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
crash

### Describe the bug
On Android 11, sharing any website will crash Bromite, this happens regardless whether Share Hub is enabled or not.

I have asked some of my friends which running Android 10 on their device, they cannot reproduce this share issue.

Logcat:
```
12-17 01:17:48.967 10933 10976 W System.err: java.lang.RuntimeException: An error occurred while executing doInBackground()
12-17 01:17:48.967 10933 10976 W System.err:    at Et.done(chromium-ChromePublic.apk-stable-1607389760:4)
12-17 01:17:48.967 10933 10976 W System.err:    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
12-17 01:17:48.967 10933 10976 W System.err:    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
12-17 01:17:48.967 10933 10976 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
12-17 01:17:48.967 10933 10976 W System.err: Caused by: java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority org.bromite.bromite.FileProvider
12-17 01:17:48.967 10933 10976 W System.err:    at M7.c(chromium-ChromePublic.apk-stable-1607389760:40)
12-17 01:17:48.967 10933 10976 W System.err:    at M7.a(chromium-ChromePublic.apk-stable-1607389760:3)
12-17 01:17:48.967 10933 10976 W System.err:    at M7.b(chromium-ChromePublic.apk-stable-1607389760:1)
12-17 01:17:48.967 10933 10976 W System.err:    at fy.a(chromium-ChromePublic.apk-stable-1607389760:4)
12-17 01:17:48.967 10933 10976 W System.err:    at org.chromium.base.ContentUriUtils.b(chromium-ChromePublic.apk-stable-1607389760:3)
12-17 01:17:48.967 10933 10976 W System.err:    at Ao1.c(chromium-ChromePublic.apk-stable-1607389760:1)
12-17 01:17:48.967 10933 10976 W System.err:    at Dt.call(chromium-ChromePublic.apk-stable-1607389760:4)
12-17 01:17:48.968 10933 10976 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-17 01:17:48.971 10933 10976 F chromium: [FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
...
12-17 01:17:49.125 11119 11119 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-17 01:17:49.125 11119 11119 F DEBUG   : crDroid Version: '7.0'
12-17 01:17:49.125 11119 11119 F DEBUG   : Build fingerprint: 'google/coral/coral:11/RP1A.201105.002/6869500:user/release-keys'
12-17 01:17:49.125 11119 11119 F DEBUG   : Revision: '0'
12-17 01:17:49.125 11119 11119 F DEBUG   : ABI: 'arm64'
12-17 01:17:49.125 11119 11119 F DEBUG   : Timestamp: 2020-12-17 01:17:49+0800
12-17 01:17:49.125 11119 11119 F DEBUG   : pid: 10933, tid: 10976, name: ThreadPoolForeg  >>> org.bromite.bromite <<<
12-17 01:17:49.125 11119 11119 F DEBUG   : uid: 10262
12-17 01:17:49.125 11119 11119 F DEBUG   : signal 5 (SIGTRAP), code -6 (SI_TKILL), fault addr --------
12-17 01:17:49.125 11119 11119 F DEBUG   : Abort message: '[FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
12-17 01:17:49.125 11119 11119 F DEBUG   : '
12-17 01:17:49.125 11119 11119 F DEBUG   :     x0  0000000000000000  x1  b400007753c45bb0  x2  0000000000000400  x3  ffffffffffffffff
12-17 01:17:49.125 11119 11119 F DEBUG   :     x4  ffffffffffffffff  x5  0000000000000000  x6  00000079ea472000  x7  0000000000078952
12-17 01:17:49.125 11119 11119 F DEBUG   :     x8  0000000000000000  x9  0000000000000000  x10 0000000000000000  x11 00000076794cef58
12-17 01:17:49.125 11119 11119 F DEBUG   :     x12 00000000ffffff80  x13 0000000000000051  x14 00000079e5890d22  x15 206176614a206564
12-17 01:17:49.125 11119 11119 F DEBUG   :     x16 00000076850a6b78  x17 00000079e58844fc  x18 0000007676114000  x19 00000076794cf408
12-17 01:17:49.125 11119 11119 F DEBUG   :     x20 00000076794cf420  x21 00000076794d0000  x22 00000076794cef58  x23 00000079e5890e80
12-17 01:17:49.125 11119 11119 F DEBUG   :     x24 00000076850b7000  x25 00000076794d0000  x26 000000000000004f  x27 0000000000000000
12-17 01:17:49.125 11119 11119 F DEBUG   :     x28 00000076794cf418  x29 00000076794cf3a0
12-17 01:17:49.125 11119 11119 F DEBUG   :     lr  000000768215e4d4  sp  00000076794cef40  pc  000000768215e6c4  pst 0000000060000000
12-17 01:17:49.126 11119 11119 F DEBUG   : backtrace:
12-17 01:17:49.126 11119 11119 F DEBUG   :       #00 pc 00000000024926c4  /data/app/~~6CBssIWZyvAvM2kjl_RPRw==/org.bromite.bromite-F_gpUnWAPp1ohbrj2Cr4Ug==/base.apk!libchrome.so (offset 0xb5c000) (BuildId: eca9eaab530e5419691532fb0d5bb1e49bad049a)
```

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Open any link.
2. Click on 3-dot menu>Share.
3. Share menu appear, but bromite crashed.

### Expected behavior
I can share website without crash Bromite.

**Comment by uazo** [comment]
Crash seems to be here `android.support.v4.content.FileProvider extends ContentProvider`

the code is not exactly that (maybe the missing if is some compiler optimization), but it almost looks like that

https://chromium.googlesource.com/android_tools/+/master/sdk/extras/android/support/v4/src/java/android/support/v4/content/FileProvider.java#558

`info` is null, here decompilated code
![image](https://user-images.githubusercontent.com/29201891/102592710-24f32d00-4114-11eb-88d1-a81105d62dee.png)

**Comment by uazo** [comment]
here
https://source.chromium.org/chromium/chromium/src/+/master:chrome/android/java/src/org/chromium/chrome/browser/FileProviderHelper.java;l=25

last call from `at org.chromium.base.ContentUriUtils.b(chromium-ChromePublic.apk-stable-1607389760:3)`

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> No

@Fei1Yang can you reproduce the crash with Chromium?

**Comment by Fei1Yang** [comment]
> > ### Can the bug be reproduced with corresponding Chromium version?
> > No
> 
> @Fei1Yang can you reproduce the crash with Chromium?

No, this issue only occurs on Bromite.

**Comment by csagan5** [comment]
@thestinger any idea what could cause this on A11? I am puzzled as of why this would happen with Bromite but not with Chromium

**Comment by thestinger** [comment]
It looks like maybe you might need to rename some metadata to match the Bromite app id? I'm not really sure. You should try a build without the app id changed to bromite.

**Comment by csagan5** [comment]
> It looks like maybe you might need to rename some metadata to match the Bromite app id? I'm not really sure. You should try a build without the app id changed to bromite.

Thanks for the tip, based on it I found this: https://github.com/chromium/chromium/blob/87.0.4280.106/chrome/browser/util/android/java/src/org/chromium/chrome/browser/util/ChromeFileProvider.java#L188

However the provider seems correctly declared in the manifest:
```xml
        <!-- Provider for FileProvider. -->
        <provider android:name="org.chromium.chrome.browser.util.ChromeFileProvider"
            android:authorities="org.bromite.bromite.FileProvider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
        </provider>
```

Does Android have an allow list for the Chromium package (without verifying signatures)? I am inclined to think not, since it would be a security flaw.

**Comment by thestinger** [comment]
> android:name="org.chromium.chrome.browser.util.ChromeFileProvider"

What about this part?

**Comment by csagan5** [comment]
The internal Java package name does not change; it should be the same for Vanadium; I went to double-check by decompiling a Bromite APK:
```
.class public Lorg/chromium/chrome/browser/util/ChromeFileProvider;
.super LM7;
.source "chromium-ChromePublic.apk-stable-1607389760"


# static fields
.field public static C:Ljava/lang/Object;

.field public static D:Z

.field public static E:Landroid/net/Uri;

.field public static F:Landroid/net/Uri;


# direct methods
.method public static constructor <clinit>()V
    .registers 1

    .line 1
    new-instance v0, Ljava/lang/Object;

    invoke-direct {v0}, Ljava/lang/Object;-><init>()V

    sput-object v0, Lorg/chromium/chrome/browser/util/ChromeFileProvider;->C:Ljava/lang/Object;

    return-void
.end method
[...]
```

If the internal Java package name was changed too, the breakage would be major as the `org.chromium.chrome` prefix is hardcoded in multiple places.

The error says:
> Caused by: java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority org.bromite.bromite.FileProvider

I wonder where such meta-data is defined if it is not the `AndroidManifest.xml`

**Comment by csagan5** [comment]
> You should try a build without the app id changed to Bromite.

That is basically the vanilla Chromium build, and reportedly it works; it is an interesting puzzle. I wonder if you can reproduce this issue for Vanadium too.

**Comment by uazo** [comment]
can this have to do with it?

https://developer.android.com/training/basics/intents/package-visibility#automatic

**Comment by Fei1Yang** [comment]
This issue no longer happens after I upgrade my ROM, so this maybe is a bug of my ROM.
Sorry for the convenience
