### ISSUE TITLE
Logging into discover.com gives outdated browser error

### ISSUE THREAD

**Issue by sivuda** [bromite/bromite#859]
yes

### Bromite version

Version: `87.0.4280.106`
Arch: `arm64`
Android version: (example: `10.0`)
Device model: (example: `SM-G986U1`)

### Is this bug about the SystemWebView?
Yes/No

No

### Is the bug reproducible with latest version?

yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is the bug a crash?

No

### Describe the bug

When I log into discover.com, I get the below error:
"Your account cannot currently be accessed.
Outdated browsers can expose your computer to security risks. To get the best experience on Discover.com, you may need to update your browser to the latest version and try again"

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to www.discover.com
2. Enter your credentials and click log in
3. See error

### Expected behavior

It supposed to log us into the website. Was able to login previously with different versions. Was able to log in with chromium. (Do not remember since what version I couldnt login)

### Screenshots

![362c2243-926b-4a23-bdc8-f7b7ec09a0bc](https://user-images.githubusercontent.com/60802237/102551199-f45bb680-4073-11eb-923d-16d3735e12f1.jpg)

**Comment by csagan5** [comment]
Report the bug to `discover.com`; if they do not want to fix their bug you could change the user agent through the custom user agent feature.
