### ISSUE TITLE
Battery Drain

### ISSUE THREAD

**Issue by pixincreate** [bromite/bromite#861]
# Bromite. 
**Version:** 87.0.4280.106. 
**Arch:** arm64. 
**Android version:** Stock Android One 10. 
**Device model:** Nokia 6.1 Plus (DRG). 

**Is this bug about the SystemWebView?**  
No

**Is the bug reproducible with latest version?**  
Yes

**Can the bug be reproduced with corresponding Chromium version?**  
No

**Is the bug a crash?**  
No

## Describe the bug:   
**In-Short:** Battery Drain.  
    I've seen many people complaining regarding the battery drain which I didn't believe about Bromite in the beginning. It's been nearly a month since I got to know and started using Bromite. 
    Within an hour of usage(In 3 - 4 hours, Using in between)
Battery for drained by 6%! Sometimes, nearly 20% (when used for an hour straight!) And I don't think it's normal as I'd used Brave, Firefox (with no satisfaction) before which it didn't.

**Steps to reproduce the bug:**  
- Check battery status
- Open Bromite,it may be either Incognito Mode or a Normal window. 
- Browse, Download, Read, anything for about an hour (atleast)
- Check battery status   
  
![Screenshot_as_Proof](https://user-images.githubusercontent.com/69745008/102597036-07d45380-4140-11eb-94d3-6dc0af433870.png)

Some screenshots will be updated later if needed for investigation

**Comment by csagan5** [comment]
> **Can the bug be reproduced with corresponding Chromium version?**
> No

Have you done this test with Chromium?

**Comment by pixincreate** [comment]
> > **Can the bug be reproduced with corresponding Chromium version?**
> > No
> 
> Have you done this test with Chromium?

Yes, I found no issues with that. Hardly, 2 - 3% dropped after using it for about an hour or so.

**Comment by tp0** [comment]
Install an app that displays more specific consumption stats/estimations, for example AccuBattery. Then compare to Chromium and try to do a continous 1-hour usage test scenario.

The drop in battery percentage alone doesn't tell much as it depends on battery size and other specs. What is your average screen-on usage per hour? (Any moderate use with screen on.)

**Comment by pixincreate** [comment]
> > > **Can the bug be reproduced with corresponding Chromium version?**
> > > No
> > 
> > 
> > Have you done this test with Chromium?
> 
> Yes, I found no issues with that. Hardly, 2 - 3% dropped after using it for about an hour or so.

I tested it again, now, it drained 5% in 42 min on Chromium. Similar to Bromite. So, it's the issue with the chromium itself? Can it be fixed?

**Comment by csagan5** [comment]
> So, it's the issue with the chromium itself? Can it be fixed?

You would have to check in the Chromium issue tracker; Chromium-based browsers will all show similar energy consumption.
