### ISSUE TITLE
Tabs seldom stop loading

### ISSUE THREAD

**Issue by Nemris** [bromite/bromite#862]
### Bromite version

Version: `87.0.4280.106`
Arch: `arm64`
Android version: `7.0`, `10.0`
Device model: `SM-A720F`, `SM-A405F`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
Yes

### Is the bug a crash?
No

### Describe the bug
Sometimes, trying to load a page makes the progress bar stuck at the beginning or around the middle.
Waiting for an amount of time results in either the page loading, or a connection error followed by an automatic reloading.

Manually reloading the page when the progress bar gets stuck loads the page just fine.

One known version of Bromite without this apparent bug is `86.0.4240.112`.

Note that this bug is fairly random. Examples of sites that triggered the bug are:
- m.facebook.com
- m.gsmarena.com
- forum.xda-developers.com

### Steps to reproduce the bug
1. Open a random site
2. Observe the progress bar getting stuck

### Expected behavior
Web pages should load fine, save for connection errors.

**Comment by csagan5** [comment]
> ### Can the bug be reproduced with corresponding Chromium version?
> Yes

Since this bug is reproducible with Chromium you have to report it on the Chromium issue tracker.

**Comment by Nemris** [comment]
Thank you for the hint - I'll do that.
