### ISSUE TITLE
Allow opening normal tabs when "Open links in incognito tabs always" is turned on

### ISSUE THREAD

**Issue by j-james** [bromite/bromite#864]
### Is your feature request related to privacy?

Yes.

### Is there a patch available for this feature somewhere?

No.

### Describe the solution you would like

The "Open links in incognito tabs always" setting is great, but makes it difficult to switch back to normal tabs when need be. It would be fantastic if this could be changed into a "Use incognito tabs by default" by making it possible to open normal tabs explicitly.

Currently, this setting means that _every_ new tab opens as private - even if you go to the tab overlay, swipe left, and hit the + button there, which would normally result in opening a new non-private tab. This feature request would change the previous behavior to open a normal tab instead of a private tab, even when enabled by the existing "Open links in incognito tabs always" setting. 

The reason behind wanting this change is that some people, myself included, find that Bromite letting you default to private tabs is great, but unfortunately means that it's not possible to easily temporarily switch back to using normal tabs, for example to persistently sign into a website. The existing UI of Chromium / Bromite makes it very clear whether you're opening a normal tab or a private one, and this change would take advantage of that.

### Describe alternatives you have considered

I'm not exactly sure what this question entails. The current "Open links in incognito tabs always" implementation, I suppose.

**Comment by uazo** [comment]
I personally think the idea of modifying the always patch by re-enabling normal browsing but showing a new anonymous default tab is an idea to consider.
for those who, like me, use always nothing changes, possibly the advantage in using those functions not yet active in always.
a button to delete all cookies / cache directly in the selection of tabs would be great, also useful for those who surf normally.
This thing would be done together with #728

**Comment by j-james** [comment]
Yes, that was my hope, that this wouldn't interfere with the way anyone currently uses Bromite. This would seem to cover everyone's use cases in #728.

**Comment by csagan5** [comment]
See also: https://github.com/GrapheneOS/Vanadium/issues/65#issuecomment-750394826

@uazo we should try to follow upstream closely on this; if the always-incognito feature needs to be redesigned then all the corner cases should be covered. Otherwise it is just going to be another year of whack-a-mole with bugs.

**Comment by uazo** [comment]
> we should try to follow upstream closely on this

currently it is only possible to disable. 
when he says "only a few patches to make before it can be supported on Android", our patch is that one, we can use that parameter, but does it make sense?

> Otherwise it is just going to be another year of whack-a-mole with bugs.

So, how can we improve?

**Comment by csagan5** [comment]
Have you read the code references in the Vanadium comment? We could start by trying to use that upstream feature.

**Comment by uazo** [comment]
> We could start by trying to use that upstream feature.

Sorry I don't understand. it doesn't work in android.
maybe do you want to use that flag? why?

**Comment by pixincreate** [comment]
I make a proposal here. See the below screenshot to know. I'd previously opened issue regarding this.  

![Screenshot_20210328-184141](https://user-images.githubusercontent.com/69745008/112753600-be748980-8ff5-11eb-9daa-78e139f7e9bb.png)  

> So, how can we improve?
This has already been implemented in Firefox. By the way, the screen shot is from the nightly version, however, you can see that option even in regular version as well:)  
I bet adding would be revolutionary.

**Comment by csagan5** [comment]
> Sorry I don't understand. it doesn't work in android.
> maybe do you want to use that flag? why?

It is speculated that it might work with some changes.

**Comment by pixincreate** [comment]
I found another app with the same/similar feature @csagan5 @uazo.   
JQwarks Viewer from f-droid. Link is [_**here**_](https://f-droid.org/packages/com.oF2pks.jquarks).  
This app allows user to open links in incognito window. Maybe, you can add it as a patch.:)

**Comment by uazo** [comment]
some notes about it, in my opinion this issue should be closed.
I personally changed my mind and I would tend not to mix normal and always incognito modes.
If any features are missing in incognito mode, perhaps it is better to add them in that, rather than risking passing data from normal to incognito (or vice versa).

> for example to persistently sign into a website

I think we can eventually try to add support for registering passwords in always incognito

**Comment by csagan5** [comment]
> some notes about it, in my opinion this issue should be closed.
> I personally changed my mind and I would tend not to mix normal and always incognito modes.
> If any features are missing in incognito mode, perhaps it is better to add them in that, rather than risking passing data from normal to incognito (or vice versa).

That has always been my position on this: that allowing opportunistic incognito makes the incognito feature _weaker_ on the long run.

Do we have other features that need to be revisited? e.g. history-in-incognito for example

**Comment by csagan5** [comment]
> lately working on the issues, I realized that in the (always) incognito browsing there are some things that I don't understand, for example if you delete the cookies from the pageinfo, the navigation is actually clean, but the infopage continues to show the old value, which it shouldn't be reading the code.

It could be something cached on the Java side.

> I do not know exactly why, maybe it is a chromium bug that does not appear or an incorrect modification of ours (or worse, we are mixing the profiles incorrectly), I would like to insert an automatic cleaning of the normal profile on opening if in always incognito, to protect the user.

We should not add a feature because we do not understand how something works.

> some time ago I saw something similar to alway incognito in the code of brave, I have to look at it, and compare it with ours

Good idea.



> they have modified the ntp and (with v94) it no longer shows the omnibox (which they call fakebox in incognito) at startup, very annoying.

We can also not support omnibox in incognito in v94; I guess I will understand better once I try.
