### ISSUE TITLE
Bromite for Linux / Windows?

### ISSUE THREAD

**Issue by resynth1943** [bromite/bromite#869]
Here is your issue template. Are there any plans to create a distribution of Bromite for Linux?

### Is your feature request related to privacy?

Yes.

### Is there a patch available for this feature somewhere?

No.

### Describe the solution you would like

Linux for Desktop.

### Describe alternatives you have considered

Answering https://github.com/bromite/bromite/issues/724

**Comment by csagan5** [comment]
There are no plans; the closest match is [ungoogled-chromium](https://github.com/Eloston/ungoogled-chromium).
