### ISSUE TITLE
Use per-site adblock content setting

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#87]
Chromium already has per-site adblock content settings; Bromite could use that setting and add an extra option in the three-dots menu "Adblock whitelist site" or similar to disable adblocks on a specific site.

**Comment by Sterilize** [comment]
Would it be possible to do the same for  Javascript.?

**Comment by fredgolightly** [comment]
Brave's implementation of this is great, Kiwi's less great, Bromite's lacking. Any chance of this?

**Comment by BetaLyte** [comment]
GelloMod have (had) this under Site Settings, which seems like a logical place to put it. I'm guessing it's implemented somewhere in here: https://github.com/LineageOS/android_packages_apps_Gello/blob/cm-14.1/src/com/android/browser/preferences/SiteSpecificPreferencesFragment.java

**Comment by Riotous** [comment]
@csagan5 Any progress on this for both adblocking and Javascript? I'd like to disable Javascript on some sites and whitelist some sites from adblocking.

**Comment by csagan5** [comment]
It should now possible to change whitelist settings for each site, as in `77.0.3865.81` the native Chromium engine is used.
