### ISSUE TITLE
Self build fails starting from Release 87.0.4280.68

### ISSUE THREAD

**Issue by scanno** [bromite/bromite#870]
### Bromite version

Version: `87.0.4280.68.` and higher
Arch: `arm64`
Android version: not relevant, build failure
Device model: not relevant, build failure

### Is this bug about the SystemWebView?
Yes/No -> system_webview_apk also fails to build

### Is the bug reproducible with the latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?
No, the build works fine and the result is usable (chrome_public_apk and system_webview_apk).

### Is the bug a crash?
`[32524/54582] LINK ./chrome_crashpad_handler
FAILED: chrome_crashpad_handler exe.unstripped/chrome_crashpad_handler exe.unstripped/chrome_crashpad_handler.map.gz 
python "../../build/toolchain/gcc_link_wrapper.py" --output="./chrome_crashpad_handler" --strip="../../buildtools/third_party/eu-strip/bin/eu-strip" --unstripped-file="./exe.unstripped/chrome_crashpad_handler" --map-file "./exe.unstripped/chrome_crashpad_handler.map.gz" -- ../../third_party/llvm-build/Release+Asserts/bin/clang++ -Wl,--fatal-warnings -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -fuse-ld=lld -Wl,-z,max-page-size=4096 -Wl,--icf=all -Wl,--color-diagnostics -flto=thin -Wl,--thinlto-jobs=8 -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy,cache_size=10\%:cache_size_bytes=10g:cache_size_files=100000 -Wl,--lto-O2 -Wl,-mllvm,-import-instr-limit=5 -Wl,--no-rosegment -Wl,--no-call-graph-profile-sort -Wl,--exclude-libs=libgcc.a -Wl,--exclude-libs=libvpx_assembly_arm.a --target=aarch64-linux-android21 -Wl,-mllvm,-enable-machine-outliner=never -Werror -Wl,--warn-shared-textrel -Wl,-O2 -Wl,--gc-sections -nostdlib++ --sysroot=../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot -B../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64 -Wl,--warn-shared-textrel -pie -Bdynamic -Wl,-z,nocopyreloc -Wl,-wrap,calloc -Wl,-wrap,free -Wl,-wrap,malloc -Wl,-wrap,memalign -Wl,-wrap,posix_memalign -Wl,-wrap,pvalloc -Wl,-wrap,realloc -Wl,-wrap,valloc -Wl,-wrap,strdup -Wl,-wrap,strndup -o "./exe.unstripped/chrome_crashpad_handler" -Wl,--start-group @"./chrome_crashpad_handler.rsp"  -Wl,--end-group  -ldl -lm -landroid -llog -latomic ../../base/android/library_loader/anchor_functions.lds
ld.lld: error: linking module flags 'ProfileSummary': IDs have conflicting values in 'obj/base/libbase.a(logging.o at 1034846)' and 'ld-temp.o'
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

### Describe the bug

Building bromite from the repository fails from release 87.0.4280.68 and above, including 87.0.4280.131. Release 87.0.4280.67 was the last release that builds successfully for me. Building pure Chromium 87.0.4280.131 results in a successful and working build (.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. checkout chromium version 87.0.4280.131
2. checkout bromite tag 87.0.4280.131
3. apply the patches
4. apply the GN arguments
5. build Chromium (chrome_public_apk)

### Expected behavior

I would expect a succesful build without failures

**Comment by csagan5** [comment]
Sorry, the issue tracker is for Bromite bugs, no support is provided for builds; I remember seeing this error and a clean build would fix it.

**Comment by scanno** [comment]
I always build clean

**Comment by csagan5** [comment]
Are you using ccache?

**Comment by scanno** [comment]
Yes, i do. Strange thing is that normal chromium builds fine

**Comment by csagan5** [comment]
See? That is why no support is provided for builds, everyone has its own quirks and issues.

Clearing the ccache files will fix this issue.

**Comment by lordarcadius** [comment]
> See? That is why no support is provided for builds, everyone has its own quirks and issues.
> 
> Clearing the ccache files will fix this issue.

How to clean ccache of Chromium?
