### ISSUE TITLE
Disable persistent histograms in SystemWebView

### ISSUE THREAD

**Issue by syphyr** [bromite/bromite#873]
### Bromite version

Version: `87.0.4280.131`
Arch: `arm64`
Android version: `7.0`
Device model: `SM-T813`

### Is this bug about the SystemWebView?
Yes

### Is the bug reproducible with latest version?
yes

### Can the bug be reproduced with corresponding Chromium version?
yes

### Is the bug a crash?
no

### Describe the bug

* It's probably some kind of bug somewhere that these
  BrowserMetrics-*.pma files are never deleted, but they don't really
  add value to us in the first place.
* Stop eating 4MB every single time any app that uses webview
  ever opens.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. 4MB is used every time a webview app is opened with Browser Metrics files

### Expected behavior

This bug has been fixed in chromium webview used by LineageOS with the following:
https://review.lineageos.org/c/LineageOS/android_external_chromium-webview/+/298862/1/patches/no-persistent-histograms.patch

**Comment by csagan5** [comment]
Interesting; the bug seems to have been introduced in https://github.com/chromium/chromium/commit/b86102f2a243, I will consider patching this for next release.

**Comment by csagan5** [comment]
Fixed in `88.0.4324.95`.
