### ISSUE TITLE
Night light (blue-lights filter) not working when opening Bromite

### ISSUE THREAD

**Issue by kibalcic** [bromite/bromite#877]
### Bromite version

Version: `87.0.4280.131`
Arch: `arm64`
Android version: 10
Device model: `Oppo Find X2 Lite`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is the bug a crash?

No

### Describe the bug

The blue-lights filter stops working as soon as I open Bromite. It works in bromite settings though. It doesn't happen on Moto G5S Plus (Android 10), only on this device.

**Comment by csagan5** [comment]
Can you provide steps to reproduce this bug?
