### ISSUE TITLE
Feature Request: Chrome-like News Section

### ISSUE THREAD

**Issue by famecastle** [bromite/bromite#878]
I'm using my browser every day and a thing I'm really missing much is the news section that comes up at the bottom of the screen when you open a new tab in Chrome. It was my daily portion of everything - politics, society, arts, tech news.

![image](https://user-images.githubusercontent.com/11258821/103926142-d33d3180-5118-11eb-8a60-0f064c7dadb0.png)

_Note: In this screenshot, the section is already scrolled up. Normally, only between 1/2 to 1 and 1/2 articles are visible at the bottom._

Could we have such a thing (with a similar design, because it's just so well made in its non-distracting placement and behavior) in Bromite as well? I also believe this is a feature which will Bromite more unique amongst other (proprietary and open source) browsers.

If this idea would be taken into consideration, I'd suggest that we fetch the news using goold old RSS feeds. As long as we don't have pre-populated community-created lists of good news feeds for each country, we could just show a little notice at the bottom telling the users that they can add their own feeds if they like.

**Comment by jbhatami** [comment]
perhaps you missed this tidbit on their homepage:

*Minimal UI changes are applied to help curbing the idea of “browser as an advertisement platform”.*

Just go to news.google.com and add a bookmark.

**Comment by Timmy183-ui** [comment]
Feature Request not related to privacy are not concerned at all

**Comment by sjehuda** [comment]
Duplicated of #2020 

> Feature Request not related to privacy are not concerned at all

RSS, in essence, IS privacy concerned!

> Content publishers hate on it because they can't do user tracking with it. RSS feeds are just text with some bits attached, such as MP3 files for podcasts. There's no JavaScript or any of the fancy stuff for tracking you, just an IP address. And if you go through an aggregator there isn't even that.

> They absolutely hate that. They'd much prefer if you used their websites or apps, where they can study you like a bug.

From https://teddit.net/r/apple/comments/4xx1gv/apple_news_no_longer_supports_rss_feeds/d6jo3g9/#c

RSS was removed because it is harder to violate privacy with the presence RSS.
