### ISSUE TITLE
Difficult to read color of font in ads site setting description in dark mode.

### ISSUE THREAD

**Issue by JVS-XII** [bromite/bromite#880]
### Bromite version
Version: 87.0.4280.131
Arch:arm64
Android version: 7.0
Device model: PRA-LA1
### Is this bug about the SystemWebView?
No
### Is the bug reproducible with latest version?
Yes
## Can the bug be reproduced with corresponding Chromium version?
This is due to Bromite's feature
### Is the bug a crash?
Very like that, I've never seen black letters in this place before.
### Screenshot
![IMG_20201226_094014.png](https://user-images.githubusercontent.com/77104981/103908194-cd554980-5134-11eb-9bd1-530e92972514.png)

**Comment by JVS-XII** [comment]
I thought this button "Close" closes the menu. I'm new. 😁

**Comment by Xi-PP** [comment]
Go to site settings from settings menu then toggle off Ads 😪 i don't think you want intrusive ads... & the colours issue will gone

**Comment by JVS-XII** [comment]
![IMG_20210110_133948.png](https://user-images.githubusercontent.com/77104981/104120681-463de680-536b-11eb-87b3-394e5836d8b8.png)🤔😏

**Comment by csagan5** [comment]
> ## Can the bug be reproduced with corresponding Chromium version?
> This is due to Bromite's feature

This is not optional; you need to test with the corresponding Chromium version.
