### ISSUE TITLE
"Reverse the meaning of bypass rules" broken

### ISSUE THREAD

**Issue by DudmasterUltra** [bromite/bromite#884]
## Bromite version
Version: 87.0.4280.131
Arch: arm64
Android version: 11.0
Device model: Google Pixel 4a 5g (GD1YQ)

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug
In the chrome://proxy configuration page, "Reverse the meaning of bypass rules" unchecks itself upon clicking "Apply". This renders the setting unusable.

### Steps to reproduce the bug
1. Go to Settings -> Privacy -> Proxy configuration
2. Enter any valid proxy configuration
3. Enter any valid "bypass rules"
4. Check "Reverse the meaning of bypass rules"
5. Click apply
6. Observe the previous checkbox un-checks itself

### Expected behavior
The check box should remain checked and saved properly.

**Comment by DudmasterUltra** [comment]
Well, now the proxy page doesn't even load in 88.0.4324.95

**Comment by csagan5** [comment]
Fixed in `88.0.4324.149`.
