### ISSUE TITLE
User-selectable ciphersuites

### ISSUE THREAD

**Issue by Serphentas** [bromite/bromite#885]
### Is your feature request related to privacy?

Yes, as some TLS ciphersuites are unsafe and can therefore lead to a degraded security level when browsing websites (ex. TLS_RSA_WITH_AES_128_CBC_SHA).

### Is there a patch available for this feature somewhere?

No, but Chromium (and alike) can be started with commands such as `chromium --cipher-suite-blacklist=0x0035,0x002f,0x009d,0x009c,0xc014,0xc013,0xcca9,0xc02c,0xc02b`.

### Describe the solution you would like

Be able to individually toggle which ciphersuites are enabled in Bromite, or toggle lists of ciphersuites, so that one can totally avoid using unsafe ciphersuites.

### Describe alternatives you have considered

Firefox-like browsers already offer such settings in `about:config` under `ssl`, not requiring custom launch commands.

![photo_2021-01-16_15-49-52](https://user-images.githubusercontent.com/9091195/104815059-90fbaa80-5812-11eb-9a26-d232478a303f.jpg)

**Comment by csagan5** [comment]
> lead to a degraded security level when browsing websites

I would rather disable all weak ciphersuites by default and offer a flag to re-enable them (not individually, but in bulk). Offering individual flags for all the ciphersuites would be problematic to maintain.

**Comment by Serphentas** [comment]
That's a good way to go, because most properly-maintained website already feature TLS 1.3 or at least some Forward Secrecy-proof suite and so it shouldn't exclude too many services (like MEGA, SourceForge, etc).

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
> > lead to a degraded security level when browsing websites
> 
> I would rather disable all weak ciphersuites by default and offer a flag to re-enable them (not individually, but in bulk). Offering individual flags for all the ciphersuites would be problematic to maintain.

Sounds cool

**Comment by csagan5** [comment]
The problem with introducing a patch for this is that it would go stale without anybody noticing, thus doing a disservice to users.

**Comment by Serphentas** [comment]
> The problem with introducing a patch for this is that it would go stale without anybody noticing, thus doing a disservice to users.

Why exactly would it go stale ? There's not a ton of testing to do for such a simple feature.

**Comment by csagan5** [comment]
> Why exactly would it go stale ? There's not a ton of testing to do for such a simple feature.

You can offer to develop and maintain over time such patch then.
