### ISSUE TITLE
Broken "Recent tabs" behaviour

### ISSUE THREAD

**Issue by tp0** [bromite/bromite#886]
### Bromite version

Version: `87.0.4280.131`
Arch: `arm64`
Android version: 10
Device model: Moto G8 Power/XT2041-3 

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is the bug a crash?

No

### Describe the bug

When opening a recently closed tab via 3-dot menu > Recent tabs, the tab is re-opened in correct place but the view switches to the previous tab.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Open 3 new tabs (any webpages)
2. Switch to tab 3 and close it
3. (View is now in tab 2) Tap 3-dot menu > Recent tabs, re-open the tab you just closed
4. The tab's content is re-opened in tab 2, but the view switches to tab 1

### Expected behavior

In step 4 the view stays on tab 2.

---

**Additional info:**

This bug first time appears in Bromite 85.0.4183.84, but is not reproducible in corresponding Chromium 85.0.4183.84.

**Comment by uazo** [comment]
it is probably due to https://github.com/bromite/bromite/blob/d4dd2dd63bf95109efe23f36bfcda2a1f5863041/build/patches/Bromite-AdBlockUpdaterService.patch#L207-L210
added to fix https://github.com/brissues/bromite/681

**Comment by csagan5** [comment]
@uazo sure, but I think that is the wrong patch. It does not seem related to adblocking.

**Comment by csagan5** [comment]
It is on the correct file; I will fix the existing patch.

**Comment by uazo** [comment]
> what are the downsides of changing FROM_LONGPRESS_BACKGROUND in FROM_LINK? This file was not previously changed by other patches

no difference, currently `createTabWithWebContents` seems to only be called by the restore code.
You can see here https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/ui/android/tab_model/tab_model_jni_bridge.cc;l=81 (the native chain of `tab_model->CreateTab()`)

**Comment by csagan5** [comment]
Fixed in `88.0.4324.95`.
