### ISSUE TITLE
No support for 90hz displays

### ISSUE THREAD

**Issue by mcergun** [bromite/bromite#887]
No support for 90hz display refresh rate. 
I'm using oneplus 7t as my daily driver. When my screen refresh rate is chosen as 90hz I get the same result as with 60hz selected. The display feels choppy.

Firefox or Chrome browsers offer different experiences with different refresh rates (choppy on 60hz, smooth on 90hz) while bromine feels laggy on either 60hz or 90hz. 

I use bromite v87.0.4280.131 armx64

**Comment by mcergun** [comment]
Is this rejected?

**Comment by Bec-de-Xorbin** [comment]
> Is this rejected?

Yes, because it happens also with Chromium. I'm using AutoHz to force 120 Hz.
