### ISSUE TITLE
cannot group tabs with tab grid enabled

### ISSUE THREAD

**Issue by BrandonH28** [bromite/bromite#894]
### Bromite version

Version: 88.0.4324.95
Arch: arm64
Android version: 11.0
Device model: Google Pixel 3a G020G

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
yes

### Can the bug be reproduced with corresponding Chromium version?
no

### Is the bug a crash?
no

### Describe the bug

i successfully enable tab grid layout in chrome://flags (takes a couple restarts). when i try to group tabs by dragging one on top of another, they do not group, but instead just re-position.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. go to chrome://flags/#enable-tab-grid-layout
2. toggle to 'enabled'
3. restart bromite until change is enabled
4. click tabs button on toolbar
5. try to group tabs by dragging one tab on top of another

### Expected behavior

create a new tab group

**Comment by Xi-PP** [comment]
chrome://flags/#enable-tab-groups
Try this

**Comment by BrandonH28** [comment]
thanks!
