### ISSUE TITLE
Optional Disable Background Audio

### ISSUE THREAD

**Issue by CJ-47** [bromite/bromite#897]
Is it possible to compile an optional apk which has background video playback disabled by default,if not can Dev help me modify the source.zip file and recompile a new apk(  I do not intend to publish/share the apk ).

**Comment by Poopooracoocoo** [comment]
You should just be able to go to chrome://flags and disable it from there, unless I'm not understanding you correctly.. You don't need a separate build.

**Comment by csagan5** [comment]
Background video playback is disabled by default since `86.0.4240.194`.
