### ISSUE TITLE
Https only mode 

### ISSUE THREAD

**Issue by hefty-fading-culprit-epiphany-drew** [bromite/bromite#902]
### Is your feature request related to privacy?
Yes

### Is there a patch available for this feature somewhere?
Brave and Firefox already have tbjs

### Describe the solution you would like
Blocking unencrypted connections by default and trying to force https would enhance privacy greatly.

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
Maybe you can look into the code of NoHttp 
https://addons.mozilla.org/en-US/firefox/addon/nohttp/
It's a great extension under 10kb and recommended by librewolf project(they recommend it over https  everywhere for the reasons listed in
https://github.com/intika/Librefox/issues/23#issuecomment-449784908)

**Comment by uazo** [comment]
@csagan5 I found this https://source.chromium.org/chromium/chromium/src/+/master:net/url_request/url_request_http_job.cc;l=207;drc=2ac64302ae161cd6b5e4b1254497bdf5fd6d3415
Can it be of interest?

**Comment by csagan5** [comment]
@uazo no; this has been asked multiple times before, see older issues.

**Comment by csagan5** [comment]
@uazo the problem with a feature to "first try HTTPS, then fallback to HTTP" is that you could have there two different sites and no way to explicitly access one or the other. In general anything which makes choices for the user breaks transparency.

Also: having to first try HTTPS and then HTTP creates a specific signature and introduces some latency. The feature you pointed at (`isClearTextPermitted`) is surely useful for specific hosts which are often subject to cleartext MiTM, but I have not investigated how it works.

**Comment by uazo** [comment]
> a feature to "first try HTTPS, then fallback to HTTP"

I was thinking of a flag + a whitelist.
that call passes to java, so the patch can be all just java.

>  I have not investigated how it works.

neither do I, only that browsing the code, every now and then I see interesting things that I mark, and that was one.

**Comment by csagan5** [comment]
> I was thinking of a flag + a whitelist.
> that call passes to java, so the patch can be all just java.

No, I explained above the rationale. We are not implementing this feature in a browser (which causes an extra HTTP request all the times) for websites that forget to enable a redirect from HTTP to HTTPS.
