### ISSUE TITLE
Add support for custom filters to be used with default filters

### ISSUE THREAD

**Issue by hbarsaiyan** [bromite/bromite#906]
### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

I do not know

### Describe the solution you would like

Ability to add custom filters like this so that we can use them with existing bromite filters.
![Screenshot_20210206-000300_Brave_-_Beta](https://user-images.githubusercontent.com/37732050/107074940-731cd680-680f-11eb-9ea7-71eac6369668.png)

### Describe alternatives you have considered

Downloading the bromite filter database and adding it to them. But it is difficult to keep the filter database in sync with upstream then.

**Comment by Prometheus38** [comment]
At least can someone explain how to use ruleset_converter to create custom filter. I am trying to figure it out but could not understand how to use it. Adblocker kinda useless without regional filters.

**Comment by infinitewaveparticle** [comment]
i agree with this 1000%

**Comment by csagan5** [comment]
No intention to develop or maintain this, sorry.
