### ISSUE TITLE
uninstalling Bromite deletes downloaded file

### ISSUE THREAD

**Issue by davexnet** [bromite/bromite#907]
Bromite version

Version: 88.0.4324.141
Arch: arm64
Android version: 9
Device model: Moto G& Power
Is this bug about the SystemWebView?
No

Is the bug reproducible with latest version?
Yes

Can the bug be reproduced with corresponding Chromium version?
Yes

Is the bug a crash?
No

Describe the bug

If the browser is used to download files, mp3 or jpg, for example and left in the default
download folder, when the browser is uninstalled the files are deleted.  It's as if the browser still
thinks it owns those files.
This can't be expected behavior, and is reproducible  in the Chromium from your site.
Thanks -
Dave H

**Comment by csagan5** [comment]
> This can't be expected behavior

It is. All Android apps work like this; when you delete them, files created on internal storage through them are gone. You can try setting the Download directory to external storage, but I do not know if it works on recent Android versions.

> Can the bug be reproduced with corresponding Chromium version?
> Yes

Then it is not a Bromite bug.

**Comment by davexnet** [comment]
Of course, I would report to the proper parties, but I don't know where.If you know which is the appropriate site, please let me know
Dave H

    On Friday, February 5, 2021, 4:00:48 PM PST, Carl <notifications@github.com> wrote:  
 
 


Closed #907.
