### ISSUE TITLE
Allow user-installed certificates

### ISSUE THREAD

**Issue by ygsk10** [bromite/bromite#918]
### Bromite version

Version: `88.0.4324.149`
Arch: `arm64`
Android version: 11
Device model: redfin

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes 

### Can the bug be reproduced with corresponding Chromium version?

No

### Is the bug a crash?
No

### Describe the bug

I use a domain fronting tool, a generated-CA is to be trusted.

The tool runs in Termux, and forward traffic with removing SNI to evade SNI-based HTTPS filtering.

I install the CA in Android Settings, and Bromite accepted the MITM, until hours ago it updated to version `88.0.4324.149`

### Steps to reproduce the bug

Steps to reproduce the bug:

I don't think developer need to run the same tool

https://github.com/URenko/Accesser

Just do some MITM test

### Expected behavior

Bromite should accept the certificate as it did in last version, `88.0.4324.141`

### Screenshots

![Screenshot_20210209-001843](https://user-images.githubusercontent.com/78546988/107247580-63e69480-6a6c-11eb-89fc-b8c17a770f35.png)
Bromite refuse certificate signed by a custom CA

![Screenshot_20210209-002055](https://user-images.githubusercontent.com/78546988/107247999-d6f00b00-6a6c-11eb-90cc-2dc66b56fb31.png)
The certificate being refused

![Screenshot_20210209-002111](https://user-images.githubusercontent.com/78546988/107248048-e4a59080-6a6c-11eb-8bf3-254f4e68ee80.png)

CA is trusted in Android Settings

**Comment by ygsk10** [comment]
I tried the same version of Chromium in the Bromite official F-Droid repo.

Cannot reproduce:

![Screenshot_20210209-003912](https://user-images.githubusercontent.com/78546988/107251484-5a126080-6a6f-11eb-8f2f-03bacf8dd379.png)
![Screenshot_20210209-003921](https://user-images.githubusercontent.com/78546988/107251497-5c74ba80-6a6f-11eb-84ff-99c0901d00bd.png)
![Screenshot_20210209-004025](https://user-images.githubusercontent.com/78546988/107251549-6b5b6d00-6a6f-11eb-9945-6997d4cfd6ca.png)

**Comment by dtaylor84** [comment]
I was about to raise this issue myself, but it seems I was beaten to it.

I've noticed the changelog explicitly mentions this change in .149: 

> do not permit user-installed certificates

https://github.com/bromite/bromite/blob/master/CHANGELOG.md

But I don't understand why - I want to use my user-installed certificate with Bromite!
