### ISSUE TITLE
Ads appear on last.fm

### ISSUE THREAD

**Issue by Elaborendum** [bromite/bromite#933]
### Bromite version

Version: `88.0.4324.149.`
Arch: `arm64`
Android version: `10`
Device model: `SM-A205G`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
No

### Describe the bug
If I search something on https://www.last.fm/, an ad appears.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to 'https://www.last.fm/'
2. Search for anything
3. See ad

### Expected behavior
No ads appear

### Screenshots
![image](https://user-images.githubusercontent.com/71190696/108136126-69089c80-7087-11eb-9080-4c279d7e27aa.png)

**Comment by csagan5** [comment]
Cannot reproduce.

**Comment by Elaborendum** [comment]
After reinstalling it, I realized that it only happens if I choose a DNS from within the browser. I was using Quad9 if that helps reproduce it.
