### ISSUE TITLE
Bookmarks sync for Bromite

### ISSUE THREAD

**Issue by galaktiker** [bromite/bromite#94]
Could please add sync function (at least boookmarks)? For those, who have rooted Android... Is it possible?

**Comment by lowtrucks** [comment]
yes, it is:

https://forum.xda-developers.com/showpost.php?p=73048109&postcount=746
http://4pda.ru/forum/index.php?showtopic=307861&st=13780#entry63245859

**Comment by csagan5** [comment]
Another user reported that issue templates do not appear here on Github via mobile; I had always been assuming that the issue template was being ignored for opened issues like this, sorry for that.

(Issues not following the template are considered invalid)

As for your specific question: there is a bookmarks import/export functionality but there will be no sync functionality.
