### ISSUE TITLE
Link to apkmirror.com as a mirror

### ISSUE THREAD

**Issue by chromer030** [bromite/bromite#942]
### Is your feature request related to privacy?
No.

### Is there a patch available for this feature somewhere?
No.

### Describe the solution you would like

Since there is an always up-to-date repository of Bromite and BromiteWebView on apkmirror, it would be better to mention it on README.md and website.

Link : 
https://www.apkmirror.com/apk/bromite/

the bottom is also well designed and available :

![get-it-on-apkmirror](https://user-images.githubusercontent.com/13361552/108629650-26bfd080-7476-11eb-9cb4-4e6a37601716.png)

**Comment by Pentaphon** [comment]
I'm pretty sure the dev would prefer we use the f-droid repo which is more useful anyway.

**Comment by csagan5** [comment]
I have no control about how and when these files are uploaded; I do not know who is uploading them.

It is not an officially supported download location.
