### ISSUE TITLE
Option to delete cookies on exit is missing (or very well hidden)

### ISSUE THREAD

**Issue by Herpderpus666** [bromite/bromite#950]
### Bromite version

Version: `88.0.4324.149`

### Is this bug about the SystemWebView?
No

### Is the bug a crash?

No

### Describe the bug

It appers there should be a way to set the browser to clear cookies on exit. 
For example, here there is a screenshot of the setting to do so
https://github.com/bromite/bromite/issues/142
But, in my browser this is nowhere to be found. Either it's very well hidden and no longer under Site Settings, Cookies, or there is something wrong with my browser.

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
Can confirm this

**Comment by csagan5** [comment]
See https://github.com/bromite/bromite/blob/master/CHANGELOG.md#850418394

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
So... It was removed a while ago
