### ISSUE TITLE
Ad block not working on build 88.0.4324.187

### ISSUE THREAD

**Issue by danieljarolim** [bromite/bromite#960]
### Bromite version

Version: 88.0.4324.187
Arch: arm64
Android version: 11
Device model: IN2023

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Only latest version.

### Can the bug be reproduced with corresponding Chromium version?
N/A

### Is the bug a crash?
No

### Describe the bug
Ad blocking is not working on latest build. Google ads showing on all sites. Reverting to previous build 88.0.4324.185 fixes problem.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Check that filters have updated in settings / ad blocking.
2. Go to businessinsider, see google ad top of page, overlay bottom of page, and popover with build 88.0.4324.187, clean page with build 88.0.4324.185

### Expected behavior
Same page as displayed by in 88.0.4324.185

**Comment by csagan5** [comment]
What happens if you manually download the filters from the Ad block settings page?

**Comment by danieljarolim** [comment]
I first saw this on a new install so I forced a refresh and that didn't change anything. Then I tried an older version, checked that it was working then upgraded to current build and that didn't work either.

**Comment by csagan5** [comment]
@danieljarolim can you please submit your `adb logcat` logs? please remove any privacy-sensitive information; only the Bromite log lines are needed.

**Comment by uazo** [comment]
the oddity is that the same behavior can also be seen in chromium desktop in responsive mode without any adblock. 
I don't think it's a bromite issue

**Comment by csagan5** [comment]
> the oddity is that the same behavior can also be seen in chromium desktop in responsive mode without any adblock.

Chromium desktop does not have the subresource filter with the filters of Bromite, so I doubt that it is comparable or that it brings any new information to the troubleshooting.

> I don't think it's a bromite issue

We could rollback the changes for the AdBlock filters UI and verify that.

**Comment by csagan5** [comment]
I am thinking that perhaps the updater bridge is the problem: a race condition with the native part loading? With the user logs we should be able to troubleshoot this.

**Comment by uazo** [comment]
> Chromium desktop does not have the subresource filter with the filters of Bromite, so I doubt that it is comparable or that it brings any new information to the troubleshooting.

sure, but give it a try, changing the screen size sometimes shows up sometimes not.

> We could rollback the changes for the AdBlock filters UI and verify that.

yes, or we add "check on every boot", but it's a workaround, we don't fix anything.

> I am thinking that perhaps the updater bridge is the problem: a race condition with the native part loading? With the user logs we should be able to troubleshoot this.

I thought about it, but I don't think so, once the filters are available in the folder they are loaded regardless of the update, and the patch just downloads, it doesn't do anything else you know

**Comment by csagan5** [comment]
> sure, but give it a try, changing the screen size sometimes shows up sometimes not.

What ads do you expected to be filtered on Chromium desktop? Those of the subresource filter?

**Comment by uazo** [comment]
> What ads do you expected to be filtered on Chromium desktop? Those of the subresource filter?

on the contrary, I expect to see them, instead they are not there

> I thought about it, but I don't think so, once the filters are available in the folder they are loaded regardless of the update, and the patch just downloads, it doesn't do anything else you know

unless there is some singleton that is not initialized, I'll check

**Comment by csagan5** [comment]
@uazo I have simplified the adblock patch a bit; will release it with next v88 release

**Comment by danieljarolim** [comment]
[logcat-2021-02-28_22-18.log](https://github.com/bromite/bromite/files/6056714/logcat-2021-02-28_22-18.log)

Logcat attached from the point where I uninstalled and reinstalled Bromite, checked that filters updated at 22:16:17 and browsed to website.

**Comment by uazo** [comment]
> I just noticed this from build .185 downloaded 2405327 bytes compared to 0 bytes downloaded for build .187

thanks, very useful, I check if it's a simple logging problem.

@csagan5  I noticed this: 
https://source.chromium.org/chromium/chromium/src/+/a0da2cf9bdc485ae384d409627eb34612cc27cc3:components/subresource_filter/core/common/indexed_ruleset.cc;l=55;bpv=1;bpt=1

`kIndexedFormatVersion` there has been a version increase? the patch must take this into account and today it does not.
do you understand if the generation of the filter.dat is also consistent with that number?

**Comment by uazo** [comment]
@csagan5 sorry, forget it

```
  // The version of the ruleset contents. Because the wire format of unindexed
  // rules is expected to be stable over time (at least backwards compatible),
  // the unindexed ruleset is uniquely identified by its content version.
```

**Comment by csagan5** [comment]
> thanks, very useful, I check if it's a simple logging problem.

`0 bytes downloaded` means that the update was not necessary, it is normal for HEAD requests

>   // The version of the ruleset contents. Because the wire format of unindexed
>   // rules is expected to be stable over time (at least backwards compatible),
>   // the unindexed ruleset is uniquely identified by its content version.

Yes, it's all protobuf bytes, there is no version there.

@uazo I have pushed the updated patch, you can see my changes there; it will now always perform the update check when users asks for it.

Release will take longer as the build is still ongoing.

**Comment by uazo** [comment]
@csagan5 II think I understand the bug.
can you remove this line in the build you are doing?
https://github.com/bromite/bromite/blob/master/build/patches/Bromite-AdBlockUpdaterService.patch#L1810

**Comment by uazo** [comment]
my fault.
I thought I was doing a right thing, instead the file downloaded in the temp is deleted!

**Comment by uazo** [comment]
sorry this https://github.com/bromite/bromite/blob/master/build/patches/Bromite-AdBlockUpdaterService.patch#L1873 line

**Comment by csagan5** [comment]
Ok; I have been comparing your version of the patch with the original to try to spot differences but I did not notice this one.

**Comment by csagan5** [comment]
Now I see more differences; I will undo some changes. The log message was correct to say "fetching" because at that point only headers have been downloaded.

It is not necessary to reset anything because the file is deleted automatically when the object is destroyed.

**Comment by tegutistgut** [comment]
I also want to add, that the adblocking isn't as good as the Samsung Internet Browser or Firefox.

The main error I'm facing is, that the ads are blocked, but sometimes the blank space from the blocked as is still visible.

Regarding that, I have 1 question:
1. What is the best filter list? (Easylist, Adguard base filter, etc.) And why is there a standard/custom Bromite Filter list?

Thanks

**Comment by chromer030** [comment]
> the ads are blocked, but sometimes the blank space from the blocked as is still visible

Bromite needs a feature in ad-blocker to hide placeholders of blocked elements.

**Comment by uazo** [comment]
> It is not necessary to reset anything because the file is deleted automatically when the object is destroyed.

Yes, it is.

> I have simplified the adblock patch a bit

I'm sorry I could only check now.
I think you have removed too much: is it wanted? one of the things I maked is that the check no longer always occurs at the startup, but you have eliminated it and now the HEAD request is done at every startup.
do you plan to replace the missing parts in an upcoming release?

**Comment by csagan5** [comment]
> I think you have removed too much: is it wanted?

Yes. Simpler code usually means less bugs.

> one of the things I maked is that the check no longer always occurs at the startup, but you have eliminated it and now the HEAD request is done at every startup.
> do you plan to replace the missing parts in an upcoming release?

I was not aware of this feature; we should document it. It can be re-introduced.

**Comment by uazo** [comment]
> I was not aware of this feature; we should document it. It can be re-introduced.

from line:
https://github.com/bromite/bromite/commit/973ede4ad1e66a4d094f7077749cb18f00db6cee#diff-9eb63b4ae6c4647cff72de5d8e26d166df65d305fae1a323737d2d72d8a30bbfL1374

to line:
https://github.com/bromite/bromite/commit/973ede4ad1e66a4d094f7077749cb18f00db6cee#diff-9eb63b4ae6c4647cff72de5d8e26d166df65d305fae1a323737d2d72d8a30bbfL1404

exactly the part you removed.
it is not urgent, I open an issue and we will think about it later.

**Comment by uazo** [comment]
while porting bromite to 89, I found myself the same bug, i think i found why:

the problem is that the patch relies on the call to "GetMostRecentlyIndexedVersion" (see https://source.chromium.org/chromium/chromium/src/+/master:components/subresource_filter/content/browser/ruleset_service.cc;l=259;drc=aece1cc3ce2c6de9f37f30c336d5f42256b92333;bpv=1;bpt=0) which, however, is only the reading from the prefs, without a real control of what is present on disk:

![image](https://user-images.githubusercontent.com/29201891/109983752-681c6f80-7d03-11eb-9d1f-5a72e283a980.png)
240 bytes, instead of 4.27MB!

even the installation, if the version is the same, refuses to continue:

```
  // Trying to store a ruleset with the same version for a second time would
  // not only be futile, but would fail on Windows due to "File System
  // Tunneling" as long as the previously stored copy of the rules is still
  // in use.
```
https://source.chromium.org/chromium/chromium/src/+/master:components/subresource_filter/content/browser/ruleset_service.cc;l=239

**Comment by uazo** [comment]
@csagan5  I have made some changes that fix (hopefully) this problem:
https://github.com/bromite/bromite/pull/956/commits/7edf804bd385974408ebbad6351f45d8ad5ebe30 the patch ready for 89

**Comment by chromer030** [comment]
@uazo , as you mentioned before, adblocker has some issues on Desktop mode, please consider fix for it.
