### ISSUE TITLE
Display Mobile and Desktop mode User Agent strings

### ISSUE THREAD

**Issue by SumatraPeter** [bromite/bromite#962]
> Have you searched the issue tracker? https://github.com/bromite/bromite/issues
> Have you read the F.A.Q.s? https://github.com/bromite/bromite/blob/master/FAQ.md
> Have you read the README? https://github.com/bromite/bromite/blob/master/README.md
> Have you read the Wiki? https://github.com/bromite/bromite/wiki

Yes, but this feature (request) doesn't seem to be mentioned anywhere.

> ### Is your feature request related to privacy?

Yes, it is a minor extension to an existing privacy-related feature.

> ### Is there a patch available for this feature somewhere?

I have no idea TBH.

> ### Describe the solution you would like

It would be nice if the standard Mobile and Desktop mode User Agent strings are displayed on the Customize User Agent settings page, preferably in a manner so that they can be copied to the clipboard easily (for example to paste in the custom settings fields for subsequent editing).

> ### Describe alternatives you have considered

The request is simply for two existing internal UA strings to be displayed, so I don't know of any alternative.

**Comment by SumatraPeter** [comment]
So... Thoughts @csagan5 and any other contributors?

**Comment by uazo** [comment]
nothing impossible, but I personally would like a features freeze until we have a reasonable certainty of having good troubleshooting

**Comment by csagan5** [comment]
There is no need for this feature.
