### ISSUE TITLE
Adblock updater does not have to make a request at each app cold start

### ISSUE THREAD

**Issue by uazo** [bromite/bromite#967]
### Is your feature request related to privacy?

Yes.

### Is there a patch available for this feature somewhere?

Yes.

from line:
973ede4#diff-9eb63b4ae6c4647cff72de5d8e26d166df65d305fae1a323737d2d72d8a30bbfL1374
to line:
973ede4#diff-9eb63b4ae6c4647cff72de5d8e26d166df65d305fae1a323737d2d72d8a30bbfL1404

### Describe the solution you would like

I would like the adblock updater not to make a head request to github every time bromite starts.

### Describe alternatives you have considered

reintroduce this function, with low priority.

**Comment by csagan5** [comment]
This new request happens only when you close the app using the Exit menu or the relative Android function, not every time you open the app, since it is already running in those cases.

**Comment by uazo** [comment]
> not every time you open the app, since it is already running in those cases.

I use always incognito.
for me always closing bromite is important, since it is a quick way to clear all the cache.

**Comment by csagan5** [comment]
This update has been in place so that after every new release of the browsers users will get the latest filters; by removing the initial request I expect that more users will submit issues due to outdated filters.

**Comment by csagan5** [comment]
Fixed in `89.0.4389.78`.
