### ISSUE TITLE
Update details about Brave's adblock engine

### ISSUE THREAD

**Issue by pes10k** [bromite/bromite#968]
Howdy! Just a very small request. The [AdBlock wiki page](https://github.com/bromite/bromite/wiki/AdBlocking) has outdated information and links about Brave's adblock engine.

Brave currently uses our own, open source, rust lib, [adblock-rust](https://github.com/brave/adblock-rust), which also has a [node / js version](https://www.npmjs.com/package/adblock-rs).

If you wouldn't mind updating the details on your wiki page, to avoid confusion, i'd greatly appreciate it.

Thanks much!

**Comment by csagan5** [comment]
Fixed.

**Comment by pes10k** [comment]
Thanks very much!
