### ISSUE TITLE
New Display-Capture Feature Policy in v89

### ISSUE THREAD

**Issue by uazo** [bromite/bromite#972]
### Is your feature request related to privacy?

I don't know. This issue is only a remind

### Is there a patch available for this feature somewhere?

No

### Describe the solution you would like

I've seen a new content settings, actually under a flag.
probably, like other content settings, it should be locked by default.
Code is https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/display_capture/display_capture_permission_context.cc

### Describe alternatives you have considered

None

**Comment by csagan5** [comment]
Can you do some investigation on the related upstream issues for this? I wonder how this works

**Comment by uazo** [comment]
this is the pr:
https://source.chromium.org/chromium/chromium/src/+/bc949e9d94ea6496b15153f5486a12608db7152b
