### ISSUE TITLE
Specific search engine not appearing

### ISSUE THREAD

**Issue by l4jos** [bromite/bromite#977]
Hi,

I am using the latest version of bromite and I want to use startpage.com as default search engine. I am making a search query and it should appear somewhere to make it default (as told in the documentation), but it does not. This search engine is a must for me, but I prefer not to switch to firefox for this reason.

![Screenshot_20210306-144821_Bromite](https://user-images.githubusercontent.com/52865939/110209464-1142a180-7e8d-11eb-89eb-6f9c6315f2c6.png)
![Screenshot_20210306-144830_Bromite](https://user-images.githubusercontent.com/52865939/110209473-17388280-7e8d-11eb-8248-a0dbd2ad1bbd.png)
![Screenshot_20210306-144923_Bromite](https://user-images.githubusercontent.com/52865939/110209476-1b64a000-7e8d-11eb-8b28-df0c6855e8fc.png)
![Screenshot_20210306-150342_Bromite](https://user-images.githubusercontent.com/52865939/110209486-28818f00-7e8d-11eb-9e09-03f18fab31c2.png)

**Comment by csagan5** [comment]
This is not a Bromite issue; please search for existing issue before creating a new one; thanks!

**Comment by l4jos** [comment]
Then, where else can I reproduce this issue?

**Comment by l4jos** [comment]
Where else? Are you sure this is not a part of?

**Comment by sorryusernameisalreadytaken** [comment]
You can add startpage.com, see [here](https://github.com/bromite/bromite/issues/435#issuecomment-1007228859).
