### ISSUE TITLE
DOMException: Failed to construct 'WebSocket': Access to this address is not allowed.

### ISSUE THREAD

**Issue by epma01** [bromite/bromite#980]
### Bromite version

Version: `88.0.4324.207`
Arch: `arm64` and `x86_64`
Android version: 8.0.0 and 11
Device model: SH-Z01 and sdk_gphone_x86_64

### Is this bug about the SystemWebView?
No, but SystemWebView version makes the same.

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No, Chromium 88.0.4324.207 works perfectly.

### Describe the bug

Bromite gives exception `DOMException: Failed to construct 'WebSocket': Access to this address is not allowed.` when trying to access a home-assistant server by a public address. With other browsers access works correctly.

Same issue as ##822, closed and marked off-topic, but the test Chromium ok / Bromite ko suggest bromite code issue

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to public home-assistan server address
2. Write user and password to log into server
3. home-assistant show "Unable to connect to Home Assistant" and bromite devtool console shows `DOMException: Failed to construct 'WebSocket': Access to this address is not allowed.`

### Expected behavior

Expected correct login and access to home-assistant server

### Screenshots
![ha](https://user-images.githubusercontent.com/49983490/110257559-b4371080-7f9e-11eb-8030-4daf95579819.jpg)
![exception](https://user-images.githubusercontent.com/49983490/110257567-b600d400-7f9e-11eb-8174-fe39ba3ea1f1.JPG)

**Comment by wchen342** [comment]
Is that domain pointing to your home address? Then you are probably connecing using LAN ip, redirected by your router somehow.

**Comment by epma01** [comment]
domain points to public ip address.

![ping](https://user-images.githubusercontent.com/49983490/110259449-e862ff00-7fa7-11eb-99d0-83ac65e1d28a.jpg)

It is an alias to a freedns dynamic dns, both on lan as on internet. Using public mobile 3g connection bromite gives the same error.

**Comment by csagan5** [comment]
> Same issue as ##822, closed and marked off-topic, but the test Chromium ok / Bromite ko suggest bromite code issue

It is not a Bromite issue; it is a security feature and it is working as intended; see also https://blog.nem.ec/2020/05/24/ebay-port-scanning/

The patch is [Block-gateway-attacks-via-websockets.patch](https://github.com/bromite/bromite/blob/88.0.4324.207/build/patches/Block-gateway-attacks-via-websockets.patch). That is the IP address of your internet gateway.

Please stop spamming the issue tracker; perhaps one day Chromium will have support of a content setting to control this, until that Bromite will keep current behaviour.

**Comment by epma01** [comment]
Article from ebay port scanning are websocket conections in a private lan to se same device (127.0.0.1) and probably your patch code is intented to extend this to any private lan device.

The blocked connection I exposed here, is a websocket connection to a public IP addess 88.9.x.x/16

I think this can't be the expected behabiour, you are blocking websocket connections to public IP addresses, and more where they points to the same domain of the browser url.

But if the second issue you close, so I am not going to try to find where is the bug with your code, be happy with your current behabiour, I will sell my soul to chrome, bye bye bromite. I'am a spammer and you didn't know what a public IP address is.

**Comment by danielehrhardt** [comment]
> But if the second issue you close, so

Did you ever find a Solution. I am having the same Issue. The WebSocket Connection is blocked without any reason.

**Comment by csagan5** [comment]
The discussion can continue on #1189
