### ISSUE TITLE
Video player does not load

### ISSUE THREAD

**Issue by oliveconstant** [bromite/bromite#982]
### Bromite version

Version: `88.0.4324.207`
Arch: `arm64`
Android version: `8.1.0`
Device model: `LG-H791`

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is the bug a crash?

No

### Describe the bug

The BBC video player does not load, e.g.: https://www.bbc.com/news/av/world-55415763. I don't know if the issue affects other websites/web players as well.

### Steps to reproduce the bug

1. Go to https://www.bbc.com/news/av/world-55415763
2. The video player does not load (see screenshot below)

<img src="https://user-images.githubusercontent.com/77325055/110309343-83d48e00-8001-11eb-89a7-0799104c2e0d.png" width="300">

### Expected behavior

The video player showing a button to start playback should load (see screenshot below).

<img src="https://user-images.githubusercontent.com/77325055/110309335-833bf780-8001-11eb-8bed-8e3cc69cde97.png" width="300">

**Comment by csagan5** [comment]
It is a problem in EasyList; they have already fixed it. It will be fixed in Bromite next time filters are updated.
