### ISSUE TITLE
"Enable save-data header" flag is missing from Bromite 89.0.4389.78

### ISSUE THREAD

**Issue by bat999** [bromite/bromite#989]
### Bromite version

Version: 89.0.4389.78
Arch: arm
Android version: 8.1.0
Device model: Xiaomi Redmi Go

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No, the feature is not available for Chromium

### Allow ads for the site; is the bug caused by the adblocker?
This section is not applicable for the bug.

### Is the bug a crash?
No

### Describe the bug
"Enable save-data header" flag is missing from Bromite 89.0.4389.78

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to chrome://flags
2. Look for save-data-header
3. It's not there.

### Expected behavior
The save-data-header flag was there in Bromite 88.0.4324.207
But it's missing from Bromite 89.0.4389.78

**Comment by csagan5** [comment]
Fixed in `89.0.4389.92`.
