### ISSUE TITLE
Download location not configurable anymore

### ISSUE THREAD

**Issue by Master0ne** [bromite/bromite#996]
### Bromite version
Version: `89.0.4389.78`
Arch: `arm64`
Android version: `11.0`
Device model: `POCO X3 NFC (surya)`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
Unknown

### Allow ads for the site; is the bug caused by the adblocker?
No

### Is the bug a crash?
No

### Describe the bug
`Settings` >> `Downloads` >> `Download location` only shows the file system path, but it can not be changed anymore. When clicking on it, a popup comes up that shows the download folder with the free space available and a `Done` button, but no possibility to actually change the download location.

This also makes the option `Ask where to save files` useless, because when activated, in the popup for downloading a file it is also not possible to change the download location.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to `Settings` >> `Downloads` and try to change the `Download location`.
2. Activate `Ask where to save files` in that settings menu and try to change the download location when downloading any file.

### Expected behavior
The default download location should be configurable in the settings menu, as well as individually when having the option `Ask where to save files` activated.

### Screenshots
![Download settings menu](https://user-images.githubusercontent.com/8912853/110574677-e2168380-815d-11eb-8718-dd5f0cf93ce6.jpg)

When clicking on the `Download location` section the following popup comes up, which does not offer to make any changes (the same goes for the popup when downloading a file with `Ask where to save files` activated):

![Download location option](https://user-images.githubusercontent.com/8912853/110574849-2ace3c80-815e-11eb-85c3-53d0e6df4918.jpg)

**Comment by csagan5** [comment]
@thestinger @uazo is it theoretically possible on A11 to let user choose between internal and external SD, like on A10?

Related: #831

![Screenshot_1615642311](https://user-images.githubusercontent.com/32685696/111031648-e3b7a400-8408-11eb-9822-792338de923f.png)

**Comment by thestinger** [comment]
It's possible to let the user choose *any* directory including a cloud storage provider, etc. if this used the SAF APIs.

**Comment by thestinger** [comment]
It's possible to let the user choose any directory in the profile home directory, external storage or another storage provider such as a cloud storage directory provided by an app, etc. if this used the SAF APIs.

**Comment by thestinger** [comment]
It's possible to let the user choose any directory in the profile home directory, an external storage device or another storage provider such as a cloud storage directory provided by an app, etc. if this used the SAF APIs.

**Comment by uazo** [comment]
yes, even in my opinion
i am currently working on https://github.com/bromite/bromite/issues/831 and slowly I understand a little more about saf and file permissions.

> It's possible to let the user choose any directory in the profile home directory, external storage or another storage provider such as a cloud storage directory provided by an app, etc. if this used the SAF APIs.

two or three limitations here and there, and something I still can't get to work easily... and the documentation doesn't help at all.
if i get stuck i will ask for your help

**Comment by csagan5** [comment]
@Master0ne do you have an SD card?

**Comment by Master0ne** [comment]
@csagan5 no, my POCO X3 NFC only has internal storage (though it has a hybrid SIM/SDcard slot, but that's occupied by a SIM).

**Comment by csagan5** [comment]
It is not a bug in Bromite; Chromium does not have this functionality anymore in A11, you can only choose between internal storage and external storage.
