### ISSUE TITLE
arm64 webview version with 32bit running

### ISSUE THREAD

**Issue by Jacky486** [bromite/bromite#997]
### Bromite version

Version: `latest`
Arch: `arm64`
Android version: (example: `11.0`)

### Is this bug about the SystemWebView?
Yes

### Is the bug reproducible with latest version?
yes

### Can the bug be reproduced with corresponding Chromium version?
yes

### Allow ads for the site; is the bug caused by the adblocker?
No

### Is the bug a crash?
no

### Describe the bug

change android:use32bitAbi="true" to false

### Steps to reproduce the bug

none

### Expected behavior

arm64 version running arm64 so

**Comment by csagan5** [comment]
Related: https://bugs.chromium.org/p/chromium/issues/detail?id=781095

It was disabled in version `80.0.3987.78` because I thought that upstream had already disabled it; will reintroduce it in next release.

**Comment by csagan5** [comment]
Fixed in `89.0.4389.92`.
